Cordio: STACK_HCI_OPT_API
STACK_HCI_OPT_API
HCI Optimization Interface Functions
This is an optimized interface for certain HCI commands that simply read a value. The stack uses these functions rather than their corresponding functions in the command interface. These functions can only be called after the reset sequence has been completed.
uint8_t * HciGetBdAddr (void)
uint8_t HciGetWhiteListSize (void)
int8_t HciGetAdvTxPwr (void)
uint16_t HciGetBufSize (void)
uint8_t HciGetNumBufs (void)
uint8_t * HciGetSupStates (void)
uint64_t HciGetLeSupFeat (void)
uint32_t HciGetLeSupFeat32 (void)
uint16_t HciGetMaxRxAclLen (void)
uint8_t HciGetResolvingListSize (void)
bool_t HciLlPrivacySupported (void)
uint16_t HciGetMaxAdvDataLen (void)
uint8_t HciGetNumSupAdvSets (void)
bool_t HciLeAdvExtSupported (void)
uint8_t HciGetPerAdvListSize (void)
hciLocalVerInfo_t * HciGetLocalVerInfo (void)
Detailed Description
Function Documentation
HciGetAdvTxPwr()
int8_t HciGetAdvTxPwr (void)
Return the advertising transmit power.
Returns
Advertising transmit power.
References hciCoreCb_t::advTxPwr, and LlGetAdvTxPower().
HciGetBdAddr()
uint8_t* HciGetBdAddr (void)
Return a pointer to the BD address of this device.
Returns
Pointer to the BD address.
References hciCoreCb_t::bdAddr.
HciGetBufSize()
uint16_t HciGetBufSize (void)
Return the ACL buffer size supported by the controller.
Returns
ACL buffer size.
References hciCoreCb_t::bufSize.
HciGetLeSupFeat()
uint64_t HciGetLeSupFeat (void)
Return the LE supported features supported by the controller.
Returns
Supported features.
References BYTES_TO_UINT64, HCI_LE_STATES_LEN, hciCoreCb_t::leSupFeat, and LlGetFeatures().
HciGetLeSupFeat32()
uint32_t HciGetLeSupFeat32 (void)
Return the LE supported features supported by the controller.
Returns
Supported features.
References BYTES_TO_UINT32, HCI_LE_STATES_LEN, hciCoreCb_t::leSupFeat, and LlGetFeatures().
HciGetLocalVerInfo()
hciLocalVerInfo_t* HciGetLocalVerInfo (void)
Return a pointer to the local version information.
Returns
Pointer to the local version information.
References hciCoreCb_t::locVerInfo.
HciGetMaxAdvDataLen()
uint16_t HciGetMaxAdvDataLen (void)
Get the maximum advertisement (or scan response) data length supported by the Controller.
Returns
Maximum advertisement data length.
References hciCoreCb_t::maxAdvDataLen.
HciGetMaxRxAclLen()
uint16_t HciGetMaxRxAclLen (void)
Get the maximum reassembled RX ACL packet length.
Returns
ACL packet length.
References hciCoreCb_t::maxRxAclLen.
HciGetNumBufs()
uint8_t HciGetNumBufs (void)
Return the number of ACL buffers supported by the controller.
Returns
Number of ACL buffers.
References hciCoreCb_t::numBufs.
HciGetNumSupAdvSets()
uint8_t HciGetNumSupAdvSets (void)
Get the maximum number of advertising sets supported by the Controller.
Returns
Maximum number of advertising sets.
References hciCoreCb_t::numSupAdvSets.
HciGetPerAdvListSize()
uint8_t HciGetPerAdvListSize (void)
Return the periodic advertising list size.
Returns
periodic advertising list size.
References hciCoreCb_t::perAdvListSize.
HciGetResolvingListSize()
uint8_t HciGetResolvingListSize (void)
Return the resolving list size.
Returns
resolving list size.
References hciCoreCb_t::resListSize.
HciGetSupStates()
uint8_t* HciGetSupStates (void)
Return the states supported by the controller.
Returns
Pointer to the supported states array.
References hciCoreCb_t::leStates, and LlGetSupStates().
HciGetWhiteListSize()
uint8_t HciGetWhiteListSize (void)
Return the white list size.
Returns
White list size.
References LlGetWhitelistSize(), and hciCoreCb_t::whiteListSize.
HciLeAdvExtSupported()
bool_t HciLeAdvExtSupported (void)
Whether LE Advertising Extensions is supported.
Returns
TRUE if LE Advertising Extensions is supported. FALSE, otherwise.
HciLlPrivacySupported()
bool_t HciLlPrivacySupported (void)
Whether LL Privacy is supported.
Returns
TRUE if LL Privacy is supported. FALSE, otherwise.