Cordio: STACK_HCI_ACL_API
STACK_HCI_ACL_API
Typedefs
typedef void(* hciAclCback_t) (uint8_t *pData)
typedef void(* hciIsoCback_t) (uint8_t *pData)
typedef void(* hciFlowCback_t) (uint16_t handle, bool_t flowDisabled)
HCI ACL Data Functions
HCI ACL data interface
void HciSendAclData (uint8_t *pAclData)
Detailed Description
Typedef Documentation
hciAclCback_t
typedef void(* hciAclCback_t) (uint8_t *pData)
HCI ACL callback type.
This callback function sends ACL data from HCI to the stack.
Parameters
pData WSF buffer containing an ACL packet.
Returns
None.
hciFlowCback_t
typedef void(* hciFlowCback_t) (uint16_t handle, bool_t flowDisabled)
HCI flow control callback type.
This callback function manages flow control in the TX path betrween the stack and HCI.
Parameters
connId Connection handle.
flowDisabled TRUE if flow is disabled.
Returns
None.
hciIsoCback_t
typedef void(* hciIsoCback_t) (uint8_t *pData)
HCI ISO callback type.
This callback function sends ISO data from HCI to the stack.
Parameters
pData WSF buffer containing an ISO packet.
Returns
None.
Function Documentation
HciSendAclData()
void HciSendAclData (uint8_t * pData)
Send ACL Data from the stack to HCI.
Parameters
pAclData WSF buffer containing an ACL packet.
Returns
None.
Send ACL Data from the stack to HCI.
Parameters
pData WSF buffer containing an ACL packet
Returns
None.
References hciCoreCb_t::aclQueue, hciCoreCb_t::aclQueueHi, hciCoreCb_t::availBufs, BYTES_TO_UINT16, hciCoreConn_t::flowDisabled, HciGetBufSize(), hciCoreConn_t::queuedBufs, WsfMsgEnq(), and WsfQueueEmpty().