Cordio: HEALTH_THERMOMETER_PROFILE
HEALTH_THERMOMETER_PROFILE
Data Structures
struct htpsCfg_t
Enumerations
enum
Functions
void HtpcHtsDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t HtpcHtsValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void HtpsInit (wsfHandlerId_t handlerId, htpsCfg_t *pCfg)
void HtpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t itCccIdx)
void HtpsMeasStop (void)
void HtpsMeasComplete (dmConnId_t connId, uint8_t tmCccIdx)
void HtpsProcMsg (wsfMsgHdr_t *pMsg)
void HtpsSetTmFlags (uint8_t flags)
void HtpsSetItFlags (uint8_t flags)
Detailed Description
Data Structure Documentation
htpsCfg_t
struct htpsCfg_t
Configurable parameters.
Data Fields
wsfTimerTicks_t period
Enumeration Type Documentation
anonymous enum
anonymous enum
Health Thermometer service enumeration of handle indexes of characteristics to be discovered.
Enumerator
HTPC_HTS_TM_HDL_IDX
Temperature measurement.
HTPC_HTS_TM_CCC_HDL_IDX
Temperature measurement CCC descriptor.
HTPC_HTS_IT_HDL_IDX
Intermediate temperature.
HTPC_HTS_IT_CCC_HDL_IDX
Intermediate temperature CCC descriptor.
HTPC_HTS_TT_HDL_IDX
Temperature type.
HTPC_HTS_HDL_LIST_LEN
Handle list length.
Function Documentation
HtpcHtsDiscover()
void HtpcHtsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Health Thermometer service. Parameter pHdlList must point to an array of length HTPC_HTS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Health Thermometer service. Parameter pHdlList must point to an array of length HTPC_HTS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attHtsSvcUuid, and HTPC_HTS_HDL_LIST_LEN.
HtpcHtsValueUpdate()
uint8_t HtpcHtsValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length HTPC_HTS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristc handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length HTPC_HTS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, attEvt_t::handle, HTPC_HTS_IT_HDL_IDX, HTPC_HTS_TM_HDL_IDX, HTPC_HTS_TT_HDL_IDX, attEvt_t::pValue, and attEvt_t::valueLen.
HtpsInit()
void HtpsInit (wsfHandlerId_t handlerId, htpsCfg_t * pCfg)
Initialize the Health Thermometer profile sensor.
Parameters
handlerId WSF handler ID of the application using this service.
pCfg Configurable parameters.
Returns
None.
Parameters
handerId WSF handler ID of the application using this service.
pCfg Configurable parameters.
Returns
None.
HtpsMeasComplete()
void HtpsMeasComplete (dmConnId_t connId, uint8_t tmCccIdx)
Temperature measurement complete.
Parameters
connId DM connection identifier.
tmCccIdx Index of temperature measurement CCC descriptor in CCC descriptor handle table.
Returns
None.
References AppHwTmRead(), ATT_DEFAULT_PAYLOAD_LEN, AttsCccEnabled(), and HtpsMeasStop().
HtpsMeasStart()
void HtpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t itCccIdx)
Start periodic temperature measurement. This function starts a timer to perform periodic measurements.
Parameters
connId DM connection identifier.
timerEvt WSF event designated by the application for the timer.
itCccIdx Index of intermediate temperature CCC descriptor in CCC descriptor handle table.
Returns
None.
References WsfTimerStartMs().
HtpsMeasStop()
void HtpsMeasStop (void)
Stop periodic temperature measurement.
Returns
None.
References WsfTimerStop().
HtpsProcMsg()
void HtpsProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when the periodic measurement timer expires.
Parameters
pMsg Event message.
Returns
None.
References AppHwTmRead(), ATT_DEFAULT_PAYLOAD_LEN, AttsCccEnabled(), wsfMsgHdr_t::param, and wsfMsgHdr_t::status.
HtpsSetItFlags()
void HtpsSetItFlags (uint8_t flags)
Set the intermediate temperature flags.
Parameters
flags Intermediate temperature flags.
Returns
None.
HtpsSetTmFlags()
void HtpsSetTmFlags (uint8_t flags)
Set the temperature measurement flags.
Parameters
flags Temperature measurement flags.
Returns
None.