Cordio: GLUCOSE_PROFILE
GLUCOSE_PROFILE
Data Structures
struct glpcFilter_t
struct glpsGlm_t
struct glpsGlmc_t
struct glpsRec_t
Macros
#define GLP_ALL_SUPPORTED_FEATURES 0x000F
#define GLPS_RACP_MIN_WRITE_LEN 2
#define GLPS_RACP_RSP_LEN 4
#define GLPS_RACP_NUM_REC_RSP_LEN 4
#define GLPS_OPERAND_MAX ((CH_RACP_GLS_FILTER_TIME_LEN * 2) + 1)
Enumerations
enum
Functions
void GlpcGlsDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t GlpcGlsValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void GlpcGlsRacpSend (dmConnId_t connId, uint16_t handle, uint8_t opcode, uint8_t oper, glpcFilter_t *pFilter)
void GlpcGlsSetLastSeqNum (uint16_t seqNum)
uint16_t GlpcGlsGetLastSeqNum (void)
void GlpsInit (void)
void GlpsProcMsg (wsfMsgHdr_t *pMsg)
void GlpsBtn (dmConnId_t connId, uint8_t btn)
uint8_t GlpsRacpWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
void GlpsSetFeature (uint16_t feature)
void GlpsSetCccIdx (uint8_t glmCccIdx, uint8_t glmcCccIdx, uint8_t racpCccIdx)
void glpsDbInit (void)
uint8_t glpsDbGetNextRecord (uint8_t oper, uint8_t *pFilter, glpsRec_t *pCurrRec, glpsRec_t **pRec)
uint8_t glpsDbDeleteRecords (uint8_t oper, uint8_t *pFilter)
uint8_t glpsDbGetNumRecords (uint8_t oper, uint8_t *pFilter, uint8_t *pNumRec)
void glpsDbGenerateRecord (void)
void glpsDbToggleMedicationUnits (void)
Detailed Description
Data Structure Documentation
glpcFilter_t
struct glpcFilter_t
Glucose service RACP filter type.
Data Fields
union {
uint16_t seqNum
} param
uint8_t type
glpsGlm_t
struct glpsGlm_t
Glucose measurement structure.
Data Fields
uint8_t flags
uint16_t seqNum
appDateTime_t baseTime
int16_t timeOffset
uint16_t concentration
uint8_t typeSampleLoc
uint16_t sensorStatus
glpsGlmc_t
struct glpsGlmc_t
Glucose measurement context structure.
Data Fields
uint8_t flags
uint16_t seqNum
uint8_t extFlags
uint8_t carbId
uint16_t carb
uint8_t meal
uint8_t testerHealth
uint16_t exerDuration
uint8_t exerIntensity
uint8_t medicationId
uint16_t medication
uint16_t hba1c
glpsRec_t
struct glpsRec_t
Glucose measurement record.
Data Fields
glpsGlm_t meas
glpsGlmc_t context
Enumeration Type Documentation
anonymous enum
anonymous enum
Glucose service enumeration of handle indexes of characteristics to be discovered.
Enumerator
GLPC_GLS_GLM_HDL_IDX
Glucose measurement.
GLPC_GLS_GLM_CCC_HDL_IDX
Glucose measurement CCC descriptor.
GLPC_GLS_GLMC_HDL_IDX
Glucose measurement context.
GLPC_GLS_GLMC_CCC_HDL_IDX
Glucose measurement context CCC descriptor.
GLPC_GLS_GLF_HDL_IDX
Glucose feature.
GLPC_GLS_RACP_HDL_IDX
Record access control point.
GLPC_GLS_RACP_CCC_HDL_IDX
Record access control point CCC descriptor.
GLPC_GLS_HDL_LIST_LEN
Handle list length.
Function Documentation
GlpcGlsDiscover()
void GlpcGlsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Glucose service. Parameter pHdlList must point to an array of length GLPC_GLS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Glucose service. Parameter pHdlList must point to an array of length GLPC_GLS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attGlsSvcUuid, and GLPC_GLS_HDL_LIST_LEN.
GlpcGlsGetLastSeqNum()
uint16_t GlpcGlsGetLastSeqNum (void)
Get the last received glucose measurement sequence number.
Returns
Last received glucose measurement sequence number.
GlpcGlsRacpSend()
void GlpcGlsRacpSend (dmConnId_t connId, uint16_t handle, uint8_t opcode, uint8_t oper, glpcFilter_t * pFilter)
Send a command to the glucose service record access control point.
Parameters
connId Connection identifier.
handle Attribute handle.
opcode Command opcode.
oper Command operator or 0 if no operator required.
pFilter Command filter parameters or NULL of no parameters required.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, AttcWriteReq(), CH_RACP_GLS_FILTER_SEQ, glpcFilter_t::param, glpcFilter_t::seqNum, glpcFilter_t::type, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
GlpcGlsSetLastSeqNum()
void GlpcGlsSetLastSeqNum (uint16_t seqNum)
Set the last received glucose measurement sequence number.
Parameters
seqNum Glucose measurement sequence number.
Returns
None.
GlpcGlsValueUpdate()
uint8_t GlpcGlsValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length GLPC_GLS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length GLPC_GLS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, BSTREAM_TO_UINT16, GLPC_GLS_GLF_HDL_IDX, GLPC_GLS_GLM_HDL_IDX, GLPC_GLS_GLMC_HDL_IDX, GLPC_GLS_RACP_HDL_IDX, attEvt_t::handle, attEvt_t::pValue, and attEvt_t::valueLen.
GlpsBtn()
void GlpsBtn (dmConnId_t connId, uint8_t btn)
Handle a button press.
Parameters
connId Connection identifier.
btn Button press.
Returns
None.
References APP_UI_BTN_2_EX_LONG, APP_UI_BTN_2_LONG, APP_UI_BTN_2_MED, APP_UI_BTN_2_SHORT, CH_RACP_OPERATOR_ALL, DM_CONN_ID_NONE, glpsDbDeleteRecords(), glpsDbGenerateRecord(), and glpsDbToggleMedicationUnits().
glpsDbDeleteRecords()
uint8_t glpsDbDeleteRecords (uint8_t oper, uint8_t * pFilter)
Delete records that match the given filter parameters.
Parameters
oper Operator.
pFilter Glucose service RACP filter parameters.
Returns
CH_RACP_RSP_SUCCESS if records deleted, otherwise an error status is returned.
Parameters
oper Operator.
pFilter Glucose service RACP filter parameters.
Returns
CH_RACP_RSP_SUCCESS if records deleted, otherwise an error status is returned.
References CH_RACP_OPERATOR_ALL, CH_RACP_RSP_OPERATOR_NOT_SUP, and CH_RACP_RSP_SUCCESS.
glpsDbGenerateRecord()
void glpsDbGenerateRecord (void)
Generate a new record.
Returns
None.
glpsDbGetNextRecord()
uint8_t glpsDbGetNextRecord (uint8_t oper, uint8_t * pFilter, glpsRec_t * pCurrRec, glpsRec_t ** pRec)
Get the next record that matches the given filter parameters that follows the given current record.
Parameters
oper Operator.
pFilter Glucose service RACP filter parameters.
pCurrRec Pointer to current record.
pRec Return pointer to next record, if found.
Returns
CH_RACP_RSP_SUCCESS if a record is found, otherwise an error status is returned.
Parameters
oper Operator.
pFilter Glucose service RACP filter parameters.
pCurrRec Pointer to current record.
pRec Return pointer to next record, if found.
Returns
CH_RACP_RSP_SUCCESS if a record is found, otherwise an error status is returned.
References CH_RACP_GLS_FILTER_SEQ, CH_RACP_OPERATOR_ALL, CH_RACP_OPERATOR_GTEQ, CH_RACP_OPERATOR_LAST, CH_RACP_OPERATOR_NULL, CH_RACP_RSP_INV_OPERATOR, CH_RACP_RSP_OPERAND_NOT_SUP, and CH_RACP_RSP_OPERATOR_NOT_SUP.
glpsDbGetNumRecords()
uint8_t glpsDbGetNumRecords (uint8_t oper, uint8_t * pFilter, uint8_t * pNumRec)
Get the number of records matching the filter parameters.
Parameters
oper Operator.
pFilter Glucose service RACP filter parameters.
pNumRec Returns number of records which match filter parameters.
Returns
RACP status.
References CH_RACP_RSP_NO_RECORDS, CH_RACP_RSP_SUCCESS, and glpsDbGetNextRecord().
glpsDbInit()
void glpsDbInit (void)
Initialize the glucose record database.
Returns
None.
glpsDbToggleMedicationUnits()
void glpsDbToggleMedicationUnits (void)
For conformance testing only. Toggle the sample data record number 2's medication quantity unit flag between Kilograms and Liters. Also modifies quantity.
Returns
None.
References CH_GLMC_FLAG_MED_KG, CH_GLMC_FLAG_MED_L, glpsRec_t::context, glpsGlmc_t::flags, glpsGlmc_t::medication, and SFLT_TO_UINT16.
GlpsInit()
GlpsInit (void)
Initialize the Glucose profile sensor.
Returns
None.
References glpsDbInit().
GlpsProcMsg()
void GlpsProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when a message that requires processing by the glucose profile sensor is received.
Parameters
pMsg Event message.
Returns
None.
References ATTS_HANDLE_VALUE_CNF, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
GlpsRacpWriteCback()
uint8_t GlpsRacpWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
ATTS write callback for glucose service record access control point. Use this function as a parameter to SvcGlsCbackRegister().
Parameters
connId DM connection identifier.
handle ATT handle.
operation ATT operation.
offset Write offset.
len Write length.
pValue Value to write.
pAttr Attribute to write.
Returns
ATT status.
ATT status.
References ATT_ERR_LENGTH, AttsCccEnabled(), BSTREAM_TO_UINT8, CH_RACP_OPCODE_ABORT, CH_RACP_OPCODE_DELETE, CH_RACP_OPCODE_REPORT, CH_RACP_OPCODE_REPORT_NUM, CH_RACP_RSP_OPCODE_NOT_SUP, CH_RACP_RSP_SUCCESS, GLPS_RACP_MIN_WRITE_LEN, GLS_ERR_CCCD, and GLS_ERR_IN_PROGRESS.
GlpsSetCccIdx()
void GlpsSetCccIdx (uint8_t glmCccIdx, uint8_t glmcCccIdx, uint8_t racpCccIdx)
Set the CCCD index used by the application for glucose service characteristics.
Parameters
glmCccIdx Glucose measurement CCCD index.
glmcCccIdx Glucose measurement context CCCD index.
racpCccIdx Record access control point CCCD index.
Returns
None.
GlpsSetFeature()
void GlpsSetFeature (uint16_t feature)
Set the supported features of the glucose sensor.
Parameters
feature Feature bitmask.
Returns
None.
References AttsSetAttr(), GLS_GLF_HDL, and UINT16_TO_BYTES.