Cordio: LL_API_DATA
LL_API_DATA
Functions
uint16_t LlGetAclMaxSize (void)
uint8_t LlGetAclTxBufs (void)
uint8_t LlGetAclRxBufs (void)
uint16_t LlGetIsoMaxBufSize (void)
uint8_t LlGetIsoTxBufs (void)
uint8_t LlGetIsoRxBufs (void)
uint8_t LlReadIsoLinkQual (uint16_t handle, LlIsoLinkQual_t *pStats)
void LlSendAclData (uint8_t *pData)
uint8_t * LlRecvAclData (void)
void LlRecvAclDataComplete (uint8_t numBufs)
Detailed Description
Function Documentation
LlGetAclMaxSize()
uint16_t LlGetAclMaxSize (void)
Get the maximum ACL buffers size.
Returns
Maximum buffers size in bytes.
References LlRtCfg_t::maxAclLen, and pLctrRtCfg.
LlGetAclRxBufs()
uint8_t LlGetAclRxBufs (void)
Get the number of buffers in the LL ACL receive queue.
Returns
Number of buffers.
References LlRtCfg_t::numRxBufs, and pLctrRtCfg.
LlGetAclTxBufs()
uint8_t LlGetAclTxBufs (void)
Get the number of buffers in the LL ACL transmit queue.
Returns
Number of buffers.
References LlRtCfg_t::numTxBufs, and pLctrRtCfg.
LlGetIsoMaxBufSize()
uint16_t LlGetIsoMaxBufSize (void)
Get the maximum ISO buffers size between host and controller.
Returns
Maximum buffers size in bytes.
Get the maximum ISO buffers size between host and controller.
Returns
Maximum buffers size in bytes.
References LlRtCfg_t::maxIsoSduLen, and pLctrRtCfg.
LlGetIsoRxBufs()
uint8_t LlGetIsoRxBufs (void)
Get the number of buffers in the LL ISO receive queue.
Returns
Number of buffers.
References LlRtCfg_t::numIsoRxBuf, and pLctrRtCfg.
LlGetIsoTxBufs()
uint8_t LlGetIsoTxBufs (void)
Get the number of buffers in the LL ISO transmit queue.
Returns
Number of buffers.
References LlRtCfg_t::numIsoTxBuf, and pLctrRtCfg.
LlReadIsoLinkQual()
uint8_t LlReadIsoLinkQual (uint16_t handle, LlIsoLinkQual_t * pStats)
Read ISO link Quality stats.
Parameters
handle connection handle.
pStats link quality statistics.
Returns
Status error code.
Parameters
handle connection handle.
Returns
Status error code.
LlRecvAclData()
uint8_t* LlRecvAclData (void)
Receive an ACL data packet.
Returns
Data buffer.
Receive an ACL data packet. If no ACL buffers are available this function returns NULL.
Note
The host must deallocate the buffer by calling WsfMsgFree() and call LlRecvBufCmpl() to update LL accounting.
Returns
Data buffer.
Receive an ACL data packet. This function returns a pointer to an ACL buffer formatted according to [1]. The host must parse the header to determine the connection handle, flags, and length fields. If no ACL buffers are available this function returns NULL.
The host must deallocate the buffer by calling WsfMsgFree() and then calling LlRecvAclDataComplete().
References LctrRxAcl().
LlRecvAclDataComplete()
void LlRecvAclDataComplete (uint8_t numBufs)
Indicate that received ACL data buffer has been deallocated.
Parameters
numBufs Number of completed packets.
Indicate that received ACL data buffer has been deallocated.
References LctrRxAclComplete().
LlSendAclData()
void LlSendAclData (uint8_t * pData)
Send an ACL data packet.
Parameters
pData Data buffer
Send an ACL data packet. pData points to an ACL buffer formatted according to [1]; the host must set the connection handle, flags, and length fields in the buffer.
References lmgrConnCtrlBlk_t::availTxBuf, LctrTxAcl(), lmgrConnCb, and WsfMsgFree().