Cordio: WIRELESS_DATA_EXCHANGE_PROFILE
WIRELESS_DATA_EXCHANGE_PROFILE
Data Structures
struct wdxcConnCb_t
struct wdxcCb_t
struct wdxsCb_t
struct wdxsDcCb_t
struct wdxsAuCb_t
union wdxsMsg_t
Macros
#define WDX_UUID_PART1
#define WDX_UUID_PART2 0x5f, 0x00
#define WDX_UUID_BUILD(part) WDX_UUID_PART1, UINT16_TO_BYTES(part), WDX_UUID_PART2
#define WDX_SVC_UUID 0xFEF6
#define WDX_DC_UUID WDX_UUID_BUILD(0x0002)
#define WDX_FTC_UUID WDX_UUID_BUILD(0x0003)
#define WDX_FTD_UUID WDX_UUID_BUILD(0x0004)
#define WDX_AU_UUID WDX_UUID_BUILD(0x0005)
#define WDX_DC_HDR_LEN 2
#define WDX_FTD_HDR_LEN 0
#define WDX_AU_HDR_LEN 1
#define WDXS_APP_RAM_MEDIA_SIZE 256
#define WDXS_DEVICE_MODEL "WDXS App"
#define WDXS_STREAM_FILE_LEN 0xFFFFFFFF
Typedefs
typedef void WdxcFtdCallback_t(dmConnId_t connId, uint16_t handle, uint16_t len, uint8_t *pData)
typedef void WdxcFtcCallback_t(dmConnId_t connId, uint16_t handle, uint8_t op, uint8_t status)
typedef uint8_t(* wdxsDcPhyWriteCback_t) (dmConnId_t connId, uint8_t op, uint8_t id, uint16_t len, uint8_t *pValue)
Enumerations
enum
Functions
void WdxcInit (WdxcFtdCallback_t *pFtdCallback, WdxcFtcCallback_t *pFtcCallback)
void WdxcProcMsg (wsfMsgHdr_t *pEvt)
void WdxcWdxsDiscover (dmConnId_t connId, uint16_t *pHdlList)
void WdxcDiscoverFiles (dmConnId_t connId, wsfEfsFileInfo_t *pFileInfo, uint8_t maxFiles)
void WdxcDcSendDisconnectAndReset (dmConnId_t connId)
void WdxcStreamStart (dmConnId_t connId, uint16_t fileHdl)
void WdxcStreamStop (dmConnId_t connId)
void WdxcFtcSendAbort (dmConnId_t connId, uint16_t fileHdl)
void WdxcFtcSendEraseFile (dmConnId_t connId, uint16_t fileHdl)
void WdxcFtcSendVerifyFile (dmConnId_t connId, uint16_t fileHdl)
void WdxcFtcSendPutReq (dmConnId_t connId, uint16_t fileHdl, uint32_t offset, uint32_t len, uint32_t fileSize, uint8_t type)
void WdxcFtcSendGetReq (dmConnId_t connId, uint16_t fileHdl, uint32_t offset, uint32_t len, uint8_t type)
void WdxcFtdSendBlock (dmConnId_t connId, uint32_t len, uint8_t *pData)
void WdxcStoreAttrHandles (dmConnId_t connId, uint16_t *pHdlList)
void WdxsAuthenticationCfg (bool_t reqLevel, uint8_t *pKey)
void WdxsHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
void WdxsHandlerInit (wsfHandlerId_t handlerId)
uint8_t WdxsAttCback (attEvt_t *pEvt)
void WdxsProcDmMsg (dmEvt_t *pEvt)
void WdxsSetCccIdx (uint8_t dcCccIdx, uint8_t auCccIdx, uint8_t ftcCccIdx, uint8_t ftdCccIdx)
void WdxsFlashMediaInit (void)
void WdxsOtaMediaInit (void)
void WdxsResetSystem (void)
void WdxsPhyInit (void)
void wdxsDcSend (dmConnId_t connId)
void wdxsFtcSend (dmConnId_t connId)
void wdxsFtcSendRsp (dmConnId_t connId, uint8_t op, uint16_t handle, uint8_t status)
void wdxsFtdSend (dmConnId_t connId)
void wdxsAuSend (dmConnId_t connId)
uint8_t wdxsDcWrite (dmConnId_t connId, uint16_t len, uint8_t *pValue)
uint8_t wdxsFtcWrite (dmConnId_t connId, uint16_t len, uint8_t *pValue)
uint8_t wdxsFtdWrite (dmConnId_t connId, uint16_t len, uint8_t *pValue)
uint8_t wdxsAuWrite (dmConnId_t connId, uint16_t len, uint8_t *pValue)
uint8_t wdxsDcUpdateConnParam (dmConnId_t connId, uint8_t status)
uint8_t wdxsDcUpdatePhy (dmConnId_t connId, uint8_t status)
void wdxsDcPhyRegister (wdxsDcPhyWriteCback_t cback)
void WdxsUpdateListing (void)
void wdxsStreamInit (void)
void wdxsSetStreamWaveform (uint8_t type)
WDXS File List Configuration
#define WDX_FLIST_HANDLE 0
#define WDX_FLIST_FORMAT_VER 1
#define WDX_FLIST_HDR_SIZE 7
#define WDX_FLIST_RECORD_SIZE 40
#define WDX_FLIST_MAX_LEN (WDX_FLIST_HDR_SIZE + (WDX_FLIST_RECORD_SIZE * (WSF_EFS_MAX_FILES-1)))
Device Configuration Characteristic oOperations
#define WDX_DC_OP_GET 0x01
#define WDX_DC_OP_SET 0x02
#define WDX_DC_OP_UPDATE 0x03
Device Control Characteristic Parameter IDs
#define WDX_DC_ID_CONN_UPDATE_REQ 0x01
#define WDX_DC_ID_CONN_PARAM 0x02
#define WDX_DC_ID_DISCONNECT_REQ 0x03
#define WDX_DC_ID_CONN_SEC_LEVEL 0x04
#define WDX_DC_ID_SECURITY_REQ 0x05
#define WDX_DC_ID_SERVICE_CHANGED 0x06
#define WDX_DC_ID_DELETE_BONDS 0x07
#define WDX_DC_ID_ATT_MTU 0x08
#define WDX_DC_ID_PHY_UPDATE_REQ 0x09
#define WDX_DC_ID_PHY 0x0A
#define WDX_DC_ID_BATTERY_LEVEL 0x20
#define WDX_DC_ID_MODEL_NUMBER 0x21
#define WDX_DC_ID_FIRMWARE_REV 0x22
#define WDX_DC_ID_ENTER_DIAGNOSTICS 0x23
#define WDX_DC_ID_DIAGNOSTICS_COMPLETE 0x24
#define WDX_DC_ID_DISCONNECT_AND_RESET 0x25
Device Control Parameter Lengths
#define WDX_DC_LEN_DATA_FORMAT 1
#define WDX_DC_LEN_SEC_LEVEL 1
#define WDX_DC_LEN_ATT_MTU 2
#define WDX_DC_LEN_BATTERY_LEVEL 1
#define WDX_DC_LEN_CONN_PARAM_REQ 8
#define WDX_DC_LEN_CONN_PARAM 7
#define WDX_DC_LEN_PHY_UPDATE_REQ 5
#define WDX_DC_LEN_PHY 3
#define WDX_DC_LEN_DIAG_COMPLETE 0
#define WDX_DC_LEN_DEVICE_MODEL 18
#define WDX_DC_LEN_FIRMWARE_REV 16
File Transfer Control Characteristic Message Header Length
#define WDX_FTC_HDR_LEN 1
#define WDX_FTC_HANDLE_LEN 2
File Transfer Control Characteristic Operations
#define WDX_FTC_OP_NONE 0x00
#define WDX_FTC_OP_GET_REQ 0x01
#define WDX_FTC_OP_GET_RSP 0x02
#define WDX_FTC_OP_PUT_REQ 0x03
#define WDX_FTC_OP_PUT_RSP 0x04
#define WDX_FTC_OP_ERASE_REQ 0x05
#define WDX_FTC_OP_ERASE_RSP 0x06
#define WDX_FTC_OP_VERIFY_REQ 0x07
#define WDX_FTC_OP_VERIFY_RSP 0x08
#define WDX_FTC_OP_ABORT 0x09
#define WDX_FTC_OP_EOF 0x0a
File Transfer Control Permissions
#define WDX_FTC_GET_PERMITTED 0x01
#define WDX_FTC_PUT_PERMITTED 0x02
#define WDX_FTC_ERASE_PERMITTED 0x04
#define WDX_FTC_VERIFY_PERMITTED 0x08
File Transfer Control Characteristic Status
#define WDX_FTC_ST_SUCCESS 0
#define WDX_FTC_ST_INVALID_OP_FILE 1
#define WDX_FTC_ST_INVALID_HANDLE 2
#define WDX_FTC_ST_INVALID_OP_DATA 3
#define WDX_FTC_ST_IN_PROGRESS 4
#define WDX_FTC_ST_VERIFICATION 5
File Transfer Control Transport
#define WDX_FTC_TRANSPORT_TYPE 0
#define WDX_FTC_TRANSPORT_ID 0x0030
Authentication Characteristic Operations
#define WDX_AU_OP_START 0x01
#define WDX_AU_OP_CHALLENGE 0x02
#define WDX_AU_OP_REPLY 0x03
Proprietary ATT Error Codes
#define WDX_APP_AUTH_REQUIRED 0x80
#define WDX_AU_ST_INVALID_MESSAGE 0x81
#define WDX_AU_ST_INVALID_STATE 0x82
#define WDX_AU_ST_AUTH_FAILED 0x83
Authentication Characteristic Authentication Level
#define WDX_AU_LVL_NONE 0x00
#define WDX_AU_LVL_USER 0x01
#define WDX_AU_LVL_MAINT 0x02
#define WDX_AU_LVL_DEBUG 0x03
Authenttication Characteristic Message Parameter Lengths
#define WDX_AU_MSG_HDR_LEN 1
#define WDX_AU_PARAM_LEN_START 2
#define WDX_AU_PARAM_LEN_CHALLENGE 16
#define WDX_AU_PARAM_LEN_REPLY 8
Authenttication Characteristic Random Number and Key Lengths
#define WDX_AU_RAND_LEN 16
#define WDX_AU_KEY_LEN 16
#define WDX_AU_HASH_LEN 8
WDXS Media Types
#define WDX_FLASH_MEDIA 0
#define WDX_OTA_MEDIA 1
#define WDX_RAM_MEDIA 2
#define WDX_STREAM_MEDIA 3
WDXS File Transfer Control Command Message Lengths
#define WDX_FTC_ABORT_LEN 3
#define WDX_FTC_ERASE_LEN 3
#define WDX_FTC_VERIFY_LEN 3
#define WDX_FTC_PUT_LEN 16
#define WDX_FTC_GET_LEN 12
WDXS Default Feature Set
#define WDXS_DC_ENABLED TRUE
#define WDXS_AU_ENABLED TRUE
#define WDXS_OTA_ENABLED TRUE
WSF event types for application event handler
#define WDXS_EVT_TX_PATH 0x01
#define WDXS_EVT_AU_SEC_COMPLETE 0x02
TX Ready Mask Bits
#define WDXS_TX_MASK_READY_BIT (1<<0)
#define WDXS_TX_MASK_DC_BIT (1<<1)
#define WDXS_TX_MASK_FTC_BIT (1<<2)
#define WDXS_TX_MASK_FTD_BIT (1<<3)
#define WDXS_TX_MASK_AU_BIT (1<<4)
Authentication states
#define WDXS_AU_STATE_UNAUTHORIZED 0x00
#define WDXS_AU_STATE_HASHING 0x01
#define WDXS_AU_STATE_WAIT_SEC 0x02
#define WDXS_AU_STATE_WAIT_REPLY 0x03
#define WDXS_AU_STATE_AUTHORIZED 0x04
WDXS Control Block External Declaration
wdxsCb_t wdxsCb
wdxsAuCb_t wdxsAuCb
wdxsDcCb_t wdxsDcCb
WDXS Stream Waveform Types
Type of waveform to output from the Example Stream
#define WDXS_STREAM_WAVEFORM_SINE 0
#define WDXS_STREAM_WAVEFORM_STEP 1
#define WDXS_STREAM_WAVEFORM_SAWTOOTH 2
Detailed Description
Data Structure Documentation
wdxcConnCb_t
struct wdxcConnCb_t
WDXC Connection Control Block.
Data Fields
uint16_t * pHdlList
uint16_t fileHdl
wsfEfsFileInfo_t * pFileList
uint16_t maxFiles
uint16_t fileCount
uint16_t fDlPos
wdxcCb_t
struct wdxcCb_t
WDXC Control Block.
Data Fields
wdxcConnCb_t conn [DM_CONN_MAX]
WdxcFtdCallback_t * pFtdCallback
WdxcFtcCallback_t * pFtcCallback
wdxsCb_t
struct wdxsCb_t
WDXS profile control block.
Data Fields
wsfHandlerId_t handlerId
uint8_t txReadyMask
uint16_t connInterval
uint16_t connLatency
uint16_t supTimeout
uint8_t txPhy
uint8_t rxPhy
uint32_t ftOffset
uint32_t ftLen
uint32_t ftTotalLen
uint16_t ftHandle
uint16_t ftcMsgLen
uint8_t ftcMsgBuf [ATT_DEFAULT_PAYLOAD_LEN]
uint8_t ftInProgress
uint8_t ftPrefXferType
uint8_t dcCccIdx
uint8_t auCccIdx
uint8_t ftcCccIdx
uint8_t ftdCccIdx
wdxsDcCb_t
struct wdxsDcCb_t
WDXS Device Configuration Control Block.
Data Fields
uint16_t dcMsgLen
uint8_t dcMsgBuf [ATT_DEFAULT_PAYLOAD_LEN]
bool_t doReset
wdxsDcPhyWriteCback_t phyWriteCback
wdxsAuCb_t
struct wdxsAuCb_t
WDXS Authentication Control Block.
Data Fields
uint8_t auMsgBuf [ATT_DEFAULT_PAYLOAD_LEN]
uint8_t auRand [WDX_AU_RAND_LEN]
uint8_t sessionKey [WDX_AU_KEY_LEN]
uint8_t auHash [WDX_AU_HASH_LEN]
uint16_t auMsgLen
uint8_t authLevel
uint8_t authMode
uint8_t reqAuthLevel
uint8_t authState
wdxsMsg_t
union wdxsMsg_t
WDXS event message union.
Data Fields
wsfMsgHdr_t hdr
dmEvt_t dm
attsCccEvt_t ccc
Field Documentation
ccc
attsCccEvt_t ccc
ATT CCC event
dm
dmEvt_t dm
DM event
hdr
wsfMsgHdr_t hdr
header
Typedef Documentation
WdxcFtcCallback_t
typedef void WdxcFtcCallback_t(dmConnId_t connId, uint16_t handle, uint8_t op, uint8_t status)
WDXC File Transfer Control callback.
Parameters
connId Connection ID.
handle Handle of the file.
op Control operation.
status Status of operation.
Returns
None.
WdxcFtdCallback_t
typedef void WdxcFtdCallback_t(dmConnId_t connId, uint16_t handle, uint16_t len, uint8_t *pData)
WDXC File Transfer Data callback.
Parameters
connId Connection ID.
handle Handle of the file.
len length of pData in bytes.
pData File data.
Returns
None.
Enumeration Type Documentation
anonymous enum
anonymous enum
WDXC enumeration of handle indexes of characteristics to be discovered.
Enumerator
WDXC_DC_HDL_IDX
WDX Device Configuration.
WDXC_DC_CCC_HDL_IDX
WDX Device Configuration CCC descriptor.
WDXC_FTC_HDL_IDX
WDX File Transfer Control.
WDXC_FTC_CCC_HDL_IDX
WDX File Transfer Control CCC descriptor.
WDXC_FTD_HDL_IDX
WDX File Transfer Data.
WDXC_FTD_CCC_HDL_IDX
WDX File Transfer Data CCC descriptor.
WDXC_AU_HDL_IDX
WDX Authenticationa.
WDXC_AU_CCC_HDL_IDX
WDX Authentication CCC descriptor.
WDXC_HDL_LIST_LEN
WDX handle list length.
Function Documentation
WdxcDcSendDisconnectAndReset()
void WdxcDcSendDisconnectAndReset (dmConnId_t connId)
Send a request to Disconnect And Reset.
Parameters
connId Connection ID.
Returns
None.
References AttcWriteReq(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, UINT8_TO_BSTREAM, WDX_DC_HDR_LEN, WDX_DC_ID_DISCONNECT_AND_RESET, WDX_DC_OP_SET, WDXC_DC_HDL_IDX, and WSF_ASSERT.
WdxcDiscoverFiles()
void WdxcDiscoverFiles (dmConnId_t connId, wsfEfsFileInfo_t * pFileInfo, uint8_t maxFiles)
Perform File Discovery.
Parameters
connId Connection ID.
pFileInfo Buffer to hold information about files
maxFiles Size of pFileInfo in number of wsfEfsFileInfo_t objects
Note
When file discovery completes, the ftcCallback() will be called with operator equal to WDX_FTC_OP_EOF and file handle equal to WDX_FLIST_HANDLE.
Returns
None.
Parameters
connId Connection ID.
pFileInfo Buffer to hold information about files
maxFiles Size of pFileInfo in number of wsfEfsFileInfo_t objects
Note
When discovery is complete, the ftcCallback will be called with op equal to WDX_FTC_OP_EOF and the file handle equal to WDX_FLIST_HANDLE.
Returns
None.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, wsfEfsFileInfo_t::attributes, BSTREAM_TO_UINT16, BSTREAM_TO_UINT8, wdxcCb_t::conn, wdxcConnCb_t::fDlPos, wdxcConnCb_t::fileCount, wdxcConnCb_t::fileHdl, wsfEfsFileInfo_t::handle, attEvt_t::handle, attEvt_t::hdr, wdxcConnCb_t::maxFiles, wsfEsfAttributes_t::name, wsfMsgHdr_t::param, wsfEsfAttributes_t::permissions, wdxcConnCb_t::pFileList, wdxcCb_t::pFtcCallback, wdxcCb_t::pFtdCallback, wdxcConnCb_t::pHdlList, attEvt_t::pValue, wsfEfsFileInfo_t::size, wsfEsfAttributes_t::type, attEvt_t::valueLen, wsfEsfAttributes_t::version, WDX_FLIST_HANDLE, WDX_FLIST_HDR_SIZE, WDX_FLIST_RECORD_SIZE, WDX_FTC_OP_ABORT, WDX_FTC_OP_EOF, WDX_FTC_ST_SUCCESS, WDXC_AU_HDL_IDX, WDXC_DC_HDL_IDX, WDXC_FTC_HDL_IDX, WDXC_FTD_HDL_IDX, WdxcFtcSendGetReq(), WSF_EFS_INVALID_HANDLE, and WSF_EFS_NAME_LEN.
WdxcFtcSendAbort()
void WdxcFtcSendAbort (dmConnId_t connId, uint16_t fileHdl)
Send a request to abort a wdx operation.
Parameters
connId Connection ID.
fileHdl Handle of file to abort operation on peer device
Returns
None.
References AttcWriteReq(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FTC_ABORT_LEN, WDX_FTC_OP_ABORT, WDXC_FTC_HDL_IDX, and WSF_ASSERT.
WdxcFtcSendEraseFile()
void WdxcFtcSendEraseFile (dmConnId_t connId, uint16_t fileHdl)
Send a request to erase a file.
Parameters
connId Connection ID.
fileHdl Handle of file to erase on peer device
Returns
None.
References AttcWriteReq(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FTC_ERASE_LEN, WDX_FTC_OP_ERASE_REQ, WDXC_FTC_HDL_IDX, and WSF_ASSERT.
WdxcFtcSendGetReq()
void WdxcFtcSendGetReq (dmConnId_t connId, uint16_t fileHdl, uint32_t offset, uint32_t len, uint8_t type)
Send a request to perform a get a block of data from a file on the peer device.
Parameters
connId Connection ID.
fileHdl Handle of file to verify on peer device
offset The offset from the beginning of the file in bytes
len The number of bytes to get
type reserved
Returns
None.
References AttcWriteReq(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, UINT16_TO_BSTREAM, UINT32_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FTC_GET_LEN, WDX_FTC_OP_GET_REQ, WDXC_FTC_HDL_IDX, and WSF_ASSERT.
WdxcFtcSendPutReq()
void WdxcFtcSendPutReq (dmConnId_t connId, uint16_t fileHdl, uint32_t offset, uint32_t len, uint32_t fileSize, uint8_t type)
Send a request to put a block of data into a file on the peer device.
Parameters
connId Connection ID.
fileHdl Handle of file on peer device
offset The offset from the beginning of the file in bytes
len The number of bytes to put
fileSize The size of the file in bytes
type reserved
Returns
None.
References AttcWriteReq(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, UINT16_TO_BSTREAM, UINT32_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FTC_OP_PUT_REQ, WDX_FTC_PUT_LEN, WDXC_FTC_HDL_IDX, and WSF_ASSERT.
WdxcFtcSendVerifyFile()
void WdxcFtcSendVerifyFile (dmConnId_t connId, uint16_t fileHdl)
Send a request to verify a file.
Parameters
connId Connection ID.
fileHdl Handle of file to verify on peer device
Returns
None.
References AttcWriteReq(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FTC_OP_VERIFY_REQ, WDX_FTC_VERIFY_LEN, WDXC_FTC_HDL_IDX, and WSF_ASSERT.
WdxcFtdSendBlock()
void WdxcFtdSendBlock (dmConnId_t connId, uint32_t len, uint8_t * pData)
Send a data block to the peer device.
Parameters
connId Connection ID.
len Size of pData in bytes
pData Data to put to the file
Returns
None.
References AttcWriteCmd(), wdxcCb_t::conn, wdxcConnCb_t::pHdlList, WDXC_FTD_HDL_IDX, and WSF_ASSERT.
WdxcInit()
void WdxcInit (WdxcFtdCallback_t * pFtdCallback, WdxcFtcCallback_t * pFtcCallback)
Initialize the WDXC.
Parameters
pFtdCallback Application Callback for File Transfer Data.
pFtcCallback Application Callback for File Transfer Control.
Returns
None.
Parameters
pFtdCallback File transfer data callback
pFtcCallback File transfer control callback
Returns
None.
References wdxcCb_t::conn, DM_CONN_MAX, wdxcConnCb_t::fileHdl, wdxcCb_t::pFtcCallback, wdxcCb_t::pFtdCallback, and WSF_EFS_INVALID_HANDLE.
WdxcProcMsg()
void WdxcProcMsg (wsfMsgHdr_t * pEvt)
Called by application to notify the WDXC of DM and ATT Events.
Parameters
pEvt Pointer to the Event
Returns
None.
Called by application to notify the WDXC of DM and ATT Events.
Parameters
pEvt Pointer to the Event
Returns
None.
References ATTC_HANDLE_VALUE_NTF, wdxcCb_t::conn, DM_CONN_CLOSE_IND, wsfMsgHdr_t::event, wdxcConnCb_t::fileHdl, and WSF_EFS_INVALID_HANDLE.
WdxcStoreAttrHandles()
void WdxcStoreAttrHandles (dmConnId_t connId, uint16_t * pHdlList)
Store pointer to the attribute handles in the control block Parameter pHdlList must point to an array of length WDXC_HDL_LIST_LEN.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Store pointer to the attribute handles in the control block Parameter pHdlList must point to an array of length WDXC_HDL_LIST_LEN.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References wdxcCb_t::conn, and wdxcConnCb_t::pHdlList.
WdxcStreamStart()
void WdxcStreamStart (dmConnId_t connId, uint16_t fileHdl)
Send a request to start a stream of a given file handle on the given connection.
Parameters
connId Connection ID.
fileHdl Handle of the file.
Returns
none.
Parameters
connId Connection ID.
fileHdl Handle of the file.
Returns
None.
References AttGetMtu(), wdxcCb_t::conn, wdxcConnCb_t::fileHdl, WdxcFtcSendGetReq(), and WSF_EFS_INVALID_HANDLE.
WdxcStreamStop()
void WdxcStreamStop (dmConnId_t connId)
Stop the active stream.
Parameters
connId Connection ID.
Returns
None.
None.
References wdxcCb_t::conn, wdxcConnCb_t::fileHdl, WdxcFtcSendAbort(), and WSF_EFS_INVALID_HANDLE.
WdxcWdxsDiscover()
void WdxcWdxsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Wireless Data Exchange service. Parameter pHdlList must point to an array of length WDXC_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Wireless Data Exchange service. Parameter pHdlList must point to an array of length WDXC_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, WDXC_HDL_LIST_LEN, and WdxcStoreAttrHandles().
WdxsAttCback()
uint8_t WdxsAttCback (attEvt_t * pEvt)
Called by application to notify the WDXS of ATT Events.
Parameters
pEvt Pointer to the ATT Event
Returns
TRUE if the application should ignore the event, else FALSE.
Parameters
pEvt Pointer to the ATT Event
Returns
None.
References attEvt_t::handle, WDXS_END_HDL, and WDXS_START_HDL.
wdxsAuSend()
void wdxsAuSend (dmConnId_t connId)
Transmit to authentication characteristic.
Parameters
connId DM connection identifier.
Returns
ATT status.
ATT status.
References ATT_ERR_LENGTH, ATT_SUCCESS, AttsCccEnabled(), AttsHandleValueNtf(), wdxsCb_t::auCccIdx, wdxsAuCb_t::auHash, wdxsAuCb_t::auMsgBuf, wdxsAuCb_t::auMsgLen, wdxsAuCb_t::auRand, wdxsAuCb_t::authLevel, wdxsAuCb_t::authMode, wdxsAuCb_t::authState, BSTREAM_TO_UINT8, wdxsCb_t::handlerId, secAes_t::pCiphertext, SecAes(), SecRand(), wdxsAuCb_t::sessionKey, wdxsCb_t::txReadyMask, UINT8_TO_BSTREAM, WDX_AU_HASH_LEN, WDX_AU_HDR_LEN, WDX_AU_OP_CHALLENGE, WDX_AU_PARAM_LEN_REPLY, WDX_AU_PARAM_LEN_START, WDX_AU_RAND_LEN, WDX_AU_ST_AUTH_FAILED, WDX_AU_ST_INVALID_STATE, WDXS_AU_HDL, WDXS_AU_STATE_AUTHORIZED, WDXS_AU_STATE_WAIT_REPLY, WDXS_AU_STATE_WAIT_SEC, WDXS_EVT_AU_SEC_COMPLETE, WDXS_EVT_TX_PATH, WDXS_TX_MASK_AU_BIT, WDXS_TX_MASK_READY_BIT, wdxsCb, and WsfSetEvent().
WdxsAuthenticationCfg()
void WdxsAuthenticationCfg (bool_t reqLevel, uint8_t * pKey)
Called at startup to configure WDXS authentication.
Parameters
reqLevel Level of authentication that is required for a client to use WDXS
pKey Authentication key (set to NULL if no authentication is required)
Returns
None.
Parameters
reqLevel Level of authentication that is required for a client to use WDXS
key Authentication key (set to NULL if no authentication is required)
Returns
None.
wdxsAuWrite()
uint8_t wdxsAuWrite (dmConnId_t connId, uint16_t len, uint8_t * pValue)
Process a write to the authentication characteristic.
Parameters
connId DM connection identifier.
len Length to write.
pValue Value to write
Returns
ATT status.
ATT status.
References ATT_ERR_LENGTH, ATT_ERR_RANGE, BSTREAM_TO_UINT8, WDX_AU_HDR_LEN, WDX_AU_OP_REPLY, and WDX_AU_OP_START.
wdxsDcPhyRegister()
void wdxsDcPhyRegister (wdxsDcPhyWriteCback_t cback)
Register a PHY write callback for the device configuration characteristic.
Parameters
cback PHY callback function.
Returns
None.
References wdxsDcCb_t::phyWriteCback.
wdxsDcSend()
void wdxsDcSend (dmConnId_t connId)
Send device configuration notification.
Parameters
connId DM connection identifier.
Returns
None.
None.
References AttsCccEnabled(), AttsHandleValueNtf(), wdxsCb_t::dcCccIdx, wdxsDcCb_t::dcMsgBuf, wdxsDcCb_t::dcMsgLen, wdxsCb_t::txReadyMask, WDXS_DC_HDL, WDXS_TX_MASK_DC_BIT, WDXS_TX_MASK_READY_BIT, and wdxsCb.
wdxsDcUpdateConnParam()
uint8_t wdxsDcUpdateConnParam (dmConnId_t connId, uint8_t status)
Send update message for connection parameters.
Parameters
connId DM connection identifier.
status Update status.
Returns
ATT status.
ATT status.
References ATT_ERR_IN_PROGRESS, ATT_SUCCESS, wdxsCb_t::connInterval, wdxsCb_t::connLatency, wdxsDcCb_t::dcMsgBuf, wdxsDcCb_t::dcMsgLen, wdxsCb_t::handlerId, wdxsCb_t::supTimeout, wdxsCb_t::txReadyMask, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_DC_HDR_LEN, WDX_DC_ID_CONN_PARAM, WDX_DC_LEN_CONN_PARAM, WDX_DC_OP_UPDATE, WDXS_EVT_TX_PATH, WDXS_TX_MASK_DC_BIT, wdxsCb, and WsfSetEvent().
wdxsDcUpdatePhy()
uint8_t wdxsDcUpdatePhy (dmConnId_t connId, uint8_t status)
Send update message for PHY.
Parameters
connId DM connection identifier.
status Update status.
Returns
ATT status.
ATT status.
References AppConnClose(), ATT_ERR_IN_PROGRESS, ATT_ERR_LENGTH, ATT_ERR_NOT_SUP, ATT_SUCCESS, BSTREAM_TO_UINT16, BSTREAM_TO_UINT8, hciConnSpec_t::connIntervalMax, hciConnSpec_t::connIntervalMin, hciConnSpec_t::connLatency, wdxsDcCb_t::dcMsgBuf, wdxsDcCb_t::dcMsgLen, DM_SEC_LEVEL_NONE, DmConnSecLevel(), DmConnUpdate(), DmSecSlaveReq(), wdxsDcCb_t::doReset, wdxsCb_t::handlerId, wdxsCb_t::rxPhy, hciConnSpec_t::supTimeout, wdxsCb_t::txPhy, wdxsCb_t::txReadyMask, UINT8_TO_BSTREAM, WDX_DC_HDR_LEN, WDX_DC_ID_DIAGNOSTICS_COMPLETE, WDX_DC_ID_PHY, WDX_DC_LEN_CONN_PARAM_REQ, WDX_DC_LEN_DIAG_COMPLETE, WDX_DC_LEN_PHY, WDX_DC_LEN_SEC_LEVEL, WDX_DC_OP_UPDATE, WDXS_EVT_TX_PATH, WDXS_TX_MASK_DC_BIT, wdxsCb, and WsfSetEvent().
wdxsDcWrite()
uint8_t wdxsDcWrite (dmConnId_t connId, uint16_t len, uint8_t * pValue)
Process a write to the device configuration characteristic.
Parameters
connId DM connection identifier.
len Length to write.
pValue value to write.
Returns
ATT status.
ATT status.
References ATT_ERR_CCCD, ATT_ERR_LENGTH, ATT_ERR_RANGE, ATT_SUCCESS, AttsCccEnabled(), BSTREAM_TO_UINT8, wdxsCb_t::dcCccIdx, wdxsDcCb_t::phyWriteCback, WDX_DC_HDR_LEN, WDX_DC_ID_ATT_MTU, WDX_DC_ID_BATTERY_LEVEL, WDX_DC_ID_CONN_PARAM, WDX_DC_ID_CONN_SEC_LEVEL, WDX_DC_ID_CONN_UPDATE_REQ, WDX_DC_ID_DELETE_BONDS, WDX_DC_ID_DISCONNECT_AND_RESET, WDX_DC_ID_DISCONNECT_REQ, WDX_DC_ID_ENTER_DIAGNOSTICS, WDX_DC_ID_FIRMWARE_REV, WDX_DC_ID_MODEL_NUMBER, WDX_DC_ID_PHY, WDX_DC_ID_PHY_UPDATE_REQ, WDX_DC_ID_SECURITY_REQ, WDX_DC_ID_SERVICE_CHANGED, WDX_DC_OP_GET, WDX_DC_OP_SET, and wdxsCb.
WdxsFlashMediaInit()
WdxsFlashMediaInit (void)
Registers the platform dependent Flash Media with the Embedded File System (EFS)
Returns
None.
Parameters
None
Returns
None.
wdxsFtcSend()
void wdxsFtcSend (dmConnId_t connId)
Send a file transfer control characteristic notification.
Parameters
connId DM connection identifier.
Returns
None.
None.
References AttsCccEnabled(), AttsHandleValueNtf(), wdxsCb_t::ftcCccIdx, wdxsCb_t::ftcMsgBuf, wdxsCb_t::ftcMsgLen, wdxsCb_t::txReadyMask, WDXS_FTC_HDL, WDXS_TX_MASK_FTC_BIT, WDXS_TX_MASK_READY_BIT, and wdxsCb.
wdxsFtcSendRsp()
void wdxsFtcSendRsp (dmConnId_t connId, uint8_t op, uint16_t handle, uint8_t status)
Send a file transfer response message.
Returns
None.
References BSTREAM_TO_UINT32, BSTREAM_TO_UINT8, wdxsCb_t::ftcMsgBuf, wdxsCb_t::ftcMsgLen, wdxsCb_t::ftHandle, wdxsCb_t::ftInProgress, wdxsCb_t::ftLen, wdxsCb_t::ftOffset, wdxsCb_t::ftPrefXferType, wdxsCb_t::ftTotalLen, wdxsCb_t::handlerId, wdxsCb_t::txReadyMask, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FLIST_HANDLE, WDX_FTC_OP_ABORT, WDX_FTC_OP_EOF, WDX_FTC_OP_ERASE_RSP, WDX_FTC_OP_GET_REQ, WDX_FTC_OP_GET_RSP, WDX_FTC_OP_NONE, WDX_FTC_OP_PUT_RSP, WDX_FTC_OP_VERIFY_RSP, WDX_FTC_ST_IN_PROGRESS, WDX_FTC_ST_INVALID_HANDLE, WDX_FTC_ST_INVALID_OP_FILE, WDX_FTC_ST_SUCCESS, WDX_FTC_TRANSPORT_ID, WDX_FTC_TRANSPORT_TYPE, WDXS_EVT_TX_PATH, WDXS_TX_MASK_FTC_BIT, WDXS_TX_MASK_FTD_BIT, wdxsCb, wdxsFtcSendRsp(), WdxsUpdateListing(), WSF_EFS_FILE_TYPE_STREAM, WSF_EFS_REMOTE_ERASE_PERMITTED, WSF_EFS_REMOTE_GET_PERMITTED, WSF_EFS_REMOTE_PUT_PERMITTED, WSF_EFS_REMOTE_VERIFY_PERMITTED, WSF_EFS_VALIDATE_CMD, WsfEfsErase(), WsfEfsGetFilePermissions(), WsfEfsGetFileType(), WsfEfsMediaSpecificCommand(), and WsfSetEvent().
wdxsFtcWrite()
uint8_t wdxsFtcWrite (dmConnId_t connId, uint16_t len, uint8_t * pValue)
Process a write to the file transfer control characteristic.
Parameters
connId DM connection identifier.
len Length to write.
pValue Value to write.
Returns
ATT status.
ATT status.
References ATT_ERR_LENGTH, ATT_SUCCESS, BSTREAM_TO_UINT16, BSTREAM_TO_UINT8, WDX_FTC_HANDLE_LEN, WDX_FTC_HDR_LEN, WDX_FTC_OP_ABORT, WDX_FTC_OP_ERASE_REQ, WDX_FTC_OP_GET_REQ, WDX_FTC_OP_PUT_REQ, and WDX_FTC_OP_VERIFY_REQ.
wdxsFtdSend()
void wdxsFtdSend (dmConnId_t connId)
Send a file transfer data characteristic notification.
Parameters
connId DM connection identifier.
Returns
None.
None.
References ATT_VALUE_NTF_LEN, AttGetMtu(), AttsCccEnabled(), wdxsCb_t::ftdCccIdx, and wdxsCb.
wdxsFtdWrite()
uint8_t wdxsFtdWrite (dmConnId_t connId, uint16_t len, uint8_t * pValue)
Process a write to the file transfer data characteristic.
Parameters
connId DM connection identifier.
len Length to write.
pValue Value to write.
Returns
ATT status.
ATT status.
References ATT_ERR_LENGTH, ATT_ERR_UNLIKELY, ATT_SUCCESS, wdxsCb_t::ftHandle, wdxsCb_t::ftInProgress, wdxsCb_t::ftLen, wdxsCb_t::ftOffset, wdxsCb_t::ftTotalLen, WDX_FTC_OP_EOF, WDX_FTC_OP_NONE, WDX_FTC_OP_PUT_REQ, WDX_FTD_HDR_LEN, wdxsCb, wdxsFtcSendRsp(), WSF_EFS_WDXS_PUT_COMPLETE_CMD, WsfEfsMediaSpecificCommand(), and WsfEfsPut().
WdxsHandler()
void WdxsHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
Handle WSF events for WDXS.
Parameters
event event
pMsg message assiciated with event
Returns
None.
Handle WSF events for WDXS.
Parameters
event WSF event mask.
pMsg WSF message.
Returns
None.
References WDXS_EVT_AU_SEC_COMPLETE, and WDXS_EVT_TX_PATH.
WdxsHandlerInit()
void WdxsHandlerInit (wsfHandlerId_t handlerId)
WSF Task Initialization for WDXS task.
Parameters
handlerId ID of the WDXS task
Returns
None.
WSF Task Initialization for WDXS task.
Parameters
handlerID WSF handler ID.
Returns
None.
References wsfEfsMedia_t::endAddress, wdxsCb_t::handlerId, wsfEsfAttributes_t::name, wsfEsfAttributes_t::permissions, wsfEfsMedia_t::startAddress, SvcWdxsAddGroup(), SvcWdxsRegister(), wdxsCb_t::txReadyMask, wsfEsfAttributes_t::type, wsfEsfAttributes_t::version, WDX_FLIST_MAX_LEN, WDX_RAM_MEDIA, WDXS_TX_MASK_READY_BIT, wdxsDcCb, WSF_EFS_FILE_OFFSET_ANY, WSF_EFS_FILE_TYPE_BULK, WSF_EFS_LOCAL_PUT_PERMITTED, WSF_EFS_NAME_LEN, WSF_EFS_REMOTE_GET_PERMITTED, WSF_EFS_VERSION_LEN, WsfEfsAddFile(), WsfEfsInit(), WsfEfsRegisterMedia(), and WstrnCpy().
WdxsOtaMediaInit()
WdxsOtaMediaInit (void)
Registers the platform dependent OTA Media with the Embedded File System (EFS)
Returns
None.
Parameters
None
Returns
None.
References WdxsResetSystem().
WdxsPhyInit()
void WdxsPhyInit (void)
Initialize WDXS Device Configuration PHY.
Returns
None.
Parameters
None
Returns
None.
References wdxsDcPhyRegister().
WdxsProcDmMsg()
void WdxsProcDmMsg (dmEvt_t * pEvt)
Called by application to notify the WDXS of DM Events.
Parameters
pEvt Pointer to the DM Event
Returns
None.
References wdxsAuCb_t::authLevel, wdxsAuCb_t::authState, wdxsCb_t::connInterval, hciLeConnCmplEvt_t::connInterval, hciLeConnUpdateCmplEvt_t::connInterval, wdxsCb_t::connLatency, hciLeConnCmplEvt_t::connLatency, hciLeConnUpdateCmplEvt_t::connLatency, dmEvt_t::connOpen, dmEvt_t::connUpdate, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, DM_CONN_UPDATE_IND, DM_PHY_UPDATE_IND, wdxsDcCb_t::doReset, wsfMsgHdr_t::event, wdxsCb_t::ftInProgress, wdxsCb_t::ftLen, wdxsCb_t::ftOffset, HCI_PHY_LE_1M_BIT, HCI_SUCCESS, dmEvt_t::hdr, wsfMsgHdr_t::param, dmEvt_t::phyUpdate, wdxsCb_t::rxPhy, hciLePhyUpdateEvt_t::rxPhy, wsfMsgHdr_t::status, wdxsCb_t::supTimeout, hciLeConnCmplEvt_t::supTimeout, hciLeConnUpdateCmplEvt_t::supTimeout, wdxsCb_t::txPhy, hciLePhyUpdateEvt_t::txPhy, wdxsCb_t::txReadyMask, WDX_AU_LVL_NONE, WDX_FTC_OP_NONE, WDXS_AU_STATE_UNAUTHORIZED, WDXS_TX_MASK_READY_BIT, wdxsAuCb, wdxsDcCb, wdxsDcUpdateConnParam(), wdxsDcUpdatePhy(), and WdxsResetSystem().
WdxsResetSystem()
WdxsResetSystem (void)
Resets the system.
Returns
None.
Parameters
None
Returns
None.
WdxsSetCccIdx()
void WdxsSetCccIdx (uint8_t dcCccIdx, uint8_t auCccIdx, uint8_t ftcCccIdx, uint8_t ftdCccIdx)
Set the CCCD index used by the application for WDXS service characteristics.
Parameters
dcCccIdx Device Control CCCD index.
auCccIdx Authentication CCCD index.
ftcCccIdx File Transfer Control CCCD index.
ftdCccIdx File Transfer Data CCCD index.
Returns
None.
References AppConnIsOpen(), ATT_ERR_HANDLE, wdxsCb_t::auCccIdx, wdxsAuCb_t::authLevel, wdxsAuCb_t::authState, wdxsCb_t::dcCccIdx, DM_CONN_ID_NONE, wdxsCb_t::ftcCccIdx, wdxsCb_t::ftdCccIdx, wdxsAuCb_t::reqAuthLevel, wdxsCb_t::txReadyMask, WDX_APP_AUTH_REQUIRED, WDX_AU_LVL_NONE, WDXS_AU_HDL, WDXS_AU_STATE_AUTHORIZED, WDXS_DC_HDL, WDXS_FTC_HDL, WDXS_FTD_HDL, WDXS_TX_MASK_AU_BIT, WDXS_TX_MASK_DC_BIT, WDXS_TX_MASK_FTC_BIT, WDXS_TX_MASK_FTD_BIT, WDXS_TX_MASK_READY_BIT, wdxsAuCb, wdxsAuSend(), wdxsAuWrite(), wdxsDcSend(), wdxsDcWrite(), wdxsFtcSend(), wdxsFtcWrite(), wdxsFtdSend(), and wdxsFtdWrite().
wdxsSetStreamWaveform()
void wdxsSetStreamWaveform (uint8_t type)
Changes the type of waveform transmitted by the stream.
Parameters
type - Identifier of the waveform
Returns
None.
wdxsStreamInit()
void wdxsStreamInit (void)
Example of creating a WDXS stream.
Returns
None.
Parameters
none
Returns
None.
References wsfEsfAttributes_t::name, wsfEsfAttributes_t::permissions, wsfEsfAttributes_t::type, wsfEsfAttributes_t::version, WDX_STREAM_MEDIA, WSF_EFS_FILE_TYPE_STREAM, WSF_EFS_NAME_LEN, WSF_EFS_REMOTE_GET_PERMITTED, WSF_EFS_REMOTE_VISIBLE, WSF_EFS_VERSION_LEN, WsfEfsAddFile(), WsfEfsRegisterMedia(), and WstrnCpy().
WdxsUpdateListing()
void WdxsUpdateListing (void)
Create the file list.
Returns
none.
References UINT16_TO_BSTREAM, UINT32_TO_BSTREAM, UINT8_TO_BSTREAM, WDX_FLIST_FORMAT_VER, WDX_FLIST_HANDLE, WDX_FLIST_HDR_SIZE, WDX_FLIST_RECORD_SIZE, WSF_EFS_MAX_FILES, WSF_EFS_REMOTE_VISIBLE, WsfEfsGetFileByHandle(), WsfEfsGetFilePermissions(), WsfEfsGetFileSize(), and WsfEfsPut().
Variable Documentation
wdxsCb
wdxsCb_t wdxsCb
WDXS control block.
application control block