Cordio: LL_API_DEVICE
LL_API_DEVICE
Macros
#define LL_SUP_STATE_NON_CONN_ADV (UINT64_C(1) << 0)
#define LL_SUP_STATE_SCAN_ADV (UINT64_C(1) << 1)
#define LL_SUP_STATE_CONN_ADV (UINT64_C(1) << 2)
#define LL_SUP_STATE_HI_DUTY_DIR_ADV (UINT64_C(1) << 3)
#define LL_SUP_STATE_PASS_SCAN (UINT64_C(1) << 4)
#define LL_SUP_STATE_ACT_SCAN (UINT64_C(1) << 5)
#define LL_SUP_STATE_INIT (UINT64_C(1) << 6)
#define LL_SUP_STATE_CONN_SLV (UINT64_C(1) << 7)
#define LL_SUP_STATE_NON_CONN_ADV_AND_PASS_SCAN (UINT64_C(1) << 8)
#define LL_SUP_STATE_SCAN_ADV_AND_PASS_SCAN (UINT64_C(1) << 9)
#define LL_SUP_STATE_CONN_ADV_AND_PASS_SCAN (UINT64_C(1) << 10)
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_AND_PASS_SCAN (UINT64_C(1) << 11)
#define LL_SUP_STATE_NON_CONN_ADV_AND_ACT_SCAN (UINT64_C(1) << 12)
#define LL_SUP_STATE_SCAN_ADV_AND_ACT_SCAN (UINT64_C(1) << 13)
#define LL_SUP_STATE_CONN_ADV_AND_ACT_SCAN (UINT64_C(1) << 14)
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_ACT_SCAN (UINT64_C(1) << 15)
#define LL_SUP_STATE_NON_CONN_ADV_AND_INIT (UINT64_C(1) << 16)
#define LL_SUP_STATE_SCAN_ADV_AND_INIT (UINT64_C(1) << 17)
#define LL_SUP_STATE_NON_CONN_ADV_MST (UINT64_C(1) << 18)
#define LL_SUP_STATE_SCAN_ADV_MST (UINT64_C(1) << 19)
#define LL_SUP_STATE_NON_CONN_ADV_SLV (UINT64_C(1) << 20)
#define LL_SUP_STATE_SCAN_ADV_SLV (UINT64_C(1) << 21)
#define LL_SUP_STATE_PASS_SCAN_AND_INIT (UINT64_C(1) << 22)
#define LL_SUP_STATE_ACT_SCAN_AND_INIT (UINT64_C(1) << 23)
#define LL_SUP_STATE_PASS_SCAN_MST (UINT64_C(1) << 24)
#define LL_SUP_STATE_ACT_SCAN_MST (UINT64_C(1) << 25)
#define LL_SUP_STATE_PASS_SCAN_SLV (UINT64_C(1) << 26)
#define LL_SUP_STATE_ACT_SCAN_SLV (UINT64_C(1) << 27)
#define LL_SUP_STATE_INIT_MST (UINT64_C(1) << 28)
#define LL_SUP_STATE_LO_DUTY_DIR_ADV (UINT64_C(1) << 29)
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_PASS_SCAN (UINT64_C(1) << 30)
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_ACT_SCAN (UINT64_C(1) << 31)
#define LL_SUP_STATE_CONN_ADV_AND_INIT (UINT64_C(1) << 32)
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_AND_INIT (UINT64_C(1) << 33)
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_INIT (UINT64_C(1) << 34)
#define LL_SUP_STATE_CONN_ADV_MST (UINT64_C(1) << 35)
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_MST (UINT64_C(1) << 36)
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_MST (UINT64_C(1) << 37)
#define LL_SUP_STATE_CONN_ADV_SLV (UINT64_C(1) << 38)
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_SLV (UINT64_C(1) << 39)
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_SLV (UINT64_C(1) << 40)
#define LL_SUP_STATE_INIT_SLV (UINT64_C(1) << 41)
#define LL_FEAT_ENCRYPTION (UINT64_C(1) << 0)
#define LL_FEAT_CONN_PARAM_REQ_PROC (UINT64_C(1) << 1)
#define LL_FEAT_EXT_REJECT_IND (UINT64_C(1) << 2)
#define LL_FEAT_SLV_INIT_FEAT_EXCH (UINT64_C(1) << 3)
#define LL_FEAT_LE_PING (UINT64_C(1) << 4)
#define LL_FEAT_DATA_LEN_EXT (UINT64_C(1) << 5)
#define LL_FEAT_PRIVACY (UINT64_C(1) << 6)
#define LL_FEAT_EXT_SCAN_FILT_POLICY (UINT64_C(1) << 7)
#define LL_FEAT_LE_2M_PHY (UINT64_C(1) << 8)
#define LL_FEAT_STABLE_MOD_IDX_TRANSMITTER (UINT64_C(1) << 9)
#define LL_FEAT_STABLE_MOD_IDX_RECEIVER (UINT64_C(1) << 10)
#define LL_FEAT_LE_CODED_PHY (UINT64_C(1) << 11)
#define LL_FEAT_LE_EXT_ADV (UINT64_C(1) << 12)
#define LL_FEAT_LE_PER_ADV (UINT64_C(1) << 13)
#define LL_FEAT_CH_SEL_2 (UINT64_C(1) << 14)
#define LL_FEAT_LE_POWER_CLASS_1 (UINT64_C(1) << 15)
#define LL_FEAT_MIN_NUM_USED_CHAN (UINT64_C(1) << 16)
#define LL_FEAT_CONN_CTE_REQ (UINT64_C(1) << 17)
#define LL_FEAT_CONN_CTE_RSP (UINT64_C(1) << 18)
#define LL_FEAT_CONNLESS_CTE_TRANS (UINT64_C(1) << 19)
#define LL_FEAT_CONNLESS_CTE_RECV (UINT64_C(1) << 20)
#define LL_FEAT_ANTENNA_SWITCH_AOD (UINT64_C(1) << 21)
#define LL_FEAT_ANTENNA_SWITCH_AOA (UINT64_C(1) << 22)
#define LL_FEAT_RECV_CTE (UINT64_C(1) << 23)
#define LL_FEAT_PAST_SENDER (UINT64_C(1) << 24)
#define LL_FEAT_PAST_RECIPIENT (UINT64_C(1) << 25)
#define LL_FEAT_SCA_UPDATE (UINT64_C(1) << 26)
#define LL_FEAT_REMOTE_PUB_KEY_VALIDATION (UINT64_C(1) << 27)
#define LL_FEAT_CIS_MASTER_ROLE (UINT64_C(1) << 28)
#define LL_FEAT_CIS_SLAVE_ROLE (UINT64_C(1) << 29)
#define LL_FEAT_ISO_BROADCASTER (UINT64_C(1) << 30)
#define LL_FEAT_ISO_SYNC (UINT64_C(1) << 31)
#define LL_FEAT_ISO_HOST_SUPPORT (UINT64_C(1) << 32)
#define LL_FEAT_POWER_CONTROL_REQUEST (UINT64_C(1) << 33)
#define LL_FEAT_POWER_CHANGE_IND (UINT64_C(1) << 34)
#define LL_FEAT_PATH_LOSS_MONITOR (UINT64_C(1) << 35)
#define LL_HOST_CONTROLLED_FEAT LL_FEAT_ISO_HOST_SUPPORT
#define LL_FEAT_ALL_MASK (UINT64_C(0x0000000FFF01FFFF))
Enumerations
enum LlRole_t
enum
Functions
void LlSetBdAddr (const uint8_t *pAddr)
void LlGetBdAddr (uint8_t *pAddr)
uint8_t LlSetRandAddr (const uint8_t *pAddr)
uint8_t LlGetRandAddr (uint8_t *pAddr)
void LlGetVersion (uint16_t *pCompId, uint8_t *pBtVer, uint16_t *pImplRev)
void LlGetSupStates (uint8_t *pStates)
void LlGetFeatures (uint8_t *pFeatures)
uint8_t LlSetFeatures (const uint8_t *pFeatures)
uint8_t LlSetHostFeatures (uint8_t bitNum, bool_t bitVal)
uint8_t LlGetRandNum (uint8_t *pRandNum)
uint8_t LlGetWhitelistSize (void)
uint8_t LlClearWhitelist (void)
uint8_t LlAddDeviceToWhitelist (uint8_t addrType, bdAddr_t pAddr)
uint8_t LlRemoveDeviceFromWhitelist (uint8_t addrType, bdAddr_t pAddr)
uint8_t LlAddDeviceToResolvingList (uint8_t peerAddrType, const uint8_t *pPeerIdentityAddr, const uint8_t *pPeerIrk, const uint8_t *pLocalIrk)
uint8_t LlRemoveDeviceFromResolvingList (uint8_t peerAddrType, const uint8_t *pPeerIdentityAddr)
uint8_t LlClearResolvingList (void)
uint8_t LlReadResolvingListSize (uint8_t *pSize)
uint8_t LlReadPeerResolvableAddr (uint8_t addrType, const uint8_t *pIdentityAddr, uint8_t *pRpa)
uint8_t LlReadLocalResolvableAddr (uint8_t addrType, const uint8_t *pIdentityAddr, uint8_t *pRpa)
uint8_t LlSetAddrResolutionEnable (uint8_t enable)
uint8_t LlSetResolvablePrivateAddrTimeout (uint16_t rpaTimeout)
uint8_t LlSetPrivacyMode (uint8_t peerAddrType, const uint8_t *pPeerIdentityAddr, uint8_t privMode)
uint8_t LlGenerateP256KeyPair (void)
uint8_t LlGenerateDhKey (const uint8_t pubKey_x[LL_ECC_KEY_LEN], const uint8_t pubKey_y[LL_ECC_KEY_LEN])
uint8_t LlGenerateDhKeyV2 (uint8_t pubKey_x[LL_ECC_KEY_LEN], uint8_t pubKey_y[LL_ECC_KEY_LEN], uint8_t keyType)
uint8_t LlSetP256PrivateKey (const uint8_t privKey[LL_ECC_KEY_LEN])
uint8_t LlSetValidatePublicKeyMode (uint8_t validateMode)
uint8_t LlSetChannelClass (const uint8_t *pChanMap)
uint8_t LlSetOpFlags (uint32_t flags, bool_t enable)
void LlSetDefaultExtAdvTxPhyOptions (const uint8_t phyOptions)
Detailed Description
Macro Definition Documentation
LL_FEAT_ALL_MASK
#define LL_FEAT_ALL_MASK (UINT64_C(0x0000000FFF01FFFF))
All feature mask, need to be updated when new features are added.
LL_FEAT_ANTENNA_SWITCH_AOA
#define LL_FEAT_ANTENNA_SWITCH_AOA (UINT64_C(1) << 22)
Anetenna Switching during CTE Reception (AoA) supported
LL_FEAT_ANTENNA_SWITCH_AOD
#define LL_FEAT_ANTENNA_SWITCH_AOD (UINT64_C(1) << 21)
Anetenna Switching during CTE Transmission (AoD) supported
LL_FEAT_CH_SEL_2
#define LL_FEAT_CH_SEL_2 (UINT64_C(1) << 14)
Channel Selection Algorithm #2 supported.
LL_FEAT_CIS_MASTER_ROLE
#define LL_FEAT_CIS_MASTER_ROLE (UINT64_C(1) << 28)
Connected Isochronous Stream Master Role supported.
LL_FEAT_CIS_SLAVE_ROLE
#define LL_FEAT_CIS_SLAVE_ROLE (UINT64_C(1) << 29)
Connected Isochronous Stream Slave Role supported.
LL_FEAT_CONN_CTE_REQ
#define LL_FEAT_CONN_CTE_REQ (UINT64_C(1) << 17)
Connection CTE Request supported
LL_FEAT_CONN_CTE_RSP
#define LL_FEAT_CONN_CTE_RSP (UINT64_C(1) << 18)
Connection CTE Response supported
LL_FEAT_CONN_PARAM_REQ_PROC
#define LL_FEAT_CONN_PARAM_REQ_PROC (UINT64_C(1) << 1)
Connection Parameters Request Procedure supported.
LL_FEAT_CONNLESS_CTE_RECV
#define LL_FEAT_CONNLESS_CTE_RECV (UINT64_C(1) << 20)
Connectionless CTE Receiver supported
LL_FEAT_CONNLESS_CTE_TRANS
#define LL_FEAT_CONNLESS_CTE_TRANS (UINT64_C(1) << 19)
Connectionless CTE Transmitter supported
LL_FEAT_DATA_LEN_EXT
#define LL_FEAT_DATA_LEN_EXT (UINT64_C(1) << 5)
Data Length Extension supported.
LL_FEAT_ENCRYPTION
#define LL_FEAT_ENCRYPTION (UINT64_C(1) << 0)
The features bitmask indicates the LE features supported by the LL. Encryption supported.
LL_FEAT_EXT_REJECT_IND
#define LL_FEAT_EXT_REJECT_IND (UINT64_C(1) << 2)
Extended Reject Indication supported.
LL_FEAT_EXT_SCAN_FILT_POLICY
#define LL_FEAT_EXT_SCAN_FILT_POLICY (UINT64_C(1) << 7)
Extended Scan Filter Policy supported.
LL_FEAT_ISO_BROADCASTER
#define LL_FEAT_ISO_BROADCASTER (UINT64_C(1) << 30)
Isochronous Broadcaster Role supported.
LL_FEAT_ISO_HOST_SUPPORT
#define LL_FEAT_ISO_HOST_SUPPORT (UINT64_C(1) << 32)
Host support for ISO Channels.
LL_FEAT_ISO_SYNC
#define LL_FEAT_ISO_SYNC (UINT64_C(1) << 31)
Isochronous Synchronizer Role supported.
LL_FEAT_LE_2M_PHY
#define LL_FEAT_LE_2M_PHY (UINT64_C(1) << 8)
LE 2M PHY supported.
LL_FEAT_LE_CODED_PHY
#define LL_FEAT_LE_CODED_PHY (UINT64_C(1) << 11)
LE Coded PHY supported.
LL_FEAT_LE_EXT_ADV
#define LL_FEAT_LE_EXT_ADV (UINT64_C(1) << 12)
LE Extended Advertising supported.
LL_FEAT_LE_PER_ADV
#define LL_FEAT_LE_PER_ADV (UINT64_C(1) << 13)
LE Periodic Advertising supported.
LL_FEAT_LE_PING
#define LL_FEAT_LE_PING (UINT64_C(1) << 4)
LE Ping supported.
LL_FEAT_LE_POWER_CLASS_1
#define LL_FEAT_LE_POWER_CLASS_1 (UINT64_C(1) << 15)
LE Power Class 1 supported.
LL_FEAT_MIN_NUM_USED_CHAN
#define LL_FEAT_MIN_NUM_USED_CHAN (UINT64_C(1) << 16)
Minimum Number of Used Channels supported.
LL_FEAT_PAST_RECIPIENT
#define LL_FEAT_PAST_RECIPIENT (UINT64_C(1) << 25)
Periodic Advertising Sync Transfer Recipient supported.
LL_FEAT_PAST_SENDER
#define LL_FEAT_PAST_SENDER (UINT64_C(1) << 24)
Periodic Advertising Sync Transfer Sender supported.
LL_FEAT_PATH_LOSS_MONITOR
#define LL_FEAT_PATH_LOSS_MONITOR (UINT64_C(1) << 35)
Path loss monitoring supported.
LL_FEAT_POWER_CHANGE_IND
#define LL_FEAT_POWER_CHANGE_IND (UINT64_C(1) << 34)
Power control power change indication supported.
LL_FEAT_POWER_CONTROL_REQUEST
#define LL_FEAT_POWER_CONTROL_REQUEST (UINT64_C(1) << 33)
Power control requests supported.
LL_FEAT_PRIVACY
#define LL_FEAT_PRIVACY (UINT64_C(1) << 6)
LL Privacy supported.
LL_FEAT_RECV_CTE
#define LL_FEAT_RECV_CTE (UINT64_C(1) << 23)
Receive Constant Tone Extension supported
LL_FEAT_REMOTE_PUB_KEY_VALIDATION
#define LL_FEAT_REMOTE_PUB_KEY_VALIDATION (UINT64_C(1) << 27)
Remote Public Key Validation supported.
LL_FEAT_SCA_UPDATE
#define LL_FEAT_SCA_UPDATE (UINT64_C(1) << 26)
Sleep Clock Accuracy Updates supported.
LL_FEAT_SLV_INIT_FEAT_EXCH
#define LL_FEAT_SLV_INIT_FEAT_EXCH (UINT64_C(1) << 3)
Slave-Initiated Features Exchange supported.
LL_FEAT_STABLE_MOD_IDX_RECEIVER
#define LL_FEAT_STABLE_MOD_IDX_RECEIVER (UINT64_C(1) << 10)
Stable Modulation Index - Receiver supported.
LL_FEAT_STABLE_MOD_IDX_TRANSMITTER
#define LL_FEAT_STABLE_MOD_IDX_TRANSMITTER (UINT64_C(1) << 9)
Stable Modulation Index - Transmitter supported.
LL_HOST_CONTROLLED_FEAT
#define LL_HOST_CONTROLLED_FEAT LL_FEAT_ISO_HOST_SUPPORT
Feature bits controlled by the host.
LL_SUP_STATE_ACT_SCAN
#define LL_SUP_STATE_ACT_SCAN (UINT64_C(1) << 5)
Active Scanning State supported.
LL_SUP_STATE_ACT_SCAN_AND_INIT
#define LL_SUP_STATE_ACT_SCAN_AND_INIT (UINT64_C(1) << 23)
Active Scanning State and Initiating State combination supported.
LL_SUP_STATE_ACT_SCAN_MST
#define LL_SUP_STATE_ACT_SCAN_MST (UINT64_C(1) << 25)
Active Scanning State and Master Role combination supported.
LL_SUP_STATE_ACT_SCAN_SLV
#define LL_SUP_STATE_ACT_SCAN_SLV (UINT64_C(1) << 27)
Active Scanning state and Slave Role combination supported.
LL_SUP_STATE_CONN_ADV
#define LL_SUP_STATE_CONN_ADV (UINT64_C(1) << 2)
Connectable Advertising State supported.
LL_SUP_STATE_CONN_ADV_AND_ACT_SCAN
#define LL_SUP_STATE_CONN_ADV_AND_ACT_SCAN (UINT64_C(1) << 14)
Connectable Advertising State and Active Scanning State combination supported.
LL_SUP_STATE_CONN_ADV_AND_INIT
#define LL_SUP_STATE_CONN_ADV_AND_INIT (UINT64_C(1) << 32)
Connectable Advertising State and Initiating State combination supported.
LL_SUP_STATE_CONN_ADV_AND_PASS_SCAN
#define LL_SUP_STATE_CONN_ADV_AND_PASS_SCAN (UINT64_C(1) << 10)
Connectable Advertising State and Passive Scanning State combination supported.
LL_SUP_STATE_CONN_ADV_MST
#define LL_SUP_STATE_CONN_ADV_MST (UINT64_C(1) << 35)
Connectable Advertising State and Master Role combination supported.
LL_SUP_STATE_CONN_ADV_SLV
#define LL_SUP_STATE_CONN_ADV_SLV (UINT64_C(1) << 38)
Connectable Advertising State and Slave Role combination supported.
LL_SUP_STATE_CONN_SLV
#define LL_SUP_STATE_CONN_SLV (UINT64_C(1) << 7)
Connection State in the Slave Role supported.
LL_SUP_STATE_HI_DUTY_DIR_ADV
#define LL_SUP_STATE_HI_DUTY_DIR_ADV (UINT64_C(1) << 3)
High Duty Cycle Directed Advertising State supported.
LL_SUP_STATE_HI_DUTY_DIR_ADV_ACT_SCAN
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_ACT_SCAN (UINT64_C(1) << 15)
Directed Advertising State and Active Scanning State combination supported.
LL_SUP_STATE_HI_DUTY_DIR_ADV_AND_INIT
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_AND_INIT (UINT64_C(1) << 33)
High Duty Cycle Directed Advertising and Initiating combination supported.
LL_SUP_STATE_HI_DUTY_DIR_ADV_AND_PASS_SCAN
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_AND_PASS_SCAN (UINT64_C(1) << 11)
Directed Advertising State and Passive Scanning State combination supported.
LL_SUP_STATE_HI_DUTY_DIR_ADV_MST
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_MST (UINT64_C(1) << 36)
High Duty Cycle Directed Advertising and Master Role combination supported.
LL_SUP_STATE_HI_DUTY_DIR_ADV_SLV
#define LL_SUP_STATE_HI_DUTY_DIR_ADV_SLV (UINT64_C(1) << 39)
High Duty Cycle Directed Advertising and Slave Role combination supported.
LL_SUP_STATE_INIT
#define LL_SUP_STATE_INIT (UINT64_C(1) << 6)
Initiating State supported. Connection State in the Master Role supported is also supported.
LL_SUP_STATE_INIT_MST
#define LL_SUP_STATE_INIT_MST (UINT64_C(1) << 28)
Initiating State and Master Role combination supported. Master Role and Master Role combination is also supported.
LL_SUP_STATE_INIT_SLV
#define LL_SUP_STATE_INIT_SLV (UINT64_C(1) << 41)
Initiating State and Slave Role combination.
LL_SUP_STATE_LO_DUTY_DIR_ADV
#define LL_SUP_STATE_LO_DUTY_DIR_ADV (UINT64_C(1) << 29)
Low Duty Cycle Directed Advertising State.
LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_ACT_SCAN
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_ACT_SCAN (UINT64_C(1) << 31)
Low Duty Cycle Directed Advertising and Active Scanning State combination supported.
LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_INIT
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_INIT (UINT64_C(1) << 34)
Low Duty Cycle Directed Advertising and Initiating combination supported.
LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_PASS_SCAN
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_AND_PASS_SCAN (UINT64_C(1) << 30)
Low Duty Cycle Directed Advertising and Passive Scanning State combination supported.
LL_SUP_STATE_LO_DUTY_DIR_ADV_MST
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_MST (UINT64_C(1) << 37)
Low Duty Cycle Directed Advertising and Master Role combination supported.
LL_SUP_STATE_LO_DUTY_DIR_ADV_SLV
#define LL_SUP_STATE_LO_DUTY_DIR_ADV_SLV (UINT64_C(1) << 40)
Low Duty Cycle Directed Advertising and Slave Role combination supported.
LL_SUP_STATE_NON_CONN_ADV
#define LL_SUP_STATE_NON_CONN_ADV (UINT64_C(1) << 0)
Non-connectable Advertising State supported.
LL_SUP_STATE_NON_CONN_ADV_AND_ACT_SCAN
#define LL_SUP_STATE_NON_CONN_ADV_AND_ACT_SCAN (UINT64_C(1) << 12)
Non-connectable Advertising State and Active Scanning State combination supported.
LL_SUP_STATE_NON_CONN_ADV_AND_INIT
#define LL_SUP_STATE_NON_CONN_ADV_AND_INIT (UINT64_C(1) << 16)
Non-connectable Advertising State and Initiating State combination supported.
LL_SUP_STATE_NON_CONN_ADV_AND_PASS_SCAN
#define LL_SUP_STATE_NON_CONN_ADV_AND_PASS_SCAN (UINT64_C(1) << 8)
Non-connectable Advertising State and Passive Scanning State combination supported.
LL_SUP_STATE_NON_CONN_ADV_MST
#define LL_SUP_STATE_NON_CONN_ADV_MST (UINT64_C(1) << 18)
Non-connectable Advertising State and Master Role combination supported.
LL_SUP_STATE_NON_CONN_ADV_SLV
#define LL_SUP_STATE_NON_CONN_ADV_SLV (UINT64_C(1) << 20)
Non-connectable Advertising State and Slave Role combination supported.
LL_SUP_STATE_PASS_SCAN
#define LL_SUP_STATE_PASS_SCAN (UINT64_C(1) << 4)
Passive Scanning State supported.
LL_SUP_STATE_PASS_SCAN_AND_INIT
#define LL_SUP_STATE_PASS_SCAN_AND_INIT (UINT64_C(1) << 22)
Passive Scanning State and Initiating State combination supported.
LL_SUP_STATE_PASS_SCAN_MST
#define LL_SUP_STATE_PASS_SCAN_MST (UINT64_C(1) << 24)
Passive Scanning State and Master Role combination supported.
LL_SUP_STATE_PASS_SCAN_SLV
#define LL_SUP_STATE_PASS_SCAN_SLV (UINT64_C(1) << 26)
Passive Scanning state and Slave Role combination supported.
LL_SUP_STATE_SCAN_ADV
#define LL_SUP_STATE_SCAN_ADV (UINT64_C(1) << 1)
Scannable Advertising State supported.
LL_SUP_STATE_SCAN_ADV_AND_ACT_SCAN
#define LL_SUP_STATE_SCAN_ADV_AND_ACT_SCAN (UINT64_C(1) << 13)
Scannable Advertising State and Active Scanning State combination supported.
LL_SUP_STATE_SCAN_ADV_AND_INIT
#define LL_SUP_STATE_SCAN_ADV_AND_INIT (UINT64_C(1) << 17)
Scannable Advertising State and Initiating State combination supported
LL_SUP_STATE_SCAN_ADV_AND_PASS_SCAN
#define LL_SUP_STATE_SCAN_ADV_AND_PASS_SCAN (UINT64_C(1) << 9)
Scannable Advertising State and Passive Scanning State combination supported.
LL_SUP_STATE_SCAN_ADV_MST
#define LL_SUP_STATE_SCAN_ADV_MST (UINT64_C(1) << 19)
Scannable Advertising State and Master Role combination supported.
LL_SUP_STATE_SCAN_ADV_SLV
#define LL_SUP_STATE_SCAN_ADV_SLV (UINT64_C(1) << 21)
Scannable Advertising State and Slave Role combination supported.
Enumeration Type Documentation
anonymous enum
anonymous enum
Operational mode flags.
Enumerator
LL_OP_MODE_FLAG_ENA_VER_LLCP_STARTUP
Perform version exchange LLCP at connection establishment.
LL_OP_MODE_FLAG_SLV_REQ_IMMED_ACK
MD bit set if data transmitted.
LL_OP_MODE_FLAG_BYPASS_CE_GUARD
Bypass end of CE guard.
LL_OP_MODE_FLAG_MST_RETX_AFTER_RX_NACK
Master retransmits after receiving NACK.
LL_OP_MODE_FLAG_MST_IGNORE_CP_RSP
Master ignores LL_CONNECTION_PARAM_RSP.
LL_OP_MODE_FLAG_MST_UNCOND_CP_RSP
Master unconditionally accepts LL_CONNECTION_PARAM_RSP. (LL_OP_MODE_FLAG_MST_IGNORE_CP_RSP must be cleared).
LL_OP_MODE_FLAG_ENA_LEN_LLCP_STARTUP
Perform data length update LLCP at connection establishment.
LL_OP_MODE_FLAG_REQ_SYM_PHY
Require symmetric PHYs for connection.
LL_OP_MODE_FLAG_ENA_FEAT_LLCP_STARTUP
Perform feature exchange LLCP at connection establishment.
LL_OP_MODE_FLAG_SLV_DELAY_LLCP_STARTUP
Slave delays LLCP startup procedures.
LL_OP_MODE_FLAG_ENA_SLV_LATENCY_WAKEUP
Enable slave latency wake up upon data pending.
LL_OP_MODE_FLAG_ENA_SLV_AUX_SCAN_RSP_ADI
Enable ADI field for aux scan.
LL_OP_MODE_FLAG_ENA_MST_CIS_NULL_PDU
Enable CIS master sends additional NULL PDU for acknowledge scheme.
LL_OP_MODE_FLAG_ENA_SLV_AUX_IND_ADVA
AdvA will be included in AUX_ADV_IND instead of ADV_EXT_IND.
LL_OP_MODE_FLAG_ENA_ADV_CHAN_RAND
Enable advertising channel randomization.
LL_OP_MODE_DISABLE_POWER_MONITOR
Disable power monitoring.
LL_OP_MODE_FLAG_ENA_ADV_DLY
Enable advertising delay.
LL_OP_MODE_FLAG_ENA_SCAN_BACKOFF
Enable scan backoff.
LL_OP_MODE_FLAG_ENA_WW
Enable window widening.
LL_OP_MODE_FLAG_ENA_SLV_LATENCY
Enable slave latency.
LL_OP_MODE_FLAG_ENA_LLCP_TIMER
Enable LLCP timer.
LL_OP_MODE_FLAG_IGNORE_CRC_ERR_TS
Ignore timestamp of RX packet with CRC error.
LL_OP_MODE_FLAG_SLV_CRC_CLOSE
Close the connection event on receiving a CRC error.
LlRole_t
enum LlRole_t
This parameter identifies the device role.
Enumerator
LL_ROLE_MASTER
Role is master.
LL_ROLE_SLAVE
Role is slave.
Function Documentation
LlAddDeviceToResolvingList()
uint8_t LlAddDeviceToResolvingList (uint8_t peerAddrType, const uint8_t * pPeerIdentityAddr, const uint8_t * pPeerIrk, const uint8_t * pLocalIrk)
Add device to resolving list.
Parameters
peerAddrType Peer identity address type.
pPeerIdentityAddr Peer identity address.
pPeerIrk Peer IRK.
pLocalIrk Local IRK.
Returns
Status error code.
Add device to resolving list.
References lmgrCtrlBlk_t::addrResEna, lmgrCtrlBlk_t::advEnabled, BbBleResListAdd(), BstreamToBda64(), LctrMstPerSyncPending, LL_ADDR_RANDOM, lmgrCb, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, and lmgrCtrlBlk_t::numScanEnabled.
LlAddDeviceToWhitelist()
uint8_t LlAddDeviceToWhitelist (uint8_t addrType, bdAddr_t pAddr)
Add device to the white list.
Parameters
addrType Address type.
pAddr Bluetooth device address.
Returns
Status error code.
Adds the given address to the white list stored in the LL.
Note
This function must only be called when advertising or scan is disabled and not initiating.
References BbBleWhiteListAdd(), BbBleWhiteListAddAnonymous(), BstreamToBda64(), LlRtCfg_t::btVer, LL_ADDR_ANONYMOUS, LL_ADDR_RANDOM, lmgrCb, lmgrCtrlBlk_t::numWlFilterEnabled, and pLctrRtCfg.
LlClearResolvingList()
uint8_t LlClearResolvingList (void)
Clear resolving list.
Returns
Status error code.
Clear resolving list.
References lmgrCtrlBlk_t::addrResEna, lmgrCtrlBlk_t::advEnabled, BbBleResListClear(), LctrMstPerSyncPending, lmgrCb, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, and lmgrCtrlBlk_t::numScanEnabled.
LlClearWhitelist()
uint8_t LlClearWhitelist (void)
Clear all white list entries.
Returns
Status error code.
Clear all white list entries stored in the LL.
Note
This function must only be called when advertising or scan is disabled and not initiating.
References BbBleWhiteListClear(), lmgrCb, and lmgrCtrlBlk_t::numWlFilterEnabled.
LlGenerateDhKey()
uint8_t LlGenerateDhKey (const uint8_t pubKey_x[LL_ECC_KEY_LEN], const uint8_t pubKey_y[LL_ECC_KEY_LEN])
Generate a Diffie-Hellman key.
Parameters
pubKey_x Remote public key x-coordinate.
pubKey_y Remote public key y-coordinate.
Returns
Status error code.
Generate a Diffie-Hellman key from a remote public key and the local private key. If another ECC operation (P-256 key pair or Diffie-Hellman key generation) is ongoing, an error will be returned.
Parameters
pubKey_x Remote public key x-coordinate.
pubKey_y Remote public key y-coordinate.
Returns
Status error code.
Generate a Diffie-Hellman key from a remote public key and the local private key. If another ECC operation (P-256 key pair generation or Diffie-Hellman key generation) is ongoing, an error will be returned.
References LctrGenerateDhKey(), lmgrScCb, and lmgrScCtrlBlk_t::privKey.
LlGenerateDhKeyV2()
uint8_t LlGenerateDhKeyV2 (uint8_t pubKey_x[LL_ECC_KEY_LEN], uint8_t pubKey_y[LL_ECC_KEY_LEN], uint8_t keyType)
Generate a Diffie-Hellman key.
Parameters
pubKey_x Remote public key x-coordinate.
pubKey_y Remote public key y-coordinate.
keyType debug enable
Returns
Status error code.
Generate a Diffie-Hellman key from a remote public key and the local private key. If another ECC operation (P-256 key pair or Diffie-Hellman key generation) is ongoing, an error will be returned. If keyType == 1, debug keys will be used in place for the keys.
Parameters
pubKey_x Remote public key x-coordinate.
pubKey_y Remote public key y-coordinate.
keyType Debug enable
Returns
Status error code.
Generate a Diffie-Hellman key from a remote public key and the local private key. If another ECC operation (P-256 key pair generation or Diffie-Hellman key generation) is ongoing, an error will be returned. If keyType == HCI_PRIVATE_KEY_DEBUG, debug keys will be used.
References HCI_PRIVATE_KEY_DEBUG, LctrGenerateDebugDhKey(), LctrGenerateDhKey(), lmgrScCb, and lmgrScCtrlBlk_t::privKey.
LlGenerateP256KeyPair()
uint8_t LlGenerateP256KeyPair (void)
Generate a P-256 public/private key pair.
Returns
Status error code.
Generate a P-256 public/private key pair. If another ECC operation (P-256 key pair or Diffie- Hellman key generation) is ongoing, an error will be returned.
Returns
Status error code.
Generate a P-256 public/private key pair. If another ECC operation (P-256 key pair generation or Diffie-Hellman key generation) is ongoing, an error will be returned.
References LctrGenerateP256KeyPair().
LlGetBdAddr()
void LlGetBdAddr (uint8_t * pAddr)
Get Bluetooth device address.
Parameters
pAddr Bluetooth device address.
Get the BD address currently used by LL or all zeros if address is not set.
References BDA64_TO_BSTREAM, lmgrPersistCtrlBlk_t::bdAddr, lmgrPersistCb, and WSF_ASSERT.
LlGetFeatures()
void LlGetFeatures (uint8_t * pFeatures)
Get features.
Parameters
pFeatures Supported features bitmask.
Return the LE features supported by the LL.
References lmgrCtrlBlk_t::features, lmgrCb, UINT64_TO_BSTREAM, and WSF_ASSERT.
LlGetRandAddr()
uint8_t LlGetRandAddr (uint8_t * pAddr)
Get random device address.
Parameters
pAddr Random Bluetooth device address.
Returns
Status error code.
Get the random address currently used by LL or all zeros if address is not set.
References BDA64_TO_BSTREAM, lmgrCtrlBlk_t::bdAddrRnd, lmgrCtrlBlk_t::bdAddrRndValid, lmgrCb, and WSF_ASSERT.
LlGetRandNum()
uint8_t LlGetRandNum (uint8_t * pRandNum)
Get random number.
Parameters
pRandNum Buffer to store 8 bytes random data.
Returns
Status error code.
Request the LL to generate a random number.
References PalCryptoGenerateRandomNumber(), and WSF_ASSERT.
LlGetSupStates()
void LlGetSupStates (uint8_t * pStates)
Get supported states.
Parameters
pStates Supported states bitmask.
Return the states supported by the LL.
References lmgrPersistCb, lmgrPersistCtrlBlk_t::supStates, UINT64_TO_BSTREAM, and WSF_ASSERT.
LlGetVersion()
void LlGetVersion (uint16_t * pCompId, uint8_t * pBtVer, uint16_t * pImplRev)
Get versions.
Parameters
pCompId Company ID.
pBtVer Bluetooth version.
pImplRev Implementation revision.
References LlRtCfg_t::btVer, LlRtCfg_t::compId, LlRtCfg_t::implRev, and pLctrRtCfg.
LlGetWhitelistSize()
uint8_t LlGetWhitelistSize (void)
Get white list size.
Returns
Total number of white list entries.
Read the white list capacity supported by the LL.
References BbBleWhiteListGetSize().
LlReadLocalResolvableAddr()
uint8_t LlReadLocalResolvableAddr (uint8_t addrType, const uint8_t * pIdentityAddr, uint8_t * pRpa)
Read local resolvable address.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
pRpa Storage for peer resolvable private address
Returns
Status error code.
Get the local resolvable private address that is currently being used for the peer identity address.
References BbBleResListReadLocal(), Bda64ToBstream(), BstreamToBda64(), and LL_ADDR_RANDOM.
LlReadPeerResolvableAddr()
uint8_t LlReadPeerResolvableAddr (uint8_t addrType, const uint8_t * pIdentityAddr, uint8_t * pRpa)
Read peer resolvable address.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
pRpa Storage for peer resolvable private address
Returns
Status error code.
Get the peer resolvable private address that is currently being used for the peer identity address.
References BbBleResListReadPeer(), Bda64ToBstream(), BstreamToBda64(), and LL_ADDR_RANDOM.
LlReadResolvingListSize()
uint8_t LlReadResolvingListSize (uint8_t * pSize)
Read resolving list size.
Parameters
pSize Storage for resolving list size.
Returns
Status error code.
Read number of address translation entries that can be stored in the resolving list.
References BbBleResListGetSize().
LlRemoveDeviceFromResolvingList()
uint8_t LlRemoveDeviceFromResolvingList (uint8_t peerAddrType, const uint8_t * pPeerIdentityAddr)
Remove device from resolving list.
Parameters
peerAddrType Peer identity address type.
pPeerIdentityAddr Peer identity address.
Returns
Status error code.
Remove device from resolving list.
References lmgrCtrlBlk_t::addrResEna, lmgrCtrlBlk_t::advEnabled, BbBleResListRemove(), BstreamToBda64(), LctrMstPerSyncPending, LL_ADDR_RANDOM, lmgrCb, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, and lmgrCtrlBlk_t::numScanEnabled.
LlRemoveDeviceFromWhitelist()
uint8_t LlRemoveDeviceFromWhitelist (uint8_t addrType, bdAddr_t pAddr)
Remove device from the white list.
Parameters
addrType Address type.
pAddr Bluetooth device address.
Returns
Status error code.
Removes the given address from the white list stored in the LL.
Note
This function must only be called when advertising or scan is disabled and not initiating.
References BbBleWhiteListRemove(), BbBleWhiteListRemoveAnonymous(), BstreamToBda64(), LlRtCfg_t::btVer, LL_ADDR_ANONYMOUS, LL_ADDR_RANDOM, lmgrCb, lmgrCtrlBlk_t::numWlFilterEnabled, and pLctrRtCfg.
LlSetAddrResolutionEnable()
uint8_t LlSetAddrResolutionEnable (uint8_t enable)
Enable or disable address resolution.
Parameters
enable Set to TRUE to enable address resolution or FALSE to disable address resolution.
Returns
Status error code.
Enable or disable address resolution so that received local or peer resolvable private addresses are resolved.
References lmgrCtrlBlk_t::addrResEna, lmgrCtrlBlk_t::advEnabled, LctrMstPerSyncPending, lmgrCb, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, and lmgrCtrlBlk_t::numScanEnabled.
LlSetBdAddr()
void LlSetBdAddr (const uint8_t * pAddr)
Set Bluetooth device address.
Parameters
pAddr Bluetooth device address.
Set the BD address to be used by LL.
References lmgrPersistCtrlBlk_t::bdAddr, BSTREAM_TO_BDA64, and lmgrPersistCb.
LlSetChannelClass()
uint8_t LlSetChannelClass (const uint8_t * pChanMap)
Set channel class.
Parameters
pChanMap Channel map (0=bad, 1=usable).
Returns
Status error code.
Set the channel class. At least 2 bits must be set.
References BSTREAM_TO_UINT40, and LctrSetChannelClass().
LlSetDefaultExtAdvTxPhyOptions()
void LlSetDefaultExtAdvTxPhyOptions (const uint8_t phyOptions)
Set the default Ext adv TX PHY options.
Parameters
phyOptions PHY options.
Set the default TX PHY options for extended adv slave primary and secondary channel.
References lmgrSlvAdvCtrlBlk_t::defTxPhyOpts, and lmgrSlvAdvCb.
LlSetFeatures()
uint8_t LlSetFeatures (const uint8_t * pFeatures)
Set features.
Parameters
pFeatures Supported features bitmask.
Returns
Status error code.
Note
This function must only be called when controller is not connected to another device.
Set the LE features supported by the LL.
References BSTREAM_TO_UINT64, lmgrCtrlBlk_t::features, LL_FEAT_ALL_MASK, lmgrCb, and WSF_ASSERT.
LlSetHostFeatures()
uint8_t LlSetHostFeatures (uint8_t bitNum, bool_t bitVal)
Set host feature.
Parameters
bitNum Bit position in the FeatureSet.
bitVal Enable or disable feature.
Returns
Status error code.
Set or clear a bit in the feature controlled by the Host in the Link Layer FeatureSet stored in the Controller.
LlSetOpFlags()
uint8_t LlSetOpFlags (uint32_t flags, bool_t enable)
Set operational mode flags.
Parameters
flags Flags.
enable TRUE to set flags or FALSE to clear flags.
Returns
Status error code.
Set mode flags governing LL operations.
Parameters
flags Flags.
enable TRUE to enable flags, FALSE to disable.
Returns
Status error code.
Set mode flags governing LL operations.
LlSetP256PrivateKey()
uint8_t LlSetP256PrivateKey (const uint8_t privKey[LL_ECC_KEY_LEN])
Set P-256 private key for debug purposes.
Parameters
privKey Private key, or all zeros to clear set private key.
Returns
Status error code.
Set P-256 private key or clear set private key. The private key will be used for generate key pairs and Diffie-Hellman keys until cleared.
LlSetPrivacyMode()
uint8_t LlSetPrivacyMode (uint8_t peerAddrType, const uint8_t * pPeerIdentityAddr, uint8_t privMode)
Set privacy mode.
Parameters
peerAddrType Peer identity address type.
pPeerIdentityAddr Peer identity address.
privMode Privacy mode.
Returns
Status error code.
Allow the host to specify the privacy mode to be used for a given entry on the resolving list.
References lmgrCtrlBlk_t::addrResEna, lmgrCtrlBlk_t::advEnabled, BbBleResListSetPrivacyMode(), BstreamToBda64(), LctrMstPerSyncPending, LL_ADDR_RANDOM, LL_PRIV_MODE_DEVICE, lmgrCb, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, and lmgrCtrlBlk_t::numScanEnabled.
LlSetRandAddr()
uint8_t LlSetRandAddr (const uint8_t * pAddr)
Set random device address.
Parameters
pAddr Random Bluetooth device address.
Returns
Status.
Set the random address to be used by LL.
References lmgrCtrlBlk_t::advEnabled, lmgrSlvAdvCtrlBlk_t::advParam, lmgrCtrlBlk_t::bdAddrRnd, lmgrCtrlBlk_t::bdAddrRndValid, BSTREAM_TO_BDA64, LctrMstExtInitEnabled, LctrMstExtScanEnabled, LctrMstInitIsEnabled(), LctrMstScanIsEnabled(), lmgrCb, lmgrSlvAdvCb, lmgrCtrlBlk_t::numInitEnabled, lmgrCtrlBlk_t::numScanEnabled, lmgrAdvParam_t::ownAddrType, WSF_ASSERT, WSF_CS_ENTER, and WSF_CS_INIT.
LlSetResolvablePrivateAddrTimeout()
uint8_t LlSetResolvablePrivateAddrTimeout (uint16_t rpaTimeout)
Set resolvable private address timeout.
Parameters
rpaTimeout Timeout measured in seconds.
Returns
Status error code.
Set the time period between automatic generation of new resolvable private addresses.
References LctrPrivSetResPrivAddrTimeout().
LlSetValidatePublicKeyMode()
uint8_t LlSetValidatePublicKeyMode (uint8_t validateMode)
Set validate public key mode.
Parameters
validateMode ALT1 or ALT2.
Returns
Status error code.
References KEY_VALIDATE_MODE_MAX, and LctrSetValidatePublicKeyMode().