Cordio: PAL_UART
PAL_UART
Data Structures
struct PalUartConfig_t
Typedefs
typedef void(* PalUartCompCback_t) (void)
Enumerations
enum PalUartState_t
enum PalUartId_t
Functions
void PalUartInit (PalUartId_t id, const PalUartConfig_t *pCfg)
void PalUartDeInit (PalUartId_t id)
PalUartState_t PalUartGetState (PalUartId_t id)
void PalUartReadData (PalUartId_t id, uint8_t *pData, uint16_t len)
void PalUartWriteData (PalUartId_t id, const uint8_t *pData, uint16_t len)
Detailed Description
Data Structure Documentation
PalUartConfig_t
struct PalUartConfig_t
Peripheral configuration.
Data Fields
PalUartCompCback_t rdCback
PalUartCompCback_t wrCback
uint32_t baud
bool_t hwFlow
Field Documentation
baud
uint32_t baud
Baud rate.
hwFlow
bool_t hwFlow
Use HW Flow control
rdCback
PalUartCompCback_t rdCback
Read data completion callback.
wrCback
PalUartCompCback_t wrCback
Write data completion callback.
Enumeration Type Documentation
PalUartId_t
enum PalUartId_t
Reserved UART ID.
Enumerator
PAL_UART_ID_USER
UART 0.
PAL_UART_ID_CHCI
UART CHCI.
PAL_UART_ID_TERMINAL
UART TERMINAL.
PAL_UART_ID_MAX
Number of UART instances.
PalUartState_t
enum PalUartState_t
Operational states.
Enumerator
PAL_UART_STATE_UNINIT
Uninitialized state.
PAL_UART_STATE_ERROR
Error state.
PAL_UART_STATE_READY
Ready state.
PAL_UART_STATE_BUSY
Busy state.
Function Documentation
PalUartDeInit()
void PalUartDeInit (PalUartId_t id)
De-Initialize UART.
Parameters
id UART id.
Returns
None.
De-Initialize UART.
References PAL_SYS_ASSERT, and PAL_UART_STATE_UNINIT.
PalUartGetState()
PalUartState_t PalUartGetState (PalUartId_t id)
Get the current state.
Parameters
id UART id.
Returns
Current state.
Return the current state.
References PAL_SYS_ASSERT, and PAL_UART_STATE_ERROR.
PalUartInit()
void PalUartInit (PalUartId_t id, const PalUartConfig_t * pCfg)
Initialize UART.
Parameters
id UART Id.
pCfg Peripheral configuration.
Returns
None.
Initialize UART peripheral with pCfg values.
References PalUartConfig_t::baud, PalUartConfig_t::hwFlow, PAL_SYS_ASSERT, PAL_UART_ID_CHCI, PAL_UART_STATE_READY, PalUartConfig_t::rdCback, and PalUartConfig_t::wrCback.
PalUartReadData()
void PalUartReadData (PalUartId_t id, uint8_t * pData, uint16_t len)
Read data from Rx FIFO.
Parameters
id UART id.
pData Read buffer.
len Number of bytes to read.
Returns
None.
Store len received bytes in pData. After len is transferred, call UartInitInfo_t::rdCback to signal read completion. Alway call this function to setup buffer when boot up or after a reading is done
References PAL_SYS_ASSERT, PAL_UART_ID_CHCI, WsfCsEnter(), and WsfCsExit().
PalUartWriteData()
void PalUartWriteData (PalUartId_t id, const uint8_t * pData, uint16_t len)
Write data to Tx FIFO.
Parameters
id UART id.
pData Write buffer.
len Number of bytes to write.
Returns
None.
Assign buffer and length and transmit data.
References PAL_SYS_ASSERT, PAL_UART_ID_CHCI, PAL_UART_STATE_BUSY, WsfCsEnter(), and WsfCsExit().