Cordio: Local Configuration API
Local Configuration API
Data Structures
struct meshModelId_t
struct meshLocalCfgModelSubscrListEntry_t
struct meshLocalCfgModelPublication_t
struct meshLocalCfgModelEntry_t
struct meshLocalCfgModelInfo_t
struct meshLocalCfgAttTmr_t
struct meshLocalCfgElementInfo_t
struct meshLocalCfgAddressListEntry_t
struct meshLocalCfgAddressListInfo_t
struct meshLocalCfgVirtualAddrListEntry_t
struct meshLocalCfgVirtualAddrListInfo_t
struct meshLocalCfgAppKeyBindListInfo_t
struct meshLocalCfgAppKeyListEntry_t
struct meshLocalCfgAppKeyListInfo_t
struct meshLocalCfgNetKeyListEntry_t
struct meshLocalCfgNetKeyListInfo_t
struct meshLocalCfgFriendSubscrEventParams_t
Typedefs
typedef uint16_t meshLocalCfgRetVal_t
typedef void(* meshLocalCfgFriendSubscrEventNotifyCback_t) (meshLocalCfgFriendSubscrEvent_t event, const meshLocalCfgFriendSubscrEventParams_t *pEventParams)
typedef meshNodeIdentityStates_t meshLocalCfgNodeIdentityListEntry_t
typedef uint8_t meshLocalCfgFriendSubscrEvent_t
Enumerations
enum meshLocalCfgFriendSubscrEventTypes
Functions
uint32_t MeshLocalCfgGetRequiredMemory (void)
void MeshLocalCfgInit (void)
void MeshLocalCfgRegisterLpn (meshLocalCfgFriendSubscrEventNotifyCback_t friendSubscrEventCback)
meshLocalCfgRetVal_t MeshLocalCfgSetPrimaryNodeAddress (meshAddress_t address)
meshLocalCfgRetVal_t MeshLocalCfgGetElementFromAddress (meshAddress_t elementAddress, const meshElement_t **ppOutElement)
meshLocalCfgRetVal_t MeshLocalCfgGetElementFromId (meshElementId_t elementId, const meshElement_t **ppOutElement)
meshLocalCfgRetVal_t MeshLocalCfgGetAddrFromElementId (meshElementId_t elementId, meshAddress_t *pOutAddress)
meshLocalCfgRetVal_t MeshLocalCfgGetElementIdFromAddr (meshAddress_t elementAddress, meshElementId_t *pOutElementId)
meshLocalCfgRetVal_t MeshLocalCfgGetVirtualAddrFromLabelUuid (const uint8_t *pLabelUuid, meshAddress_t *pOutVirtualAddr)
void MeshLocalCfgSetProductInformation (const meshProdInfo_t *pProdInfo)
void MeshLocalCfgGetProductInformation (meshProdInfo_t *pOutProdInfo)
meshFeatures_t MeshLocalCfgGetSupportedFeatures (void)
bool_t MeshLocalCfgModelExists (meshElementId_t elementId, const meshModelId_t *pModelId)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishAddress (meshElementId_t elementId, const meshModelId_t *pModelId, meshAddress_t publishAddress)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishAddress (meshElementId_t elementId, const meshModelId_t *pModelId, meshAddress_t *pOutPublishAddress, uint8_t **ppOutLabelUuid)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishVirtualAddr (meshElementId_t elementId, const meshModelId_t *pModelId, const uint8_t *pLabelUuid, meshAddress_t virtualAddr)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishPeriod (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishPeriodNumSteps_t numberOfSteps, meshPublishPeriodStepRes_t stepResolution)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishPeriod (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishPeriodNumSteps_t *pOutNumberOfSteps, meshPublishPeriodStepRes_t *pOutStepResolution)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishAppKeyIndex (meshElementId_t elementId, const meshModelId_t *pModelId, uint16_t appKeyIndex)
void MeshLocalCfgMdlClearPublishAppKeyIndex (meshElementId_t elementId, const meshModelId_t *pModelId)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishAppKeyIndex (meshElementId_t elementId, const meshModelId_t *pModelId, uint16_t *pOutAppKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishFriendshipCredFlag (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishFriendshipCred_t friendshipCredFlag)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishFriendshipCredFlag (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishFriendshipCred_t *pOutFriendshipCredFlag)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishTtl (meshElementId_t elementId, const meshModelId_t *pModelId, uint8_t publishTtl)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishTtl (meshElementId_t elementId, const meshModelId_t *pModelId, uint8_t *pOutPublishTtl)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishRetransCount (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishRetransCount_t retransCount)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishRetransCount (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishRetransCount_t *pOutRetransCount)
meshLocalCfgRetVal_t MeshLocalCfgSetPublishRetransIntvlSteps (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishRetransIntvlSteps_t retransSteps)
meshLocalCfgRetVal_t MeshLocalCfgGetPublishRetransIntvlSteps (meshElementId_t elementId, const meshModelId_t *pModelId, meshPublishRetransIntvlSteps_t *pOutRetransSteps)
meshLocalCfgRetVal_t MeshLocalCfgAddAddressToSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId, meshAddress_t subscrAddress)
meshLocalCfgRetVal_t MeshLocalCfgGetNextAddressFromSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId, meshAddress_t *pOutSubscAddress, uint8_t *pInOutStartIndex)
bool_t MeshLocalCfgFindAddrInModelSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId, meshAddress_t subscrAddr, const uint8_t *pLabelUuid)
meshLocalCfgRetVal_t MeshLocalCfgRemoveAddressFromSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId, meshAddress_t address)
meshLocalCfgRetVal_t MeshLocalCfgAddVirtualAddrToSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId, const uint8_t *pLabelUuid, meshAddress_t virtualAddr)
meshLocalCfgRetVal_t MeshLocalCfgRemoveVirtualAddrFromSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId, const uint8_t *pLabelUuid)
meshLocalCfgRetVal_t MeshLocalCfgRemoveAllFromSubscrList (meshElementId_t elementId, const meshModelId_t *pModelId)
meshLocalCfgRetVal_t MeshLocalCfgGetSubscrListSize (meshElementId_t elementId, const meshModelId_t *pModelId, uint8_t *pOutNumAddr, uint8_t *pOutTotalSize)
bool_t MeshLocalCfgFindSubscrAddr (meshAddress_t subscrAddr)
bool_t MeshLocalCfgSubscrAddressListIsNotEmpty (void)
bool_t MeshLocalCfgSubscrVirtualAddrListIsNotEmpty (void)
meshLocalCfgRetVal_t MeshLocalCfgGetNextSubscrAddress (meshAddress_t *pOutSubscAddress, uint16_t *pInOutStartIndex)
meshLocalCfgRetVal_t MeshLocalCfgGetNextSubscrVirtualAddr (meshAddress_t *pOutSubscAddress, uint16_t *pInOutStartIndex)
void MeshLocalCfgSetDevKey (const uint8_t *pDevKey)
void MeshLocalCfgGetDevKey (uint8_t *pOutDevKey)
meshLocalCfgRetVal_t MeshLocalCfgSetNetKey (uint16_t netKeyIndex, const uint8_t *pNetKey)
meshLocalCfgRetVal_t MeshLocalCfgUpdateNetKey (uint16_t netKeyIndex, const uint8_t *pNetKey)
meshLocalCfgRetVal_t MeshLocalCfgRemoveNetKey (uint16_t netKeyIndex, bool_t removeOldKeyOnly)
meshLocalCfgRetVal_t MeshLocalCfgGetNetKey (uint16_t netKeyIndex, uint8_t *pOutNetKey)
meshLocalCfgRetVal_t MeshLocalCfgGetUpdatedNetKey (uint16_t netKeyIndex, uint8_t *pOutNetKey)
uint16_t MeshLocalCfgCountNetKeys (void)
meshLocalCfgRetVal_t MeshLocalCfgGetNextNetKeyIndex (uint16_t *pOutNetKeyIndex, uint16_t *pInOutIndex)
meshLocalCfgRetVal_t MeshLocalCfgSetAppKey (uint16_t appKeyIndex, const uint8_t *pAppKey)
meshLocalCfgRetVal_t MeshLocalCfgUpdateAppKey (uint16_t appKeyIndex, const uint8_t *pAppKey)
meshLocalCfgRetVal_t MeshLocalCfgRemoveAppKey (uint16_t appKeyIndex, bool_t removeOldKeyOnly)
meshLocalCfgRetVal_t MeshLocalCfgGetNextAppKeyIndex (uint16_t *pOutAppKeyIndex, uint16_t *pInOutIndex)
meshLocalCfgRetVal_t MeshLocalCfgGetAppKey (uint16_t appKeyIndex, uint8_t *pOutAppKey)
meshLocalCfgRetVal_t MeshLocalCfgGetUpdatedAppKey (uint16_t appKeyIndex, uint8_t *pOutAppKey)
meshLocalCfgRetVal_t MeshLocalCfgBindAppKeyToModel (meshElementId_t elementId, const meshModelId_t *pModelId, uint16_t appKeyIndex)
void MeshLocalCfgUnbindAppKeyFromModel (meshElementId_t elementId, const meshModelId_t *pModelId, uint16_t appKeyIndex)
bool_t MeshLocalCfgValidateModelToAppKeyBind (meshElementId_t elementId, meshModelId_t *pModelId, uint16_t appKeyIndex)
uint8_t MeshLocalCfgCountModelBoundAppKeys (meshElementId_t elementId, const meshModelId_t *pModelId)
meshLocalCfgRetVal_t MeshLocalCfgGetNextModelBoundAppKey (meshElementId_t elementId, const meshModelId_t *pModelId, uint16_t *pOutAppKeyIndex, uint8_t *pInOutIndex)
meshLocalCfgRetVal_t MeshLocalCfgBindAppKeyToNetKey (uint16_t appKeyIndex, uint16_t netKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgUnbindAppKeyToNetKey (uint16_t appKeyIndex, uint16_t netKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgGetBoundNetKeyIndex (uint16_t appKeyIndex, uint16_t *pOutNetKeyIndex)
uint16_t MeshLocalCfgCountBoundAppKeys (uint16_t netKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgGetNextBoundAppKey (uint16_t netKeyIndex, uint16_t *pOutAppKeyIndex, uint16_t *pInOutIndex)
bool_t MeshLocalCfgValidateNetToAppKeyBind (uint16_t netKeyIndex, uint16_t appKeyIndex)
void MeshLocalCfgGetVtadList (const meshLocalCfgVirtualAddrListInfo_t **ppVtadList)
void MeshLocalCfgSetDefaultTtl (uint8_t defaultTtl)
uint8_t MeshLocalCfgGetDefaultTtl (void)
void MeshLocalCfgSetRelayState (meshRelayStates_t relayState)
meshRelayStates_t MeshLocalCfgGetRelayState (void)
void MeshLocalCfgSetAttentionTimer (meshElementId_t elementId, uint8_t timerVal)
uint8_t MeshLocalCfgGetAttentionTimer (meshElementId_t elementId)
void MeshLocalCfgSetBeaconState (meshBeaconStates_t beaconState)
meshBeaconStates_t MeshLocalCfgGetBeaconState (void)
void MeshLocalCfgSetGattProxyState (meshGattProxyStates_t gattProxyState)
meshGattProxyStates_t MeshLocalCfgGetGattProxyState (void)
void MeshLocalCfgSetNodeIdentityState (uint16_t netKeyIndex, meshNodeIdentityStates_t nodeIdentityState)
meshNodeIdentityStates_t MeshLocalCfgGetNodeIdentityState (uint16_t netKeyIndex)
void MeshLocalCfgSetFriendState (meshFriendStates_t friendState)
meshFriendStates_t MeshLocalCfgGetFriendState (void)
void MeshLocalCfgSetLowPowerState (meshLowPowerStates_t lowPowerState)
meshLowPowerStates_t MeshLocalCfgGetLowPowerState (void)
void MeshLocalCfgSetKeyRefreshState (uint16_t netKeyIndex, meshKeyRefreshStates_t keyRefreshState)
meshKeyRefreshStates_t MeshLocalCfgGetKeyRefreshPhaseState (uint16_t netKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgSetHbPubDst (meshAddress_t dstAddress)
meshAddress_t MeshLocalCfgGetHbPubDst (void)
void MeshLocalCfgSetHbPubCountLog (uint8_t countLog)
uint8_t MeshLocalCfgGetHbPubCountLog (void)
void MeshLocalCfgSetHbPubPeriodLog (uint8_t periodLog)
uint8_t MeshLocalCfgGetHbPubPeriodLog (void)
void MeshLocalCfgSetHbPubTtl (uint8_t pubTtl)
uint8_t MeshLocalCfgGetHbPubTtl (void)
void MeshLocalCfgSetHbPubFeatures (meshFeatures_t pubFeatures)
meshFeatures_t MeshLocalCfgGetHbPubFeatures (void)
meshLocalCfgRetVal_t MeshLocalCfgSetHbPubNetKeyIndex (uint16_t netKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgGetHbPubNetKeyIndex (uint16_t *pOutNetKeyIndex)
meshLocalCfgRetVal_t MeshLocalCfgSetHbSubSrc (meshAddress_t srcAddress)
meshAddress_t MeshLocalCfgGetHbSubSrc (void)
meshLocalCfgRetVal_t MeshLocalCfgSetHbSubDst (meshAddress_t dstAddress)
meshAddress_t MeshLocalCfgGetHbSubDst (void)
void MeshLocalCfgSetHbSubCountLog (uint8_t countLog)
uint8_t MeshLocalCfgGetHbSubCountLog (void)
void MeshLocalCfgSetHbSubPeriodLog (uint8_t periodLog)
uint8_t MeshLocalCfgGetHbSubPeriodLog (void)
void MeshLocalCfgSetHbSubMinHops (uint8_t minHops)
uint8_t MeshLocalCfgGetHbSubMinHops (void)
void MeshLocalCfgSetHbSubMaxHops (uint8_t maxHops)
uint8_t MeshLocalCfgGetHbSubMaxHops (void)
void MeshLocalCfgSetNwkTransmitCount (uint8_t transCount)
uint8_t MeshLocalCfgGetNwkTransmitCount (void)
void MeshLocalCfgSetNwkTransmitIntvlSteps (uint8_t intvlSteps)
uint8_t MeshLocalCfgGetNwkTransmitIntvlSteps (void)
void MeshLocalCfgSetRelayRetransmitCount (uint8_t retransCount)
uint8_t MeshLocalCfgGetRelayRetransmitCount (void)
void MeshLocalCfgSetRelayRetransmitIntvlSteps (uint8_t intvlSteps)
uint8_t MeshLocalCfgGetRelayRetransmitIntvlSteps (void)
meshLocalCfgRetVal_t MeshLocalCfgSetSeqNumber (meshElementId_t elementId, meshSeqNumber_t seqNumber)
meshLocalCfgRetVal_t MeshLocalCfgGetSeqNumber (meshElementId_t elementId, meshSeqNumber_t *pOutSeqNumber)
void MeshLocalCfgSetSeqNumberThresh (meshElementId_t elementId, meshSeqNumber_t seqNumber)
meshSeqNumber_t MeshLocalCfgGetSeqNumberThresh (meshElementId_t elementId)
uint32_t MeshLocalCfgGetIvIndex (bool_t *pIvUpdtInProg)
void MeshLocalCfgSetIvIndex (uint32_t ivIndex)
void MeshLocalCfgSetIvUpdateInProgress (bool_t ivUpdtInProg)
void MeshLocalCfgEraseNvm (void)
Detailed Description
Data Structure Documentation
meshModelId_t
struct meshModelId_t
Data type for storing both SIG and Vendor model identifiers
Data Fields
bool_t isSigModel
modelId_t modelId
Field Documentation
isSigModel
bool_t isSigModel
Determines if model type is SIG or Vendor
modelId
modelId_t modelId
Model Id
meshLocalCfgModelSubscrListEntry_t
struct meshLocalCfgModelSubscrListEntry_t
Data type for Subscription list entries
Data Fields
uint16_t subscrAddressIndex
bool_t subscrToLabelUuid
Field Documentation
subscrAddressIndex
uint16_t subscrAddressIndex
Address index into one of the address lists
subscrToLabelUuid
bool_t subscrToLabelUuid
Subscription Address is in Label UUID list
meshLocalCfgModelPublication_t
struct meshLocalCfgModelPublication_t
Structure to store Model Publication state informations
Data Fields
uint16_t publishAddressIndex
uint16_t publishAppKeyEntryIndex
meshPublishPeriodNumSteps_t publishPeriodNumSteps
meshPublishPeriodStepRes_t publishPeriodStepRes
meshPublishFriendshipCred_t publishFriendshipCred
uint8_t publishTtl
meshPublishRetransCount_t publishRetransCount
meshPublishRetransIntvlSteps_t publishRetransSteps50Ms
bool_t publishToLabelUuid
Field Documentation
publishAddressIndex
uint16_t publishAddressIndex
Publish Address index in the address list
publishAppKeyEntryIndex
uint16_t publishAppKeyEntryIndex
Publish AppKey index in the AppKey list
publishFriendshipCred
meshPublishFriendshipCred_t publishFriendshipCred
Publish friendship security material
publishPeriodNumSteps
meshPublishPeriodNumSteps_t publishPeriodNumSteps
Publish period number of steps
publishPeriodStepRes
meshPublishPeriodStepRes_t publishPeriodStepRes
Publish period step resolution
publishRetransCount
meshPublishRetransCount_t publishRetransCount
Publish retransmit count
publishRetransSteps50Ms
meshPublishRetransIntvlSteps_t publishRetransSteps50Ms
Publish 50 ms retransmit steps
publishToLabelUuid
bool_t publishToLabelUuid
Publish Address is virtual
publishTtl
uint8_t publishTtl
Publish TTL
meshLocalCfgModelEntry_t
struct meshLocalCfgModelEntry_t
Data type for Model instance list entries
Data Fields
meshModelId_t modelId
meshElementId_t elementId
meshLocalCfgModelPublication_t publicationState
uint16_t subscrListStartIdx
uint16_t appKeyBindListStartIdx
uint8_t subscrListSize
uint8_t appKeyBindListSize
Field Documentation
appKeyBindListSize
uint8_t appKeyBindListSize
Size of AppKey Bind list for the model
appKeyBindListStartIdx
uint16_t appKeyBindListStartIdx
Start index in the AppKey Bind List for a specific model
elementId
meshElementId_t elementId
Element index in the Element array
modelId
meshModelId_t modelId
Pointer to the Model structure
publicationState
meshLocalCfgModelPublication_t publicationState
Model publication state
subscrListSize
uint8_t subscrListSize
Subscription list size for the model
subscrListStartIdx
uint16_t subscrListStartIdx
Start index in the Subscription list for a specific model
meshLocalCfgModelInfo_t
struct meshLocalCfgModelInfo_t
Local structure to store Models informations
Data Fields
meshLocalCfgModelEntry_t * pModelArray
uint16_t modelArraySize
Field Documentation
modelArraySize
uint16_t modelArraySize
Size of the Models List
pModelArray
meshLocalCfgModelEntry_t* pModelArray
Pointer to array describing models
meshLocalCfgAttTmr_t
struct meshLocalCfgAttTmr_t
Local structure for attention timer
Data Fields
wsfTimer_t attTmr
uint8_t remainingSec
Field Documentation
attTmr
wsfTimer_t attTmr
WSF timer
remainingSec
uint8_t remainingSec
Remaining seconds
meshLocalCfgElementInfo_t
struct meshLocalCfgElementInfo_t
Local structure to store Elements informations
Data Fields
const meshElement_t * pElementArray
meshLocalCfgAttTmr_t * pAttTmrArray
meshSeqNumber_t * pSeqNumberArray
meshSeqNumber_t * pSeqNumberThreshArray
uint8_t elementArrayLen
Field Documentation
elementArrayLen
uint8_t elementArrayLen
Length of pElementArray and pElementLocalCfgArray. Both have the same length and indexes
pAttTmrArray
meshLocalCfgAttTmr_t* pAttTmrArray
Pointer to array attention timer for each element
pElementArray
const meshElement_t* pElementArray
Pointer to array describing elements present in the node
pSeqNumberArray
meshSeqNumber_t* pSeqNumberArray
Pointer to SEQ number array for each element
pSeqNumberThreshArray
meshSeqNumber_t* pSeqNumberThreshArray
Pointer to SEQ number threshold array for each element
meshLocalCfgAddressListEntry_t
struct meshLocalCfgAddressListEntry_t
Data type for non-virtual address list entries
Data Fields
meshAddress_t address
uint16_t referenceCountPublish
uint16_t referenceCountSubscr
Field Documentation
address
meshAddress_t address
Non-virtual address
referenceCountPublish
uint16_t referenceCountPublish
Number of allocations of this address for publication
referenceCountSubscr
uint16_t referenceCountSubscr
Number of allocations of this address for subscription
meshLocalCfgAddressListInfo_t
struct meshLocalCfgAddressListInfo_t
Local structure to store Non-virtual Address informations
Data Fields
meshLocalCfgAddressListEntry_t * pAddressList
uint16_t addressListSize
Field Documentation
addressListSize
uint16_t addressListSize
Size of the Address List
pAddressList
meshLocalCfgAddressListEntry_t* pAddressList
Pointer to the start location of the Non-virtual Address List in memory
meshLocalCfgVirtualAddrListEntry_t
struct meshLocalCfgVirtualAddrListEntry_t
Data type for Virtual Address list entries
Data Fields
meshAddress_t address
uint8_t labelUuid [MESH_LABEL_UUID_SIZE]
uint16_t referenceCountPublish
uint16_t referenceCountSubscr
Field Documentation
address
meshAddress_t address
Virtual Address
labelUuid
uint8_t labelUuid[MESH_LABEL_UUID_SIZE]
Label UUID
referenceCountPublish
uint16_t referenceCountPublish
Number of allocations of this address for publication
referenceCountSubscr
uint16_t referenceCountSubscr
Number of allocations of this address for subscription
meshLocalCfgVirtualAddrListInfo_t
struct meshLocalCfgVirtualAddrListInfo_t
Local structure to store Label UUID informations
Data Fields
meshLocalCfgVirtualAddrListEntry_t * pVirtualAddrList
uint16_t virtualAddrListSize
Field Documentation
pVirtualAddrList
meshLocalCfgVirtualAddrListEntry_t* pVirtualAddrList
Pointer to the start location of the Virtual Address List in memory
virtualAddrListSize
uint16_t virtualAddrListSize
Size of the Virtual Address List
meshLocalCfgAppKeyBindListInfo_t
struct meshLocalCfgAppKeyBindListInfo_t
Local structure to store AppKey to Model ID bind informations
Data Fields
uint16_t * pAppKeyBindList
uint16_t appKeyBindListSize
Field Documentation
appKeyBindListSize
uint16_t appKeyBindListSize
Size of the AppKeyBind List
pAppKeyBindList
uint16_t* pAppKeyBindList
Pointer to the start location of the AppKeyBind list in memory
meshLocalCfgAppKeyListEntry_t
struct meshLocalCfgAppKeyListEntry_t
Data type for AppKey list entries
Data Fields
uint16_t netKeyEntryIndex
uint16_t appKeyIndex
uint8_t appKeyOld [MESH_KEY_SIZE_128]
uint8_t appKeyNew [MESH_KEY_SIZE_128]
bool_t newKeyAvailable
Field Documentation
appKeyIndex
uint16_t appKeyIndex
AppKey Index to identify the AppKey in the list
appKeyNew
uint8_t appKeyNew[MESH_KEY_SIZE_128]
New Application Key value
appKeyOld
uint8_t appKeyOld[MESH_KEY_SIZE_128]
Old Application Key value
netKeyEntryIndex
uint16_t netKeyEntryIndex
Index in the table of NetKeys for the NetKey binded to the AppKey
newKeyAvailable
bool_t newKeyAvailable
Flag to signal that a new key is available
meshLocalCfgAppKeyListInfo_t
struct meshLocalCfgAppKeyListInfo_t
Local structure to store AppKey List related informations
Data Fields
meshLocalCfgAppKeyListEntry_t * pAppKeyList
uint16_t appKeyListSize
Field Documentation
appKeyListSize
uint16_t appKeyListSize
Size of the AppKey List
pAppKeyList
meshLocalCfgAppKeyListEntry_t* pAppKeyList
Pointer to the start location of the AppKeyList in memory
meshLocalCfgNetKeyListEntry_t
struct meshLocalCfgNetKeyListEntry_t
Data type for NetKey List entries
Data Fields
uint16_t netKeyIndex
uint8_t netKeyOld [MESH_KEY_SIZE_128]
uint8_t netKeyNew [MESH_KEY_SIZE_128]
meshKeyRefreshStates_t keyRefreshState
bool_t newKeyAvailable
Field Documentation
keyRefreshState
meshKeyRefreshStates_t keyRefreshState
Key Refresh Phase state value. See::meshKeyRefreshStates_t
netKeyIndex
uint16_t netKeyIndex
NetKey Index to identify the NetKey in the list
netKeyNew
uint8_t netKeyNew[MESH_KEY_SIZE_128]
New Network Key value
netKeyOld
uint8_t netKeyOld[MESH_KEY_SIZE_128]
Old Network Key value
newKeyAvailable
bool_t newKeyAvailable
Flag to signal that a new key is available
meshLocalCfgNetKeyListInfo_t
struct meshLocalCfgNetKeyListInfo_t
Local structure to store NetKey List related informations
Data Fields
meshLocalCfgNetKeyListEntry_t * pNetKeyList
meshLocalCfgNodeIdentityListEntry_t * pNodeIdentityList
uint16_t netKeyListSize
Field Documentation
netKeyListSize
uint16_t netKeyListSize
Size of the NetKey List
pNetKeyList
meshLocalCfgNetKeyListEntry_t* pNetKeyList
Pointer to the start location of the NetKeyList in memory
pNodeIdentityList
meshLocalCfgNodeIdentityListEntry_t* pNodeIdentityList
Pointer to the start location of the Node Identity State list in memory
meshLocalCfgFriendSubscrEventParams_t
struct meshLocalCfgFriendSubscrEventParams_t
Mesh Local Config Friend Subscription Event notification
Data Fields
meshAddress_t address
uint16_t idx
Field Documentation
address
meshAddress_t address
Address
idx
uint16_t idx
Index in address list
Typedef Documentation
meshLocalCfgFriendSubscrEvent_t
typedef uint8_t meshLocalCfgFriendSubscrEvent_t
Mesh Local Config Friend Subscription notification event type. See meshLocalCfgFriendSubscrEventTypes
meshLocalCfgFriendSubscrEventNotifyCback_t
typedef void(* meshLocalCfgFriendSubscrEventNotifyCback_t) (meshLocalCfgFriendSubscrEvent_t event, const meshLocalCfgFriendSubscrEventParams_t *pEventParams)
Mesh Local Config Friend Subscription event notification callback function pointer type.
Parameters
[in] event Reason the callback is being invoked. See ::meshLocalCfgSubscrEvent_t
[in] pEventParams Pointer to the event parameters structure passed to the function. See ::meshLocalCfgEventParams_t
Returns
None.
meshLocalCfgNodeIdentityListEntry_t
typedef meshNodeIdentityStates_t meshLocalCfgNodeIdentityListEntry_t
Data type for Node Identity State List entries. See::meshNodeIdentityStates_t
meshLocalCfgRetVal_t
typedef uint16_t meshLocalCfgRetVal_t
Mesh Local Config return value. See meshReturnValues for codes starting at MESH_LOCAL_CFG_RETVAL_BASE
Enumeration Type Documentation
meshLocalCfgFriendSubscrEventTypes
enum meshLocalCfgFriendSubscrEventTypes
Mesh Local Config Friend Subscription notification event types enumeration
Enumerator
MESH_LOCAL_CFG_FRIEND_SUBSCR_ADD
Local Config subscription address add
MESH_LOCAL_CFG_FRIEND_SUBSCR_RM
Local Config subscription address remove
Function Documentation
MeshLocalCfgAddAddressToSubscrList()
meshLocalCfgRetVal_t MeshLocalCfgAddAddressToSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId, meshAddress_t subscrAddress)
Adds non-virtual address to the subscription list for an element.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] subscAddress Subscription address.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_UNASSIGNED, MESH_IS_ADDR_VIRTUAL, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::subscrListSize, meshLocalCfgModelEntry_t::subscrListStartIdx, and WSF_ASSERT.
MeshLocalCfgAddVirtualAddrToSubscrList()
meshLocalCfgRetVal_t MeshLocalCfgAddVirtualAddrToSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId, const uint8_t * pLabelUuid, meshAddress_t virtualAddr)
Adds multiple virtual address entries to the subscription list for an element.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] pLabelUuid Pointer to Label UUID.
[in] virtualAddr Virtual address for the Label UUID.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_VIRTUAL, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::subscrListSize, meshLocalCfgModelEntry_t::subscrListStartIdx, and WSF_ASSERT.
MeshLocalCfgBindAppKeyToModel()
meshLocalCfgRetVal_t MeshLocalCfgBindAppKeyToModel (meshElementId_t elementId, const meshModelId_t * pModelId, uint16_t appKeyIndex)
Binds an Application Key index to a Model ID.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] appKeyIndex Application key index.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgBindAppKeyToNetKey()
meshLocalCfgRetVal_t MeshLocalCfgBindAppKeyToNetKey (uint16_t appKeyIndex, uint16_t netKeyIndex)
Binds an Application key index to a Network key index.
Parameters
[in] appKeyIndex Application key index.
[in] netKeyIndex Network key index.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgCountBoundAppKeys()
uint16_t MeshLocalCfgCountBoundAppKeys (uint16_t netKeyIndex)
Counts number of AppKeys bound to a NetKey.
Parameters
[in] netKeyIndex Network Key index.
Returns
Number of bound AppKeys or 0 on error.
MeshLocalCfgCountModelBoundAppKeys()
uint8_t MeshLocalCfgCountModelBoundAppKeys (meshElementId_t elementId, const meshModelId_t * pModelId)
Counts number of Application Keys bound to a Model instance.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
Returns
TRUE if bind exists, FALSE otherwise.
References meshLocalCfgModelEntry_t::appKeyBindListSize, meshLocalCfgModelEntry_t::appKeyBindListStartIdx, meshLocalCfgAppKeyBindListInfo_t::pAppKeyBindList, meshLocalCfgModelInfo_t::pModelArray, and WSF_ASSERT.
MeshLocalCfgCountNetKeys()
uint16_t MeshLocalCfgCountNetKeys (void)
Counts number of NetKeys on the node.
Returns
Number of NetKeys on the node.
References meshLocalCfgNetKeyListEntry_t::netKeyIndex, meshLocalCfgNetKeyListInfo_t::netKeyListSize, and meshLocalCfgNetKeyListInfo_t::pNetKeyList.
MeshLocalCfgEraseNvm()
void MeshLocalCfgEraseNvm (void)
Erase configuration.
Returns
None.
References meshLocalCfgNetKeyListInfo_t::netKeyListSize, and WsfNvmEraseData().
MeshLocalCfgFindAddrInModelSubscrList()
bool_t MeshLocalCfgFindAddrInModelSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId, meshAddress_t subscrAddr, const uint8_t * pLabelUuid)
Checks if a model instance is subscribed to an address.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] subscrAddr Subscription address.
[in] pLabelUuid Pointer to Label UUID for virtual subscription addresses.
Returns
TRUE if address is found, FALSE otherwise.
MeshLocalCfgFindSubscrAddr()
bool_t MeshLocalCfgFindSubscrAddr (meshAddress_t subscrAddr)
Searches for an address in the subscription lists.
Parameters
[in] subscrAddr Subscription Address to be searched.
Returns
TRUE if the address is in any subscription list or FALSE otherwise.
MeshLocalCfgGetAddrFromElementId()
meshLocalCfgRetVal_t MeshLocalCfgGetAddrFromElementId (meshElementId_t elementId, meshAddress_t * pOutAddress)
Gets the Mesh Address from an element identifier.
Parameters
[in] elementId Local element identifier.
[out] pOutAddress Pointer to store the address on success.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_ADDR_TYPE_UNASSIGNED, MESH_IS_ADDR_UNICAST, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, and WSF_ASSERT.
MeshLocalCfgGetAppKey()
meshLocalCfgRetVal_t MeshLocalCfgGetAppKey (uint16_t appKeyIndex, uint8_t * pOutAppKey)
Gets the Application key for a key index.
Parameters
[in] appKeyIndex Application key index.
[out] pOutAppKey Pointer to store the Application key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
Any of the output parameters can be omitted. Set NULL if not requested.
References WSF_ASSERT.
MeshLocalCfgGetAttentionTimer()
uint8_t MeshLocalCfgGetAttentionTimer (meshElementId_t elementId)
Gets the Attention Timer value.
Parameters
[in] elementId Local element identifier.
Returns
Attention Timer value.
References meshLocalCfgElementInfo_t::elementArrayLen, meshLocalCfgElementInfo_t::pAttTmrArray, and meshLocalCfgAttTmr_t::remainingSec.
MeshLocalCfgGetBeaconState()
meshBeaconStates_t MeshLocalCfgGetBeaconState (void)
Gets the Secure Network Beacon state value.
Returns
Secure Network Beacon state value. See meshBeaconStates_t.
MeshLocalCfgGetBoundNetKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgGetBoundNetKeyIndex (uint16_t appKeyIndex, uint16_t * pOutNetKeyIndex)
Gets NetKey Index of Network Key bound to Application Key identified by appKeyIndex.
Parameters
[in] appKeyIndex Application Key index.
[out] pOutNetKeyIndex Pointer to memory where the NetKey Index is stored if successful.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgGetDefaultTtl()
uint8_t MeshLocalCfgGetDefaultTtl (void)
Gets the Default TTL value.
Returns
Default TTL value.
MeshLocalCfgGetDevKey()
void MeshLocalCfgGetDevKey (uint8_t * pOutDevKey)
Gets the Device key.
Parameters
[out] pOutDevKey Pointer to store the Device Key.
Returns
None.
References MESH_KEY_SIZE_128, and WSF_ASSERT.
MeshLocalCfgGetElementFromAddress()
meshLocalCfgRetVal_t MeshLocalCfgGetElementFromAddress (meshAddress_t elementAddress, const meshElement_t ** ppOutElement)
Gets a pointer to a constant local Mesh element based on element address.
Parameters
[in] elementAddress Local element address.
[out] ppOutElement Pointer to store address of a constant local element or NULL if element not found.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgElementInfo_t::pElementArray, and WSF_ASSERT.
MeshLocalCfgGetElementFromId()
meshLocalCfgRetVal_t MeshLocalCfgGetElementFromId (meshElementId_t elementId, const meshElement_t ** ppOutElement)
Gets a pointer to a constant local Mesh element based on element identifier in list.
Parameters
[in] elementId Local element identifier.
[out] ppOutElement Pointer to store address of a constant local element or NULL if element not found.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgElementInfo_t::pElementArray, and WSF_ASSERT.
MeshLocalCfgGetElementIdFromAddr()
meshLocalCfgRetVal_t MeshLocalCfgGetElementIdFromAddr (meshAddress_t elementAddress, meshElementId_t * pOutElementId)
Gets the Mesh element identifier from an unicast address.
Parameters
[in] elementAddress Local element identifier.
[out] pOutElementId Pointer to memory where to store the id on success.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, and WSF_ASSERT.
MeshLocalCfgGetFriendState()
meshFriendStates_t MeshLocalCfgGetFriendState (void)
Gets the Friend state value.
Returns
Friend state value. See meshFriendStates_t.
MeshLocalCfgGetGattProxyState()
meshGattProxyStates_t MeshLocalCfgGetGattProxyState (void)
Gets the GATT Proxy state value.
Returns
GATT Proxy state value. See meshGattProxyStates_t.
MeshLocalCfgGetHbPubCountLog()
uint8_t MeshLocalCfgGetHbPubCountLog (void)
Gets the Heartbeat Publication Count Log value.
Returns
Heartbeat Publication Count Log value.
MeshLocalCfgGetHbPubDst()
meshAddress_t MeshLocalCfgGetHbPubDst (void)
Gets the Heartbeat Publication destination address.
Returns
Heartbeat Publication destination address.
References meshLocalCfgAddressListEntry_t::address, MESH_ADDR_TYPE_UNASSIGNED, and meshLocalCfgAddressListInfo_t::pAddressList.
MeshLocalCfgGetHbPubFeatures()
meshFeatures_t MeshLocalCfgGetHbPubFeatures (void)
Gets the Heartbeat Publication Features set.
Returns
Heartbeat Publication Features.
MeshLocalCfgGetHbPubNetKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgGetHbPubNetKeyIndex (uint16_t * pOutNetKeyIndex)
Gets the Heartbeat Publication NetKey Index value.
Parameters
[out] pOutNetKeyIndex Pointer to store the Heartbeat Publication NetKey Index value.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgNetKeyListEntry_t::netKeyIndex, meshLocalCfgNetKeyListInfo_t::netKeyListSize, meshLocalCfgNetKeyListInfo_t::pNetKeyList, and WSF_ASSERT.
MeshLocalCfgGetHbPubPeriodLog()
uint8_t MeshLocalCfgGetHbPubPeriodLog (void)
Gets the Heartbeat Publication Period Log value.
Returns
Heartbeat Publication Period Log value.
MeshLocalCfgGetHbPubTtl()
uint8_t MeshLocalCfgGetHbPubTtl (void)
Gets the Heartbeat Publication TTL value.
Returns
Heartbeat Publication TTL value.
MeshLocalCfgGetHbSubCountLog()
uint8_t MeshLocalCfgGetHbSubCountLog (void)
Gets the Heartbeat Subscription Count Log value.
Returns
Heartbeat Subscription Count Log value.
MeshLocalCfgGetHbSubDst()
meshAddress_t MeshLocalCfgGetHbSubDst (void)
Gets the Heartbeat Subscription destination address.
Returns
Heartbeat Subscription destination address.
References meshLocalCfgAddressListEntry_t::address, MESH_ADDR_TYPE_UNASSIGNED, and meshLocalCfgAddressListInfo_t::pAddressList.
MeshLocalCfgGetHbSubMaxHops()
uint8_t MeshLocalCfgGetHbSubMaxHops (void)
Gets the Heartbeat Subscription Max Hops value which determines the maximum hops registered when receiving Heartbeat messages since receiving the most recent Config Heartbeat Subscription Set message.
Returns
Heartbeat Subscription Max Hops value.
MeshLocalCfgGetHbSubMinHops()
uint8_t MeshLocalCfgGetHbSubMinHops (void)
Gets the Heartbeat Subscription Min Hops value.
Returns
Heartbeat Subscription Min Hops value.
MeshLocalCfgGetHbSubPeriodLog()
uint8_t MeshLocalCfgGetHbSubPeriodLog (void)
Gets the Heartbeat Subscription Period Log value.
Returns
Heartbeat Subscription Period Log value.
MeshLocalCfgGetHbSubSrc()
meshAddress_t MeshLocalCfgGetHbSubSrc (void)
Gets the Heartbeat Subscription source address.
Returns
Heartbeat Subscription source address.
References meshLocalCfgAddressListEntry_t::address, MESH_ADDR_TYPE_UNASSIGNED, and meshLocalCfgAddressListInfo_t::pAddressList.
MeshLocalCfgGetIvIndex()
uint32_t MeshLocalCfgGetIvIndex (bool_t * pIvUpdtInProg)
Gets the IV Index value and IV Index update in progress flag.
Parameters
[out] pIvUpdtInProg Pointer to store TRUE if IV update is in progress or FALSE otherwise.
Returns
IV index value.
MeshLocalCfgGetKeyRefreshPhaseState()
meshKeyRefreshStates_t MeshLocalCfgGetKeyRefreshPhaseState (uint16_t netKeyIndex)
Gets the Key Refresh Phase state value.
Parameters
[in] netKeyIndex NetKey Index to identify the NetKey in the list.
Returns
Key Refresh Phase state value for the given NetKey Index.
MeshLocalCfgGetLowPowerState()
meshLowPowerStates_t MeshLocalCfgGetLowPowerState (void)
Gets the Low Power state value.
Returns
Low Power state value. See meshLowPowerStates_t.
MeshLocalCfgGetNetKey()
meshLocalCfgRetVal_t MeshLocalCfgGetNetKey (uint16_t netKeyIndex, uint8_t * pOutNetKey)
Gets the Network key for a key index.
Parameters
[in] netKeyIndex Network key index.
[out] pOutNetKey Pointer to store the Network key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgGetNextAddressFromSubscrList()
meshLocalCfgRetVal_t MeshLocalCfgGetNextAddressFromSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId, meshAddress_t * pOutSubscAddress, uint8_t * pInOutStartIndex)
Gets address entry from a specific index in the subscription list for an element.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutSubscAddress Pointer to the memory where to store the subscription address.
[in,out] pInOutStartIndex Pointer to an indexing variable. Must be intialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves as an iterator, fetching one address at a time.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutSubscAddress Pointer to the memory where to store the subscription address.
[in,out] pInOutStartIndex For input the index from where to start the search. For output the index where the search stopped.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::subscrListSize, meshLocalCfgModelEntry_t::subscrListStartIdx, and WSF_ASSERT.
MeshLocalCfgGetNextAppKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgGetNextAppKeyIndex (uint16_t * pOutAppKeyIndex, uint16_t * pInOutIndex)
Gets next AppKey Index.
Parameters
[out] pOutAppKeyIndex Pointer to variable where the next AppKey Index is stored.
[in,out] pInOutIndex Pointer to an indexing variable. Must be initialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves as an iterator, fetching one key index at a time.
References meshLocalCfgAppKeyListEntry_t::appKeyIndex, meshLocalCfgAppKeyListInfo_t::appKeyListSize, MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgAppKeyListInfo_t::pAppKeyList, and WSF_ASSERT.
MeshLocalCfgGetNextBoundAppKey()
meshLocalCfgRetVal_t MeshLocalCfgGetNextBoundAppKey (uint16_t netKeyIndex, uint16_t * pOutAppKeyIndex, uint16_t * pInOutIndex)
Gets next AppKey Index bound to a NetKey Index.
Parameters
[in] netKeyIndex Network Key index.
[out] pOutAppKeyIndex Pointer to variable where the next AppKey Index is stored.
[in,out] pInOutIndex Pointer to an indexing variable. Must be intialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves as an iterator,fetching one key index at a time.
Parameters
[in] netKeyIndex Network Key index.
[out] pOutAppKeyIndex Pointer to variable where the next AppKey Index is stored.
[in,out] pInOutIndex Pointer to an indexing variable. Must be intialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves like an iterator. Fetching one key index at a time.
References WSF_ASSERT.
MeshLocalCfgGetNextModelBoundAppKey()
meshLocalCfgRetVal_t MeshLocalCfgGetNextModelBoundAppKey (meshElementId_t elementId, const meshModelId_t * pModelId, uint16_t * pOutAppKeyIndex, uint8_t * pInOutIndex)
Gets next AppKey Index bound to a model instance.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutAppKeyIndex Pointer to variable where the next AppKey Index is stored.
[in,out] pInOutIndex Pointer to an indexing variable. Must be intialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves like an iterator. Fetching one key index at a time.
References meshLocalCfgModelEntry_t::appKeyBindListSize, meshLocalCfgModelEntry_t::appKeyBindListStartIdx, meshLocalCfgAppKeyListEntry_t::appKeyIndex, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgAppKeyBindListInfo_t::pAppKeyBindList, meshLocalCfgAppKeyListInfo_t::pAppKeyList, meshLocalCfgModelInfo_t::pModelArray, and WSF_ASSERT.
MeshLocalCfgGetNextNetKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgGetNextNetKeyIndex (uint16_t * pOutNetKeyIndex, uint16_t * pInOutIndex)
Gets next NetKey Index.
Parameters
[out] pOutNetKeyIndex Pointer to variable where the next NetKey Index is stored.
[in,out] pInOutIndex Pointer to an indexing variable. Must be intialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves as an iterator, fetching one key index at a time.
Parameters
[out] pOutNetKeyIndex Pointer to variable where the next NetKey Index is stored.
[in,out] pInOutIndex Pointer to an indexing variable. Must be initialized with 0 on to restart search.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
This function behaves as an iterator, fetching one key index at a time.
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgNetKeyListEntry_t::netKeyIndex, meshLocalCfgNetKeyListInfo_t::netKeyListSize, meshLocalCfgNetKeyListInfo_t::pNetKeyList, and WSF_ASSERT.
MeshLocalCfgGetNextSubscrAddress()
meshLocalCfgRetVal_t MeshLocalCfgGetNextSubscrAddress (meshAddress_t * pOutSubscAddress, uint16_t * pInOutStartIndex)
Gets subscription address entry from a specific index in the address list.
Parameters
[out] pOutSubscAddress Pointer to the memory where to store the subscription address.
[in,out] pInOutStartIndex For input the index from where to start the search. For output the index where the search stopped.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgAddressListEntry_t::address, meshLocalCfgAddressListInfo_t::addressListSize, MESH_ADDR_TYPE_UNASSIGNED, MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgAddressListInfo_t::pAddressList, meshLocalCfgAddressListEntry_t::referenceCountSubscr, and WSF_ASSERT.
MeshLocalCfgGetNextSubscrVirtualAddr()
meshLocalCfgRetVal_t MeshLocalCfgGetNextSubscrVirtualAddr (meshAddress_t * pOutSubscAddress, uint16_t * pInOutStartIndex)
Gets virtual subscription address entry from a specific index in the virtual address list.
Parameters
[out] pOutSubscAddress Pointer to the memory where to store the subscription address.
[in,out] pInOutStartIndex For input the index from where to start the search. For output the index where the search stopped.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgVirtualAddrListEntry_t::address, MESH_ADDR_TYPE_UNASSIGNED, MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgVirtualAddrListInfo_t::pVirtualAddrList, meshLocalCfgVirtualAddrListEntry_t::referenceCountSubscr, meshLocalCfgVirtualAddrListInfo_t::virtualAddrListSize, and WSF_ASSERT.
MeshLocalCfgGetNodeIdentityState()
meshNodeIdentityStates_t MeshLocalCfgGetNodeIdentityState (uint16_t netKeyIndex)
Gets the Node Identity state value.
Parameters
[in] netKeyIndex NetKey Index to identify the subnet for the Node Identity.
Returns
Node Identity state value for the given NetKey Index or MESH_NODE_IDENTITY_PROHIBITED_START if NetKey Index is invalid.
MeshLocalCfgGetNwkTransmitCount()
uint8_t MeshLocalCfgGetNwkTransmitCount (void)
Gets the Network Transmit Count value.
Returns
Network Transmit Count value.
MeshLocalCfgGetNwkTransmitIntvlSteps()
uint8_t MeshLocalCfgGetNwkTransmitIntvlSteps (void)
Gets the Network Transmit Interval Steps value.
Returns
Network Transmit Interval Steps value.
MeshLocalCfgGetProductInformation()
void MeshLocalCfgGetProductInformation (meshProdInfo_t * pOutProdInfo)
Gets product information.
Parameters
[out] pOutProdInfo Pointer to memory where to store the product information (CID/PID/VID). See meshProdInfo_t
Returns
None.
References meshProdInfo_t::companyId, meshProdInfo_t::productId, meshProdInfo_t::versionId, and WSF_ASSERT.
MeshLocalCfgGetPublishAddress()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishAddress (meshElementId_t elementId, const meshModelId_t * pModelId, meshAddress_t * pOutPublishAddress, uint8_t ** ppOutLabelUuid)
Gets publish address based on a model ID.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutPublishAddress Pointer to memory where to store the publish address.
[out] ppOutLabelUuid Pointer to memory where to store the memory address of the Label UUID if address is virtual.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishAddressIndex, meshLocalCfgModelPublication_t::publishToLabelUuid, and WSF_ASSERT.
MeshLocalCfgGetPublishAppKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishAppKeyIndex (meshElementId_t elementId, const meshModelId_t * pModelId, uint16_t * pOutAppKeyIndex)
Gets model publish AppKey Index.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutAppKeyIndex Pointer to memory where to store publish AppKeyIndex.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgAppKeyListEntry_t::appKeyIndex, MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgAppKeyListInfo_t::pAppKeyList, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishAppKeyEntryIndex, and WSF_ASSERT.
MeshLocalCfgGetPublishFriendshipCredFlag()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishFriendshipCredFlag (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishFriendshipCred_t * pOutFriendshipCredFlag)
Gets model publish friendship security credential flag.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutFriendshipCredFlag Pointer to memory where to store publish friendship credential flag. See meshPublishFriendshipCred_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishFriendshipCred, and WSF_ASSERT.
MeshLocalCfgGetPublishPeriod()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishPeriod (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishPeriodNumSteps_t * pOutNumberOfSteps, meshPublishPeriodStepRes_t * pOutStepResolution)
Gets model publish period in number of steps and step resolution.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutNumberOfSteps Pointer to store the number of steps. See meshPublishPeriodNumSteps_t
[out] pOutStepResolution Pointer to store the resolution of the number of steps field. See :: meshPublishPeriodStepRes_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishPeriodNumSteps, meshLocalCfgModelPublication_t::publishPeriodStepRes, and WSF_ASSERT.
MeshLocalCfgGetPublishRetransCount()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishRetransCount (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishRetransCount_t * pOutRetransCount)
Gets model publish retransmit count.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutRetransCount Point to publish retransmit count value. See meshPublishRetransCount_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishRetransCount, and WSF_ASSERT.
MeshLocalCfgGetPublishRetransIntvlSteps()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishRetransIntvlSteps (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishRetransIntvlSteps_t * pOutRetransSteps)
Gets model publish retransmission interval steps.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutRetransSteps Pointer to publish retransmit interval steps value. See meshPublishRetransIntvlSteps_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
The retransmission interval is calculated using the formula retransmitInterval = (publishRetransSteps + 1) * 50.
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishRetransSteps50Ms, and WSF_ASSERT.
MeshLocalCfgGetPublishTtl()
meshLocalCfgRetVal_t MeshLocalCfgGetPublishTtl (meshElementId_t elementId, const meshModelId_t * pModelId, uint8_t * pOutPublishTtl)
Gets model publish TTL.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutPublishTtl Pointer to memory where to store publish TTL.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishTtl, and WSF_ASSERT.
MeshLocalCfgGetRelayRetransmitCount()
uint8_t MeshLocalCfgGetRelayRetransmitCount (void)
Gets the Relay Retransmit Count value.
Returns
Relay Retransmit Count value.
MeshLocalCfgGetRelayRetransmitIntvlSteps()
uint8_t MeshLocalCfgGetRelayRetransmitIntvlSteps (void)
Gets the Relay Retransmit Interval Steps value.
Returns
Relay Retransmit Interval Steps value.
MeshLocalCfgGetRelayState()
meshRelayStates_t MeshLocalCfgGetRelayState (void)
Gets the Relay state value.
Returns
Relay state value. See meshRelayStates_t.
MeshLocalCfgGetRequiredMemory()
uint32_t MeshLocalCfgGetRequiredMemory (void)
Computes the required memory to be provided based on the given configuration.
Returns
Required memory in bytes or MESH_MEM_REQ_INVALID_CFG in case of fail.
References meshMemoryConfig_t::addrListMaxSize, meshMemoryConfig_t::appKeyListSize, meshConfig_t::elementArrayLen, MESH_MEM_REQ_INVALID_CFG, meshMemoryConfig_t::netKeyListSize, meshConfig_t::pElementArray, meshConfig_t::pMemoryConfig, pMeshConfig, and meshMemoryConfig_t::virtualAddrListMaxSize.
MeshLocalCfgGetSeqNumber()
meshLocalCfgRetVal_t MeshLocalCfgGetSeqNumber (meshElementId_t elementId, meshSeqNumber_t * pOutSeqNumber)
Gets the SEQ number value.
Parameters
[in] elementId Local element identifier.
[out] pOutSeqNumber Pointer to store the SEQ number value.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgElementInfo_t::pSeqNumberArray, and WSF_ASSERT.
MeshLocalCfgGetSeqNumberThresh()
meshSeqNumber_t MeshLocalCfgGetSeqNumberThresh (meshElementId_t elementId)
Gets the SEQ number Threshold value.
Parameters
[in] elementId Local element identifier.
Returns
SEQ number threshold value.
References meshLocalCfgElementInfo_t::elementArrayLen, and meshLocalCfgElementInfo_t::pSeqNumberThreshArray.
MeshLocalCfgGetSubscrListSize()
meshLocalCfgRetVal_t MeshLocalCfgGetSubscrListSize (meshElementId_t elementId, const meshModelId_t * pModelId, uint8_t * pOutNumAddr, uint8_t * pOutTotalSize)
Gets the subscription list available size and maximum size for an model instance.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[out] pOutNumAddr Pointer to store the number of addresses in subscription list for the given element.
[out] pOutTotalSize Pointer to store the maximum size of the subscription list for the given element.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::subscrListSize, meshLocalCfgModelEntry_t::subscrListStartIdx, and WSF_ASSERT.
MeshLocalCfgGetSupportedFeatures()
meshFeatures_t MeshLocalCfgGetSupportedFeatures (void)
Gets supported features from the stack.
Returns
Bit field feature support value. See meshFeatures_t.
References MESH_FEAT_FRIEND, MESH_FEAT_LOW_POWER, MESH_FEAT_PROXY, MESH_FEAT_RELAY, MESH_FRIEND_FEATURE_ENABLED, MESH_GATT_PROXY_FEATURE_ENABLED, MESH_LOW_POWER_FEATURE_ENABLED, MESH_RELAY_FEATURE_ENABLED, MeshLocalCfgGetFriendState(), MeshLocalCfgGetGattProxyState(), MeshLocalCfgGetLowPowerState(), and MeshLocalCfgGetRelayState().
MeshLocalCfgGetUpdatedAppKey()
meshLocalCfgRetVal_t MeshLocalCfgGetUpdatedAppKey (uint16_t appKeyIndex, uint8_t * pOutAppKey)
Gets the updated Application key for a key index.
Parameters
[in] appKeyIndex Application key index.
[out] pOutAppKey Pointer to store the updated Application key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
Any of the output parameters can be omitted. Set NULL if not requested.
References WSF_ASSERT.
MeshLocalCfgGetUpdatedNetKey()
meshLocalCfgRetVal_t MeshLocalCfgGetUpdatedNetKey (uint16_t netKeyIndex, uint8_t * pOutNetKey)
Gets the updated Network key for a key index.
Parameters
[in] netKeyIndex Network key index.
[out] pOutNetKey Pointer to store the updated Network key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgGetVirtualAddrFromLabelUuid()
meshLocalCfgRetVal_t MeshLocalCfgGetVirtualAddrFromLabelUuid (const uint8_t * pLabelUuid, meshAddress_t * pOutVirtualAddr)
Gets generated Virtual Address associated to a Label UUID.
Parameters
[in] pLabelUuid Pointer to the Label UUID location.
[out] pPOutVirtualAddr Pointer to store the virtual address or MESH_ADDR_TYPE_UNASSIGNED if Label UUID not found.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgVirtualAddrListEntry_t::address, meshLocalCfgVirtualAddrListEntry_t::labelUuid, MESH_ADDR_TYPE_UNASSIGNED, MESH_LABEL_UUID_SIZE, MESH_LOCAL_CFG_NOT_FOUND, MESH_SUCCESS, meshLocalCfgVirtualAddrListInfo_t::pVirtualAddrList, meshLocalCfgVirtualAddrListInfo_t::virtualAddrListSize, and WSF_ASSERT.
MeshLocalCfgGetVtadList()
void MeshLocalCfgGetVtadList (const meshLocalCfgVirtualAddrListInfo_t ** ppVtadList)
Gets a read only copy of the Virtual Address Table.
Parameters
[out] ppVtadList Pointer to memory where the address of the virtual address information structure is stored.
Returns
None.
References WSF_ASSERT.
MeshLocalCfgInit()
void MeshLocalCfgInit (void)
Initializes the Local Configuration module and allocates memory.
Returns
None.
MeshLocalCfgMdlClearPublishAppKeyIndex()
void MeshLocalCfgMdlClearPublishAppKeyIndex (meshElementId_t elementId, const meshModelId_t * pModelId)
Un-sets model publish AppKey Index.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
Returns
None.
References meshLocalCfgModelInfo_t::modelArraySize, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishAppKeyEntryIndex, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgModelExists()
bool_t MeshLocalCfgModelExists (meshElementId_t elementId, const meshModelId_t * pModelId)
Determines if model instance exists on node.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
Returns
TRUE if element contains an instance of the model.
MeshLocalCfgRegisterLpn()
void MeshLocalCfgRegisterLpn (meshLocalCfgFriendSubscrEventNotifyCback_t friendSubscrEventCback)
Registers the LPN events callback.
Parameters
[in] friendSubscrEventCback Friend subscription event notification callback.
Returns
None.
MeshLocalCfgRemoveAddressFromSubscrList()
meshLocalCfgRetVal_t MeshLocalCfgRemoveAddressFromSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId, meshAddress_t address)
Removes an address from the subscription list for an element.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] address Address to be removed.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_UNASSIGNED, MESH_IS_ADDR_VIRTUAL, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::subscrListSize, meshLocalCfgModelEntry_t::subscrListStartIdx, and WSF_ASSERT.
MeshLocalCfgRemoveAllFromSubscrList()
meshLocalCfgRetVal_t MeshLocalCfgRemoveAllFromSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId)
Removes all entries from the subscription list for an element.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgRemoveAppKey()
meshLocalCfgRetVal_t MeshLocalCfgRemoveAppKey (uint16_t appKeyIndex, bool_t removeOldKeyOnly)
Removes the Application key for a key index.
Parameters
[in] appKeyIndex Application key index.
[in] removeOldKeyOnly If TRUE, AppKey Old is replaced by AppKey New If FALSE, the AppKey is removed from the AppKey List.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgRemoveNetKey()
meshLocalCfgRetVal_t MeshLocalCfgRemoveNetKey (uint16_t netKeyIndex, bool_t removeOldKeyOnly)
Removes the Network key for a key index.
Parameters
[in] netKeyIndex Network key index.
[in] removeOldKeyOnly If TRUE, NetKey Old is replaced by NetKey New If FALSE, the NetKey is removed from the NetKey List.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgRemoveVirtualAddrFromSubscrList()
meshLocalCfgRetVal_t MeshLocalCfgRemoveVirtualAddrFromSubscrList (meshElementId_t elementId, const meshModelId_t * pModelId, const uint8_t * pLabelUuid)
Removes an Label UUID from the subscription list for an element.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] pLabelUuid Pointer to the Label UUID to be removed.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_SUCCESS, MeshLocalCfgGetVirtualAddrFromLabelUuid(), meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::subscrListSize, meshLocalCfgModelEntry_t::subscrListStartIdx, and WSF_ASSERT.
MeshLocalCfgSetAppKey()
meshLocalCfgRetVal_t MeshLocalCfgSetAppKey (uint16_t appKeyIndex, const uint8_t * pAppKey)
Sets the Application key and key index.
Parameters
[in] appKeyIndex Application key index.
[in] pAppKey Pointer to the Application Key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgSetAttentionTimer()
void MeshLocalCfgSetAttentionTimer (meshElementId_t elementId, uint8_t timerVal)
Sets the Attention Timer value.
Parameters
[in] elementId Local element identifier.
[in] timerVal Attention Timer value.
Returns
None.
References meshLocalCfgElementInfo_t::elementArrayLen, meshLocalCfgElementInfo_t::pAttTmrArray, and meshLocalCfgAttTmr_t::remainingSec.
MeshLocalCfgSetBeaconState()
void MeshLocalCfgSetBeaconState (meshBeaconStates_t beaconState)
Sets the Secure Network Beacon state value.
Parameters
[in] beaconState Secure Network Beacon state value. See meshBeaconStates_t
Returns
None.
References MESH_BEACON_PROHIBITED_START, and WsfNvmWriteData().
MeshLocalCfgSetDefaultTtl()
void MeshLocalCfgSetDefaultTtl (uint8_t defaultTtl)
Sets the Default TTL value.
Parameters
[in] defaultTtl Default TTL value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetDevKey()
void MeshLocalCfgSetDevKey (const uint8_t * pDevKey)
Sets the Device key.
Parameters
[in] pDevKey Pointer to the Device Key.
Returns
None.
References MESH_KEY_SIZE_128, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSetFriendState()
void MeshLocalCfgSetFriendState (meshFriendStates_t friendState)
Sets the Friend state value.
Parameters
[in] friendState Friend state value. See meshFriendStates_t
Returns
None.
References MESH_FRIEND_FEATURE_PROHIBITED_START, and WsfNvmWriteData().
MeshLocalCfgSetGattProxyState()
void MeshLocalCfgSetGattProxyState (meshGattProxyStates_t gattProxyState)
Sets the GATT Proxy state value.
Parameters
[in] gattProxyState GATT Proxy state value. See meshGattProxyStates_t
Returns
None.
References MESH_GATT_PROXY_FEATURE_PROHIBITED_START, and WsfNvmWriteData().
MeshLocalCfgSetHbPubCountLog()
void MeshLocalCfgSetHbPubCountLog (uint8_t countLog)
Sets the Heartbeat Publication Count Log state which controls the number of periodical Heartbeat transport control messages to be sent.
Parameters
[in] countLog Heartbeat Publication Count Log value to be set.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbPubDst()
meshLocalCfgRetVal_t MeshLocalCfgSetHbPubDst (meshAddress_t dstAddress)
Sets the Heartbeat Publication destination address.
Parameters
[in] dstAddress Destination address for Heartbeat messages.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_GROUP, MESH_IS_ADDR_UNASSIGNED, MESH_IS_ADDR_UNICAST, and WSF_ASSERT.
MeshLocalCfgSetHbPubFeatures()
void MeshLocalCfgSetHbPubFeatures (meshFeatures_t pubFeatures)
Sets the Heartbeat Publication Features that trigger sending Heartbeat messages.
Parameters
[in] pubFeatures Heartbeat Publication Features to be set.
Returns
None.
References MESH_FEAT_RFU_START, and WsfNvmWriteData().
MeshLocalCfgSetHbPubNetKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgSetHbPubNetKeyIndex (uint16_t netKeyIndex)
Sets the Heartbeat Publication NetKey Index used when sending Heartbeat messages.
Parameters
[in] netKeyIndex Heartbeat Publication NetKey Index value to be set.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgSetHbPubPeriodLog()
void MeshLocalCfgSetHbPubPeriodLog (uint8_t periodLog)
Sets the Heartbeat Publication Period Log state which controls the cadence of periodical Heartbeat transport control messages to be sent.
Parameters
[in] periodLog Heartbeat Publication Period Log value to be set.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbPubTtl()
void MeshLocalCfgSetHbPubTtl (uint8_t pubTtl)
Sets the Heartbeat Publication TTL used when sending Heartbeat messages.
Parameters
[in] pubTtl Heartbeat Publication TTL value to be set.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbSubCountLog()
void MeshLocalCfgSetHbSubCountLog (uint8_t countLog)
Sets the Heartbeat Subscription Count Log value.
Parameters
[in] countLog Heartbeat Subscription Count Log value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbSubDst()
meshLocalCfgRetVal_t MeshLocalCfgSetHbSubDst (meshAddress_t dstAddress)
Sets the Heartbeat Subscription destination address.
Parameters
[in] dstAddress Destination address for Heartbeat messages.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_GROUP, MESH_IS_ADDR_UNASSIGNED, MESH_IS_ADDR_UNICAST, and WSF_ASSERT.
MeshLocalCfgSetHbSubMaxHops()
void MeshLocalCfgSetHbSubMaxHops (uint8_t maxHops)
Sets the Heartbeat Subscription Max Hops value which determines the maximum hops registered when receiving Heartbeat messages since receiving the most recent Config Heartbeat Subscription Set message.
Parameters
[in] maxHops Heartbeat Subscription Max Hops value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbSubMinHops()
void MeshLocalCfgSetHbSubMinHops (uint8_t minHops)
Sets the Heartbeat Subscription Min Hops value which determines the minimum hops registered when receiving Heartbeat messages since receiving the most recent.
Parameters
[in] minHops Heartbeat Subscription Min Hops value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbSubPeriodLog()
void MeshLocalCfgSetHbSubPeriodLog (uint8_t periodLog)
Sets the Heartbeat Subscription Period Log state which controls the period for processing periodical Heartbeat transport control messages.
Parameters
[in] periodLog Heartbeat Subscription Period Log value to be set.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetHbSubSrc()
meshLocalCfgRetVal_t MeshLocalCfgSetHbSubSrc (meshAddress_t srcAddress)
Sets the Heartbeat Subscription source address.
Parameters
[in] srcAddress Source address for Heartbeat messages.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_UNASSIGNED, MESH_IS_ADDR_UNICAST, and WSF_ASSERT.
MeshLocalCfgSetIvIndex()
void MeshLocalCfgSetIvIndex (uint32_t ivIndex)
Sets the IV index value.
Parameters
[in] ivIndex IV index value.
Returns
None.
References wsfMsgHdr_t::event, meshCb_t::evtCback, meshIvUpdtEvt_t::hdr, meshIvUpdtEvt_t::ivIndex, MESH_CORE_EVENT, MESH_CORE_IV_UPDATED_EVENT, MESH_SUCCESS, wsfMsgHdr_t::param, wsfMsgHdr_t::status, and WsfNvmWriteData().
MeshLocalCfgSetIvUpdateInProgress()
void MeshLocalCfgSetIvUpdateInProgress (bool_t ivUpdtInProg)
Sets the IV Index update in progress flag.
Parameters
[in] ivUpdtInProg IV Index update in progress flag value.
Returns
None.
MeshLocalCfgSetKeyRefreshState()
void MeshLocalCfgSetKeyRefreshState (uint16_t netKeyIndex, meshKeyRefreshStates_t keyRefreshState)
Sets the Key Refresh Phase state value.
Parameters
[in] netKeyIndex NetKey Index to identify the NetKey in the list.
[in] keyRefreshState Key Refresh Phase state value. See meshKeyRefreshStates_t
Returns
None.
References MESH_KEY_REFRESH_PROHIBITED_START, and WSF_ASSERT.
MeshLocalCfgSetLowPowerState()
void MeshLocalCfgSetLowPowerState (meshLowPowerStates_t lowPowerState)
Sets the Low Power state value.
Parameters
[in] lowPowerState Low Power state value. See meshLowPowerStates_t
Returns
None.
References MESH_LOW_POWER_FEATURE_PROHIBITED_START.
MeshLocalCfgSetNetKey()
meshLocalCfgRetVal_t MeshLocalCfgSetNetKey (uint16_t netKeyIndex, const uint8_t * pNetKey)
Sets the Network key and key index.
Parameters
[in] netKeyIndex Network key index.
[in] pNetKey Pointer to the Network Key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgSetNodeIdentityState()
void MeshLocalCfgSetNodeIdentityState (uint16_t netKeyIndex, meshNodeIdentityStates_t nodeIdentityState)
Sets the Node Identity state value.
Parameters
[in] netKeyIndex NetKey Index to identify the subnet for the Node Identity.
[in] nodeIdentityState Node Identity state value. See meshNodeIdentityStates_t
Returns
None.
References MESH_NODE_IDENTITY_PROHIBITED_START, and WSF_ASSERT.
MeshLocalCfgSetNwkTransmitCount()
void MeshLocalCfgSetNwkTransmitCount (uint8_t transCount)
Sets the Network Transmit Count value which controls the number of message transmissions of the Network PDU originating from the node.
Parameters
[in] transCount Network Transmit Count value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetNwkTransmitIntvlSteps()
void MeshLocalCfgSetNwkTransmitIntvlSteps (uint8_t intvlSteps)
Sets the Network Transmit Interval Steps value representing the number of 10ms steps that controls the interval between transmissions of Network PDUs originating from the node.
Parameters
[in] intvlSteps Network Transmit Interval Steps value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetPrimaryNodeAddress()
meshLocalCfgRetVal_t MeshLocalCfgSetPrimaryNodeAddress (meshAddress_t address)
Sets the address for the primary node.
Parameters
[in] address Primary element address.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_IS_ADDR_UNICAST, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, and WsfNvmWriteData().
MeshLocalCfgSetProductInformation()
void MeshLocalCfgSetProductInformation (const meshProdInfo_t * pProdInfo)
Sets product information.
Parameters
[in] pProdInfo Pointer to product information structure. See meshProdInfo_t
Returns
None.
References meshProdInfo_t::companyId, meshProdInfo_t::productId, meshProdInfo_t::versionId, and WSF_ASSERT.
MeshLocalCfgSetPublishAddress()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishAddress (meshElementId_t elementId, const meshModelId_t * pModelId, meshAddress_t publishAddress)
Sets publish non-virtual address based on a model ID.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] publishAddress Publish address.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgSetPublishAppKeyIndex()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishAppKeyIndex (meshElementId_t elementId, const meshModelId_t * pModelId, uint16_t appKeyIndex)
Sets model publish AppKey Index.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] appKeyIndex AppKey Index for model publication.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgSetPublishFriendshipCredFlag()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishFriendshipCredFlag (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishFriendshipCred_t friendshipCredFlag)
Sets model publish friendship security credential flag.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] friendshipCredFlag Publish friendship security credential flag. See meshPublishFriendshipCred_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgModelInfo_t::modelArraySize, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishFriendshipCred, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSetPublishPeriod()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishPeriod (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishPeriodNumSteps_t numberOfSteps, meshPublishPeriodStepRes_t stepResolution)
Sets model publish period in number of steps and step resolution.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] numberOfSteps Number of steps. See meshPublishPeriodNumSteps_t
[in] stepResolution The resolution of the number of steps field. See meshPublishPeriodStepRes_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgModelInfo_t::modelArraySize, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishPeriodNumSteps, meshLocalCfgModelPublication_t::publishPeriodStepRes, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSetPublishRetransCount()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishRetransCount (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishRetransCount_t retransCount)
Sets model publish retransmit count.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure
[in] retransCount Publish retransmit count value. See meshPublishRetransCount_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgModelInfo_t::modelArraySize, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishRetransCount, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSetPublishRetransIntvlSteps()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishRetransIntvlSteps (meshElementId_t elementId, const meshModelId_t * pModelId, meshPublishRetransIntvlSteps_t retransSteps)
Sets model publish retransmission interval steps.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] retransSteps Publish retransmit interval steps. See meshPublishRetransIntvlSteps_t
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
Remarks
The retransmission interval is calculated using the formula retransmitInterval = (publishRetransSteps + 1) * 50.
References MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgModelInfo_t::modelArraySize, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishRetransSteps50Ms, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSetPublishTtl()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishTtl (meshElementId_t elementId, const meshModelId_t * pModelId, uint8_t publishTtl)
Sets model publish TTL.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] publishTtl Publish TTL value.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgModelInfo_t::modelArraySize, meshLocalCfgModelInfo_t::pModelArray, meshLocalCfgModelEntry_t::publicationState, meshLocalCfgModelPublication_t::publishTtl, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSetPublishVirtualAddr()
meshLocalCfgRetVal_t MeshLocalCfgSetPublishVirtualAddr (meshElementId_t elementId, const meshModelId_t * pModelId, const uint8_t * pLabelUuid, meshAddress_t virtualAddr)
Sets publish virtual address based on a model ID.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] pLabelUuid Pointer to Label UUID.
[in] virtualAddr Virtual address for the Label UUID.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
MeshLocalCfgSetRelayRetransmitCount()
void MeshLocalCfgSetRelayRetransmitCount (uint8_t retransCount)
Sets the Relay Retransmit Count value which controls the number of retransmissions of the Network PDU relayed by the node.
Parameters
[in] retransCount Relay Retransmit Count value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetRelayRetransmitIntvlSteps()
void MeshLocalCfgSetRelayRetransmitIntvlSteps (uint8_t intvlSteps)
Sets the Relay Retransmit Interval Steps value representing the number of 10ms steps that controls the interval between retransmissions of Network PDUs relayed by the node.
Parameters
[in] intvlSteps Relay Retransmit Interval Steps value.
Returns
None.
References WsfNvmWriteData().
MeshLocalCfgSetRelayState()
void MeshLocalCfgSetRelayState (meshRelayStates_t relayState)
Sets the Relay state value.
Parameters
[in] relayState Relay state value. See meshRelayStates_t
Returns
None.
References MESH_RELAY_FEATURE_PROHIBITED_START, and WsfNvmWriteData().
MeshLocalCfgSetSeqNumber()
meshLocalCfgRetVal_t MeshLocalCfgSetSeqNumber (meshElementId_t elementId, meshSeqNumber_t seqNumber)
Sets the SEQ number value.
Parameters
[in] elementId Local element identifier.
[in] seqNumber SEQ number value.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SEQ_MAX_VAL, MESH_SUCCESS, MeshLocalCfgSetSeqNumberThresh(), and meshLocalCfgElementInfo_t::pSeqNumberArray.
MeshLocalCfgSetSeqNumberThresh()
void MeshLocalCfgSetSeqNumberThresh (meshElementId_t elementId, meshSeqNumber_t seqNumber)
Sets the SEQ number threshold value.
Parameters
[in] elementId Local element identifier.
[in] seqNumber SEQ number threshold value.
Returns
None.
References meshLocalCfgElementInfo_t::elementArrayLen, MESH_SEQ_MAX_VAL, meshLocalCfgElementInfo_t::pSeqNumberThreshArray, WSF_ASSERT, and WsfNvmWriteData().
MeshLocalCfgSubscrAddressListIsNotEmpty()
bool_t MeshLocalCfgSubscrAddressListIsNotEmpty (void)
Checks if Subscription Address List is not empty.
Returns
TRUE if not empty, FALSE otherwise.
MeshLocalCfgSubscrVirtualAddrListIsNotEmpty()
bool_t MeshLocalCfgSubscrVirtualAddrListIsNotEmpty (void)
Checks if Subscription Virtual Address List is not empty.
Returns
TRUE if not empty, FALSE otherwise.
MeshLocalCfgUnbindAppKeyFromModel()
void MeshLocalCfgUnbindAppKeyFromModel (meshElementId_t elementId, const meshModelId_t * pModelId, uint16_t appKeyIndex)
Unbinds an Application key index from a Model ID.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] appKeyIndex Application key index.
Returns
None.
References WSF_ASSERT.
MeshLocalCfgUnbindAppKeyToNetKey()
meshLocalCfgRetVal_t MeshLocalCfgUnbindAppKeyToNetKey (uint16_t appKeyIndex, uint16_t netKeyIndex)
Unbinds an Application key index from a Network key index.
Parameters
[in] appKeyIndex Application key index.
[in] netKeyIndex Network key index.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References meshLocalCfgAppKeyListEntry_t::appKeyIndex, meshLocalCfgAppKeyListInfo_t::appKeyListSize, MESH_LOCAL_CFG_INVALID_PARAMS, MESH_SUCCESS, meshLocalCfgAppKeyListEntry_t::netKeyEntryIndex, meshLocalCfgNetKeyListEntry_t::netKeyIndex, meshLocalCfgNetKeyListInfo_t::netKeyListSize, meshLocalCfgAppKeyListInfo_t::pAppKeyList, meshLocalCfgNetKeyListInfo_t::pNetKeyList, and WsfNvmWriteData().
MeshLocalCfgUpdateAppKey()
meshLocalCfgRetVal_t MeshLocalCfgUpdateAppKey (uint16_t appKeyIndex, const uint8_t * pAppKey)
Sets the new Application key for a key index.
Parameters
[in] appKeyIndex Application key index.
[in] pAppKey Pointer to the Application Key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgUpdateNetKey()
meshLocalCfgRetVal_t MeshLocalCfgUpdateNetKey (uint16_t netKeyIndex, const uint8_t * pNetKey)
Sets the new Network key for a key index.
Parameters
[in] netKeyIndex Network key index.
[in] pNetKey Pointer to the Network Key.
Returns
Success or error reason.
See also
meshLocalCfgRetVal_t
References WSF_ASSERT.
MeshLocalCfgValidateModelToAppKeyBind()
bool_t MeshLocalCfgValidateModelToAppKeyBind (meshElementId_t elementId, meshModelId_t * pModelId, uint16_t appKeyIndex)
Validates that an Application Key is bound to a Model instance.
Parameters
[in] elementId Local element identifier.
[in] pModelId Pointer to generic model identifier structure.
[in] appKeyIndex Application key index.
Returns
TRUE if bind exists, FALSE otherwise.
MeshLocalCfgValidateNetToAppKeyBind()
bool_t MeshLocalCfgValidateNetToAppKeyBind (uint16_t netKeyIndex, uint16_t appKeyIndex)
Validates if a Network-Application Key binding exists.
Parameters
[in] netKeyIndex Network Key index.
[in] appKeyIndex Application Key index.
Returns
TRUE if bind exists. FALSE otherwise.