Cordio: LL_API_ENCRYPT
LL_API_ENCRYPT
Data Structures
struct LlEncMode_t
Enumerations
enum
Functions
uint8_t LlEncrypt (uint8_t *pKey, uint8_t *pData)
uint8_t LlStartEncryption (uint16_t handle, const uint8_t *pRand, uint16_t diversifier, const uint8_t *pKey)
uint8_t LlLtkReqReply (uint16_t handle, const uint8_t *pKey)
uint8_t LlLtkReqNegReply (uint16_t handle)
uint8_t LlReadAuthPayloadTimeout (uint16_t handle, uint16_t *pTimeout)
uint8_t LlWriteAuthPayloadTimeout (uint16_t handle, uint16_t timeout)
uint8_t LlGetEncMode (uint16_t handle, LlEncMode_t *pMode)
uint8_t LlSetEncMode (uint16_t handle, const LlEncMode_t *pMode)
Detailed Description
Data Structure Documentation
LlEncMode_t
struct LlEncMode_t
Encryption mode data structure used in LlGetEncMode() and LlSetEncMode().
Data Fields
bool_t enaAuth
bool_t nonceMode
Field Documentation
enaAuth
bool_t enaAuth
Enable authentication.
nonceMode
bool_t nonceMode
Nonce mode.
Enumeration Type Documentation
anonymous enum
anonymous enum
Nonce mode.
Enumerator
LL_NONCE_MODE_PKT_CNTR
Packet counter nonce mode (default).
LL_NONCE_MODE_EVT_CNTR
Connection event counter mode.
Function Documentation
LlEncrypt()
uint8_t LlEncrypt (uint8_t * pKey, uint8_t * pData)
Encrypt data.
Parameters
pKey Encryption key.
pData 16 bytes of plain text data.
Returns
Status error code.
Request the LL to encryption a block of data in place.
Parameters
pKey Encryption key.
pData 16 bytes of plain text data.
Returns
Status error code.
Request the LL to encrypt a block of data in place.
LlGetEncMode()
uint8_t LlGetEncMode (uint16_t handle, LlEncMode_t * pMode)
Get encryption mode used in a connection.
Parameters
handle Connection handle.
pMode Storage for encryption mode.
Returns
Status error code.
Get the encryption mode used by a connection.
References LctrGetEncMode(), LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlLtkReqNegReply()
uint8_t LlLtkReqNegReply (uint16_t handle)
Negative reply to a LTK request.
Parameters
handle Connection handle.
Returns
Status error code.
Requested LTK encryption key not available. This function is only used when operating in slave mode.
Parameters
handle Connection handle.
Requested LTK encryption key not available. This function is only used when operating in slave mode.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, LCTR_CONN_MSG_API_LTK_NEG_REPLY, LCTR_DISP_CONN, LCTR_HOST_REPLY_LTK_REQ, LctrGetRole(), LctrIsConnHandleEnabled(), LctrIsWaitingForReply(), LL_ROLE_SLAVE, lmgrPersistCb, LlRtCfg_t::maxConn, pLctrRtCfg, WsfMsgAlloc(), and WsfMsgSend().
LlLtkReqReply()
uint8_t LlLtkReqReply (uint16_t handle, const uint8_t * pKey)
Reply to a LTK request.
Parameters
handle Connection handle.
pKey Pointer to new key.
Returns
Status error code.
Provide the requested LTK encryption key. This function is only used when operating in slave mode.
Parameters
handle Connection handle.
pKey Pointer to new key.
Provide the requested LTK encryption key. This function is only used when operating in slave mode.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, lctrLtkReply_t::hdr, lctrLtkReply_t::key, LCTR_CONN_MSG_API_LTK_REPLY, LCTR_DISP_CONN, LCTR_HOST_REPLY_LTK_REQ, LctrGetRole(), LctrIsConnHandleEnabled(), LctrIsWaitingForReply(), LL_ROLE_SLAVE, lmgrPersistCb, LlRtCfg_t::maxConn, pLctrRtCfg, WsfMsgAlloc(), and WsfMsgSend().
LlReadAuthPayloadTimeout()
uint8_t LlReadAuthPayloadTimeout (uint16_t handle, uint16_t * pTimeout)
Read authenticated payload timeout value.
Parameters
handle Connection handle.
pTimeout Pointer to timeout value.
Returns
Status error code.
Read authenticated payload timeout value for the given handle.
Parameters
handle Connection handle.
pTimeout Pointer to timeout value in 10 millisecond units.
Returns
Status error code.
Read authenticated payload timeout value for the given handle.
References LctrGetAuthPayloadTimeout(), LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlSetEncMode()
uint8_t LlSetEncMode (uint16_t handle, const LlEncMode_t * pMode)
Set encryption mode used in a connection.
Parameters
handle Connection handle.
pMode New encryption mode.
Returns
Status error code.
Set the encryption mode used by a connection. Must be called before encryption is started or when encryption is paused.
References LctrIsConnHandleEnabled(), LctrSetEncMode(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlStartEncryption()
uint8_t LlStartEncryption (uint16_t handle, const uint8_t * pRand, uint16_t diversifier, const uint8_t * pKey)
Start encryption.
Parameters
handle Connection handle.
pRand Pointer to the random number.
diversifier Diversifier value.
pKey Pointer to the encryption key.
Returns
Status error code.
Start or restart link layer encryption on a connection. This function is only used when operating in master role.
References LCTR_CONN_MSG_API_START_ENC, and LctrIsProcActPended().
LlWriteAuthPayloadTimeout()
uint8_t LlWriteAuthPayloadTimeout (uint16_t handle, uint16_t timeout)
Write authenticated payload timeout value.
Parameters
handle Connection handle.
timeout New timeout value.
Returns
Status error code.
Write new authenticated payload timeout value for the given handle.
Parameters
handle Connection handle.
timeout New timeout value in 10 millisecond units.
Returns
Status error code.
Write new authenticated payload timeout value for the given handle.
References LctrIsConnHandleEnabled(), LctrSetAuthPayloadTimeout(), LlRtCfg_t::maxConn, and pLctrRtCfg.