Cordio: APP_FRAMEWORK_UI_API
APP_FRAMEWORK_UI_API
Data Structures
struct appUiSound_t
struct appUiLed_t
struct appUiCback_t
Macros
#define APP_UI_LED_NONE 0x00
#define APP_UI_LED_1 0x01
#define APP_UI_LED_2 0x02
#define APP_UI_LED_3 0x04
#define APP_UI_LED_4 0x08
#define APP_UI_LED_WRAP 0xFF
#define APP_UI_SOUND_WRAP 0xFFFF
Typedefs
typedef void(* appUiBtnCback_t) (uint8_t btn)
typedef void(* appUiActionCback_t) (uint8_t event, uint32_t param)
typedef void(* appUiBtnPollCback_t) (void)
typedef void(* appUiPrintFunc_t) (const char *txt)
Enumerations
enum
enum
APP Terminal Functions
Open a terminal interface to the application.
void AppTerminalInit (void)
APP User Interface
Commands that may be sent via terminal to the application.
void AppUiAction (uint8_t event)
void AppUiDisplayPasskey (uint32_t passkey)
void AppUiDisplayConfirmValue (uint32_t confirm)
void AppUiDisplayRssi (int8_t rssi)
void AppUiBtnRegister (appUiBtnCback_t btnCback)
void AppUiActionRegister (appUiActionCback_t actionCback)
void AppUiBtnPollRegister (appUiBtnPollCback_t btnPollCback)
void AppUiBtnPressed (void)
void AppUiSoundPlay (const appUiSound_t *pSound)
void AppUiSoundStop (void)
void AppUiLedStart (const appUiLed_t *pLed)
void AppUiLedStop (void)
void AppUiBtnTest (uint8_t btn)
Detailed Description
Data Structure Documentation
appUiSound_t
struct appUiSound_t
Sound data structure.
Data Fields
uint16_t tone
uint16_t duration
appUiLed_t
struct appUiLed_t
LED data structure.
Data Fields
uint8_t led
uint8_t state
uint16_t duration
appUiCback_t
struct appUiCback_t
Callback structure.
Data Fields
appUiBtnCback_t btnCback
appUiActionCback_t actionCback
appUiBtnPollCback_t btnPollCback
Macro Definition Documentation
APP_UI_LED_NONE
#define APP_UI_LED_NONE 0x00
LED values.
No LED
Enumeration Type Documentation
anonymous enum
anonymous enum
UI event enumeration.
Enumerator
APP_UI_NONE
No event.
APP_UI_RESET_CMPL
Reset complete.
APP_UI_DISCOVERABLE
Enter discoverable mode.
APP_UI_ADV_START
Advertising started.
APP_UI_ADV_STOP
Advertising stopped.
APP_UI_SCAN_START
Scanning started.
APP_UI_SCAN_STOP
Scanning stopped.
APP_UI_SCAN_REPORT
Scan data received from peer device.
APP_UI_CONN_OPEN
Connection opened.
APP_UI_CONN_CLOSE
Connection closed.
APP_UI_SEC_PAIR_CMPL
Pairing completed successfully.
APP_UI_SEC_PAIR_FAIL
Pairing failed or other security failure.
APP_UI_SEC_ENCRYPT
Connection encrypted.
APP_UI_SEC_ENCRYPT_FAIL
Encryption failed.
APP_UI_PASSKEY_PROMPT
Prompt user to enter passkey.
APP_UI_DISPLAY_PASSKEY
Display passkey.
APP_UI_DISPLAY_CONFIRM
Display confirm value.
APP_UI_DISPLAY_RSSI
Display rssi.
APP_UI_ALERT_CANCEL
Cancel a low or high alert.
APP_UI_ALERT_LOW
Low alert.
APP_UI_ALERT_HIGH
High alert.
APP_UI_ADV_SET_START_IND
Advertising set(s) started.
APP_UI_ADV_SET_STOP_IND
Advertising set(s) stopped.
APP_UI_SCAN_REQ_RCVD_IND
Scan request received.
APP_UI_EXT_SCAN_START_IND
Extended scanning started.
APP_UI_EXT_SCAN_STOP_IND
Extended scanning stopped.
APP_UI_PER_ADV_SET_START_IND
Periodic advertising set started.
APP_UI_PER_ADV_SET_STOP_IND
Periodic advertising set stopped.
APP_UI_PER_ADV_SYNC_EST_IND
Periodic advertising sync established.
APP_UI_PER_ADV_SYNC_LOST_IND
Periodic advertising sync lost.
APP_UI_HW_ERROR
Hardware error.
anonymous enum
anonymous enum
Button press enumeration.
Enumerator
APP_UI_BTN_NONE
No button press.
APP_UI_BTN_1_DOWN
Button 1 on down press.
APP_UI_BTN_1_SHORT
Button 1 short press.
APP_UI_BTN_1_MED
Button 1 medium press.
APP_UI_BTN_1_LONG
Button 1 long press.
APP_UI_BTN_1_EX_LONG
Button 1 extra long press.
APP_UI_BTN_2_DOWN
Button 2 on down press.
APP_UI_BTN_2_SHORT
Button 2 short press.
APP_UI_BTN_2_MED
Button 2 medium press.
APP_UI_BTN_2_LONG
Button 2 long press.
APP_UI_BTN_2_EX_LONG
Button 2 extra long press.
Function Documentation
AppTerminalInit()
void AppTerminalInit (void)
Initialize terminal.
Returns
None.
References APP_UI_BTN_1_DOWN, APP_UI_BTN_1_EX_LONG, APP_UI_BTN_1_LONG, APP_UI_BTN_1_MED, APP_UI_BTN_1_SHORT, APP_UI_BTN_2_DOWN, APP_UI_BTN_2_EX_LONG, APP_UI_BTN_2_LONG, APP_UI_BTN_2_MED, APP_UI_BTN_2_SHORT, AppUiBtnTest(), DM_CONN_MAX, DmSecAuthRsp(), SMP_PIN_LEN, TERMINAL_ERROR_BAD_ARGUMENTS, TERMINAL_ERROR_OK, TERMINAL_ERROR_TOO_FEW_ARGUMENTS, TERMINAL_ERROR_TOO_MANY_ARGUMENTS, TERMINAL_STRING_NEW_LINE, TerminalHandler(), TerminalInit(), TerminalRegisterCommand(), TerminalRegisterUartTxFunc(), TerminalRx(), TerminalTxPrint(), UINT32_TO_BYTE0, UINT32_TO_BYTE1, UINT32_TO_BYTE2, WsfBufIoUartRegister(), WsfBufIoWrite(), and WsfOsSetNextHandler().
AppUiAction()
void AppUiAction (uint8_t event)
Perform a user interface action based on the event value passed to the function.
Parameters
event User interface event value.
Returns
None.
References appUiCback_t::actionCback, APP_UI_ADV_SET_START_IND, APP_UI_ADV_SET_STOP_IND, APP_UI_ADV_START, APP_UI_ADV_STOP, APP_UI_ALERT_CANCEL, APP_UI_ALERT_HIGH, APP_UI_ALERT_LOW, APP_UI_CONN_CLOSE, APP_UI_CONN_OPEN, APP_UI_EXT_SCAN_START_IND, APP_UI_EXT_SCAN_STOP_IND, APP_UI_NONE, APP_UI_PASSKEY_PROMPT, APP_UI_PER_ADV_SET_START_IND, APP_UI_PER_ADV_SET_STOP_IND, APP_UI_PER_ADV_SYNC_EST_IND, APP_UI_PER_ADV_SYNC_LOST_IND, APP_UI_RESET_CMPL, APP_UI_SCAN_REPORT, APP_UI_SCAN_REQ_RCVD_IND, APP_UI_SCAN_START, APP_UI_SCAN_STOP, APP_UI_SEC_ENCRYPT, APP_UI_SEC_ENCRYPT_FAIL, APP_UI_SEC_PAIR_CMPL, and APP_UI_SEC_PAIR_FAIL.
AppUiActionRegister()
void AppUiActionRegister (appUiActionCback_t actionCback)
Register a callback function to receive action events.
Parameters
actionCback Callback function.
Returns
None.
Note
Registered by platform
Returns
None.
Note
Registered by platform
References appUiCback_t::actionCback.
AppUiBtnPollRegister()
void AppUiBtnPollRegister (appUiBtnPollCback_t btnPollCback)
Register a callback function to receive APP_BTN_POLL_IND events.
Parameters
btnPollCback Callback function.
Returns
None.
Note
Registered by platform
Returns
None.
Note
Registered by platform
References appUiCback_t::btnPollCback.
AppUiBtnPressed()
void AppUiBtnPressed (void)
Handle a hardware button press. This function is called to handle WSF event APP_BTN_DOWN_EVT.
Returns
None.
AppUiBtnRegister()
void AppUiBtnRegister (appUiBtnCback_t btnCback)
Register a callback function to receive button presses.
Parameters
btnCback Callback function.
Returns
None.
Note
Registered by application to receive button events
Register a callback function to receive button presses.
Returns
None.
Note
Registered by application to receive button events
References appUiCback_t::btnCback.
AppUiBtnTest()
void AppUiBtnTest (uint8_t btn)
Button test function– for test purposes only.
Parameters
btn button press
Returns
None.
None.
References appUiCback_t::btnCback.
AppUiDisplayConfirmValue()
void AppUiDisplayConfirmValue (uint32_t confirm)
Display a confirmation value.
Parameters
confirm Confirm value to display.
Returns
None.
References appUiCback_t::actionCback, and APP_UI_DISPLAY_CONFIRM.
AppUiDisplayPasskey()
void AppUiDisplayPasskey (uint32_t passkey)
Display a passkey.
Parameters
passkey Passkey to display.
Returns
None.
References appUiCback_t::actionCback, and APP_UI_DISPLAY_PASSKEY.
AppUiDisplayRssi()
void AppUiDisplayRssi (int8_t rssi)
Display an RSSI value.
Parameters
rssi Rssi value to display.
Returns
None.
References appUiCback_t::actionCback, APP_UI_DISPLAY_RSSI, and appUiCback_t::btnPollCback.
AppUiLedStart()
void AppUiLedStart (const appUiLed_t * pLed)
Start LED blinking.
Parameters
pLed Pointer to LED data structure.
Returns
None.
AppUiLedStop()
void AppUiLedStop (void)
Stop LED blinking.
Returns
None.
AppUiSoundPlay()
void AppUiSoundPlay (const appUiSound_t * pSound)
Play a sound.
Parameters
pSound Pointer to sound tone/duration array.
Returns
None.
AppUiSoundStop()
void AppUiSoundStop (void)
Stop the sound that is currently playing.
Returns
None.