Cordio: APP_FRAMEWORK_API
APP_FRAMEWORK_API
APP_FRAMEWORK_DB_API
Data Structures
struct appAdvCfg_t
struct appExtAdvCfg_t
struct appSlaveCfg_t
struct appMasterCfg_t
struct appExtMasterCfg_t
struct appSecCfg_t
struct appUpdateCfg_t
struct appReqActCfg_t
struct appDiscCfg_t
struct appCfg_t
struct appDevInfo_t
Macros
#define APP_ADV_NUM_CFG APP_ADV_STOPPED
#define APP_RESOLVE_ADV_RPA 0
#define APP_RESOLVE_DIRECT_RPA 1
#define APP_SCAN_RESULT_MAX 10
Typedefs
typedef void(* appDiscCback_t) (dmConnId_t connId, uint8_t status)
Enumerations
enum
enum
enum
enum
Variables
appAdvCfg_t * pAppAdvCfg
appExtAdvCfg_t * pAppExtAdvCfg
appSlaveCfg_t * pAppSlaveCfg
appMasterCfg_t * pAppMasterCfg
appExtMasterCfg_t * pAppExtMasterCfg
appSecCfg_t * pAppSecCfg
appUpdateCfg_t * pAppUpdateCfg
appDiscCfg_t * pAppDiscCfg
appCfg_t * pAppCfg
appReqActCfg_t * pAppMasterReqActCfg
appReqActCfg_t * pAppSlaveReqActCfg
App Advertising Mode
Discoverable/connectable mode used by function AppAdvStart.
#define APP_MODE_CONNECTABLE 0
#define APP_MODE_DISCOVERABLE 1
#define APP_MODE_AUTO_INIT 2
#define APP_MODE_NONE 255
#define APP_NUM_MODES 2
App Initialization Functions
Application role initialization.
void AppSlaveInit (void)
void AppMasterInit (void)
App Advertising Functions
Configure and send legacy, extended and periodic advertisments.
void AppSetAdvType (uint8_t advType)
void AppSetAdvPeerAddr (uint8_t peerAddrType, uint8_t *pPeerAddr)
void AppAdvSetData (uint8_t location, uint8_t len, uint8_t *pData)
bool_t AppAdvSetAdValue (uint8_t location, uint8_t adType, uint8_t len, uint8_t *pValue)
void AppAdvStart (uint8_t mode)
void AppAdvStop (void)
dmConnId_t AppConnAccept (uint8_t advType, uint8_t addrType, uint8_t *pAddr, appDbHdl_t dbHdl)
bool_t AppSlaveIsAdvertising (void)
void AppSlaveClearAllBondingInfo (void)
void AppExtSetAdvPeerAddr (uint8_t advHandle, uint8_t peerAddrType, uint8_t *pPeerAddr)
void AppExtAdvSetData (uint8_t advHandle, uint8_t location, uint16_t len, uint8_t *pData, uint16_t bufLen)
void AppExtAdvStart (uint8_t numSets, uint8_t *pAdvHandles, uint8_t mode)
void AppExtAdvStop (uint8_t numSets, uint8_t *pAdvHandles)
bool_t AppExtAdvSetAdValue (uint8_t advHandle, uint8_t location, uint8_t adType, uint8_t len, uint8_t *pValue)
void AppExtSetAdvType (uint8_t advHandle, uint8_t advType)
dmConnId_t AppExtConnAccept (uint8_t advHandle, uint8_t advType, uint8_t addrType, uint8_t *pAddr, appDbHdl_t dbHdl)
void AppPerAdvSetData (uint8_t advHandle, uint16_t len, uint8_t *pData, uint16_t bufLen)
void AppPerAdvStart (uint8_t advHandle)
void AppPerAdvStop (uint8_t advHandle)
bool_t AppPerAdvSetAdValue (uint8_t advHandle, uint8_t adType, uint8_t len, uint8_t *pValue)
App Scan Functions
configure and enable legacy and extended scanning and periodic synch.
void AppScanStart (uint8_t mode, uint8_t scanType, uint16_t duration)
void AppScanStop (void)
void AppMasterResolveAddr (dmEvt_t *pMsg, appDbHdl_t dbHdl, uint8_t resolveType)
void AppExtScanStart (uint8_t scanPhys, uint8_t mode, const uint8_t *pScanType, uint16_t duration, uint16_t period)
void AppExtScanStop (void)
appDevInfo_t * AppScanGetResult (uint8_t idx)
uint8_t AppScanGetNumResults (void)
dmSyncId_t AppSyncStart (uint8_t advSid, uint8_t advAddrType, const uint8_t *pAdvAddr, uint16_t skip, uint16_t syncTimeout)
void AppSyncStop (dmSyncId_t syncId)
App Connection Functions
Initiate and update connections
dmConnId_t AppConnOpen (uint8_t addrType, uint8_t *pAddr, appDbHdl_t dbHdl)
void AppConnClose (dmConnId_t connId)
dmConnId_t AppExtConnOpen (uint8_t initPhys, uint8_t addrType, uint8_t *pAddr, appDbHdl_t dbHdl)
dmConnId_t AppConnIsOpen (void)
uint8_t AppConnOpenList (dmConnId_t *pConnIdList)
App Security and Bonding Functions
Security and Bonding functions for configuration and interaction with STACK_SMP Pairing procedures.
void AppSetBondable (bool_t bondable)
void AppMasterSecurityReq (dmConnId_t connId)
void AppSlaveSecurityReq (dmConnId_t connId)
void AppHandlePasskey (dmSecAuthReqIndEvt_t *pAuthReq)
void AppHandleNumericComparison (dmSecCnfIndEvt_t *pCnfInd)
App Event Processing
Process received messages for which there is a general process.
void AppSlaveProcDmMsg (dmEvt_t *pMsg)
void AppSlaveSecProcDmMsg (dmEvt_t *pMsg)
void AppMasterProcDmMsg (dmEvt_t *pMsg)
void AppMasterSecProcDmMsg (dmEvt_t *pMsg)
void AppServerInit (void)
void AppServerConnCback (dmEvt_t *pDmEvt)
void AppServerProcAttMsg (wsfMsgHdr_t *pMsg)
APP Service Discovery
GATT Service Discovery initialization, configuration and execution.
void AppDiscInit (void)
void AppDiscRegister (appDiscCback_t cback)
void AppDiscSetHdlList (dmConnId_t connId, uint8_t hdlListLen, uint16_t *pHdlList)
void AppDiscComplete (dmConnId_t connId, uint8_t status)
void AppDiscFindService (dmConnId_t connId, uint8_t uuidLen, uint8_t *pUuid, uint8_t listLen, attcDiscChar_t **pCharList, uint16_t *pHdlList)
void AppDiscConfigure (dmConnId_t connId, uint8_t status, uint8_t cfgListLen, attcDiscCfg_t *pCfgList, uint8_t hdlListLen, uint16_t *pHdlList)
void AppDiscServiceChanged (attEvt_t *pMsg)
void AppDiscProcDmMsg (dmEvt_t *pMsg)
void AppDiscProcAttMsg (attEvt_t *pMsg)
bool_t AppDiscGetHandleRange (dmConnId_t connId, uint16_t *pStartHdl, uint16_t *pEndHdl)
void AppDiscReadDatabaseHash (dmConnId_t connId)
App Privacy Functions
Maintain privacy information about known peer devices.
void AppAddDevToResList (dmEvt_t *pMsg, dmConnId_t connId)
appDbHdl_t AppAddNextDevToResList (appDbHdl_t hdl)
void AppClearAllBondingInfo (void)
void AppUpdatePrivacyMode (appDbHdl_t hdl)
Detailed Description
Data Structure Documentation
appAdvCfg_t
struct appAdvCfg_t
Configurable parameters for advertising.
Data Fields
uint16_t advDuration [APP_ADV_NUM_CFG]
uint16_t advInterval [APP_ADV_NUM_CFG]
appExtAdvCfg_t
struct appExtAdvCfg_t
Configurable parameters for extended and periodic advertising.
Data Fields
uint16_t advDuration [DM_NUM_ADV_SETS]
uint16_t advInterval [DM_NUM_ADV_SETS]
uint8_t maxEaEvents [DM_NUM_ADV_SETS]
bool_t useLegacyPdu [DM_NUM_ADV_SETS]
uint16_t perAdvInterval [DM_NUM_ADV_SETS]
appSlaveCfg_t
struct appSlaveCfg_t
Configurable parameters for slave.
Data Fields
uint8_t connMax
appMasterCfg_t
struct appMasterCfg_t
Configurable parameters for master.
Data Fields
uint16_t scanInterval
uint16_t scanWindow
uint16_t scanDuration
uint8_t discMode
uint8_t scanType
appExtMasterCfg_t
struct appExtMasterCfg_t
Configurable parameters for extended master.
Data Fields
uint16_t scanInterval [DM_NUM_PHYS]
uint16_t scanWindow [DM_NUM_PHYS]
uint16_t scanDuration
uint16_t scanPeriod
uint8_t discMode
uint8_t scanType [DM_NUM_PHYS]
appSecCfg_t
struct appSecCfg_t
Configurable parameters for security.
Data Fields
uint8_t auth
uint8_t iKeyDist
uint8_t rKeyDist
bool_t oob
bool_t initiateSec
appUpdateCfg_t
struct appUpdateCfg_t
Configurable parameters for connection parameter update.
Data Fields
wsfTimerTicks_t idlePeriod
uint16_t connIntervalMin
uint16_t connIntervalMax
uint16_t connLatency
uint16_t supTimeout
uint8_t maxAttempts
appReqActCfg_t
struct appReqActCfg_t
Configurable parameters for incoming request actions.
Data Fields
uint8_t remConnParamReqAct
appDiscCfg_t
struct appDiscCfg_t
Configurable parameters for service and characteristic discovery.
Data Fields
bool_t waitForSec
bool_t readDbHash
appCfg_t
struct appCfg_t
Configurable parameters for application.
Data Fields
bool_t abortDisc
bool_t disconnect
appDevInfo_t
struct appDevInfo_t
Device information data type.
Data Fields
bdAddr_t addr
uint8_t addrType
uint8_t directAddrType
bdAddr_t directAddr
Typedef Documentation
appDiscCback_t
typedef void(* appDiscCback_t) (dmConnId_t connId, uint8_t status)
Service discovery and configuration callback.
Parameters
connId Connection identifier.
status Service or configuration status.
Returns
None.
Enumeration Type Documentation
anonymous enum
anonymous enum
Advertising states.
Enumerator
APP_ADV_STATE1
Advertising state 1.
APP_ADV_STATE2
Advertising state 2.
APP_ADV_STATE3
Advertising state 3.
APP_ADV_STOPPED
Advertising stopped.
anonymous enum
anonymous enum
Advertising and scan data storage locations.
Enumerator
APP_ADV_DATA_CONNECTABLE
Advertising data for connectable mode.
APP_SCAN_DATA_CONNECTABLE
Scan data for connectable mode.
APP_ADV_DATA_DISCOVERABLE
Advertising data for discoverable mode.
APP_SCAN_DATA_DISCOVERABLE
Scan data for discoverable mode.
APP_NUM_DATA_LOCATIONS
number of data storage locations.
anonymous enum
anonymous enum
Service discovery and configuration client status.
Enumerator
APP_DISC_INIT
No discovery or configuration complete.
APP_DISC_READ_DATABASE_HASH
Read peer's database hash.
APP_DISC_SEC_REQUIRED
Security required to complete configuration.
APP_DISC_START
Service discovery started.
APP_DISC_CMPL
Service discovery complete.
APP_DISC_FAILED
Service discovery failed.
APP_DISC_CFG_START
Service configuration started.
APP_DISC_CFG_CONN_START
Configuration for connection setup started.
APP_DISC_CFG_CMPL
Service configuration complete.
anonymous enum
anonymous enum
Actions for incoming requests.
Enumerator
APP_ACT_ACCEPT
Accept incoming request.
APP_ACT_REJECT
Reject incoming request.
APP_ACT_NONE
Do nothing - app will handle incoming request.
Function Documentation
AppAddDevToResList()
void AppAddDevToResList (dmEvt_t * pMsg, dmConnId_t connId)
Add device to resolving list.
Parameters
pMsg Pointer to DM callback event message.
connId Connection identifier.
Returns
None.
References dmSecIrk_t::addrType, AppDbGetKey(), dmSecIrk_t::bdAddr, DM_KEY_IRK, DmPrivAddDevToResList(), DmSecGetLocalIrk(), HciLlPrivacySupported(), dmSecKey_t::irk, and dmSecIrk_t::key.
AppAddNextDevToResList()
appDbHdl_t AppAddNextDevToResList (appDbHdl_t hdl)
Add next device to resolving list. For the first device, the function should be called with 'hdl' set to 'APP_DB_HDL_NONE'.
Parameters
hdl The last handle returned by AppAddNextDevToResList or APP_DB_HDL_NONE to begin.
Returns
The handle being restored or APP_DB_HDL_NONE when the operation is complete.
Note
Applications supporting address resolution should call this functions after DmDevReset. This function will restore the resolving list in the Controller using information in the app device database.
After each device is added to resolving list, the DM will send DM_PRIV_ADD_DEV_TO_RES_LIST_IND to the application. The application must call AppAddNextDevToResList again to continue the restore process until AppAddNextDevToResList returns APP_DB_HDL_NONE.
References dmSecIrk_t::addrType, APP_DB_HDL_NONE, AppDbGetKey(), AppDbGetNextRecord(), AppDbGetPeerRpao(), dmSecIrk_t::bdAddr, DM_KEY_IRK, DM_PRIV_MODE_DEVICE, DmPrivAddDevToResList(), DmPrivSetPrivacyMode(), DmSecGetLocalIrk(), dmSecKey_t::irk, dmSecIrk_t::key, and WSF_ASSERT.
AppAdvSetAdValue()
bool_t AppAdvSetAdValue (uint8_t location, uint8_t adType, uint8_t len, uint8_t * pValue)
Set the value of an advertising data element in the advertising or scan response data. If the element already exists in the data then it is replaced with the new value. If the element does not exist in the data it is appended to it, space permitting.
There is special handling for the device name (AD type DM_ADV_TYPE_LOCAL_NAME). If the name can only fit in the data if it is shortened, the name is shortened and the AD type is changed to DM_ADV_TYPE_SHORT_NAME.
Parameters
location Data location.
adType Advertising data element type.
len Length of the value. Maximum length is 29 bytes.
pValue Pointer to the value.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
There is special handling for the device name (AD type DM_ADV_TYPE_LOCAL_NAME). If the name can only fit in the data if it is shortened, the name is shortened and the AD type is changed to DM_ADV_TYPE_SHORT_NAME.
Parameters
location Data location.
adType Advertising data element type.
len Length of the value. Maximum length is 31 bytes.
pValue Pointer to the value.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
AppAdvSetData()
void AppAdvSetData (uint8_t location, uint8_t len, uint8_t * pData)
Set advertising or scan data. Separate advertising and scan data can be set for connectable and discoverable modes. The application must allocate and maintain the memory pointed to by pData while the device is advertising.
Parameters
location Data location.
len Length of the data. Maximum length is 31 bytes.
pData Pointer to the data.
Returns
None.
Set advertising or scan data. Separate advertising and scan data can be set for connectable and discoverable modes. The application must allocate and maintain the memory pointed to by pData while the device is advertising.
Parameters
location Data location.
len Length of the data. Maximum length is 31 bytes.
pData Pointer to the data.
Returns
None.
References DM_ADV_HANDLE_DEFAULT, and HCI_ADV_DATA_LEN.
AppAdvStart()
void AppAdvStart (uint8_t mode)
Start advertising using the parameters for the given mode.
Parameters
mode Discoverable/connectable mode.
Returns
None.
References appAdvCfg_t::advDuration, appAdvCfg_t::advInterval, appSlaveCb_t::advState, APP_ADV_STATE1, DM_ADV_HANDLE_DEFAULT, and pAppAdvCfg.
AppAdvStop()
void AppAdvStop (void)
Stop advertising. The device will no longer be connectable or discoverable.
Returns
None.
Stop advertising. The device will no longer be connectable or discoverable.
Returns
None.
References DM_ADV_HANDLE_DEFAULT.
AppClearAllBondingInfo()
void AppClearAllBondingInfo (void)
Clear all bonding information.
Returns
None.
This API should not be used when:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
Otherwise, clearing the resolving list in the Controller may fail.
References AppDbDeleteAllRecords(), DmLlPrivEnabled(), DmPrivSetAddrResEnable(), and HciLlPrivacySupported().
AppConnAccept()
dmConnId_t AppConnAccept (uint8_t advType, uint8_t addrType, uint8_t * pAddr, appDbHdl_t dbHdl)
Accept a connection to a peer device with the given address.
Parameters
advType Advertising type.
addrType Address type.
pAddr Peer device address.
dbHdl Device database handle.
Returns
Connection identifier.
References appAdvCfg_t::advDuration, appAdvCfg_t::advInterval, APP_ADV_STATE1, DM_ADV_HANDLE_DEFAULT, and pAppAdvCfg.
AppConnClose()
void AppConnClose (dmConnId_t connId)
Close a connection with the given connection identifier.
Parameters
connId Connection identifier.
Returns
None.
Close a connection with the given connection identifier.
Parameters
connId Connection identifier.
Returns
None.
References DM_CLIENT_ID_APP, DmConnClose(), and HCI_ERR_REMOTE_TERMINATED.
AppConnIsOpen()
dmConnId_t AppConnIsOpen (void)
Check if a connection is open.
Returns
Connection ID of open connection or DM_CONN_ID_NONE if no open connections.
References appConnCb_t::connId, DM_CONN_ID_NONE, and DM_CONN_MAX.
AppConnOpen()
dmConnId_t AppConnOpen (uint8_t addrType, uint8_t * pAddr, appDbHdl_t dbHdl)
Open a connection to a peer device with the given address.
Parameters
addrType Address type.
pAddr Peer device address.
dbHdl Device database handle.
Returns
Connection identifier.
References DM_CONN_ID_NONE, and HCI_INIT_PHY_LE_1M_BIT.
AppConnOpenList()
uint8_t AppConnOpenList (dmConnId_t * pConnIdList)
Gets a list of connection identifiers of open connections.
Parameters
pConnIdList Buffer to hold connection IDs (must be DM_CONN_MAX bytes).
Returns
Number of open connections.
Gets a list of connection identifiers of open connections.
Parameters
pConnIdList Buffer to hold connection IDs (must be DM_CONN_MAX bytes).
Returns
Number of open connections.
References appConnCb_t::connId, DM_CONN_ID_NONE, and DM_CONN_MAX.
AppDiscComplete()
void AppDiscComplete (dmConnId_t connId, uint8_t status)
Service discovery or configuration procedure complete.
Parameters
connId Connection identifier.
status Service or configuration status.
Returns
None.
References APP_DB_HDL_NONE, APP_DISC_CFG_CMPL, APP_DISC_CFG_CONN_START, APP_DISC_CMPL, AppDbGetHdl(), AppDbSetDiscStatus(), AppDbSetHdlList(), DM_CONN_IDLE, DM_IDLE_APP_DISC, DmConnSetIdle(), and WsfBufFree().
AppDiscConfigure()
void AppDiscConfigure (dmConnId_t connId, uint8_t status, uint8_t cfgListLen, attcDiscCfg_t * pCfgList, uint8_t hdlListLen, uint16_t * pHdlList)
Configure characteristics for discovered services.
Parameters
connId Connection identifier.
status APP_DISC_CFG_START or APP_DISC_CFG_CONN_START.
cfgListLen Length of characteristic configuration list.
pCfgList Characteristic configuration list.
hdlListLen Length of characteristic handle list.
pHdlList Characteristic handle list.
Returns
None.
References APP_DISC_CFG_CMPL, APP_DISC_CFG_CONN_START, ATT_SUCCESS, AttcDiscConfigStart(), DM_CONN_BUSY, DM_IDLE_APP_DISC, DmConnSetIdle(), and WsfBufAlloc().
AppDiscFindService()
void AppDiscFindService (dmConnId_t connId, uint8_t uuidLen, uint8_t * pUuid, uint8_t listLen, attcDiscChar_t ** pCharList, uint16_t * pHdlList)
Perform service and characteristic discovery for a given service.
Parameters
connId Connection identifier.
uuidLen Length of service UUID (2 or 16).
pUuid Pointer to service UUID.
listLen Length of characteristic and handle lists.
pCharList Characterisic list for discovery.
pHdlList Characteristic handle list.
Returns
None.
Parameters
connId Connection identifier.
uuidLen Length of UUID (2 or 16).
pUuid Pointer to UUID data.
listLen Length of characteristic and handle lists.
pCharList Characterisic list for discovery.
pHdlList Characteristic handle list.
Returns
None.
References AttcDiscService(), DM_CONN_BUSY, DM_IDLE_APP_DISC, DmConnSetIdle(), and WsfBufAlloc().
AppDiscGetHandleRange()
bool_t AppDiscGetHandleRange (dmConnId_t connId, uint16_t * pStartHdl, uint16_t * pEndHdl)
Get the handle range of the latest service discovery operation.
May be called after receiving a APP_DISC_CMPL event, but before calling AppDiscComplete().
Parameters
connId connection identifier.
pStartHdl output parameter for start handle.
pEndHdl output parameter for end handle.
Returns
TRUE if handles were set, FALSE otherwise.
AppDiscInit()
void AppDiscInit (void)
Initialize app framework discovery.
Returns
None.
References DM_CONN_MAX.
AppDiscProcAttMsg()
void AppDiscProcAttMsg (attEvt_t * pMsg)
Process discovery-related ATT messages. This function should be called from the application's event handler.
Parameters
pMsg Pointer to ATT callback event message.
Returns
None.
References APP_DB_HDL_NONE, APP_DISC_START, AppDbGetHdl(), AppDbGetPeerDbHash(), AppDbNewRecord(), AppDbSetCacheByHash(), AppDbSetPeerDbHash(), ATT_DATABASE_HASH_LEN, ATT_ERR_DATABASE_OUT_OF_SYNC, ATT_SUCCESS, ATTC_READ_BY_TYPE_RSP, DmConnPeerAddr(), DmConnPeerAddrType(), wsfMsgHdr_t::event, attEvt_t::hdr, wsfMsgHdr_t::param, attEvt_t::pValue, and wsfMsgHdr_t::status.
AppDiscProcDmMsg()
void AppDiscProcDmMsg (dmEvt_t * pMsg)
Process discovery-related DM messages. This function should be called from the application's event handler.
Parameters
pMsg Pointer to DM callback event message.
Returns
None.
References DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, DM_SEC_ENCRYPT_IND, DM_SEC_PAIR_CMPL_IND, DM_SEC_PAIR_FAIL_IND, wsfMsgHdr_t::event, and dmEvt_t::hdr.
AppDiscReadDatabaseHash()
void AppDiscReadDatabaseHash (dmConnId_t connId)
Read peer's database hash.
Parameters
dmConnId_t Connection ID.
Returns
None.
References ATT_16_UUID_LEN, ATT_HANDLE_MAX, ATT_HANDLE_START, AttcReadByTypeReq(), and attGattDbhChUuid.
AppDiscRegister()
void AppDiscRegister (appDiscCback_t cback)
Register a callback function to service discovery status.
Parameters
cback Application service discovery callback function.
Returns
None.
AppDiscServiceChanged()
void AppDiscServiceChanged (attEvt_t * pMsg)
Perform the GATT service changed procedure. This function is called when an indication is received containing the GATT service changed characteristic. This function may initialize the discovery state and initiate service discovery and configuration.
Parameters
pMsg Pointer to ATT callback event message containing received indication.
Returns
None.
References attEvt_t::hdr, and wsfMsgHdr_t::param.
AppDiscSetHdlList()
void AppDiscSetHdlList (dmConnId_t connId, uint8_t hdlListLen, uint16_t * pHdlList)
Set the discovery cached handle list for a given connection.
Parameters
connId Connection identifier.
hdlListLen Length of characteristic and handle lists.
pHdlList Characteristic handle list.
Returns
None.
Parameters
connId Connection identifier.
listLen Length of characteristic and handle lists.
pHdlList Characteristic handle list.
Returns
None.
AppExtAdvSetAdValue()
bool_t AppExtAdvSetAdValue (uint8_t advHandle, uint8_t location, uint8_t adType, uint8_t len, uint8_t * pValue)
Set the value of an advertising data element in the extended advertising or scan response data. If the element already exists in the data then it is replaced with the new value. If the element does not exist in the data it is appended to it, space permitting.
There is special handling for the device name (AD type DM_ADV_TYPE_LOCAL_NAME). If the name can only fit in the data if it is shortened, the name is shortened and the AD type is changed to DM_ADV_TYPE_SHORT_NAME.
Parameters
advHandle Advertising handle.
location Data location.
adType Advertising data element type.
len Length of the value. Maximum length is 31 bytes if advertising set uses legacy advertising PDUs with extended advertising.
pValue Pointer to the value.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
AppExtAdvSetData()
void AppExtAdvSetData (uint8_t advHandle, uint8_t location, uint16_t len, uint8_t * pData, uint16_t bufLen)
Set extended advertising data.
Parameters
advHandle Advertising handle.
location Data location.
len Length of the data. Maximum length is 31 bytes if advertising set uses legacy advertising PDUs with extended advertising.
pData Pointer to the data.
bufLen Length of the data buffer maintained by Application. Minimum length is 31 bytes.
Returns
None.
References DM_NUM_ADV_SETS, HCI_ADV_DATA_LEN, HciGetMaxAdvDataLen(), pAppExtAdvCfg, appExtAdvCfg_t::useLegacyPdu, and WSF_ASSERT.
AppExtAdvStart()
void AppExtAdvStart (uint8_t numSets, uint8_t * pAdvHandles, uint8_t mode)
Start extended advertising using the parameters for the given mode.
Parameters
numSets Number of advertising sets.
pAdvHandles Advertising handles array.
mode Discoverable/connectable mode.
Returns
None.
Start extended advertising using the parameters for the given mode.
Parameters
numSets Number of advertising sets.
pAdvHandles Advertising handles array.
mode Discoverable/connectable mode.
Returns
None.
References appExtAdvCfg_t::advDuration, appExtAdvCfg_t::advInterval, appSlaveCb_t::advState, appSlaveCb_t::advType, APP_ADV_STATE1, APP_MODE_NONE, appSlaveCb_t::discMode, DM_NUM_ADV_SETS, DmExtMaxAdvDataLen(), appSlaveCb_t::maxAdvDataLen, appExtAdvCfg_t::maxEaEvents, pAppExtAdvCfg, appExtAdvCfg_t::useLegacyPdu, and WSF_ASSERT.
AppExtAdvStop()
void AppExtAdvStop (uint8_t numSets, uint8_t * pAdvHandles)
Stop extended advertising. If the number of sets is set to 0 then all advertising sets are disabled.
Parameters
numSets Number of advertising sets.
pAdvHandles Advertising handle.
Returns
None.
Parameters
numSets Number of advertising sets.
advHandle Advertising handle array.
Returns
None.
References DM_NUM_ADV_SETS, and WSF_ASSERT.
AppExtConnAccept()
dmConnId_t AppExtConnAccept (uint8_t advHandle, uint8_t advType, uint8_t addrType, uint8_t * pAddr, appDbHdl_t dbHdl)
Accept a connection to a peer device with the given address using a given advertising set.
Parameters
advHandle Advertising handle.
advType Advertising type.
addrType Address type.
pAddr Peer device address.
dbHdl Device database handle.
Returns
Connection identifier.
References appExtAdvCfg_t::advDuration, appExtAdvCfg_t::advInterval, DM_NUM_ADV_SETS, DmExtMaxAdvDataLen(), appSlaveCb_t::maxAdvDataLen, appExtAdvCfg_t::maxEaEvents, pAppExtAdvCfg, appExtAdvCfg_t::useLegacyPdu, and WSF_ASSERT.
AppExtConnOpen()
dmConnId_t AppExtConnOpen (uint8_t initPhys, uint8_t addrType, uint8_t * pAddr, appDbHdl_t dbHdl)
Open a connection to a peer device with the given address.
Parameters
initPhys Initiator PHYs.
addrType Address type.
pAddr Peer device address.
dbHdl Device database handle.
Returns
Connection identifier.
References DM_CONN_ID_NONE.
AppExtScanStart()
void AppExtScanStart (uint8_t scanPhys, uint8_t mode, const uint8_t * pScanType, uint16_t duration, uint16_t period)
Start scanning. A scan is performed using the given scanner PHYs, discoverability mode, scan type, duration, and period.
Parameters
scanPhys Scanner PHYs.
mode Discoverability mode.
pScanType Scan type array.
duration The scan duration, in milliseconds. If set to zero or both duration and period set to non-zero, scanning will continue until DmExtScanStop() is called.
period The scan period, in 1.28 sec units. Set to zero to disable periodic scanning.
Returns
None.
References DM_NUM_PHYS, DmScanSetInterval(), DmScanStart(), pAppExtMasterCfg, appExtMasterCfg_t::scanInterval, and appExtMasterCfg_t::scanWindow.
AppExtScanStop()
void AppExtScanStop (void)
Stop scanning.
Returns
None.
References appMasterCb_t::inProgress.
AppExtSetAdvPeerAddr()
void AppExtSetAdvPeerAddr (uint8_t advHandle, uint8_t peerAddrType, uint8_t * pPeerAddr)
Set advertising peer address and its type for the given advertising set.
Parameters
advHandle Advertising handle.
peerAddrType Peer address type.
pPeerAddr Peer address.
Returns
None.
References BdaCpy(), DM_NUM_ADV_SETS, appSlaveCb_t::peerAddr, appSlaveCb_t::peerAddrType, and WSF_ASSERT.
AppExtSetAdvType()
void AppExtSetAdvType (uint8_t advHandle, uint8_t advType)
Set extended advertising type.
Parameters
advHandle Advertising handle.
advType Advertising type.
Returns
None.
References appExtAdvCfg_t::advDuration, appExtAdvCfg_t::advInterval, DM_NUM_ADV_SETS, DmExtMaxAdvDataLen(), appSlaveCb_t::maxAdvDataLen, appExtAdvCfg_t::maxEaEvents, pAppExtAdvCfg, appExtAdvCfg_t::useLegacyPdu, and WSF_ASSERT.
AppHandleNumericComparison()
void AppHandleNumericComparison (dmSecCnfIndEvt_t * pCnfInd)
Handle a numeric comparison indication during pairing. The confirmation value is displayed and the user is prompted to verify that the local and peer confirmation values match.
Parameters
pCnfInd DM confirmation indication event structure.
Returns
None.
References AppUiDisplayConfirmValue(), dmSecCnfIndEvt_t::confirm, DmSecCompareRsp(), DmSecGetCompareValue(), dmSecCnfIndEvt_t::hdr, and wsfMsgHdr_t::param.
AppHandlePasskey()
void AppHandlePasskey (dmSecAuthReqIndEvt_t * pAuthReq)
Handle a passkey request during pairing. If the passkey is to be displayed, a random passkey is generated and displayed. If the passkey is to be entered the user is prompted to enter the passkey.
Parameters
pAuthReq DM authentication requested event structure.
Returns
None.
Handle a passkey request during pairing. If the passkey is to be displayed, a random passkey is generated and displayed. If the passkey is to be entered the user is prompted to enter the passkey.
Parameters
pAuthReq DM authentication requested event structure.
Returns
None.
References APP_UI_PASSKEY_PROMPT, AppUiAction(), AppUiDisplayPasskey(), dmSecAuthReqIndEvt_t::display, DmSecAuthRsp(), dmSecAuthReqIndEvt_t::hdr, wsfMsgHdr_t::param, SecRand(), SMP_PIN_LEN, UINT32_TO_BYTE0, UINT32_TO_BYTE1, and UINT32_TO_BYTE2.
AppMasterInit()
void AppMasterInit (void)
Initialize the App Framework for operation as a Bluetooth LE master.
Returns
None.
Initialize the App Framework for operation as a Bluetooth LE master.
Returns
None.
References appMasterCb_t::inProgress.
AppMasterProcDmMsg()
void AppMasterProcDmMsg (dmEvt_t * pMsg)
Process connection-related DM messages for a master. This function should be called from the application's event handler.
Parameters
pMsg Pointer to DM callback event message.
Returns
None.
References DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, DM_PRIV_RESOLVED_ADDR_IND, DM_REM_CONN_PARAM_REQ_IND, DM_RESET_CMPL_IND, DM_SCAN_REPORT_IND, DM_SCAN_START_IND, DM_SCAN_STOP_IND, wsfMsgHdr_t::event, dmEvt_t::hdr, wsfMsgHdr_t::param, and appMasterCb_t::scanMode.
AppMasterResolveAddr()
void AppMasterResolveAddr (dmEvt_t * pMsg, appDbHdl_t dbHdl, uint8_t resolveType)
Resolve the advertiser's RPA (AdvA) or the initiator's RPA (InitA) of a directed advertisement report. If the addresses resolved then a connection will be initiated.
Parameters
pMsg Pointer to DM callback event message.
dbHdl Database record handle.
resolveType Which address in advertising report to be resolved.
Returns
None.
References APP_RESOLVE_DIRECT_RPA, appMasterCb_t::dbHdl, hciLeAdvReportEvt_t::directAddr, DmPrivResolveAddr(), DmSecGetLocalIrk(), appMasterCb_t::idx, appMasterCb_t::inProgress, and dmEvt_t::scanReport.
AppMasterSecProcDmMsg()
void AppMasterSecProcDmMsg (dmEvt_t * pMsg)
Process security-related DM messages for a master. This function should be called from the application's event handler.
Parameters
pMsg Pointer to DM callback event message.
Returns
None.
References DM_CONN_CLOSE_IND, DM_CONN_ID_NONE, DM_CONN_OPEN_IND, DM_PRIV_ADD_DEV_TO_RES_LIST_IND, DM_PRIV_REM_DEV_FROM_RES_LIST_IND, DM_PRIV_SET_ADDR_RES_ENABLE_IND, DM_SEC_ENCRYPT_FAIL_IND, DM_SEC_ENCRYPT_IND, DM_SEC_KEY_IND, DM_SEC_PAIR_CMPL_IND, DM_SEC_PAIR_FAIL_IND, DM_SEC_SLAVE_REQ_IND, wsfMsgHdr_t::event, dmEvt_t::hdr, and wsfMsgHdr_t::param.
AppMasterSecurityReq()
void AppMasterSecurityReq (dmConnId_t connId)
Initiate security as a master device. If there is a stored encryption key for the peer device this function will initiate encryption, otherwise it will initiate pairing.
Parameters
connId Connection identifier.
Returns
None.
References DM_CONN_MAX, DM_SEC_LEVEL_NONE, DmConnSecLevel(), appSecCfg_t::initiateSec, appConnCb_t::initiatingSec, pAppSecCfg, and WSF_ASSERT.
AppPerAdvSetAdValue()
bool_t AppPerAdvSetAdValue (uint8_t advHandle, uint8_t adType, uint8_t len, uint8_t * pValue)
Set the value of an advertising data element in the periodic advertising data. If the element already exists in the data then it is replaced with the new value. If the element does not exist in the data it is appended to it, space permitting.
There is special handling for the device name (AD type DM_ADV_TYPE_LOCAL_NAME). If the name can only fit in the data if it is shortened, the name is shortened and the AD type is changed to DM_ADV_TYPE_SHORT_NAME.
Parameters
advHandle Advertising handle.
adType Advertising data element type.
len Length of the value. Maximum length is 31 bytes if advertising set uses legacy advertising PDUs with extended advertising.
pValue Pointer to the value.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
AppPerAdvSetData()
void AppPerAdvSetData (uint8_t advHandle, uint16_t len, uint8_t * pData, uint16_t bufLen)
Set periodic advertising data.
Parameters
advHandle Advertising handle.
len Length of the data.
pData Pointer to the data.
bufLen Length of the data buffer maintained by Application. Minimum length is 31 bytes.
Returns
None.
References DM_NUM_ADV_SETS, and WSF_ASSERT.
AppPerAdvStart()
void AppPerAdvStart (uint8_t advHandle)
Start periodic advertising for the given advertising handle.
Parameters
advHandle Advertising handle.
Returns
None.
References APP_ADV_STATE1, DM_NUM_ADV_SETS, and WSF_ASSERT.
AppPerAdvStop()
void AppPerAdvStop (uint8_t advHandle)
Stop periodic advertising for the given advertising handle.
Parameters
advHandle Advertising handle.
Returns
None.
References APP_ADV_STOPPED, DM_NUM_ADV_SETS, DmPerAdvStop(), and WSF_ASSERT.
AppScanGetNumResults()
uint8_t AppScanGetNumResults (void)
Get the number of stored scan results.
Returns
Number of stored scan results.
References APP_DB_HDL_NONE, AppDbFindByAddr(), AppDbRecordInUse(), appConnCb_t::connId, DM_CLIENT_ID_APP, DM_CONN_ID_NONE, DmConnOpen(), and appMasterCb_t::numScanResults.
AppScanGetResult()
appDevInfo_t* AppScanGetResult (uint8_t idx)
Get a stored scan result from the scan result list. The first result is at index zero.
Parameters
idx Index of result in scan result list.
Returns
Pointer to scan result device info or NULL if index contains no result.
Get a stored scan result from the scan result list. The first result is at index zero.
Parameters
idx Index of result in scan result list.
Returns
Pointer to scan result device info or NULL if index contains no result.
References appDevInfo_t::addrType.
AppScanStart()
void AppScanStart (uint8_t mode, uint8_t scanType, uint16_t duration)
Start scanning. A scan is performed using the given discoverability mode, scan type, and duration.
Parameters
mode Discoverability mode.
scanType Scan type.
duration The scan duration, in milliseconds. If set to zero, scanning will continue until AppScanStop() is called.
Returns
None.
References DmScanSetInterval(), DmScanStart(), HCI_SCAN_PHY_LE_CODED_BIT, pAppMasterCfg, appMasterCfg_t::scanInterval, and appMasterCfg_t::scanWindow.
AppScanStop()
void AppScanStop (void)
Stop scanning.
Returns
None.
References appMasterCb_t::inProgress.
AppServerConnCback()
void AppServerConnCback (dmEvt_t * pDmEvt)
ATT connection callback for app framework. This function is used when the application is operating as an ATT server and it uses notifications or indications. This function can be called by the application's ATT connection callback or it can be installed as the ATT connection callback.
Parameters
pDmEvt DM callback event.
Returns
None.
ATT connection callback for app framework. This function is used when the application is operating as an ATT server and it uses notifications or indications. This function can be called by the application's ATT connection callback or it can be installed as the ATT connection callback.
Parameters
pDmEvt DM callback event.
Returns
None.
References APP_DB_HDL_NONE, AppDbGetCccTbl(), AppDbGetCsfRecord(), AppDbGetHdl(), ATT_HANDLE_MAX, ATT_HANDLE_START, ATTS_CLIENT_CHANGE_UNAWARE, AttsCccInitTable(), AttsCsfConnOpen(), DM_CONN_OPEN_IND, wsfMsgHdr_t::event, GattSendServiceChangedInd(), dmEvt_t::hdr, and wsfMsgHdr_t::param.
AppServerInit()
void AppServerInit (void)
Application Server initialization routine.
Returns
None.
References AttsCsfRegister().
AppServerProcAttMsg()
void AppServerProcAttMsg (wsfMsgHdr_t * pMsg)
Process ATT messages.
Parameters
pMsg message containing event.
Returns
None.
References ATTS_DB_HASH_CALC_CMPL_IND, ATTS_HANDLE_VALUE_CNF, and wsfMsgHdr_t::event.
AppSetAdvPeerAddr()
void AppSetAdvPeerAddr (uint8_t peerAddrType, uint8_t * pPeerAddr)
Set advertising peer address and its type.
Parameters
peerAddrType Peer address type.
pPeerAddr Peer address.
Returns
None.
References BdaCpy(), DM_ADV_HANDLE_DEFAULT, appSlaveCb_t::peerAddr, and appSlaveCb_t::peerAddrType.
AppSetAdvType()
void AppSetAdvType (uint8_t advType)
Set advertising type.
Parameters
advType Advertising type.
Returns
None.
References appAdvCfg_t::advDuration, appAdvCfg_t::advInterval, appSlaveCb_t::advState, DM_ADV_HANDLE_DEFAULT, and pAppAdvCfg.
AppSetBondable()
void AppSetBondable (bool_t bondable)
Set the bondable mode of the device.
Parameters
bondable TRUE to set device to bondable, FALSE to set to non-bondable.
Returns
None.
Set the bondable mode of the device.
Parameters
bondable TRUE to set device to bondable, FALSE to set to non-bondable.
Returns
None.
AppSlaveClearAllBondingInfo()
void AppSlaveClearAllBondingInfo (void)
Clear all bonding information on a slave device and make it bondable.
Returns
None.
This API should not be used when Advertising (other than periodic advertising) is enabled. Otherwise, clearing the resolving list in the Controller may fail.
References AppClearAllBondingInfo(), and AppSetBondable().
AppSlaveInit()
void AppSlaveInit (void)
Initialize the App Framework for operation as a Bluetooth LE slave.
Returns
None.
Initialize the App Framework for operation as a Bluetooth LE slave.
Returns
None.
References appSlaveCb_t::advState, appSlaveCb_t::advType, appSlaveCb_t::advTypeChanged, APP_ADV_STOPPED, DM_ADV_CONN_UNDIRECT, and DM_NUM_ADV_SETS.
AppSlaveIsAdvertising()
bool_t AppSlaveIsAdvertising (void)
Check if the local device's currently advertising.
Returns
TRUE if device's advertising. FALSE, otherwise.
AppSlaveProcDmMsg()
void AppSlaveProcDmMsg (dmEvt_t * pMsg)
Process connection-related DM messages for a slave. This function should be called from the application's event handler.
Parameters
pMsg Pointer to DM callback event message.
Returns
None.
References appSlaveCb_t::advDataBufLen, appSlaveCb_t::advDataLen, appSlaveCb_t::advDataOffset, appSlaveCb_t::advDataSynced, appSlaveCb_t::advState, appSlaveCb_t::advStopCback, APP_ADV_STOPPED, appSlaveCb_t::discMode, DM_ADV_SET_STOP_IND, DM_ADV_STOP_IND, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, DM_CONN_UPDATE_IND, DM_PRIV_RESOLVED_ADDR_IND, DM_REM_CONN_PARAM_REQ_IND, DM_REMOTE_FEATURES_IND, DM_RESET_CMPL_IND, wsfMsgHdr_t::event, HCI_EXT_ADV_DATA_LEN, dmEvt_t::hdr, appSlaveCb_t::maxAdvDataLen, wsfMsgHdr_t::param, and appConnCb_t::updateState.
AppSlaveSecProcDmMsg()
void AppSlaveSecProcDmMsg (dmEvt_t * pMsg)
Process security-related DM messages for a slave. This function should be called from the application's event handler.
Parameters
pMsg Pointer to DM callback event message.
Returns
None.
References DM_CONN_CLOSE_IND, DM_CONN_ID_NONE, DM_CONN_OPEN_IND, DM_PRIV_ADD_DEV_TO_RES_LIST_IND, DM_PRIV_REM_DEV_FROM_RES_LIST_IND, DM_PRIV_SET_ADDR_RES_ENABLE_IND, DM_SEC_ENCRYPT_FAIL_IND, DM_SEC_ENCRYPT_IND, DM_SEC_KEY_IND, DM_SEC_LTK_REQ_IND, DM_SEC_PAIR_CMPL_IND, DM_SEC_PAIR_FAIL_IND, DM_SEC_PAIR_IND, wsfMsgHdr_t::event, dmEvt_t::hdr, and wsfMsgHdr_t::param.
AppSlaveSecurityReq()
void AppSlaveSecurityReq (dmConnId_t connId)
Initiate a request for security as a slave device. This function will send a message to the master peer device requesting security. The master device should either initiate encryption or pairing.
Parameters
connId Connection identifier.
Returns
None.
References appSecCfg_t::auth, DM_SEC_LEVEL_NONE, DmConnSecLevel(), DmSecSlaveReq(), and pAppSecCfg.
AppSyncStart()
dmSyncId_t AppSyncStart (uint8_t advSid, uint8_t advAddrType, const uint8_t * pAdvAddr, uint16_t skip, uint16_t syncTimeout)
Synchronize with periodic advertising from the given advertiser, and start receiving periodic advertising packets.
Parameters
advSid Advertising SID.
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
skip Number of periodic advertising packets that can be skipped after successful receive.
syncTimeout Synchronization timeout.
Returns
Sync identifier.
References DM_SYNC_ID_NONE, and DmSyncStart().
AppSyncStop()
void AppSyncStop (dmSyncId_t syncId)
Stop reception of the periodic advertising identified by the given sync identifier.
Parameters
syncId Sync identifier.
Returns
None.
References DmSyncStop().
AppUpdatePrivacyMode()
void AppUpdatePrivacyMode (appDbHdl_t hdl)
Update privacy mode for a given peer device.
Parameters
hdl Database record handle.
Returns
None.
References dmSecIrk_t::addrType, APP_DB_HDL_NONE, AppDbGetKey(), AppDbGetPeerAddedToRl(), AppDbGetPeerRpao(), AppDbSetPeerAddedToRl(), dmSecIrk_t::bdAddr, DM_KEY_IRK, DM_PRIV_MODE_DEVICE, DmPrivSetPrivacyMode(), and dmSecKey_t::irk.
Variable Documentation
pAppAdvCfg
appAdvCfg_t* pAppAdvCfg
This is a pointer to the advertising configurable parameters used by the application. If advertising is used, the application must set this variable during system initialization.
Configuration pointer for advertising
pAppCfg
appCfg_t* pAppCfg
This is a pointer to the application parameters used by the application. The application must set this variable during system initialization.
Configuration pointer for application
pAppDiscCfg
appDiscCfg_t* pAppDiscCfg
This is a pointer to the discovery parameters used by the application. The application must set this variable during system initialization.
Configuration pointer for discovery
pAppExtAdvCfg
appExtAdvCfg_t* pAppExtAdvCfg
This is a pointer to the extended advertising configurable parameters used by the application. If extended advertising is used, the application must set this variable during system initialization.
Configuration pointer for extended and periodic advertising
pAppExtMasterCfg
appExtMasterCfg_t* pAppExtMasterCfg
This is a pointer to the extended master configurable parameters used by the application. If master mode is used, the application must set this variable during system initialization.
Configuration pointer for extended master
pAppMasterCfg
appMasterCfg_t* pAppMasterCfg
This is a pointer to the master configurable parameters used by the application. If master mode is used, the application must set this variable during system initialization.
Configuration pointer for master
pAppMasterReqActCfg
appReqActCfg_t* pAppMasterReqActCfg
This is a pointer to the master incoming request actions used by the application. The application must set this variable during system initialization.
Configuration pointer for incoming request actions on master
pAppSecCfg
appSecCfg_t* pAppSecCfg
This is a pointer to the security-related configurable parameters used by the application. The application must set this variable during system initialization.
Configuration pointer for security
pAppSlaveCfg
appSlaveCfg_t* pAppSlaveCfg
This is a pointer to the slave configurable parameters used by the application. If slave mode is used, the application must set this variable during system initialization.
Configuration pointer for slave
pAppSlaveReqActCfg
appReqActCfg_t* pAppSlaveReqActCfg
This is a pointer to the master incoming request actions used by the application. The application must set this variable during system initialization.
Configurable pointer for incoming request actions on slave
pAppUpdateCfg
appUpdateCfg_t* pAppUpdateCfg
This is a pointer to the connection parameter update parameters used by the application. The application must set this variable during system initialization.
Configuration pointer for connection parameter update