Cordio: TEMPERATURE_SERVICE_PROFILE
TEMPERATURE_SERVICE_PROFILE
Functions
void TempStart (wsfHandlerId_t handlerId, uint8_t timerEvt)
void TempStop (void)
void TempMeasStop (void)
void TempMeasStart (void)
void TempMeasComplete (dmConnId_t connId, int16_t temp)
Detailed Description
Function Documentation
TempMeasComplete()
void TempMeasComplete (dmConnId_t connId, int16_t temp)
Measurement complete handler.
Parameters
connId Connection ID.
temp Temperature reading.
Returns
None.
TempMeasStart()
void TempMeasStart (void)
Measurement start handler.
Returns
None.
TempMeasStop()
void TempMeasStop (void)
Measurement stop handler.
Returns
None.
TempStart()
void TempStart (wsfHandlerId_t handlerId, uint8_t timerEvt)
Start service.
Parameters
handlerId Handler ID.
timerEvt Timer message event.
Returns
None.
References SvcTempAddGroup(), and SvcTempCbackRegister().
TempStop()
void TempStop (void)
Stop service.
Returns
None.
References SvcTempRemoveGroup(), and TempMeasStop().