Cordio: LL_API_CENTRAL
LL_API_CENTRAL
Functions
uint8_t LlCreateConn (const LlInitParam_t *pInitParam, const LlConnSpec_t *pConnSpec)
uint8_t LlExtCreateConn (const LlExtInitParam_t *pInitParam, const LlExtInitScanParam_t scanParam[], const LlConnSpec_t connSpec[])
void LlCreateConnCancel (void)
Detailed Description
Function Documentation
LlCreateConn()
uint8_t LlCreateConn (const LlInitParam_t * pInitParam, const LlConnSpec_t * pConnSpec)
Create connection.
Parameters
pInitParam Initiating parameters.
pConnSpec Connection specification.
Returns
Status error code.
Create a connection to the specified peer address with the specified connection parameters. This function is only when operating in master role.
References BstreamToBda64(), LlConnSpec_t::connIntervalMax, LlConnSpec_t::connIntervalMin, LlConnSpec_t::connLatency, lctrInitiateMsg_t::connSpec, lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrCtrlBlk_t::features, LlInitParam_t::filterPolicy, lmgrPersistCtrlBlk_t::handlerId, lctrInitiateMsg_t::hdr, LCTR_DISP_INIT, LCTR_INIT_MSG_INITIATE, LctrValidateConnSpec(), LL_ADDR_RANDOM, LL_ADDR_RANDOM_IDENTITY, LL_FEAT_PRIVACY, LL_SCAN_FILTER_NONE, LL_SCAN_FILTER_WL_BIT, lmgrCb, LmgrIsAddressTypeAvailable(), LmgrIsLegacyCommandAllowed(), lmgrPersistCb, lmgrScanParam_t::ownAddrType, LlInitParam_t::ownAddrType, lctrInitiateMsg_t::peerAddr, lctrInitiateMsg_t::peerAddrType, LlInitParam_t::peerAddrType, LlInitParam_t::pPeerAddr, lmgrScanParam_t::scanFiltPolicy, lmgrScanParam_t::scanInterval, LlInitParam_t::scanInterval, lctrInitiateMsg_t::scanParam, lmgrScanParam_t::scanWindow, LlInitParam_t::scanWindow, LlConnSpec_t::supTimeout, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
LlCreateConnCancel()
void LlCreateConnCancel (void)
Cancel a create connection operation.
Cancel a connection before it is established. This function is only used when operating in master role.
Cancel a connection before it is established. This function is only used when operating in master role. This command is used to cancel extended and legacy create connection.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrPersistCtrlBlk_t::handlerId, LCTR_DISP_EXT_INIT, LCTR_DISP_INIT, LCTR_INIT_MSG_INITIATE_CANCEL, lmgrCb, lmgrPersistCb, lmgrCtrlBlk_t::useExtCmds, WsfMsgAlloc(), and WsfMsgSend().
LlExtCreateConn()
uint8_t LlExtCreateConn (const LlExtInitParam_t * pInitParam, const LlExtInitScanParam_t scanParam[], const LlConnSpec_t connSpec[])
Extended create connection.
Parameters
pInitParam Initiating parameters.
scanParam Scan parameters table indexed by PHY.
connSpec Connection specification table indexed by PHY.
Returns
Status error code.
Create a connection to the specified peer address with the specified connection parameters. This function is only when operating in master role.
References BstreamToBda64(), lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrCtrlBlk_t::features, lctrExtInitiateMsg_t::filterPolicy, LlExtInitParam_t::filterPolicy, lmgrPersistCtrlBlk_t::handlerId, lctrExtInitiateMsg_t::hdr, lctrExtInitiateMsg_t::initPhys, LlExtInitParam_t::initPhys, LCTR_DISP_EXT_INIT, LCTR_EXT_INIT_MSG_INITIATE, LctrMstExtInitClearScanPhy(), LctrMstExtInitParam(), LctrMstExtInitSetScanPhy(), LL_FEAT_LE_2M_PHY, LL_FEAT_LE_CODED_PHY, LL_PHYS_LE_1M_BIT, LL_PHYS_LE_2M_BIT, LL_PHYS_LE_CODED_BIT, lmgrCb, LmgrIsExtCommandAllowed(), lmgrPersistCb, lmgrCtrlBlk_t::numExtScanPhys, lmgrCtrlBlk_t::numInitEnabled, lctrExtInitiateMsg_t::ownAddrType, LlExtInitParam_t::ownAddrType, lctrExtInitiateMsg_t::peerAddr, lctrExtInitiateMsg_t::peerAddrType, LlExtInitParam_t::peerAddrType, LlExtInitParam_t::pPeerAddr, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().