Cordio: WSF_MSG_API
WSF_MSG_API
Functions
void * WsfMsgDataAlloc (uint16_t len, uint8_t tailroom)
void * WsfMsgAlloc (uint16_t len)
void WsfMsgFree (void *pMsg)
void WsfMsgSend (wsfHandlerId_t handlerId, void *pMsg)
void WsfMsgEnq (wsfQueue_t *pQueue, wsfHandlerId_t handlerId, void *pMsg)
void * WsfMsgDeq (wsfQueue_t *pQueue, wsfHandlerId_t *pHandlerId)
void * WsfMsgPeek (wsfQueue_t *pQueue, wsfHandlerId_t *pHandlerId)
void * WsfMsgNPeek (wsfQueue_t *pQueue, uint8_t n, wsfHandlerId_t *pHandlerId)
Detailed Description
Function Documentation
WsfMsgAlloc()
void* WsfMsgAlloc (uint16_t len)
Allocate a message buffer to be sent with WsfMsgSend().
Parameters
len Message length in bytes.
Returns
Pointer to message buffer or NULL if allocation failed.
References WsfBufAlloc().
WsfMsgDataAlloc()
void* WsfMsgDataAlloc (uint16_t len, uint8_t tailroom)
Allocate a data message buffer to be sent with WsfMsgSend().
Parameters
len Message length in bytes.
tailroom Tailroom length in bytes.
Returns
Pointer to data message buffer or NULL if allocation failed.
References WsfMsgAlloc().
WsfMsgDeq()
void* WsfMsgDeq (wsfQueue_t * pQueue, wsfHandlerId_t * pHandlerId)
Dequeue a message.
Parameters
pQueue Pointer to queue.
pHandlerId Handler ID of returned message; this is a return parameter.
Returns
Pointer to message that has been dequeued or NULL if queue is empty.
References WsfQueueDeq().
WsfMsgEnq()
void WsfMsgEnq (wsfQueue_t * pQueue, wsfHandlerId_t handlerId, void * pMsg)
Enqueue a message.
Parameters
pQueue Pointer to queue.
handlerId Set message handler ID to this value.
pMsg Pointer to message buffer.
pQueue Pointer to queue.
handerId Set message handler ID to this value.
pElem Pointer to message buffer.
References WSF_ASSERT, and WsfQueueEnq().
WsfMsgFree()
void WsfMsgFree (void * pMsg)
Free a message buffer allocated with WsfMsgAlloc().
Parameters
pMsg Pointer to message buffer.
References WsfBufFree().
WsfMsgNPeek()
void* WsfMsgNPeek (wsfQueue_t * pQueue, uint8_t n, wsfHandlerId_t * pHandlerId)
Get the Nth message without removing it from the queue.
Parameters
pQueue Pointer to queue.
n Nth item from the top (0 = top element).
pHandlerId Handler ID of returned message; this is a return parameter.
Returns
Pointer to the next message on the queue or NULL if queue is empty.
References wsfQueue_t::pHead.
WsfMsgPeek()
void* WsfMsgPeek (wsfQueue_t * pQueue, wsfHandlerId_t * pHandlerId)
Get the next message without removing it from the queue.
Parameters
pQueue Pointer to queue.
pHandlerId Handler ID of returned message; this is a return parameter.
Returns
Pointer to the next message on the queue or NULL if queue is empty.
References wsfQueue_t::pHead.
WsfMsgSend()
void WsfMsgSend (wsfHandlerId_t handlerId, void * pMsg)
Send a message to an event handler.
Parameters
handlerId Event handler ID.
pMsg Pointer to message buffer.
References WSF_MSG_QUEUE_EVENT, WsfMsgEnq(), WsfTaskMsgQueue(), and WsfTaskSetReady().