Cordio: LL_API_CONN
LL_API_CONN
Data Structures
struct LlInitParam_t
struct LlExtInitParam_t
struct LlExtInitScanParam_t
struct LlConnSpec_t
Macros
#define LL_PC_PATH_LOSS_UNUSED_HIGH_THRESHOLD 0xFF
Enumerations
enum
enum
enum
enum
enum LlPhy_t
enum
enum
enum
enum
enum
Functions
uint8_t LlDisconnect (uint16_t handle, uint8_t reason)
uint8_t LlSetConnOpFlags (uint16_t handle, uint32_t flags, bool_t enable)
uint8_t LlReadRemoteFeat (uint16_t handle)
uint8_t LlReadRemoteVerInfo (uint16_t handle)
uint8_t LlGetRssi (uint16_t handle, int8_t *pRssi)
uint8_t LlGetTxPowerLevel (uint16_t handle, uint8_t type, int8_t *pLevel)
uint8_t LlGetEnhTxPowerLevel (uint16_t handle, uint8_t phy, int8_t *pCurPwr, int8_t *pMaxPwr)
uint8_t LlSetAllPhyTxPowerLevel (uint16_t handle, int8_t level)
uint8_t LlSetPhyTxPowerLevel (uint16_t handle, int8_t level, uint8_t phy)
uint8_t LlConnUpdate (uint16_t handle, const LlConnSpec_t *pConnSpec)
uint8_t LlRemoteConnParamReqReply (uint16_t handle, const LlConnSpec_t *pConnSpec)
uint8_t LlRemoteConnParamReqNegReply (uint16_t handle, uint8_t reason)
uint8_t LlSetChannelMap (uint16_t handle, const uint8_t *pChanMap)
uint8_t LlGetChannelMap (uint16_t handle, uint8_t *pChanMap)
uint8_t LlSetDataLen (uint16_t handle, uint16_t txLen, uint16_t txTime)
void LlReadDefaultDataLen (uint16_t *pMaxTxLen, uint16_t *pMaxTxTime)
uint8_t LlWriteDefaultDataLen (uint16_t maxTxLen, uint16_t maxTxTime)
void LlReadMaximumDataLen (uint16_t *pMaxTxLen, uint16_t *pMaxTxTime, uint16_t *pMaxRxLen, uint16_t *pMaxRxTime)
uint8_t LlReadPhy (uint16_t handle, uint8_t *pTxPhy, uint8_t *pRxPhy)
uint8_t LlSetDefaultPhy (uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys)
bool_t llValidatePhySupport (uint8_t txPhys, uint8_t rxPhys)
uint8_t LlSetPhy (uint16_t handle, uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys, uint16_t phyOptions)
uint8_t LlSetLocalMinUsedChan (uint8_t phys, int8_t pwrThres, uint8_t minUsedCh)
uint8_t LlGetPeerMinUsedChan (uint16_t handle, uint8_t *pPeerMinUsedChan)
uint8_t LlRequestPeerSca (uint16_t handle)
Detailed Description
Data Structure Documentation
LlInitParam_t
struct LlInitParam_t
Initiating parameters (LlExtCreateConn()).
Data Fields
uint16_t scanInterval
uint16_t scanWindow
uint8_t filterPolicy
uint8_t ownAddrType
uint8_t peerAddrType
const uint8_t * pPeerAddr
Field Documentation
filterPolicy
uint8_t filterPolicy
Scan filter policy.
ownAddrType
uint8_t ownAddrType
Address type used by this device.
peerAddrType
uint8_t peerAddrType
Address type used for peer device.
pPeerAddr
const uint8_t* pPeerAddr
Address of peer device.
scanInterval
uint16_t scanInterval
Scan interval.
scanWindow
uint16_t scanWindow
Scan window.
LlExtInitParam_t
struct LlExtInitParam_t
Initiating parameters (LlExtCreateConn()).
Data Fields
uint8_t filterPolicy
uint8_t ownAddrType
uint8_t peerAddrType
const uint8_t * pPeerAddr
uint8_t initPhys
Field Documentation
filterPolicy
uint8_t filterPolicy
Scan filter policy.
initPhys
uint8_t initPhys
Initiating PHYs.
ownAddrType
uint8_t ownAddrType
Address type used by this device.
peerAddrType
uint8_t peerAddrType
Address type used for peer device.
pPeerAddr
const uint8_t* pPeerAddr
Address of peer device.
LlExtInitScanParam_t
struct LlExtInitScanParam_t
Initiating scan parameters (LlExtCreateConn()).
Data Fields
uint16_t scanInterval
uint16_t scanWindow
Field Documentation
scanInterval
uint16_t scanInterval
Scan interval.
scanWindow
uint16_t scanWindow
Scan window.
LlConnSpec_t
struct LlConnSpec_t
Connection specification (LlCreateConn(), LlConnUpdate() and LlExtCreateConn()).
Data Fields
uint16_t connIntervalMin
uint16_t connIntervalMax
uint16_t connLatency
uint16_t supTimeout
uint16_t minCeLen
uint16_t maxCeLen
Field Documentation
connIntervalMax
uint16_t connIntervalMax
Maximum connection interval.
connIntervalMin
uint16_t connIntervalMin
Minimum connection interval.
connLatency
uint16_t connLatency
Connection latency.
maxCeLen
uint16_t maxCeLen
Maximum CE length.
minCeLen
uint16_t minCeLen
Minimum CE length.
supTimeout
uint16_t supTimeout
Supervision timeout.
Enumeration Type Documentation
anonymous enum
anonymous enum
Master clock accuracy.
Enumerator
LL_MCA_500_PPM
500 ppm
LL_MCA_250_PPM
250 ppm
LL_MCA_150_PPM
150 ppm
LL_MCA_100_PPM
100 ppm
LL_MCA_75_PPM
75 ppm
LL_MCA_50_PPM
50 ppm
LL_MCA_30_PPM
30 ppm
LL_MCA_20_PPM
20 ppm
anonymous enum
anonymous enum
PHYS specification.
Enumerator
LL_PHYS_NONE
No selected PHY.
LL_PHYS_LE_1M_BIT
LE 1M PHY.
LL_PHYS_LE_2M_BIT
LE 2M PHY.
LL_PHYS_LE_CODED_BIT
LE Coded PHY.
anonymous enum
anonymous enum
All PHYs preference.
Enumerator
LL_ALL_PHY_ALL_PREFERENCES
All PHY preferences.
LL_ALL_PHY_TX_PREFERENCE_BIT
Set if no Tx PHY preference.
LL_ALL_PHY_RX_PREFERENCE_BIT
Set if no Rx PHY preference.
anonymous enum
anonymous enum
PHY options.
Enumerator
LL_PHY_OPTIONS_NONE
No preferences.
LL_PHY_OPTIONS_S2_PREFERRED
S=2 coding preferred when transmitting on LE Coded PHY.
LL_PHY_OPTIONS_S8_PREFERRED
S=8 coding preferred when transmitting on LE Coded PHY.
anonymous enum
anonymous enum
Power control PHY bits.
Enumerator
LL_PC_1M_BIT
LE 1M PHY bit.
LL_PC_2M_BIT
LE 2M PHY bit.
LL_PC_CODED_S8_BIT
LE Coded S8 PHY bit.
LL_PC_CODED_S2_BIT
LE Coded S2 PHY bit.
anonymous enum
anonymous enum
Privacy modes.
Enumerator
LL_PRIV_MODE_NETWORK
Network privacy mode.
LL_PRIV_MODE_DEVICE
Device privacy mode.
anonymous enum
anonymous enum
Channel selection algorithm methods.
Enumerator
LL_CH_SEL_1
Channel selection #1.
LL_CH_SEL_2
Channel selection #2.
anonymous enum
anonymous enum
Tx power level type.
Enumerator
LL_TX_PWR_LVL_TYPE_CURRENT
Current transmit power level.
LL_TX_PWR_LVL_TYPE_MAX
Maximum transmit power level.
LlPhy_t
enum LlPhy_t
PHY types.
Enumerator
LL_PHY_NONE
PHY not selected.
LL_PHY_LE_1M
LE 1M PHY.
LL_PHY_LE_2M
LE 2M PHY.
LL_PHY_LE_CODED
LE Coded PHY.
Function Documentation
LlConnUpdate()
uint8_t LlConnUpdate (uint16_t handle, const LlConnSpec_t * pConnSpec)
Update connection parameters.
Parameters
handle Connection handle.
pConnSpec New connection specification.
Returns
Status error code.
Update the connection parameters of a connection.
References LCTR_CONN_MSG_API_CONN_UPDATE, LctrIsConnHandleEnabled(), LctrIsProcActPended(), LlRtCfg_t::maxConn, pLctrRtCfg, and WSF_ASSERT.
LlDisconnect()
uint8_t LlDisconnect (uint16_t handle, uint8_t reason)
Disconnect a connection.
Parameters
handle Connection handle.
reason Disconnect reason.
Returns
Status error code.
Disconnect a connection.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, lctrDisconnect_t::hdr, LCTR_CONN_MSG_API_DISCONNECT, LCTR_DISP_CONN, LCTR_MAX_HANDLE_INDEX, LctrIsCisConnHandleEnabled(), LctrIsConnHandleEnabled(), lmgrPersistCb, lctrDisconnect_t::reason, WsfMsgAlloc(), and WsfMsgSend().
LlGetChannelMap()
uint8_t LlGetChannelMap (uint16_t handle, uint8_t * pChanMap)
Get connection's channel map.
Parameters
handle Connection handle.
pChanMap Channel map.
Returns
Status error code.
Get the current channel map of a connection.
References LctrGetChannelMap(), LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, pLctrRtCfg, UINT40_TO_BSTREAM, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
LlGetEnhTxPowerLevel()
uint8_t LlGetEnhTxPowerLevel (uint16_t handle, uint8_t phy, int8_t * pCurPwr, int8_t * pMaxPwr)
Get connection's enhanced TX power level and max txPower.
Parameters
handle Connection handle.
phy PHY.
pCurPwr Transmit power level.
pMaxPwr Max power level.
Returns
Status error code.
Parameters
handle Connection handle.
phy PHY.
pCurPwr Current transmit power level.
pMaxPwr Max power level.
Returns
Status error code.
References LctrIsConnHandleEnabled(), LL_PHY_NONE, LlRtCfg_t::maxConn, pLctrRtCfg, WSF_CS_ENTER, and WSF_CS_INIT.
LlGetPeerMinUsedChan()
uint8_t LlGetPeerMinUsedChan (uint16_t handle, uint8_t * pPeerMinUsedChan)
Get peer minimum number of used channels.
Parameters
handle Connection handle.
pPeerMinUsedChan Storage for the peer minimum number of used channels.
Returns
Status error code.
Get peer minimum number of used channels.
References lmgrCtrlBlk_t::features, LctrGetPeerMinUsedChan(), LctrGetRole(), LctrIsConnHandleEnabled(), LL_FEAT_MIN_NUM_USED_CHAN, LL_ROLE_MASTER, lmgrCb, LlRtCfg_t::maxConn, pLctrRtCfg, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
LlGetRssi()
uint8_t LlGetRssi (uint16_t handle, int8_t * pRssi)
Get RSSI of a connection.
Parameters
handle Connection handle.
pRssi RSSI value.
Returns
Status error code.
Get the current RSSI of a connection.
References LctrGetRssi(), LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, pLctrRtCfg, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
LlGetTxPowerLevel()
uint8_t LlGetTxPowerLevel (uint16_t handle, uint8_t type, int8_t * pLevel)
Get connection's TX power level.
Parameters
handle Connection handle.
type Power level type.
pLevel Transmit power level.
Returns
Status error code.
Get the TX power of a connection.
References LctrGetTxPowerLevel(), LctrIsConnHandleEnabled(), LL_TX_PWR_LVL_TYPE_CURRENT, LL_TX_PWR_LVL_TYPE_MAX, LlRtCfg_t::maxConn, pLctrRtCfg, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
LlReadDefaultDataLen()
void LlReadDefaultDataLen (uint16_t * pMaxTxLen, uint16_t * pMaxTxTime)
Read default data length.
Parameters
pMaxTxLen Maximum number of payload bytes for a Data PDU
pMaxTxTime Maximum microseconds for a Data PDU
Suggested length and microseconds that the local Controller should use to transmit a single Link Layer Data Channel PDU.
References lmgrConnCb, lmgrConnCtrlBlk_t::maxTxLen, lmgrConnCtrlBlk_t::maxTxTime, and WSF_ASSERT.
LlReadMaximumDataLen()
void LlReadMaximumDataLen (uint16_t * pMaxTxLen, uint16_t * pMaxTxTime, uint16_t * pMaxRxLen, uint16_t * pMaxRxTime)
Read maximum data length.
Parameters
pMaxTxLen Maximum number of payload bytes for a Tx Data PDU
pMaxTxTime Maximum microseconds for a Tx Data PDU
pMaxRxLen Maximum number of payload bytes for a Rx Data PDU
pMaxRxTime Maximum microseconds for a Rx Data PDU
Read the Controller's maximum supported payload octets and packet duration times for transmission and reception.
References LCTR_MAX_DATA_LEN_MAX, LlRtCfg_t::maxAclLen, pLctrRtCfg, WSF_ASSERT, and WSF_MIN.
LlReadPhy()
uint8_t LlReadPhy (uint16_t handle, uint8_t * pTxPhy, uint8_t * pRxPhy)
Read current transmitter PHY and receive PHY.
Parameters
handle Connection handle.
pTxPhy Storage for transmitter PHY.
pRxPhy Storage for receiver PHY.
Returns
Status error code.
Read current transmitter PHY and receive PHY.
References LctrGetRxPhy(), LctrGetTxPhy(), LctrIsConnHandleEnabled(), LL_ALL_PHY_RX_PREFERENCE_BIT, LL_ALL_PHY_TX_PREFERENCE_BIT, LL_PHY_OPTIONS_S8_PREFERRED, LL_PHYS_LE_1M_BIT, LL_PHYS_LE_2M_BIT, LL_PHYS_LE_CODED_BIT, LlRtCfg_t::maxConn, and pLctrRtCfg.
LlReadRemoteFeat()
uint8_t LlReadRemoteFeat (uint16_t handle)
Read remote features.
Parameters
handle Connection handle.
Returns
Status error code.
Read the link layer features of the remote device.
References LCTR_CONN_MSG_API_REMOTE_FEATURE, and LctrIsProcActPended().
LlReadRemoteVerInfo()
uint8_t LlReadRemoteVerInfo (uint16_t handle)
Read remote version information.
Parameters
handle Connection handle.
Returns
Status error code.
Read the version information of the remote device.
References LCTR_CONN_MSG_API_REMOTE_VERSION, LctrIsConnHandleEnabled(), LctrIsProcActPended(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlRemoteConnParamReqNegReply()
uint8_t LlRemoteConnParamReqNegReply (uint16_t handle, uint8_t reason)
Remote connection parameter request negative reply.
Parameters
handle Connection handle.
reason Reason code.
Returns
Status error code.
Negative reply to a connection parameter request.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, lctrConnParamNegReply_t::hdr, LCTR_CONN_MSG_API_CONN_PARAM_NEG_REPLY, LCTR_DISP_CONN, LCTR_HOST_REPLY_CONN_PARAM_REQ, LctrIsConnHandleEnabled(), LctrIsWaitingForReply(), lmgrPersistCb, LlRtCfg_t::maxConn, pLctrRtCfg, lctrConnParamNegReply_t::reason, WsfMsgAlloc(), and WsfMsgSend().
LlRemoteConnParamReqReply()
uint8_t LlRemoteConnParamReqReply (uint16_t handle, const LlConnSpec_t * pConnSpec)
Remote connection parameter request reply.
Parameters
handle Connection handle.
pConnSpec New connection specification.
Returns
Status error code.
Reply to a connection parameter request.
References lctrConnParamReply_t::connSpec, lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, lctrConnParamReply_t::hdr, LCTR_CONN_MSG_API_CONN_PARAM_REPLY, LCTR_DISP_CONN, LCTR_HOST_REPLY_CONN_PARAM_REQ, LctrIsConnHandleEnabled(), LctrIsWaitingForReply(), LctrValidateConnSpec(), lmgrPersistCb, LlRtCfg_t::maxConn, pLctrRtCfg, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
LlRequestPeerSca()
uint8_t LlRequestPeerSca (uint16_t handle)
Used to read the sleep clock accuracy of the peer device.
Parameters
handle Handle of the ACL.
Returns
Status error code.
Parameters
handle Connection handle.
Returns
Status error code.
References lctrScaReq_t::action, lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, lctrScaReq_t::hdr, LCTR_CONN_MSG_API_REQ_PEER_SCA, LCTR_DISP_CONN, LctrGetUsedFeatures(), LctrIsConnHandleEnabled(), LL_FEAT_SCA_UPDATE, lmgrPersistCb, LlRtCfg_t::maxConn, pLctrRtCfg, WsfMsgAlloc(), and WsfMsgSend().
LlSetAllPhyTxPowerLevel()
uint8_t LlSetAllPhyTxPowerLevel (uint16_t handle, int8_t level)
Set connection's TX power level (all PHYs).
Parameters
handle Connection handle.
level Transmit power level.
Returns
Status error code.
Set connection's TX power level (all PHYs).
Parameters
handle Connection handle.
level Transmit power level.
Returns
Status error code.
Set the TX power of a connection (All PHYs).
References LctrIsConnHandleEnabled(), LctrSetTxPowerLevel(), LlRtCfg_t::maxConn, pLctrRtCfg, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
LlSetChannelMap()
uint8_t LlSetChannelMap (uint16_t handle, const uint8_t * pChanMap)
Set connection's channel map.
Parameters
handle Connection handle.
pChanMap Channel map.
Returns
Status error code.
Set the channel map of a connection.
References LCTR_CONN_MSG_API_CHAN_MAP_UPDATE, and LctrIsProcActPended().
LlSetConnOpFlags()
uint8_t LlSetConnOpFlags (uint16_t handle, uint32_t flags, bool_t enable)
Set connection's operational mode flags.
Parameters
handle Connection handle.
flags Flags.
enable TRUE to set flags or FALSE to clear flags.
Returns
Status error code.
Set connection's operational mode flags governing LL operations.
Set connection's operational mode flags.
Parameters
flags Flags.
enable TRUE to set flags or FALSE to clear flags.
Returns
Status error code.
Set mode flags governing LL operations of a given connection.
LlSetDataLen()
uint8_t LlSetDataLen (uint16_t handle, uint16_t txLen, uint16_t txTime)
Set data length.
Parameters
handle Connection handle.
txLen Maximum number of payload bytes for a Data PDU
txTime Maximum microseconds for a Data PDU
Returns
Status error code.
Preferred maximum microseconds that the local Controller should use to transmit a single Link Layer Data Channel PDU.
References LCTR_CONN_MSG_API_DATA_LEN_CHANGE, LctrIsConnHandleEnabled(), LctrIsProcActPended(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlSetDefaultPhy()
uint8_t LlSetDefaultPhy (uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys)
Set default PHYs.
Parameters
allPhys All PHYs preferences.
txPhys Preferred transmitter PHYs.
rxPhys Preferred receiver PHYs.
Returns
Status error code.
Specify the preferred values for the transmitter PHY and receiver PHY to be used for all subsequent connections over the LE transport.
References lmgrConnCtrlBlk_t::allPhys, LL_ALL_PHY_RX_PREFERENCE_BIT, LL_ALL_PHY_TX_PREFERENCE_BIT, LL_PHY_OPTIONS_NONE, LL_PHYS_NONE, llValidatePhySupport(), lmgrConnCb, lmgrConnCtrlBlk_t::rxPhys, and lmgrConnCtrlBlk_t::txPhys.
LlSetLocalMinUsedChan()
uint8_t LlSetLocalMinUsedChan (uint8_t phys, int8_t pwrThres, uint8_t minUsedCh)
Set local minimum number of used channels.
Parameters
phys Bitmask for the PHYs.
pwrThres Power threshold.
minUsedCh Minimum number of used channels.
Returns
Status error code.
Set local minimum number of used channels.
References lmgrCtrlBlk_t::features, LCTR_CONN_MSG_API_SET_MIN_USED_CHAN, LctrGetRole(), LctrIsConnHandleEnabled(), LctrIsProcActPended(), LL_FEAT_MIN_NUM_USED_CHAN, LL_ROLE_SLAVE, lmgrCb, lmgrCtrlBlk_t::localMinUsedChan, LlRtCfg_t::maxConn, pLctrRtCfg, and lmgrCtrlBlk_t::powerThreshold.
LlSetPhy()
uint8_t LlSetPhy (uint16_t handle, uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys, uint16_t phyOptions)
Set PHY for a connection.
Parameters
handle Connection handle.
allPhys All PHYs preferences.
txPhys Preferred transmitter PHYs.
rxPhys Preferred receiver PHYs.
phyOptions PHY options.
Returns
Status error code.
Set PHY preferences for a given connection. The controller might not be able to make the change (e.g., because the peer does not support the requested PHY) or may decide that the current PHY is preferable.
References LCTR_CONN_MSG_API_PHY_UPDATE, LctrIsConnHandleEnabled(), LctrIsProcActPended(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlSetPhyTxPowerLevel()
uint8_t LlSetPhyTxPowerLevel (uint16_t handle, int8_t level, uint8_t phy)
Set connection's TX power level for a PHY.
Parameters
handle Connection handle.
level Transmit power level.
phy PHY txPower to change.
Returns
Status error code.
Parameters
handle Connection handle.
level Transmit power level.
Returns
Status error code.
Set the TX power of a connection for a PHY.
References LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, pLctrRtCfg, WSF_CS_ENTER, and WSF_CS_INIT.
llValidatePhySupport()
bool_t llValidatePhySupport (uint8_t txPhys, uint8_t rxPhys)
Validate if specified PHYs are supported by LL.
Parameters
txPhys Preferred transmitter PHYs.
rxPhys Preferred receiver PHYs.
Returns
TRUE if all specified PHYs are supported.
LlWriteDefaultDataLen()
uint8_t LlWriteDefaultDataLen (uint16_t maxTxLen, uint16_t maxTxTime)
Write default data length.
Parameters
maxTxLen Maximum number of payload bytes for a Data PDU
maxTxTime Maximum microseconds for a Data PDU
Returns
Status error code.
Suggested length and microseconds that the local Controller should use to transmit a single Link Layer Data Channel PDU.
References LlRtCfg_t::btVer, LCTR_MAX_DATA_LEN_MAX, lmgrConnCb, LlRtCfg_t::maxAclLen, lmgrConnCtrlBlk_t::maxTxLen, lmgrConnCtrlBlk_t::maxTxTime, pLctrRtCfg, and WSF_MIN.