Cordio: USER_DATA_PROFILE
USER_DATA_PROFILE
Typedefs
typedef void(* UdsRspCback_t) (dmConnId_t connId, uint8_t opcode, uint8_t response, uint8_t index)
Enumerations
enum
Functions
void UdscDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t UdscValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void UdscReadUserIndex (dmConnId_t connId, uint16_t handle)
void UdscReadDatabaseChangeIncrement (dmConnId_t connId, uint16_t handle)
void UdscWriteDatabaseChangeIncrement (dmConnId_t connId, uint16_t handle, uint32_t increment)
void UdscRegisterNewUser (dmConnId_t connId, uint16_t handle, uint16_t consentCode)
void UdscConsent (dmConnId_t connId, uint16_t handle, uint8_t index, uint16_t consentCode)
void UdscDeleteUserData (dmConnId_t connId, uint16_t handle)
void UdscClose (void)
void UdscInit (wsfHandlerId_t handlerId, uint8_t timerEvent, UdsRspCback_t rspCback)
User Control Point Opcodes
#define UDSC_UCP_OPCODE_RNU 0x01
#define UDSC_UCP_OPCODE_CONSENT 0x02
#define UDSC_UCP_OPCODE_DUD 0x03
#define UDSC_UCP_OPCODE_RESPONSE 0x20
User Control Point Response Values
#define UDSC_UCP_RSP_SUCCESS 0x01
#define UDSC_UCP_RSP_OP_NOT_SUPPORTED 0x02
#define UDSC_UCP_RSP_INVALID_PARAMETER 0x03
#define UDSC_UCP_RSP_OP_FAILED 0x04
#define UDSC_UCP_RSP_NOT_AUTHORIZED 0x05
Detailed Description
Typedef Documentation
UdsRspCback_t
typedef void(* UdsRspCback_t) (dmConnId_t connId, uint8_t opcode, uint8_t response, uint8_t index)
UDS Control Point Response Callback.
Parameters
connId Connection ID.
opcode Cmd opcode being responded to.
response Response code.
index User index (only set when opcode is UDSC_UCP_OPCODE_RNU)
Returns
None
Enumeration Type Documentation
anonymous enum
anonymous enum
UDSC service enumeration of handle indexes of characteristics to be discovered.
Enumerator
UDSC_DBCI_HDL_IDX
Database Change Interval.
UDSC_DCBI_CCC_HDL_IDX
Database Change Interval CCC descriptor.
UDSC_UI_HDL_IDX
User Index.
UDSC_UCP_IDX
User Control Point.
UDSC_UCP_CCC_HDL_IDX
User Control Point CCC descriptor.
UDSC_HDL_LIST_LEN
Handle list length.
Function Documentation
UdscClose()
void UdscClose (void)
Called by the application when a connection closes.
Returns
None.
References WsfTimerStop().
UdscConsent()
void UdscConsent (dmConnId_t connId, uint16_t handle, uint8_t index, uint16_t consentCode)
Write to the user control point characteristic - Consent.
Parameters
connId Connection identifier.
handle Attribute handle.
index User Index
consentCode Consent code (0-9999 - provided when user was registered)
Returns
None.
Parameters
connId Connection identifier.
handle Attribute handle.
index User index
consentCode Consent code (0-9999 - provided when user was registered)
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, UDSC_UCP_OPCODE_CONSENT, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
UdscDeleteUserData()
void UdscDeleteUserData (dmConnId_t connId, uint16_t handle)
Write to the user control point characteristic - Delete User Data.
Parameters
connId Connection identifier.
handle Attribute handle.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, UDSC_UCP_OPCODE_DUD, and UINT8_TO_BSTREAM.
UdscDiscover()
void UdscDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for User Data service. Parameter pHdlList must point to an array of length UDSC_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for User Data service. Parameter pHdlList must point to an array of length UDSC_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attUdsSvcUuid, BSTREAM_TO_INT8, UDSC_HDL_LIST_LEN, UDSC_UCP_OPCODE_RESPONSE, UDSC_UCP_OPCODE_RNU, UDSC_UCP_RSP_SUCCESS, and WsfTimerStop().
UdscInit()
void UdscInit (wsfHandlerId_t handlerId, uint8_t timerEvent, UdsRspCback_t rspCback)
Initialize User Data Service collector callbacks.
Parameters
handlerId Application task handler ID.
timerEvent Application timer event for control point timeout.
rspCback Callback to receive control point response messages.
Returns
None.
UdscReadDatabaseChangeIncrement()
void UdscReadDatabaseChangeIncrement (dmConnId_t connId, uint16_t handle)
Read the database change increment characteristic.
Parameters
connId Connection identifier.
handle Attribute handle.
Returns
None.
References ATT_HANDLE_NONE, and AttcReadReq().
UdscReadUserIndex()
void UdscReadUserIndex (dmConnId_t connId, uint16_t handle)
Read the user index characteristic.
Parameters
connId Connection identifier.
handle Attribute handle.
Returns
None.
References ATT_HANDLE_NONE, and AttcReadReq().
UdscRegisterNewUser()
void UdscRegisterNewUser (dmConnId_t connId, uint16_t handle, uint16_t consentCode)
Write to the user control point characteristic - Register New User.
Parameters
connId Connection identifier.
handle Attribute handle.
consentCode Consent code (0-9999)
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, UDSC_UCP_OPCODE_RNU, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
UdscValueUpdate()
uint8_t UdscValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length UDSC_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length UDSC_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, attEvt_t::handle, attEvt_t::hdr, wsfMsgHdr_t::param, attEvt_t::pValue, UDSC_UCP_IDX, and attEvt_t::valueLen.
UdscWriteDatabaseChangeIncrement()
void UdscWriteDatabaseChangeIncrement (dmConnId_t connId, uint16_t handle, uint32_t increment)
Write the database change increment characteristic.
Parameters
connId Connection identifier.
handle Attribute handle.
increment DB Change Increment
Returns
None.
Parameters
connId Connection identifier.
handle Attribute handle.
increment DB change increment
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, AttcWriteReq(), UINT32_TO_BSTREAM, and WsfTimerStartSec().