Cordio: Mesh Low Power Node API
Mesh Low Power Node API
Data Structures
struct meshLpnFriendshipEstablishedEvt_t
struct meshLpnFriendshipTerminatedEvt_t
union meshLpnEvt_t
Typedefs
typedef void(* meshLpnEvtNotifyCback_t) (const meshLpnEvt_t *pEvent)
Enumerations
enum meshLpnEventValues
Functions
uint32_t MeshLpnGetRequiredMemory (void)
uint32_t MeshLpnMemInit (uint8_t *pFreeMem, uint32_t freeMemSize)
void MeshLpnInit (void)
void MeshLpnRegister (meshLpnEvtNotifyCback_t eventCback)
bool_t MeshLpnEstablishFriendship (uint16_t netKeyIndex, meshFriendshipCriteria_t *pLpnCriteria, uint32_t sleepDurationMs, uint8_t recvDelayMs, uint8_t establishRetryCount)
void MeshLpnTerminateFriendship (uint16_t netKeyIndex)
uint32_t MeshLpnGetRemainingSleepPeriod (void)
uint16_t MeshLpnSizeOfEvt (wsfMsgHdr_t *pMeshLpnEvt)
Detailed Description
Data Structure Documentation
meshLpnFriendshipEstablishedEvt_t
struct meshLpnFriendshipEstablishedEvt_t
LPN Friendship Established event type for MESH_LPN_FRIENDSHIP_ESTABLISHED_EVENT.
Data Fields
wsfMsgHdr_t hdr
uint16_t netKeyIndex
Field Documentation
hdr
wsfMsgHdr_t hdr
Header structure
netKeyIndex
uint16_t netKeyIndex
Connection identifier
meshLpnFriendshipTerminatedEvt_t
struct meshLpnFriendshipTerminatedEvt_t
LPN Friendship Established event type for MESH_LPN_FRIENDSHIP_TERMINATED_EVENT.
Data Fields
wsfMsgHdr_t hdr
uint16_t netKeyIndex
Field Documentation
hdr
wsfMsgHdr_t hdr
Header structure
netKeyIndex
uint16_t netKeyIndex
Connection identifier
meshLpnEvt_t
union meshLpnEvt_t
Generic LPN event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
meshLpnFriendshipEstablishedEvt_t friendshipEstablished
meshLpnFriendshipTerminatedEvt_t friendshipTerminated
Field Documentation
friendshipEstablished
meshLpnFriendshipEstablishedEvt_t friendshipEstablished
Friendship Established event
friendshipTerminated
meshLpnFriendshipTerminatedEvt_t friendshipTerminated
Friendship Terminated event
hdr
wsfMsgHdr_t hdr
Generic WSF header
Typedef Documentation
meshLpnEvtNotifyCback_t
typedef void(* meshLpnEvtNotifyCback_t) (const meshLpnEvt_t *pEvent)
Mesh LPN event notification callback function pointer type.
Parameters
[in] pEvent Pointer to LPN event. See meshLpnEvt_t
Returns
None.
Note
This notification callback should be used by the application to process the LPN events and take appropriate action.
Enumeration Type Documentation
meshLpnEventValues
enum meshLpnEventValues
Mesh LPN callback events.
Enumerator
MESH_LPN_FRIENDSHIP_ESTABLISHED_EVENT
Friendship Established event
MESH_LPN_FRIENDSHIP_TERMINATED_EVENT
Friendship Terminated event
MESH_LPN_MAX_EVENT
Max LPN event
Function Documentation
MeshLpnEstablishFriendship()
bool_t MeshLpnEstablishFriendship (uint16_t netKeyIndex, meshFriendshipCriteria_t * pLpnCriteria, uint32_t sleepDurationMs, uint8_t recvDelayMs, uint8_t establishRetryCount)
Tries to establish a Friendship based on specific criteria for a subnet.
Parameters
[in] netKeyIndex NetKey index.
[in] pLpnCriteria Pointer to LPN criteria structure.
[in] sleepDurationMs Sleep duration in milliseconds.
[in] recvDelayMs Receive Delay in milliseconds, see meshFriendshipRecvDelayValues.
[in] establishRetryCount Number of retries for Friendship establish procedures.
Returns
TRUE if success, FALSE otherwise.
MeshLpnGetRemainingSleepPeriod()
uint32_t MeshLpnGetRemainingSleepPeriod (void)
Returns the period in milliseconds until another scheduled action is performed by LPN.
Returns
Period value in milliseconds.
References wsfMsgHdr_t::event, wsfTimer_t::isStarted, meshLpnCtx_t::lpnTimer, wsfTimer_t::msg, meshLpnCtx_t::pollTimer, wsfTimer_t::ticks, WSF_CS_ENTER, WSF_CS_EXIT, WSF_CS_INIT, WSF_MIN, and WSF_MS_PER_TICK.
MeshLpnGetRequiredMemory()
uint32_t MeshLpnGetRequiredMemory (void)
Computes memory requirements for LPN feature.
Returns
Required memory in bytes.
MeshLpnInit()
void MeshLpnInit (void)
Initialize Low Power Node feature.
Returns
None.
This function initializes the Low Power Node feature.
Note
This function and MeshFriendInit() are mutually exclusive.
References meshCb_t::friendshipMsgCback, wsfTimer_t::handlerId, meshCb_t::handlerId, meshLpnCtx_t::lpnTimer, meshMemoryConfig_t::maxNumFriendships, MESH_ADDR_TYPE_UNASSIGNED, MESH_LOW_POWER_FEATURE_DISABLED, MeshAccRegisterLpn(), MeshLocalCfgRegisterLpn(), MeshLocalCfgSetLowPowerState(), meshMemoryConfig_t::netKeyListSize, meshConfig_t::pMemoryConfig, pMeshConfig, meshLpnCtx_t::pollTimer, meshLpnCtx_t::subscrListQueue, WSF_MIN, and WSF_QUEUE_INIT.
MeshLpnMemInit()
uint32_t MeshLpnMemInit (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize Low Power Node memory requirements.
Parameters
[in] pFreeMem Pointer to free memory.
[in] freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function initializes the Low Power Node feature.
Note
This function must be called once after Mesh Stack initialization.
Parameters
[in] pFreeMem Free memory.
[in] freeMemSize Amount of free memory in bytes.
Returns
Amount of free memory consumed.
This function initializes the Low Power Node memory requirements.
Note
This function must be called once after Mesh Stack initialization.
References meshMemoryConfig_t::maxNumFriendships, MeshLpnGetRequiredMemory(), meshConfig_t::pMemoryConfig, pMeshConfig, and WSF_ASSERT.
MeshLpnRegister()
void MeshLpnRegister (meshLpnEvtNotifyCback_t eventCback)
Registers the Mesh LPN events callback.
Parameters
[in] eventCback Callback function for LPN events.
Returns
None.
MeshLpnSizeOfEvt()
uint16_t MeshLpnSizeOfEvt (wsfMsgHdr_t * pMeshLpnEvt)
Return size of a Mesh Low Power Node callback event.
Parameters
[in] pMeshLpnEvt Mesh Low Power Node callback event.
Returns
Size of Mesh Low Power Node callback event.
References wsfMsgHdr_t::event, MESH_LPN_EVENT, MESH_LPN_MAX_EVENT, and wsfMsgHdr_t::param.
MeshLpnTerminateFriendship()
void MeshLpnTerminateFriendship (uint16_t netKeyIndex)
Terminates an established Friendship for a subnet.
Parameters
[in] netKeyIndex NetKey index.
Returns
None.
References wsfMsgHdr_t::event, meshCb_t::handlerId, MESH_KEY_REFRESH_PROHIBITED_START, MeshLocalCfgGetKeyRefreshPhaseState(), wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().