Cordio: BATTERY_PROFILE
BATTERY_PROFILE
Data Structures
struct basCfg_t
Functions
void BasInit (wsfHandlerId_t handlerId, basCfg_t *pCfg)
void BasMeasBattStart (dmConnId_t connId, uint8_t timerEvt, uint8_t battCccIdx)
void BasMeasBattStop (dmConnId_t connId)
void BasProcMsg (wsfMsgHdr_t *pMsg)
void BasSendBattLevel (dmConnId_t connId, uint8_t idx, uint8_t level)
uint8_t BasReadCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, attsAttr_t *pAttr)
Detailed Description
Data Structure Documentation
basCfg_t
struct basCfg_t
Battery service configurable parameters.
Data Fields
wsfTimerTicks_t period
uint16_t count
uint8_t threshold
Function Documentation
BasInit()
void BasInit (wsfHandlerId_t handlerId, basCfg_t * pCfg)
Initialize the battery service server.
Parameters
handlerId WSF handler ID of the application using this service.
pCfg Battery service configurable parameters.
Returns
None.
Parameters
handerId WSF handler ID of the application using this service.
pCfg Battery service configurable parameters.
Returns
None.
BasMeasBattStart()
void BasMeasBattStart (dmConnId_t connId, uint8_t timerEvt, uint8_t battCccIdx)
Start periodic battery level measurement. This function starts a timer to perform periodic battery measurements.
Parameters
connId DM connection identifier.
timerEvt WSF event designated by the application for the timer.
battCccIdx Index of battery level CCC descriptor in CCC descriptor handle table.
Returns
None.
References WsfTimerStartSec().
BasMeasBattStop()
void BasMeasBattStop (dmConnId_t connId)
Stop periodic battery level measurement.
Parameters
connId DM connection identifier.
Returns
None.
References DM_CONN_ID_NONE.
BasProcMsg()
void BasProcMsg (wsfMsgHdr_t * pMsg)
Process received WSF message.
Parameters
pMsg Event message.
Returns
None.
References ATTS_HANDLE_VALUE_CNF, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
BasReadCback()
uint8_t BasReadCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, attsAttr_t * pAttr)
ATTS read callback for battery service used to read the battery level. Use this function as a parameter to SvcBattCbackRegister().
Parameters
connId DM connection identifier.
handle ATT handle.
operation ATT operation.
offset read offset.
pAttr pointer to Attribute
Returns
ATT status.
ATT status.
References AppHwBattRead(), ATT_SUCCESS, and attsAttr_t::pValue.
BasSendBattLevel()
void BasSendBattLevel (dmConnId_t connId, uint8_t idx, uint8_t level)
Send the battery level to the peer device.
Parameters
connId DM connection identifier.
idx Index of battery level CCC descriptor in CCC descriptor handle table.
level The battery level.
Returns
None.
References AttsCccEnabled(), AttsHandleValueNtf(), BATT_LVL_HDL, and CH_BATT_LEVEL_LEN.