Cordio: ASSET_TRACKING_PROFILE_CLIENT
ASSET_TRACKING_PROFILE_CLIENT
Enumerations
enum
Functions
void AtpcCteDiscover (dmConnId_t connId, uint16_t *pHdlList)
void AtpcCteWriteEnable (dmConnId_t connId, uint16_t handle, uint8_t enable)
void AtpcCteWriteMinLen (dmConnId_t connId, uint16_t handle, uint8_t minLen)
void AtpcCteWriteMinTxCount (dmConnId_t connId, uint16_t handle, uint8_t txCount)
void AtpcCteWriteTxDuration (dmConnId_t connId, uint16_t handle, uint8_t duration)
void AtpcCteWriteInterval (dmConnId_t connId, uint16_t handle, uint16_t interval)
void AtpcCteWritePhy (dmConnId_t connId, uint16_t handle, uint8_t phy)
void AtpcSetAntennaIds (dmConnId_t connId, uint8_t numAntenna, uint8_t *pAntennaIds)
void AtpcCteAclEnableReq (dmConnId_t connId, uint16_t handle, uint8_t length, uint16_t interval)
void AtpcCteAclDisableReq (dmConnId_t connId, uint16_t handle)
void AtpcProcMsg (wsfMsgHdr_t *pEvt)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumeration of handle indexes of characteristics to be discovered.
Enumerator
ATPC_CTE_ENABLE_HDL
Constant Tone Extension enable.
ATPC_CTE_MIN_LEN_HDL
Constant Tone Extension minimum length.
ATPC_CTE_ADV_MIN_TX_CNT_HDL
Constant Tone Extension minimum transmit count.
ATPC_CTE_ADV_TX_DURATION_HDL
Constant Tone Extension transmit duration.
ATPC_CTE_ADV_INTERVAL_HDL
Constant Tone Extension interval.
ATPC_CTE_ADV_EXT_PHY_HDL
Constant Tone Extension PHY.
ATPC_CTE_HDL_LIST_LEN
Handle list length.
Function Documentation
AtpcCteAclDisableReq()
void AtpcCteAclDisableReq (dmConnId_t connId, uint16_t handle)
Disable AoA CTE Rx request over ACL.
Parameters
connId Connection identifier.
handle CTE enable attribute handle.
Returns
None.
References AtpcCteWriteEnable(), ATT_HANDLE_NONE, CTE_ENABLE_NONE, DM_CONN_CTE_STATE_INITIATING, DM_CONN_ID_NONE, DM_CONN_MAX, DmConnCteGetReqState(), and WSF_ASSERT.
AtpcCteAclEnableReq()
void AtpcCteAclEnableReq (dmConnId_t connId, uint16_t handle, uint8_t length, uint16_t interval)
Enable AoA CTE Rx request over ACL.
Parameters
connId Connection identifier.
handle CTE enable attribute handle.
length Request length.
interval Request interval.
Returns
None.
References AtpcCteWriteEnable(), ATT_HANDLE_NONE, CTE_ENABLE_ACL_BIT, DM_CONN_CTE_STATE_IDLE, DM_CONN_ID_NONE, DM_CONN_MAX, DmConnCteGetReqState(), and WSF_ASSERT.
AtpcCteDiscover()
void AtpcCteDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Constant Tone Extension service. Parameter pHdlList must point to an array of length ATPC_CTE_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATPC_CTE_HDL_LIST_LEN, ATT_16_UUID_LEN, and attCteSvcUuid.
AtpcCteWriteEnable()
void AtpcCteWriteEnable (dmConnId_t connId, uint16_t handle, uint8_t enable)
Write to the Constant Tone Extension enable attribute.
Parameters
connId Connection identifier.
handle Attribute handle.
enable Enable.
Returns
None.
References ATT_HANDLE_NONE, AttcWriteReq(), and WSF_ASSERT.
AtpcCteWriteInterval()
void AtpcCteWriteInterval (dmConnId_t connId, uint16_t handle, uint16_t interval)
Write to the Constant Tone Extension interval attribute.
Parameters
connId Connection identifier.
handle Attribute handle.
interval Interval.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, AttcWriteReq(), UINT16_TO_BSTREAM, and WSF_ASSERT.
AtpcCteWriteMinLen()
void AtpcCteWriteMinLen (dmConnId_t connId, uint16_t handle, uint8_t minLen)
Write to the Constant Tone Extension minimum length attribute.
Parameters
connId Connection identifier.
handle Attribute handle.
minLen Minimum length.
Returns
None.
References ATT_HANDLE_NONE, AttcWriteReq(), and WSF_ASSERT.
AtpcCteWriteMinTxCount()
void AtpcCteWriteMinTxCount (dmConnId_t connId, uint16_t handle, uint8_t txCount)
Write to the Constant Tone Extension minimum transmit count attribute.
Parameters
connId Connection identifier.
handle Attribute handle.
txCount Minimum transmit count.
Returns
None.
References ATT_HANDLE_NONE, AttcWriteReq(), and WSF_ASSERT.
AtpcCteWritePhy()
void AtpcCteWritePhy (dmConnId_t connId, uint16_t handle, uint8_t phy)
Write to the Constant Tone Extension PHY attribute.
Parameters
connId Connection identifier.
handle Attribute handle.
phy PHY.
Returns
None.
References ATT_HANDLE_NONE, AttcWriteReq(), and WSF_ASSERT.
AtpcCteWriteTxDuration()
void AtpcCteWriteTxDuration (dmConnId_t connId, uint16_t handle, uint8_t duration)
Write to the Constant Tone Extension transmit duration attribute.
Parameters
connId Connection identifier.
handle Attribute handle.
duration Transmit duration.
Returns
None.
References ATT_HANDLE_NONE, AttcWriteReq(), and WSF_ASSERT.
AtpcProcMsg()
void AtpcProcMsg (wsfMsgHdr_t * pEvt)
Called by application to notify the ATPC of System Events.
Parameters
pEvt Pointer to the Event.
Returns
None.
References ATTC_WRITE_RSP, hciLeReadAntennaInfoCmdCmplEvt_t::cteMaxLen, DM_CONN_CTE_RX_SAMPLE_START_IND, DM_CONN_CTE_RX_SAMPLE_STOP_IND, DM_CTE_REQ_FAIL_IND, DM_READ_ANTENNA_INFO_IND, DM_RESET_CMPL_IND, DmConnCteReqStart(), DmConnCteReqStop(), DmReadAntennaInfo(), wsfMsgHdr_t::event, HCI_CTE_TYPE_REQ_AOA, HCI_SUCCESS, hciLeReadAntennaInfoCmdCmplEvt_t::numAntennae, wsfMsgHdr_t::param, dmEvt_t::readAntennaInfo, hciLeReadAntennaInfoCmdCmplEvt_t::switchPatternMaxLen, and hciLeReadAntennaInfoCmdCmplEvt_t::switchSampleRates.
AtpcSetAntennaIds()
void AtpcSetAntennaIds (dmConnId_t connId, uint8_t numAntenna, uint8_t * pAntennaIds)
Set the antenna identifiers for a connection ID.
Parameters
connId Connection identifier.
numAntenna Number of antenna and len of pAntennaIds in bytes.
pAntennaIds Array containing identifiers of antenna for this connection.
Returns
None.
References DM_CONN_ID_NONE, DM_CONN_MAX, and WSF_ASSERT.