Cordio: LL_API_BROADCAST
LL_API_BROADCAST
Data Structures
struct LlExtAdvParam_t
struct LlExtAdvEnableParam_t
struct LlPerAdvParam_t
Macros
#define LL_ADDR_RANDOM_BIT LL_ADDR_RANDOM
#define LL_ADDR_IDENTITY_BIT LL_ADDR_PUBLIC_IDENTITY
#define LL_ADV_EVT_PROP_NON_CONN_NON_SCAN 0
Enumerations
enum
enum
enum
enum
enum
enum
enum
Functions
void LlSetAdvTxPower (int8_t advTxPwr)
uint8_t LlGetAdvTxPower (int8_t *pAdvTxPwr)
uint8_t LlSetAdvParam (uint16_t advIntervalMin, uint16_t advIntervalMax, uint8_t advType, uint8_t ownAddrType, uint8_t peerAddrType, const uint8_t *pPeerAddr, uint8_t advChanMap, uint8_t advFiltPolicy)
uint8_t LlSetAdvData (uint8_t len, const uint8_t *pData)
uint8_t LlSetScanRespData (uint8_t len, const uint8_t *pData)
void LlAdvEnable (uint8_t enable)
uint8_t LlSetAdvSetRandAddr (uint8_t handle, const uint8_t *pAddr)
uint64_t LlGetPeriodicChanMap (uint16_t handle, bool_t isAdv)
uint8_t LlGetAdvSetRandAddr (uint8_t handle, uint8_t *pAddr)
uint8_t LlSetExtAdvParam (uint8_t handle, LlExtAdvParam_t *pExtAdvParam)
uint8_t LlGetExtAdvTxPowerLevel (uint16_t handle, int8_t *pLevel)
uint8_t LlSetExtAdvData (uint8_t handle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t *pData)
uint8_t LlSetExtScanRespData (uint8_t handle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t *pData)
void LlExtAdvEnable (uint8_t enable, uint8_t numAdvSets, LlExtAdvEnableParam_t enaParam[])
uint8_t LlReadMaxAdvDataLen (uint16_t *pLen)
uint8_t LlReadNumSupAdvSets (uint8_t *pNumSets)
uint8_t LlRemoveAdvSet (uint8_t handle)
uint8_t LlClearAdvSets (void)
uint8_t LlSetPeriodicAdvParam (uint8_t handle, LlPerAdvParam_t *pPerAdvParam)
uint8_t LlSetPeriodicAdvData (uint8_t handle, uint8_t op, uint8_t len, const uint8_t *pData)
void LlSetPeriodicAdvEnable (uint8_t enable, uint8_t handle)
uint8_t LlSetAuxOffsetDelay (uint8_t handle, uint32_t delayUsec)
uint8_t LlSetExtAdvDataFragLen (uint8_t handle, uint8_t fragLen)
uint8_t LlSetExtAdvTxPhyOptions (uint8_t handle, uint8_t priPhyOpts, uint8_t secPhyOpts)
void LlReadSupTxPower (int8_t *pMinTxPwr, int8_t *pMaxTxPwr)
void LlReadRfPathComp (int16_t *pTxPathComp, int16_t *pRxPathComp)
uint8_t LlWriteRfPathComp (int16_t txPathComp, int16_t rxPathComp)
void LlScanReportEnable (uint8_t enable)
Detailed Description
Data Structure Documentation
LlExtAdvParam_t
struct LlExtAdvParam_t
Extended advertising parameters.
Data Fields
uint16_t advEventProp
uint32_t priAdvInterMin
uint32_t priAdvInterMax
uint8_t priAdvChanMap
uint8_t ownAddrType
uint8_t peerAddrType
const uint8_t * pPeerAddr
uint8_t advFiltPolicy
int8_t advTxPwr
uint8_t priAdvPhy
uint8_t secAdvMaxSkip
uint8_t secAdvPhy
uint8_t advSID
uint8_t scanReqNotifEna
Field Documentation
advEventProp
uint16_t advEventProp
Advertising Event Properties.
advFiltPolicy
uint8_t advFiltPolicy
Advertising Filter Policy.
advSID
uint8_t advSID
Advertising SID.
advTxPwr
int8_t advTxPwr
Advertising Tx Power.
ownAddrType
uint8_t ownAddrType
Own Address Type.
peerAddrType
uint8_t peerAddrType
Peer Address Type.
pPeerAddr
const uint8_t* pPeerAddr
Peer Address.
priAdvChanMap
uint8_t priAdvChanMap
Primary Advertising Channel Map.
priAdvInterMax
uint32_t priAdvInterMax
Primary Advertising Interval Maximum.
priAdvInterMin
uint32_t priAdvInterMin
Primary Advertising Interval Minimum.
priAdvPhy
uint8_t priAdvPhy
Primary Advertising PHY.
scanReqNotifEna
uint8_t scanReqNotifEna
Scan Request Notification Enable.
secAdvMaxSkip
uint8_t secAdvMaxSkip
Secondary Advertising Maximum Skip.
secAdvPhy
uint8_t secAdvPhy
Secondary Advertising PHY.
LlExtAdvEnableParam_t
struct LlExtAdvEnableParam_t
Extended advertising enable parameters.
Data Fields
uint8_t handle
uint16_t duration
uint8_t numEvents
Field Documentation
duration
uint16_t duration
Duration.
handle
uint8_t handle
Advertising handle.
numEvents
uint8_t numEvents
Maximum number of extended advertising events.
LlPerAdvParam_t
struct LlPerAdvParam_t
Periodic advertising parameters.
Data Fields
uint16_t perAdvInterMin
uint16_t perAdvInterMax
uint16_t perAdvProp
Field Documentation
perAdvInterMax
uint16_t perAdvInterMax
Periodic Advertising Interval Maximum.
perAdvInterMin
uint16_t perAdvInterMin
Periodic Advertising Interval Minimum.
perAdvProp
uint16_t perAdvProp
Periodic Advertising Properties.
Macro Definition Documentation
LL_ADDR_IDENTITY_BIT
#define LL_ADDR_IDENTITY_BIT LL_ADDR_PUBLIC_IDENTITY
Address type identity bit.
LL_ADDR_RANDOM_BIT
#define LL_ADDR_RANDOM_BIT LL_ADDR_RANDOM
Address type random or public bit.
LL_ADV_EVT_PROP_NON_CONN_NON_SCAN
#define LL_ADV_EVT_PROP_NON_CONN_NON_SCAN 0
Non-connectable and non-scannable advertising.
Enumeration Type Documentation
anonymous enum
anonymous enum
The advertising type indicates the connectable and discoverable nature of the advertising packets transmitted by a device.
Enumerator
LL_ADV_CONN_UNDIRECT
Connectable undirected advertising. Peer devices can scan and connect to this device.
LL_ADV_CONN_DIRECT_HIGH_DUTY
Connectable directed advertising, high duty cycle. Only a specified peer device can connect to this device.
LL_ADV_SCAN_UNDIRECT
Scannable undirected advertising. Peer devices can scan this device but cannot connect.
LL_ADV_NONCONN_UNDIRECT
Non-connectable undirected advertising. Peer devices cannot scan or connect to this device.
LL_ADV_CONN_DIRECT_LOW_DUTY
Connectable directed advertising, low duty cycle. Only a specified peer device can connect to this device.
anonymous enum
anonymous enum
The address type indicates whether an address is public or random.
Enumerator
LL_ADDR_PUBLIC
Public address.
LL_ADDR_RANDOM
Random address.
LL_ADDR_PUBLIC_IDENTITY
Public identity address.
LL_ADDR_RANDOM_IDENTITY
Random (static) identity address.
LL_ADDR_RANDOM_UNRESOLVABLE
Un-resolvable random address.
LL_ADDR_ANONYMOUS
Anonymous advertiser.
anonymous enum
anonymous enum
Advertising channel bit.
Enumerator
LL_ADV_CHAN_37_BIT
Advertising channel 37.
LL_ADV_CHAN_38_BIT
Advertising channel 38.
LL_ADV_CHAN_39_BIT
Advertising channel 39.
LL_ADV_CHAN_ALL
All advertising channels.
anonymous enum
anonymous enum
Advertising filter policy.
Enumerator
LL_ADV_FILTER_NONE
Scan from any device.
LL_ADV_FILTER_SCAN_WL_BIT
Scan from White List only.
LL_ADV_FILTER_CONN_WL_BIT
Connect from While List only.
LL_ADV_FILTER_WL_ONLY
Scan and connect from While List only.
anonymous enum
anonymous enum
Advertising event properties.
Enumerator
LL_ADV_EVT_PROP_CONN_ADV_BIT
Connectable advertising.
LL_ADV_EVT_PROP_SCAN_ADV_BIT
Scannable advertising.
LL_ADV_EVT_PROP_DIRECT_ADV_BIT
Directed advertising.
LL_ADV_EVT_PROP_HIGH_DUTY_ADV_BIT
High Duty Cycle advertising.
LL_ADV_EVT_PROP_LEGACY_ADV_BIT
Use legacy advertising PDUs.
LL_ADV_EVT_PROP_OMIT_AA_BIT
Omit advertiser's address from all PDUs (anonymous advertising).
LL_ADV_EVT_PROP_TX_PWR_BIT
Include TxPower in the advertising PDU.
anonymous enum
anonymous enum
Advertising data operation.
Enumerator
LL_ADV_DATA_OP_FRAG_INTER
Intermediate fragment.
LL_ADV_DATA_OP_FRAG_FIRST
First fragment.
LL_ADV_DATA_OP_FRAG_LAST
Last fragment.
LL_ADV_DATA_OP_COMP
Complete extended advertising data.
LL_ADV_DATA_OP_UNCHANGED
Unchanged data (just update the Advertising DID).
anonymous enum
anonymous enum
Advertising data fragment preference.
Enumerator
LL_ADV_DATA_FRAG_ALLOW
Controller may fragment all Host advertising data.
LL_ADV_DATA_FRAG_DISALLOW
Controller should not fragment nor minimize fragmentation of Host advertising data.
Function Documentation
LlAdvEnable()
void LlAdvEnable (uint8_t enable)
Advertising enable.
Parameters
enable Set to TRUE to enable advertising, FALSE to disable advertising.
Enable or disable advertising.
References lmgrSlvAdvCtrlBlk_t::advParam, lmgrAdvParam_t::advType, LL_ADV_CONN_DIRECT_HIGH_DUTY, LL_ADV_CONN_DIRECT_LOW_DUTY, LL_ADV_CONN_UNDIRECT, lmgrCb, LmgrIsLegacyCommandAllowed(), LmgrSendAdvEnableCnf(), lmgrSlvAdvCb, LlRtCfg_t::maxConn, lmgrCtrlBlk_t::numConnEnabled, and pLctrRtCfg.
LlClearAdvSets()
uint8_t LlClearAdvSets (void)
Clear advertising sets.
Returns
Status error code.
Remove all existing advertising sets from the LL.
References LmgrIsExtCommandAllowed().
LlExtAdvEnable()
void LlExtAdvEnable (uint8_t enable, uint8_t numAdvSets, LlExtAdvEnableParam_t enaParam[])
Extended advertising enable.
Parameters
enable Set to TRUE to enable advertising, FALSE to disable advertising.
numAdvSets Number of elements in enaParam[].
enaParam Enable parameter table.
Enable or disable extended advertising.
References lmgrCtrlBlk_t::advSetEnaStatus, lctrMsgHdr_t::dispId, LlExtAdvEnableParam_t::duration, LctrExtAdvEnableMsg_t::durMs, lctrMsgHdr_t::event, lmgrCtrlBlk_t::extAdvEnaDelayCnt, lctrMsgHdr_t::handle, LlExtAdvEnableParam_t::handle, lmgrPersistCtrlBlk_t::handlerId, LctrExtAdvEnableMsg_t::hdr, LCTR_DISP_EXT_ADV, lmgrCb, LmgrIsExtCommandAllowed(), lmgrPersistCb, LctrExtAdvEnableMsg_t::maxEvents, LlExtAdvEnableParam_t::numEvents, WsfMsgAlloc(), and WsfMsgSend().
LlGetAdvSetRandAddr()
uint8_t LlGetAdvSetRandAddr (uint8_t handle, uint8_t * pAddr)
Get advertising set random device address.
Parameters
handle Advertising handle.
pAddr Random Bluetooth device address.
Returns
Status error code.
Get the random address to be used by a advertising set.
Parameters
handle Advertising set ID.
pAddr Random Bluetooth device address.
Returns
Status error code.
Get the random address to be used by a advertising set.
References WSF_ASSERT.
LlGetAdvTxPower()
uint8_t LlGetAdvTxPower (int8_t * pAdvTxPwr)
Get advertising transmit power.
Parameters
pAdvTxPwr Advertising transmit power level.
Returns
Status error code.
Return the advertising transmit power.
References lmgrCtrlBlk_t::advTxPwr, lmgrCb, LmgrIsLegacyCommandAllowed(), PalRadioGetActualTxPower(), and WSF_ASSERT.
LlGetExtAdvTxPowerLevel()
uint8_t LlGetExtAdvTxPowerLevel (uint16_t handle, int8_t * pLevel)
Get extended advertising TX power level.
Parameters
handle Advertising handle.
pLevel Transmit power level.
Returns
Status error code.
Get the TX power of an advertising set.
LlGetPeriodicChanMap()
uint64_t LlGetPeriodicChanMap (uint16_t handle, bool_t isAdv)
Get periodic channel map.
Parameters
handle Periodic advertiser/scanner handle.
isAdv TRUE for periodic advertiser, FALSE for periodic scanner.
Returns
64-bit formatted channel mask.
Get the 64-bit channel mask of the channel map
Get periodic channel map.
Parameters
handle handle.
isAdv Handle is an advertiser.
Returns
Channel map, packed into a 64bit int
Note: Consider moving to ll_main_ae.c (as of now, no file for this exists).
LlReadMaxAdvDataLen()
uint8_t LlReadMaxAdvDataLen (uint16_t * pLen)
Read maximum advertising data length.
Parameters
pLen Return buffer for Maximum data length.
Returns
Status error code.
Read maximum advertising data length.
References LmgrIsExtCommandAllowed(), LlRtCfg_t::maxExtAdvDataLen, pLctrRtCfg, WSF_ASSERT, and WSF_MIN.
LlReadNumSupAdvSets()
uint8_t LlReadNumSupAdvSets (uint8_t * pNumSets)
Read number of supported advertising sets.
Parameters
pNumSets Return buffer for number of advertising sets.
Returns
Status error code.
Read number of supported advertising sets.
References LmgrIsExtCommandAllowed(), LlRtCfg_t::maxAdvSets, pLctrRtCfg, and WSF_ASSERT.
LlReadRfPathComp()
void LlReadRfPathComp (int16_t * pTxPathComp, int16_t * pRxPathComp)
Read RF path compensation.
Parameters
pTxPathComp Return buffer for RF transmit path compensation value.
pRxPathComp Return buffer for RF receive path compensation value.
Read the RF Path Compensation Values parameter used in the Tx Power Level and RSSI calculation.
References PalRadioReadRfPathComp(), and WSF_ASSERT.
LlReadSupTxPower()
void LlReadSupTxPower (int8_t * pMinTxPwr, int8_t * pMaxTxPwr)
Read supported transmit power.
Parameters
pMinTxPwr Return buffer for minimum transmit power.
pMaxTxPwr Return buffer for maximum transmit power.
Read the minimum and maximum transmit powers supported by the LL.
References PalRadioGetSupTxPower(), and WSF_ASSERT.
LlRemoveAdvSet()
uint8_t LlRemoveAdvSet (uint8_t handle)
Remove advertising set.
Parameters
handle Advertising handle.
Returns
Status error code.
Removes the an advertising set from the LL.
Parameters
handle Advertising set ID.
Returns
Status error code.
Removes the an advertising set from the LL.
References LmgrIsExtCommandAllowed().
LlScanReportEnable()
void LlScanReportEnable (uint8_t enable)
Scan report enable.
Parameters
enable Set to TRUE to enable scan reports, FALSE to disable scan reports.
Enable or disable reports about the scanners from which an advertiser receives scan requests.
Parameters
enable Set to TRUE to enable scan reports, FALSE to disable scan reports.
Returns
None.
Enable or disable reports about the scanners from which an advertiser receives scan requests.
References lmgrSlvAdvCb, and lmgrSlvAdvCtrlBlk_t::scanReportEna.
LlSetAdvData()
uint8_t LlSetAdvData (uint8_t len, const uint8_t * pData)
Set advertising data.
Parameters
len Data buffer length.
pData Advertising data buffer.
Returns
Status error code.
Set advertising data data.
References lmgrSlvAdvCtrlBlk_t::advData, lmgrAdvbUser_t::buf, lmgrAdvbUser_t::len, LmgrIsLegacyCommandAllowed(), lmgrSlvAdvCb, lmgrAdvbUser_t::modified, WSF_CS_ENTER, and WSF_CS_INIT.
LlSetAdvParam()
uint8_t LlSetAdvParam (uint16_t advIntervalMin, uint16_t advIntervalMax, uint8_t advType, uint8_t ownAddrType, uint8_t peerAddrType, const uint8_t * pPeerAddr, uint8_t advChanMap, uint8_t advFiltPolicy)
Set advertising parameter.
Parameters
advIntervalMin Minimum advertising interval.
advIntervalMax Maximum advertising interval.
advType Advertising type.
ownAddrType Address type used by this device.
peerAddrType Address type of peer device. Only used for directed advertising.
pPeerAddr Address of peer device. Only used for directed advertising.
advChanMap Advertising channel map.
advFiltPolicy Advertising filter policy.
Returns
Status error code.
Set advertising parameters.
Note
This function must only be called when advertising is disabled.
References lmgrAdvParam_t::advChanMap, lmgrCtrlBlk_t::advEnabled, lmgrAdvParam_t::advFiltPolicy, lmgrAdvParam_t::advInterMaxUsec, lmgrAdvParam_t::advInterMinUsec, lmgrAdvParam_t::advType, BB_BLE_TO_US, BSTREAM_TO_BDA64, lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrCtrlBlk_t::features, lmgrPersistCtrlBlk_t::handlerId, lctrAdvParamMsg_t::hdr, LCTR_ADV_MSG_PARAM_UPD, LCTR_DISP_ADV, LL_ADDR_IDENTITY_BIT, LL_ADDR_RANDOM, LL_ADDR_RANDOM_IDENTITY, LL_ADV_CHAN_ALL, LL_ADV_CONN_DIRECT_HIGH_DUTY, LL_ADV_CONN_DIRECT_LOW_DUTY, LL_ADV_FILTER_WL_ONLY, LL_FEAT_PRIVACY, lmgrCb, LmgrIsLegacyCommandAllowed(), lmgrPersistCb, lmgrAdvParam_t::ownAddrType, lctrAdvParamMsg_t::param, lmgrAdvParam_t::peerAddr, lmgrAdvParam_t::peerAddrType, WsfMsgAlloc(), and WsfMsgSend().
LlSetAdvSetRandAddr()
uint8_t LlSetAdvSetRandAddr (uint8_t handle, const uint8_t * pAddr)
Set advertising set random device address.
Parameters
handle Advertising handle.
pAddr Random Bluetooth device address.
Returns
Status error code.
Set the random address to be used by a advertising set.
Parameters
handle Advertising set ID.
pAddr Random Bluetooth device address.
Returns
Status error code.
Set the random address to be used by a advertising set.
References WSF_ASSERT.
LlSetAdvTxPower()
void LlSetAdvTxPower (int8_t advTxPwr)
Set advertising transmit power.
Parameters
advTxPwr Advertising transmit power level.
Set the advertising transmit power.
References lmgrCtrlBlk_t::advTxPwr, and lmgrCb.
LlSetAuxOffsetDelay()
uint8_t LlSetAuxOffsetDelay (uint8_t handle, uint32_t delayUsec)
Set auxiliary packet offset delay.
Parameters
handle Advertising handle.
delayUsec Additional time in microseconds. "0" to disable.
Returns
Status error code.
Additional delay given to auxiliary packets specified by AuxPtr. Offset values are limited by the advertising interval.
LlSetExtAdvData()
uint8_t LlSetExtAdvData (uint8_t handle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t * pData)
Set extended advertising data.
Parameters
handle Advertising handle.
op Operation.
fragPref Fragment preference.
len Data buffer length.
pData Advertising data buffer.
Returns
Status error code.
Set extended advertising data data.
Parameters
handle Advertising set ID.
op Operation.
fragPref Fragment preference.
len Data buffer length.
pData Advertising data buffer.
Returns
Status error code.
Set extended advertising data data.
References LmgrIsExtCommandAllowed(), and WSF_ASSERT.
LlSetExtAdvDataFragLen()
uint8_t LlSetExtAdvDataFragLen (uint8_t handle, uint8_t fragLen)
Set extended advertising data fragmentation length.
Parameters
handle Advertising handle.
fragLen Fragmentation length.
Returns
Status error code.
Fragmentation size for Advertising Data and Scan Response Data when selected by the host.
LlSetExtAdvParam()
uint8_t LlSetExtAdvParam (uint8_t handle, LlExtAdvParam_t * pExtAdvParam)
Set extended advertising parameters.
Parameters
handle Advertising handle.
pExtAdvParam Extended advertising parameters.
Returns
Status error code.
Set extended advertising parameters.
Note
This function must only be called when advertising for this set is disabled.
Parameters
handle Advertising set ID.
pExtAdvParam Extended advertising parameters.
Returns
Status error code.
Set extended advertising parameters.
Note
This function must only be called when advertising for this set is disabled.
References LlExtAdvParam_t::advEventProp, BbGetBbTimerBoundaryUs(), lmgrCtrlBlk_t::features, LL_ADV_EVT_PROP_CONN_ADV_BIT, LL_ADV_EVT_PROP_DIRECT_ADV_BIT, LL_ADV_EVT_PROP_HIGH_DUTY_ADV_BIT, LL_ADV_EVT_PROP_LEGACY_ADV_BIT, LL_ADV_EVT_PROP_OMIT_AA_BIT, LL_ADV_EVT_PROP_SCAN_ADV_BIT, LL_ADV_EVT_PROP_TX_PWR_BIT, LL_FEAT_LE_2M_PHY, LL_FEAT_LE_CODED_PHY, LL_PHY_LE_1M, LL_PHY_LE_2M, LL_PHY_LE_CODED, lmgrCb, LmgrIsExtCommandAllowed(), LlExtAdvParam_t::priAdvInterMax, LlExtAdvParam_t::priAdvInterMin, LlExtAdvParam_t::priAdvPhy, LlExtAdvParam_t::secAdvPhy, and WSF_MIN.
LlSetExtAdvTxPhyOptions()
uint8_t LlSetExtAdvTxPhyOptions (uint8_t handle, uint8_t priPhyOpts, uint8_t secPhyOpts)
Set extended advertising transmit PHY options.
Parameters
handle Advertising handle.
priPhyOpts Primary advertising channel PHY options.
secPhyOpts Secondary advertising channel PHY options.
Returns
Status error code.
PHY options for extended advertising transmissions. New values are applied dynamically.
References LL_PHY_OPTIONS_S2_PREFERRED, and LL_PHY_OPTIONS_S8_PREFERRED.
LlSetExtScanRespData()
uint8_t LlSetExtScanRespData (uint8_t handle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t * pData)
Set extended scan response data.
Parameters
handle Advertising handle.
op Operation.
fragPref Fragment preference.
len Data buffer length.
pData Scan response data buffer.
Returns
Status error code.
Set extended scan response data.
Parameters
handle Advertising set ID.
op Operation.
fragPref Fragment preference.
len Data buffer length.
pData Scan response data buffer.
Returns
Status error code.
Set extended scan response data.
References LmgrIsExtCommandAllowed(), and WSF_ASSERT.
LlSetPeriodicAdvData()
uint8_t LlSetPeriodicAdvData (uint8_t handle, uint8_t op, uint8_t len, const uint8_t * pData)
Set periodic advertising data.
Parameters
handle Advertising handle.
op Operation.
len Data buffer length.
pData Advertising data buffer.
Returns
Status error code.
Set periodic advertising data.
Parameters
handle Advertising handle.
op Operation.
len Data buffer length.
pData Advertising data buffer.
Returns
Status error code.
Set extended advertising data data.
References LL_ADV_DATA_OP_COMP, LmgrIsExtCommandAllowed(), and WSF_ASSERT.
LlSetPeriodicAdvEnable()
void LlSetPeriodicAdvEnable (uint8_t enable, uint8_t handle)
Set periodic advertising enable.
Parameters
enable TRUE to enable advertising, FALSE to disable advertising.
handle Advertising handle.
Returns
Status error code.
Enable or disable periodic advertising.
Parameters
handle Advertising handle.
enable Set to TRUE to enable advertising, FALSE to disable advertising.
Enable or disable periodic advertising.
References LmgrIsExtCommandAllowed().
LlSetPeriodicAdvParam()
uint8_t LlSetPeriodicAdvParam (uint8_t handle, LlPerAdvParam_t * pPerAdvParam)
Set periodic advertising parameters.
Parameters
handle Advertising handle.
pPerAdvParam Periodic advertising parameters.
Returns
Status error code.
Set periodic advertising parameters.
Note
This function must only be called when advertising handle exists.
Parameters
handle Advertising set ID.
pPerAdvParam Periodic advertising parameters.
Returns
Status error code.
Set periodic advertising parameters.
Note
This function must only be called when advertising handle exists.
References LmgrIsExtCommandAllowed(), LlPerAdvParam_t::perAdvInterMax, LlPerAdvParam_t::perAdvInterMin, and LlPerAdvParam_t::perAdvProp.
LlSetScanRespData()
uint8_t LlSetScanRespData (uint8_t len, const uint8_t * pData)
Set scan response data.
Parameters
len Data buffer length.
pData Scan response data buffer.
Returns
Status error code.
Set scan response data.
References lmgrAdvbUser_t::buf, lmgrAdvbUser_t::len, LmgrIsLegacyCommandAllowed(), lmgrSlvAdvCb, lmgrAdvbUser_t::modified, lmgrSlvAdvCtrlBlk_t::scanRspData, WSF_CS_ENTER, and WSF_CS_INIT.
LlWriteRfPathComp()
uint8_t LlWriteRfPathComp (int16_t txPathComp, int16_t rxPathComp)
Write RF path compensation.
Parameters
txPathComp RF transmit path compensation value.
rxPathComp RF receive path compensation value.
Returns
Status error code.
Indicate the RF path gain or loss between the RF transceiver and the antenna contributed by intermediate components.
References PalRadioWriteRfPathComp().