Cordio: Mesh Friend API
Mesh Friend API
Functions
uint32_t MeshFriendGetRequiredMemory (void)
uint32_t MeshFriendMemInit (uint8_t *pFreeMem, uint32_t freeMemSize)
void MeshFriendInit (uint8_t recvWinMs)
Detailed Description
Function Documentation
MeshFriendGetRequiredMemory()
uint32_t MeshFriendGetRequiredMemory (void)
Computes the required memory to be provided based on the given configuration.
Returns
Memory required value in bytes if success or MESH_MEM_REQ_INVALID_CFG in case fail.
References MESH_MEM_REQ_INVALID_CFG, and MESH_UTILS_ALIGN.
MeshFriendInit()
void MeshFriendInit (uint8_t recvWinMs)
Initialize Friend Node feature.
Parameters
[in] recvWinMs Receive Window in milliseconds.
Returns
None.
Note
This function and MeshLpnInit() are mutually exclusive.
Parameters
[in] recvWinMs Receive Window in milliseconds.
Returns
None
Note
This function and MeshLpnInit() are mutually exclusive.
References MESH_FRIEND_FEATURE_DISABLED, MESH_FRIEND_FEATURE_ENABLED, MESH_FRIEND_FEATURE_NOT_SUPPORTED, MeshLocalCfgGetFriendState(), MeshLocalCfgSetFriendState(), meshFriendCb_t::pSm, meshFriendCb_t::recvWindow, and meshFriendCb_t::state.
MeshFriendMemInit()
uint32_t MeshFriendMemInit (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize Friend Node memory requirements.
Parameters
[in] pFreeMem Pointer to free memory.
[in] freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
Note
This function must be called once after Mesh Stack initialization.
References meshCb_t::handlerId, MESH_UTILS_ALIGN, MeshFriendGetRequiredMemory(), and meshFriendCb_t::pLpnCtxTbl.