Cordio: HEART_RATE_PROFILE
HEART_RATE_PROFILE
Data Structures
struct hrpsCfg_t
Enumerations
enum
Functions
void HrpcHrsDiscover (dmConnId_t connId, uint16_t *pHdlList)
void HrpcHrsControl (dmConnId_t connId, uint16_t handle, uint8_t command)
uint8_t HrpcHrsValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void HrpsInit (wsfHandlerId_t handlerId, hrpsCfg_t *pCfg)
void HrpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t hrmCccIdx)
void HrpsMeasStop (dmConnId_t connId)
void HrpsProcMsg (wsfMsgHdr_t *pMsg)
uint8_t HrpsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
void HrpsSetFlags (uint8_t flags)
Detailed Description
Data Structure Documentation
hrpsCfg_t
struct hrpsCfg_t
Configurable parameters.
Data Fields
wsfTimerTicks_t period
Enumeration Type Documentation
anonymous enum
anonymous enum
Heart Rate service enumeration of handle indexes of characteristics to be discovered.
Enumerator
HRPC_HRS_HRM_HDL_IDX
Heart rate measurement.
HRPC_HRS_HRM_CCC_HDL_IDX
Heart rate measurement CCC descriptor.
HRPC_HRS_BSL_HDL_IDX
Body sensor location.
HRPC_HRS_HRCP_HDL_IDX
Heart rate control point.
HRPC_HRS_HDL_LIST_LEN
Handle list length.
Function Documentation
HrpcHrsControl()
void HrpcHrsControl (dmConnId_t connId, uint16_t handle, uint8_t command)
Send a command to the heart rate control point.
Parameters
connId Connection identifier.
handle Attribute handle.
command Control point command.
Returns
None.
References ATT_HANDLE_NONE, and AttcWriteReq().
HrpcHrsDiscover()
void HrpcHrsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Heart Rate service. Parameter pHdlList must point to an array of length HRPC_HRS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Heart Rate service. Parameter pHdlList must point to an array of length HRPC_HRS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attHrsSvcUuid, and HRPC_HRS_HDL_LIST_LEN.
HrpcHrsValueUpdate()
uint8_t HrpcHrsValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length HRPC_HRS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characterist handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length HRPC_HRS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, BSTREAM_TO_UINT8, CH_BSENSOR_LOC_FOOT, attEvt_t::handle, HRPC_HRS_BSL_HDL_IDX, HRPC_HRS_HRM_HDL_IDX, attEvt_t::pValue, and attEvt_t::valueLen.
HrpsInit()
void HrpsInit (wsfHandlerId_t handlerId, hrpsCfg_t * pCfg)
Initialize the Heart Rate profile sensor.
Parameters
handlerId WSF handler ID of the application using this service.
pCfg Configurable parameters.
Returns
None.
Parameters
handerId WSF handler ID of the application using this service.
pCfg Configurable parameters.
Returns
None.
HrpsMeasStart()
void HrpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t hrmCccIdx)
Start periodic heart rate measurement. This function starts a timer to perform periodic measurements.
Parameters
connId DM connection identifier.
timerEvt WSF event designated by the application for the timer.
hrmCccIdx Index of heart rate CCC descriptor in CCC descriptor handle table.
Returns
None.
References WsfTimerStartMs().
HrpsMeasStop()
void HrpsMeasStop (dmConnId_t connId)
Stop periodic heart rate measurement.
Parameters
connId DM connection identifier.
Returns
None.
References DM_CONN_ID_NONE.
HrpsProcMsg()
void HrpsProcMsg (wsfMsgHdr_t * pMsg)
Process received WSF message.
Parameters
pMsg Event message.
Returns
None.
References ATTS_HANDLE_VALUE_CNF, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
HrpsSetFlags()
void HrpsSetFlags (uint8_t flags)
Set the heart rate measurement flags.
Parameters
flags Heart rate measurement flags.
Returns
None.
HrpsWriteCback()
uint8_t HrpsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
ATTS write callback for heart rate service Use this function as a parameter to SvcHrsCbackRegister().
Parameters
connId DM connection identifier.
handle ATT handle.
operation ATT operation.
offset Write offset.
len Write length.
pValue Value to write.
pAttr Attribute to write.
Returns
ATT status.
ATTS write callback for heart rate service Use this function as a parameter to SvcHrsCbackRegister().
Returns
ATT status.
References ATT_SUCCESS, CH_HRCP_RESET_ENERGY_EXP, and HRS_ERR_CP_NOT_SUP.