Cordio: LL_API_INIT
LL_API_INIT
Data Structures
struct LlRtCfg_t
Functions
void LlGetDefaultRunTimeCfg (LlRtCfg_t *pCfg)
void LlInitRunTimeCfg (const LlRtCfg_t *pCfg)
uint16_t LlInitConnMem (uint8_t *pFreeMem, uint32_t freeMemSize)
uint16_t LlInitExtAdvMem (uint8_t *pFreeMem, uint32_t freeMemSize)
uint16_t LlInitExtScanMem (uint8_t *pFreeMem, uint32_t freeMemSize)
void LlAdvSlaveInit (void)
void LlExtAdvSlaveInit (void)
void LlConnSlaveInit (void)
void LlEncConnSlaveInit (void)
void LlScanMasterInit (void)
void LlExtScanMasterInit (void)
void LlInitMasterInit (void)
void LlExtInitMasterInit (void)
void LlConnMasterInit (void)
void LlEncConnMasterInit (void)
void LlPrivInit (void)
void LlScInit (void)
void LlPhySlaveInit (void)
void LlPhyMasterInit (void)
void LlChannelSelection2Init (void)
void LlTestInit (void)
void LlHandlerInit (wsfHandlerId_t handlerId)
void LlPowerControlInit (void)
void LlHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
void LlReset (void)
void LlEvtRegister (llEvtCback_t evtCback)
void LlAclRegister (llAclCback_t sendCompCback, llAclCback_t recvPendCback)
void LlIsoRegister (llIsoCback_t sendIsoCompCback, llIsoCback_t recvIsoPendCback)
Detailed Description
Data Structure Documentation
LlRtCfg_t
struct LlRtCfg_t
LL runtime configuration parameters.
Data Fields
uint16_t compId
uint16_t implRev
uint8_t btVer
uint32_t _align32
uint8_t maxAdvSets
uint8_t maxAdvReports
uint16_t maxExtAdvDataLen
uint8_t defExtAdvDataFrag
uint16_t auxDelayUsec
uint16_t auxPtrOffsetUsec
uint8_t maxScanReqRcvdEvt
uint16_t maxExtScanDataLen
uint8_t maxConn
uint8_t numTxBufs
uint8_t numRxBufs
uint16_t maxAclLen
int8_t defTxPwrLvl
uint8_t ceJitterUsec
uint8_t numIsoTxBuf
uint8_t numIsoRxBuf
uint16_t maxIsoSduLen
uint16_t maxIsoPduLen
uint8_t maxCig
uint8_t maxCis
uint16_t cisSubEvtSpaceDelay
uint8_t maxBig
uint8_t maxBis
uint16_t dtmRxSyncMs
bool_t phy2mSup
bool_t phyCodedSup
bool_t stableModIdxTxSup
bool_t stableModIdxRxSup
Field Documentation
_align32
uint32_t _align32
Unused. Align next field to word boundary.
auxDelayUsec
uint16_t auxDelayUsec
Auxiliary Offset delay above T_MAFS in microseconds.
auxPtrOffsetUsec
uint16_t auxPtrOffsetUsec
Delay of auxiliary packet in microseconds from the time specified by auxPtr.
btVer
uint8_t btVer
Core specification implementation level (LL_VER_BT_CORE_SPEC_4_2).
ceJitterUsec
uint8_t ceJitterUsec
Allowable CE jitter on a slave (account for master's sleep clock resolution).
cisSubEvtSpaceDelay
uint16_t cisSubEvtSpaceDelay
Subevent spacing above T_MSS in microsecond.
compId
uint16_t compId
Company ID (default to ARM Ltd. ID).
defExtAdvDataFrag
uint8_t defExtAdvDataFrag
Default extended advertising data fragmentation size.
defTxPwrLvl
int8_t defTxPwrLvl
Default Tx power level for connections.
dtmRxSyncMs
uint16_t dtmRxSyncMs
DTM Rx synchronization window in milliseconds.
implRev
uint16_t implRev
Implementation revision number.
maxAclLen
uint16_t maxAclLen
Maximum ACL buffer size.
maxAdvReports
uint8_t maxAdvReports
Maximum number of pending legacy or extended advertising reports.
maxAdvSets
uint8_t maxAdvSets
Maximum number of advertising sets.
maxBig
uint8_t maxBig
Maximum number of BIG.
maxBis
uint8_t maxBis
Maximum number of BIS.
maxCig
uint8_t maxCig
Maximum number of CIG.
maxCis
uint8_t maxCis
Maximum number of CIS, it is shared by the CIGs.
maxConn
uint8_t maxConn
Maximum number of connections.
maxExtAdvDataLen
uint16_t maxExtAdvDataLen
Maximum extended advertising data size.
maxExtScanDataLen
uint16_t maxExtScanDataLen
Maximum extended scan data size.
maxIsoPduLen
uint16_t maxIsoPduLen
Maximum ISO Data PDU buffer size.
maxIsoSduLen
uint16_t maxIsoSduLen
Maximum ISO SDU size between host and controller.
maxScanReqRcvdEvt
uint8_t maxScanReqRcvdEvt
Maximum scan request received events.
numIsoRxBuf
uint8_t numIsoRxBuf
Default number of ISO receive buffers.
numIsoTxBuf
uint8_t numIsoTxBuf
Default number of ISO transmit buffers.
numRxBufs
uint8_t numRxBufs
Default number of receive buffers.
numTxBufs
uint8_t numTxBufs
Default number of transmit buffers.
phy2mSup
bool_t phy2mSup
2M PHY supported.
phyCodedSup
bool_t phyCodedSup
Coded PHY supported.
stableModIdxRxSup
bool_t stableModIdxRxSup
Rx stable modulation index supported.
stableModIdxTxSup
bool_t stableModIdxTxSup
Tx stable modulation index supported.
Function Documentation
LlAclRegister()
void LlAclRegister (llAclCback_t sendCompCback, llAclCback_t recvPendCback)
Register ACL handler.
Parameters
sendCompCback Client ACL send complete callback function.
recvPendCback Client ACL receive pending callback function.
This function is called by a client to register for ACL data.
References lmgrPersistCb, lmgrPersistCtrlBlk_t::recvPendCback, and lmgrPersistCtrlBlk_t::sendCompCback.
LlAdvSlaveInit()
void LlAdvSlaveInit (void)
Initialize LL subsystem for operation as an advertising slave.
This function initializes the LL subsystem for use as an advertising slave.
References LctrSlvAdvInit(), LmgrSlvInit(), pLctrRtCfg, and WSF_ASSERT.
LlChannelSelection2Init()
void LlChannelSelection2Init (void)
Initialize LL subsystem for secure connections.
This function initializes the LL subsystem for secure connections.
LlConnMasterInit()
void LlConnMasterInit (void)
Initialize LL subsystem for operation as a connectable master.
This function initializes the LL subsystem for use as a scanning and initiating master.
This function initializes the LL subsystem for use as an advertising and connectable master.
References LctrMstConnInit(), LmgrConnInit(), pLctrRtCfg, and WSF_ASSERT.
LlConnSlaveInit()
void LlConnSlaveInit (void)
Initialize LL subsystem for operation as a connectable slave.
This function initializes the LL subsystem for use as an advertising and connectable slave.
References LctrSlvConnInit(), LmgrConnInit(), pLctrRtCfg, and WSF_ASSERT.
LlEncConnMasterInit()
void LlEncConnMasterInit (void)
Initialize LL subsystem for operation as a encryptable connectable slave.
This function initializes the LL subsystem for use as an advertising and encryptable connectable slave.
Initialize LL subsystem for operation as a encryptable connectable slave.
This function initializes the LL subsystem for use as an advertising and encryptable connectable master.
References LctrMstConnEncInit(), LmgrConnInit(), pLctrRtCfg, and WSF_ASSERT.
LlEncConnSlaveInit()
void LlEncConnSlaveInit (void)
Initialize LL subsystem for operation as a encryptable connectable slave.
This function initializes the LL subsystem for use as an advertising and encryptable connectable slave.
References LctrSlvConnEncInit(), LmgrConnInit(), pLctrRtCfg, and WSF_ASSERT.
LlEvtRegister()
void LlEvtRegister (llEvtCback_t evtCback)
Register LL event handler.
Parameters
evtCback Client callback function.
This function is called by a client to register for LL events.
References lmgrPersistCtrlBlk_t::evtCback, and lmgrPersistCb.
LlExtAdvSlaveInit()
void LlExtAdvSlaveInit (void)
Initialize LL subsystem for operation for extended advertising slave.
This function initializes the LL subsystem for use as an extended advertising slave.
References LmgrSlvInit(), pLctrRtCfg, and WSF_ASSERT.
LlExtInitMasterInit()
void LlExtInitMasterInit (void)
Initialize LL subsystem for operation as an extended initiating master.
This function initializes the LL subsystem for use as an initiating master.
Initialize LL subsystem for operation as an extended initiating master.
This function initializes the LL subsystem for use as an initiating master.
References LctrMstExtInitInit(), pLctrRtCfg, and WSF_ASSERT.
LlExtScanMasterInit()
void LlExtScanMasterInit (void)
Initialize LL subsystem for operation for extended scanning master.
This function initializes the LL subsystem for use as an extended scanning master.
Initialize LL subsystem for operation for extended scanning master.
This function initializes the LL subsystem for use as an scanning master.
References LmgrMstInit(), pLctrRtCfg, and WSF_ASSERT.
LlGetDefaultRunTimeCfg()
void LlGetDefaultRunTimeCfg (LlRtCfg_t * pCfg)
Get default runtime configuration values.
Parameters
pCfg Pointer to runtime configuration parameters.
This function returns default value for the LL subsystem's runtime configurations.
References LlRtCfg_t::compId, and HCI_ID_ANALOG.
LlHandler()
void LlHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
LL message dispatch handler.
Parameters
event WSF event.
pMsg WSF message.
References LCTR_EVENT_TOTAL, LctrEventHandler(), and LctrMsgDispatcher().
LlHandlerInit()
void LlHandlerInit (wsfHandlerId_t handlerId)
Initialize LL subsystem with task handler.
Parameters
handlerId WSF handler ID.
This function initializes the LL subsystem. It is called once upon system initialization. It must be called before any other function in the LL API is called.
References lmgrCtrlBlk_t::advEnabled, lmgrPersistCtrlBlk_t::bdAddr, LlRtCfg_t::compId, lmgrPersistCtrlBlk_t::handlerId, LctrSetSupStates(), lmgrCb, lmgrPersistCb, lmgrCtrlBlk_t::numConnEnabled, and WSF_ASSERT.
LlInitConnMem()
uint16_t LlInitConnMem (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize memory for connections.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for connections.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
References LctrInitConnMem(), pLctrRtCfg, and WSF_ASSERT.
LlInitExtAdvMem()
uint16_t LlInitExtAdvMem (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize memory for extended advertising.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for extended advertising.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
References LctrInitAdvSetMem(), pLctrRtCfg, and WSF_ASSERT.
LlInitExtScanMem()
uint16_t LlInitExtScanMem (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize memory for extended scanning.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for extended scanning.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
References LctrInitExtScanMem(), pLctrRtCfg, and WSF_ASSERT.
LlInitMasterInit()
void LlInitMasterInit (void)
Initialize LL subsystem for operation as an initiating master.
This function initializes the LL subsystem for use as an initiating master.
References LctrMstInitInit(), pLctrRtCfg, and WSF_ASSERT.
LlInitRunTimeCfg()
void LlInitRunTimeCfg (const LlRtCfg_t * pCfg)
Initialize runtime configuration.
Parameters
pCfg Pointer to runtime configuration parameters (data must be static).
This function initializes the LL subsystem's runtime configuration.
Note
This routine must be called only once before any other initialization routines.
References LlRtCfg_t::btVer, LlRtCfg_t::dtmRxSyncMs, LlRtCfg_t::maxAclLen, LlRtCfg_t::maxAdvReports, LlRtCfg_t::maxAdvSets, LlRtCfg_t::maxConn, LlRtCfg_t::maxExtAdvDataLen, LlRtCfg_t::numRxBufs, LlRtCfg_t::numTxBufs, and WSF_ASSERT.
LlIsoRegister()
void LlIsoRegister (llIsoCback_t sendIsoCompCback, llIsoCback_t recvIsoPendCback)
Register ISO handler.
Parameters
sendIsoCompCback Client ISO send complete callback function.
recvIsoPendCback Client ISO receive pending callback function.
This function is called by a client to register for ISO data.
Parameters
sendIsoCompCback Client ISO send complete callback function.
recvIsoPendCback Client ISO receive pending callback function.
This function is called by a client to register for ACL data.
References lmgrPersistCb, lmgrPersistCtrlBlk_t::recvIsoPendCback, and lmgrPersistCtrlBlk_t::sendIsoCompCback.
LlPhyMasterInit()
void LlPhyMasterInit (void)
Initialize LL subsystem for PHY features (master).
This function initializes the LL subsystem for master PHY features.
LlPhySlaveInit()
void LlPhySlaveInit (void)
Initialize LL subsystem for PHY features (slave).
This function initializes the LL subsystem for slave PHY features.
LlPowerControlInit()
void LlPowerControlInit (void)
Initialize LL subsystem for operation for power control.
This function initializes the LL subsystem for power control.
LlPrivInit()
void LlPrivInit (void)
Initialize LL subsystem for operation with privacy.
This function initializes the LL subsystem for use with privacy.
Initialize LL subsystem for operation with privacy.
This function initializes the LL subsystem for use as an advertising slave.
References LctrPrivInit(), and LmgrPrivInit().
LlReset()
void LlReset (void)
Reset LL subsystem.
Reset the LL subsystem. All active connections are closed and all radio procedures such as scanning or advertising are terminated.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, LCTR_DISP_BCST, LCTR_MSG_RESET, lmgrPersistCb, WsfMsgAlloc(), and WsfMsgSend().
LlScanMasterInit()
void LlScanMasterInit (void)
Initialize LL subsystem for operation as a scanning master.
This function initializes the LL subsystem for use as a scanning master.
Initialize LL subsystem for operation as a scanning master.
This function initializes the LL subsystem for use as an scanning master.
References LctrMstScanInit(), LmgrMstInit(), pLctrRtCfg, and WSF_ASSERT.
LlScInit()
void LlScInit (void)
Initialize LL subsystem for secure connections.
This function initializes the LL subsystem for secure connections.
References LctrScInit(), LmgrScInit(), pLctrRtCfg, and WSF_ASSERT.
LlTestInit()
void LlTestInit (void)
Initialize LL subsystem for test modes.
This function initializes the LL subsystem for test modes.
Initialize LL subsystem for test modes.
References BbBleTestInit(), and LCTR_DISP_TEST.