Cordio: RUNNING_SPEED_AND_CADENCE_PROFILE
RUNNING_SPEED_AND_CADENCE_PROFILE
Functions
void RscpsSetParameter (uint8_t type, uint32_t value)
void RscpsSetSensorLocation (uint8_t location)
void RscpsSetFeatures (uint16_t features)
void RscpsSendSpeedMeasurement (dmConnId_t connId)
Running Speed and Cadence Measurement Parameter Types
#define RSCP_SM_PARAM_SPEED 0
#define RSCP_SM_PARAM_CADENCE 1
#define RSCP_SM_PARAM_STRIDE_LENGTH 2
#define RSCP_SM_PARAM_TOTAL_DISTANCE 3
#define RSCP_SM_PARAM_STATUS 4
Running Speed and Cadence Running Status Values
#define RSCP_SM_STATUS_WALKING 0
#define RSCP_SM_STATUS_RUNNING 1
Detailed Description
Function Documentation
RscpsSendSpeedMeasurement()
void RscpsSendSpeedMeasurement (dmConnId_t connId)
Notifies the collector of a Running Speed and Cadence Measurement.
Parameters
connId Connection ID
Returns
none
Notifies the collector of a Running Speed and Cadence Measurement.
Parameters
connId Connection ID
Returns
none
References AttsHandleValueNtf(), RSCS_RSM_HDL, UINT16_TO_BSTREAM, UINT32_TO_BSTREAM, and UINT8_TO_BSTREAM.
RscpsSetFeatures()
void RscpsSetFeatures (uint16_t features)
Set the features attribute.
Parameters
features Features bitmask.
Returns
none
References AttsSetAttr(), RSCS_RSF_HDL, and UINT16_TO_BYTES.
RscpsSetParameter()
void RscpsSetParameter (uint8_t type, uint32_t value)
Set a running speed measurement parameter.
Parameters
type Parameter identifier
value Measurement value.
Returns
none
References RSCP_SM_PARAM_CADENCE, RSCP_SM_PARAM_SPEED, RSCP_SM_PARAM_STATUS, RSCP_SM_PARAM_STRIDE_LENGTH, and RSCP_SM_PARAM_TOTAL_DISTANCE.
RscpsSetSensorLocation()
void RscpsSetSensorLocation (uint8_t location)
Set the sensor location attribute.
Parameters
location Sensor Location.
Returns
none
References AttsSetAttr(), and RSCS_SL_HDL.