Cordio: CYCLING_SPEED_AND_CADENCE_PROFILE
CYCLING_SPEED_AND_CADENCE_PROFILE
Functions
void CscpsSetParameter (uint8_t type, uint32_t value)
void CscpsSendSpeedMeasurement (dmConnId_t connId)
void CscpsSetSensorLocation (uint8_t location)
void CscpsSetFeatures (uint16_t features)
Cycling Speed Measurement Parameter Types
#define CSCP_SM_PARAM_WHEEL_REVOLUTIONS 0 /* Cumulative Wheel Revolutions */
#define CSCP_SM_PARAM_LAST_WHEEL_EVT_TIME 1 /* Last Wheel Event Time */
#define CSCP_SM_PARAM_CRANK_REVOLUTIONS 2 /* Cumulative Crank Revolutions */
#define CSCP_SM_PARAM_LAST_CRANK_TIME 3 /* Last Crank Event Time */
Detailed Description
Function Documentation
CscpsSendSpeedMeasurement()
void CscpsSendSpeedMeasurement (dmConnId_t connId)
Notifies the collector of a Cycle Speed Measurement.
Parameters
connId Connection ID
Returns
none
References AttsHandleValueNtf(), CSCS_CSM_HDL, UINT16_TO_BSTREAM, UINT32_TO_BSTREAM, and UINT8_TO_BSTREAM.
CscpsSetFeatures()
void CscpsSetFeatures (uint16_t features)
Set the features attribute.
Parameters
features Features bitmask.
Returns
none
References AttsSetAttr(), CSCS_CSF_HDL, and UINT16_TO_BYTES.
CscpsSetParameter()
void CscpsSetParameter (uint8_t type, uint32_t value)
Set a cycling speed measurement parameter.
Parameters
type Parameter identifier
value Measurement value.
Returns
none
CscpsSetSensorLocation()
void CscpsSetSensorLocation (uint8_t location)
Set the sensor location attribute.
Parameters
location Sensor Location.
Returns
none
References AttsSetAttr(), and CSCS_SL_HDL.