Cordio: Bluetooth LE Protocol
Bluetooth LE Protocol
Baseband (BB) API
Data Structures
struct BbBleAdvPktStats_t
struct BbBleAuxAdvPktStats_t
struct BbBleScanPktStats_t
struct BbBleAuxScanPktStats_t
struct BbBlePerScanPktStats_t
struct BbBleDataPktStats_t
struct BbBlePduFiltStats_t
struct BbBleMstAdvEvent_t
struct BbBleSlvAdvEvent_t
struct BbBleMstAuxAdvEvent_t
struct BbBleMstPerScanEvent_t
struct BbBleSlvAuxAdvEvent_t
struct BbBleMstConnEvent_t
struct BbBleSlvConnEvent_t
struct BbBleMstCisEvent_t
struct BbBleSlvCisEvent_t
struct BbBleMstBisEvent_t
struct BbBleSlvBisEvent_t
struct BbBleTestTx_t
struct BbBleTestRx_t
struct BbBleData_t
Macros
#define BB_BLE_TO_US(n) ((n) * LL_BLE_US_PER_TICK)
#define BB_INC_STAT(s) s++
#define BB_REQ_PDU_MAX_LEN (LL_ADV_HDR_LEN + LL_CONN_IND_PDU_LEN)
#define BB_MIN_SCAN_US
Typedefs
typedef void(* BbBlePreExec_t) (BbOpDesc_t *pBod)
typedef void(* BbBleExec_t) (BbOpDesc_t *pBod)
typedef void(* BbBleCancel_t) (BbOpDesc_t *pBod)
typedef void(* BbBleTxAdvSetup_t) (BbOpDesc_t *pBod, uint32_t advTxTime)
typedef uint32_t(* BbBleTxAuxSetup_t) (BbOpDesc_t *pBod, bool_t isChainInd)
typedef bool_t(* BbBleAdvComp_t) (BbOpDesc_t *pBod, const uint8_t *pBuf)
typedef void(* BbBleAdvPost_t) (BbOpDesc_t *pBod, const uint8_t *pBuf)
typedef uint32_t(* BbBleRxChain_t) (BbOpDesc_t *pBod, const uint8_t *pBuf)
typedef bool_t(* BbBleRxChainPost_t) (BbOpDesc_t *pBod, const uint8_t *pBuf)
typedef void(* BbBleTxDataComp_t) (BbOpDesc_t *pBod, uint8_t status)
typedef void(* BbBleRxDataComp_t) (BbOpDesc_t *pBod, uint8_t *pBuf, uint8_t status)
typedef uint32_t(* BbBleCisCheckContOp_t) (BbOpDesc_t *pBod, bool_t *pNewCisCtx)
typedef void(* BbBleCisPostExec_t) (BbOpDesc_t *pBod, uint8_t status)
typedef void(* BbBleCisRxDataComp_t) (BbOpDesc_t *pBod, uint8_t *pBuf, uint8_t status)
typedef bool_t(* BbBleTestComp_t) (BbOpDesc_t *pBod, uint8_t status)
typedef uint32_t(* BbBlePerComp_t) (BbOpDesc_t *pBod, const uint8_t *pBuf, uint8_t status)
typedef bool_t(* BbBlePerPostComp_t) (BbOpDesc_t *pBod, const uint8_t *pBuf)
Enumerations
enum BbBleOp_t
Functions
void BbBleInit (void)
void BbBleScanMasterInit (void)
void BbBleAuxScanMasterInit (void)
void BbBlePerScanMasterInit (void)
void BbBleConnMasterInit (void)
void BbBleAdvSlaveInit (void)
void BbBleAuxAdvSlaveInit (void)
void BbBleConnSlaveInit (void)
void BbBleTestInit (void)
uint16_t BbBleInitWhiteList (uint8_t numEntries, uint8_t *pFreeMem, uint32_t freeMemSize)
uint16_t BbBleInitResolvingList (uint8_t numEntries, uint8_t *pFreeMem, uint32_t freeMemSize)
uint16_t BbBleInitPeriodicList (uint8_t numEntries, uint8_t *pFreeMem, uint32_t freeMemSize)
void BbBleGetAdvStats (BbBleAdvPktStats_t *pStats)
void BbBleGetScanStats (BbBleScanPktStats_t *pStats)
void BbBleGetAuxAdvStats (BbBleAuxAdvPktStats_t *pStats)
void BbBleGetAuxScanStats (BbBleAuxScanPktStats_t *pStats)
void BbBleGetPerScanStats (BbBlePerScanPktStats_t *pStats)
void BbBleGetConnStats (BbBleDataPktStats_t *pStats)
void BbBleResetConnStats (void)
void BbBleGetTestStats (BbBleDataPktStats_t *pStats)
void BbBleResetTestStats (void)
void BbBleGetPduFiltStats (BbBlePduFiltStats_t *pStats)
void BbBleCisMasterInit (void)
void BbBleCisSlaveInit (void)
void BbBleBisMasterInit (void)
void BbBleBisSlaveInit (void)
void BbBleGetCisStats (BbBleDataPktStats_t *pStats)
void BbBleTxData (PalBbBleTxBufDesc_t descs[], uint8_t cnt)
void BbBleRxData (uint8_t *pBuf, uint16_t len)
void BbBleCisTxData (PalBbBleTxBufDesc_t descs[], uint8_t cnt)
void BbBleCisRxData (uint8_t *pBuf, uint16_t len)
void BbBleBisTxData (PalBbBleTxBufDesc_t descs[], uint8_t cnt, uint32_t nextPduTime, PalBbBleChan_t *pNextChan)
void BbBleBisRxData (uint8_t *pBuf, uint16_t len, uint32_t nextPduTime, PalBbBleChan_t *pNextChan, bool_t reAcq)
void BbBleBisRxDataReAcq (uint32_t syncTime, PalBbBleChan_t *pChan)
Detailed Description
Data Structure Documentation
BbBleAdvPktStats_t
struct BbBleAdvPktStats_t
Advertising packet statistics.
Data Fields
uint32_t txAdv
uint32_t rxReq
uint32_t rxReqCrc
uint32_t rxReqTimeout
uint32_t txRsp
uint32_t errAdv
uint16_t rxSetupUsec
uint16_t txSetupUsec
uint16_t rxIsrUsec
uint16_t txIsrUsec
Field Documentation
errAdv
uint32_t errAdv
Number of advertising transaction errors.
rxIsrUsec
uint16_t rxIsrUsec
Rx ISR processing watermark in microseconds.
rxReq
uint32_t rxReq
Number of successfully received advertising requests.
rxReqCrc
uint32_t rxReqCrc
Number of received advertising requests with CRC errors.
rxReqTimeout
uint32_t rxReqTimeout
Number of timed out received advertising requests (receive timeout).
rxSetupUsec
uint16_t rxSetupUsec
Rx packet setup watermark in microseconds.
txAdv
uint32_t txAdv
Number of sent advertising packets.
txIsrUsec
uint16_t txIsrUsec
Tx ISR processing watermark in microseconds.
txRsp
uint32_t txRsp
Number of sent response packets.
txSetupUsec
uint16_t txSetupUsec
Tx packet setup watermark in microseconds.
BbBleAuxAdvPktStats_t
struct BbBleAuxAdvPktStats_t
Auxiliary advertising packet statistics.
Data Fields
uint32_t txAdv
uint32_t rxReq
uint32_t rxReqCrc
uint32_t rxReqTimeout
uint32_t txRsp
uint32_t txChain
uint32_t errAdv
uint16_t rxSetupUsec
uint16_t txSetupUsec
uint16_t rxIsrUsec
uint16_t txIsrUsec
Field Documentation
errAdv
uint32_t errAdv
Number of advertising transaction errors.
rxIsrUsec
uint16_t rxIsrUsec
Rx ISR processing watermark in microseconds.
rxReq
uint32_t rxReq
Number of successfully received advertising requests.
rxReqCrc
uint32_t rxReqCrc
Number of received advertising requests with CRC errors.
rxReqTimeout
uint32_t rxReqTimeout
Number of timed out received advertising requests (receive timeout).
rxSetupUsec
uint16_t rxSetupUsec
Rx packet setup watermark in microseconds.
txAdv
uint32_t txAdv
Number of sent advertising packets.
txChain
uint32_t txChain
Number of sent chain packets.
txIsrUsec
uint16_t txIsrUsec
Tx ISR processing watermark in microseconds.
txRsp
uint32_t txRsp
Number of sent response packets.
txSetupUsec
uint16_t txSetupUsec
Tx packet setup watermark in microseconds.
BbBleScanPktStats_t
struct BbBleScanPktStats_t
Scan packet statistics.
Data Fields
uint32_t rxAdv
uint32_t rxAdvCrc
uint32_t rxAdvTimeout
uint32_t txReq
uint32_t rxRsp
uint32_t rxRspCrc
uint32_t rxRspTimeout
uint32_t errScan
uint16_t rxSetupUsec
uint16_t txSetupUsec
uint16_t rxIsrUsec
uint16_t txIsrUsec
Field Documentation
errScan
uint32_t errScan
Number of scan transaction errors.
rxAdv
uint32_t rxAdv
Number of successfully received advertising packets.
rxAdvCrc
uint32_t rxAdvCrc
Number of received advertising packets with CRC errors.
rxAdvTimeout
uint32_t rxAdvTimeout
Number of timed out advertising packets (receive timeout).
rxIsrUsec
uint16_t rxIsrUsec
Rx ISR processing watermark in microseconds.
rxRsp
uint32_t rxRsp
Number of successfully received advertising response packets.
rxRspCrc
uint32_t rxRspCrc
Number of received advertising response packets with CRC errors.
rxRspTimeout
uint32_t rxRspTimeout
Number of timed out advertising response packets (receive timeout).
rxSetupUsec
uint16_t rxSetupUsec
Rx packet setup watermark in microseconds.
txIsrUsec
uint16_t txIsrUsec
Tx ISR processing watermark in microseconds.
txReq
uint32_t txReq
Number of sent advertising requests.
txSetupUsec
uint16_t txSetupUsec
Tx packet setup watermark in microseconds.
BbBleAuxScanPktStats_t
struct BbBleAuxScanPktStats_t
Scan packet statistics.
Data Fields
uint32_t rxAdv
uint32_t rxAdvCrc
uint32_t rxAdvTimeout
uint32_t txReq
uint32_t rxRsp
uint32_t rxRspCrc
uint32_t rxRspTimeout
uint32_t rxChain
uint32_t rxChainCrc
uint32_t rxChainTimeout
uint32_t errScan
uint16_t rxSetupUsec
uint16_t txSetupUsec
uint16_t rxIsrUsec
uint16_t txIsrUsec
Field Documentation
errScan
uint32_t errScan
Number of scan transaction errors.
rxAdv
uint32_t rxAdv
Number of successfully received advertising packets.
rxAdvCrc
uint32_t rxAdvCrc
Number of received advertising packets with CRC errors.
rxAdvTimeout
uint32_t rxAdvTimeout
Number of timed out advertising packets (receive timeout).
rxChain
uint32_t rxChain
Number of successfully received chain packets.
rxChainCrc
uint32_t rxChainCrc
Number of received chain packets with CRC errors.
rxChainTimeout
uint32_t rxChainTimeout
Number of timed out chain packets (receive timeout).
rxIsrUsec
uint16_t rxIsrUsec
Rx ISR processing watermark in microseconds.
rxRsp
uint32_t rxRsp
Number of successfully received advertising response packets.
rxRspCrc
uint32_t rxRspCrc
Number of received advertising response packets with CRC errors.
rxRspTimeout
uint32_t rxRspTimeout
Number of timed out advertising response packets (receive timeout).
rxSetupUsec
uint16_t rxSetupUsec
Rx packet setup watermark in microseconds.
txIsrUsec
uint16_t txIsrUsec
Tx ISR processing watermark in microseconds.
txReq
uint32_t txReq
Number of sent advertising requests.
txSetupUsec
uint16_t txSetupUsec
Tx packet setup watermark in microseconds.
BbBlePerScanPktStats_t
struct BbBlePerScanPktStats_t
Periodic scan packet statistics.
Data Fields
uint32_t rxAdv
uint32_t rxAdvCrc
uint32_t rxAdvTimeout
uint32_t rxChain
uint32_t rxChainCrc
uint32_t rxChainTimeout
uint32_t errScan
uint16_t rxSetupUsec
uint16_t txSetupUsec
uint16_t rxIsrUsec
uint16_t txIsrUsec
Field Documentation
errScan
uint32_t errScan
Number of scan transaction errors.
rxAdv
uint32_t rxAdv
Number of successfully received advertising packets.
rxAdvCrc
uint32_t rxAdvCrc
Number of received advertising packets with CRC errors.
rxAdvTimeout
uint32_t rxAdvTimeout
Number of timed out advertising packets (receive timeout).
rxChain
uint32_t rxChain
Number of successfully received chain packets.
rxChainCrc
uint32_t rxChainCrc
Number of received chain packets with CRC errors.
rxChainTimeout
uint32_t rxChainTimeout
Number of timed out chain packets (receive timeout).
rxIsrUsec
uint16_t rxIsrUsec
Rx ISR processing watermark in microseconds.
rxSetupUsec
uint16_t rxSetupUsec
Rx packet setup watermark in microseconds.
txIsrUsec
uint16_t txIsrUsec
Tx ISR processing watermark in microseconds.
txSetupUsec
uint16_t txSetupUsec
Tx packet setup watermark in microseconds.
BbBleDataPktStats_t
struct BbBleDataPktStats_t
Data packet statistics.
Data Fields
uint32_t rxData
uint32_t rxDataCrc
uint32_t rxDataTimeout
uint32_t txData
uint32_t errData
uint16_t rxSetupUsec
uint16_t txSetupUsec
uint16_t rxIsrUsec
uint16_t txIsrUsec
Field Documentation
errData
uint32_t errData
Number of data transaction errors.
rxData
uint32_t rxData
Number of successfully received data packets.
rxDataCrc
uint32_t rxDataCrc
Number of received data packets with CRC errors.
rxDataTimeout
uint32_t rxDataTimeout
Number of timed out data packets (receive timeout).
rxIsrUsec
uint16_t rxIsrUsec
Rx ISR processing watermark in microseconds.
rxSetupUsec
uint16_t rxSetupUsec
Rx packet setup watermark in microseconds.
txData
uint32_t txData
Number of sent data packets.
txIsrUsec
uint16_t txIsrUsec
Tx ISR processing watermark in microseconds.
txSetupUsec
uint16_t txSetupUsec
Tx packet setup watermark in microseconds.
BbBlePduFiltStats_t
struct BbBlePduFiltStats_t
PDU filtering statistics.
Data Fields
uint16_t failPduTypeFilt
uint16_t passPduTypeFilt
uint16_t failWlFilt
uint16_t passWlFilt
uint16_t failPeerAddrMatch
uint16_t passPeerAddrMatch
uint16_t failLocalAddrMatch
uint16_t passLocalAddrMatch
uint16_t failPeerRpaVerify
uint16_t passPeerRpaVerify
uint16_t failLocalRpaVerify
uint16_t passLocalRpaVerify
uint16_t failPeerPrivAddrReq
uint16_t failLocalPrivAddrReq
uint16_t failPeerAddrResReq
uint16_t passPeerAddrResOpt
uint16_t passLocalAddrResOpt
uint16_t peerResAddrPend
uint16_t localResAddrPend
Field Documentation
failLocalAddrMatch
uint16_t failLocalAddrMatch
Number of PDUS failing local address match.
failLocalPrivAddrReq
uint16_t failLocalPrivAddrReq
Number of local addresses failing requirement to be RPAs.
failLocalRpaVerify
uint16_t failLocalRpaVerify
Number of local RPAs failing verification.
failPduTypeFilt
uint16_t failPduTypeFilt
Number of PDUs failing PDU type filter.
failPeerAddrMatch
uint16_t failPeerAddrMatch
Number of PDUS failing peer address match.
failPeerAddrResReq
uint16_t failPeerAddrResReq
Number of PDUs failing required peer address resolution.
failPeerPrivAddrReq
uint16_t failPeerPrivAddrReq
Number of peer addresses failing requirement to be RPAs.
failPeerRpaVerify
uint16_t failPeerRpaVerify
Number of peer RPAs failing verification.
failWlFilt
uint16_t failWlFilt
Number of PDUs failing whitelist filter.
localResAddrPend
uint16_t localResAddrPend
Number of local address resolutions pended.
passLocalAddrMatch
uint16_t passLocalAddrMatch
Number of PDUs passing local address match.
passLocalAddrResOpt
uint16_t passLocalAddrResOpt
Number of PDUs passing optional local address resolution.
passLocalRpaVerify
uint16_t passLocalRpaVerify
Number of local RPAs passing verification.
passPduTypeFilt
uint16_t passPduTypeFilt
Number of PDUs passing PDU type filter.
passPeerAddrMatch
uint16_t passPeerAddrMatch
Number of PDUs passing peer address match.
passPeerAddrResOpt
uint16_t passPeerAddrResOpt
Number of PDUs passing optional peer address resolution.
passPeerRpaVerify
uint16_t passPeerRpaVerify
Number of peer RPAs passing verification.
passWlFilt
uint16_t passWlFilt
Number of PDUs passing whitelist filter.
peerResAddrPend
uint16_t peerResAddrPend
Number of peer address resolutions pended.
BbBleMstAdvEvent_t
struct BbBleMstAdvEvent_t
Master advertising event operation data (BB_BLE_OP_MST_ADV_EVENT).
Note
BB assumes maximum adversing and scan response payload is 39 bytes.
Data Fields
uint8_t * pRxAdvBuf
uint8_t * pTxReqBuf
uint8_t * pRxRspBuf
BbBlePreExec_t preExecCback
BbBleAdvComp_t rxAdvCback
BbBleAdvPost_t rxAdvPostCback
BbBleAdvComp_t txReqCback
BbBleAdvComp_t rxRspCback
uint8_t txReqLen
uint8_t scanChMap
int8_t advRssi
uint8_t advRxPhyOptions
uint32_t advCrc
uint32_t advStartTsUsec
uint32_t elapsedUsec
bbBlePduFiltResults_t filtResults
Field Documentation
advCrc
uint32_t advCrc
CRC of advertisement.
advRssi
int8_t advRssi
RSSI of advertisement.
advRxPhyOptions
uint8_t advRxPhyOptions
Rx PHY options.
advStartTsUsec
uint32_t advStartTsUsec
Start of advertising packet timestamp in microseconds.
elapsedUsec
uint32_t elapsedUsec
Elapsed time of a single scan window in microseconds.
filtResults
bbBlePduFiltResults_t filtResults
Results from PDU filtering.
preExecCback
BbBlePreExec_t preExecCback
Pre-execute callback.
pRxAdvBuf
uint8_t* pRxAdvBuf
Advertising buffer.
pRxRspBuf
uint8_t* pRxRspBuf
Scan response buffer.
pTxReqBuf
uint8_t* pTxReqBuf
Scan request buffer.
rxAdvCback
BbBleAdvComp_t rxAdvCback
Advertising completion callback.
rxAdvPostCback
BbBleAdvPost_t rxAdvPostCback
Advertising completion post processing callback.
rxRspCback
BbBleAdvComp_t rxRspCback
Scan response completion callback.
scanChMap
uint8_t scanChMap
Scan channel map.
txReqCback
BbBleAdvComp_t txReqCback
Scan request completion callback.
txReqLen
uint8_t txReqLen
Scan request buffer length.
BbBleSlvAdvEvent_t
struct BbBleSlvAdvEvent_t
Slave advertising event operation data (BB_BLE_OP_SLV_ADV_EVENT).
Note
BB assumes maximum scan request payload is 39 bytes.
Data Fields
uint8_t * pTxAdvBuf
uint8_t * pRxReqBuf
uint8_t * pTxRspBuf
BbBleTxAdvSetup_t txAdvSetupCback
BbBleAdvComp_t rxReqCback
BbBleAdvPost_t rxReqPostCback
uint8_t txAdvLen
uint8_t txRspLen
uint8_t firstAdvChIdx
uint8_t advChMap
uint32_t reqStartTsUsec
bbBlePduFiltResults_t filtResults
Field Documentation
advChMap
uint8_t advChMap
Advertising channel map.
filtResults
bbBlePduFiltResults_t filtResults
Results from PDU filtering.
firstAdvChIdx
uint8_t firstAdvChIdx
first advertising channel index.
pRxReqBuf
uint8_t* pRxReqBuf
Scan request buffer (must be size of BB_REQ_PDU_MAX_LEN).
pTxAdvBuf
uint8_t* pTxAdvBuf
Advertising buffer.
pTxRspBuf
uint8_t* pTxRspBuf
Scan response buffer.
reqStartTsUsec
uint32_t reqStartTsUsec
Start of request packet timestamp in microseconds.
rxReqCback
BbBleAdvComp_t rxReqCback
Scan/Connect request receive completion callback.
rxReqPostCback
BbBleAdvPost_t rxReqPostCback
Scan/Connect request receive post processing callback.
txAdvLen
uint8_t txAdvLen
Advertising buffer length.
txAdvSetupCback
BbBleTxAdvSetup_t txAdvSetupCback
Adv PDU transmit setup callback.
txRspLen
uint8_t txRspLen
Scan response buffer length.
BbBleMstAuxAdvEvent_t
struct BbBleMstAuxAdvEvent_t
Master auxiliary advertising event operation data (BB_BLE_OP_MST_AUX_ADV_EVENT).
Data Fields
uint8_t * pTxAuxReqBuf
BbBleAdvComp_t rxAuxAdvCback
BbBleAdvComp_t rxAuxRspCback
BbBleRxChain_t rxAuxChainCback
BbBleRxChainPost_t rxAuxChainPostCback
uint8_t txAuxReqLen
uint32_t rxSyncDelayUsec
bool_t isInit
int8_t auxAdvRssi
uint8_t auxRxPhyOptions
uint32_t auxAdvCrc
uint32_t auxStartTsUsec
bbBlePduFiltResults_t filtResults
Field Documentation
auxAdvCrc
uint32_t auxAdvCrc
CRC of advertisement.
auxAdvRssi
int8_t auxAdvRssi
RSSI of advertisement.
auxRxPhyOptions
uint8_t auxRxPhyOptions
Rx PHY options.
auxStartTsUsec
uint32_t auxStartTsUsec
Start of auxiliary advertising packet timestamp in microseconds.
filtResults
bbBlePduFiltResults_t filtResults
Results from PDU filtering.
isInit
bool_t isInit
TRUE if the event is for an initiation.
pTxAuxReqBuf
uint8_t* pTxAuxReqBuf
Scan request buffer.
rxAuxAdvCback
BbBleAdvComp_t rxAuxAdvCback
Advertising completion callback.
rxAuxChainCback
BbBleRxChain_t rxAuxChainCback
Chain completion callback.
rxAuxChainPostCback
BbBleRxChainPost_t rxAuxChainPostCback
Chain completion post callback.
rxAuxRspCback
BbBleAdvComp_t rxAuxRspCback
Scan response completion callback.
rxSyncDelayUsec
uint32_t rxSyncDelayUsec
Receive timeout in microseconds.
txAuxReqLen
uint8_t txAuxReqLen
Scan request buffer length.
BbBleMstPerScanEvent_t
struct BbBleMstPerScanEvent_t
Master periodic scanning event operation data (BB_BLE_OP_MST_PER_SCAN_EVENT).
Data Fields
BbBlePerComp_t rxPerAdvCback
BbBlePerPostComp_t rxPerAdvPostCback
uint32_t rxSyncDelayUsec
uint8_t rxStatus
int8_t perAdvRssi
uint8_t perRxPhyOptions
uint32_t perAdvCrc
uint32_t perStartTsUsec
bool_t perIsFirstTs
Field Documentation
perAdvCrc
uint32_t perAdvCrc
CRC of advertisement.
perAdvRssi
int8_t perAdvRssi
RSSI of advertisement.
perIsFirstTs
bool_t perIsFirstTs
True if it is the first timestamp for a serial of periodic packets.
perRxPhyOptions
uint8_t perRxPhyOptions
Rx PHY options.
perStartTsUsec
uint32_t perStartTsUsec
Start of periodic advertising packet timestamp in microseconds.
rxPerAdvCback
BbBlePerComp_t rxPerAdvCback
Periodic scanning completion callback.
rxPerAdvPostCback
BbBlePerPostComp_t rxPerAdvPostCback
Periodic scanning completion post callback.
rxStatus
uint8_t rxStatus
RX status.
rxSyncDelayUsec
uint32_t rxSyncDelayUsec
Receive timeout in microseconds.
BbBleSlvAuxAdvEvent_t
struct BbBleSlvAuxAdvEvent_t
Slave auxiliary advertising event operation data (BB_BLE_OP_SLV_AUX_ADV_EVENT).
Data Fields
PalBbBleTxBufDesc_t txAuxAdvPdu [2]
uint8_t * pRxAuxReqBuf
PalBbBleTxBufDesc_t txAuxRspPdu [2]
PalBbBleTxBufDesc_t txAuxChainPdu [2]
BbBleAdvComp_t rxAuxReqCback
BbBleAdvPost_t rxAuxReqPostCback
BbBleTxAuxSetup_t txAuxSetupCback
uint8_t auxAdvCh
uint8_t auxRxPhyOptions
uint32_t auxReqStartTsUsec
bbBlePduFiltResults_t filtResults
Field Documentation
auxAdvCh
uint8_t auxAdvCh
Advertising channel map.
auxReqStartTsUsec
uint32_t auxReqStartTsUsec
Start of request packet timestamp in microseconds.
auxRxPhyOptions
uint8_t auxRxPhyOptions
Rx PHY options.
filtResults
bbBlePduFiltResults_t filtResults
Results from PDU filtering.
pRxAuxReqBuf
uint8_t* pRxAuxReqBuf
Auxiliary request buffer (must be size of BB_REQ_PDU_MAX_LEN).
rxAuxReqCback
BbBleAdvComp_t rxAuxReqCback
Auxiliary request receive completion callback.
rxAuxReqPostCback
BbBleAdvPost_t rxAuxReqPostCback
Auxiliary scan/connect request receive post processing callback.
txAuxAdvPdu
PalBbBleTxBufDesc_t txAuxAdvPdu[2]
Advertising PDU descriptor.
txAuxChainPdu
PalBbBleTxBufDesc_t txAuxChainPdu[2]
Auxiliary chain PDU descriptor.
txAuxRspPdu
PalBbBleTxBufDesc_t txAuxRspPdu[2]
Response PDU descriptor.
txAuxSetupCback
BbBleTxAuxSetup_t txAuxSetupCback
Auxiliary chain indication setup callback.
BbBleMstConnEvent_t
struct BbBleMstConnEvent_t
Connection event operation data (BB_BLE_OP_MST_CONN_EVENT).
Data Fields
BbBleExec_t execCback
BbBleCancel_t cancelCback
BbBleTxDataComp_t txDataCback
BbBleRxDataComp_t rxDataCback
int8_t rssi
uint8_t rxPhyOptions
Field Documentation
cancelCback
BbBleCancel_t cancelCback
Cancel callback.
execCback
BbBleExec_t execCback
Execute callback.
rssi
int8_t rssi
RSSI of the last received packet.
rxDataCback
BbBleRxDataComp_t rxDataCback
Receive completion callback.
rxPhyOptions
uint8_t rxPhyOptions
Rx PHY options.
txDataCback
BbBleTxDataComp_t txDataCback
Transmit completion callback.
BbBleSlvConnEvent_t
struct BbBleSlvConnEvent_t
Connection event operation data (BB_BLE_OP_SLV_CONN_EVENT).
Data Fields
uint32_t rxSyncDelayUsec
BbBleExec_t execCback
BbBleCancel_t cancelCback
BbBleTxDataComp_t txDataCback
BbBleRxDataComp_t rxDataCback
uint32_t startTsUsec
int8_t rssi
uint8_t rxPhyOptions
Field Documentation
cancelCback
BbBleCancel_t cancelCback
Cancel callback.
execCback
BbBleExec_t execCback
Execute callback.
rssi
int8_t rssi
RSSI of the last received packet.
rxDataCback
BbBleRxDataComp_t rxDataCback
Receive completion callback.
rxPhyOptions
uint8_t rxPhyOptions
Rx PHY options.
rxSyncDelayUsec
uint32_t rxSyncDelayUsec
Receive timeout in microseconds.
startTsUsec
uint32_t startTsUsec
Start timestamp of the first received packet in microseconds.
txDataCback
BbBleTxDataComp_t txDataCback
Transmit completion callback.
BbBleMstCisEvent_t
struct BbBleMstCisEvent_t
CIS master event operation data (BB_BLE_OP_MST_CIS_EVENT).
Data Fields
BbBleCisCheckContOp_t checkContOpCback
BbBleExec_t execCback
BbBleExec_t contExecCback
BbBleCisPostExec_t postSubEvtCback
BbBleCancel_t cancelCback
BbBleTxDataComp_t txDataCback
BbBleCisRxDataComp_t rxDataCback
int8_t rssi
uint8_t rxPhyOptions
Field Documentation
cancelCback
BbBleCancel_t cancelCback
Cancel callback.
checkContOpCback
BbBleCisCheckContOp_t checkContOpCback
Check whether to continue current operation callback.
contExecCback
BbBleExec_t contExecCback
Continue execute callback.
execCback
BbBleExec_t execCback
Execute callback.
postSubEvtCback
BbBleCisPostExec_t postSubEvtCback
Post subevent callback.
rssi
int8_t rssi
RSSI of the last received packet.
rxDataCback
BbBleCisRxDataComp_t rxDataCback
Receive completion callback.
rxPhyOptions
uint8_t rxPhyOptions
Rx PHY options.
txDataCback
BbBleTxDataComp_t txDataCback
Transmit completion callback.
BbBleSlvCisEvent_t
struct BbBleSlvCisEvent_t
CIS slave event operation data (BB_BLE_OP_SLV_CIS_EVENT).
Data Fields
BbBleCisCheckContOp_t checkContOpCback
BbBleExec_t execCback
BbBleExec_t contExecCback
BbBleCisPostExec_t postSubEvtCback
BbBleCancel_t cancelCback
BbBleTxDataComp_t txDataCback
BbBleRxDataComp_t rxDataCback
bool_t isFirstTs
uint32_t startTsUsec
uint32_t rxTsUsec
int8_t rssi
uint8_t rxPhyOptions
uint32_t rxSyncDelayUsec
Field Documentation
cancelCback
BbBleCancel_t cancelCback
Cancel callback.
checkContOpCback
BbBleCisCheckContOp_t checkContOpCback
Check whether to continue current operation callback.
contExecCback
BbBleExec_t contExecCback
Continue execute callback.
execCback
BbBleExec_t execCback
Execute callback.
isFirstTs
bool_t isFirstTs
True for the first timestamp.
postSubEvtCback
BbBleCisPostExec_t postSubEvtCback
Post subevent callback.
rssi
int8_t rssi
RSSI of the last received packet.
rxDataCback
BbBleRxDataComp_t rxDataCback
Receive completion callback.
rxPhyOptions
uint8_t rxPhyOptions
Rx PHY options.
rxSyncDelayUsec
uint32_t rxSyncDelayUsec
Receive timeout in microseconds.
rxTsUsec
uint32_t rxTsUsec
Timestamp of the received packet. in microseconds
startTsUsec
uint32_t startTsUsec
Start timestamp of the first received packet in microseconds.
txDataCback
BbBleTxDataComp_t txDataCback
Transmit completion callback.
BbBleMstBisEvent_t
struct BbBleMstBisEvent_t
BIS master event operation data (BB_BLE_OP_MST_BIS_EVENT).
Data Fields
uint32_t rxSyncDelayUsec
BbBleExec_t execCback
BbBleRxDataComp_t rxDataCback
uint32_t startTsUsec
Field Documentation
execCback
BbBleExec_t execCback
Execute callback.
rxDataCback
BbBleRxDataComp_t rxDataCback
Recieve completion callback.
rxSyncDelayUsec
uint32_t rxSyncDelayUsec
Receive timeout in microseconds.
startTsUsec
uint32_t startTsUsec
First Rx timestamp.
BbBleSlvBisEvent_t
struct BbBleSlvBisEvent_t
BIS slave event operation data (BB_BLE_OP_SLV_BIS_EVENT).
Data Fields
BbBleExec_t execCback
BbBleTxDataComp_t txDataCback
Field Documentation
execCback
BbBleExec_t execCback
Execute callback.
txDataCback
BbBleTxDataComp_t txDataCback
Transmit completion callback.
BbBleTestTx_t
struct BbBleTestTx_t
Continuous transmit operation data (BB_BLE_OP_TEST_TX).
Data Fields
BbBleTestComp_t testCback
uint8_t * pTxBuf
uint16_t txLen
uint16_t pktInterUsec
Field Documentation
pktInterUsec
uint16_t pktInterUsec
Transmit packet interval.
pTxBuf
uint8_t* pTxBuf
Transmit data buffer.
testCback
BbBleTestComp_t testCback
Test callback.
txLen
uint16_t txLen
Transmit data buffer length.
BbBleTestRx_t
struct BbBleTestRx_t
Continuous receive operation data (BB_BLE_OP_TEST_RX).
Data Fields
uint32_t rxSyncDelayUsec
BbBleTestComp_t testCback
uint8_t * pRxBuf
uint16_t rxLen
Field Documentation
pRxBuf
uint8_t* pRxBuf
Receive data buffer.
rxLen
uint16_t rxLen
Receive data buffer length.
rxSyncDelayUsec
uint32_t rxSyncDelayUsec
Synchronization delay in microseconds.
testCback
BbBleTestComp_t testCback
Test callback.
BbBleData_t
struct BbBleData_t
Bluetooth Low Energy protocol specific operation parameters.
Data Fields
PalBbBleChan_t chan
bbBlePduFiltParams_t pduFilt
union {
BbBleMstAdvEvent_t mstAdv
BbBleSlvAdvEvent_t slvAdv
BbBleMstAuxAdvEvent_t mstAuxAdv
BbBleSlvAuxAdvEvent_t slvAuxAdv
BbBleSlvAuxAdvEvent_t slvPerAdv
BbBleMstConnEvent_t mstConn
BbBleSlvConnEvent_t slvConn
BbBleMstPerScanEvent_t mstPerScan
BbBleMstCisEvent_t mstCis
BbBleSlvCisEvent_t slvCis
BbBleMstBisEvent_t mstBis
BbBleSlvBisEvent_t slvBis
BbBleTestTx_t testTx
BbBleTestRx_t testRx
} op
Field Documentation
chan
PalBbBleChan_t chan
Channelization parameters.
mstAdv
BbBleMstAdvEvent_t mstAdv
Master advertising event data.
mstAuxAdv
BbBleMstAuxAdvEvent_t mstAuxAdv
Master auxiliary advertising event data.
mstBis
BbBleMstBisEvent_t mstBis
Master BIS event data.
mstCis
BbBleMstCisEvent_t mstCis
Master CIS event data.
mstConn
BbBleMstConnEvent_t mstConn
Master connection event data.
mstPerScan
BbBleMstPerScanEvent_t mstPerScan
Master periodic scanning event data.
op
union { ... } op
Operation specific data.
pduFilt
bbBlePduFiltParams_t pduFilt
PDU filter parameters.
slvAdv
BbBleSlvAdvEvent_t slvAdv
Slave advertising event data.
slvAuxAdv
BbBleSlvAuxAdvEvent_t slvAuxAdv
Slave auxiliary advertising event data.
slvBis
BbBleSlvBisEvent_t slvBis
Slave BIS event data.
slvCis
BbBleSlvCisEvent_t slvCis
Slave CIS event data.
slvConn
BbBleSlvConnEvent_t slvConn
Slave connection event data.
slvPerAdv
BbBleSlvAuxAdvEvent_t slvPerAdv
Slave periodic advertising event data.
testRx
BbBleTestRx_t testRx
Receive test data.
testTx
BbBleTestTx_t testTx
Transmit test data.
Enumeration Type Documentation
BbBleOp_t
enum BbBleOp_t
Operation types.
Enumerator
BB_BLE_OP_TEST_TX
Continuous Tx test mode.
BB_BLE_OP_TEST_RX
Continuous Rx test mode.
BB_BLE_OP_MST_ADV_EVENT
Master advertising event.
BB_BLE_OP_SLV_ADV_EVENT
Slave advertising event.
BB_BLE_OP_MST_CONN_EVENT
Master connection event.
BB_BLE_OP_SLV_CONN_EVENT
Slave connection event.
BB_BLE_OP_MST_AUX_ADV_EVENT
Master auxiliary advertising event.
BB_BLE_OP_SLV_AUX_ADV_EVENT
Slave auxiliary advertising event.
BB_BLE_OP_SLV_PER_ADV_EVENT
Slave periodic advertising event.
BB_BLE_OP_MST_PER_SCAN_EVENT
Master periodic scanning event.
BB_BLE_OP_MST_CIS_EVENT
Master CIS event.
BB_BLE_OP_SLV_CIS_EVENT
Slave CIS event.
BB_BLE_OP_MST_BIS_EVENT
Master BIS event.
BB_BLE_OP_SLV_BIS_EVENT
Slave BIS event.
BB_BLE_OP_NUM
Total number of operations.
Function Documentation
BbBleAdvSlaveInit()
void BbBleAdvSlaveInit (void)
Initialize for advertising slave operations.
Update the operation table with advertising slave operations routines.
References BB_BLE_OP_SLV_ADV_EVENT.
BbBleAuxAdvSlaveInit()
void BbBleAuxAdvSlaveInit (void)
Initialize for auxiliary advertising slave operations.
Update the operation table with auxiliary advertising slave operations routines.
Initialize for auxiliary advertising slave operations.
Update the operation table with advertising slave operations routines.
References BB_BLE_OP_SLV_AUX_ADV_EVENT, and BB_BLE_OP_SLV_PER_ADV_EVENT.
BbBleAuxScanMasterInit()
void BbBleAuxScanMasterInit (void)
Initialize for auxiliary scanning master operations.
Update the operation table with auxiliary scanning master operations routines.
Initialize for auxiliary scanning master operations.
Update the operation table with scanning master operations routines.
References BB_BLE_OP_MST_AUX_ADV_EVENT.
BbBleBisMasterInit()
void BbBleBisMasterInit (void)
Initialize for Broadcast isochronous stream master operations.
Update the operation table with CIS master operations routines.
Initialize for Broadcast isochronous stream master operations.
Update the operation table with BIS master operations routines.
References BB_BLE_OP_MST_BIS_EVENT.
BbBleBisRxData()
void BbBleBisRxData (uint8_t * pBuf, uint16_t len, uint32_t nextPduTime, PalBbBleChan_t * pNextChan, bool_t reAcq)
Set receive BIS Data PDU buffer for next receive slot.
Parameters
pBuf Receive data buffer.
len Maximum length of data buffer.
nextPduTime Next PDU time.
pNextChan Next PDU channel.
reAcq Rx train re-acquisition required.
BbBleBisRxDataReAcq()
void BbBleBisRxDataReAcq (uint32_t syncTime, PalBbBleChan_t * pChan)
Receive data re-acquisition.
Parameters
syncTime Due time for the next Rx operation.
pChan Channel parameters.
Update due time for next Rx operation. Called after a missed Rx operation for re-acquisition of the receive train.
Parameters
syncTime Due time for the next Rx operation.
Update due time for next Rx operation. Called after a missed Rx operation for re-acquisition of the receive train.
References bbBleCtrlBlk_t::bbParam, PalBbBleDataParam_t::dueUsec, PalBbBleCancelTifs(), PalBbBleSetChannelParam(), and PalBbBleSetDataParams().
BbBleBisSlaveInit()
void BbBleBisSlaveInit (void)
Initialize for Broadcast isochronous stream slave operations.
Update the operation table with CIS slave operations routines.
Initialize for Broadcast isochronous stream slave operations.
Update the operation table with BIS slave operations routines.
References BB_BLE_OP_SLV_BIS_EVENT.
BbBleBisTxData()
void BbBleBisTxData (PalBbBleTxBufDesc_t descs[], uint8_t cnt, uint32_t nextPduTime, PalBbBleChan_t * pNextChan)
Transmit BIS Data PDU at next transmit slot.
Parameters
descs Array of transmit buffer descriptor.
cnt Number of descriptors.
nextPduTime Next PDU time.
pNextChan Next PDU channel.
References bbBleCtrlBlk_t::evtState, PalBbBleTxData(), PalBbBleTxTifsData(), and BbBleDataPktStats_t::txSetupUsec.
BbBleCisMasterInit()
void BbBleCisMasterInit (void)
Initialize for connected isochronous stream master operations.
Update the operation table with CIS master operations routines.
Initialize for connected isochronous stream master operations.
Update the operation table with CIS master operations routines.
References BB_BLE_OP_MST_CIS_EVENT.
BbBleCisRxData()
void BbBleCisRxData (uint8_t * pBuf, uint16_t len)
Set receive data buffer for next receive slot.
Parameters
pBuf Receive data buffer.
len Maximum length of data buffer.
Note
This function is expected to be called during the call context of BbBleSlvCisEvent_t::rxDataCback callback routine.
BB must always call the BbBleSlvCisEvent_t::rxDataCback callback routine of the currently executing BOD with the given buffer.
Parameters
pBuf Receive data buffer.
len Maximum length of data buffer.
Note
This function is expected to be called during the call context of BbBleMstCisEvent_t::rxDataCback or BbBleSlvCisEvent_t::rxDataCback callback routine.
BB must always call the BbBleMstCisEvent_t::rxDataCback or BbBleSlvCisEvent_t::rxDataCback callback routine of the currently executing BOD with the given buffer.
References BB_BLE_OP_SLV_CIS_EVENT, BbGetCurrentBod(), bbBleCtrlBlk_t::evtState, PalBbBleRxData(), BbOpDesc_t::pBle, bbBleCtrlBlk_t::pRxCisDataBuf, bbBleCtrlBlk_t::rxCisDataLen, and WSF_ASSERT.
BbBleCisSlaveInit()
void BbBleCisSlaveInit (void)
Initialize for connected isochronous stream slave operations.
Update the operation table with CIS slave operations routines.
Update the operation table with onnected isochronous stream slave operations routines.
References BB_BLE_OP_SLV_CIS_EVENT.
BbBleCisTxData()
void BbBleCisTxData (PalBbBleTxBufDesc_t descs[], uint8_t cnt)
Transmit CIS PDU at next transmit slot.
Parameters
descs Array of transmit buffer descriptor.
cnt Number of descriptors.
Note
This function is expected to be called during the call context of BbBleMstCisEvent_t::rxDataCback or BbBleSlvCisEvent_t::rxDataCback callback routine.
Transmit CIS PDU at next transmit slot.
Parameters
descs Array of transmit buffer descriptor.
cnt Number of descriptors.
Note
This function is expected to be called during the call context of BbBleMstCisEvent_t::rxDataCback or BbBleSlvCisEvent_t::rxDataCback callback routine.
References BB_BLE_OP_MST_CIS_EVENT, BbGetCurrentBod(), bbBleCtrlBlk_t::evtState, PalBbBleTxData(), PalBbBleTxTifsData(), BbOpDesc_t::pBle, and BbBleDataPktStats_t::txSetupUsec.
BbBleConnMasterInit()
void BbBleConnMasterInit (void)
Initialize for connectable master operations.
Update the operation table with connectable master operations routines.
References BB_BLE_OP_MST_CONN_EVENT.
BbBleConnSlaveInit()
void BbBleConnSlaveInit (void)
Initialize for connectable slave operations.
Update the operation table with connectable slave operations routines.
References BB_BLE_OP_SLV_CONN_EVENT.
BbBleGetAdvStats()
void BbBleGetAdvStats (BbBleAdvPktStats_t * pStats)
Get advertising packet statistics.
Parameters
pStats Advertising statistics.
BbBleGetAuxAdvStats()
void BbBleGetAuxAdvStats (BbBleAuxAdvPktStats_t * pStats)
Get auxiliary advertising packet statistics.
Parameters
pStats Auxiliary advertising statistics.
BbBleGetAuxScanStats()
void BbBleGetAuxScanStats (BbBleAuxScanPktStats_t * pStats)
Get auxiliary scan packet statistics.
Parameters
pStats Auxiliary scan statistics.
Get auxiliary scan packet statistics.
Parameters
pStats Auxiliary scan statistics.
BbBleGetCisStats()
void BbBleGetCisStats (BbBleDataPktStats_t * pStats)
Get CIS packet statistics.
Parameters
pStats CIS data statistics.
Get CIS packet statistics.
BbBleGetConnStats()
void BbBleGetConnStats (BbBleDataPktStats_t * pStats)
Get connection packet statistics.
Parameters
pStats Connection data statistics.
BbBleGetPduFiltStats()
void BbBleGetPduFiltStats (BbBlePduFiltStats_t * pStats)
Get PDU filter statistics.
Parameters
pStats PDU filter statistics.
BbBleGetPerScanStats()
void BbBleGetPerScanStats (BbBlePerScanPktStats_t * pStats)
Get periodic scan packet statistics.
Parameters
pStats Periodic scan statistics.
Get periodic scan packet statistics.
Parameters
pStats periodic scan statistics.
BbBleGetScanStats()
void BbBleGetScanStats (BbBleScanPktStats_t * pStats)
Get scan packet statistics.
Parameters
pStats Scan statistics.
Get scan packet statistics.
BbBleGetTestStats()
void BbBleGetTestStats (BbBleDataPktStats_t * pStats)
Get test mode packet statistics.
Parameters
pStats Test data statistics.
BbBleInit()
void BbBleInit (void)
Initialize the BLE BB.
Initialize baseband resources.
References BB_PROT_BLE, BB_PROT_BLE_DTM, BB_PROT_PRBS15, BbRegisterProt(), BbRegisterProtLowPower(), bbBleCtrlBlk_t::cancelOpCback, bbBleCtrlBlk_t::execOpCback, bbBleCtrlBlk_t::opCbacks, and PalBbBleInit().
BbBleInitPeriodicList()
uint16_t BbBleInitPeriodicList (uint8_t numEntries, uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize periodic list.
Parameters
numEntries Number of periodic list entries to provide.
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function initializes the periodic list.
Note
This function must be called once before initializing the LL.
Parameters
numEntries Number of periodic list entries to provide.
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function initializes the white list.
Note
This function must be called once before initializing the LL.
References WSF_ASSERT.
BbBleInitResolvingList()
uint16_t BbBleInitResolvingList (uint8_t numEntries, uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize resolving list.
Parameters
numEntries Number of resolving list entries to provide.
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function initializes the resolving list.
Note
This function must be called once before initializing the LL.
References WSF_ASSERT.
BbBleInitWhiteList()
uint16_t BbBleInitWhiteList (uint8_t numEntries, uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize white list.
Parameters
numEntries Number of white list entries to provide.
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function initializes the white list.
Note
This function must be called once before initializing the LL.
BbBlePerScanMasterInit()
void BbBlePerScanMasterInit (void)
Initialize for periodic scanning master operations.
Update the operation table with periodic scanning master operations routines.
References BB_BLE_OP_MST_PER_SCAN_EVENT.
BbBleResetTestStats()
void BbBleResetTestStats (void)
Reset test mode packet statistics.
Returns
None.
BbBleRxData()
void BbBleRxData (uint8_t * pBuf, uint16_t len)
Set receive data buffer for next receive slot.
Parameters
pBuf Receive data buffer.
len Maximum length of data buffer.
Note
This function is expected to be called during the call context of BbBleSlvConnEvent_t::rxDataCback callback routine.
BB must always call the BbSlvConnEvent_t::rxDataCback callback routine of the currently executing BOD with the given buffer.
Parameters
pBuf Receive data buffer.
len Maximum length of data buffer.
Note
This function is expected to be called during the call context of BbBleMstConnEvent_t::rxDataCback or BbBleSlvConnEvent_t::rxDataCback callback routine.
BB must always call the BbBleMstConnEvent_t::rxDataCback or BbBleSlvConnEvent_t::rxDataCback callback routine of the currently executing BOD with the given buffer.
References BB_BLE_OP_SLV_CONN_EVENT, BbGetCurrentBod(), bbBleCtrlBlk_t::evtState, PalBbBleRxData(), BbOpDesc_t::pBle, bbBleCtrlBlk_t::pRxDataBuf, bbBleCtrlBlk_t::rxDataLen, and WSF_ASSERT.
BbBleScanMasterInit()
void BbBleScanMasterInit (void)
Initialize for scanning master operations.
Update the operation table with scanning master operations routines.
References BB_BLE_OP_MST_ADV_EVENT.
BbBleTestInit()
void BbBleTestInit (void)
Initialize for test operations.
Update the operation table with test operations routines.
Initialize for test operations.
Update the operation table with direct test mode operations routines.
References BB_BLE_OP_TEST_RX, and BB_BLE_OP_TEST_TX.
BbBleTxData()
void BbBleTxData (PalBbBleTxBufDesc_t descs[], uint8_t cnt)
Transmit data PDU at next transmit slot.
Parameters
descs Array of transmit buffer descriptor.
cnt Number of descriptors.
Note
This function is expected to be called during the call context of BbBleSlvConnEvent_t::rxDataCback callback routine.
Parameters
descs Array of transmit buffer descriptor.
cnt Number of descriptors.
Note
This function is expected to be called during the call context of BbBleMstConnEvent_t::rxDataCback or BbBleSlvConnEvent_t::rxDataCback callback routine.
References BB_BLE_OP_MST_CONN_EVENT, BbGetCurrentBod(), bbSnifferCtx_t::enabled, bbBleCtrlBlk_t::evtState, PalBbBleTxData(), PalBbBleTxTifsData(), BbOpDesc_t::pBle, PalBbBleTxBufDesc_t::pBuf, bbSnifferCtx_t::txBuf, and BbBleDataPktStats_t::txSetupUsec.