Cordio: Control interface
Control interface
Baseband (BB) API
Functions
void BbStart (PalBbProt_t protId)
void BbStop (PalBbProt_t protId)
void BbExecuteBod (BbOpDesc_t *pBod)
void BbCancelBod (void)
BbOpDesc_t * BbGetCurrentBod (void)
void BbSetBodTerminateFlag (void)
bool_t BbGetBodTerminateFlag (void)
void BbTerminateBod (void)
uint16_t BbGetClockAccuracy (void)
uint32_t BbGetBbTimerBoundaryUs (void)
uint16_t BbGetSchSetupDelayUs (void)
uint16_t BbGetRfSetupDelayUs (void)
uint32_t BbAdjustTime (uint32_t dueUsec)
uint32_t BbGetTargetTimeDelta (uint32_t targetUsec, uint32_t refUsec)
uint8_t BbGetActiveProtocol (void)
Detailed Description
Function Documentation
BbAdjustTime()
uint32_t BbAdjustTime (uint32_t dueUsec)
Adjust new time tick with wraparound.
Parameters
dueUsec Time tick without wraparound in microseconds.
Returns
Time tick with wraparound.
Note
dueUsec can only be at most +/-(BbTimerBoundaryUs/2) out of range.
References BbRtCfg_t::BbTimerBoundaryUs, and WSF_ASSERT.
BbExecuteBod()
void BbExecuteBod (BbOpDesc_t * pBod)
Execute BOD.
Parameters
pBod Pointer to the BOD to execute.
Execute the protocol specific BOD handler.
References BB_PROT_NUM, BbCtrlBlk_t::pOpInProgress, BbOpDesc_t::protId, BbCtrlBlk_t::termBod, and WSF_ASSERT.
BbGetActiveProtocol()
uint8_t BbGetActiveProtocol (void)
Returns the ID of the active protocol.
Returns
Protocol operation in progress.
References BbCtrlBlk_t::protIdStarted.
BbGetBbTimerBoundaryUs()
uint32_t BbGetBbTimerBoundaryUs (void)
Get BB timer boundary before wraparound.
Returns
Time boundary in microseconds.
References BbRtCfg_t::BbTimerBoundaryUs.
BbGetBodTerminateFlag()
bool_t BbGetBodTerminateFlag (void)
Get termination state of current executing BOD.
Returns
TRUE if termination flag set, FALSE otherwise.
BbGetClockAccuracy()
uint16_t BbGetClockAccuracy (void)
Get BB clock accuracy.
Returns
Clock accuracy in part per million.
Returns the current BB clock accuracy.
References BbRtCfg_t::clkPpm.
BbGetCurrentBod()
BbOpDesc_t* BbGetCurrentBod (void)
Get the currently-executing BOD.
Returns
Currently-executing BOD.
References BbCtrlBlk_t::pOpInProgress.
BbGetRfSetupDelayUs()
uint16_t BbGetRfSetupDelayUs (void)
Get RF setup delay.
Returns
RF setup delay in microseconds.
Returns the RF setup delay.
References BbRtCfg_t::rfSetupDelayUs.
BbGetSchSetupDelayUs()
uint16_t BbGetSchSetupDelayUs (void)
Get scheduler setup delay.
Returns
Scheduler setup delay in microseconds.
Returns the scheduler setup delay.
References BbRtCfg_t::schSetupDelayUs.
BbGetTargetTimeDelta()
uint32_t BbGetTargetTimeDelta (uint32_t targetUsec, uint32_t refUsec)
Get Delta between target and reference time. Only valid if target time is in the future.
Parameters
targetUsec Target time in microseconds.
refUsec Reference time in microseconds.
Returns
Positive number in microseconds if target time is in the future. Zero if target time is in the past or same compared with reference time.
Note
Caller has to make sure target time and reference time are within SCH_MAX_SPAN.
References BbAdjustTime(), and BbRtCfg_t::BbTimerBoundaryUs.
BbSetBodTerminateFlag()
void BbSetBodTerminateFlag (void)
Set termination flag of current executing BOD.
Note
This function is expected to be called during the execution context of the current executing BOD, typically in the related ISRs. In the end, termination flag will help to decide if BbTerminateBod() should be called.
References BbCtrlBlk_t::pOpInProgress, and BbCtrlBlk_t::termBod.
BbStart()
void BbStart (PalBbProt_t protId)
Start BB processing of given protocol.
Parameters
protId Protocol ID.
Enable BB and start processing the list of BODs. This routine may be called several times, if a protocol layers has several simultaneously-enabled operations. However, BbStop() must be called an equal number of time to disable the baseband.
References BB_PROT_NUM, PalBbEnable(), BbCtrlBlk_t::prot, BbCtrlBlk_t::protStarted, BbCtrlBlk_t::startCnt, BbCtrlBlk_t::stopProtCback, and WSF_ASSERT.
BbStop()
void BbStop (PalBbProt_t protId)
Stop BB processing of given protocol.
Parameters
protId Protocol ID.
Disable BB processing of BODs.
Note
For any particular protocol, calls to BbStart() and BbStop() must be balanced to ensure that the hardware is disabled if and only if appropriate.
References BB_PROT_NUM, PalBbDisable(), BbCtrlBlk_t::prot, BbCtrlBlk_t::protIdStarted, BbCtrlBlk_t::protStarted, BbCtrlBlk_t::startCnt, and WSF_ASSERT.
BbTerminateBod()
void BbTerminateBod (void)
Terminate a BOD immediately.
Note
This function is expected to be called during the execution context of the current executing BOD, typically in the related ISRs.
References BbCtrlBlk_t::bodCompCback, BbCtrlBlk_t::lowPowerOpCback, BbCtrlBlk_t::pOpInProgress, BbCtrlBlk_t::prot, BbOpDesc_t::protId, BbCtrlBlk_t::termBod, and WSF_ASSERT.