Cordio: Mesh Access Layer API
Mesh Access Layer API
Data Structures
struct meshAccCoreMdl_t
Typedefs
typedef meshAddress_t(* meshAccFriendAddrFromSubnetCback_t) (uint16_t netKeyIndex)
typedef void(* meshAccCoreMdlMsgRecvCback_t) (uint8_t opcodeIdx, uint8_t *pMsgParam, uint16_t msgParamLen, meshAddress_t src, meshElementId_t elemId, uint8_t ttl, uint16_t netKeyIndex)
Functions
uint32_t MeshAccGetRequiredMemory (void)
void MeshAccInit (void)
void MeshAccRegisterLpn (meshAccFriendAddrFromSubnetCback_t cback)
void MeshAccRegisterCoreModel (meshAccCoreMdl_t *pCoreMdl)
void MeshAccGetNumCoreModels (uint8_t elemId, uint8_t *pOutNumSig, uint8_t *pOutNumVendor)
uint8_t MeshAccGetCoreSigModelsIds (uint8_t elemId, meshSigModelId_t *pOutSigMdlIdArray, uint8_t arraySize)
meshSendMessage_t * MeshAccAllocMsg (const meshMsgInfo_t *pMsgInfo, const uint8_t *pMsgParam, uint16_t msgParamLen, uint16_t netKeyIndex)
void MeshAccSendMessage (const meshMsgInfo_t *pMsgInfo, const uint8_t *pMsgParam, uint16_t msgParamLen, uint16_t netKeyIndex, uint32_t rndDelayMsMin, uint32_t rndDelayMsMax)
void MeshAccPublishMessage (const meshPubMsgInfo_t *pPubMsgInfo, const uint8_t *pMsgParam, uint16_t msgParamLen)
void MeshAccPeriodPubChanged (meshElementId_t elemId, meshModelId_t *pModelId)
Detailed Description
Data Structure Documentation
meshAccCoreMdl_t
struct meshAccCoreMdl_t
Structure containing Access Layer identification of models implemented by the Core stack.
Data Fields
void * pNext
meshAccCoreMdlMsgRecvCback_t msgRecvCback
const meshMsgOpcode_t * pOpcodeArray
uint8_t opcodeArrayLen
meshElementId_t elemId
meshModelId_t mdlId
Field Documentation
elemId
meshElementId_t elemId
Identifier of the element containing the model.
mdlId
meshModelId_t mdlId
Model identifier.
msgRecvCback
meshAccCoreMdlMsgRecvCback_t msgRecvCback
Core model message received callback.
opcodeArrayLen
uint8_t opcodeArrayLen
Length of the opcode array.
pNext
void* pNext
Pointer to next core model.
pOpcodeArray
const meshMsgOpcode_t* pOpcodeArray
Pointer to opcode array for received messages.
Typedef Documentation
meshAccCoreMdlMsgRecvCback_t
typedef void(* meshAccCoreMdlMsgRecvCback_t) (uint8_t opcodeIdx, uint8_t *pMsgParam, uint16_t msgParamLen, meshAddress_t src, meshElementId_t elemId, uint8_t ttl, uint16_t netKeyIndex)
Callback definition for receiving Mesh messages for core models working with Device Key.
Parameters
[in] opcodeIdx Index of the opcode in the receive opcodes array registered.
[in] pMsgParam Pointer to raw message parameters.
[in] msgParamLen Length of the message parameters array.
[in] src Address of the element originating the request.
[in] elemId Destination element identifier.
[in] ttl TTL of the received message.
[in] netKeyIndex Global identifier for the Network Key of the subnet on which the message is received
Returns
None.
meshAccFriendAddrFromSubnetCback_t
typedef meshAddress_t(* meshAccFriendAddrFromSubnetCback_t) (uint16_t netKeyIndex)
Callback definition for getting the Friend address for a subnet.
Parameters
[in] netKeyIndex Global identifier for the Network Key of the subnet.
Returns
Friend address or MESH_ADDR_TYPE_UNASSIGNED if friendship is not established.
Function Documentation
MeshAccAllocMsg()
meshSendMessage_t* MeshAccAllocMsg (const meshMsgInfo_t * pMsgInfo, const uint8_t * pMsgParam, uint16_t msgParamLen, uint16_t netKeyIndex)
Allocate and build an WSF message for delaying or sending an Access message.
Parameters
[in] pMsgInfo Pointer to a Mesh message information structure. See ::meshMsgId_t
[in] pMsgParam Pointer to a Mesh message parameter list.
[in] msgParamLen Length of the message parameter list.
[in] netKeyIndex Global Network Key identifier.
Returns
Pointer to meshSendMessage_t.
References MESH_LABEL_UUID_SIZE, meshSendMessage_t::msgInfo, meshSendMessage_t::msgParamLen, meshSendMessage_t::netKeyIndex, meshMsgInfo_t::pDstLabelUuid, meshSendMessage_t::pMsgParam, and WsfMsgAlloc().
MeshAccGetCoreSigModelsIds()
uint8_t MeshAccGetCoreSigModelsIds (uint8_t elemId, meshSigModelId_t * pOutSigMdlIdArray, uint8_t arraySize)
Gets core SIG models identifiers of models contained by an element.
Parameters
[in] elemId Element identifier.
[out] pOutMdlIdArray Pointer to buffer store SIG model identifiers of core models.
[in] arraySize Size of the array provided.
Returns
Number of core SIG model identifiers contained by the element.
References meshAccCb_t::coreMdlQueue, meshAccCoreMdl_t::elemId, meshModelId_t::isSigModel, meshAccCoreMdl_t::mdlId, meshModelId_t::modelId, meshAccCoreMdl_t::pNext, modelId_t::sigModelId, and WSF_ASSERT.
MeshAccGetNumCoreModels()
void MeshAccGetNumCoreModels (uint8_t elemId, uint8_t * pOutNumSig, uint8_t * pOutNumVendor)
Gets number of core models contained by an element.
Parameters
[in] elemId Element identifier.
[out] pOutNumSig Pointer to memory where number of SIG models is stored.
[out] pOutNumVendor Pointer to memory where number of Vendor models is stored.
Returns
None.
References meshAccCb_t::coreMdlQueue, meshAccCoreMdl_t::elemId, meshModelId_t::isSigModel, meshAccCoreMdl_t::mdlId, meshAccCoreMdl_t::pNext, and WSF_ASSERT.
MeshAccGetRequiredMemory()
uint32_t MeshAccGetRequiredMemory (void)
Gets memory required for configuration.
Returns
Configuration memory required or MESH_MEM_REQ_INVALID_CFG on error.
References meshCb_t::handlerId, meshModelId_t::isSigModel, meshCb_t::memBuffSize, MESH_UTILS_ALIGN, meshModelId_t::modelId, meshElement_t::numSigModels, meshElement_t::numVendorModels, meshConfig_t::pElementArray, meshCb_t::pMemBuff, pMeshConfig, meshAccCb_t::ppChangedCback, meshAccCb_t::ppWsfMsgCback, modelId_t::sigModelId, modelId_t::vendorModelId, WSF_ASSERT, WSF_QUEUE_INIT, and WsfQueueEnq().
MeshAccInit()
void MeshAccInit (void)
Initializes the Mesh Access layer.
Returns
None.
References meshCb_t::accMsgCback, meshAccCb_t::coreMdlQueue, meshAccCb_t::friendAddrFromSubnetCback, meshAccCb_t::msgSendQueue, meshAccCb_t::ppChangedCback, meshAccCb_t::ppWsfMsgCback, meshAccCb_t::pubRetransQueue, WSF_QUEUE_INIT, WsfBufFree(), WsfQueueDeq(), and WsfQueueEmpty().
MeshAccPeriodPubChanged()
void MeshAccPeriodPubChanged (meshElementId_t elemId, meshModelId_t * pModelId)
Informs the Access Layer of the periodic publishing value of a model instance.
Parameters
[in] elemId Element identifier.
[in] pModelId Pointer to a model identifier.
Returns
None.
References meshAccCb_t::ppChangedCback.
MeshAccPublishMessage()
void MeshAccPublishMessage (const meshPubMsgInfo_t * pPubMsgInfo, const uint8_t * pMsgParam, uint16_t msgParamLen)
Publishes a Mesh Message based on internal Model Publication State configuration.
Parameters
[in] pPubMsgInfo Pointer to a published Mesh message information structure.
[in] pMsgParam Pointer to a Mesh message parameter list.
[in] msgParamLen Length of the message parameter list.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, meshPubMsgInfo_t::elementId, meshCb_t::handlerId, meshModelId_t::isSigModel, MESH_ADDR_TYPE_UNASSIGNED, MESH_IS_ADDR_UNICAST, MESH_OPCODE_IS_VENDOR, MESH_OPCODE_SIZE, MESH_PUBLISH_MASTER_SECURITY, MESH_SUCCESS, MESH_TTL_IS_VALID, MeshLocalCfgGetBoundNetKeyIndex(), MeshLocalCfgGetElementIdFromAddr(), MeshLocalCfgGetPublishAddress(), MeshLocalCfgGetPublishAppKeyIndex(), MeshLocalCfgGetPublishFriendshipCredFlag(), MeshLocalCfgGetPublishRetransCount(), MeshLocalCfgGetPublishRetransIntvlSteps(), MeshLocalCfgGetPublishTtl(), MeshLocalCfgValidateModelToAppKeyBind(), meshModelId_t::modelId, meshMsgInfo_t::modelId, meshPubMsgInfo_t::modelId, meshMsgInfo_t::opcode, meshPubMsgInfo_t::opcode, meshMsgInfo_t::pDstLabelUuid, meshAccCb_t::pubRetransQueue, modelId_t::sigModelId, meshAccCb_t::tmrUidGen, meshMsgInfo_t::ttl, modelId_t::vendorModelId, WsfBufAlloc(), WsfQueueEnq(), and WsfTimerStartMs().
MeshAccRegisterCoreModel()
void MeshAccRegisterCoreModel (meshAccCoreMdl_t * pCoreMdl)
Registers the Access Layer information to multiplex received messages to core models.
Parameters
[in] pCoreMdl Pointer to linked list element containing information used by the Access Layer to multiplex messages on the Rx data path.
Returns
None.
Parameters
[in] pCoreMdl Pointer to linked list element containing information used by the Access Layer to multiplex messages on the RX data path.
Returns
None.
References meshAccCb_t::coreMdlQueue, meshAccCoreMdl_t::msgRecvCback, meshAccCoreMdl_t::pOpcodeArray, WSF_ASSERT, and WsfQueueEnq().
MeshAccRegisterLpn()
void MeshAccRegisterLpn (meshAccFriendAddrFromSubnetCback_t cback)
Registers callback for LPN.
Parameters
[in] cback Callback to get the Friend address from subnet.
Returns
None.
References meshAccCb_t::friendAddrFromSubnetCback.
MeshAccSendMessage()
void MeshAccSendMessage (const meshMsgInfo_t * pMsgInfo, const uint8_t * pMsgParam, uint16_t msgParamLen, uint16_t netKeyIndex, uint32_t rndDelayMsMin, uint32_t rndDelayMsMax)
Sends a Mesh message to a destination address with a random delay.
Parameters
[in] pMsgInfo Pointer to a Mesh message information structure. See ::meshMsgId_t
[in] pMsgParam Pointer to a Mesh message parameter list.
[in] msgParamLen Length of the message parameter list.
[in] netKeyIndex Global Network Key identifier.
[in] rndDelayMsMin Minimum value for random send delay in ms. 0 for instant send.
[in] rndDelayMsMax Maximum value for random send delay in ms. 0 for instant send.
Returns
None.
Remarks
pMsgInfo->appKeyIndex can also be MESH_APPKEY_INDEX_LOCAL_DEV_KEY or MESH_APPKEY_INDEX_REMOTE_DEV_KEY for local or remote Device keys.
References meshSendMessage_t::delayTmr, wsfMsgHdr_t::event, wsfTimer_t::handlerId, meshCb_t::handlerId, MESH_PUBLISH_MASTER_SECURITY, MeshAccAllocMsg(), wsfTimer_t::msg, meshSendMessage_t::msgInfo, meshAccCb_t::msgSendQueue, wsfMsgHdr_t::param, SecRand(), WsfMsgEnq(), and WsfTimerStartMs().