Cordio: GATT_PROFILE
GATT_PROFILE
Enumerations
enum
Functions
void GattDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t GattValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
uint8_t GattReadCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, attsAttr_t *pAttr)
uint8_t GattWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
void GattSetSvcChangedIdx (uint8_t idx)
void GattSendServiceChangedInd (dmConnId_t connId, uint16_t start, uint16_t end)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumeration of handle indexes of characteristics to be discovered.
Enumerator
GATT_SC_HDL_IDX
Service changed.
GATT_SC_CCC_HDL_IDX
Service changed client characteristic configuration descriptor.
GATT_CSF_HDL_IDX
Client Supported Features.
GATT_HDL_LIST_LEN
Handle list length.
Function Documentation
GattDiscover()
void GattDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for GATT service. Note that pHdlList must point to an array of handles of length GATT_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for GATT service. Note that pHdlList must point to an array of handles of length GATT_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attGattSvcUuid, and GATT_HDL_LIST_LEN.
GattReadCback()
uint8_t GattReadCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, attsAttr_t * pAttr)
ATTS read callback for gatt service.
Parameters
connId Connection identifier.
handle ATT handle.
operation Operation selected.
offset Offset to begin read from.
pAttr Attribute to read from.
Returns
ATT status.
References ATT_CSF_LEN, ATT_SUCCESS, AttsCsfGetFeatures(), GATT_CSF_HDL, and attsAttr_t::pValue.
GattSendServiceChangedInd()
void GattSendServiceChangedInd (dmConnId_t connId, uint16_t start, uint16_t end)
Send Service Change Indications to the specified connections if they are configured to do so.
Parameters
connId DM Connection identifier or DM_CONN_ID_NONE to send to all connections.
start start handle for service changed value.
end end handle for service changed value.
Returns
None.
References AttsCccEnabled(), AttsHandleValueInd(), DM_CONN_ID_NONE, DM_CONN_MAX, GATT_SC_HDL, and UINT16_TO_BSTREAM.
GattSetSvcChangedIdx()
void GattSetSvcChangedIdx (uint8_t idx)
Set Index of the Service Changed CCCD in the ATT Server.
Parameters
idx Index of the Service Changed CCCD in the ATT Server.
Returns
None.
GattValueUpdate()
uint8_t GattValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length GATT_HDL_LIST_LEN. If the attribute handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length GATT_HDL_LIST_LEN. If the attribute handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References AppDiscServiceChanged(), ATT_ERR_NOT_FOUND, ATT_SUCCESS, GATT_SC_HDL_IDX, and attEvt_t::handle.
GattWriteCback()
uint8_t GattWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
ATTS write callback for gatt service.
Parameters
connId Connection identifier.
handle ATT handle.
operation Operation selected.
offset Offset to begin write.
len Length of write.
pValue Pointer to buffer to write.
pAttr Attribute to write to.
Returns
ATT status.
References ATT_SUCCESS, AttsCsfWriteFeatures(), and GATT_CSF_HDL.