Cordio: APP_FRAMEWORK_DB_API
APP_FRAMEWORK_DB_API
Modules
APP_FRAMEWORK_API
Macros
#define APP_DB_HDL_NONE NULL
Typedefs
typedef void * appDbHdl_t
App Configuration
Build-time configuration constants
#define APP_DB_NUM_RECS 3
#define APP_DB_NUM_CCCD 10
#define APP_DB_HDL_LIST_LEN 21
App Database
Store known device and security information.
void AppDbInit (void)
appDbHdl_t AppDbNewRecord (uint8_t addrType, uint8_t *pAddr)
appDbHdl_t AppDbGetNextRecord (appDbHdl_t hdl)
void AppDbDeleteRecord (appDbHdl_t hdl)
void AppDbValidateRecord (appDbHdl_t hdl, uint8_t keyMask)
void AppDbCheckValidRecord (appDbHdl_t hdl)
bool_t AppDbRecordInUse (appDbHdl_t hdl)
bool_t AppDbCheckBonded (void)
void AppDbDeleteAllRecords (void)
appDbHdl_t AppDbFindByAddr (uint8_t addrType, uint8_t *pAddr)
appDbHdl_t AppDbFindByLtkReq (uint16_t encDiversifier, uint8_t *pRandNum)
appDbHdl_t AppDbGetHdl (dmConnId_t connId)
dmSecKey_t * AppDbGetKey (appDbHdl_t hdl, uint8_t type, uint8_t *pSecLevel)
void AppDbSetKey (appDbHdl_t hdl, dmSecKeyIndEvt_t *pKey)
uint16_t * AppDbGetCccTbl (appDbHdl_t hdl)
void AppDbSetCccTblValue (appDbHdl_t hdl, uint16_t idx, uint16_t value)
void AppDbGetCsfRecord (appDbHdl_t hdl, uint8_t *pIsChangeAware, uint8_t **pCsf)
void AppDbSetCsfRecord (appDbHdl_t hdl, uint8_t changeAwareState, uint8_t *pCsf)
void AppDbSetClientChangeAwareState (appDbHdl_t hdl, uint8_t state)
uint8_t * AppDbGetDbHash (void)
void AppDbSetDbHash (uint8_t *pHash)
uint8_t * AppDbGetPeerDbHash (appDbHdl_t hdl)
void AppDbSetPeerDbHash (appDbHdl_t hdl, uint8_t *dbHash)
bool_t AppDbIsCacheCheckedByHash (appDbHdl_t hdl)
void AppDbSetCacheByHash (appDbHdl_t hdl, bool_t cacheByHash)
uint8_t AppDbGetDiscStatus (appDbHdl_t hdl)
void AppDbSetDiscStatus (appDbHdl_t hdl, uint8_t status)
uint16_t * AppDbGetHdlList (appDbHdl_t hdl)
void AppDbSetHdlList (appDbHdl_t hdl, uint16_t *pHdlList)
char * AppDbGetDevName (uint8_t *pLen)
void AppDbSetDevName (uint8_t len, char *pStr)
bool_t AppDbGetPeerAddrRes (appDbHdl_t hdl)
void AppDbSetPeerAddrRes (appDbHdl_t hdl, uint8_t addrRes)
uint32_t AppDbGetPeerSignCounter (appDbHdl_t hdl)
void AppDbSetPeerSignCounter (appDbHdl_t hdl, uint32_t signCounter)
bool_t AppDbGetPeerAddedToRl (appDbHdl_t hdl)
void AppDbSetPeerAddedToRl (appDbHdl_t hdl, bool_t peerAddedToRl)
bool_t AppDbGetPeerRpao (appDbHdl_t hdl)
void AppDbSetPeerRpao (appDbHdl_t hdl, bool_t peerRpao)
void AppDbNvmStorePeerRpao (appDbHdl_t hdl)
void AppDbNvmStoreCccTbl (appDbHdl_t hdl)
void AppDbNvmStoreHdlList (appDbHdl_t hdl)
void AppDbNvmStorePeerSignCounter (appDbHdl_t hdl)
void AppDbNvmStorePeerAddrRes (appDbHdl_t hdl)
void AppDbNvmStoreChangeAwareState (appDbHdl_t hdl)
void AppDbNvmStoreCsfRecord (appDbHdl_t hdl)
void AppDbNvmStoreCacheByHash (appDbHdl_t hdl)
void AppDbNvmStoreDbHash (appDbHdl_t hdl)
void AppDbNvmStoreBond (appDbHdl_t hdl)
void AppDbNvmReadAll (void)
void AppDbNvmDeleteRec (appDbHdl_t hdl)
void AppDbNvmDeleteAll (void)
Detailed Description
Function Documentation
AppDbCheckBonded()
bool_t AppDbCheckBonded (void)
Check if there is a stored bond with any device.
Returns
TRUE if a bonded device is found, FALSE otherwise.
Parameters
hdl Database record handle.
Returns
TRUE if a bonded device is found, FALSE otherwise.
AppDbCheckValidRecord()
void AppDbCheckValidRecord (appDbHdl_t hdl)
Check if a record has been validated. If it has not, delete it. This function is typically called when the connection is closed.
Parameters
hdl Database record handle.
Returns
None.
AppDbDeleteAllRecords()
void AppDbDeleteAllRecords (void)
Delete all database records.
Returns
None.
References APP_DB_NUM_RECS.
AppDbDeleteRecord()
void AppDbDeleteRecord (appDbHdl_t hdl)
Delete a new device database record.
Parameters
hdl Database record handle.
Returns
None.
AppDbFindByAddr()
appDbHdl_t AppDbFindByAddr (uint8_t addrType, uint8_t * pAddr)
Find a device database record by peer address.
Parameters
addrType Address type.
pAddr Peer device address.
Returns
Database record handle or APP_DB_HDL_NONE if not found.
References APP_DB_HDL_NONE, APP_DB_NUM_RECS, BdaCmp(), and DmHostAddrType().
AppDbFindByLtkReq()
appDbHdl_t AppDbFindByLtkReq (uint16_t encDiversifier, uint8_t * pRandNum)
Find a device database record from data in an LTK request.
Parameters
encDiversifier Encryption diversifier associated with key.
pRandNum Pointer to random number associated with key.
Returns
Database record handle or APP_DB_HDL_NONE if not found.
Find a device database record from data in an LTK request.
Parameters
encDiversifier Encryption diversifier associated with key.
pRandNum Pointer to random number associated with key.
Returns
Database record handle or APP_DB_HDL_NONE if not found.
References APP_DB_HDL_NONE, APP_DB_NUM_RECS, and SMP_RAND8_LEN.
AppDbGetCccTbl()
uint16_t* AppDbGetCccTbl (appDbHdl_t hdl)
Get the client characteristic configuration descriptor table.
Parameters
hdl Database record handle.
Returns
Pointer to client characteristic configuration descriptor table.
AppDbGetCsfRecord()
void AppDbGetCsfRecord (appDbHdl_t hdl, uint8_t * pChangeAwareState, uint8_t ** pCsf)
Get the change aware state and client supported features record.
Parameters
hdl Database record handle.
pIsChangeAware Pointer to peer client's change aware status to a change in the database.
pCsf Pointer to csf value pointer.
Returns
None.
Get the change aware state and client supported features record.
Parameters
hdl Database record handle.
pChangeAwareState Pointer to peer client's change aware status to a change in the database.
pCsf Pointer to csf value pointer.
Returns
None.
AppDbGetDbHash()
uint8_t* AppDbGetDbHash (void)
Get device's GATT database hash.
Returns
Pointer to database hash.
AppDbGetDevName()
char* AppDbGetDevName (uint8_t * pLen)
Get the device name.
Parameters
pLen Returned device name length.
Returns
Pointer to UTF-8 string containing the device name or NULL if not set.
Parameters
pLen Returned device name length.
Returns
Pointer to UTF-8 string containing device name or NULL if not set.
AppDbGetDiscStatus()
uint8_t AppDbGetDiscStatus (appDbHdl_t hdl)
Get the discovery status.
Parameters
hdl Database record handle.
Returns
Discovery status.
AppDbGetHdl()
appDbHdl_t AppDbGetHdl (dmConnId_t connId)
Get the device database record handle associated with an open connection.
Parameters
connId Connection identifier.
Returns
Database record handle or APP_DB_HDL_NONE.
AppDbGetHdlList()
uint16_t* AppDbGetHdlList (appDbHdl_t hdl)
Get the cached handle list.
Parameters
hdl Database record handle.
Returns
Pointer to handle list.
AppDbGetKey()
dmSecKey_t* AppDbGetKey (appDbHdl_t hdl, uint8_t type, uint8_t * pSecLevel)
Get a key from a device database record.
Parameters
hdl Database record handle.
type Type of key to get.
pSecLevel If the key is valid, returns the security level of the key.
Returns
Pointer to the key if the key is valid or NULL if not valid.
Parameters
hdl Database record handle.
type Type of key to get.
pSecLevel If the key is valid, the security level of the key.
Returns
Pointer to key if key is valid or NULL if not valid.
References DM_KEY_CSRK, DM_KEY_IRK, DM_KEY_LOCAL_LTK, and DM_KEY_PEER_LTK.
AppDbGetNextRecord()
appDbHdl_t AppDbGetNextRecord (appDbHdl_t hdl)
Get next device database record for a given database record. For the first database record, the function should be called with 'hdl' set to 'APP_DB_HDL_NONE'.
Parameters
hdl Database record handle.
Returns
Next database record handle found. APP_DB_HDL_NONE, otherwise.
Get next device database record for a given database record. For the first database record, the function should be called with 'hdl' set to 'APP_DB_HDL_NONE'.
Parameters
hdl Database record handle.
Returns
Next record handle found. APP_DB_HDL_NONE, otherwise.
References APP_DB_HDL_NONE, APP_DB_NUM_RECS, and AppDbRecordInUse().
AppDbGetPeerAddedToRl()
bool_t AppDbGetPeerAddedToRl (appDbHdl_t hdl)
Get the peer device added to resolving list flag value.
Parameters
hdl Database record handle.
Returns
TRUE if peer device's been added to resolving list. FALSE, otherwise.
AppDbGetPeerAddrRes()
bool_t AppDbGetPeerAddrRes (appDbHdl_t hdl)
Get address resolution attribute value read from a peer device.
Parameters
hdl Database record handle.
Returns
TRUE if address resolution is supported in peer device. FALSE, otherwise.
AppDbGetPeerDbHash()
uint8_t* AppDbGetPeerDbHash (appDbHdl_t hdl)
Get the peer's database hash.
Parameters
hdl Database record handle.
Returns
Pointer to database hash.
AppDbGetPeerRpao()
bool_t AppDbGetPeerRpao (appDbHdl_t hdl)
Get resolvable private address only attribute present flag for a peer device.
Parameters
hdl Database record handle.
Returns
TRUE if RPA Only attribute is present on peer device. FALSE, otherwise.
Get resolvable private address only attribute present flag for a peer device.
Parameters
hdl Database record handle.
Returns
TRUE if RPA Only attribute is present on peer device. FALSE, otherwise.
AppDbGetPeerSignCounter()
uint32_t AppDbGetPeerSignCounter (appDbHdl_t hdl)
Get sign counter for a peer device.
Parameters
hdl Database record handle.
Returns
Sign counter for peer device.
AppDbInit()
void AppDbInit (void)
Initialize the device database.
Returns
None.
AppDbIsCacheCheckedByHash()
bool_t AppDbIsCacheCheckedByHash (appDbHdl_t hdl)
Check if cached handles' validity are ascertained by reading the peer's database hash.
Parameters
hdl Database record handle.
Returns
TRUE if peer's database hash must be read to verify handles have not changed.
Check if cached handles' validity are ascertained by reading the peer's database hash.
Parameters
hdl Database record handle.
Returns
TRUE if peer's database hash must be read to verify handles have not changed.
AppDbNewRecord()
appDbHdl_t AppDbNewRecord (uint8_t addrType, uint8_t * pAddr)
Create a new device database record.
Parameters
addrType Address type.
pAddr Peer device address.
Returns
Database record handle.
References APP_DB_NUM_RECS.
AppDbNvmDeleteAll()
void AppDbNvmDeleteAll (void)
Delete all device database records from NVM.
Returns
None.
References APP_DB_NUM_RECS, and WsfNvmEraseData().
AppDbNvmDeleteRec()
void AppDbNvmDeleteRec (appDbHdl_t hdl)
Delete the device database record with the given handle from NVM.
Parameters
hdl Record handle.
Returns
None.
References WsfNvmEraseData().
AppDbNvmReadAll()
void AppDbNvmReadAll (void)
Read all device database records from NVM.
Returns
None.
References APP_DB_NUM_RECS.
AppDbNvmStoreBond()
void AppDbNvmStoreBond (appDbHdl_t hdl)
Store bonding information for device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
AppDbNvmStoreCacheByHash()
void AppDbNvmStoreCacheByHash (appDbHdl_t hdl)
Store the method of validating the cache handle for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References WsfNvmWriteData().
AppDbNvmStoreCccTbl()
void AppDbNvmStoreCccTbl (appDbHdl_t hdl)
Store the client characteristic configuration table for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References APP_DB_NUM_CCCD, and WsfNvmWriteData().
AppDbNvmStoreChangeAwareState()
void AppDbNvmStoreChangeAwareState (appDbHdl_t hdl)
Store the client's state of awareness to a change for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References WsfNvmWriteData().
AppDbNvmStoreCsfRecord()
void AppDbNvmStoreCsfRecord (appDbHdl_t hdl)
Store the client supported features for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References ATT_CSF_LEN, and WsfNvmWriteData().
AppDbNvmStoreDbHash()
void AppDbNvmStoreDbHash (appDbHdl_t hdl)
Store the GATT database hash for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References ATT_DATABASE_HASH_LEN, and WsfNvmWriteData().
AppDbNvmStoreHdlList()
void AppDbNvmStoreHdlList (appDbHdl_t hdl)
Store the cached attribute handle list for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References APP_DB_HDL_LIST_LEN, and WsfNvmWriteData().
AppDbNvmStorePeerAddrRes()
void AppDbNvmStorePeerAddrRes (appDbHdl_t hdl)
Store the address resolution attribute value for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References WsfNvmWriteData().
AppDbNvmStorePeerRpao()
void AppDbNvmStorePeerRpao (appDbHdl_t hdl)
Store the resolvable private address only attribute flag for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References WsfNvmWriteData().
AppDbNvmStorePeerSignCounter()
void AppDbNvmStorePeerSignCounter (appDbHdl_t hdl)
Store the peer sign counter for a device record in NVM.
Parameters
hdl Database record handle.
Returns
None.
References WsfNvmWriteData().
AppDbRecordInUse()
bool_t AppDbRecordInUse (appDbHdl_t hdl)
Check if a database record is in use.
Parameters
hdl Database record handle.
Returns
TURE if record in use. FALSE, otherwise.
AppDbSetCacheByHash()
void AppDbSetCacheByHash (appDbHdl_t hdl, bool_t cacheByHash)
Set if cached handles' validity are determined by reading the peer's database hash.
Parameters
hdl Database record handle.
cacheByHash TRUE if peer's database must be read to verify cached handles.
Returns
None.
Set if cached handles' validity are determined by reading the peer's database hash.
Parameters
hdl Database record handle.
cacheByHash TRUE if peer's database must be read to verify cached handles.
Returns
None.
AppDbSetCccTblValue()
void AppDbSetCccTblValue (appDbHdl_t hdl, uint16_t idx, uint16_t value)
Set a value in the client characteristic configuration table.
Parameters
hdl Database record handle.
idx Table index.
value Client characteristic configuration value.
Returns
None.
Parameters
hdl Database record handle.
idx Table index.
value client characteristic configuration value.
Returns
None.
References APP_DB_NUM_CCCD, and WSF_ASSERT.
AppDbSetClientChangeAwareState()
void AppDbSetClientChangeAwareState (appDbHdl_t hdl, uint8_t state)
Set client's state of awareness to a change in the database.
Parameters
hdl Database record handle. If hdl == NULL, state is set for all clients.
state The state of awareness to a change, see attClientAwareStates.
Returns
None.
References APP_DB_HDL_NONE, and APP_DB_NUM_RECS.
AppDbSetCsfRecord()
void AppDbSetCsfRecord (appDbHdl_t hdl, uint8_t changeAwareState, uint8_t * pCsf)
Set a client supported features record.
Parameters
hdl Database record handle.
changeAwareState The state of awareness to a change.
pCsf pointed client supported features.
Returns
None.
Parameters
hdl Database record handle.
changeAwareState The state of awareness to a change, see attClientAwareStates.
pCsf Pointer to the client supported features value.
Returns
None.
References APP_DB_HDL_NONE, and ATT_CSF_LEN.
AppDbSetDbHash()
void AppDbSetDbHash (uint8_t * pHash)
Set device's GATT database hash.
Parameters
pHash GATT database hash to store.
Returns
None.
References ATT_DATABASE_HASH_LEN.
AppDbSetDevName()
void AppDbSetDevName (uint8_t len, char * pStr)
Set the device name.
Parameters
len Device name length.
pStr UTF-8 string containing the device name.
Returns
None.
Parameters
len Device name length.
pStr UTF-8 string containing device name.
Returns
None.
AppDbSetDiscStatus()
void AppDbSetDiscStatus (appDbHdl_t hdl, uint8_t status)
Set the discovery status.
Parameters
hdl Database record handle.
status Discovery status.
Returns
None.
Parameters
hdl Database record handle.
state Discovery status.
Returns
None.
AppDbSetHdlList()
void AppDbSetHdlList (appDbHdl_t hdl, uint16_t * pHdlList)
Set the cached handle list.
Parameters
hdl Database record handle.
pHdlList Pointer to handle list.
Returns
None.
AppDbSetKey()
void AppDbSetKey (appDbHdl_t hdl, dmSecKeyIndEvt_t * pKey)
Set a key in a device database record.
Parameters
hdl Database record handle.
pKey Key data.
Returns
None.
References dmSecIrk_t::addrType, BdaCpy(), dmSecIrk_t::bdAddr, dmSecKey_t::csrk, DM_KEY_CSRK, DM_KEY_IRK, DM_KEY_LOCAL_LTK, DM_KEY_PEER_LTK, dmSecKey_t::irk, dmSecKeyIndEvt_t::keyData, dmSecKey_t::ltk, dmSecKeyIndEvt_t::secLevel, and dmSecKeyIndEvt_t::type.
AppDbSetPeerAddedToRl()
void AppDbSetPeerAddedToRl (appDbHdl_t hdl, bool_t peerAddedToRl)
Set the peer device added to resolving list flag to a given value.
Parameters
hdl Database record handle.
peerAddedToRl Peer device added to resolving list flag value.
Returns
None.
AppDbSetPeerAddrRes()
void AppDbSetPeerAddrRes (appDbHdl_t hdl, uint8_t addrRes)
Set address resolution attribute value for a peer device.
Parameters
hdl Database record handle.
addrRes Peer address resolution attribue value.
Returns
None.
Parameters
hdl Database record handle.
addrRes Address resolution attribue value.
Returns
None.
AppDbSetPeerDbHash()
void AppDbSetPeerDbHash (appDbHdl_t hdl, uint8_t * pDbHash)
Set a new peer database hash.
Parameters
hdl Database record handle.
dbHash Pointer to new hash.
Returns
None.
Parameters
hdl Database record handle.
pDbHash Pointer to new hash.
Returns
None.
References ATT_DATABASE_HASH_LEN, and WSF_ASSERT.
AppDbSetPeerRpao()
void AppDbSetPeerRpao (appDbHdl_t hdl, bool_t peerRpao)
Set resolvable private address only attribute present flag for a peer device.
Parameters
hdl Database record handle.
peerRpao Resolvable private address only attribute present flag.
Returns
None.
Set resolvable private address only attribute present flag for a peer device.
Parameters
hdl Database record handle.
peerRpao Resolvable private address only attribute flag value.
Returns
None.
AppDbSetPeerSignCounter()
void AppDbSetPeerSignCounter (appDbHdl_t hdl, uint32_t signCounter)
Set sign counter for a peer device.
Parameters
hdl Database record handle.
signCounter Sign counter for peer device.
Returns
None.
AppDbValidateRecord()
void AppDbValidateRecord (appDbHdl_t hdl, uint8_t keyMask)
Validate a new device database record. This function is called when pairing is successful and the devices are bonded.
Parameters
hdl Database record handle.
keyMask Bitmask of keys to validate.
Returns
None.