Cordio: MESH_SECURITY
MESH_SECURITY
Data Structures
struct meshSecFriendshipCred_t
struct meshSecUtrEncryptParams_t
struct meshSecUtrDecryptParams_t
struct meshSecNwkEncObfParams_t
struct meshSecNwkDeobfDecParams_t
struct meshSecToolCcmParams_t
struct meshSecToolCcmEncryptResult_t
struct meshSecToolCcmDecryptResult_t
struct meshSecToolCcmResult_t
Macros
#define MESH_APPKEY_INDEX_LOCAL_DEV_KEY 0xFFFF
#define MESH_APPKEY_INDEX_REMOTE_DEV_KEY 0xFFFE
#define MESH_SEC_DEVICE_KEY_AID 0xFF
#define MESH_SEC_TOOL_AES_BLOCK_SIZE 16
#define MESH_SEC_TOOL_CCM_NONCE_SIZE 13
#define MESH_SEC_TOOL_CCM_MAX_MAC_SIZE 8
#define MESH_SEC_TOOL_ECC_KEY_SIZE 32
#define MESH_SEC_TOOL_AES_REQ_QUEUE_SIZE 6
#define MESH_SEC_TOOL_CMAC_REQ_QUEUE_SIZE 6
#define MESH_SEC_TOOL_CCM_REQ_QUEUE_SIZE 6
#define MESH_SEC_TOOL_KX_REQ_QUEUE_SIZE 6
#define MESH_SEC_TOOL_K1_RESULT_SIZE 16
#define MESH_SEC_TOOL_K2_RESULT_SIZE 33
#define MESH_SEC_TOOL_K3_RESULT_SIZE 8
#define MESH_SEC_TOOL_K4_RESULT_SIZE 1
Typedefs
typedef uint16_t meshSecRetVal_t
typedef uint8_t meshSecKeyType_t
typedef void(* meshSecKeyMaterialDerivCback_t) (meshSecKeyType_t keyType, uint16_t keyIndex, bool_t isSuccess, bool_t keyUpdated, void *pParam)
typedef void(* meshSecAllKeyMaterialRestoreCback_t) (bool_t isSuccess)
typedef void(* meshSecFriendCredDerivCback_t) (meshAddress_t friendAddress, meshAddress_t lpnAddress, uint16_t netKeyIndex, bool_t isSuccess, void *pParam)
typedef void(* meshSecUtrEncryptCback_t) (bool_t isEncryptSuccess, uint8_t *pEncAppPayload, uint16_t appPayloadSize, uint8_t *pTransMic, uint8_t transMicSize, uint8_t aid, void *pParam)
typedef void(* meshSecUtrDecryptCback_t) (bool_t isDecryptSuccess, uint8_t *pAppPayload, uint8_t *pLabelUuid, uint16_t appPayloadSize, uint16_t appKeyIndex, uint16_t netKeyIndex, void *pParam)
typedef void(* meshSecNwkEncObfCback_t) (bool_t isSuccess, bool_t isProxyConfig, uint8_t *pObfEncNwkPduNoMic, uint8_t nwkPduNoMicSize, uint8_t *pNwkPduNetMic, uint8_t netMicSize, void *pParam)
typedef void(* meshSecNwkDeobfDecCback_t) (bool_t isSuccess, bool_t isProxyConfig, uint8_t *pNwkPduNoMic, uint8_t nwkPduSizeNoMic, uint16_t netKeyIndex, uint32_t ivIndex, meshAddress_t friendOrLpnAddr, void *pParam)
typedef void(* meshSecBeaconComputeAuthCback_t) (bool_t isSuccess, uint8_t *pSecNwkBeacon, uint16_t netKeyIndex, void *pParam)
typedef void(* meshSecBeaconAuthCback_t) (bool_t isSuccess, bool_t newKeyUsed, uint8_t *pSecNwkBeacon, uint16_t netKeyIndex, void *pParam)
typedef bool_t(* meshSecRemoteDevKeyReadCback_t) (meshAddress_t addr, uint8_t *pOutDevKey)
typedef uint16_t meshSecToolRetVal_t
typedef uint8_t meshSecToolAlgoBitfield_t
typedef uint8_t meshSecToolCcmOperation_t
typedef void(* meshSecToolAesCback_t) (const uint8_t *pCipherTextBlock, void *pParam)
typedef void(* meshSecToolCmacCback_t) (const uint8_t *pCmacResult, void *pParam)
typedef void(* meshSecToolCcmCback_t) (const meshSecToolCcmResult_t *pCcmResult, void *pParam)
typedef void(* meshSecToolEccKeyGenCback_t) (const uint8_t *pPubX, const uint8_t *pPubY, const uint8_t *pPriv)
typedef void(* meshSecToolEcdhCback_t) (bool_t isValid, const uint8_t *pSharedSecret)
typedef void(* meshSecToolKeyDerivationCback_t) (const uint8_t *pResult, uint8_t resultSize, void *pParam)
Enumerations
enum meshSecKeyTypeValues
enum meshSecToolAlgoBitMask
enum meshSecToolCcmOperationType
Functions
uint32_t MeshSecGetRequiredMemory (void)
void MeshSecInit (void)
void MeshSecRegisterRemoteDevKeyReader (meshSecRemoteDevKeyReadCback_t devKeyReader)
meshSecRetVal_t MeshSecAddKeyMaterial (meshSecKeyType_t keyType, uint16_t keyIndex, bool_t isUpdate, meshSecKeyMaterialDerivCback_t keyMaterialAddedCback, void *pParam)
void MeshSecRestoreAllKeyMaterial (meshSecAllKeyMaterialRestoreCback_t restoreCback)
meshSecRetVal_t MeshSecRemoveKeyMaterial (meshSecKeyType_t keyType, uint16_t keyIndex, bool_t deleteOldOnly)
meshSecRetVal_t MeshSecAddFriendCred (const meshSecFriendshipCred_t *pFriendshipCred, meshSecFriendCredDerivCback_t friendCredAdded, void *pParam)
meshSecRetVal_t MeshSecRemoveFriendCred (meshAddress_t friendAddr, meshAddress_t lpnAddr, uint16_t netKeyIndex)
bool_t MeshSecNidExists (uint8_t nid)
meshSecRetVal_t MeshSecUtrEncrypt (meshSecUtrEncryptParams_t *pReqParams, meshSecUtrEncryptCback_t utrEncryptCompleteCback, void *pParam)
meshSecRetVal_t MeshSecUtrDecrypt (meshSecUtrDecryptParams_t *pReqParams, meshSecUtrDecryptCback_t utrDecryptCompleteCback, void *pParam)
meshSecRetVal_t MeshSecNwkEncObf (bool_t isProxyConfig, meshSecNwkEncObfParams_t *pReqParams, meshSecNwkEncObfCback_t encObfCompleteCback, void *pParam)
meshSecRetVal_t MeshSecNwkDeobfDec (bool_t isProxyConfig, meshSecNwkDeobfDecParams_t *pReqParams, meshSecNwkDeobfDecCback_t nwkDeobfDecCback, void *pParam)
meshSecRetVal_t MeshSecBeaconComputeAuth (uint8_t *pSecNwkBeacon, uint16_t netKeyIndex, bool_t useNewKey, meshSecBeaconComputeAuthCback_t secNwkBeaconGenCback, void *pParam)
meshSecRetVal_t MeshSecBeaconAuthenticate (uint8_t *pSecNwkBeacon, meshSecBeaconAuthCback_t secNwkBeaconAuthCback, void *pParam)
uint8_t * MeshSecNetKeyIndexToNwkId (uint16_t netKeyIndex)
uint8_t * MeshSecNetKeyIndexToIdentityKey (uint16_t netKeyIndex)
void MeshSecToolInit (void)
meshSecToolRetVal_t MeshSecToolAesEncrypt (uint8_t *pAesKey, uint8_t *pPlainTextBlock, meshSecToolAesCback_t aesCback, void *pParam)
meshSecToolRetVal_t MeshSecToolCmacCalculate (uint8_t *pKey, uint8_t *pPlainText, uint16_t plainTextLen, meshSecToolCmacCback_t cmacCback, void *pParam)
meshSecToolRetVal_t MeshSecToolCcmEncryptDecrypt (meshSecToolCcmOperation_t opType, meshSecToolCcmParams_t *pOpParams, meshSecToolCcmCback_t ccmCback, void *pParam)
meshSecToolRetVal_t MeshSecToolEccGenerateKey (meshSecToolEccKeyGenCback_t eccKeyGenCback)
meshSecToolRetVal_t MeshSecToolEccCompSharedSecret (const uint8_t *pPeerPubX, const uint8_t *pPeerPubY, const uint8_t *pLocalPriv, meshSecToolEcdhCback_t sharedSecretCback)
meshSecToolRetVal_t MeshSecToolGenerateSalt (uint8_t *pPlainText, uint16_t plainTextLen, meshSecToolCmacCback_t saltCback, void *pParam)
meshSecToolRetVal_t MeshSecToolK1Derive (uint8_t *pPlainText, uint16_t plainTextSize, uint8_t *pSalt, uint8_t *pTempKeyMaterial, uint16_t tempKeyMaterialSize, meshSecToolKeyDerivationCback_t derivCompleteCback, void *pParam)
meshSecToolRetVal_t MeshSecToolK2Derive (uint8_t *pPlainText, uint16_t plainTextSize, uint8_t *pTempKeyMaterial, meshSecToolKeyDerivationCback_t derivCompleteCback, void *pParam)
meshSecToolRetVal_t MeshSecToolK3Derive (uint8_t *pPlainText, meshSecToolKeyDerivationCback_t derivCompleteCback, void *pParam)
meshSecToolRetVal_t MeshSecToolK4Derive (uint8_t *pPlainText, meshSecToolKeyDerivationCback_t derivCompleteCback, void *pParam)
Detailed Description
Data Structure Documentation
meshSecFriendshipCred_t
struct meshSecFriendshipCred_t
Mesh Security friendship credentials information
Data Fields
meshAddress_t friendAddres
meshAddress_t lpnAddress
uint16_t friendCounter
uint16_t lpnCounter
uint16_t netKeyIndex
Field Documentation
friendAddres
meshAddress_t friendAddres
Address of the friend node
friendCounter
uint16_t friendCounter
The value from the FriendCounter field of the Friend Offer message
lpnAddress
meshAddress_t lpnAddress
Address of the low power node
lpnCounter
uint16_t lpnCounter
The value from the LPNCounter field of the Friend Request message
netKeyIndex
uint16_t netKeyIndex
Global network key index
meshSecUtrEncryptParams_t
struct meshSecUtrEncryptParams_t
Mesh Security Upper transport encryption parameters Description:
Pointers to application payload, encrypted application payload and label UUID must reference buffers available until the encryption callback is invoked
Pointer to 16 byte Label UUID must be not NULL if destination address type is virtual
transMicSize must be either 4 or 8 and it is the transport MIC size in bytes
Data Fields
uint8_t * pAppPayload
uint8_t * pEncAppPayload
uint8_t * pTransMic
uint8_t * pLabelUuid
uint16_t appPayloadSize
uint16_t appKeyIndex
uint16_t netKeyIndex
uint32_t seqNo
meshAddress_t srcAddr
meshAddress_t dstAddr
uint8_t transMicSize
Field Documentation
appKeyIndex
uint16_t appKeyIndex
Global index of the Application Key to be used
appPayloadSize
uint16_t appPayloadSize
Size of the application payload
dstAddr
meshAddress_t dstAddr
Destination address
netKeyIndex
uint16_t netKeyIndex
Global index of the Network Key bound to the Application Key
pAppPayload
uint8_t* pAppPayload
Pointer to application payload buffer
pEncAppPayload
uint8_t* pEncAppPayload
Pointer to encrypted application payload buffer
pLabelUuid
uint8_t* pLabelUuid
Pointer to label UUID for virtual destination addresses
pTransMic
uint8_t* pTransMic
Pointer to transport mic buffer
seqNo
uint32_t seqNo
24 bit sequence number allocated for the PDU
srcAddr
meshAddress_t srcAddr
Source address of the element originating the message
transMicSize
uint8_t transMicSize
Size of the transport MIC
meshSecUtrDecryptParams_t
struct meshSecUtrDecryptParams_t
Mesh Security Upper transport decryption parameters Description:
Pointers to application payload and encrypted application payload must reference buffers available until the decryption callback is invoked
transMicSize must be either 4 or 8 and it is the provided transport MIC size in bytes
Data Fields
uint8_t * pEncAppPayload
uint8_t * pAppPayload
uint8_t * pTransMic
uint32_t seqNo
uint32_t recvIvIndex
meshAddress_t srcAddr
meshAddress_t dstAddr
uint16_t netKeyIndex
uint16_t appPayloadSize
uint8_t transMicSize
uint8_t aid
Field Documentation
aid
uint8_t aid
5 bit Application Key identifier
appPayloadSize
uint16_t appPayloadSize
Size of the application payload
dstAddr
meshAddress_t dstAddr
Destination address
netKeyIndex
uint16_t netKeyIndex
Global network key index of the key used to decrypt the Network PDU
pAppPayload
uint8_t* pAppPayload
Pointer to decrypted application payload buffer
pEncAppPayload
uint8_t* pEncAppPayload
Pointer to encrypted application payload buffer
pTransMic
uint8_t* pTransMic
Pointer to transport mic buffer that needs to be verified
recvIvIndex
uint32_t recvIvIndex
IV index used when Network authenticated the PDU
seqNo
uint32_t seqNo
24 bit sequence number allocated for the PDU
srcAddr
meshAddress_t srcAddr
Source address of the element originating the message
transMicSize
uint8_t transMicSize
Size of the transport MIC
meshSecNwkEncObfParams_t
struct meshSecNwkEncObfParams_t
Mesh Security Network PDU encryption and obfuscation parameters Description:
The friendOrLpnAddress parameter must be set to the unassigned address if master security credentials should be used. Otherwise it must be set to the target friend or one of the low power nodes that has friendship established
pObfEncNwkPduNoMic must reference memory that does not change until the procedure is complete
pNwkPduNetMic must reference memory that does not change until the procedure is complete
Data Fields
uint32_t ivIndex
uint16_t netKeyIndex
meshAddress_t friendOrLpnAddress
uint8_t * pNwkPduNoMic
uint8_t * pObfEncNwkPduNoMic
uint8_t * pNwkPduNetMic
uint8_t nwkPduNoMicSize
uint8_t netMicSize
Field Documentation
friendOrLpnAddress
meshAddress_t friendOrLpnAddress
Unassigned address if master credentials are used, or the friend or low power node address
ivIndex
uint32_t ivIndex
IV Index
netKeyIndex
uint16_t netKeyIndex
Global network key identifier
netMicSize
uint8_t netMicSize
Size of the Net MIC in bytes (can be only 4 or 8 bytes)
nwkPduNoMicSize
uint8_t nwkPduNoMicSize
Size of the network PDU excluding Net MIC in bytes
pNwkPduNetMic
uint8_t* pNwkPduNetMic
Pointer to buffer where the calculated NetMic is stored
pNwkPduNoMic
uint8_t* pNwkPduNoMic
Pointer to buffer containing a network PDU excluding NetMIC
pObfEncNwkPduNoMic
uint8_t* pObfEncNwkPduNoMic
Pointer to buffer representing an obfuscated and encrypted network PDU excluding NetMIC
meshSecNwkDeobfDecParams_t
struct meshSecNwkDeobfDecParams_t
Mesh Security Network PDU deobfuscation and decryption parameters Description:
Data Fields
uint8_t * pObfEncAuthNwkPdu
uint8_t * pNwkPduNoMic
uint8_t nwkPduSize
Field Documentation
nwkPduSize
uint8_t nwkPduSize
Size of the received encrypted, obfuscated and authenticated network pdu
pNwkPduNoMic
uint8_t* pNwkPduNoMic
Pointer to buffer where the decrypted and deobfuscated network PDU excluding NetMic is stored
pObfEncAuthNwkPdu
uint8_t* pObfEncAuthNwkPdu
Pointer to buffer representing a received obfuscated, encrypted and authenticated network PDU
meshSecToolCcmParams_t
struct meshSecToolCcmParams_t
Mesh Security Toolbox CCM request parameter structure
Data Fields
uint8_t * pIn
uint8_t * pOut
uint8_t * pAuthData
uint8_t * pCbcMac
uint8_t * pCcmKey
uint8_t * pNonce
uint16_t inputLen
uint16_t authDataLen
uint8_t cbcMacSize
Field Documentation
authDataLen
uint16_t authDataLen
Authentication data length
cbcMacSize
uint8_t cbcMacSize
Size of the CBC-MAC
inputLen
uint16_t inputLen
Input/Output buffer length
pAuthData
uint8_t* pAuthData
Pointer to authentication data
pCbcMac
uint8_t* pCbcMac
Pointer to CBC-MAC in/out buffer
pCcmKey
uint8_t* pCcmKey
Pointer to 128-bit AES CCM Key
pIn
uint8_t* pIn
Pointer to input buffer
pNonce
uint8_t* pNonce
13-byte Nonce for counter
pOut
uint8_t* pOut
Pointer output buffer
meshSecToolCcmEncryptResult_t
struct meshSecToolCcmEncryptResult_t
Mesh Security CCM Encrypt operation result
Data Fields
uint8_t * pCipherText
uint16_t cipherTextSize
uint8_t * pCbcMac
uint8_t cbcMacSize
Field Documentation
cbcMacSize
uint8_t cbcMacSize
Size in bytes of the CBC-MAC
cipherTextSize
uint16_t cipherTextSize
Size of the ciphertext
pCbcMac
uint8_t* pCbcMac
Pointer to buffer storing the CBC-MAC calculation (passed as parameter in the request)
pCipherText
uint8_t* pCipherText
Pointer to buffer storing the ciphertext (passed as pOut in the request)
meshSecToolCcmDecryptResult_t
struct meshSecToolCcmDecryptResult_t
Mesh CCM Decrypt operation result
Data Fields
uint8_t * pPlainText
uint16_t plainTextSize
bool_t isAuthSuccess
Field Documentation
isAuthSuccess
bool_t isAuthSuccess
TRUE if PDU is authenticated
plainTextSize
uint16_t plainTextSize
Size of the plaintext
pPlainText
uint8_t* pPlainText
Pointer to buffer storing the plaintext (passed as pOut in the request)
meshSecToolCcmResult_t
struct meshSecToolCcmResult_t
Mesh CCM operation result
Data Fields
meshSecToolCcmOperation_t op
meshSecToolCcmResults_t results
Field Documentation
op
meshSecToolCcmOperation_t op
Operation identifier
results
meshSecToolCcmResults_t results
Results union
Macro Definition Documentation
MESH_APPKEY_INDEX_LOCAL_DEV_KEY
#define MESH_APPKEY_INDEX_LOCAL_DEV_KEY 0xFFFF
Mesh AppKey Index used by the Security module when key type is local Device Key
MESH_APPKEY_INDEX_REMOTE_DEV_KEY
#define MESH_APPKEY_INDEX_REMOTE_DEV_KEY 0xFFFE
Mesh AppKey Index used by the Security module when key type is remote Device Key
MESH_SEC_DEVICE_KEY_AID
#define MESH_SEC_DEVICE_KEY_AID 0xFF
Mesh security invalid AID provided in the UTR encryption complete callback if Device Key is used
MESH_SEC_TOOL_AES_BLOCK_SIZE
#define MESH_SEC_TOOL_AES_BLOCK_SIZE 16
AES-128 block size in bytes
MESH_SEC_TOOL_AES_REQ_QUEUE_SIZE
#define MESH_SEC_TOOL_AES_REQ_QUEUE_SIZE 6
Request queue size for AES-128 requests
MESH_SEC_TOOL_CCM_MAX_MAC_SIZE
#define MESH_SEC_TOOL_CCM_MAX_MAC_SIZE 8
Maximum CCM MAC size for Mesh Security operations
MESH_SEC_TOOL_CCM_NONCE_SIZE
#define MESH_SEC_TOOL_CCM_NONCE_SIZE 13
Nonce size for Mesh CCM operations is fixed: 13 bytes
MESH_SEC_TOOL_CCM_REQ_QUEUE_SIZE
#define MESH_SEC_TOOL_CCM_REQ_QUEUE_SIZE 6
Request queue size for AES-CCM requests
MESH_SEC_TOOL_CMAC_REQ_QUEUE_SIZE
#define MESH_SEC_TOOL_CMAC_REQ_QUEUE_SIZE 6
Request queue size for AES-CMAC requests
MESH_SEC_TOOL_ECC_KEY_SIZE
#define MESH_SEC_TOOL_ECC_KEY_SIZE 32
ECC key length in P-256 space
MESH_SEC_TOOL_K1_RESULT_SIZE
#define MESH_SEC_TOOL_K1_RESULT_SIZE 16
K1 derivation function result size in bytes
MESH_SEC_TOOL_K2_RESULT_SIZE
#define MESH_SEC_TOOL_K2_RESULT_SIZE 33
K2 derivation function result size in bytes
MESH_SEC_TOOL_K3_RESULT_SIZE
#define MESH_SEC_TOOL_K3_RESULT_SIZE 8
K3 derivation function result size in bytes
MESH_SEC_TOOL_K4_RESULT_SIZE
#define MESH_SEC_TOOL_K4_RESULT_SIZE 1
K4 derivation function result size in bytes
MESH_SEC_TOOL_KX_REQ_QUEUE_SIZE
#define MESH_SEC_TOOL_KX_REQ_QUEUE_SIZE 6
Request queue size for Kx derivation requests
Typedef Documentation
meshSecAllKeyMaterialRestoreCback_t
typedef void(* meshSecAllKeyMaterialRestoreCback_t) (bool_t isSuccess)
Mesh Security all keys material derivation complete callback.
Parameters
[in] isSuccess TRUE if operation is successful.
Returns
None.
meshSecBeaconAuthCback_t
typedef void(* meshSecBeaconAuthCback_t) (bool_t isSuccess, bool_t newKeyUsed, uint8_t *pSecNwkBeacon, uint16_t netKeyIndex, void *pParam)
Mesh Security Secure Network Beacon authentication complete callback.
Parameters
[in] isSuccess TRUE if operation completed successfully.
[in] newKeyUsed TRUE if the new key was used to authenticate.
[in] pSecNwkBeacon Pointer to buffer where the Secure Network Beacon is stored.
[in] netKeyIndex Global network key index associated to the key that successfully processed the received Secure Network Beacon.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
meshSecBeaconComputeAuthCback_t
typedef void(* meshSecBeaconComputeAuthCback_t) (bool_t isSuccess, uint8_t *pSecNwkBeacon, uint16_t netKeyIndex, void *pParam)
Mesh Security Secure Network Beacon authentication calculated callback.
Parameters
[in] isSuccess TRUE if operation completed successfully.
[in] pSecNwkBeacon Pointer to buffer where the Secure Network Beacon is stored.
[in] netKeyIndex Global network key index used to compute the authentication value.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
meshSecFriendCredDerivCback_t
typedef void(* meshSecFriendCredDerivCback_t) (meshAddress_t friendAddress, meshAddress_t lpnAddress, uint16_t netKeyIndex, bool_t isSuccess, void *pParam)
Mesh Security friendship credentials derivation complete callback.
Parameters
[in] friendAddress The address of the friend node.
[in] lpnAddress The address of the low power node.
[in] netKeyIndex Global network key index.
[in] isSuccess TRUE if operation is successful.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
meshSecKeyMaterialDerivCback_t
typedef void(* meshSecKeyMaterialDerivCback_t) (meshSecKeyType_t keyType, uint16_t keyIndex, bool_t isSuccess, bool_t keyUpdated, void *pParam)
Mesh Security key material derivation complete callback.
Parameters
[in] keyType The type of the key.
[in] keyIndex Global key index for application and network key types.
[in] keyUpdated TRUE if key material was added for the new key of an existing key index.
[in] isSuccess TRUE if operation is successful.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
See also
meshSecKeyType_t
meshSecKeyType_t
typedef uint8_t meshSecKeyType_t
Mesh Key type used by the key material derivation API. See meshSecKeyTypeValues
meshSecNwkDeobfDecCback_t
typedef void(* meshSecNwkDeobfDecCback_t) (bool_t isSuccess, bool_t isProxyConfig, uint8_t *pNwkPduNoMic, uint8_t nwkPduSizeNoMic, uint16_t netKeyIndex, uint32_t ivIndex, meshAddress_t friendOrLpnAddr, void *pParam)
Mesh Security Network deobfuscation and decryption complete callback.
Parameters
[in] isSuccess TRUE if operation completed succesfully.
[in] isProxyConfig TRUE if Network PDU is a Proxy Configuration Message.
[in] pNwkPduNoMic Pointer to buffer where the deobfuscated and decrypted network PDU is stored.
[in] nwkPduSizeNoMic Size of the deobfuscated and decrypted network PDU excluding NetMIC.
[in] netKeyIndex Global network key index associated to the key that successfully processed the received network PDU. using friendship credentials. Unassigned address otherwise.
[in] ivIndex IV index that successfully authenticated the PDU.
[in] friendOrLpnAddr Friend or LPN address.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
meshSecNwkEncObfCback_t
typedef void(* meshSecNwkEncObfCback_t) (bool_t isSuccess, bool_t isProxyConfig, uint8_t *pObfEncNwkPduNoMic, uint8_t nwkPduNoMicSize, uint8_t *pNwkPduNetMic, uint8_t netMicSize, void *pParam)
Mesh Security Network PDU encryption and obfuscation complete callback.
Parameters
[in] isSuccess TRUE if operation completed successfully.
[in] isProxyConfig TRUE if Network PDU is a Proxy Configuration Message.
[in] pObfEncNwkPduNoMic Pointer to buffer where the encrypted and obfuscated network PDU is stored.
[in] nwkPduNoMicSize Size of the network PDU excluding NetMIC.
[in] pNwkPduNetMic Pointer to buffer where the calculated NetMIC is stored.
[in] netMicSize Size of the calculated NetMIC.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
meshSecRemoteDevKeyReadCback_t
typedef bool_t(* meshSecRemoteDevKeyReadCback_t) (meshAddress_t addr, uint8_t *pOutDevKey)
Reads the Device Key of a remote node.
Parameters
[in] addr Address of the node for which the Device Key is read.
[out] pOutDevKey Pointer to buffer where the Device Key is copied if an address matches.
meshSecRetVal_t
typedef uint16_t meshSecRetVal_t
Mesh Security API return type. See meshReturnValues for codes starting at MESH_SEC_RETVAL_BASE
meshSecToolAesCback_t
typedef void(* meshSecToolAesCback_t) (const uint8_t *pCipherTextBlock, void *pParam)
Callback for AES-128 block encryption (e - function).
Parameters
[in] pCipherTextBlock Pointer to 16 byte ciphertext block.
[in] pParam Pointer to generic parameter provided in request.
Returns
None.
meshSecToolAlgoBitfield_t
typedef uint8_t meshSecToolAlgoBitfield_t
Mesh Security Toolbox supported algorithms bitfield
meshSecToolCcmCback_t
typedef void(* meshSecToolCcmCback_t) (const meshSecToolCcmResult_t *pCcmResult, void *pParam)
Callback for AES-CCM operation.
Parameters
[in] pCmacResult Pointer to CCM response structure.
[in] pParam Pointer to generic parameter provided in request.
Returns
None.
See also
meshSecToolCcmResult_t
meshSecToolCcmOperation_t
typedef uint8_t meshSecToolCcmOperation_t
Mesh Security CCM operation type. See meshSecToolCcmOperationType
meshSecToolCmacCback_t
typedef void(* meshSecToolCmacCback_t) (const uint8_t *pCmacResult, void *pParam)
Callback for AES-CMAC operation.
Parameters
[in] pCmacResult Pointer to 16 byte CMAC result.
[in] pParam Pointer to generic parameter provided in request.
Returns
None.
meshSecToolEccKeyGenCback_t
typedef void(* meshSecToolEccKeyGenCback_t) (const uint8_t *pPubX, const uint8_t *pPubY, const uint8_t *pPriv)
Callback for ECC key generation.
Parameters
[in] pPubX Pointer to the X component of ECC public key.
[in] pPubY Pointer to the Y component of ECC public key.
[in] pPriv Pointer to the ECC private key.
Returns
None.
Remarks
The caller must copy the value of the ECC keys until the callback ends execution.
meshSecToolEcdhCback_t
typedef void(* meshSecToolEcdhCback_t) (bool_t isValid, const uint8_t *pSharedSecret)
Callback for ECDH shared secret calculation.
Parameters
[in] isValid TRUE if the peer ECC key is valid, FALSE otherwise.
[in] pSharedSecret Pointer to MESH_SEC_TOOL_ECC_KEY_SIZE bytes of shared secret.
Returns
None.
Remarks
The caller must copy the value of the ECDH secret until the callback ends execution.
meshSecToolKeyDerivationCback_t
typedef void(* meshSecToolKeyDerivationCback_t) (const uint8_t *pResult, uint8_t resultSize, void *pParam)
Callback for Mesh Security Derivation functions.
Parameters
[in] pResult Pointer to result buffer.
[in] resultSize Size of the result.
[in] pParam Pointer to generic parameter provided in request.
Returns
None.
meshSecToolRetVal_t
typedef uint16_t meshSecToolRetVal_t
Mesh Security Toolbox return value type. See meshReturnValues
meshSecUtrDecryptCback_t
typedef void(* meshSecUtrDecryptCback_t) (bool_t isDecryptSuccess, uint8_t *pAppPayload, uint8_t *pLabelUuid, uint16_t appPayloadSize, uint16_t appKeyIndex, uint16_t netKeyIndex, void *pParam)
Mesh Security Upper transport decryption complete callback.
Parameters
[in] isDecryptSuccess TRUE if decryption and authentication finished successfully.
[in] pAppPayload Pointer to decrypted application payload, provided in the request.
[in] pLabelUuid Pointer to label UUID for virtual destination addresses.
[in] appPayloadSize Size of the decrypted application payload.
[in] appKeyIndex Global application index that matched the AID in the request.
[in] netKeyIndex Global network key index associated to the application key index.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
Note
Pointer to 16 byte Label UUID must not be NULL if destination address type is virtual.
meshSecUtrEncryptCback_t
typedef void(* meshSecUtrEncryptCback_t) (bool_t isEncryptSuccess, uint8_t *pEncAppPayload, uint16_t appPayloadSize, uint8_t *pTransMic, uint8_t transMicSize, uint8_t aid, void *pParam)
Mesh Security Upper transport encryption complete callback.
Parameters
[in] isEncryptSuccess TRUE if encryption finished successfully.
[in] pEncAppPayload Pointer to encrypted application payload, provided in the request.
[in] appPayloadSize Size of the encrypted application payload.
[in] pTransMic Pointer to buffer, provided in the request, used to store calculated transport MIC over the application payload.
[in] transMicSize Size of the transport MIC (4 or 8 bytes).
[in] aid AID derived by the key used or invalid if Device Key is used.
[in] pParam Pointer to generic callback parameter provided in the request.
Returns
None.
Enumeration Type Documentation
meshSecKeyTypeValues
enum meshSecKeyTypeValues
Enumeration of key types used by the key material derivation API
Enumerator
MESH_SEC_KEY_TYPE_NWK
Key type is Network Key
MESH_SEC_KEY_TYPE_APP
Key type is Application Key
meshSecToolAlgoBitMask
enum meshSecToolAlgoBitMask
Mesh Security Toolbox used algorithms bitmask
Enumerator
MESH_SEC_TOOL_ALGO_AES_128
AES 128
MESH_SEC_TOOL_ALGO_AES_CMAC
AES-CMAC
MESH_SEC_TOOL_ALGO_CCM
AES-CCM
MESH_SEC_TOOL_ALGO_ECC
ECC KeyGen and ECDH
meshSecToolCcmOperationType
enum meshSecToolCcmOperationType
Mesh Security CCM operation types
Enumerator
MESH_SEC_TOOL_CCM_ENCRYPT
Encrypt operation
MESH_SEC_TOOL_CCM_DECRYPT
Decrypt operation
Function Documentation
MeshSecAddFriendCred()
meshSecRetVal_t MeshSecAddFriendCred (const meshSecFriendshipCred_t * pFriendshipCred, meshSecFriendCredDerivCback_t friendCredAdded, void * pParam)
Generates and adds friendship credentials to network key derivation material.
Parameters
[in] pFriendshipCred Pointer to friendship credentials material information.
[in] friendCredAdded Callback used for procedure complete notification.
[in] pParam Pointer to generic parameter for the callback.
Return values
MESH_SUCCESS Friendship material derivation started.
MESH_SEC_INVALID_PARAMS Invalid parameters.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
MESH_SEC_KEY_MATERIAL_NOT_FOUND There is no existing entry for the provided network key index.
MESH_SEC_KEY_MATERIAL_EXISTS The friendship credentials already exist.
Remarks
This function must be called when a friendship is established.
See also
meshSecKeyType_t
meshSecFriendCredDerivCback_t
References meshSecFriendDerivReq_t::cback, meshSecFriendDerivReq_t::doUpdate, meshSecKeyInfoHdr_t::flags, meshSecFriendshipCred_t::friendAddres, meshSecFriendMat_t::friendAddres, meshSecFriendDerivReq_t::friendListIdx, meshSecKeyDerivRequests_t::friendMatDerivReq, meshSecMaterial_t::friendMatListSize, meshSecNetKeyInfo_t::hdr, meshSecKeyInfoHdr_t::keyIndex, meshSecFriendshipCred_t::lpnAddress, meshSecFriendMat_t::lpnAddress, MESH_IS_ADDR_UNICAST, MESH_SEC_INVALID_PARAMS, MESH_SEC_KEY_MATERIAL_EXISTS, MESH_SEC_KEY_MATERIAL_NOT_FOUND, MESH_SEC_OUT_OF_MEMORY, MESH_SUCCESS, meshSecFriendDerivReq_t::netKeyIndex, meshSecFriendshipCred_t::netKeyIndex, meshSecFriendMat_t::netKeyInfoIndex, meshSecMaterial_t::netKeyInfoListSize, meshSecFriendDerivReq_t::netKeyListIdx, meshSecMaterial_t::pFriendMatArray, meshSecFriendDerivReq_t::pK2PBuff, meshSecMaterial_t::pNetKeyInfoArray, and meshSecFriendDerivReq_t::pParam.
MeshSecAddKeyMaterial()
meshSecRetVal_t MeshSecAddKeyMaterial (meshSecKeyType_t keyType, uint16_t keyIndex, bool_t isUpdate, meshSecKeyMaterialDerivCback_t keyMaterialAddedCback, void * pParam)
Derives and stores Application or Network Key material.
Parameters
[in] keyType Type of the key for which derivation is requested.
[in] keyIndex Global key index for application or network keys.
[in] isUpdate Indicates if derivation material is needed for a new key of the same global key index. Used during Key Refresh Procedure transitions (add new key).
[in] keyMaterialAddedCback Callback invoked after key material is stored in the module.
[in] pParam Pointer to generic parameter for the callback.
Return values
MESH_SUCCESS Key derivation started.
MESH_SEC_INVALID_PARAMS Invalid parameters.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
MESH_SEC_KEY_NOT_FOUND An update is requested for a key index that is not stored.
MESH_SEC_KEY_MATERIAL_NOT_FOUND An update is requested for a key index that has no key material derived from the old key.
MESH_SEC_KEY_MATERIAL_EXISTS The key derivation material already exists.
Remarks
For key update procedures, this function also updates the friendship security credentials that already exist for a specific network key.
See also
meshSecKeyType_t
meshSecKeyMaterialDerivCback_t
MeshSecBeaconAuthenticate()
meshSecRetVal_t MeshSecBeaconAuthenticate (uint8_t * pSecNwkBeacon, meshSecBeaconAuthCback_t secNwkBeaconAuthCback, void * pParam)
Authenticates a Secure Network Beacon.
Parameters
[in] pSecNwkBeacon Pointer to received Secure Network Beacon.
[in] secNwkBeaconAuthCback Callback used to signal operation complete.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS All validation is performed. Authentication starts.
MESH_SEC_INVALID_PARAMS Invalid parameters (E.g.: NULL input).
MESH_SEC_KEY_NOT_FOUND No matching NetKey index is found.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
Remarks
This function computes the authentication value and compares it with the last 8 bytes of the buffer referenced by pSecNwkBeacon.
See also
meshSecBeaconAuthCback_t
References meshSecCryptoRequests_t::beaconAuthReq, meshSecNwkBeaconAuthReq_t::cback, meshSecNwkBeaconAuthReq_t::keySearchIndex, MESH_SEC_INVALID_PARAMS, MESH_SEC_OUT_OF_MEMORY, MESH_SUCCESS, meshSecNwkBeaconAuthReq_t::pParam, and meshSecNwkBeaconAuthReq_t::pSecBeacon.
MeshSecBeaconComputeAuth()
meshSecRetVal_t MeshSecBeaconComputeAuth (uint8_t * pSecNwkBeacon, uint16_t netKeyIndex, bool_t useNewKey, meshSecBeaconComputeAuthCback_t secNwkBeaconGenCback, void * pParam)
Computes Secure Network Beacon authentication value.
Parameters
[in] pSecNwkBeacon Pointer to 22 byte buffer storing the Secure Network Beacon.
[in] netKeyIndex Global Network Key identifier.
[in] useNewKey TRUE if new key should be used for computation.
[in] secNwkBeaconGenCback Callback used to signal operation complete.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS All validation is performed. Calculation starts.
MESH_SEC_INVALID_PARAMS Invalid parameters (E.g.: NULL input).
MESH_SEC_KEY_MATERIAL_NOT_FOUND Either there is no material available for the NetKey Index or the Network ID field of the beacon has no match with the Network ID(s) associated to the index.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
See also
meshSecBeaconComputeAuthCback_t
Remarks
This function computes the authentication value and stores it in the last 8 bytes of the buffer referenced by pSecNwkBeacon. Also copies the Network ID associated to the Network Key used for computing the authentication value.
MeshSecGetRequiredMemory()
uint32_t MeshSecGetRequiredMemory (void)
Computes the required memory to be provided based on the global configuration.
Returns
Required memory in bytes or MESH_MEM_REQ_INVALID_CFG in case of error.
References meshMemoryConfig_t::appKeyListSize, meshMemoryConfig_t::maxNumFriendships, MESH_MEM_REQ_INVALID_CFG, meshMemoryConfig_t::netKeyListSize, meshConfig_t::pMemoryConfig, and pMeshConfig.
MeshSecInit()
void MeshSecInit (void)
Initializes the Security module and allocates configuration memory.
Returns
None.
References meshSecMaterial_t::appKeyInfoListSize, meshMemoryConfig_t::appKeyListSize, meshSecMaterial_t::friendMatListSize, meshSecFriendMat_t::hasUpdtMaterial, meshMemoryConfig_t::maxNumFriendships, meshCb_t::memBuffSize, MeshSecGetRequiredMemory(), meshSecFriendMat_t::netKeyInfoIndex, meshSecMaterial_t::netKeyInfoListSize, meshMemoryConfig_t::netKeyListSize, meshSecMaterial_t::pAppKeyInfoArray, meshSecMaterial_t::pFriendMatArray, meshCb_t::pMemBuff, meshConfig_t::pMemoryConfig, pMeshConfig, and meshSecMaterial_t::pNetKeyInfoArray.
MeshSecNetKeyIndexToIdentityKey()
uint8_t* MeshSecNetKeyIndexToIdentityKey (uint16_t netKeyIndex)
Gets the Identity Key.
Parameters
[in] netKeyIndex Netkey index.
Returns
Pointer to Identity Key, or NULL if not found.
References meshSecNetKeyMaterial_t::identityKey.
MeshSecNetKeyIndexToNwkId()
uint8_t* MeshSecNetKeyIndexToNwkId (uint16_t netKeyIndex)
Gets the Network ID.
Parameters
[in] netKeyIndex Netkey index.
Returns
Pointer to Network ID, or NULL if not found.
References meshSecNetKeyMaterial_t::networkID.
MeshSecNidExists()
bool_t MeshSecNidExists (uint8_t nid)
Determines if the NID value exists for the existing network keys.
Parameters
[in] nid Network identifier to be searched.
Returns
TRUE if at least one NID matched or FALSE otherwise.
MeshSecNwkDeobfDec()
meshSecRetVal_t MeshSecNwkDeobfDec (bool_t isProxyConfig, meshSecNwkDeobfDecParams_t * pReqParams, meshSecNwkDeobfDecCback_t nwkDeobfDecCback, void * pParam)
Deobfuscates and decrypts a received network PDU.
Parameters
[in] isProxyConfig TRUE if PDU type is a Proxy Configuration Message.
[in] pReqParams Pointer to deobfuscation and decryption setup and storage parameters.
[in] nwkDeobfDecCback Callback used to signal operation complete.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS All validation is performed. Deobfuscation starts.
MESH_SEC_INVALID_PARAMS Invalid parameters (E.g.: Invalid length of the received PDU).
MESH_SEC_KEY_MATERIAL_NOT_FOUND No NetKey index matching NID.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
See also
meshSecNwkDeobfDecParams_t
meshSecNwkDeobfDecCback_t
MeshSecNwkEncObf()
meshSecRetVal_t MeshSecNwkEncObf (bool_t isProxyConfig, meshSecNwkEncObfParams_t * pReqParams, meshSecNwkEncObfCback_t encObfCompleteCback, void * pParam)
Encrypts and obfuscates the network PDU.
Parameters
[in] isProxyConfig TRUE if the PDU is a Proxy Configuration Message.
[in] pReqParams Pointer to encryption and obfuscation setup and storage parameters.
[in] encObfCompleteCback Callback used to signal encryption and obfuscation complete.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS All validation is performed. Encryption starts.
MESH_SEC_INVALID_PARAMS Invalid parameters (E.g.: Invalid length of the network PDU).
MESH_SEC_KEY_MATERIAL_NOT_FOUND There is no key material associated to the Network Key Index. See the remarks section for more information.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
Remarks
The NID, Encryption, Privacy keys can be present for the old key during a Key Refresh Procedure phase, but not for the new key and the phase dictates the new key material should be returned.
Note
The successful operation of Network encrypt also sets IVI-NID byte in the first byte of the encrypted and obfuscated Network PDU.
See also
meshSecNwkEncObfParams_t
meshSecNwkEncObfCback_t
MeshSecRegisterRemoteDevKeyReader()
void MeshSecRegisterRemoteDevKeyReader (meshSecRemoteDevKeyReadCback_t devKeyReader)
Registers the reader function for remote Device Keys.
Parameters
[in] devKeyReader Function (callback) called when Security needs to read a remote node's Device Key.
Returns
None.
Note
This function should be called only when an instance of Configuration Client is present on the local node.
References meshSecMaterial_t::netKeyInfoListSize, and meshSecCb_t::secRemoteDevKeyReader.
MeshSecRemoveFriendCred()
meshSecRetVal_t MeshSecRemoveFriendCred (meshAddress_t friendAddr, meshAddress_t lpnAddr, uint16_t netKeyIndex)
Removes friendship credentials from existing network key derivation material.
Parameters
[in] friendAddr Friend address.
[in] lpnAddr LPN address.
[in] netKeyIndex Global Network Key identifier.
Return values
MESH_SUCCESS Key material removed as configured by the parameters.
MESH_SEC_INVALID_PARAMS Invalid parameters. See the Remarks section.
MESH_SEC_KEY_NOT_FOUND The module has no material for the specified global key index.
MESH_SEC_KEY_MATERIAL_NOT_FOUND There is no friendship material identified by the same parameters.
Remarks
This function must be called when a friendship is terminated.
References meshSecFriendMat_t::friendAddres, meshSecKeyDerivRequests_t::friendMatDerivReq, meshSecMaterial_t::friendMatListSize, meshSecNetKeyInfo_t::hdr, meshSecKeyInfoHdr_t::keyIndex, meshSecFriendMat_t::lpnAddress, MESH_IS_ADDR_UNICAST, MESH_NET_KEY_INDEX_MAX_VAL, MESH_SEC_INVALID_PARAMS, MESH_SEC_KEY_MATERIAL_NOT_FOUND, MESH_SUCCESS, meshSecFriendDerivReq_t::netKeyIndex, meshSecFriendMat_t::netKeyInfoIndex, meshSecMaterial_t::netKeyInfoListSize, meshSecFriendDerivReq_t::netKeyListIdx, meshSecMaterial_t::pFriendMatArray, and meshSecMaterial_t::pNetKeyInfoArray.
MeshSecRemoveKeyMaterial()
meshSecRetVal_t MeshSecRemoveKeyMaterial (meshSecKeyType_t keyType, uint16_t keyIndex, bool_t deleteOldOnly)
Removes key derivation material based on keyType and key index.
Parameters
[in] keyType Type of the key for which key material must be removed.
[in] keyIndex Global key index for application or network keys.
[in] deleteOldOnly Indicates if only old key derivation material is removed. Used during Key Refresh Procedure transitions (back to normal operation).
Return values
MESH_SUCCESS Key material removed as configured by the parameters.
MESH_SEC_INVALID_PARAMS Invalid parameters. See the Remarks section.
MESH_SEC_KEY_NOT_FOUND The module has no material for the specified global key index.
MESH_SEC_KEY_MATERIAL_NOT_FOUND Caller requests to delete the old key material only, but there is only one set of key derivation material.
Remarks
This function cleans up all security materials for a specific key. For network keys, to remove only the friendship security material use MeshSecRemoveFriendCredentials. If deleteOldOnly is TRUE, this function also updates the friendship security credentials that already exist for a specific network key.
See also
meshSecKeyType_t
MeshSecRestoreAllKeyMaterial()
void MeshSecRestoreAllKeyMaterial (meshSecAllKeyMaterialRestoreCback_t restoreCback)
Derives and stores key material for all keys stored in Local Config.
Returns
None.
See also
meshSecAllKeyMaterialRestoreCback_t
Returns
None.
See also
meshSecAllKeyMaterialRestoreCback_t
Remarks
This function should be called only once after Local Config restores the keys.
References MESH_SUCCESS, MeshLocalCfgGetNextNetKeyIndex(), meshSecCb_t::restoreCback, and WSF_ASSERT.
MeshSecToolAesEncrypt()
meshSecToolRetVal_t MeshSecToolAesEncrypt (uint8_t * pAesKey, uint8_t * pPlainTextBlock, meshSecToolAesCback_t aesCback, void * pParam)
Mesh Security Toolbox AES-128 primitive.
Parameters
[in] pAesKey Pointer to 128-bit AES Key.
[in] pPlainTextBlock Pointer to 128-bit plaintext block.
[in] aesCback Callback invoked after encryption is complete.
[in] pParam Pointer to generic callback parameter.
See also
meshSecToolAesCback_t
Return values
MESH_SUCCESS Request processed successfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
References MESH_SEC_TOOL_AES_REQ_QUEUE_SIZE, MESH_SEC_TOOL_INVALID_PARAMS, MESH_SEC_TOOL_OUT_OF_MEMORY, MESH_SEC_TOOL_UNKNOWN_ERROR, MESH_SUCCESS, SEC_TOKEN_INVALID, SecAesRev(), and WsfQueueEnq().
MeshSecToolCcmEncryptDecrypt()
meshSecToolRetVal_t MeshSecToolCcmEncryptDecrypt (meshSecToolCcmOperation_t opType, meshSecToolCcmParams_t * pOpParams, meshSecToolCcmCback_t ccmCback, void * pParam)
Mesh Security Toolbox AES-CCM primitive.
Parameters
[in] opType Type of operation (encrypt or decrypt).
[in] pOpParams Pointer to structure holding the parameters to configure CCM.
[in] ccmCback Callback invoked after CCM operation is complete.
[in] pParam Pointer to generic parameter for the callback.
See also
meshSecToolCcmCback_t
meshSecToolCcmOperation_t
Return values
MESH_SUCCESS Request processed successfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Usage:
//global variables
uint8_t ccmKey[16] = { 0x00, 0x01, 0x02 };
uint8_t plain[5] = {'P','L','A','I','N'}, cipher[5] = { 0 };
uint8_t authData[3] = { 0x00, 0x02, 0x03 };
uint8_t cbcMac[8] = { 0 };
uint8_t nonce[13] = { 0x01, 0x02, 0x02, 0x01, 0x04, 0x08,
                      0xFE, 0xAB, 0xAA, 0x90, 0x11, 0x22, 0x05 };
void ccmCback(const meshSecToolCcmResult_t *pCcmResult, void *pParam)
{
  if(pCcmResult->op == (meshSecToolCcmOperation_t)MESH_SEC_TOOL_CCM_ENCRYPT)
  {
    //pCipherText points to cipher array
    PRINT_ARRAY(pCcmResult->results.encryptResult.pCipherText,
                pCcmResult->results.encryptResult.cipherTextLen);
    //pCbcMac points to cbcMac array
    PRINT_ARRAY(pCcmResult->results.encryptResult.pCbcMac,
                pCcmResult->results.encryptResult.cbcMacSize);
  }
  else
  {
    //pPlainText points to plain array
    PRINT_ARRAY(pCcmResult->results.decryptResult.pPlainText,
                pCcmResult->results.decryptResult.plainTextSize);
    PRINT("AUTH has %s",
          (pCcmResult->results.decryptResult.isAuthSuccess) ? "SUCCEEDED":"FAILED");
  }
}
void myFunc(void)
{
    meshSecToolCcmParams_t params;
    meshSecToolCcmOperation_t opType;
    params.pNonce = nonce;
    params.pCcmKey = ccmKey;
    params.pAuthData = authData;
    params.authDataLen = sizeof(authData);
    params.inputLen = sizeof(plain); //sizeof(cipher);
    params.pCbcMac = cbcMac;
    params.cbcMacSize = sizeof(cbcMac);
    if(encrypt)
    {
      params.pIn = plain;
      params.pOut = cipher;
      opType = (meshSecToolCcmOperation_t)MESH_SEC_TOOL_CCM_ENCRYPT;
    }
    else //ciphertext located in cipher, cbcMac already contains 8 byte MAC
    {
      params.pIn = cipher;
      params.pOut = plain;
      opType = (meshSecToolCcmOperation_t)MESH_SEC_TOOL_CCM_DECRYPT;
    }
    retVal = MeshSecToolCcmEncryptDecrypt(opType, &params, ccmCback, NULL);
    //check retval
}
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
MeshSecToolCmacCalculate()
meshSecToolRetVal_t MeshSecToolCmacCalculate (uint8_t * pKey, uint8_t * pPlainText, uint16_t plainTextLen, meshSecToolCmacCback_t cmacCback, void * pParam)
Mesh Security Toolbox AES-CMAC primitive.
Parameters
[in] pKey Pointer to 128-bit AES Key.
[in] pPlainText Pointer to plain text array.
[in] plainTextLen Length of the plain text.
[in] cmacCback Callback invoked after CMAC calculation is complete.
[in] pParam Pointer to generic parameter for the callback.
See also
meshSecToolCmacCback_t
Return values
MESH_SUCCESS Request processed successfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
References MESH_SEC_TOOL_CMAC_REQ_QUEUE_SIZE, MESH_SEC_TOOL_INVALID_PARAMS, and MESH_SEC_TOOL_OUT_OF_MEMORY.
MeshSecToolEccCompSharedSecret()
meshSecToolRetVal_t MeshSecToolEccCompSharedSecret (const uint8_t * pPeerPubX, const uint8_t * pPeerPubY, const uint8_t * pLocalPriv, meshSecToolEcdhCback_t sharedSecretCback)
Mesh Security Toolbox compute ECDH shared secret.
Parameters
[in] pPeerPubX Pointer to the peer's public key X component.
[in] pPeerPubY Pointer to the peer's public key Y component.
[in] pLocalPriv Pointer to the local private key.
[in] sharedSecretCback Callback invoked at the end of the shared secret calculation.
See also
meshSecToolEcdhCback_t
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by the input pointers until the callback is triggered.
Parameters
[in] pPrivAPubB Pointer to ECC Key containing remote public-local private keys.
[in] sharedSecretCback Callback invoked at the end of the shared secret calculation.
See also
meshSecToolEcdhCback_t
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered. Usage: Declare a ::meshSecToolEccKey_t variable. Copy the contents of its private key to the priv key. Copy the received public key (x,y) pair to the pubX and pubY members and call this function passing the address of the variable and a callback as params.
References MESH_SEC_TOOL_ECC_KEY_SIZE, MESH_SEC_TOOL_INVALID_PARAMS, MESH_SEC_TOOL_OUT_OF_MEMORY, MESH_SEC_TOOL_UNKNOWN_ERROR, MESH_SUCCESS, secEccKey_t::privKey, secEccKey_t::pubKey_x, secEccKey_t::pubKey_y, and SecEccGenSharedSecret().
MeshSecToolEccGenerateKey()
meshSecToolRetVal_t MeshSecToolEccGenerateKey (meshSecToolEccKeyGenCback_t eccKeyGenCback)
Mesh Security Toolbox Generate P-256 ECC Key.
Parameters
[in] eccKeyGenCback Callback invoked after a fresh key has been generated.
See also
meshSecToolEccKeyGenCback_t
Return values
MESH_SUCCESS Request processed successfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
References MESH_SEC_TOOL_INVALID_PARAMS, MESH_SEC_TOOL_OUT_OF_MEMORY, MESH_SEC_TOOL_UNKNOWN_ERROR, MESH_SUCCESS, and SecEccGenKey().
MeshSecToolGenerateSalt()
meshSecToolRetVal_t MeshSecToolGenerateSalt (uint8_t * pPlainText, uint16_t plainTextLen, meshSecToolCmacCback_t saltCback, void * pParam)
Mesh Security Toolbox Salt s1 primitive.
Parameters
[in] pPlainText Pointer to non-zero length plaintext.
[in] plainTextLen Length of the plaintext.
[in] saltCback Callback invoked after salt is generated.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
See also
meshSecToolCmacCback_t
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
References MESH_SEC_TOOL_INVALID_PARAMS, and MeshSecToolCmacCalculate().
MeshSecToolInit()
void MeshSecToolInit (void)
Mesh Security Toolbox Init.
Returns
None.
MeshSecToolK1Derive()
meshSecToolRetVal_t MeshSecToolK1Derive (uint8_t * pPlainText, uint16_t plainTextSize, uint8_t * pSalt, uint8_t * pTempKeyMaterial, uint16_t tempKeyMaterialSize, meshSecToolKeyDerivationCback_t derivCompleteCback, void * pParam)
Mesh Security Toolbox k1 derivation primitive.
Used to derive Device, Identity and Beacon Keys. Description: k1(N, SALT, P) = CMAC(T, P), T = CMAC(SALT, N), size(SALT) = 16B, size(N) >= 0B, size(P) >= 0B;
Parameters
[in] pPlainText Pointer to plaintext data (P).
[in] plainTextSize Size of the plaintext.
[in] pSalt Pointer to 128-bit Salt.
[in] pTempKeyMaterial Pointer to plaintext used to compute the T key (N).
[in] tempKeyMaterialSize Size of the plaintext used to compute the T key.
[in] derivCompleteCback Callback invoked after derivation is complete.
[in] pParam Pointer to generic callback parameter.
See also
meshSecToolKeyDerivationCback_t
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
References MESH_SEC_TOOL_INVALID_PARAMS.
MeshSecToolK2Derive()
meshSecToolRetVal_t MeshSecToolK2Derive (uint8_t * pPlainText, uint16_t plainTextSize, uint8_t * pTempKeyMaterial, meshSecToolKeyDerivationCback_t derivCompleteCback, void * pParam)
Mesh Security Toolbox k2 derivation primitive.
Used to derive Encryption and Privacy Keys, and NID. Description: k2(N, P) = (T1 || T2 || T3) mod (1 << 263), size(N) = 16B, size(P) >= 1B T = CMAC(SALT, N), SALT = s1("smk2") T0 = empty string, Tn = CMAC(T, (Tn-1 || P || n)), 0 < n < 4
Parameters
[in] pPlainText Pointer to plaintext data (P).
[in] plainTextSize Size of the plaintext (at least 1 byte).
[in] pTempKeyMaterial Pointer to 128-bit plaintext used to compute the T key (N).
[in] derivCompleteCback Callback invoked after derivation is complete.
[in] pParam Pointer to generic callback parameter.
See also
meshSecToolKeyDerivationCback_t
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
Note
This implementation does not allow plainTextSize larger than 15 bytes.
References MESH_SEC_TOOL_AES_BLOCK_SIZE, and MESH_SEC_TOOL_INVALID_PARAMS.
MeshSecToolK3Derive()
meshSecToolRetVal_t MeshSecToolK3Derive (uint8_t * pPlainText, meshSecToolKeyDerivationCback_t derivCompleteCback, void * pParam)
Mesh Security Toolbox k3 derivation primitive.
Used to derive 64 bit Network ID Description: k3(N) = CMAC(T, ("id64" || 0x01)) mod (1 << 64); size(N) = 16B T = CMAC(SALT, N), SALT = s1("smk3")
Parameters
[in] pPlainText Pointer to 128-bit plaintext used to compute the T key (N).
[in] derivCompleteCback Callback invoked after derivation is complete.
[in] pParam Pointer to generic callback parameter.
See also
meshSecToolKeyDerivationCback_t
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
References MESH_SEC_TOOL_INVALID_PARAMS.
MeshSecToolK4Derive()
meshSecToolRetVal_t MeshSecToolK4Derive (uint8_t * pPlainText, meshSecToolKeyDerivationCback_t derivCompleteCback, void * pParam)
Mesh Security Toolbox k4 derivation primitive.
Used to derive 6 bits AID Description: k4(N) = CMAC(T, ("id6" || 0x01)) mod (1 << 6); size(N) = 16B T = CMAC(SALT, N), SALT = s1("smk4")
Parameters
[in] pPlainText Pointer to 128-bit plaintext used to compute the T key (N).
[in] derivCompleteCaback Callback invoked after derivation is complete.
[in] pParam Pointer to generic callback parameter.
See also
meshSecToolKeyDerivationCback_t
Return values
MESH_SUCCESS Request processed succesfully.
MESH_SEC_TOOL_INVALID_PARAMS Invalid parameters in request.
MESH_SEC_TOOL_OUT_OF_MEMORY No resources to process request.
MESH_SEC_TOOL_UNINITIALIZED The algorithm used by this request is not initialized.
MESH_SEC_TOOL_UNKNOWN_ERROR An error occurred in the PAL layer.
Remarks
The caller should not overwrite the memory referenced by input pointers until the callback is triggered.
References MESH_SEC_TOOL_INVALID_PARAMS.
MeshSecUtrDecrypt()
meshSecRetVal_t MeshSecUtrDecrypt (meshSecUtrDecryptParams_t * pReqParams, meshSecUtrDecryptCback_t utrDecryptCompleteCback, void * pParam)
Decrypts upper transport PDU.
Parameters
[in] pReqParams Pointer to decryption setup and storage parameters.
[in] utrDecryptCompleteCback Callback used to signal decryption complete.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS All validation is performed. Decryption starts.
MESH_SEC_INVALID_PARAMS Invalid parameters (E.g.: Mic size invalid, or Label UUID NULL for virtual destination address).
MESH_SEC_KEY_NOT_FOUND Application key index not found to match AID.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
See also
meshSecUtrDecryptParams_t
meshSecUtrDecryptCback_t
References meshSecUtrDecReq_t::aid, meshSecUtrDecryptParams_t::aid, meshSecUtrDecryptParams_t::appPayloadSize, meshSecUtrDecReq_t::cback, meshSecToolCcmParams_t::cbcMacSize, meshSecUtrDecReq_t::ccmParams, meshSecUtrDecryptParams_t::dstAddr, meshSecToolCcmParams_t::inputLen, meshSecUtrDecReq_t::key, meshSecUtrDecReq_t::keySearchIdx, MESH_ADDR_TYPE_UNASSIGNED, MESH_AID_MASK, MESH_AID_SHIFT, MESH_IS_ADDR_UNICAST, MESH_IS_ADDR_VIRTUAL, MESH_SEC_DEVICE_KEY_AID, MESH_SEC_INVALID_PARAMS, MESH_SEC_OUT_OF_MEMORY, MESH_SEQ_MAX_VAL, MESH_SUCCESS, meshSecUtrDecReq_t::netKeyIndex, meshSecUtrDecryptParams_t::netKeyIndex, meshSecUtrDecReq_t::nonce, meshSecUtrDecryptParams_t::pAppPayload, meshSecToolCcmParams_t::pCbcMac, meshSecToolCcmParams_t::pCcmKey, meshSecUtrDecryptParams_t::pEncAppPayload, meshSecToolCcmParams_t::pIn, meshSecToolCcmParams_t::pNonce, meshSecToolCcmParams_t::pOut, meshSecUtrDecReq_t::pParam, meshSecUtrDecryptParams_t::pTransMic, meshSecUtrDecryptParams_t::recvIvIndex, meshSecUtrDecryptParams_t::seqNo, meshSecUtrDecryptParams_t::srcAddr, meshSecUtrDecryptParams_t::transMicSize, meshSecCryptoRequests_t::utrDecReq, meshSecUtrDecReq_t::vtad, and meshSecUtrDecReq_t::vtadSearchIdx.
MeshSecUtrEncrypt()
meshSecRetVal_t MeshSecUtrEncrypt (meshSecUtrEncryptParams_t * pReqParams, meshSecUtrEncryptCback_t utrEncryptCompleteCback, void * pParam)
Encrypts upper transport PDU.
Parameters
[in] pReqParams Pointer to encryption setup and storage parameters.
[in] utrEncryptCompleteCback Callback used to signal encryption complete.
[in] pParam Pointer to generic callback parameter.
Return values
MESH_SUCCESS All validation is performed. Encryption starts.
MESH_SEC_INVALID_PARAMS Invalid parameters (E.g.: Mic size invalid, or Label UUID NULL for virtual destination address).
MESH_SEC_KEY_NOT_FOUND Application key index not found.
MESH_SEC_KEY_MATERIAL_NOT_FOUND There is no AID computed for the application key index. See the remarks section for more information.
MESH_SEC_OUT_OF_MEMORY There are no resources to process the request.
Remarks
The AID can be present for the old key in a Key Refresh Procedure phase, but not for the new key and the phase dictates the new key AID should be returned.
See also
meshSecUtrEncryptParams_t
meshSecUtrEncryptCback_t