Cordio: Mesh Configuration Models
Mesh Configuration Models
Data Structures
struct meshCfgMdlHdr_t
struct meshCfgMdlBeaconStateEvt_t
struct meshCfgMdlCompDataEvt_t
struct meshCfgMdlDefaultTtlStateEvt_t
struct meshCfgMdlGattProxyEvt_t
struct meshCfgMdlRelayCompositeStateEvt_t
struct meshCfgMdlModelPubEvt_t
struct meshCfgMdlModelSubscrChgEvt_t
struct meshCfgMdlModelSubscrListEvt_t
struct meshCfgMdlNetKeyChgEvt_t
struct meshCfgMdlNetKeyListEvt_t
struct meshCfgMdlAppKeyChgEvt_t
struct meshCfgMdlAppKeyListEvt_t
struct meshCfgMdlNodeIdentityEvt_t
struct meshCfgMdlModelAppBindEvt_t
struct meshCfgMdlModelAppListEvt_t
struct meshCfgMdlNodeResetStateEvt_t
struct meshCfgMdlFriendEvt_t
struct meshCfgMdlKeyRefPhaseEvt_t
struct meshCfgMdlHbPubEvt_t
struct meshCfgMdlHbSubEvt_t
struct meshCfgMdlLpnPollTimeoutEvt_t
struct meshCfgMdlNwkTransStateEvt_t
union meshCfgMdlClEvt_t
union meshCfgMdlSrEvt_t
Macros
#define MESH_CFG_MDL_CL_LOCAL_NODE_SR MESH_ADDR_TYPE_UNASSIGNED
#define BSTREAM_TO_CFG_CL_COMP_PG0_HDR(pBuf, len, cid, pid, vid, crpl, feat)
#define BSTREAM_TO_CFG_CL_COMP_PG0_ELEM_HDR(pBuf, len, loc, numS, numV)
#define BSTREAM_TO_CFG_CL_COMP_PG0_SIG_MODEL_ID(pBuf, len, sigId)
#define BSTREAM_TO_CFG_CL_COMP_PG0_VENDOR_MODEL_ID(pBuf, len, vendId)
Typedefs
typedef uint8_t meshCfgMdlEventType_t
typedef uint8_t meshCfgMdlClSubscrAddrOp_t
typedef uint8_t meshCfgMdlClKeyOp_t
typedef void(* meshCfgMdlClCback_t) (meshCfgMdlClEvt_t *pEvt)
typedef void(* meshCfgMdlSrCback_t) (const meshCfgMdlSrEvt_t *pEvt)
Enumerations
enum meshCfgMdlOtaErrCodes
enum meshCfgMdlEventValues
enum meshCfgMdlClEventStatusValues
enum meshCfgMdlClSubscrAddrOpValues
enum meshCfgMdlClKeyOpValues
enum meshCfgMdlSrEventStatusValues
Functions
uint16_t MeshCfgSizeOfEvt (wsfMsgHdr_t *pMeshCfgEvt)
bool_t MeshCfgMsgDeepCopy (wsfMsgHdr_t *pMeshCfgEvtOut, const wsfMsgHdr_t *pMeshCfgEvtIn)
uint32_t MeshCfgMdlClGetRequiredMemory (void)
uint32_t MeshCfgMdlClInit (uint8_t *pFreeMem, uint32_t freeMemSize)
void MeshCfgMdlClRegister (meshCfgMdlClCback_t meshCfgMdlClCback, uint16_t timeoutSeconds)
void MeshCfgMdlClBeaconGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClBeaconSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshBeaconStates_t beaconState)
void MeshCfgMdlClCompDataGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, uint8_t pageNumber)
void MeshCfgMdlClDefaultTtlGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClDefaultTtlSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, uint8_t ttl)
void MeshCfgMdlClGattProxyGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClGattProxySet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshGattProxyStates_t gattProxyState)
void MeshCfgMdlClRelayGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClRelaySet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshRelayStates_t relayState, meshRelayRetransState_t *pRelayRetransState)
void MeshCfgMdlClPubGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
void MeshCfgMdlClPubSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshAddress_t elemAddr, meshAddress_t pubAddr, const uint8_t *pLabelUuid, meshModelPublicationParams_t *pPubParams, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
void MeshCfgMdlClSubscrListChg (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshAddress_t elemAddr, meshCfgMdlClSubscrAddrOp_t opType, meshAddress_t subscrAddr, const uint8_t *pLabelUuid, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
void MeshCfgMdlClSubscrListGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
void MeshCfgMdlClNetKeyChg (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, uint16_t netKeyIndex, meshCfgMdlClKeyOp_t keyOp, const uint8_t *pNetKey)
void MeshCfgMdlClNetKeyGet (meshAddress_t cfgMdlSrAddr, const uint8_t *pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex)
void MeshCfgMdlClAppKeyChg (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, const meshAppNetKeyBind_t *pAppKeyBind, meshCfgMdlClKeyOp_t keyOp, const uint8_t *pAppKey)
void MeshCfgMdlClAppKeyGet (meshAddress_t cfgMdlSrAddr, const uint8_t *pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex, uint16_t netKeyIndex)
void MeshCfgMdlClNodeIdentityGet (meshAddress_t cfgMdlSrAddr, const uint8_t *pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex, uint16_t netKeyIndex)
void MeshCfgMdlClNodeIdentitySet (meshAddress_t cfgMdlSrAddr, const uint8_t *pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex, uint16_t netKeyIndex, meshNodeIdentityStates_t nodeIdentityState)
void MeshCfgMdlClAppBind (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, bool_t bind, uint16_t appKeyIndex, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
void MeshCfgMdlClAppGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
void MeshCfgMdlClNodeReset (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClFriendGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClFriendSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshFriendStates_t friendState)
void MeshCfgMdlClKeyRefPhaseGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, uint16_t netKeyIndex)
void MeshCfgMdlClKeyRefPhaseSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, uint16_t netKeyIndex, meshKeyRefreshTrans_t transition)
void MeshCfgMdlClHbPubGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClHbPubSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshHbPub_t *pHbPubState)
void MeshCfgMdlClHbSubGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClHbSubSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshHbSub_t *pHbSubState)
void MeshCfgMdlClPollTimeoutGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshAddress_t lpnAddr)
void MeshCfgMdlClNwkTransmitGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey)
void MeshCfgMdlClNwkTransmitSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t *pCfgMdlSrDevKey, meshNwkTransState_t *pNwkTransmit)
void MeshCfgMdlSrInit (void)
void MeshCfgMdlSrRegister (meshCfgMdlSrCback_t meshCfgMdlSrCback)
Detailed Description
Data Structure Documentation
meshCfgMdlHdr_t
struct meshCfgMdlHdr_t
Configuration Model header event.
Data Fields
wsfMsgHdr_t hdr
meshAddress_t peerAddress
Field Documentation
hdr
wsfMsgHdr_t hdr
Header structure
peerAddress
meshAddress_t peerAddress
Address of the peer node
meshCfgMdlBeaconStateEvt_t
struct meshCfgMdlBeaconStateEvt_t
Beacon state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshBeaconStates_t state
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
state
meshBeaconStates_t state
Beacon state
meshCfgMdlCompDataEvt_t
struct meshCfgMdlCompDataEvt_t
Key binding information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshCompData_t data
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
data
meshCompData_t data
Composition data
meshCfgMdlDefaultTtlStateEvt_t
struct meshCfgMdlDefaultTtlStateEvt_t
Default TTL state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
uint8_t ttl
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
ttl
uint8_t ttl
Default TTL state
meshCfgMdlGattProxyEvt_t
struct meshCfgMdlGattProxyEvt_t
Key binding information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshGattProxyStates_t gattProxy
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
gattProxy
meshGattProxyStates_t gattProxy
Gatt Proxy state
meshCfgMdlRelayCompositeStateEvt_t
struct meshCfgMdlRelayCompositeStateEvt_t
Relay composite state event containing Relay state and Relay Retransmit Count state.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshRelayStates_t relayState
meshRelayRetransState_t relayRetrans
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
relayRetrans
meshRelayRetransState_t relayRetrans
Relay retransmit state
relayState
meshRelayStates_t relayState
Relay feature state
meshCfgMdlModelPubEvt_t
struct meshCfgMdlModelPubEvt_t
Model Publication state event for both virtual and non-virtual addresses.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshAddress_t elemAddr
meshAddress_t pubAddr
meshModelPublicationParams_t pubParams
modelId_t modelId
bool_t isSig
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
elemAddr
meshAddress_t elemAddr
Address of the element containing the model
isSig
bool_t isSig
TRUE if model identifier is SIG, FALSE for vendor
modelId
modelId_t modelId
Model identifier
pubAddr
meshAddress_t pubAddr
Publish address for the model instance
pubParams
meshModelPublicationParams_t pubParams
Publication parameters
meshCfgMdlModelSubscrChgEvt_t
struct meshCfgMdlModelSubscrChgEvt_t
Model Subscription List changed event for both virtual and non-virtual addresses.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshAddress_t elemAddr
meshAddress_t subscrAddr
modelId_t modelId
bool_t isSig
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
elemAddr
meshAddress_t elemAddr
Address of the element containing the model
isSig
bool_t isSig
TRUE if model identifier is SIG, FALSE for vendor
modelId
modelId_t modelId
Model identifier
subscrAddr
meshAddress_t subscrAddr
Subscription address for the model instance
meshCfgMdlModelSubscrListEvt_t
struct meshCfgMdlModelSubscrListEvt_t
Model Subscription List event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshAddress_t elemAddr
modelId_t modelId
bool_t isSig
meshAddress_t * pSubscrList
uint8_t subscrListSize
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
elemAddr
meshAddress_t elemAddr
Address of the element containing the model
isSig
bool_t isSig
TRUE if model identifier is SIG, FALSE for vendor
modelId
modelId_t modelId
Model identifier
pSubscrList
meshAddress_t* pSubscrList
Pointer to the model Subscription List.
subscrListSize
uint8_t subscrListSize
Subscription List size.
meshCfgMdlNetKeyChgEvt_t
struct meshCfgMdlNetKeyChgEvt_t
NetKey changed information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
uint16_t netKeyIndex
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
netKeyIndex
uint16_t netKeyIndex
NetKey Index
meshCfgMdlNetKeyListEvt_t
struct meshCfgMdlNetKeyListEvt_t
NetKeyList information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshNetKeyList_t netKeyList
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
netKeyList
meshNetKeyList_t netKeyList
NetKey list
meshCfgMdlAppKeyChgEvt_t
struct meshCfgMdlAppKeyChgEvt_t
AppKey changed information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshAppNetKeyBind_t bind
Field Documentation
bind
meshAppNetKeyBind_t bind
Key binding
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
meshCfgMdlAppKeyListEvt_t
struct meshCfgMdlAppKeyListEvt_t
AppKey List information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshAppKeyList_t appKeyList
Field Documentation
appKeyList
meshAppKeyList_t appKeyList
AppKey list
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
meshCfgMdlNodeIdentityEvt_t
struct meshCfgMdlNodeIdentityEvt_t
Node Identity information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
uint16_t netKeyIndex
meshNodeIdentityStates_t state
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
netKeyIndex
uint16_t netKeyIndex
NetKey Index.
state
meshNodeIdentityStates_t state
Node identity state.
meshCfgMdlModelAppBindEvt_t
struct meshCfgMdlModelAppBindEvt_t
Model to AppKey Bind information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
uint16_t appKeyIndex
meshAddress_t elemAddr
modelId_t modelId
bool_t isSig
Field Documentation
appKeyIndex
uint16_t appKeyIndex
AppKey Index bound to model
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
elemAddr
meshAddress_t elemAddr
Address of the element containing the model
isSig
bool_t isSig
TRUE if model identifier is SIG, FALSE for vendor
modelId
modelId_t modelId
Model identifier
meshCfgMdlModelAppListEvt_t
struct meshCfgMdlModelAppListEvt_t
Model to AppKey List information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshModelAppList_t modelAppList
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
modelAppList
meshModelAppList_t modelAppList
Model AppKey List.
meshCfgMdlNodeResetStateEvt_t
struct meshCfgMdlNodeResetStateEvt_t
Node Reset state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
meshCfgMdlFriendEvt_t
struct meshCfgMdlFriendEvt_t
Friend state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshFriendStates_t friendState
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
friendState
meshFriendStates_t friendState
Friend state
meshCfgMdlKeyRefPhaseEvt_t
struct meshCfgMdlKeyRefPhaseEvt_t
Key binding information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
uint16_t netKeyIndex
meshKeyRefreshStates_t keyRefState
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
keyRefState
meshKeyRefreshStates_t keyRefState
Key Refresh Phase state
netKeyIndex
uint16_t netKeyIndex
Global identifier of the Network Key
meshCfgMdlHbPubEvt_t
struct meshCfgMdlHbPubEvt_t
Heartbeat Publication state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshHbPub_t hbPub
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
hbPub
meshHbPub_t hbPub
Heartbeat Publication state
meshCfgMdlHbSubEvt_t
struct meshCfgMdlHbSubEvt_t
Heartbeat Subscription state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshHbSub_t hbSub
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
hbSub
meshHbSub_t hbSub
Heartbeat Subscription state
meshCfgMdlLpnPollTimeoutEvt_t
struct meshCfgMdlLpnPollTimeoutEvt_t
PollTimeout information event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
uint16_t lpnAddr
uint32_t pollTimeout100Ms
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
lpnAddr
uint16_t lpnAddr
Primary element address of the Low Power node
pollTimeout100Ms
uint32_t pollTimeout100Ms
PollTimeout timer value in units of 100 ms
meshCfgMdlNwkTransStateEvt_t
struct meshCfgMdlNwkTransStateEvt_t
Network Transmit state event.
Data Fields
meshCfgMdlHdr_t cfgMdlHdr
meshNwkTransState_t nwkTransState
Field Documentation
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure
nwkTransState
meshNwkTransState_t nwkTransState
Network Transmit state
meshCfgMdlClEvt_t
union meshCfgMdlClEvt_t
Configuration Client event
Attention
If the operation status (hdr.status) is not success or an OTA error code, then only the hdr and cfgMdlHdr structure of any event contains valid information.
Data Fields
wsfMsgHdr_t hdr
meshCfgMdlHdr_t cfgMdlHdr
meshCfgMdlBeaconStateEvt_t beacon
meshCfgMdlCompDataEvt_t compData
meshCfgMdlDefaultTtlStateEvt_t defaultTtl
meshCfgMdlGattProxyEvt_t gattProxy
meshCfgMdlRelayCompositeStateEvt_t relayComposite
meshCfgMdlModelPubEvt_t modelPub
meshCfgMdlModelSubscrChgEvt_t subscrChg
meshCfgMdlModelSubscrListEvt_t subscrList
meshCfgMdlNetKeyChgEvt_t netKeyChg
meshCfgMdlNetKeyListEvt_t netKeyList
meshCfgMdlAppKeyChgEvt_t appKeyChg
meshCfgMdlAppKeyListEvt_t appKeyList
meshCfgMdlNodeIdentityEvt_t nodeIdentity
meshCfgMdlModelAppBindEvt_t modelAppBind
meshCfgMdlModelAppListEvt_t modelAppList
meshCfgMdlNodeResetStateEvt_t nodeReset
meshCfgMdlFriendEvt_t friendState
meshCfgMdlKeyRefPhaseEvt_t keyRefPhase
meshCfgMdlHbPubEvt_t hbPub
meshCfgMdlHbSubEvt_t hbSub
meshCfgMdlLpnPollTimeoutEvt_t pollTimeout
meshCfgMdlNwkTransStateEvt_t nwkTrans
Field Documentation
appKeyChg
meshCfgMdlAppKeyChgEvt_t appKeyChg
Valid if event is MESH_CFG_MDL_APPKEY_ADD_EVENT or MESH_CFG_MDL_APPKEY_DEL_EVENT or MESH_CFG_MDL_APPKEY_UPDT_EVENT
appKeyList
meshCfgMdlAppKeyListEvt_t appKeyList
Valid if event is MESH_CFG_MDL_APPKEY_GET_EVENT
beacon
meshCfgMdlBeaconStateEvt_t beacon
Valid if event is MESH_CFG_MDL_BEACON_GET_EVENT or MESH_CFG_MDL_BEACON_SET_EVENT or
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure extension for Configuration Model events.
compData
meshCfgMdlCompDataEvt_t compData
Valid if event is MESH_CFG_MDL_COMP_PAGE_GET_EVENT
defaultTtl
meshCfgMdlDefaultTtlStateEvt_t defaultTtl
Valid if event is MESH_CFG_MDL_DEFAULT_TTL_GET_EVENT or MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT or
friendState
meshCfgMdlFriendEvt_t friendState
Valid if event is MESH_CFG_MDL_FRIEND_GET_EVENT or MESH_CFG_MDL_FRIEND_SET_EVENT
gattProxy
meshCfgMdlGattProxyEvt_t gattProxy
Valid if event is MESH_CFG_MDL_GATT_PROXY_GET_EVENT or MESH_CFG_MDL_GATT_PROXY_SET_EVENT
hbPub
meshCfgMdlHbPubEvt_t hbPub
Valid if event is MESH_CFG_MDL_HB_PUB_GET_EVENT or MESH_CFG_MDL_HB_PUB_SET_EVENT
hbSub
meshCfgMdlHbSubEvt_t hbSub
Valid if event is MESH_CFG_MDL_HB_SUB_GET_EVENT or MESH_CFG_MDL_HB_SUB_SET_EVENT
hdr
wsfMsgHdr_t hdr
Header structure. This is used for all events in case the status field is MESH_CFG_MDL_CL_OUT_OF_RESOURCES or MESH_CFG_MDL_CL_INVALID_PARAMS or MESH_CFG_MDL_CL_TIMEOUT or MESH_CFG_MDL_CL_UNKOWN_ERROR. For these error codes, the param field contains the server address
keyRefPhase
meshCfgMdlKeyRefPhaseEvt_t keyRefPhase
Valid if event is MESH_CFG_MDL_KEY_REF_PHASE_GET_EVENT or MESH_CFG_MDL_KEY_REF_PHASE_SET_EVENT
modelAppBind
meshCfgMdlModelAppBindEvt_t modelAppBind
Valid if event is MESH_CFG_MDL_APP_BIND_EVENT or MESH_CFG_MDL_APP_UNBIND_EVENT
modelAppList
meshCfgMdlModelAppListEvt_t modelAppList
Valid if event is MESH_CFG_MDL_APP_SIG_GET_EVENT or MESH_CFG_MDL_APP_VENDOR_GET_EVENT
modelPub
meshCfgMdlModelPubEvt_t modelPub
Valid if event is MESH_CFG_MDL_PUB_GET_EVENT or MESH_CFG_MDL_PUB_SET_EVENT or MESH_CFG_MDL_PUB_VIRT_SET_EVENT
netKeyChg
meshCfgMdlNetKeyChgEvt_t netKeyChg
Valid if event is MESH_CFG_MDL_NETKEY_ADD_EVENT or MESH_CFG_MDL_NETKEY_DEL_EVENT or MESH_CFG_MDL_NETKEY_UPDT_EVENT
netKeyList
meshCfgMdlNetKeyListEvt_t netKeyList
Valid if event is MESH_CFG_MDL_NETKEY_GET_EVENT
nodeIdentity
meshCfgMdlNodeIdentityEvt_t nodeIdentity
Valid if event is MESH_CFG_MDL_NODE_IDENTITY_GET_EVENT or MESH_CFG_MDL_NODE_IDENTITY_SET_EVENT
nodeReset
meshCfgMdlNodeResetStateEvt_t nodeReset
Valid if event is MESH_CFG_MDL_NODE_RESET_EVENT
nwkTrans
meshCfgMdlNwkTransStateEvt_t nwkTrans
Valid if event is MESH_CFG_MDL_NWK_TRANS_GET_EVENT or MESH_CFG_MDL_NWK_TRANS_SET_EVENT
pollTimeout
meshCfgMdlLpnPollTimeoutEvt_t pollTimeout
Valid if event is MESH_CFG_MDL_LPN_POLLTIMEOUT_GET_EVENT
relayComposite
meshCfgMdlRelayCompositeStateEvt_t relayComposite
Valid if event is MESH_CFG_MDL_RELAY_GET_EVENT or MESH_CFG_MDL_RELAY_SET_EVENT
subscrChg
meshCfgMdlModelSubscrChgEvt_t subscrChg
Valid if event is MESH_CFG_MDL_SUBSCR_ADD_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_ADD_EVENT or MESH_CFG_MDL_SUBSCR_DEL_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_DEL_EVENT or MESH_CFG_MDL_SUBSCR_OVR_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_OVR_EVENT or MESH_CFG_MDL_SUBSCR_DEL_ALL_EVENT
subscrList
meshCfgMdlModelSubscrListEvt_t subscrList
Valid if event is MESH_CFG_MDL_SUBSCR_SIG_GET_EVENT or MESH_CFG_MDL_SUBSCR_VENDOR_GET_EVENT
meshCfgMdlSrEvt_t
union meshCfgMdlSrEvt_t
Configuration Server event.
Data Fields
wsfMsgHdr_t hdr
meshCfgMdlHdr_t cfgMdlHdr
meshCfgMdlBeaconStateEvt_t beacon
meshCfgMdlDefaultTtlStateEvt_t defaultTtl
meshCfgMdlGattProxyEvt_t gattProxy
meshCfgMdlRelayCompositeStateEvt_t relayComposite
meshCfgMdlModelPubEvt_t modelPub
meshCfgMdlModelSubscrChgEvt_t subscrChg
meshCfgMdlNetKeyChgEvt_t netKeyChg
meshCfgMdlAppKeyChgEvt_t appKeyChg
meshCfgMdlNodeIdentityEvt_t nodeIdentity
meshCfgMdlModelAppBindEvt_t modelAppBind
meshCfgMdlNodeResetStateEvt_t nodeReset
meshCfgMdlFriendEvt_t friendState
meshCfgMdlKeyRefPhaseEvt_t keyRefPhase
meshCfgMdlHbPubEvt_t hbPub
meshCfgMdlHbSubEvt_t hbSub
meshCfgMdlNwkTransStateEvt_t nwkTrans
Field Documentation
appKeyChg
meshCfgMdlAppKeyChgEvt_t appKeyChg
Valid if event is MESH_CFG_MDL_APPKEY_ADD_EVENT or MESH_CFG_MDL_APPKEY_DEL_EVENT or MESH_CFG_MDL_APPKEY_UPDT_EVENT
beacon
meshCfgMdlBeaconStateEvt_t beacon
Valid if event is MESH_CFG_MDL_BEACON_SET_EVENT
cfgMdlHdr
meshCfgMdlHdr_t cfgMdlHdr
Header structure extension for Configuration Model events.
defaultTtl
meshCfgMdlDefaultTtlStateEvt_t defaultTtl
Valid if event is MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT
friendState
meshCfgMdlFriendEvt_t friendState
Valid if event is MESH_CFG_MDL_FRIEND_SET_EVENT
gattProxy
meshCfgMdlGattProxyEvt_t gattProxy
Valid if event is MESH_CFG_MDL_GATT_PROXY_SET_EVENT
hbPub
meshCfgMdlHbPubEvt_t hbPub
Valid if event is MESH_CFG_MDL_HB_PUB_SET_EVENT
hbSub
meshCfgMdlHbSubEvt_t hbSub
Valid if event is MESH_CFG_MDL_HB_SUB_SET_EVENT
hdr
wsfMsgHdr_t hdr
Header structure
keyRefPhase
meshCfgMdlKeyRefPhaseEvt_t keyRefPhase
Valid if event is MESH_CFG_MDL_KEY_REF_PHASE_SET_EVENT
modelAppBind
meshCfgMdlModelAppBindEvt_t modelAppBind
Valid if event is MESH_CFG_MDL_APP_BIND_EVENT or MESH_CFG_MDL_APP_UNBIND_EVENT
modelPub
meshCfgMdlModelPubEvt_t modelPub
Valid if event is MESH_CFG_MDL_PUB_SET_EVENT or MESH_CFG_MDL_PUB_VIRT_SET_EVENT
netKeyChg
meshCfgMdlNetKeyChgEvt_t netKeyChg
Valid if event is MESH_CFG_MDL_NETKEY_ADD_EVENT or MESH_CFG_MDL_NETKEY_DEL_EVENT or MESH_CFG_MDL_NETKEY_UPDT_EVENT
nodeIdentity
meshCfgMdlNodeIdentityEvt_t nodeIdentity
Valid if event is MESH_CFG_MDL_NODE_IDENTITY_SET_EVENT
nodeReset
meshCfgMdlNodeResetStateEvt_t nodeReset
Valid if event is MESH_CFG_MDL_NODE_RESET_EVENT
nwkTrans
meshCfgMdlNwkTransStateEvt_t nwkTrans
Valid if event is MESH_CFG_MDL_NWK_TRANS_SET_EVENT
relayComposite
meshCfgMdlRelayCompositeStateEvt_t relayComposite
Valid if event is MESH_CFG_MDL_RELAY_SET_EVENT
subscrChg
meshCfgMdlModelSubscrChgEvt_t subscrChg
Valid if event is MESH_CFG_MDL_SUBSCR_ADD_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_ADD_EVENT or MESH_CFG_MDL_SUBSCR_DEL_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_DEL_EVENT or MESH_CFG_MDL_SUBSCR_OVR_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_OVR_EVENT or MESH_CFG_MDL_SUBSCR_DEL_ALL_EVENT
Macro Definition Documentation
BSTREAM_TO_CFG_CL_COMP_PG0_ELEM_HDR
#define BSTREAM_TO_CFG_CL_COMP_PG0_ELEM_HDR (pBuf, len, loc, numS, numV)
Value:
do                                    \
                                       {                                     \
                                         if((len) < 4)                       \
                                         {                                   \
                                           (len) = 0;  (loc) = 0;            \
                                           (numS) = 0; (numV)=0;             \
                                         }                                   \
                                         else                                \
                                         {                                   \
                                            BSTREAM_TO_UINT16((loc), (pBuf));\
                                            BSTREAM_TO_UINT8((numS), (pBuf));\
                                            BSTREAM_TO_UINT8((numV), (pBuf));\
                                            (len) -= 4;                      \
                                         }                                   \
                                       } while (0)
Mesh Configuration Client Composition Page 0 stream parser macros for element header.
Note
pBuf is remaining of Page 0 raw byte array, len is the remaining length. loc = location descriptor (2 bytes); numS = number of SIG models on this element (1 byte); numV = number of Vendor models on this element (1 byte);
BSTREAM_TO_CFG_CL_COMP_PG0_HDR
#define BSTREAM_TO_CFG_CL_COMP_PG0_HDR (pBuf, len, cid, pid, vid, crpl, feat)
Value:
do                                    \
                                       {                                     \
                                         BSTREAM_TO_UINT16((cid), (pBuf));   \
                                         (len) -= 2;                         \
                                         BSTREAM_TO_UINT16((pid), (pBuf));   \
                                         (len) -= 2;                         \
                                         BSTREAM_TO_UINT16((vid), (pBuf));   \
                                         (len) -= 2;                         \
                                         BSTREAM_TO_UINT16((crpl), (pBuf));  \
                                         (len) -= 2;                         \
                                         BSTREAM_TO_UINT16((feat), (pBuf));  \
                                         (len) -= 2;                         \
                                       } while (0)
Mesh Configuration Client Composition Page 0 stream parser macros for page header.
Note
pBuf is Page 0 raw byte array, len is the initial length. cid = company ID (2 bytes); pid = product ID (2 bytes); vid = version ID (2 bytes); crpl = minimum number of replay protection list entries in a device (2 bytes); feat = features (see meshFeatures_t);
BSTREAM_TO_CFG_CL_COMP_PG0_SIG_MODEL_ID
#define BSTREAM_TO_CFG_CL_COMP_PG0_SIG_MODEL_ID (pBuf, len, sigId)
Value:
do                                      \
                                       {                                       \
                                         if((len) < sizeof(meshSigModelId_t))  \
                                         {                                     \
                                           (len) = 0;                          \
                                           (sigId) = 0x0000;                   \
                                         }                                     \
                                         else                                  \
                                         {                                     \
                                            BSTREAM_TO_UINT16((sigId), (pBuf));\
                                            (len) -= sizeof(meshSigModelId_t); \
                                         }                                     \
                                       } while (0)
Mesh Configuration Client Composition Page 0 stream parser macros for SIG models.
Note
pBuf is remaining of Page 0 raw byte array, len is the remaining length. sigId = SIG model ID (2 bytes);
BSTREAM_TO_CFG_CL_COMP_PG0_VENDOR_MODEL_ID
#define BSTREAM_TO_CFG_CL_COMP_PG0_VENDOR_MODEL_ID (pBuf, len, vendId)
Value:
do                                         \
                                       {                                          \
                                         if((len) < sizeof(meshVendorModelId_t))  \
                                         {                                        \
                                           (len) = 0;                             \
                                           (vendId) = 0x0000;                     \
                                         }                                        \
                                         else                                     \
                                         {                                        \
                                            BSTREAM_TO_UINT32((vendId), (pBuf));  \
                                            (len) -= sizeof(meshVendorModelId_t); \
                                         }                                        \
                                       } while (0)
Mesh Configuration Client Composition Page 0 stream parser macros for Vendor models.
Note
pBuf is remaining of Page 0 raw byte array, len is the remaining length. vendId = Vendor model ID (4 bytes);
Remarks
PAGE 0 structure: Page Header | [Elem X HDR | Elem X SIG IDs | Elem X Vendor IDs]...
Stream macros for Composition Data Page 0 must be used in a specific order. See code.
uint16_t cid, pid, vid, crpl, locDescr;
uint8_t numS, numV;
meshFeatures_t feat;
meshSigModelId_t sigModelId;
meshVendorModelId_t vendModelId;
// Extract header.
BSTREAM_TO_CFG_CL_COMP_PG0_HDR(pPg0, len, cid, pid, vid, crpl, feat);
// Print header.
PRINT_NUM("COMPANY ID", cid);
PRINT_NUM("PRODUCT ID", pid);
PRINT_NUM("VERSION ID", vid);
PRINT_NUM("Replay protection number of entries", crpl);
if (feat & MESH_FEAT_RELAY)
{
  PRINT("Relay supported");
}
if (feat & MESH_FEAT_PROXY)
{
  PRINT("Proxy supported");
}
if (feat & MESH_FEAT_FRIEND)
{
  PRINT("Friend supported");
}
if (feat & MESH_FEAT_LOW_POWER)
{
  PRINT("LPN supported");
}
uint8_t i = 0;
while (len > 0)
{
  // First get element header.
  BSTREAM_TO_CFG_CL_COMP_PG0_ELEM_HDR(pPg0, len, locDescr, numS, numV);
  PRINT_NUM("Element", i);
  i++;
  PRINT("Element information: ");
  PRINT_NUM("Location descriptor", locDescr);
  // Then get all SIG models for this element
  while ((len != 0) && numS != 0)
  {
    // Get SIG model ID.
    BSTREAM_TO_CFG_CL_COMP_PG0_SIG_MODEL_ID(pPg0, len, sigModelId);
    PRINT_NUM("SIG MODEL ID", sigModelId);
    numS--;
  }
  // Finally get all Vendor models for this element
  while ((len != 0) && numV != 0)
  {
    // Get Vendor model ID.
    BSTREAM_TO_CFG_CL_COMP_PG0_VENDOR_MODEL_ID(pPg0, len, vendModelId);
    PRINT_NUM("VENDOR MODEL ID", vendModelId);
    numV--;
  }
}
Typedef Documentation
meshCfgMdlClCback_t
typedef void(* meshCfgMdlClCback_t) (meshCfgMdlClEvt_t *pEvt)
Callback for informing the upper layer that a requested operation has completed.
Parameters
[in] pEvt Pointer to Configuration Client event.
Returns
None.
See also
meshCfgMdlClEvt_t
meshCfgMdlEventType_t
typedef uint8_t meshCfgMdlEventType_t
Configuration model callback event type (used in wsfMsgHdr_t.event). See meshCfgMdlEventValues
meshCfgMdlSrCback_t
typedef void(* meshCfgMdlSrCback_t) (const meshCfgMdlSrEvt_t *pEvt)
Notification callback triggered after a Configuration Client modifies a local state.
Parameters
[in] pEvt Pointer to the event structure.
Returns
None.
Enumeration Type Documentation
meshCfgMdlClEventStatusValues
enum meshCfgMdlClEventStatusValues
Configuration Client event status. Applicable to all event types.
Enumerator
MESH_CFG_MDL_CL_SUCCESS
Operation completed without errors
MESH_CFG_MDL_CL_OUT_OF_RESOURCES
Client has no resources to perform the procedure
MESH_CFG_MDL_CL_INVALID_PARAMS
Parameters passed to the API are not valid
MESH_CFG_MDL_CL_TIMEOUT
No response received from the Configuration Server
MESH_CFG_MDL_CL_UNKOWN_ERROR
Unknown error
MESH_CFG_MDL_CL_REMOTE_ERROR_BASE
Start of procedure-specific codes for errors received from Server. Error codes above this value are obtained by subtracting base from the error code and comparing to meshCfgMdlOtaErrCodes.
meshCfgMdlClKeyOpValues
enum meshCfgMdlClKeyOpValues
Operations that can be performed over an AppKey or a NetKey.
Enumerator
MESH_CFG_MDL_CL_KEY_ADD
AppKey or NetKey Add
MESH_CFG_MDL_CL_KEY_UPDT
AppKey or NetKey Update
MESH_CFG_MDL_CL_KEY_DEL
AppKey or NetKey Delete
MESH_CFG_MDL_CL_KEY_UNDEFINED
Undefined Op Value
meshCfgMdlClSubscrAddrOpValues
enum meshCfgMdlClSubscrAddrOpValues
Operations that can be performed over the Subscription List of a model.
Enumerator
MESH_CFG_MDL_CL_SUBSCR_ADDR_ADD
Subscription Address Add. Generates MESH_CFG_MDL_SUBSCR_ADD_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_ADD_EVENT event
MESH_CFG_MDL_CL_SUBSCR_ADDR_DEL
Subscription Address Delete. Generates MESH_CFG_MDL_SUBSCR_DEL_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_DEL_EVENT event
MESH_CFG_MDL_CL_SUBSCR_ADDR_OVR
Subscription Address Overwrite. Generates MESH_CFG_MDL_SUBSCR_OVR_EVENT or MESH_CFG_MDL_SUBSCR_VIRT_OVR_EVENT event
MESH_CFG_MDL_CL_SUBSCR_ADDR_DEL_ALL
Subscription Address Delete All. Generates MESH_CFG_MDL_SUBSCR_DEL_ALL_EVENT event
meshCfgMdlEventValues
enum meshCfgMdlEventValues
Enumeration of the configuration model events triggered by the configuration model API. The list is shared by both the Configuration Client and the Configuration Server.
Remarks
Each event in the list is notified at the end of the corresponding operation of the Configuration Client.
The Configuration Server can optionally notify events that modify states. This means that "get" and "list" events are never notified by a Configuration Server.
Enumerator
MESH_CFG_MDL_BEACON_GET_EVENT
Config Model Beacon Get operation complete
MESH_CFG_MDL_BEACON_SET_EVENT
Config Model Beacon Set operation complete
MESH_CFG_MDL_COMP_PAGE_GET_EVENT
Config Model Composition Page Get operation complete
MESH_CFG_MDL_DEFAULT_TTL_GET_EVENT
Config Model Default TTL Get operation complete
MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT
Config Model Default TTL Set operation complete
MESH_CFG_MDL_GATT_PROXY_GET_EVENT
Config Model Gatt Proxy Get operation complete
MESH_CFG_MDL_GATT_PROXY_SET_EVENT
Config Model Gatt Proxy Set operation complete
MESH_CFG_MDL_RELAY_GET_EVENT
Config Model Relay Get operation complete
MESH_CFG_MDL_RELAY_SET_EVENT
Config Model Relay Set operation complete
MESH_CFG_MDL_PUB_GET_EVENT
Config Model Model Publication Get complete
MESH_CFG_MDL_PUB_SET_EVENT
Config Model Model Publication Set complete
MESH_CFG_MDL_PUB_VIRT_SET_EVENT
Config Model Model Publication Virtual Set complete
MESH_CFG_MDL_SUBSCR_ADD_EVENT
Config Model Subscription Add.
MESH_CFG_MDL_SUBSCR_VIRT_ADD_EVENT
Config Model Subscription Virtual Address Add.
MESH_CFG_MDL_SUBSCR_DEL_EVENT
Config Model Subscription Delete.
MESH_CFG_MDL_SUBSCR_VIRT_DEL_EVENT
Config Model Subscription Virtual Address Delete.
MESH_CFG_MDL_SUBSCR_OVR_EVENT
Config Model Subscription Overwrite.
MESH_CFG_MDL_SUBSCR_VIRT_OVR_EVENT
Config Model Subscription Virtual Address Overwrite.
MESH_CFG_MDL_SUBSCR_DEL_ALL_EVENT
Config Model Subscription Delete All.
MESH_CFG_MDL_SUBSCR_SIG_GET_EVENT
Config Model SIG Model Subscription List Get.
MESH_CFG_MDL_SUBSCR_VENDOR_GET_EVENT
Config Model Vendor Model Subscription List Get.
MESH_CFG_MDL_NETKEY_ADD_EVENT
Config Model NetKey Add operation complete
MESH_CFG_MDL_NETKEY_UPDT_EVENT
Config Model NetKey Update operation complete
MESH_CFG_MDL_NETKEY_DEL_EVENT
Config Model NetKey Delete operation complete
MESH_CFG_MDL_NETKEY_GET_EVENT
Config Model NetKey Get operation complete
MESH_CFG_MDL_APPKEY_ADD_EVENT
Config Model AppKey Add operation complete
MESH_CFG_MDL_APPKEY_UPDT_EVENT
Config Model AppKey Update operation complete
MESH_CFG_MDL_APPKEY_DEL_EVENT
Config Model AppKey Delete operation complete
MESH_CFG_MDL_APPKEY_GET_EVENT
Config Model AppKey Get operation complete
MESH_CFG_MDL_NODE_IDENTITY_GET_EVENT
Config Model Node Identity Get operation complete
MESH_CFG_MDL_NODE_IDENTITY_SET_EVENT
Config Model Node Identity Set operation complete
MESH_CFG_MDL_APP_BIND_EVENT
Config Model App Bind operation complete
MESH_CFG_MDL_APP_UNBIND_EVENT
Config Model App Unbind operation complete
MESH_CFG_MDL_APP_SIG_GET_EVENT
Config Model SIG Model App Get operation complete
MESH_CFG_MDL_APP_VENDOR_GET_EVENT
Config Model Vendor Model App Get operation complete
MESH_CFG_MDL_NODE_RESET_EVENT
Config Model Node Reset operation complete
MESH_CFG_MDL_FRIEND_GET_EVENT
Config Model Friend Get operation complete
MESH_CFG_MDL_FRIEND_SET_EVENT
Config Model Friend Set operation complete
MESH_CFG_MDL_KEY_REF_PHASE_GET_EVENT
Config Model Key Refresh Phase Get operation complete
MESH_CFG_MDL_KEY_REF_PHASE_SET_EVENT
Config Model Key Refresh Phase Set operation complete
MESH_CFG_MDL_HB_PUB_GET_EVENT
Config Model Heartbeat Publication Get
MESH_CFG_MDL_HB_PUB_SET_EVENT
Config Model Heartbeat Publication Set
MESH_CFG_MDL_HB_SUB_GET_EVENT
Config Model Heartbeat Subscription Get
MESH_CFG_MDL_HB_SUB_SET_EVENT
Config Model Heartbeat Subscription Set
MESH_CFG_MDL_LPN_POLLTIMEOUT_GET_EVENT
Config Model Low Power Node Poll Timeout Get
MESH_CFG_MDL_NWK_TRANS_GET_EVENT
Config Model Network Transmit Get operation complete
MESH_CFG_MDL_NWK_TRANS_SET_EVENT
Config Model Network Transmit Set operation complete
MESH_CFG_MDL_MAX_EVENT
Maximum number of Config Model events
meshCfgMdlOtaErrCodes
enum meshCfgMdlOtaErrCodes
Table 4.108. Status code messages for messages that contain a Status parameter.
Enumerator
MESH_CFG_MDL_ERR_INVALID_ADDR
Invalid Address
MESH_CFG_MDL_ERR_INVALID_MODEL
Invalid Model
MESH_CFG_MDL_ERR_INVALID_APPKEY_INDEX
Invalid AppKey Index
MESH_CFG_MDL_ERR_INVALID_NETKEY_INDEX
Invalid NetKey Index
MESH_CFG_MDL_ERR_INSUFFICIENT_RESOURCES
Insufficient Resources
MESH_CFG_MDL_ERR_KEY_INDEX_EXISTS
Key Index Already Stored
MESH_CFG_MDL_ERR_INVALID_PUB_PARAMS
Invalid Publish Parameters
MESH_CFG_MDL_ERR_NOT_SUBSCRIBE_MODEL
Not a Subscribe Model
MESH_CFG_MDL_ERR_STORAGE_FAILURE
Storage Failure
MESH_CFG_MDL_ERR_FEATURE_NOT_SUPPORTED
Feature Not Supported
MESH_CFG_MDL_ERR_CANNOT_UPDATE
Cannot Update
MESH_CFG_MDL_ERR_CANNOT_REMOVE
Cannot Update
MESH_CFG_MDL_ERR_CANNOT_BIND
Cannot Bind
MESH_CFG_MDL_ERR_TEMP_UNABLE_TO_CHG_STATE
Temporarily Unable to Change State
MESH_CFG_MDL_ERR_CANNOT_SET
Cannot Set
MESH_CFG_MDL_ERR_UNSPECIFIED
Unspecified Error
MESH_CFG_MDL_ERR_INVALID_BINDING
Invalid Binding
MESH_CFG_MDL_ERR_RFU_START
RFU
MESH_CFG_MDL_ERR_RFU_END
RFU
meshCfgMdlSrEventStatusValues
enum meshCfgMdlSrEventStatusValues
Configuration Server event status. Applicable to all event types.
Enumerator
MESH_CFG_MDL_SR_SUCCESS
A state change has completed without errors
Function Documentation
MeshCfgMdlClAppBind()
void MeshCfgMdlClAppBind (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, bool_t bind, uint16_t appKeyIndex, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
Binds or unbinds a model to an AppKey.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] bind TRUE to bind model to AppKey, FALSE to unbind.
[in] appKeyIndex Global identifier of the AppKey to be (un)bound to the model.
[in] elemAddr Address of the element containing the model.
[in] sigModelId SIG model identifier.
[in] vendorModelId Vendor model identifier.
[in] isSig TRUE if SIG model identifier should be used, FALSE for vendor.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_APP_BIND_EVENT, MESH_CFG_MDL_APP_UNBIND_EVENT
Returns
None.
MeshCfgMdlClAppGet()
void MeshCfgMdlClAppGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
Gets a list of AppKeys bound to a model.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] elemAddr Address of the element containing the model.
[in] sigModelId SIG model identifier.
[in] vendorModelId Vendor model identifier.
[in] isSig TRUE if SIG model identifier should be used, FALSE for vendor.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_APP_SIG_GET_EVENT, MESH_CFG_MDL_APP_VENDOR_GET_EVENT
Returns
None.
MeshCfgMdlClAppKeyChg()
void MeshCfgMdlClAppKeyChg (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, const meshAppNetKeyBind_t * pAppKeyBind, meshCfgMdlClKeyOp_t keyOp, const uint8_t * pAppKey)
Modifies an AppKey.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] pAppKeyBind Pointer to bind definition for the Application Key.
[in] keyOp Key Operation.
[in] pAppKey Pointer to memory holding the Application Key.
See also
meshCfgMdlClEvent_t, MESH_CFG_MDL_APPKEY_ADD_EVENT, MESH_CFG_MDL_APPKEY_UPDT_EVENT, MESH_CFG_MDL_APPKEY_DEL_EVENT
Returns
None.
Remarks
If the operation is MESH_CFG_MDL_CL_KEY_DEL, pAppKey is ignored.
References meshCfgMdlClOpReqParams_t::apiEvt, meshAppNetKeyBind_t::appKeyIndex, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, MESH_APP_KEY_INDEX_MAX_VAL, MESH_CFG_MDL_APPKEY_ADD_EVENT, MESH_CFG_MDL_APPKEY_DEL_EVENT, MESH_CFG_MDL_APPKEY_UPDT_EVENT, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_CL_KEY_ADD, MESH_CFG_MDL_CL_KEY_DEL, MESH_CFG_MDL_CL_KEY_UPDT, MESH_KEY_SIZE_128, MESH_NET_KEY_INDEX_MAX_VAL, meshAppNetKeyBind_t::netKeyIndex, wsfMsgHdr_t::param, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, wsfMsgHdr_t::status, and WsfMsgSend().
MeshCfgMdlClAppKeyGet()
void MeshCfgMdlClAppKeyGet (meshAddress_t cfgMdlSrAddr, const uint8_t * pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex, uint16_t netKeyIndex)
Gets an AppKey List.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] netKeyIndex NetKey Index for which bound AppKeys indexes are read.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_APPKEY_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_APPKEY_GET_EVENT, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_SR_EVENT, MESH_NET_KEY_INDEX_MAX_VAL, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClBeaconGet()
void MeshCfgMdlClBeaconGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets a Secure Network Beacon state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_BEACON_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, MESH_CFG_MDL_BEACON_GET_EVENT, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_SR_EVENT, wsfMsgHdr_t::param, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClBeaconSet()
void MeshCfgMdlClBeaconSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshBeaconStates_t beaconState)
Sets a Secure Network Beacon state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] beaconState New secure network beacon state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_BEACON_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_BEACON_STATE_IS_VALID, MESH_CFG_MDL_BEACON_SET_EVENT, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClCompDataGet()
void MeshCfgMdlClCompDataGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, uint8_t pageNumber)
Gets a Composition Data Page. (Only Page 0 is supported at this time).
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] pageNumber Requested page number.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_COMP_PAGE_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_COMP_PAGE_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClDefaultTtlGet()
void MeshCfgMdlClDefaultTtlGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets the Default TTL state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_DEFAULT_TTL_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_DEFAULT_TTL_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClDefaultTtlSet()
void MeshCfgMdlClDefaultTtlSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, uint8_t ttl)
Sets the Default TTL state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] ttl New value for the Default TTL.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_TTL_IS_VALID, MESH_TX_TTL_FILTER_VALUE, MESH_USE_DEFAULT_TTL, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClFriendGet()
void MeshCfgMdlClFriendGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets the Friend state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_FRIEND_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_FRIEND_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClFriendSet()
void MeshCfgMdlClFriendSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshFriendStates_t friendState)
Sets the Friend state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] friendState New value for the Friend state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_FRIEND_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_FRIEND_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_FRIEND_FEATURE_NOT_SUPPORTED, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClGattProxyGet()
void MeshCfgMdlClGattProxyGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets the Gatt Proxy state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_GATT_PROXY_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_GATT_PROXY_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClGattProxySet()
void MeshCfgMdlClGattProxySet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshGattProxyStates_t gattProxyState)
Sets the Gatt Proxy state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] gattProxyState GATT Proxy State.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_GATT_PROXY_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_GATT_PROXY_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_GATT_PROXY_FEATURE_NOT_SUPPORTED, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClGetRequiredMemory()
uint32_t MeshCfgMdlClGetRequiredMemory (void)
Gets memory required for configuration.
Returns
Configuration memory required or MESH_MEM_REQ_INVALID_CFG on error.
References meshMemoryConfig_t::cfgMdlClMaxSrSupported, MESH_UTILS_ALIGN, meshConfig_t::pMemoryConfig, and pMeshConfig.
MeshCfgMdlClHbPubGet()
void MeshCfgMdlClHbPubGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets a Heartbeat Publication state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_HB_PUB_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_HB_PUB_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClHbPubSet()
void MeshCfgMdlClHbPubSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshHbPub_t * pHbPubState)
Sets Heartbeat Publication states.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] pHbPubState Pointer to new values for Heartbeat Publication state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_HB_PUB_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, meshHbPub_t::countLog, meshHbPub_t::dstAddr, wsfMsgHdr_t::event, meshHbPub_t::features, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_HB_PUB_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_FEAT_RFU_START, MESH_IS_ADDR_VIRTUAL, MESH_NET_KEY_INDEX_MAX_VAL, meshHbPub_t::netKeyIndex, meshHbPub_t::periodLog, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, meshHbPub_t::ttl, and WsfMsgSend().
MeshCfgMdlClHbSubGet()
void MeshCfgMdlClHbSubGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets a Heartbeat Subscription state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_HB_SUB_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_HB_SUB_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClHbSubSet()
void MeshCfgMdlClHbSubSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshHbSub_t * pHbSubState)
Sets Heartbeat Subscription states.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] pHbSubState Pointer to new values for Heartbeat Subscription state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_HB_SUB_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, meshHbSub_t::dstAddr, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_HB_SUB_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_IS_ADDR_GROUP, MESH_IS_ADDR_VIRTUAL, meshHbSub_t::periodLog, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, meshHbSub_t::srcAddr, and WsfMsgSend().
MeshCfgMdlClInit()
uint32_t MeshCfgMdlClInit (uint8_t * pFreeMem, uint32_t freeMemSize)
Initializes the Configuration Client.
Parameters
[in] pFreeMem Pointer to free memory.
[in] freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
References MeshCfgMdlClGetRequiredMemory(), and WSF_ASSERT.
MeshCfgMdlClKeyRefPhaseGet()
void MeshCfgMdlClKeyRefPhaseGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, uint16_t netKeyIndex)
Gets the Key Refresh Phase state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] netKeyIndex Network Key Index for which the phase is read.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_KEY_REF_PHASE_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_KEY_REF_PHASE_GET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_NET_KEY_INDEX_MAX_VAL, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClKeyRefPhaseSet()
void MeshCfgMdlClKeyRefPhaseSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, uint16_t netKeyIndex, meshKeyRefreshTrans_t transition)
Sets the Key Refresh Phase state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] netKeyIndex Network Key Index for which the phase is read.
[in] transition Transition number. (Table 4.18 of the specification)
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_KEY_REF_PHASE_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_KEY_REF_PHASE_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_KEY_REFRESH_TRANS02, MESH_KEY_REFRESH_TRANS03, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, UINT8_TO_BSTREAM, and WsfMsgSend().
MeshCfgMdlClNetKeyChg()
void MeshCfgMdlClNetKeyChg (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, uint16_t netKeyIndex, meshCfgMdlClKeyOp_t keyOp, const uint8_t * pNetKey)
Modifies a NetKey.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] netKeyIndex Global identifier of the NetKey.
[in] keyOp Key Operation.
[in] pNetKey Pointer to memory holding the Network Key.
See also
meshCfgMdlClEvent_t, MESH_CFG_MDL_NETKEY_ADD_EVENT, MESH_CFG_MDL_NETKEY_UPDT_EVENT, MESH_CFG_MDL_NETKEY_DEL_EVENT
Returns
None.
Remarks
If the operation is MESH_CFG_MDL_CL_KEY_DEL, pNetKey is ignored.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_CL_KEY_ADD, MESH_CFG_MDL_CL_KEY_DEL, MESH_CFG_MDL_CL_KEY_UPDT, MESH_CFG_MDL_NETKEY_ADD_EVENT, MESH_CFG_MDL_NETKEY_DEL_EVENT, MESH_CFG_MDL_NETKEY_UPDT_EVENT, MESH_KEY_SIZE_128, MESH_NET_KEY_INDEX_MAX_VAL, wsfMsgHdr_t::param, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, wsfMsgHdr_t::status, and WsfMsgSend().
MeshCfgMdlClNetKeyGet()
void MeshCfgMdlClNetKeyGet (meshAddress_t cfgMdlSrAddr, const uint8_t * pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex)
Gets a NetKey List.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_NETKEY_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_NETKEY_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClNodeIdentityGet()
void MeshCfgMdlClNodeIdentityGet (meshAddress_t cfgMdlSrAddr, const uint8_t * pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex, uint16_t netKeyIndex)
Gets the current Node Identity State of a subnet.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] netKeyIndex NetKey Index identifying the subnet.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_NODE_IDENTITY_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_NODE_IDENTITY_GET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_NET_KEY_INDEX_MAX_VAL, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClNodeIdentitySet()
void MeshCfgMdlClNodeIdentitySet (meshAddress_t cfgMdlSrAddr, const uint8_t * pCfgMdlSrDevKey, uint16_t cfgMdlSrNetKeyIndex, uint16_t netKeyIndex, meshNodeIdentityStates_t nodeIdentityState)
Sets the current Node Identity State of a subnet.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] netKeyIndex NetKey Index identifying the subnet.
[in] nodeIdentityState New value for the Node Identity state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_NODE_IDENTITY_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_NODE_IDENTITY_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_NET_KEY_INDEX_MAX_VAL, MESH_NODE_IDENTITY_NOT_SUPPORTED, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, UINT8_TO_BSTREAM, and WsfMsgSend().
MeshCfgMdlClNodeReset()
void MeshCfgMdlClNodeReset (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Reset Node state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_NODE_RESET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_NODE_RESET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClNwkTransmitGet()
void MeshCfgMdlClNwkTransmitGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets the Network Transmit state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_NWK_TRANS_GET_EVENT
Returns
None.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_NWK_TRANS_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClNwkTransmitSet()
void MeshCfgMdlClNwkTransmitSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshNwkTransState_t * pNwkTransmit)
Sets the Network Transmit state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] pNwkTransmit Pointer to new value for the Network Transmit state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_NWK_TRANS_SET_EVENT
Returns
None.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] pNwkTransmit Pointer to new value for the Network Transmit state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_DEFAULT_TTL_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_NWK_TRANS_SET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, meshNwkTransState_t::transCount, meshNwkTransState_t::transIntervalSteps10Ms, and WsfMsgSend().
MeshCfgMdlClPollTimeoutGet()
void MeshCfgMdlClPollTimeoutGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshAddress_t lpnAddr)
Gets the PollTimeout state of a Low Power Node from a Friend node.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] lpnAddr Primary element address of the Low Power Node.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_LPN_POLLTIMEOUT_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_LPN_POLLTIMEOUT_GET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_IS_ADDR_UNICAST, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, UINT16_TO_BUF, and WsfMsgSend().
MeshCfgMdlClPubGet()
void MeshCfgMdlClPubGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
Gets the publish address and parameters of an outgoing message that originates from a model instance.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] elemAddr Address of the element containing the model.
[in] sigModelId SIG model identifier.
[in] vendorModelId Vendor model identifier.
[in] isSig TRUE if SIG model identifier should be used, FALSE for vendor.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_PUB_GET_EVENT
Returns
None.
MeshCfgMdlClPubSet()
void MeshCfgMdlClPubSet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshAddress_t elemAddr, meshAddress_t pubAddr, const uint8_t * pLabelUuid, meshModelPublicationParams_t * pPubParams, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
Sets the Model Publication state of an outgoing message that originates from a model instance when a either a virtual or non-virtual publish address is used.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] elemAddr Address of the element containing the model.
[in] pubAddr Publication address. Ignored when pointer to Label UUID is not NULL.
[in] pLabelUuid Pointer to Label UUID. Set to NULL to use pubAddr as publication address.
[in] pPubParams Pointer to model publication parameters.
[in] sigModelId SIG model identifier.
[in] vendorModelId Vendor model identifier.
[in] isSig TRUE if SIG model identifier should be used, FALSE for vendor.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_PUB_SET_EVENT, MESH_CFG_MDL_PUB_VIRT_SET_EVENT
Returns
None.
MeshCfgMdlClRegister()
void MeshCfgMdlClRegister (meshCfgMdlClCback_t meshCfgMdlClCback, uint16_t timeoutSeconds)
Installs the Configuration Client callback.
Parameters
[in] meshCfgMdlClCback Upper layer callback to notify operation results.
[in] timeoutSeconds Timeout for configuration operations, in seconds.
Returns
None.
References meshCfgMdlClCb_t::cback, meshCfgMdlClCb_t::opTimeoutSec, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshCfgMdlClRelayGet()
void MeshCfgMdlClRelayGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey)
Gets a Relay state.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_RELAY_GET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_RELAY_GET_EVENT, MESH_CFG_MDL_SR_EVENT, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClRelaySet()
void MeshCfgMdlClRelaySet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshRelayStates_t relayState, meshRelayRetransState_t * pRelayRetransState)
Sets Relay and Relay Retransmit states.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] relayState New value for the Relay state.
[in] pRelayRetransState Pointer to new value for the Relay Retransmit state.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_RELAY_SET_EVENT
Returns
None.
References meshCfgMdlClOpReqParams_t::apiEvt, meshCfgMdlClCb_t::cback, wsfMsgHdr_t::event, meshCb_t::handlerId, meshCfgMdlHdr_t::hdr, MESH_CFG_MDL_CL_INVALID_PARAMS, MESH_CFG_MDL_RELAY_SET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_RELAY_FEATURE_NOT_SUPPORTED, meshCfgMdlClOpReq_t::pMsgParam, meshCfgMdlClOpReq_t::pReqParam, meshCfgMdlClOpReqParams_t::reqOpId, meshRelayRetransState_t::retransCount, meshRelayRetransState_t::retransIntervalSteps10Ms, meshCfgMdlClOpReqParams_t::rspOpId, and WsfMsgSend().
MeshCfgMdlClSubscrListChg()
void MeshCfgMdlClSubscrListChg (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshAddress_t elemAddr, meshCfgMdlClSubscrAddrOp_t opType, meshAddress_t subscrAddr, const uint8_t * pLabelUuid, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
Changes the Model Subscription List state of a model instance when a either a virtual or non-virtual subscription address is used.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] elemAddr Address of the element containing the model.
[in] opType Type of operation applied to the subscription list.
[in] subscrAddr Subscription address. Ignored when pointer to Label UUID is not NULL.
[in] pLabelUuid Pointer to Label UUID. Set to NULL to use subscrAddr as subscription address.
[in] sigModelId SIG model identifier.
[in] vendorModelId Vendor model identifier.
[in] isSig TRUE if SIG model identifier should be used, FALSE for vendor.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_SUBSCR_ADD_EVENT, MESH_CFG_MDL_SUBSCR_VIRT_ADD_EVENT, MESH_CFG_MDL_SUBSCR_DEL_EVENT, MESH_CFG_MDL_SUBSCR_VIRT_DEL_EVENT, MESH_CFG_MDL_SUBSCR_OVR_EVENT, MESH_CFG_MDL_SUBSCR_VIRT_OVR_EVENT, MESH_CFG_MDL_SUBSCR_DEL_ALL_EVENT
Remarks
If opType is MESH_CFG_MDL_SUBSCR_DEL_ALL_EVENT, both subscrAddr and pLabelUuid are ignored.
Returns
None.
MeshCfgMdlClSubscrListGet()
void MeshCfgMdlClSubscrListGet (meshAddress_t cfgMdlSrAddr, uint16_t cfgMdlSrNetKeyIndex, const uint8_t * pCfgMdlSrDevKey, meshAddress_t elemAddr, meshSigModelId_t sigModelId, meshVendorModelId_t vendorModelId, bool_t isSig)
Gets the Model Subscription List state of a model instance.
Parameters
[in] cfgMdlSrAddr Primary element containing an instance of Configuration Server model.
[in] cfgMdlSrNetKeyIndex Global identifier of the Network on which the request is sent.
[in] pCfgMdlSrDevKey Pointer to the Device Key of the remote Configuration Server or NULL for local (cfgMdlSrAddr is MESH_CFG_MDL_CL_LOCAL_NODE_SR).
[in] elemAddr Address of the element containing the model.
[in] sigModelId SIG model identifier.
[in] vendorModelId Vendor model identifier.
[in] isSig TRUE if SIG model identifier should be used, FALSE for vendor.
See also
meshCfgMdlClEvt_t, MESH_CFG_MDL_SUBSCR_SIG_GET_EVENT, MESH_CFG_MDL_SUBSCR_VENDOR_GET_EVENT
Returns
None.
MeshCfgMdlSrInit()
void MeshCfgMdlSrInit (void)
Initializes the Configuration Server.
Returns
None.
References meshCfgMdlSrCb_t::cback, meshCfgMdlSrCb_t::friendStateChgCback, MeshAccRegisterCoreModel(), and meshCfgMdlSrCb_t::netKeyDelNotifyCback.
MeshCfgMdlSrRegister()
void MeshCfgMdlSrRegister (meshCfgMdlSrCback_t meshCfgMdlSrCback)
Installs the Configuration Server callback.
Parameters
[in] meshCfgMdlSrCback Upper layer callback to notify that a local state has changed.
Returns
None.
References meshCfgMdlSrCb_t::cback, meshCfgMdlSrCb_t::friendStateChgCback, meshCfgMdlSrCb_t::netKeyDelNotifyCback, meshCfgMdlSrCb_t::pollTimeoutGetCback, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshCfgMsgDeepCopy()
bool_t MeshCfgMsgDeepCopy (wsfMsgHdr_t * pMeshCfgEvtOut, const wsfMsgHdr_t * pMeshCfgEvtIn)
Make a deep copy of a Configuration Message.
Parameters
MeshCfgSizeOfEvt()
uint16_t MeshCfgSizeOfEvt (wsfMsgHdr_t * pMeshCfgEvt)
Return size of a Mesh Configuration Model callback event.
Parameters
[in] pMeshCfgEvt Mesh Configuration Model callback event.
Returns
Size of Mesh Configuration Model callback event.
References wsfMsgHdr_t::event, MESH_CFG_MDL_APP_SIG_GET_EVENT, MESH_CFG_MDL_APP_VENDOR_GET_EVENT, MESH_CFG_MDL_APPKEY_GET_EVENT, MESH_CFG_MDL_CL_EVENT, MESH_CFG_MDL_CL_SUCCESS, MESH_CFG_MDL_COMP_PAGE_GET_EVENT, MESH_CFG_MDL_MAX_EVENT, MESH_CFG_MDL_NETKEY_GET_EVENT, MESH_CFG_MDL_SR_EVENT, MESH_CFG_MDL_SUBSCR_SIG_GET_EVENT, MESH_CFG_MDL_SUBSCR_VENDOR_GET_EVENT, wsfMsgHdr_t::param, and wsfMsgHdr_t::status.