Cordio: LL_LHCI_INT
LL_LHCI_INT
Data Structures
struct lhciPersistCb_t
struct lhciCb_t
struct lhciIsoCb_t
Macros
#define LHCI_LEN_SET_EVENT_MASK_EVT 1
#define LHCI_LEN_RESET_EVT 1
#define LHCI_LEN_READ_PWR_LVL_EVT 4
#define LHCI_LEN_READ_AUTH_PAYLOAD_TO_EVT 5
#define LHCI_LEN_WRITE_AUTH_PAYLOAD_TO_EVT 3
#define LHCI_LEN_READ_LOCAL_VER_EVT 9
#define LHCI_LEN_READ_LOCAL_SUP_CMDS_EVT 65
#define LHCI_LEN_READ_LOCAL_SUP_FEAT_EVT 9
#define LHCI_LEN_READ_BUF_SIZE_EVT 8
#define LHCI_LEN_READ_BD_ADDR_EVT 7
#define LHCI_LEN_LE_SET_EVENT_MASK_EVT 1
#define LHCI_LEN_LE_READ_BUF_SIZE_EVT 4
#define LHCI_LEN_LE_READ_LOCAL_SUP_FEAT_EVT 9
#define LHCI_LEN_LE_SET_RAND_ADDR_EVT 1
#define LHCI_LEN_LE_SET_ADV_PARAM_EVT 1
#define LHCI_LEN_LE_READ_ADV_TX_POWER_EVT 2
#define LHCI_LEN_LE_SET_ADV_DATA_EVT 1
#define LHCI_LEN_LE_SET_SCAN_RESP_DATA_EVT 1
#define LHCI_LEN_LE_SET_ADV_ENABLE_EVT 1
#define LHCI_LEN_LE_SET_SCAN_PARAM_EVT 1
#define LHCI_LEN_LE_SET_SCAN_ENABLE_EVT 1
#define LHCI_LEN_LE_CREATE_CONN_CANCEL_EVT 1
#define LHCI_LEN_LE_READ_WL_SIZE_EVT 2
#define LHCI_LEN_LE_CLEAR_WHITE_LIST_EVT 1
#define LHCI_LEN_LE_ADD_DEV_WHITE_LIST_EVT 1
#define LHCI_LEN_LE_REMOVE_DEV_WHITE_LIST_EVT 1
#define LHCI_LEN_LE_SET_HOST_CHAN_CLASS 1
#define LHCI_LEN_LE_READ_CHAN_MAP_EVT 8
#define LHCI_LEN_LE_ENCRYPT_EVT 17
#define LHCI_LEN_LE_LTK_REQ_REPL_EVT 3
#define LHCI_LEN_LE_LTK_REQ_NEG_REPL_EVT 3
#define LHCI_LEN_LE_RAND_EVT 9
#define LHCI_LEN_LE_READ_SUP_STATES_EVT 9
#define LHCI_LEN_LE_RECEIVER_TEST_EVT 1
#define LHCI_LEN_LE_TRANSMITTER_TEST_EVT 1
#define LHCI_LEN_LE_TEST_END_EVT 3
#define LHCI_LEN_LE_REM_CONN_PARAM_REP 3
#define LHCI_LEN_LE_REM_CONN_PARAM_NEG_REP 3
#define LHCI_LEN_LE_SET_DATA_LEN 3
#define LHCI_LEN_LE_READ_DEF_DATA_LEN 5
#define LHCI_LEN_LE_WRITE_DEF_DATA_LEN 1
#define LHCI_LEN_LE_ADD_DEV_RES_LIST_EVT 1
#define LHCI_LEN_LE_REMOVE_DEV_RES_LIST_EVT 1
#define LHCI_LEN_LE_CLEAR_RES_LIST_EVT 1
#define LHCI_LEN_LE_READ_RES_LIST_SIZE_EVT 2
#define LHCI_LEN_LE_READ_PEER_RES_ADDR_EVT 7
#define LHCI_LEN_LE_READ_LOCAL_RES_ADDR_EVT 7
#define LHCI_LEN_LE_SET_ADDR_RES_ENABLE_EVT 1
#define LHCI_LEN_LE_SET_RES_PRIV_ADDR_TO_EVT 1
#define LHCI_LEN_LE_READ_MAX_DATA_LEN 9
#define LHCI_LEN_LE_SET_PRIVACY_MODE 1
#define LHCI_LEN_LE_SET_ADV_SET_RAND_ADDR 1
#define LHCI_LEN_LE_SET_EXT_ADV_PARAM 2
#define LHCI_LEN_LE_SET_EXT_ADV_DATA 1
#define LHCI_LEN_LE_SET_EXT_SCAN_RESP_DATA 1
#define LHCI_LEN_LE_SET_EXT_ADV_ENABLE 1
#define LHCI_LEN_LE_READ_MAX_ADV_DATA_LEN 3
#define LHCI_LEN_LE_READ_NUM_OF_SUP_ADV_SETS 2
#define LHCI_LEN_LE_REMOVE_ADV_SET 1
#define LHCI_LEN_LE_CLEAR_ADV_SETS 1
#define LHCI_LEN_LE_SET_PER_ADV_PARAM 1
#define LHCI_LEN_LE_SET_PER_ADV_DATA 1
#define LHCI_LEN_LE_SET_PER_ADV_ENABLE 1
#define LHCI_LEN_LE_SET_EXT_SCAN_PARAM 1
#define LHCI_LEN_LE_SET_EXT_SCAN_ENABLE 1
#define LHCI_LEN_LE_PER_ADV_CREATE_SYNC_CANCEL 1
#define LHCI_LEN_LE_PER_ADV_TERMINATE_SYNC 1
#define LHCI_LEN_LE_ADD_DEV_PER_ADV_LIST 1
#define LHCI_LEN_LE_REM_DEV_PER_ADV_LIST 1
#define LHCI_LEN_LE_CLEAR_PER_ADV_LIST 1
#define LHCI_LEN_LE_READ_PER_ADV_LIST_SIZE 2
#define LHCI_LEN_LE_READ_SUP_TX_POWER 3
#define LHCI_LEN_LE_WRITE_RF_PATH_COMP 1
#define LHCI_LEN_LE_READ_RF_PATH_COMP 5
#define LHCI_LEN_LE_SET_EXT_SCAN_ENABLE_EVT 1
#define LHCI_LEN_LE_READ_PHY_EVT 5
#define LHCI_LEN_LE_SET_DEF_PHY_EVT 1
#define LHCI_LEN_LE_ENHANCED_RECEIVER_TEST_EVT 1
#define LHCI_LEN_LE_ENHANCED_TRANSMITTER_TEST_EVT 1
#define LHCI_LEN_LE_SET_PER_ADV_RCV_ENABLE 1
#define LHCI_LEN_LE_PER_ADV_SYNC_TRANSFER 3
#define LHCI_LEN_LE_PER_ADV_SET_INFO_TRANSFER 3
#define LHCI_LEN_LE_SET_PAST_PARAM 3
#define LHCI_LEN_LE_SET_DEFAULT_PAST_PARAM 1
#define LHCI_LEN_LE_MODIFY_SCA_EVT 1
#define LHCI_LEN_LE_READ_BUF_SIZE_V2 7
#define LHCI_LEN_LE_READ_TX_SYNC 12
#define LHCI_LEN_LE_REMOVE_CIG 1
#define LHCI_LEN_LE_REJECT_CIS_REQ 1
#define LHCI_LEN_LE_BIG_TERMINATE_SYNC 2
#define LHCI_LEN_LE_SETUP_ISO_DATA_PATH 3
#define LHCI_LEN_LE_REMOVE_ISO_DATA_PATH 3
#define LHCI_LEN_LE_ISO_TX_TEST 1
#define LHCI_LEN_LE_ISO_RX_TEST 1
#define LHCI_LEN_LE_ISO_READ_TEST_COUNTER 15
#define LHCI_LEN_LE_ISO_TEST_END 15
#define LHCI_LEN_LE_SET_HOST_FEATURE 1
#define LHCI_LEN_LE_READ_ISO_LINK_QUAL 31
#define LHCI_LEN_LE_READ_ENH_TX_POWER_EVT 6
#define LHCI_LEN_LE_SET_TX_POWER_REPORT_EVT 3
#define LHCI_LEN_LE_SET_PATH_LOSS_REPORTING_PARAMS 3
#define LHCI_LEN_LE_SET_PATH_LOSS_REPORTING_ENABLE 3
#define LHCI_LEN_CONFIG_DATA_PATH 1
#define LHCI_LEN_READ_LOCAL_SUP_CODECS 3
#define LHCI_LEN_READ_LOCAL_SUP_CODEC_CAP 2
#define LHCI_LEN_READ_LOCAL_SUP_CONTROLLER_DLY 7
#define LHCI_DEF_EVT_MASK UINT64_C(0x00001FFFFFFFFFFF);
#define LHCI_DEF_EVT_PG2_MASK UINT64_C(0x0000000000000000);
#define LHCI_DEF_LE_EVT_MASK UINT64_C(0x000000000000001F);
#define LHCI_LOCAL_SUP_FEAT_VAL UINT64_C(0x0000006000000000)
#define LHCI_BYTE_TO_BITS(x) (8 * x)
#define LHCI_LEN_VS_EVT 2
#define LHCI_LEN_CMD_STATUS_EVT 0xFF
#define LHCI_OPCODE_VS_SET_SCAN_CH_MAP HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E0)
#define LHCI_OPCODE_VS_SET_EVENT_MASK HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E1)
#define LHCI_OPCODE_VS_SET_RSRC_MGR_MODE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E2)
#define LHCI_OPCODE_VS_ENA_ACL_SINK HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E3)
#define LHCI_OPCODE_VS_GENERATE_ACL HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E4)
#define LHCI_OPCODE_VS_ENA_AUTO_GEN_ACL HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E5)
#define LHCI_OPCODE_VS_SET_TX_TEST_ERR_PATT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E6)
#define LHCI_OPCODE_VS_SET_CONN_OP_FLAGS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E7)
#define LHCI_OPCODE_VS_SET_P256_PRIV_KEY HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E8)
#define LHCI_OPCODE_VS_GET_PER_CHAN_MAP HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DE)
#define LHCI_OPCODE_VS_SET_HCI_SUP_CMD HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DF)
#define LHCI_OPCODE_VS_GET_ACL_TEST_REPORT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E9)
#define LHCI_OPCODE_VS_SET_LOCAL_MIN_USED_CHAN HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3EA)
#define LHCI_OPCODE_VS_GET_PEER_MIN_USED_CHAN HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3EB)
#define LHCI_OPCODE_VS_VALIDATE_PUB_KEY_MODE
#define LHCI_OPCODE_VS_SET_BD_ADDR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F0)
#define LHCI_OPCODE_VS_GET_RAND_ADDR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F1)
#define LHCI_OPCODE_VS_SET_LOCAL_FEAT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F2)
#define LHCI_OPCODE_VS_SET_OP_FLAGS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F3)
#define LHCI_OPCODE_VS_GET_PDU_FILT_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F4)
#define LHCI_OPCODE_VS_SET_ADV_TX_PWR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F5)
#define LHCI_OPCODE_VS_SET_CONN_TX_PWR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F6)
#define LHCI_OPCODE_VS_SET_ENC_MODE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F7)
#define LHCI_OPCODE_VS_SET_CHAN_MAP HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F8)
#define LHCI_OPCODE_VS_SET_DIAG_MODE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F9)
#define LHCI_OPCODE_VS_SET_SNIFFER_ENABLE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3CD)
#define LHCI_OPCODE_VS_GET_SYS_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FA)
#define LHCI_OPCODE_VS_GET_ADV_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FB)
#define LHCI_OPCODE_VS_GET_SCAN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FC)
#define LHCI_OPCODE_VS_GET_CONN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FD)
#define LHCI_OPCODE_VS_GET_TEST_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FE)
#define LHCI_OPCODE_VS_GET_POOL_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FF)
#define LHCI_OPCODE_VS_SET_AUX_DELAY HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D0)
#define LHCI_OPCODE_VS_SET_EXT_ADV_FRAG_LEN
#define LHCI_OPCODE_VS_SET_EXT_ADV_PHY_OPTS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D2)
#define LHCI_OPCODE_VS_SET_EXT_ADV_DEF_PHY_OPTS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D3)
#define LHCI_OPCODE_VS_SET_EXT_SCAN_PHY_OPTS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D4)
#define LHCI_OPCODE_VS_GENERATE_ISO HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D5)
#define LHCI_OPCODE_VS_GET_ISO_TEST_REPORT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D6)
#define LHCI_OPCODE_VS_ENA_ISO_SINK HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D7)
#define LHCI_OPCODE_VS_ENA_AUTO_GEN_ISO HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D8)
#define LHCI_OPCODE_VS_GET_CIS_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D9)
#define LHCI_OPCODE_VS_GET_AUX_ADV_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DA)
#define LHCI_OPCODE_VS_GET_AUX_SCAN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DB)
#define LHCI_OPCODE_VS_GET_PER_SCAN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DC)
#define LHCI_OPCODE_VS_SET_CONN_PHY_TX_PWR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DD)
#define LHCI_OPCODE_VS_REG_WRITE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x300)
#define LHCI_OPCODE_VS_REG_READ HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x301)
#define LHCI_OPCODE_VS_RESET_CONN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x302)
#define LHCI_OPCODE_VS_TX_TEST HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x303)
#define LHCI_OPCODE_VS_RESET_TEST_STATS
#define LHCI_OPCODE_VS_RX_TEST
#define LHCI_OPCODE_VS_GET_RSSI
#define LHCI_OPCODE_VS_PHY_EN
#define LHCI_OPCODE_VS_PHY_DIS
#define LHCI_VS_EVT_MASK_SCAN_REPORT_EVT 0x01
#define LHCI_VS_EVT_MASK_DIAG_TRACE_EVT 0x02
#define LHCI_VS_EVT_MASK_ISO_EVENT_CMPL_EVT 0x04
Typedefs
typedef bool_t(* lhciEvtHandler_t) (LlEvt_t *pEvt)
typedef uint8_t *(* lhciServiceAcl_t) (void)
typedef uint8_t *(* lhciServiceIso_t) (void)
Enumerations
enum
enum
Functions
void lhciReset (void)
void lhciRecv (uint8_t type, uint8_t *pBuf)
void lhciSendComplete (uint8_t type, uint8_t *pBuf)
bool_t lhciService (uint8_t *pType, uint16_t *pLen, uint8_t **pBuf)
void lhciSendHwError (uint8_t code)
bool_t lhciLlEvtHandler (LlEvt_t *pEvt)
void lhciAclSendComplete (uint16_t handle, uint8_t numBufs)
uint8_t * lhciRecvAcl (void)
void lhciAclRecvPending (uint16_t handle, uint8_t numBufs)
void lhciGenerateAcl (uint16_t handle, uint16_t pktLen, uint8_t numPkts)
void lhciIsoSendComplete (uint8_t numHandles, uint16_t *pHandle, uint16_t *pNumPkts)
uint8_t * lhciRecvIso (void)
void lhciIsoRecvPending (uint8_t numHandles, uint16_t *pHandle, uint16_t *pNumPkts)
void lhciGenerateIso (uint16_t handle, uint16_t pktLen, uint8_t numPkts)
bool_t lhciCommonDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciConnDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstConnDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstExtConnDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstEncDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvEncDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstScanDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvAdvDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstExtScanDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvExtAdvDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciPrivAdvDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciPrivConnDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciScDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciPhyDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciPastDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstCisDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvCisDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvBisDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstBisDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciIsoDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciPclDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciCommonVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciConnVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstConnVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstScanVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvAdvVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvEncVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciScVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciMstExtScanVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciSlvExtAdvVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
bool_t lhciIsoVsStdDecodeCmdPkt (LhciHdr_t *pHdr, uint8_t *pBuf)
void lhciSendCmdStatusEvt (LhciHdr_t *pCmdHdr, uint8_t status)
bool_t lhciConnEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciConnCsEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciMstConnEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciMstScanEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciSlvAdvEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciMstExtScanEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciSlvExtAdvEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciMstEncEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciSlvEncEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciPrivConnEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciScEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciPhyEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciMstCisEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciSlvCisEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciSlvBigEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciMstBisEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciIsoEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciPclEncodeEvtPkt (LlEvt_t *pEvt)
bool_t lhciSlvVsStdEncodeEvtPkt (LlEvt_t *pEvt)
uint8_t * lhciAllocEvt (uint8_t evtCode, uint8_t paramLen)
uint8_t * lhciAllocCmdCmplEvt (uint8_t paramLen, uint16_t opCode)
void lhciConnSendCmdCmplEvt (LhciHdr_t *pCmdHdr, uint8_t status, uint8_t paramLen, uint8_t *pParam, uint16_t handle)
void lhciPclSendCmdCmplEvt (LhciHdr_t *pCmdHdr, uint8_t status, uint8_t paramLen, uint8_t *pParam, uint16_t handle)
uint8_t lhciUnpackConnSpec (LlConnSpec_t *pConnSpec, const uint8_t *pBuf)
Variables
lhciCmdHandler_t lhciCmdTbl [LHCI_MSG_TOTAL]
lhciEvtHandler_t lhciEvtTbl [LHCI_MSG_TOTAL]
lhciServiceAcl_t lhciServiceAcl
lhciServiceIso_t lhciServiceIso
lhciPersistCb_t lhciPersistCb
lhciCb_t lhciCb
lhciIsoCb_t lhciIsoCb
uint16_t lhciHandlerWatermarkUsec
Detailed Description
Data Structure Documentation
lhciPersistCb_t
struct lhciPersistCb_t
Control block of the LL HCI subsystem (persists with resets).
Data Fields
wsfHandlerId_t handlerId
wsfQueue_t aclQ
wsfQueue_t cmdQ
wsfQueue_t evtQ
wsfQueue_t isoQ
bool_t evtTrPending
uint8_t supCmds [HCI_SUP_CMD_LEN]
Field Documentation
aclQ
wsfQueue_t aclQ
ACL queue.
cmdQ
wsfQueue_t cmdQ
Command queue.
evtQ
wsfQueue_t evtQ
Event queue.
evtTrPending
bool_t evtTrPending
Event transport in progress.
handlerId
wsfHandlerId_t handlerId
Task handler ID.
isoQ
wsfQueue_t isoQ
ISO queue.
supCmds
uint8_t supCmds[HCI_SUP_CMD_LEN]
Supported HCI commands bit mask.
lhciCb_t
struct lhciCb_t
Control block of the LL HCI subsystem (cleared with resets).
Data Fields
uint64_t evtMsk
uint64_t evtMskPg2
uint64_t leEvtMsk
lhciCompHandler_t evtCompCback
uint8_t numScanReqRcvd
uint8_t hwErrorCode
bool_t recvAclSink
uint32_t recvAclPktCnt
uint32_t recvAclOctetCnt
bool_t genEnaFlag
uint8_t genPldCnt
uint16_t genPktLen
uint32_t genPktCnt
uint32_t genOctetCnt
uint8_t numAdvReport
Field Documentation
evtCompCback
lhciCompHandler_t evtCompCback
Event complete handler.
evtMsk
uint64_t evtMsk
General event mask.
evtMskPg2
uint64_t evtMskPg2
General event mask page 2.
genEnaFlag
bool_t genEnaFlag
Generate enable flag.
genOctetCnt
uint32_t genOctetCnt
Generate ACL octet count.
genPktCnt
uint32_t genPktCnt
Generate ACL packet count.
genPktLen
uint16_t genPktLen
Generate ACL packet length (0 to disable).
genPldCnt
uint8_t genPldCnt
Generate ACL packet fill value.
hwErrorCode
uint8_t hwErrorCode
Hardware error code.
leEvtMsk
uint64_t leEvtMsk
LE specific event mask.
numAdvReport
uint8_t numAdvReport
Number of pending advertising reports.
numScanReqRcvd
uint8_t numScanReqRcvd
Number of scan request received.
recvAclOctetCnt
uint32_t recvAclOctetCnt
Receive ACL octet count.
recvAclPktCnt
uint32_t recvAclPktCnt
Receive ACL packet count.
recvAclSink
bool_t recvAclSink
Receive ACL sink.
lhciIsoCb_t
struct lhciIsoCb_t
Control block for ISO data generator.
Data Fields
bool_t recvIsoSink
uint32_t recvIsoPktCnt
uint32_t recvIsoOctetCnt
bool_t genEnaFlag
uint8_t genPldCnt
uint16_t genPktLen
uint32_t genPktCnt
uint32_t genOctetCnt
bool_t isoRxTest
Field Documentation
genEnaFlag
bool_t genEnaFlag
Generate ISO enable flag.
genOctetCnt
uint32_t genOctetCnt
Generate ISO octet count.
genPktCnt
uint32_t genPktCnt
Generate ISO packet count.
genPktLen
uint16_t genPktLen
Generate ISO packet length (0 to disable).
genPldCnt
uint8_t genPldCnt
Generate ISO packet fill value.
isoRxTest
bool_t isoRxTest
TRUE if ISO Rx test is enabled.
recvIsoOctetCnt
uint32_t recvIsoOctetCnt
Receive ISO octet count.
recvIsoPktCnt
uint32_t recvIsoPktCnt
Receive ISO packet count.
recvIsoSink
bool_t recvIsoSink
Receive ISO sink.
Macro Definition Documentation
LHCI_LEN_CONFIG_DATA_PATH
#define LHCI_LEN_CONFIG_DATA_PATH 1
Configure data path.
LHCI_LEN_LE_ADD_DEV_PER_ADV_LIST
#define LHCI_LEN_LE_ADD_DEV_PER_ADV_LIST 1
LE add device from periodic advertising list command complete event length.
LHCI_LEN_LE_ADD_DEV_RES_LIST_EVT
#define LHCI_LEN_LE_ADD_DEV_RES_LIST_EVT 1
LE add device to resolving list command complete event length.
LHCI_LEN_LE_ADD_DEV_WHITE_LIST_EVT
#define LHCI_LEN_LE_ADD_DEV_WHITE_LIST_EVT 1
LE add device to white list command complete event length.
LHCI_LEN_LE_BIG_TERMINATE_SYNC
#define LHCI_LEN_LE_BIG_TERMINATE_SYNC 2
LE BIG terminate sync.
LHCI_LEN_LE_CLEAR_ADV_SETS
#define LHCI_LEN_LE_CLEAR_ADV_SETS 1
LE clear advertising sets command complete event length.
LHCI_LEN_LE_CLEAR_PER_ADV_LIST
#define LHCI_LEN_LE_CLEAR_PER_ADV_LIST 1
LE clear periodic advertising list command complete event length.
LHCI_LEN_LE_CLEAR_RES_LIST_EVT
#define LHCI_LEN_LE_CLEAR_RES_LIST_EVT 1
LE clear resolving list command complete event length.
LHCI_LEN_LE_CLEAR_WHITE_LIST_EVT
#define LHCI_LEN_LE_CLEAR_WHITE_LIST_EVT 1
LE clear white list command complete event length.
LHCI_LEN_LE_CREATE_CONN_CANCEL_EVT
#define LHCI_LEN_LE_CREATE_CONN_CANCEL_EVT 1
LE create connection cancel command complete event length.
LHCI_LEN_LE_ENCRYPT_EVT
#define LHCI_LEN_LE_ENCRYPT_EVT 17
LE encrypt command complete event length.
LHCI_LEN_LE_ENHANCED_RECEIVER_TEST_EVT
#define LHCI_LEN_LE_ENHANCED_RECEIVER_TEST_EVT 1
LE enhanced receiver test command complete event length.
LHCI_LEN_LE_ENHANCED_TRANSMITTER_TEST_EVT
#define LHCI_LEN_LE_ENHANCED_TRANSMITTER_TEST_EVT 1
LE enhanced transmitter test command complete event length.
LHCI_LEN_LE_ISO_READ_TEST_COUNTER
#define LHCI_LEN_LE_ISO_READ_TEST_COUNTER 15
LE ISO read test counter.
LHCI_LEN_LE_ISO_RX_TEST
#define LHCI_LEN_LE_ISO_RX_TEST 1
LE ISO Rx Test.
LHCI_LEN_LE_ISO_TEST_END
#define LHCI_LEN_LE_ISO_TEST_END 15
LE ISO test end.
LHCI_LEN_LE_ISO_TX_TEST
#define LHCI_LEN_LE_ISO_TX_TEST 1
LE ISO Tx Test.
LHCI_LEN_LE_LTK_REQ_NEG_REPL_EVT
#define LHCI_LEN_LE_LTK_REQ_NEG_REPL_EVT 3
LE LTK request negative reply command complete event length.
LHCI_LEN_LE_LTK_REQ_REPL_EVT
#define LHCI_LEN_LE_LTK_REQ_REPL_EVT 3
LE LTK request reply command complete event length.
LHCI_LEN_LE_MODIFY_SCA_EVT
#define LHCI_LEN_LE_MODIFY_SCA_EVT 1
LE Modify sleep clock accuracy event length.
LHCI_LEN_LE_PER_ADV_CREATE_SYNC_CANCEL
#define LHCI_LEN_LE_PER_ADV_CREATE_SYNC_CANCEL 1
LE periodic advertising create sync cancel command complete event length.
LHCI_LEN_LE_PER_ADV_SET_INFO_TRANSFER
#define LHCI_LEN_LE_PER_ADV_SET_INFO_TRANSFER 3
LE periodic advertising set info transfer command complete event length.
LHCI_LEN_LE_PER_ADV_SYNC_TRANSFER
#define LHCI_LEN_LE_PER_ADV_SYNC_TRANSFER 3
LE periodic advertising sync transfer command complete event length.
LHCI_LEN_LE_PER_ADV_TERMINATE_SYNC
#define LHCI_LEN_LE_PER_ADV_TERMINATE_SYNC 1
LE periodic advertising terminate sync command complete event length.
LHCI_LEN_LE_RAND_EVT
#define LHCI_LEN_LE_RAND_EVT 9
LE random command complete event length.
LHCI_LEN_LE_READ_ADV_TX_POWER_EVT
#define LHCI_LEN_LE_READ_ADV_TX_POWER_EVT 2
LE read advertising Tx power command complete event length.
LHCI_LEN_LE_READ_BUF_SIZE_EVT
#define LHCI_LEN_LE_READ_BUF_SIZE_EVT 4
LE read buffer size command complete event length.
LHCI_LEN_LE_READ_BUF_SIZE_V2
#define LHCI_LEN_LE_READ_BUF_SIZE_V2 7
LE read ISO buffer size command complete event length.
LHCI_LEN_LE_READ_CHAN_MAP_EVT
#define LHCI_LEN_LE_READ_CHAN_MAP_EVT 8
LE read channel map command complete event length.
LHCI_LEN_LE_READ_DEF_DATA_LEN
#define LHCI_LEN_LE_READ_DEF_DATA_LEN 5
LE read default data length command complete event length.
LHCI_LEN_LE_READ_ENH_TX_POWER_EVT
#define LHCI_LEN_LE_READ_ENH_TX_POWER_EVT 6
LE Read enhanced TX power.
LHCI_LEN_LE_READ_ISO_LINK_QUAL
#define LHCI_LEN_LE_READ_ISO_LINK_QUAL 31
LE Read ISO link quality.
LHCI_LEN_LE_READ_LOCAL_RES_ADDR_EVT
#define LHCI_LEN_LE_READ_LOCAL_RES_ADDR_EVT 7
LE read local resolving address command complete event length.
LHCI_LEN_LE_READ_LOCAL_SUP_FEAT_EVT
#define LHCI_LEN_LE_READ_LOCAL_SUP_FEAT_EVT 9
LE read local supported feature command complete event length.
LHCI_LEN_LE_READ_MAX_ADV_DATA_LEN
#define LHCI_LEN_LE_READ_MAX_ADV_DATA_LEN 3
LE read maximum advertising data length command complete event length.
LHCI_LEN_LE_READ_MAX_DATA_LEN
#define LHCI_LEN_LE_READ_MAX_DATA_LEN 9
LE read maximum data length command complete event length.
LHCI_LEN_LE_READ_NUM_OF_SUP_ADV_SETS
#define LHCI_LEN_LE_READ_NUM_OF_SUP_ADV_SETS 2
LE read number of supported advertising sets command complete event length.
LHCI_LEN_LE_READ_PEER_RES_ADDR_EVT
#define LHCI_LEN_LE_READ_PEER_RES_ADDR_EVT 7
LE read peer resolving address command complete event length.
LHCI_LEN_LE_READ_PER_ADV_LIST_SIZE
#define LHCI_LEN_LE_READ_PER_ADV_LIST_SIZE 2
LE read periodic advertising list size command complete event length.
LHCI_LEN_LE_READ_PHY_EVT
#define LHCI_LEN_LE_READ_PHY_EVT 5
LE read PHY command complete event length.
LHCI_LEN_LE_READ_RES_LIST_SIZE_EVT
#define LHCI_LEN_LE_READ_RES_LIST_SIZE_EVT 2
LE read resolving list size command complete event length.
LHCI_LEN_LE_READ_RF_PATH_COMP
#define LHCI_LEN_LE_READ_RF_PATH_COMP 5
LE read RF path compensation command complete event length.
LHCI_LEN_LE_READ_SUP_STATES_EVT
#define LHCI_LEN_LE_READ_SUP_STATES_EVT 9
LE read supported states command complete event length.
LHCI_LEN_LE_READ_SUP_TX_POWER
#define LHCI_LEN_LE_READ_SUP_TX_POWER 3
LE read supported Tx power command complete event length.
LHCI_LEN_LE_READ_TX_SYNC
#define LHCI_LEN_LE_READ_TX_SYNC 12
LE read ISO Tx sync.
LHCI_LEN_LE_READ_WL_SIZE_EVT
#define LHCI_LEN_LE_READ_WL_SIZE_EVT 2
LE read white list size command complete event length.
LHCI_LEN_LE_RECEIVER_TEST_EVT
#define LHCI_LEN_LE_RECEIVER_TEST_EVT 1
LE receiver test command complete event length.
LHCI_LEN_LE_REJECT_CIS_REQ
#define LHCI_LEN_LE_REJECT_CIS_REQ 1
LE reject CIS request.
LHCI_LEN_LE_REM_CONN_PARAM_NEG_REP
#define LHCI_LEN_LE_REM_CONN_PARAM_NEG_REP 3
LE remote connection parameter negative reply command complete event length.
LHCI_LEN_LE_REM_CONN_PARAM_REP
#define LHCI_LEN_LE_REM_CONN_PARAM_REP 3
LE remote connection parameter reply command complete event length.
LHCI_LEN_LE_REM_DEV_PER_ADV_LIST
#define LHCI_LEN_LE_REM_DEV_PER_ADV_LIST 1
LE remove device from periodic advertising list command complete event length.
LHCI_LEN_LE_REMOVE_ADV_SET
#define LHCI_LEN_LE_REMOVE_ADV_SET 1
LE remove advertising set command complete event length.
LHCI_LEN_LE_REMOVE_CIG
#define LHCI_LEN_LE_REMOVE_CIG 1
LE remove CIG.
LHCI_LEN_LE_REMOVE_DEV_RES_LIST_EVT
#define LHCI_LEN_LE_REMOVE_DEV_RES_LIST_EVT 1
LE remove device from resolving list command complete event length.
LHCI_LEN_LE_REMOVE_DEV_WHITE_LIST_EVT
#define LHCI_LEN_LE_REMOVE_DEV_WHITE_LIST_EVT 1
LE remove device from white list command complete event length.
LHCI_LEN_LE_REMOVE_ISO_DATA_PATH
#define LHCI_LEN_LE_REMOVE_ISO_DATA_PATH 3
LE remove ISO data path.
LHCI_LEN_LE_SET_ADDR_RES_ENABLE_EVT
#define LHCI_LEN_LE_SET_ADDR_RES_ENABLE_EVT 1
LE set address resolution enable command complete event length.
LHCI_LEN_LE_SET_ADV_DATA_EVT
#define LHCI_LEN_LE_SET_ADV_DATA_EVT 1
LE set advertising data command complete event length.
LHCI_LEN_LE_SET_ADV_ENABLE_EVT
#define LHCI_LEN_LE_SET_ADV_ENABLE_EVT 1
LE set advertising enable command complete event length.
LHCI_LEN_LE_SET_ADV_PARAM_EVT
#define LHCI_LEN_LE_SET_ADV_PARAM_EVT 1
LE set advertising parameter command complete event length.
LHCI_LEN_LE_SET_ADV_SET_RAND_ADDR
#define LHCI_LEN_LE_SET_ADV_SET_RAND_ADDR 1
LE set advertising set random address command complete event length.
LHCI_LEN_LE_SET_DATA_LEN
#define LHCI_LEN_LE_SET_DATA_LEN 3
LE set data length command complete event length.
LHCI_LEN_LE_SET_DEF_PHY_EVT
#define LHCI_LEN_LE_SET_DEF_PHY_EVT 1
LE set default PHY command complete event length.
LHCI_LEN_LE_SET_DEFAULT_PAST_PARAM
#define LHCI_LEN_LE_SET_DEFAULT_PAST_PARAM 1
LE set default periodic advertising sync transfer parameters command complete event length.
LHCI_LEN_LE_SET_EVENT_MASK_EVT
#define LHCI_LEN_LE_SET_EVENT_MASK_EVT 1
LE set event mask command complete event length.
LHCI_LEN_LE_SET_EXT_ADV_DATA
#define LHCI_LEN_LE_SET_EXT_ADV_DATA 1
LE set extended advertising data command complete event length.
LHCI_LEN_LE_SET_EXT_ADV_ENABLE
#define LHCI_LEN_LE_SET_EXT_ADV_ENABLE 1
LE set extended advertising enable command complete event length.
LHCI_LEN_LE_SET_EXT_ADV_PARAM
#define LHCI_LEN_LE_SET_EXT_ADV_PARAM 2
LE set extended advertising parameters command complete event length.
LHCI_LEN_LE_SET_EXT_SCAN_ENABLE
#define LHCI_LEN_LE_SET_EXT_SCAN_ENABLE 1
LE set extended scan enable command complete event length.
LHCI_LEN_LE_SET_EXT_SCAN_ENABLE_EVT
#define LHCI_LEN_LE_SET_EXT_SCAN_ENABLE_EVT 1
LE set extended scan enable command complete event length.
LHCI_LEN_LE_SET_EXT_SCAN_PARAM
#define LHCI_LEN_LE_SET_EXT_SCAN_PARAM 1
LE set extended scan parameter command complete event length.
LHCI_LEN_LE_SET_EXT_SCAN_RESP_DATA
#define LHCI_LEN_LE_SET_EXT_SCAN_RESP_DATA 1
LE set extended scan response data command complete event length.
LHCI_LEN_LE_SET_HOST_CHAN_CLASS
#define LHCI_LEN_LE_SET_HOST_CHAN_CLASS 1
LE set host channel class command complete event length.
LHCI_LEN_LE_SET_HOST_FEATURE
#define LHCI_LEN_LE_SET_HOST_FEATURE 1
LE Set Host Feature.
LHCI_LEN_LE_SET_PAST_PARAM
#define LHCI_LEN_LE_SET_PAST_PARAM 3
LE set periodic advertising sync transfer parameters command complete event length.
LHCI_LEN_LE_SET_PATH_LOSS_REPORTING_ENABLE
#define LHCI_LEN_LE_SET_PATH_LOSS_REPORTING_ENABLE 3
LE Set path loss reporting enable event.
LHCI_LEN_LE_SET_PATH_LOSS_REPORTING_PARAMS
#define LHCI_LEN_LE_SET_PATH_LOSS_REPORTING_PARAMS 3
LE Set path loss reporting parameters event.
LHCI_LEN_LE_SET_PER_ADV_DATA
#define LHCI_LEN_LE_SET_PER_ADV_DATA 1
LE set periodic advertising data command complete event length.
LHCI_LEN_LE_SET_PER_ADV_ENABLE
#define LHCI_LEN_LE_SET_PER_ADV_ENABLE 1
LE set periodic advertising enable command complete event length.
LHCI_LEN_LE_SET_PER_ADV_PARAM
#define LHCI_LEN_LE_SET_PER_ADV_PARAM 1
LE set periodic advertising parameters command complete event length.
LHCI_LEN_LE_SET_PER_ADV_RCV_ENABLE
#define LHCI_LEN_LE_SET_PER_ADV_RCV_ENABLE 1
LE set periodic advertising receive enable command complete event length.
LHCI_LEN_LE_SET_PRIVACY_MODE
#define LHCI_LEN_LE_SET_PRIVACY_MODE 1
LE set privacy mode command complete event length.
LHCI_LEN_LE_SET_RAND_ADDR_EVT
#define LHCI_LEN_LE_SET_RAND_ADDR_EVT 1
LE set random address command complete event length.
LHCI_LEN_LE_SET_RES_PRIV_ADDR_TO_EVT
#define LHCI_LEN_LE_SET_RES_PRIV_ADDR_TO_EVT 1
LE set resolving private address timeout command complete event length.
LHCI_LEN_LE_SET_SCAN_ENABLE_EVT
#define LHCI_LEN_LE_SET_SCAN_ENABLE_EVT 1
LE set scan enable command complete event length.
LHCI_LEN_LE_SET_SCAN_PARAM_EVT
#define LHCI_LEN_LE_SET_SCAN_PARAM_EVT 1
LE set scan parameter command complete event length.
LHCI_LEN_LE_SET_SCAN_RESP_DATA_EVT
#define LHCI_LEN_LE_SET_SCAN_RESP_DATA_EVT 1
LE set scan response data command complete event length.
LHCI_LEN_LE_SET_TX_POWER_REPORT_EVT
#define LHCI_LEN_LE_SET_TX_POWER_REPORT_EVT 3
LE Set transmit power reporting enable event.
LHCI_LEN_LE_SETUP_ISO_DATA_PATH
#define LHCI_LEN_LE_SETUP_ISO_DATA_PATH 3
LE setup ISO data path.
LHCI_LEN_LE_TEST_END_EVT
#define LHCI_LEN_LE_TEST_END_EVT 3
LE test end command complete event length.
LHCI_LEN_LE_TRANSMITTER_TEST_EVT
#define LHCI_LEN_LE_TRANSMITTER_TEST_EVT 1
LE transmitter test command complete event length.
LHCI_LEN_LE_WRITE_DEF_DATA_LEN
#define LHCI_LEN_LE_WRITE_DEF_DATA_LEN 1
LE write default data length command complete event length.
LHCI_LEN_LE_WRITE_RF_PATH_COMP
#define LHCI_LEN_LE_WRITE_RF_PATH_COMP 1
LE write RF path compensation command complete event length.
LHCI_LEN_READ_AUTH_PAYLOAD_TO_EVT
#define LHCI_LEN_READ_AUTH_PAYLOAD_TO_EVT 5
Read authenticated payload timeout command complete event length.
LHCI_LEN_READ_BD_ADDR_EVT
#define LHCI_LEN_READ_BD_ADDR_EVT 7
Read BD address command complete event length.
LHCI_LEN_READ_BUF_SIZE_EVT
#define LHCI_LEN_READ_BUF_SIZE_EVT 8
Read buffer size command complete event length.
LHCI_LEN_READ_LOCAL_SUP_CMDS_EVT
#define LHCI_LEN_READ_LOCAL_SUP_CMDS_EVT 65
Read local supported commands command complete event length.
LHCI_LEN_READ_LOCAL_SUP_CODEC_CAP
#define LHCI_LEN_READ_LOCAL_SUP_CODEC_CAP 2
Read local supported codec configuration.
LHCI_LEN_READ_LOCAL_SUP_CODECS
#define LHCI_LEN_READ_LOCAL_SUP_CODECS 3
Read local supported codecs.
LHCI_LEN_READ_LOCAL_SUP_CONTROLLER_DLY
#define LHCI_LEN_READ_LOCAL_SUP_CONTROLLER_DLY 7
Read local supported controller delay.
LHCI_LEN_READ_LOCAL_SUP_FEAT_EVT
#define LHCI_LEN_READ_LOCAL_SUP_FEAT_EVT 9
Read local supported feature command complete event length.
LHCI_LEN_READ_LOCAL_VER_EVT
#define LHCI_LEN_READ_LOCAL_VER_EVT 9
Read local version command complete event length.
LHCI_LEN_READ_PWR_LVL_EVT
#define LHCI_LEN_READ_PWR_LVL_EVT 4
Read power level command complete event length.
LHCI_LEN_RESET_EVT
#define LHCI_LEN_RESET_EVT 1
Reset command complete event length.
LHCI_LEN_SET_EVENT_MASK_EVT
#define LHCI_LEN_SET_EVENT_MASK_EVT 1
Set event mask command complete event length.
LHCI_LEN_WRITE_AUTH_PAYLOAD_TO_EVT
#define LHCI_LEN_WRITE_AUTH_PAYLOAD_TO_EVT 3
Write authenticated payload timeout command complete event length.
LHCI_OPCODE_VS_ENA_ACL_SINK
#define LHCI_OPCODE_VS_ENA_ACL_SINK HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E3)
Enable ACL Packet Sink opcode.
LHCI_OPCODE_VS_ENA_AUTO_GEN_ACL
#define LHCI_OPCODE_VS_ENA_AUTO_GEN_ACL HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E5)
Enable Auto Generate ACL Packets opcode.
LHCI_OPCODE_VS_ENA_AUTO_GEN_ISO
#define LHCI_OPCODE_VS_ENA_AUTO_GEN_ISO HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D8)
Enable Auto Generate ISO Packets opcode.
LHCI_OPCODE_VS_ENA_ISO_SINK
#define LHCI_OPCODE_VS_ENA_ISO_SINK HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D7)
Enable ISO Packet Sink opcode.
LHCI_OPCODE_VS_GENERATE_ACL
#define LHCI_OPCODE_VS_GENERATE_ACL HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E4)
Generate ACL Packets opcode.
LHCI_OPCODE_VS_GENERATE_ISO
#define LHCI_OPCODE_VS_GENERATE_ISO HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D5)
Generate ISO Packets opcode.
LHCI_OPCODE_VS_GET_ACL_TEST_REPORT
#define LHCI_OPCODE_VS_GET_ACL_TEST_REPORT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E9)
Get ACL Test Report opcode.
LHCI_OPCODE_VS_GET_ADV_STATS
#define LHCI_OPCODE_VS_GET_ADV_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FB)
Get Advertising Statistics opcode.
LHCI_OPCODE_VS_GET_AUX_ADV_STATS
#define LHCI_OPCODE_VS_GET_AUX_ADV_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DA)
Get Auxiliary Advertising Statistics opcode.
LHCI_OPCODE_VS_GET_AUX_SCAN_STATS
#define LHCI_OPCODE_VS_GET_AUX_SCAN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DB)
Get Auxiliary Scanning Statistics opcode.
LHCI_OPCODE_VS_GET_CIS_STATS
#define LHCI_OPCODE_VS_GET_CIS_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D9)
Get ISO Connection Statistics opcode.
LHCI_OPCODE_VS_GET_CONN_STATS
#define LHCI_OPCODE_VS_GET_CONN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FD)
Get Connection Statistics opcode.
LHCI_OPCODE_VS_GET_ISO_TEST_REPORT
#define LHCI_OPCODE_VS_GET_ISO_TEST_REPORT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D6)
Get ISO Test Report opcode.
LHCI_OPCODE_VS_GET_PDU_FILT_STATS
#define LHCI_OPCODE_VS_GET_PDU_FILT_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F4)
Get PDU Filter Statistics opcode.
LHCI_OPCODE_VS_GET_PEER_MIN_USED_CHAN
#define LHCI_OPCODE_VS_GET_PEER_MIN_USED_CHAN HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3EB)
Get peer minimum number of used channels.
LHCI_OPCODE_VS_GET_PER_CHAN_MAP
#define LHCI_OPCODE_VS_GET_PER_CHAN_MAP HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DE)
Get channel map of periodic scan/adv.
LHCI_OPCODE_VS_GET_PER_SCAN_STATS
#define LHCI_OPCODE_VS_GET_PER_SCAN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DC)
Get Periodic Scanning Statistics opcode.
LHCI_OPCODE_VS_GET_POOL_STATS
#define LHCI_OPCODE_VS_GET_POOL_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FF)
Get Pool Statistics opcode.
LHCI_OPCODE_VS_GET_RAND_ADDR
#define LHCI_OPCODE_VS_GET_RAND_ADDR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F1)
Get Random Address opcode.
LHCI_OPCODE_VS_GET_RSSI
#define LHCI_OPCODE_VS_GET_RSSI
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC, \
               0x306)
Vendor specific Get RSSI
LHCI_OPCODE_VS_GET_SCAN_STATS
#define LHCI_OPCODE_VS_GET_SCAN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FC)
Get Scan Statistics opcode.
LHCI_OPCODE_VS_GET_SYS_STATS
#define LHCI_OPCODE_VS_GET_SYS_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FA)
Get Memory Statistics opcode.
LHCI_OPCODE_VS_GET_TEST_STATS
#define LHCI_OPCODE_VS_GET_TEST_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3FE)
Get Test Statistics opcode.
LHCI_OPCODE_VS_PHY_DIS
#define LHCI_OPCODE_VS_PHY_DIS
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC, \
               0x308)
Vendor specific Get RSSI
LHCI_OPCODE_VS_PHY_EN
#define LHCI_OPCODE_VS_PHY_EN
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC, \
               0x307)
Vendor specific Get RSSI
LHCI_OPCODE_VS_REG_READ
#define LHCI_OPCODE_VS_REG_READ HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x301)
Read data from MCU register or memory space.
LHCI_OPCODE_VS_REG_WRITE
#define LHCI_OPCODE_VS_REG_WRITE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x300)
Write data to MCU register or memory space.
LHCI_OPCODE_VS_RESET_CONN_STATS
#define LHCI_OPCODE_VS_RESET_CONN_STATS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x302)
Reset connection stats.
LHCI_OPCODE_VS_RESET_TEST_STATS
#define LHCI_OPCODE_VS_RESET_TEST_STATS
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC, \
               0x304)
Vendor specific End Test Returning More than RX Packets
LHCI_OPCODE_VS_RX_TEST
#define LHCI_OPCODE_VS_RX_TEST
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC, \
               0x305)
Vendor specific RX Test
LHCI_OPCODE_VS_SET_ADV_TX_PWR
#define LHCI_OPCODE_VS_SET_ADV_TX_PWR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F5)
Set Advertising Tx Power opcode.
LHCI_OPCODE_VS_SET_AUX_DELAY
#define LHCI_OPCODE_VS_SET_AUX_DELAY HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D0)
Set Additional AuxPtr offset.
LHCI_OPCODE_VS_SET_BD_ADDR
#define LHCI_OPCODE_VS_SET_BD_ADDR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F0)
Set BD address opcode.
LHCI_OPCODE_VS_SET_CHAN_MAP
#define LHCI_OPCODE_VS_SET_CHAN_MAP HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F8)
Set Channel Map opcode.
LHCI_OPCODE_VS_SET_CONN_OP_FLAGS
#define LHCI_OPCODE_VS_SET_CONN_OP_FLAGS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E7)
Set Connection Operational Flags opcode.
LHCI_OPCODE_VS_SET_CONN_PHY_TX_PWR
#define LHCI_OPCODE_VS_SET_CONN_PHY_TX_PWR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DD)
Set Connection Phy Tx Power opcode.
LHCI_OPCODE_VS_SET_CONN_TX_PWR
#define LHCI_OPCODE_VS_SET_CONN_TX_PWR HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F6)
Set Connection Tx Power opcode.
LHCI_OPCODE_VS_SET_DIAG_MODE
#define LHCI_OPCODE_VS_SET_DIAG_MODE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F9)
Set Diagnostic Mode opcode.
LHCI_OPCODE_VS_SET_ENC_MODE
#define LHCI_OPCODE_VS_SET_ENC_MODE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F7)
Set Encryption Mode opcode.
LHCI_OPCODE_VS_SET_EVENT_MASK
#define LHCI_OPCODE_VS_SET_EVENT_MASK HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E1)
Set Vendor Specific Event Mask opcode.
LHCI_OPCODE_VS_SET_EXT_ADV_DEF_PHY_OPTS
#define LHCI_OPCODE_VS_SET_EXT_ADV_DEF_PHY_OPTS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D3)
Set extended advertising default PHY options.
LHCI_OPCODE_VS_SET_EXT_ADV_FRAG_LEN
#define LHCI_OPCODE_VS_SET_EXT_ADV_FRAG_LEN
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC,         \
               0x3D1)
Set extended advertising data fragmentation length.
LHCI_OPCODE_VS_SET_EXT_ADV_PHY_OPTS
#define LHCI_OPCODE_VS_SET_EXT_ADV_PHY_OPTS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D2)
Set extended advertising PHY options.
LHCI_OPCODE_VS_SET_EXT_SCAN_PHY_OPTS
#define LHCI_OPCODE_VS_SET_EXT_SCAN_PHY_OPTS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3D4)
Set extended scanning default PHY options.
LHCI_OPCODE_VS_SET_HCI_SUP_CMD
#define LHCI_OPCODE_VS_SET_HCI_SUP_CMD HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3DF)
DEPRECATED.
LHCI_OPCODE_VS_SET_LOCAL_FEAT
#define LHCI_OPCODE_VS_SET_LOCAL_FEAT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F2)
Set Local Feature opcode.
LHCI_OPCODE_VS_SET_LOCAL_MIN_USED_CHAN
#define LHCI_OPCODE_VS_SET_LOCAL_MIN_USED_CHAN HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3EA)
Set local minimum number of used channels.
LHCI_OPCODE_VS_SET_OP_FLAGS
#define LHCI_OPCODE_VS_SET_OP_FLAGS HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3F3)
Set Operational Flags opcode.
LHCI_OPCODE_VS_SET_P256_PRIV_KEY
#define LHCI_OPCODE_VS_SET_P256_PRIV_KEY HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E8)
Set P-256 Private Key opcode.
LHCI_OPCODE_VS_SET_RSRC_MGR_MODE
#define LHCI_OPCODE_VS_SET_RSRC_MGR_MODE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E2)
DEPRECATED.
LHCI_OPCODE_VS_SET_SCAN_CH_MAP
#define LHCI_OPCODE_VS_SET_SCAN_CH_MAP HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E0)
Set Scan Channel Map opcode.
LHCI_OPCODE_VS_SET_SNIFFER_ENABLE
#define LHCI_OPCODE_VS_SET_SNIFFER_ENABLE HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3CD)
Enable sniffer packet forwarding.
LHCI_OPCODE_VS_SET_TX_TEST_ERR_PATT
#define LHCI_OPCODE_VS_SET_TX_TEST_ERR_PATT HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x3E6)
Set Tx Test Error Pattern opcode.
LHCI_OPCODE_VS_TX_TEST
#define LHCI_OPCODE_VS_TX_TEST HCI_OPCODE(HCI_OGF_VENDOR_SPEC, 0x303)
Vendor specific TX test that takes numPkt param.
LHCI_OPCODE_VS_VALIDATE_PUB_KEY_MODE
#define LHCI_OPCODE_VS_VALIDATE_PUB_KEY_MODE
Value:
HCI_OPCODE(HCI_OGF_VENDOR_SPEC,          \
               0x3EC)
Set validate public key mode between ALT1 and ALT2.
LHCI_VS_EVT_MASK_DIAG_TRACE_EVT
#define LHCI_VS_EVT_MASK_DIAG_TRACE_EVT 0x02
(Byte 0) VS event bit, diagnostic tracing.
LHCI_VS_EVT_MASK_ISO_EVENT_CMPL_EVT
#define LHCI_VS_EVT_MASK_ISO_EVENT_CMPL_EVT 0x04
(Byte 0) VS event bit, ISO event complete.
LHCI_VS_EVT_MASK_SCAN_REPORT_EVT
#define LHCI_VS_EVT_MASK_SCAN_REPORT_EVT 0x01
(Byte 0) VS event bit, scan report.
Enumeration Type Documentation
anonymous enum
anonymous enum
Message handler types.
Enumerator
LHCI_MSG_PRIV
Privacy command handler type. Must be before CONN.
LHCI_MSG_CONN
Connection command handler type.
LHCI_MSG_CONN_CS2
Connection Channel Selection 2 command handler type.
LHCI_MSG_ENC
Encryption command handler type.
LHCI_MSG_SCAN
Scan command handler type.
LHCI_MSG_EXT_SCAN
Extended scan command handler type.
LHCI_MSG_PER_SCAN
Periodic scan command handler type.
LHCI_MSG_ADV
Advertising command handler type.
LHCI_MSG_EXT_ADV
Extended advertising command handler type.
LHCI_MSG_PER_ADV
Periodic advertising command handler type.
LHCI_MSG_SC
Secure connections command handler type.
LHCI_MSG_PHY
PHY features command handler type.
LHCI_MSG_PAST
Periodic advertising sync transfer command handler type.
LHCI_MSG_CIS_MST
Connected isochronous stream master features command handler type.
LHCI_MSG_CIS_SLV
Connected isochronous stream slave features command handler type.
LHCI_MSG_BIS_MST
Broadcast isochronous stream master features command handler type.
LHCI_MSG_BIS_SLV
Broadcast isochronous stream slave features command handler type.
LHCI_MSG_ISO
Isochronous features command handler type.
LHCI_MSG_PC
Power control handler type.
LHCI_MSG_VS_EXT
Extended vendor specific command handler type.
LHCI_MSG_TESTER
Tester vendor specific command handler type.
LHCI_MSG_TOTAL
Total number of command handlers.
anonymous enum
anonymous enum
Task event types.
Enumerator
LHCI_EVT_ACL_RCVD
HCI ACL packet received.
LHCI_EVT_CMD_RCVD
HCI command packet received.
LHCI_EVT_SEND_CMPL
HCI event packet send completion.
LHCI_EVT_HW_ERR
HCI hardware error.
LHCI_EVT_ISO_RCVD
HCI ISO packet received.
Function Documentation
lhciAclRecvPending()
void lhciAclRecvPending (uint16_t handle, uint8_t numBufs)
LL ACL receive pending event handler.
Parameters
handle Connection handle.
numBufs Number of buffers.
References lhciCb, LlRecvAclData(), and lhciCb_t::recvAclSink.
lhciAclSendComplete()
void lhciAclSendComplete (uint16_t handle, uint8_t numBufs)
LL ACL send complete event handler.
Parameters
handle Connection handle.
numBufs Number of buffers.
References lhciCb_t::genPktLen, lhciAllocEvt(), and lhciCb.
lhciAllocCmdCmplEvt()
uint8_t* lhciAllocCmdCmplEvt (uint8_t paramLen, uint16_t opCode)
Allocate a command complete event.
Parameters
paramLen Parameter length.
opCode OpCode command field.
Returns
Buffer for command complete event.
References HCI_EVT_HDR_LEN, HCI_LEN_CMD_CMPL, and WsfMsgAlloc().
lhciAllocEvt()
uint8_t* lhciAllocEvt (uint8_t evtCode, uint8_t paramLen)
Allocate an event.
Parameters
evtCode Event code.
paramLen Parameter length.
Returns
Buffer for event.
References HCI_EVT_HDR_LEN, and WsfMsgAlloc().
lhciCommonDecodeCmdPkt()
bool_t lhciCommonDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
status
local device management
test
default/unused
Returns
TRUE if opcode handled, FALSE otherwise.
lhciCommonVsStdDecodeCmdPkt()
bool_t lhciCommonVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Packetcraft common vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciConnCsEncodeEvtPkt()
bool_t lhciConnCsEncodeEvtPkt (LlEvt_t * pEvt)
LL channel selection event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciConnDecodeCmdPkt()
bool_t lhciConnDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
connection control
connection status
local device management
remote device management
default
Returns
TRUE if opcode handled, FALSE otherwise.
lhciConnEncodeEvtPkt()
bool_t lhciConnEncodeEvtPkt (LlEvt_t * pEvt)
LL connection event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciConnSendCmdCmplEvt()
void lhciConnSendCmdCmplEvt (LhciHdr_t * pCmdHdr, uint8_t status, uint8_t paramLen, uint8_t * pParam, uint16_t handle)
Build and send a command complete event packet.
Parameters
pCmdHdr Command HCI header.
status Status value.
paramLen Parameter length of the command status event.
pParam Parameter buffer.
handle Connection handle.
References lhciAllocCmdCmplEvt(), and LhciHdr_t::opCode.
lhciConnVsStdDecodeCmdPkt()
bool_t lhciConnVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. connection vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciGenerateAcl()
void lhciGenerateAcl (uint16_t handle, uint16_t pktLen, uint8_t numPkts)
Generate ACL packets.
Parameters
handle Connection handle.
pktLen Packet length.
numPkts Number of packets.
References lhciCb_t::genEnaFlag, and lhciCb.
lhciGenerateIso()
void lhciGenerateIso (uint16_t handle, uint16_t pktLen, uint8_t numPkts)
Generate ISO packets.
Parameters
handle Connection handle.
pktLen Packet length.
numPkts Number of packets.
References lhciIsoCb_t::genEnaFlag.
lhciIsoDecodeCmdPkt()
bool_t lhciIsoDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciIsoEncodeEvtPkt()
bool_t lhciIsoEncodeEvtPkt (LlEvt_t * pEvt)
LL ISO event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciIsoRecvPending()
void lhciIsoRecvPending (uint8_t numHandles, uint16_t * pHandle, uint16_t * pNumPkts)
LL ISO receive pending event handler.
Parameters
numHandles Number of handles.
pHandle Array of CIS or BIS handle.
pNumPkts Array of number of pending packets.
References lhciIsoCb_t::isoRxTest, and lhciIsoCb.
lhciIsoSendComplete()
void lhciIsoSendComplete (uint8_t numHandles, uint16_t * pHandle, uint16_t * pNumPkts)
LL ISO send complete event handler.
Parameters
numHandles Number of handles.
pHandle Array of CIS or BIS handle.
pNumPkts Array of number of completed packets.
References lhciAllocEvt().
lhciIsoVsStdDecodeCmdPkt()
bool_t lhciIsoVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. connection vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciLlEvtHandler()
bool_t lhciLlEvtHandler (LlEvt_t * pEvt)
LL event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event sent, FALSE otherwise.
lhciMstBisDecodeCmdPkt()
bool_t lhciMstBisDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstBisEncodeEvtPkt()
bool_t lhciMstBisEncodeEvtPkt (LlEvt_t * pEvt)
LL BIS master event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciMstCisDecodeCmdPkt()
bool_t lhciMstCisDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstCisEncodeEvtPkt()
bool_t lhciMstCisEncodeEvtPkt (LlEvt_t * pEvt)
LL CIS master event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciMstConnDecodeCmdPkt()
bool_t lhciMstConnDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
connection control
default
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstConnEncodeEvtPkt()
bool_t lhciMstConnEncodeEvtPkt (LlEvt_t * pEvt)
LL master connection event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciMstConnVsStdDecodeCmdPkt()
bool_t lhciMstConnVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. master connection vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstEncDecodeCmdPkt()
bool_t lhciMstEncDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
data & flow control
status
advertising control
remote device management
local device management
test
default/unused
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstEncEncodeEvtPkt()
bool_t lhciMstEncEncodeEvtPkt (LlEvt_t * pEvt)
LL slave data event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciMstExtConnDecodeCmdPkt()
bool_t lhciMstExtConnDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
connection control
default
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstExtScanDecodeCmdPkt()
bool_t lhciMstExtScanDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstExtScanEncodeEvtPkt()
bool_t lhciMstExtScanEncodeEvtPkt (LlEvt_t * pEvt)
LL master advertising extension event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciMstExtScanVsStdDecodeCmdPkt()
bool_t lhciMstExtScanVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode master extended advertising vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstScanDecodeCmdPkt()
bool_t lhciMstScanDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
scan control
default/unused
Returns
TRUE if opcode handled, FALSE otherwise.
lhciMstScanEncodeEvtPkt()
bool_t lhciMstScanEncodeEvtPkt (LlEvt_t * pEvt)
LL master advertising event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciMstScanVsStdDecodeCmdPkt()
bool_t lhciMstScanVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. master advertising vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciPastDecodeCmdPkt()
bool_t lhciPastDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciPclDecodeCmdPkt()
bool_t lhciPclDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
connection control
connection status
local device management
remote device management
default
Returns
TRUE if opcode handled, FALSE otherwise.
lhciPclEncodeEvtPkt()
bool_t lhciPclEncodeEvtPkt (LlEvt_t * pEvt)
LL connection event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciPclSendCmdCmplEvt()
void lhciPclSendCmdCmplEvt (LhciHdr_t * pCmdHdr, uint8_t status, uint8_t paramLen, uint8_t * pParam, uint16_t handle)
Build and send a command complete event packet.
Parameters
pCmdHdr Command HCI header.
status Status value.
paramLen Parameter length of the command status event.
pParam Parameter buffer.
handle Connection handle.
References lhciAllocCmdCmplEvt(), and LhciHdr_t::opCode.
lhciPhyDecodeCmdPkt()
bool_t lhciPhyDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciPhyEncodeEvtPkt()
bool_t lhciPhyEncodeEvtPkt (LlEvt_t * pEvt)
LL PHY features event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciPrivAdvDecodeCmdPkt()
bool_t lhciPrivAdvDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciPrivConnDecodeCmdPkt()
bool_t lhciPrivConnDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciPrivConnEncodeEvtPkt()
bool_t lhciPrivConnEncodeEvtPkt (LlEvt_t * pEvt)
LL privacy connection event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciRecv()
void lhciRecv (uint8_t type, uint8_t * pBuf)
Queue a received buffer for processing by the message handler.
Parameters
type Type of message.
pBuf Pointer to received message.
References lhciPersistCb_t::aclQ, lhciPersistCb_t::cmdQ, lhciPersistCb_t::handlerId, lhciPersistCb_t::isoQ, LHCI_EVT_ACL_RCVD, LHCI_EVT_CMD_RCVD, LHCI_EVT_ISO_RCVD, WsfMsgEnq(), WsfMsgFree(), and WsfSetEvent().
lhciRecvAcl()
uint8_t* lhciRecvAcl (void)
Receive LL ACL.
Returns
Pointer to buffer for transport.
References LlRecvAclData().
lhciRecvIso()
uint8_t* lhciRecvIso (void)
Receive LL ISO.
Returns
Pointer to buffer for transport.
References LlRecvIsoData().
lhciReset()
void lhciReset (void)
Reset HCI state.
This function is called at the end of a HCI reset.
References lhciCb_t::evtCompCback, lhciCb_t::evtMsk, lhciCb_t::evtMskPg2, HCI_SUP_CONFIG_DATA_PATH, HCI_SUP_DISCONNECT, HCI_SUP_LE_ACCEPT_CIS_REQ, HCI_SUP_LE_ADD_DEV_PER_ADV_LIST, HCI_SUP_LE_ADD_DEV_RES_LIST_EVT, HCI_SUP_LE_ADD_DEV_WHITE_LIST, HCI_SUP_LE_BIG_CREATE_SYNC, HCI_SUP_LE_BIG_TERMINATE_SYNC, HCI_SUP_LE_CLEAR_ADV_SETS, HCI_SUP_LE_CLEAR_PER_ADV_LIST, HCI_SUP_LE_CLEAR_RES_LIST, HCI_SUP_LE_CLEAR_WHITE_LIST, HCI_SUP_LE_CONN_UPDATE, HCI_SUP_LE_CREATE_BIG, HCI_SUP_LE_CREATE_BIG_TEST, HCI_SUP_LE_CREATE_CIS, HCI_SUP_LE_CREATE_CONN, HCI_SUP_LE_CREATE_CONN_CANCEL, HCI_SUP_LE_ENCRYPT, HCI_SUP_LE_ENH_READ_TX_POWER_LEVEL, HCI_SUP_LE_ENHANCED_RECEIVER_TEST, HCI_SUP_LE_ENHANCED_TRANSMITTER_TEST, HCI_SUP_LE_EXT_CREATE_CONN, HCI_SUP_LE_GENERATE_DHKEY, HCI_SUP_LE_ISO_READ_TEST_COUNTERS, HCI_SUP_LE_ISO_RECEIVE_TEST, HCI_SUP_LE_ISO_TEST_END, HCI_SUP_LE_ISO_TRANSMIT_TEST, HCI_SUP_LE_LTK_REQ_NEG_REPL, HCI_SUP_LE_LTK_REQ_REPL, HCI_SUP_LE_PER_ADV_CREATE_SYNC, HCI_SUP_LE_PER_ADV_CREATE_SYNC_CANCEL, HCI_SUP_LE_PER_ADV_SET_INFO_TRANSFER, HCI_SUP_LE_PER_ADV_SYNC_TRANSFER, HCI_SUP_LE_PER_ADV_TERMINATE_SYNC, HCI_SUP_LE_RAND, HCI_SUP_LE_READ_ADV_TX_POWER, HCI_SUP_LE_READ_BUF_SIZE, HCI_SUP_LE_READ_BUF_SIZE_V2, HCI_SUP_LE_READ_CHAN_MAP, HCI_SUP_LE_READ_DEF_DATA_LEN, HCI_SUP_LE_READ_ISO_LINK_QUALITY, HCI_SUP_LE_READ_ISO_TX_SYNC, HCI_SUP_LE_READ_LOCAL_P256_PUB_KEY, HCI_SUP_LE_READ_LOCAL_RES_ADDR, HCI_SUP_LE_READ_LOCAL_SUP_FEAT, HCI_SUP_LE_READ_MAX_ADV_DATA_LEN, HCI_SUP_LE_READ_MAX_DATA_LEN, HCI_SUP_LE_READ_NUM_OF_SUP_ADV_SETS, HCI_SUP_LE_READ_PEER_RES_ADDR, HCI_SUP_LE_READ_PER_ADV_LIST_SIZE, HCI_SUP_LE_READ_PHY, HCI_SUP_LE_READ_REMOTE_FEAT, HCI_SUP_LE_READ_REMOTE_TX_POWER_LEVEL, HCI_SUP_LE_READ_RES_LIST_SIZE, HCI_SUP_LE_READ_RF_PATH_COMP, HCI_SUP_LE_READ_SUP_STATES, HCI_SUP_LE_READ_TX_POWER, HCI_SUP_LE_READ_WHITE_LIST_SIZE, HCI_SUP_LE_RECEIVER_TEST, HCI_SUP_LE_REJECT_CIS_REQ, HCI_SUP_LE_REM_CONN_PARAM_REQ_NEG_REPL, HCI_SUP_LE_REM_CONN_PARAM_REQ_REPL, HCI_SUP_LE_REMOVE_ADV_SET, HCI_SUP_LE_REMOVE_CIG, HCI_SUP_LE_REMOVE_DEV_PER_ADV_LIST, HCI_SUP_LE_REMOVE_DEV_RES_LIST, HCI_SUP_LE_REMOVE_DEV_WHITE_LIST, HCI_SUP_LE_REMOVE_ISO_DATA_PATH, HCI_SUP_LE_REQ_PEER_SCA, HCI_SUP_LE_SET_ADDR_RES_ENABLE, HCI_SUP_LE_SET_ADV_DATA, HCI_SUP_LE_SET_ADV_ENABLE, HCI_SUP_LE_SET_ADV_PARAM, HCI_SUP_LE_SET_ADV_SET_RAND_ADDR, HCI_SUP_LE_SET_CIG_PARAM, HCI_SUP_LE_SET_CIG_PARAM_TEST, HCI_SUP_LE_SET_DATA_LEN, HCI_SUP_LE_SET_DEF_PHY, HCI_SUP_LE_SET_DEFAULT_PAST_PARAM, HCI_SUP_LE_SET_EVENT_MASK, HCI_SUP_LE_SET_EXT_ADV_DATA, HCI_SUP_LE_SET_EXT_ADV_ENABLE, HCI_SUP_LE_SET_EXT_ADV_PARAM, HCI_SUP_LE_SET_EXT_SCAN_ENABLE, HCI_SUP_LE_SET_EXT_SCAN_PARAM, HCI_SUP_LE_SET_EXT_SCAN_RESP_DATA, HCI_SUP_LE_SET_HOST_CHAN_CLASS, HCI_SUP_LE_SET_HOST_FEATURE, HCI_SUP_LE_SET_PAST_PARAM, HCI_SUP_LE_SET_PATH_LOSS_REPORT_ENABLE, HCI_SUP_LE_SET_PATH_LOSS_REPORT_PARAM, HCI_SUP_LE_SET_PER_ADV_DATA, HCI_SUP_LE_SET_PER_ADV_ENABLE, HCI_SUP_LE_SET_PER_ADV_PARAM, HCI_SUP_LE_SET_PER_ADV_RCV_ENABLE, HCI_SUP_LE_SET_PHY, HCI_SUP_LE_SET_PRIVACY_MODE, HCI_SUP_LE_SET_RAND_ADDR, HCI_SUP_LE_SET_RES_PRIV_ADDR_TO, HCI_SUP_LE_SET_SCAN_ENABLE, HCI_SUP_LE_SET_SCAN_PARAM, HCI_SUP_LE_SET_SCAN_RESP_DATA, HCI_SUP_LE_SET_TX_POWER_REPORT_ENABLE, HCI_SUP_LE_SETUP_ISO_DATA_PATH, HCI_SUP_LE_START_ENCRYPTION, HCI_SUP_LE_TERMINATE_BIG, HCI_SUP_LE_TEST_END, HCI_SUP_LE_TRANSMITTER_TEST, HCI_SUP_LE_TRANSMITTER_TEST_V4, HCI_SUP_LE_WRITE_DEF_DATA_LEN, HCI_SUP_LE_WRITE_RF_PATH_COMP, HCI_SUP_READ_AUTH_PAYLOAD_TO, HCI_SUP_READ_BD_ADDR, HCI_SUP_READ_LOCAL_SUP_CODEC_CAP, HCI_SUP_READ_LOCAL_SUP_CODECS_V2, HCI_SUP_READ_LOCAL_SUP_CTR_DLY, HCI_SUP_READ_LOCAL_SUP_FEAT, HCI_SUP_READ_LOCAL_VER_INFO, HCI_SUP_READ_REMOTE_VER_INFO, HCI_SUP_READ_RSSI, HCI_SUP_READ_TX_PWR_LVL, HCI_SUP_RESET, HCI_SUP_SET_EVENT_MASK, HCI_SUP_SET_EVENT_MASK_PAGE2, HCI_SUP_WRITE_AUTH_PAYLOAD_TO, lhciCb_t::leEvtMsk, LHCI_DEF_EVT_MASK, LHCI_DEF_EVT_PG2_MASK, LHCI_DEF_LE_EVT_MASK, LHCI_MSG_ADV, LHCI_MSG_BIS_MST, LHCI_MSG_BIS_SLV, LHCI_MSG_CIS_MST, LHCI_MSG_CIS_SLV, LHCI_MSG_CONN, LHCI_MSG_ENC, LHCI_MSG_EXT_ADV, LHCI_MSG_EXT_SCAN, LHCI_MSG_ISO, LHCI_MSG_PAST, LHCI_MSG_PC, LHCI_MSG_PER_ADV, LHCI_MSG_PER_SCAN, LHCI_MSG_PHY, LHCI_MSG_PRIV, LHCI_MSG_SC, LHCI_MSG_SCAN, lhciCmdTbl, and lhciPersistCb_t::supCmds.
lhciScDecodeCmdPkt()
bool_t lhciScDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
LE secure connections
default/unused
Returns
TRUE if opcode handled, FALSE otherwise.
lhciScEncodeEvtPkt()
bool_t lhciScEncodeEvtPkt (LlEvt_t * pEvt)
LL secure connections data event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciScVsStdDecodeCmdPkt()
bool_t lhciScVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. master secure connections vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSendCmdStatusEvt()
void lhciSendCmdStatusEvt (LhciHdr_t * pCmdHdr, uint8_t status)
Build and send command status event packet.
Parameters
pCmdHdr Command HCI header.
status Status value.
References lhciAllocEvt().
lhciSendComplete()
void lhciSendComplete (uint8_t type, uint8_t * pBuf)
Signal transport send completion.
Parameters
type Type of message.
pBuf Pointer to transmitted message.
lhciSendHwError()
void lhciSendHwError (uint8_t code)
Signal transport hardware error.
Parameters
code Error code.
References lhciPersistCb_t::handlerId, lhciCb_t::hwErrorCode, LHCI_EVT_HW_ERR, and WsfSetEvent().
lhciService()
bool_t lhciService (uint8_t * pType, uint16_t * pLen, uint8_t ** pBuf)
Service LHCI for transport.
Parameters
pType Storage for type of message.
pLen Storage for length of message.
pBuf Storage for pointer to transmitted message.
Returns
TRUE if message ready.
lhciSlvAdvDecodeCmdPkt()
bool_t lhciSlvAdvDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
status
advertising control
default/unused
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvAdvEncodeEvtPkt()
bool_t lhciSlvAdvEncodeEvtPkt (LlEvt_t * pEvt)
LL slave advertising data event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciSlvAdvVsStdDecodeCmdPkt()
bool_t lhciSlvAdvVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. slave advertising vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvBigEncodeEvtPkt()
bool_t lhciSlvBigEncodeEvtPkt (LlEvt_t * pEvt)
LL BIS slave event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciSlvBisDecodeCmdPkt()
bool_t lhciSlvBisDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvCisDecodeCmdPkt()
bool_t lhciSlvCisDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvCisEncodeEvtPkt()
bool_t lhciSlvCisEncodeEvtPkt (LlEvt_t * pEvt)
LL CIS slave event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciSlvEncDecodeCmdPkt()
bool_t lhciSlvEncDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Command processing is organized by urgency then by frequency of command calls during normal operation. The following grouping is used:
encryption
default/unused
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvEncEncodeEvtPkt()
bool_t lhciSlvEncEncodeEvtPkt (LlEvt_t * pEvt)
LL slave data event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciSlvEncVsStdDecodeCmdPkt()
bool_t lhciSlvEncVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode Arm Ltd. slave encryption vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvExtAdvDecodeCmdPkt()
bool_t lhciSlvExtAdvDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode an HCI command packet.
Parameters
pHdr Decoded packet header.
pBuf Packed HCI packet buffer.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvExtAdvEncodeEvtPkt()
bool_t lhciSlvExtAdvEncodeEvtPkt (LlEvt_t * pEvt)
LL slave advertising extension data event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciSlvExtAdvVsStdDecodeCmdPkt()
bool_t lhciSlvExtAdvVsStdDecodeCmdPkt (LhciHdr_t * pHdr, uint8_t * pBuf)
Decode slave extended advertising vendor specific HCI command packet.
Parameters
pHdr Unpacked command header.
pBuf Packed HCI packet buffer.
Command processing for vendor specific commands.
Returns
TRUE if opcode handled, FALSE otherwise.
lhciSlvVsStdEncodeEvtPkt()
bool_t lhciSlvVsStdEncodeEvtPkt (LlEvt_t * pEvt)
LL slave VS event handler.
Parameters
pEvt Buffer containing LL event.
Returns
TRUE if event handled, FALSE otherwise.
lhciUnpackConnSpec()
uint8_t lhciUnpackConnSpec (LlConnSpec_t * pConnSpec, const uint8_t * pBuf)
Unpack a connection specification from a command packet.
Parameters
pConnSpec Unpacked command structure.
pBuf Packed packet buffer.
Returns
Payload length.
References BSTREAM_TO_UINT16, LlConnSpec_t::connIntervalMax, LlConnSpec_t::connIntervalMin, LlConnSpec_t::connLatency, LHCI_LEN_READ_PWR_LVL_EVT, LlConnSpec_t::maxCeLen, LlConnSpec_t::minCeLen, LlConnSpec_t::supTimeout, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
Variable Documentation
lhciCmdTbl
lhciCmdHandler_t lhciCmdTbl[LHCI_MSG_TOTAL]
Command handler table.
Command handler table.
lhciEvtTbl
lhciEvtHandler_t lhciEvtTbl[LHCI_MSG_TOTAL]
Event handler table.
Event handler table.