Cordio: PAL_TIMER
PAL_TIMER
Typedefs
typedef void(* PalTimerCompCback_t) (void)
Enumerations
enum PalTimerState_t
Functions
void PalTimerInit (PalTimerCompCback_t expCback)
void PalTimerDeInit (void)
PalTimerState_t PalTimerGetState (void)
void PalTimerStart (uint32_t expUsec)
void PalTimerStop (void)
uint32_t PalTimerGetExpTime (void)
void PalTimerSleep (uint32_t expUsec)
void PalTimerRestore (uint32_t schTime)
void PalTimerSetIRQPriority (uint32_t priority)
Detailed Description
Enumeration Type Documentation
PalTimerState_t
enum PalTimerState_t
Operational states.
Enumerator
PAL_TIMER_STATE_UNINIT
Uninitialized state.
PAL_TIMER_STATE_ERROR
Error state.
PAL_TIMER_STATE_READY
Ready state.
PAL_TIMER_STATE_BUSY
Busy state.
Function Documentation
PalTimerDeInit()
void PalTimerDeInit (void)
De-Initialize timer resources.
Returns
None.
References PAL_TIMER_STATE_UNINIT.
PalTimerGetExpTime()
uint32_t PalTimerGetExpTime (void)
Get the time in microseconds before the next PalTimer expiration.
Returns
Time to next PalTimer expiration in micro seconds.
References PAL_RTC_TICKS_PER_SEC, and PAL_TIMER_STATE_BUSY.
PalTimerGetState()
PalTimerState_t PalTimerGetState (void)
Return scheduler timer state.
Returns
state.
PalTimerInit()
void PalTimerInit (PalTimerCompCback_t expCback)
Initialize timer resources.
Returns
None.
References PAL_TIMER_STATE_UNINIT.
PalTimerRestore()
void PalTimerRestore (uint32_t expUsec)
Restore timer state after deep sleep.
Parameters
expUsec Countdown time in microseconds, adjusted for sleep time.
Returns
None.
References PAL_TIMER_STATE_UNINIT, PalTimerInit(), and PalTimerStart().
PalTimerSetIRQPriority()
void PalTimerSetIRQPriority (uint32_t priority)
Configure PAL timer interrupt priority.
Parameters
priority Interrupt priority.
Returns
None.
PalTimerSleep()
void PalTimerSleep (uint32_t expUsec)
Sleep and use the timer to wakeup after expUsec micros seconds.
Parameters
expUsec Countdown time in microseconds.
Returns
None.
References PAL_LED_ID_CPU_ACTIVE, PalLedOff(), and PalLedOn().
PalTimerStart()
void PalTimerStart (uint32_t expUsec)
Register a callback and set a timer.
Parameters
expUsec Countdown time in microseconds.
Returns
None.
References PAL_RTC_TICKS_PER_SEC, PAL_TIMER_STATE_BUSY, PAL_TIMER_STATE_READY, PalSysSetBusy(), WsfCsEnter(), and WsfCsExit().
PalTimerStop()
void PalTimerStop (void)
Cancel a timer operation.
Returns
None.
References PAL_TIMER_STATE_READY.