Cordio: Scenes Server Model API
Scenes Server Model API
Data Structures
struct mmdlSceneSrDesc_t
Macros
#define MMDL_SCENE_STATE_CNT 1
Functions
void MmdlSceneSrInit (void)
void MmdlSceneSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlSceneSrHandler (wsfMsgHdr_t *pMsg)
void MmdlSceneSetupSrHandler (wsfMsgHdr_t *pMsg)
void MmdlSceneSrPublish (meshElementId_t elementId)
void MmdlSceneSrPublishRegister (meshElementId_t elementId)
void MmdlSceneSrRegister (mmdlEventCback_t recvCback)
Variables
wsfHandlerId_t mmdlSceneSrHandlerId
Supported opcodes
const meshMsgOpcode_t mmdlSceneSrRcvdOpcodes []
const meshMsgOpcode_t mmdlSceneSetupSrRcvdOpcodes []
Detailed Description
Data Structure Documentation
mmdlSceneSrDesc_t
struct mmdlSceneSrDesc_t
Model Scene Server descriptor definition.
Data Fields
mmdlSceneNumber_t * pStoredScenes
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
uint8_t targetSceneIdx
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
mmdlSceneStatus_t delayedStatus
uint16_t ackAppKeyIndex
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the delayed message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
delayedStatus
mmdlSceneStatus_t delayedStatus
Status of delayed command.
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages
pStoredScenes
mmdlSceneNumber_t* pStoredScenes
Pointer to the structure that stores current scene and scene register. Structure will store ::MMDL_NUM_OF_SCENES + MMDL_SCENE_STATE_CNT states.
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
targetSceneIdx
uint8_t targetSceneIdx
Target scene index in scene register
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
Function Documentation
MmdlSceneSetupSrHandler()
void MmdlSceneSetupSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Scenes Setup Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelEvt_t::msgRecvEvt, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlSceneSrHandler()
void MmdlSceneSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Scenes Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlSceneSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlSceneSrHandlerInit()
void MmdlSceneSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Scenes Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Scenes Server Model.
Returns
None.
References mmdlSceneSrHandlerId.
MmdlSceneSrInit()
void MmdlSceneSrInit (void)
Initializes the Scenes Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlSceneSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlSceneSrDesc_t::srcAddr, and mmdlSceneSrDesc_t::transitionTimer.
MmdlSceneSrPublish()
void MmdlSceneSrPublish (meshElementId_t elementId)
Publish a Scene Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References mmdlSceneSrDesc_t::delay5Ms, meshPubMsgInfo_t::elementId, MESH_PUB_MSG_INFO, MeshPublishMessage(), meshPubMsgInfo_t::opcode, meshMsgOpcode_t::opcodeBytes, mmdlSceneSrDesc_t::pStoredScenes, mmdlSceneSrDesc_t::remainingTimeMs, mmdlSceneSrDesc_t::targetSceneIdx, wsfTimer_t::ticks, mmdlSceneSrDesc_t::transitionTimer, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, and WSF_MS_PER_TICK.
MmdlSceneSrPublishRegister()
void MmdlSceneSrPublishRegister (meshElementId_t elementId)
Publish a Scene Register Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References meshPubMsgInfo_t::elementId, MESH_PUB_MSG_INFO, MeshPublishMessage(), MMDL_STATE_UPDATED_BY_BIND, mmdlSceneSrDesc_t::pStoredScenes, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, WsfBufAlloc(), and WsfBufFree().
MmdlSceneSrRegister()
void MmdlSceneSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
Variable Documentation
mmdlSceneSetupSrRcvdOpcodes
const meshMsgOpcode_t mmdlSceneSetupSrRcvdOpcodes[]
Supported opcodes
mmdlSceneSrHandlerId
wsfHandlerId_t mmdlSceneSrHandlerId
WSF handler id.
WSF handler ID
mmdlSceneSrRcvdOpcodes
const meshMsgOpcode_t mmdlSceneSrRcvdOpcodes[]
Supported opcodes