Cordio: STACK_DM_API
STACK_DM_API
Data Structures
struct dmCfg_t
struct dmSecLtk_t
struct dmSecIrk_t
struct dmSecCsrk_t
union dmSecKey_t
struct dmSecPairCmplIndEvt_t
struct dmSecEncryptIndEvt_t
struct dmSecAuthReqIndEvt_t
struct dmSecPairIndEvt_t
struct dmSecSlaveIndEvt_t
struct dmSecKeyIndEvt_t
struct dmSecCnfIndEvt_t
struct dmSecKeypressIndEvt_t
struct dmPrivGenAddrIndEvt_t
struct dmSecOobCalcIndEvt_t
struct dmAdvNewAddrIndEvt_t
struct dmAdvSetStartEvt_t
struct dmPerAdvSetStartEvt_t
struct dmPerAdvSetStopEvt_t
struct dmL2cCmdRejEvt_t
union dmEvt_t
struct dmSecLescOobCfg_t
Macros
#define DM_SEC_HCI_ERR_BASE 0x20
Typedefs
typedef uint8_t dmConnId_t
typedef uint8_t dmSyncId_t
typedef void(* dmCback_t) (dmEvt_t *pDmEvt)
GAP Device Role
Connectable GAP Roles.
#define DM_ROLE_MASTER HCI_ROLE_MASTER
#define DM_ROLE_SLAVE HCI_ROLE_SLAVE
GAP Discovery Mode
When setup as a discoverable device, these are the possible modes of discovery.
#define DM_DISC_MODE_NONE 0
#define DM_DISC_MODE_LIMITED 1
#define DM_DISC_MODE_GENERAL 2
GAP Advertising Type
Type of connectable or disconverable advertising to perform.
#define DM_ADV_CONN_UNDIRECT 0
#define DM_ADV_CONN_DIRECT 1
#define DM_ADV_SCAN_UNDIRECT 2
#define DM_ADV_NONCONN_UNDIRECT 3
#define DM_ADV_CONN_DIRECT_LO_DUTY 4
GAP AE Advertising Types
Advertising extension types - AE only.
#define DM_EXT_ADV_CONN_UNDIRECT 5
#define DM_EXT_ADV_NONCONN_DIRECT 6
#define DM_EXT_ADV_SCAN_DIRECT 7
#define DM_ADV_NONE 255
GAP Advertising Report Type
Type of an advertising report observed while scanning.
#define DM_RPT_CONN_UNDIRECT 0
#define DM_RPT_CONN_DIRECT 1
#define DM_RPT_SCAN_UNDIRECT 2
#define DM_RPT_NONCONN_UNDIRECT 3
#define DM_RPT_SCAN_RESPONSE 4
GAP Advertising Data Location
Whether data is located in the advertising data or in the scan response data
#define DM_DATA_LOC_ADV 0
#define DM_DATA_LOC_SCAN 1
GAP Scan Type
When setup as a connectable or observer device, this is the type of scanning to perform.
#define DM_SCAN_TYPE_PASSIVE 0
#define DM_SCAN_TYPE_ACTIVE 1
GAP Advertising Channel Map
Advertising channel map codes
#define DM_ADV_CHAN_37 HCI_ADV_CHAN_37
#define DM_ADV_CHAN_38 HCI_ADV_CHAN_38
#define DM_ADV_CHAN_39 HCI_ADV_CHAN_39
#define DM_ADV_CHAN_ALL (HCI_ADV_CHAN_37 | HCI_ADV_CHAN_38 | HCI_ADV_CHAN_39)
DM Client IDs
The client ID parameter to function DmConnRegister()
#define DM_CLIENT_ID_ATT 0
#define DM_CLIENT_ID_SMP 1
#define DM_CLIENT_ID_DM 2
#define DM_CLIENT_ID_APP 3
#define DM_CLIENT_ID_L2C 4
#define DM_CLIENT_ID_MAX 5
DM Unknown IDs
Values for unknown or unspecificed device identifiers.
#define DM_CONN_ID_NONE 0
#define DM_SYNC_ID_NONE 0
#define DM_CIG_ID_NONE 0xFF
#define DM_CIS_ID_NONE 0xFF
GAP Address Type
The address type to use over the air or that is associated with a received address.
#define DM_ADDR_PUBLIC 0x00
#define DM_ADDR_RANDOM 0x01
#define DM_ADDR_PUBLIC_IDENTITY 0x02
#define DM_ADDR_RANDOM_IDENTITY 0x03
#define DM_ADDR_RANDOM_UNRESOLVED 0xFE
#define DM_ADDR_NONE 0xFF
GAP Advertising Data Types
Advertising data types flags.
#define DM_ADV_TYPE_FLAGS 0x01
#define DM_ADV_TYPE_16_UUID_PART 0x02
#define DM_ADV_TYPE_16_UUID 0x03
#define DM_ADV_TYPE_32_UUID_PART 0x04
#define DM_ADV_TYPE_32_UUID 0x05
#define DM_ADV_TYPE_128_UUID_PART 0x06
#define DM_ADV_TYPE_128_UUID 0x07
#define DM_ADV_TYPE_SHORT_NAME 0x08
#define DM_ADV_TYPE_LOCAL_NAME 0x09
#define DM_ADV_TYPE_TX_POWER 0x0A
#define DM_ADV_TYPE_SM_TK_VALUE 0x10
#define DM_ADV_TYPE_SM_OOB_FLAGS 0x11
#define DM_ADV_TYPE_CONN_INTERVAL 0x12
#define DM_ADV_TYPE_SIGNED_DATA 0x13
#define DM_ADV_TYPE_16_SOLICIT 0x14
#define DM_ADV_TYPE_128_SOLICIT 0x15
#define DM_ADV_TYPE_SERVICE_DATA 0x16
#define DM_ADV_TYPE_PUBLIC_TARGET 0x17
#define DM_ADV_TYPE_RANDOM_TARGET 0x18
#define DM_ADV_TYPE_APPEARANCE 0x19
#define DM_ADV_TYPE_ADV_INTERVAL 0x1A
#define DM_ADV_TYPE_BD_ADDR 0x1B
#define DM_ADV_TYPE_ROLE 0x1C
#define DM_ADV_TYPE_32_SOLICIT 0x1F
#define DM_ADV_TYPE_SVC_DATA_32 0x20
#define DM_ADV_TYPE_SVC_DATA_128 0x21
#define DM_ADV_TYPE_LESC_CONFIRM 0x22
#define DM_ADV_TYPE_LESC_RANDOM 0x23
#define DM_ADV_TYPE_URI 0x24
#define DM_ADV_TYPE_INDOOR_POS 0x25
#define DM_ADV_TYPE_TRANS_DISC 0x26
#define DM_ADV_TYPE_LE_SUP_FEAT 0x27
#define DM_ADV_TYPE_CH_MAP_UPD_IND 0x28
#define DM_ADV_TYPE_PB_ADV 0x29
#define DM_ADV_TYPE_MESH_MSG 0x2A
#define DM_ADV_TYPE_MESH_BEACON 0x2B
#define DM_ADV_TYPE_BIG_INFO 0x2C
#define DM_ADV_TYPE_BCAST_CODE 0x2D
#define DM_ADV_TYPE_3D_INFO_DATA 0x3D
#define DM_ADV_TYPE_MANUFACTURER 0xFF
GAP Advertising Data Flag Advertising Type
Bit mask for Advertising Type flag in advertising data.
#define DM_FLAG_LE_LIMITED_DISC 0x01
#define DM_FLAG_LE_GENERAL_DISC 0x02
#define DM_FLAG_LE_BREDR_NOT_SUP 0x04
GAP Advertising Data Element Indexes
Advertising data element indexes.
#define DM_AD_LEN_IDX 0
#define DM_AD_TYPE_IDX 1
#define DM_AD_DATA_IDX 2
GAP Advertising URI
Advertising URI Scheme
#define DM_URI_SCHEME_HTTP 0x16
#define DM_URI_SCHEME_HTTPS 0x17
GAP Timeouts
Timeouts defined by the GAP specification; in units of milliseconds.
#define DM_GAP_LIM_ADV_TIMEOUT 180000
#define DM_GAP_GEN_DISC_SCAN_MIN 10240
#define DM_GAP_LIM_DISC_SCAN_MIN 10240
#define DM_GAP_CONN_PARAM_TIMEOUT 30000
#define DM_GAP_SCAN_FAST_PERIOD 30720
#define DM_GAP_ADV_FAST_PERIOD 30000
GAP 1M PHY Timing
Advertising, scanning, and connection parameters defined in the GAP specification for the LE 1M PHY. In units of 625 microseconds.
#define DM_GAP_SCAN_FAST_INT_MIN 48
#define DM_GAP_SCAN_FAST_INT_MAX 96
#define DM_GAP_SCAN_FAST_WINDOW 48
#define DM_GAP_SCAN_SLOW_INT_1 2048
#define DM_GAP_SCAN_SLOW_WINDOW_1 18
#define DM_GAP_SCAN_SLOW_INT_2 4096
#define DM_GAP_SCAN_SLOW_WINDOW_2 36
#define DM_GAP_ADV_FAST_INT_MIN_1 48
#define DM_GAP_ADV_FAST_INT_MAX_1 96
#define DM_GAP_ADV_FAST_INT_MIN_2 160
#define DM_GAP_ADV_FAST_INT_MAX_2 240
#define DM_GAP_ADV_SLOW_INT_MIN 1600
#define DM_GAP_ADV_SLOW_INT_MAX 1920
GAP Coded PHY Timing
Advertising, scanning, and connection parameters defined in the GAP specification for the LE Coded PHY. In units of 625 microseconds.
#define DM_GAP_SCAN_CODED_FAST_INT_MIN 144
#define DM_GAP_SCAN_CODED_FAST_INT_MAX 288
#define DM_GAP_SCAN_CODED_FAST_WINDOW 144
#define DM_GAP_SCAN_CODED_SLOW_INT_1 6144
#define DM_GAP_SCAN_CODED_SLOW_WINDOW_1 54
#define DM_GAP_SCAN_CODED_SLOW_INT_2 12288
#define DM_GAP_SCAN_CODED_SLOW_WINDOW_2 108
#define DM_GAP_ADV_CODED_FAST_INT_MIN_1 144
#define DM_GAP_ADV_CODED_FAST_INT_MAX_1 288
#define DM_GAP_ADV_CODED_FAST_INT_MIN_2 480
#define DM_GAP_ADV_CODED_FAST_INT_MAX_2 720
#define DM_GAP_ADV_CODED_SLOW_INT_MIN 4800
#define DM_GAP_ADV_CODED_SLOW_INT_MAX 5760
GAP Connection Slave Latency
#define DM_GAP_CONN_EST_LATENCY 0
GAP Connection Interval
GAP connection interval in 1.25ms units.
#define DM_GAP_INITIAL_CONN_INT_MIN 24
#define DM_GAP_INITIAL_CONN_INT_MAX 40
GAP Connection Event Lengths
GAP connection establishment minimum and maximum connection event lengths.
#define DM_GAP_CONN_EST_MIN_CE_LEN 0
#define DM_GAP_CONN_EST_MAX_CE_LEN 0
GAP Peripheral Privacy Characteristic Values
#define DM_GAP_PRIV_DISABLED 0
#define DM_GAP_PRIV_ENABLED 1
GAP Connection Supervision Timeout
Connection supervision timeout, in 10ms units
#define DM_DEFAULT_EST_SUP_TIMEOUT 2000
GAP Security Pairing Authentication Requirements
Pairing authentication/security properties bit mask.
#define DM_AUTH_BOND_FLAG SMP_AUTH_BOND_FLAG
#define DM_AUTH_MITM_FLAG SMP_AUTH_MITM_FLAG
#define DM_AUTH_SC_FLAG SMP_AUTH_SC_FLAG
#define DM_AUTH_KP_FLAG SMP_AUTH_KP_FLAG
GAP Key Distribution Flags
Key distribution bit mask
#define DM_KEY_DIST_LTK SMP_KEY_DIST_ENC
#define DM_KEY_DIST_IRK SMP_KEY_DIST_ID
#define DM_KEY_DIST_CSRK SMP_KEY_DIST_SIGN
DM Security Key Indication Types
Type of key used in DM_SEC_KEY_IND.
#define DM_KEY_LOCAL_LTK 0x01
#define DM_KEY_PEER_LTK 0x02
#define DM_KEY_IRK 0x04
#define DM_KEY_CSRK 0x08
GAP Security Level
GAP Mode 1 Security Levels
#define DM_SEC_LEVEL_NONE 0
#define DM_SEC_LEVEL_ENC 1
#define DM_SEC_LEVEL_ENC_AUTH 2
#define DM_SEC_LEVEL_ENC_LESC 3
GAP Broadcast Security Level
GAP Mode 3 Security Levels
#define DM_SEC_LEVEL_BCAST_NONE 0
#define DM_SEC_LEVEL_BCAST_UNAUTH 1
#define DM_SEC_LEVEL_BCAST_AUTH 2
GAP Random Address Types
Random address type masks.
#define DM_RAND_ADDR_STATIC 0xC0
#define DM_RAND_ADDR_RESOLV 0x40
#define DM_RAND_ADDR_NONRESOLV 0x00
GAP Random Address Macros
Macros for identifying address type.
#define DM_RAND_ADDR_GET(addr) ((addr)[5] & 0xC0)
#define DM_RAND_ADDR_SET(addr, type) {(addr)[5] = ((addr)[5] & 0x3F) | (type);}
#define DM_RAND_ADDR_SA(addr, type)
#define DM_RAND_ADDR_RPA(addr, type)
GAP Privacy Mode
Privacy Mode of this device in regards to a peer device.
#define DM_PRIV_MODE_NETWORK 0x00
#define DM_PRIV_MODE_DEVICE 0x01
DM Internal State
Connection busy or idle state
#define DM_CONN_IDLE 0
#define DM_CONN_BUSY 1
DM Internal State Flags
Connection busy/idle state bitmask.
#define DM_IDLE_SMP_PAIR 0x0001
#define DM_IDLE_DM_ENC 0x0002
#define DM_IDLE_ATTS_DISC 0x0004
#define DM_IDLE_APP_DISC 0x0008
#define DM_IDLE_USER_1 0x0010
#define DM_IDLE_USER_2 0x0020
#define DM_IDLE_USER_3 0x0040
#define DM_IDLE_USER_4 0x0080
GAP Filter Policy Modes
Filter policy modes.
#define DM_FILT_POLICY_MODE_ADV 0
#define DM_FILT_POLICY_MODE_SCAN 1
#define DM_FILT_POLICY_MODE_INIT 2
#define DM_FILT_POLICY_MODE_SYNC 3
DM Proprietary Error Codes
Internal error codes not sent in any PDU.
#define DM_ERR_SMP_RX_PDU_LEN_EXCEEDED 0x01
#define DM_ERR_ATT_RX_PDU_LEN_EXCEEDED 0x02
#define DM_ERR_L2C_RX_PDU_LEN_EXCEEDED 0x03
DM Conn CTE states
Internal states of the DM conn CTE.
enum
DM Legacy Advertising Handle
Default handle for legacy advertising when using legacy HCI interface. In this case only one advertising set is allowed so all activity uses the same handle.
#define DM_ADV_HANDLE_DEFAULT 0
DM Callback Events
Events handled by the DM state machine.
enum
#define DM_CBACK_START 0x20
#define DM_CBACK_END DM_VENDOR_SPEC_IND
DM App Callback Registration
void DmRegister (dmCback_t cback)
DM Advertising Functions
Functions used to control Legacy and Extended Advertising.
uint8_t * DmFindAdType (uint8_t adType, uint16_t dataLen, uint8_t *pData)
void DmAdvInit (void)
void DmExtAdvInit (void)
bool_t DmAdvModeLeg (void)
bool_t DmAdvModeExt (void)
void DmAdvConfig (uint8_t advHandle, uint8_t advType, uint8_t peerAddrType, uint8_t *pPeerAddr)
void DmAdvSetData (uint8_t advHandle, uint8_t op, uint8_t location, uint8_t len, uint8_t *pData)
void DmAdvStart (uint8_t numSets, uint8_t *pAdvHandles, uint16_t *pDuration, uint8_t *pMaxEaEvents)
void DmAdvStop (uint8_t numSets, uint8_t *pAdvHandles)
void DmAdvRemoveAdvSet (uint8_t advHandle)
void DmAdvClearAdvSets (void)
void DmAdvSetRandAddr (uint8_t advHandle, const uint8_t *pAddr)
void DmAdvSetInterval (uint8_t advHandle, uint16_t intervalMin, uint16_t intervalMax)
void DmAdvSetChannelMap (uint8_t advHandle, uint8_t channelMap)
void DmAdvSetAddrType (uint8_t addrType)
bool_t DmAdvSetAdValue (uint8_t adType, uint8_t len, uint8_t *pValue, uint16_t *pAdvDataLen, uint8_t *pAdvData, uint16_t advDataBufLen)
bool_t DmAdvSetName (uint8_t len, uint8_t *pValue, uint16_t *pAdvDataLen, uint8_t *pAdvData, uint16_t advDataBufLen)
void DmDevPrivInit (void)
void DmDevPrivStart (uint16_t changeInterval)
void DmDevPrivStop (void)
void DmAdvUseLegacyPdu (uint8_t advHandle, bool_t useLegacyPdu)
void DmAdvOmitAdvAddr (uint8_t advHandle, bool_t omitAdvAddr)
void DmAdvIncTxPwr (uint8_t advHandle, bool_t incTxPwr, int8_t advTxPwr)
void DmAdvSetPhyParam (uint8_t advHandle, uint8_t priAdvPhy, uint8_t secAdvMaxSkip, uint8_t secAdvPhy)
void DmAdvScanReqNotifEnable (uint8_t advHandle, bool_t scanReqNotifEna)
void DmAdvSetFragPref (uint8_t advHandle, uint8_t fragPref)
void DmAdvSetSid (uint8_t advHandle, uint8_t advSid)
void DmPerAdvConfig (uint8_t advHandle)
void DmPerAdvSetData (uint8_t advHandle, uint8_t op, uint8_t len, uint8_t *pData)
void DmPerAdvStart (uint8_t advHandle)
void DmPerAdvStop (uint8_t advHandle)
void DmPerAdvSetInterval (uint8_t advHandle, uint16_t intervalMin, uint16_t intervalMax)
void DmPerAdvIncTxPwr (uint8_t advHandle, bool_t incTxPwr)
bool_t DmPerAdvEnabled (uint8_t advHandle)
uint16_t DmExtMaxAdvDataLen (uint8_t advType, bool_t useLegacyPdu)
DM Privacy Functions
Functions for controlling Privacy.
void DmPrivInit (void)
void DmPrivResolveAddr (uint8_t *pAddr, uint8_t *pIrk, uint16_t param)
void DmPrivAddDevToResList (uint8_t addrType, const uint8_t *pIdentityAddr, uint8_t *pPeerIrk, uint8_t *pLocalIrk, bool_t enableLlPriv, uint16_t param)
void DmPrivRemDevFromResList (uint8_t addrType, const uint8_t *pIdentityAddr, uint16_t param)
void DmPrivClearResList (void)
void DmPrivReadPeerResolvableAddr (uint8_t addrType, const uint8_t *pIdentityAddr)
void DmPrivReadLocalResolvableAddr (uint8_t addrType, const uint8_t *pIdentityAddr)
void DmPrivSetAddrResEnable (bool_t enable)
void DmPrivSetResolvablePrivateAddrTimeout (uint16_t rpaTimeout)
void DmPrivSetPrivacyMode (uint8_t addrType, const uint8_t *pIdentityAddr, uint8_t mode)
void DmPrivGenerateAddr (uint8_t *pIrk, uint16_t param)
bool_t DmLlPrivEnabled (void)
DM Scanner Functions
Functions for controlling Legacy and Extended Scanner behavior.
void DmScanInit (void)
void DmExtScanInit (void)
void DmPastInit (void)
void DmConnCteInit (void)
bool_t DmScanModeLeg (void)
bool_t DmScanModeExt (void)
void DmScanStart (uint8_t scanPhys, uint8_t mode, const uint8_t *pScanType, bool_t filterDup, uint16_t duration, uint16_t period)
void DmScanStop (void)
void DmScanSetInterval (uint8_t scanPhys, uint16_t *pScanInterval, uint16_t *pScanWindow)
void DmScanSetAddrType (uint8_t addrType)
dmSyncId_t DmSyncStart (uint8_t advSid, uint8_t advAddrType, const uint8_t *pAdvAddr, uint16_t skip, uint16_t syncTimeout)
void DmSyncStop (dmSyncId_t syncId)
void DmSyncSetEncrypt (uint16_t syncHandle, bool_t encrypt)
bool_t DmSyncEncrypted (uint16_t syncHandle)
bool_t DmSyncEnabled (uint16_t syncHandle)
void DmSyncInitialRptEnable (bool_t enable)
void DmBigSyncStart (uint8_t bigHandle, uint16_t syncHandle, uint8_t mse, uint16_t bigSyncTimeout, uint8_t numBis, uint8_t *pBis)
void DmBigSyncStop (uint8_t bigHandle)
bool_t DmBisSyncInUse (uint16_t handle)
void DmBigSyncSetBcastCode (uint8_t bigHandle, bool_t encrypt, bool_t authen, uint8_t *pBcastCode)
void DmBigSyncSetSecLevel (uint8_t bigHandle, uint8_t secLevel)
uint8_t DmBigSyncGetSecLevel (uint16_t handle)
void DmBisMasterInit (void)
void DmAddDeviceToPerAdvList (uint8_t advAddrType, uint8_t *pAdvAddr, uint8_t advSid)
void DmRemoveDeviceFromPerAdvList (uint8_t advAddrType, uint8_t *pAdvAddr, uint8_t advSid)
void DmClearPerAdvList (void)
void DmPastRptRcvEnable (dmSyncId_t syncId, bool_t enable)
void DmPastSyncTrsf (dmConnId_t connId, uint16_t serviceData, dmSyncId_t syncId)
void DmPastSetInfoTrsf (dmConnId_t connId, uint16_t serviceData, uint8_t advHandle)
void DmPastConfig (dmConnId_t connId, uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
void DmPastDefaultConfig (uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
void DmConnCteRxSampleStart (dmConnId_t connId, uint8_t slotDurations, uint8_t switchPatternLen, uint8_t *pAntennaIDs)
void DmConnCteRxSampleStop (dmConnId_t connId)
void DmConnCteTxConfig (dmConnId_t connId, uint8_t cteTypeBits, uint8_t switchPatternLen, uint8_t *pAntennaIDs)
void DmConnCteReqStart (dmConnId_t connId, uint16_t cteReqInt, uint8_t reqCteLen, uint8_t reqCteType)
void DmConnCteReqStop (dmConnId_t connId)
void DmConnCteRspStart (dmConnId_t connId)
void DmConnCteRspStop (dmConnId_t connId)
uint8_t DmConnCteGetReqState (dmConnId_t connId)
uint8_t DmConnCteGetRspState (dmConnId_t connId)
void DmReadAntennaInfo (void)
DM Connection Functions
Functions for forming connections and managing connection behavior and parameter updates.
void DmConnInit (void)
void DmConnMasterInit (void)
void DmExtConnMasterInit (void)
void DmConnSlaveInit (void)
void DmExtConnSlaveInit (void)
void DmConnRegister (uint8_t clientId, dmCback_t cback)
dmConnId_t DmConnOpen (uint8_t clientId, uint8_t initPhys, uint8_t addrType, uint8_t *pAddr)
void DmConnClose (uint8_t clientId, dmConnId_t connId, uint8_t reason)
dmConnId_t DmConnAccept (uint8_t clientId, uint8_t advHandle, uint8_t advType, uint16_t duration, uint8_t maxEaEvents, uint8_t addrType, uint8_t *pAddr)
void DmConnUpdate (dmConnId_t connId, hciConnSpec_t *pConnSpec)
void DmConnSetScanInterval (uint16_t scanInterval, uint16_t scanWindow)
void DmExtConnSetScanInterval (uint8_t initPhys, uint16_t *pScanInterval, uint16_t *pScanWindow)
void DmConnSetConnSpec (hciConnSpec_t *pConnSpec)
void DmExtConnSetConnSpec (uint8_t initPhys, hciConnSpec_t *pConnSpec)
void DmConnSetAddrType (uint8_t addrType)
void DmConnSetIdle (dmConnId_t connId, uint16_t idleMask, uint8_t idle)
uint16_t DmConnCheckIdle (dmConnId_t connId)
void DmConnReadRssi (dmConnId_t connId)
void DmRemoteConnParamReqReply (dmConnId_t connId, hciConnSpec_t *pConnSpec)
void DmRemoteConnParamReqNegReply (dmConnId_t connId, uint8_t reason)
void DmConnSetDataLen (dmConnId_t connId, uint16_t txOctets, uint16_t txTime)
uint8_t DmConnRole (dmConnId_t connId)
void DmWriteAuthPayloadTimeout (dmConnId_t connId, uint16_t timeout)
void DmConnRequestPeerSca (dmConnId_t connId)
DM CIS Functions
Functions for forming and managing Connected Isochronous Stream (CIS) streams.
void DmCisInit (void)
void DmCisMasterInit (void)
void DmCisSlaveInit (void)
void DmCisCigSetSduInterval (uint8_t cigId, uint32_t sduIntervalMToS, uint32_t sduIntervalSToM)
void DmCisCigSetSca (uint8_t cigId, uint8_t sca)
void DmCisCigSetPackingFraming (uint8_t cigId, uint8_t packing, uint32_t framing)
void DmCisCigSetTransLatInterval (uint8_t cigId, uint16_t transLatMToS, uint16_t transLatSToM)
void DmCisCigConfig (uint8_t cigId, dmConnId_t numCis, HciCisCisParams_t *pCisParam)
void DmCisCigRemove (uint8_t cigId)
void DmCisOpen (uint8_t numCis, uint16_t *pCisHandle, uint16_t *pAclHandle)
void DmCisAccept (uint16_t handle)
void DmCisReject (uint16_t handle, uint8_t reason)
void DmCisClose (uint16_t handle, uint8_t reason)
bool_t DmCisConnInUse (uint16_t handle)
DM BIS Functions
Functions for forming and managing Broadcast Isochronous Stream (BIS) streams and synchronization.
void DmBisSlaveInit (void)
void DmBigStart (uint8_t bigHandle, uint8_t advHandle, uint8_t numBis, uint32_t sduInterUsec, uint16_t maxSdu, uint16_t mtlMs, uint8_t rtn)
void DmBigStop (uint8_t bigHandle, uint8_t reason)
bool_t DmBisInUse (uint16_t handle)
void DmBigSetPhy (uint8_t bigHandle, uint8_t phyBits)
void DmBigSetPackingFraming (uint8_t bigHandle, uint8_t packing, uint32_t framing)
void DmBigSetBcastCode (uint8_t bigHandle, bool_t encrypt, bool_t authen, uint8_t *pBcastCode)
void DmBigSetSecLevel (uint8_t bigHandle, uint8_t secLevel)
uint8_t DmBigGetSecLevel (uint16_t handle)
DM Isochronous (ISO) Functions
Functions for setting up and managing isochronous data path between the Host and the Controller.
void DmIsoInit (void)
void DmIsoDataPathSetup (HciIsoSetupDataPath_t *pDataPathParam)
void DmIsoDataPathRemove (uint16_t handle, uint8_t directionBits)
void DmDataPathConfig (HciConfigDataPath_t *pDataPathParam)
void DmReadLocalSupCodecs (void)
void DmReadLocalSupCodecCap (HciReadLocalSupCodecCaps_t *pCodecParam)
void DmReadLocalSupCtrDly (HciReadLocalSupControllerDly_t *pDelayParam)
DM PHY Control Functions
Functions for setting PHY preferences.
void DmSetDefaultPhy (uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys)
void DmReadPhy (dmConnId_t connId)
void DmSetPhy (dmConnId_t connId, uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys, uint16_t phyOptions)
void DmPhyInit (void)
DM Device Functions
Device control functions
void DmDevReset (void)
void DmDevSetRandAddr (uint8_t *pAddr)
void DmDevWhiteListAdd (uint8_t addrType, uint8_t *pAddr)
void DmDevWhiteListRemove (uint8_t addrType, uint8_t *pAddr)
void DmDevWhiteListClear (void)
bool_t DmDevSetFilterPolicy (uint8_t mode, uint8_t policy)
bool_t DmDevSetExtFilterPolicy (uint8_t advHandle, uint8_t mode, uint8_t policy)
void DmDevVsInit (uint8_t param)
DM Security Functions
Functions for accessing and controlling security configuration of device.
void DmSecInit (void)
void DmSecLescInit (void)
void DmSecPairReq (dmConnId_t connId, uint8_t oob, uint8_t auth, uint8_t iKeyDist, uint8_t rKeyDist)
void DmSecPairRsp (dmConnId_t connId, uint8_t oob, uint8_t auth, uint8_t iKeyDist, uint8_t rKeyDist)
void DmSecCancelReq (dmConnId_t connId, uint8_t reason)
void DmSecAuthRsp (dmConnId_t connId, uint8_t authDataLen, uint8_t *pAuthData)
void DmSecSlaveReq (dmConnId_t connId, uint8_t auth)
void DmSecEncryptReq (dmConnId_t connId, uint8_t secLevel, dmSecLtk_t *pLtk)
void DmSecLtkRsp (dmConnId_t connId, bool_t keyFound, uint8_t secLevel, uint8_t *pKey)
void DmSecSetLocalCsrk (uint8_t *pCsrk)
void DmSecSetLocalIrk (uint8_t *pIrk)
void DmSecGenerateEccKeyReq (void)
void DmSecSetEccKey (secEccKey_t *pKey)
secEccKey_t * DmSecGetEccKey (void)
void DmSecSetDebugEccKey (void)
void DmSecSetOob (dmConnId_t connId, dmSecLescOobCfg_t *pConfig)
void DmSecCalcOobReq (uint8_t *pRand, uint8_t *pPubKeyX)
void DmSecCompareRsp (dmConnId_t connId, bool_t valid)
uint32_t DmSecGetCompareValue (uint8_t *pConfirm)
DM Internal Functions
Functions called internally by the stack.
uint8_t DmLlAddrType (uint8_t addrType)
uint8_t DmHostAddrType (uint8_t addrType)
uint16_t DmSizeOfEvt (dmEvt_t *pDmEvt)
void DmL2cConnUpdateCnf (uint16_t handle, uint16_t reason)
void DmL2cCmdRejInd (uint16_t handle, uint16_t result)
void DmL2cConnUpdateInd (uint8_t identifier, uint16_t handle, hciConnSpec_t *pConnSpec)
dmConnId_t DmConnIdByHandle (uint16_t handle)
bool_t DmConnInUse (dmConnId_t connId)
uint8_t DmConnPeerAddrType (dmConnId_t connId)
uint8_t * DmConnPeerAddr (dmConnId_t connId)
uint8_t DmConnLocalAddrType (dmConnId_t connId)
uint8_t * DmConnLocalAddr (dmConnId_t connId)
uint8_t * DmConnPeerRpa (dmConnId_t connId)
uint8_t * DmConnLocalRpa (dmConnId_t connId)
uint8_t DmConnSecLevel (dmConnId_t connId)
void DmSmpEncryptReq (dmConnId_t connId, uint8_t secLevel, uint8_t *pKey)
void DmSmpCbackExec (dmEvt_t *pDmEvt)
uint8_t * DmSecGetLocalCsrk (void)
uint8_t * DmSecGetLocalIrk (void)
void DmReadRemoteFeatures (dmConnId_t connId)
void DmReadRemoteVerInfo (dmConnId_t connId)
Detailed Description
Data Structure Documentation
dmCfg_t
struct dmCfg_t
Configuration structure.
Data Fields
uint8_t dummy
dmSecLtk_t
struct dmSecLtk_t
LTK data type.
Data Fields
uint8_t key [SMP_KEY_LEN]
uint8_t rand [SMP_RAND8_LEN]
uint16_t ediv
dmSecIrk_t
struct dmSecIrk_t
IRK data type.
Data Fields
uint8_t key [SMP_KEY_LEN]
bdAddr_t bdAddr
uint8_t addrType
dmSecCsrk_t
struct dmSecCsrk_t
CSRK data type.
Data Fields
uint8_t key [SMP_KEY_LEN]
dmSecKey_t
union dmSecKey_t
Union of key types.
Data Fields
dmSecLtk_t ltk
dmSecIrk_t irk
dmSecCsrk_t csrk
dmSecPairCmplIndEvt_t
struct dmSecPairCmplIndEvt_t
Data type for DM_SEC_PAIR_CMPL_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t auth
dmSecEncryptIndEvt_t
struct dmSecEncryptIndEvt_t
Data type for DM_SEC_ENCRYPT_IND.
Data Fields
wsfMsgHdr_t hdr
bool_t usingLtk
dmSecAuthReqIndEvt_t
struct dmSecAuthReqIndEvt_t
Data type for DM_SEC_AUTH_REQ_IND.
Data Fields
wsfMsgHdr_t hdr
bool_t oob
bool_t display
dmSecPairIndEvt_t
struct dmSecPairIndEvt_t
Data type for DM_SEC_PAIR_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t auth
bool_t oob
uint8_t iKeyDist
uint8_t rKeyDist
dmSecSlaveIndEvt_t
struct dmSecSlaveIndEvt_t
Data type for DM_SEC_SLAVE_REQ_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t auth
dmSecKeyIndEvt_t
struct dmSecKeyIndEvt_t
Data type for DM_SEC_KEY_IND.
Data Fields
wsfMsgHdr_t hdr
dmSecKey_t keyData
uint8_t type
uint8_t secLevel
uint8_t encKeyLen
dmSecCnfIndEvt_t
struct dmSecCnfIndEvt_t
Data type for DM_SEC_COMPARE_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t confirm [SMP_CONFIRM_LEN]
dmSecKeypressIndEvt_t
struct dmSecKeypressIndEvt_t
Data type for DM_SEC_KEYPRESS_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t notificationType
dmPrivGenAddrIndEvt_t
struct dmPrivGenAddrIndEvt_t
Data type for DM_PRIV_GENERATE_ADDR_IND.
Data Fields
wsfMsgHdr_t hdr
bdAddr_t addr
dmSecOobCalcIndEvt_t
struct dmSecOobCalcIndEvt_t
Data type for DM_SEC_CALC_OOB_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t confirm [SMP_CONFIRM_LEN]
uint8_t random [SMP_RAND_LEN]
dmAdvNewAddrIndEvt_t
struct dmAdvNewAddrIndEvt_t
Data type for DM_ADV_NEW_ADDR_IND.
Data Fields
wsfMsgHdr_t hdr
bdAddr_t addr
bool_t firstTime
dmAdvSetStartEvt_t
struct dmAdvSetStartEvt_t
Data structure for DM_ADV_SET_START_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t numSets
uint8_t advHandle [DM_NUM_ADV_SETS]
dmPerAdvSetStartEvt_t
struct dmPerAdvSetStartEvt_t
Data structure for DM_PER_ADV_SET_START_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t advHandle
dmPerAdvSetStopEvt_t
struct dmPerAdvSetStopEvt_t
Data structure for DM_PER_ADV_SET_STOP_IND.
Data Fields
wsfMsgHdr_t hdr
uint8_t advHandle
dmL2cCmdRejEvt_t
struct dmL2cCmdRejEvt_t
Data structure for DM_L2C_CMD_REJ_IND.
Data Fields
wsfMsgHdr_t hdr
uint16_t reason
uint16_t handle
dmEvt_t
union dmEvt_t
Union of DM callback event data types.
Note
the following events use only the common wsfMsgHdr_t header: DM_RESET_CMPL_IND, DM_ADV_START_IND, DM_ADV_STOP_IND, DM_SCAN_START_IND, DM_SCAN_STOP_IND, DM_SEC_PAIR_FAIL_IND, DM_SEC_ENCRYPT_FAIL_IND, DM_PRIV_RESOLVED_ADDR_IND, DM_EXT_SCAN_START_IND, DM_EXT_SCAN_STOP_IND, DM_ERROR_IND
Data Fields
wsfMsgHdr_t hdr
dmAdvNewAddrIndEvt_t advNewAddr
hciLeAdvReportEvt_t scanReport
hciLeConnCmplEvt_t connOpen
hciDisconnectCmplEvt_t connClose
hciLeConnUpdateCmplEvt_t connUpdate
dmSecPairCmplIndEvt_t pairCmpl
dmSecEncryptIndEvt_t encryptInd
dmSecAuthReqIndEvt_t authReq
dmSecKeyIndEvt_t keyInd
hciLeLtkReqEvt_t ltkReqInd
dmSecPairIndEvt_t pairInd
dmSecSlaveIndEvt_t slaveInd
dmSecOobCalcIndEvt_t oobCalcInd
secEccMsg_t eccMsg
dmSecCnfIndEvt_t cnfInd
dmSecKeypressIndEvt_t keypressInd
dmPrivGenAddrIndEvt_t genAddr
hciReadRssiCmdCmplEvt_t readRssi
hciLeAddDevToResListCmdCmplEvt_t addDevToResList
hciLeRemDevFromResListCmdCmplEvt_t remDevFromResList
hciLeClearResListCmdCmplEvt_t clearResList
hciLeReadPeerResAddrCmdCmplEvt_t readPeerResAddr
hciLeReadLocalResAddrCmdCmplEvt_t readLocalResAddr
hciLeSetAddrResEnableCmdCmplEvt_t setAddrResEnable
hciLeRemConnParamReqEvt_t remConnParamReq
hciLeDataLenChangeEvt_t dataLenChange
hciWriteAuthPayloadToCmdCmplEvt_t writeAuthTo
hciAuthPayloadToExpiredEvt_t authToExpired
hciLeReadPhyCmdCmplEvt_t readPhy
hciLeSetDefPhyCmdCmplEvt_t setDefPhy
hciLePhyUpdateEvt_t phyUpdate
dmAdvSetStartEvt_t advSetStart
hciLeAdvSetTermEvt_t advSetStop
hciLeScanReqRcvdEvt_t scanReqRcvd
hciLeExtAdvReportEvt_t extScanReport
dmPerAdvSetStartEvt_t perAdvSetStart
dmPerAdvSetStopEvt_t perAdvSetStop
hciLePerAdvSyncEstEvt_t perAdvSyncEst
hciLePerAdvSyncEstEvt_t perAdvSyncEstFail
hciLePerAdvSyncLostEvt_t perAdvSyncLost
HciLePerAdvSyncTrsfRcvdEvt_t perAdvSyncTrsfEst
HciLePerAdvSyncTrsfRcvdEvt_t perAdvSyncTrsEstFail
hciLePerAdvSyncTrsfCmdCmplEvt_t perAdvSyncTrsf
hciLePerAdvSetInfoTrsfCmdCmplEvt_t perAdvSetInfoTrsf
hciLePerAdvReportEvt_t perAdvReport
hciLeReadRemoteFeatCmplEvt_t readRemoteFeat
hciReadRemoteVerInfoCmplEvt_t readRemVerInfo
hciLeConnIQReportEvt_t connIQReport
hciLeCteReqFailedEvt_t cteReqFail
hciLeSetConnCteRxParamsCmdCmplEvt_t connCteRxSampleStart
hciLeSetConnCteRxParamsCmdCmplEvt_t connCteRxSampleStop
hciLeSetConnCteTxParamsCmdCmplEvt_t connCteTxCfg
hciLeConnCteReqEnableCmdCmplEvt_t connCteReqStart
hciLeConnCteReqEnableCmdCmplEvt_t connCteReqStop
hciLeConnCteRspEnableCmdCmplEvt_t connCteRspStart
hciLeConnCteRspEnableCmdCmplEvt_t connCteRspStop
hciLeReadAntennaInfoCmdCmplEvt_t readAntennaInfo
hciLeSetCigParamsCmdCmplEvt_t cisCigConfig
hciLeRemoveCigCmdCmplEvt_t cisCigRemove
HciLeCisReqEvt_t cisReq
HciLeCisEstEvt_t cisOpen
hciDisconnectCmplEvt_t cisClose
HciLeReqPeerScaCmplEvt_t_t reqPeerSca
hciLeSetupIsoDataPathCmdCmplEvt_t isoDataPathSetup
hciLeRemoveIsoDataPathCmdCmplEvt_t isoDataPathRemove
hciConfigDataPathCmdCmplEvt_t dataPathConfig
hciReadLocalSupCodecsCmdCmplEvt_t readLocalSupCodecs
hciReadLocalSupCodecCapCmdCmplEvt_t readLocalSupCodecCap
hciReadLocalSupCtrDlyCmdCmplEvt_t readLocalSupCtrDly
HciLeCreateBigCmplEvt_t bigStart
HciLeTerminateBigCmplEvt_t bigStop
HciLeBigSyncEstEvt_t bigSyncEst
HciLeBigSyncEstEvt_t bigSyncEstFail
HciLeBigSyncLostEvt_t bigSyncLost
HciLeBigTermSyncCmplEvt_t bigSyncStop
HciLeBigInfoAdvRptEvt_t bigInfoAdvRpt
dmL2cCmdRejEvt_t l2cCmdRej
hciHwErrorEvt_t hwError
hciVendorSpecEvt_t vendorSpec
dmSecLescOobCfg_t
struct dmSecLescOobCfg_t
Data type for DmSecSetOob().
Data Fields
uint8_t localRandom [SMP_RAND_LEN]
uint8_t localConfirm [SMP_CONFIRM_LEN]
uint8_t peerRandom [SMP_RAND_LEN]
uint8_t peerConfirm [SMP_CONFIRM_LEN]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DM_CONN_CTE_STATE_IDLE
Idle
DM_CONN_CTE_STATE_INITIATING
Initiating CTE request
DM_CONN_CTE_STATE_RESPONDING
Responding to CTE request
DM_CONN_CTE_STATE_SAMPLING
Sampling received CTE
DM_CONN_CTE_STATE_STARTING
Starting CTE request, CTE response or sampling received CTE
DM_CONN_CTE_STATE_STOPPING
Stopping CTE request, CTE response or sampling received CTE
anonymous enum
anonymous enum
DM callback events.
Enumerator
DM_RESET_CMPL_IND
Reset complete.
DM_ADV_START_IND
Advertising started.
DM_ADV_STOP_IND
Advertising stopped.
DM_ADV_NEW_ADDR_IND
New resolvable address has been generated.
DM_SCAN_START_IND
Scanning started.
DM_SCAN_STOP_IND
Scanning stopped.
DM_SCAN_REPORT_IND
Scan data received from peer device.
DM_CONN_OPEN_IND
Connection opened.
DM_CONN_CLOSE_IND
Connection closed.
DM_CONN_UPDATE_IND
Connection update complete.
DM_SEC_PAIR_CMPL_IND
Pairing completed successfully.
DM_SEC_PAIR_FAIL_IND
Pairing failed or other security failure.
DM_SEC_ENCRYPT_IND
Connection encrypted.
DM_SEC_ENCRYPT_FAIL_IND
Encryption failed.
DM_SEC_AUTH_REQ_IND
PIN or OOB data requested for pairing.
DM_SEC_KEY_IND
Security key indication.
DM_SEC_LTK_REQ_IND
LTK requested for encyption.
DM_SEC_PAIR_IND
Incoming pairing request from master.
DM_SEC_SLAVE_REQ_IND
Incoming security request from slave.
DM_SEC_CALC_OOB_IND
Result of OOB Confirm Calculation Generation.
DM_SEC_ECC_KEY_IND
Result of ECC Key Generation.
DM_SEC_COMPARE_IND
Result of Just Works/Numeric Comparison Compare Value Calculation.
DM_SEC_KEYPRESS_IND
Keypress indication from peer in passkey security.
DM_PRIV_RESOLVED_ADDR_IND
Private address resolved.
DM_PRIV_GENERATE_ADDR_IND
Private resolvable address generated.
DM_CONN_READ_RSSI_IND
Connection RSSI read.
DM_PRIV_ADD_DEV_TO_RES_LIST_IND
Device added to resolving list.
DM_PRIV_REM_DEV_FROM_RES_LIST_IND
Device removed from resolving list.
DM_PRIV_CLEAR_RES_LIST_IND
Resolving list cleared.
DM_PRIV_READ_PEER_RES_ADDR_IND
Peer resolving address read.
DM_PRIV_READ_LOCAL_RES_ADDR_IND
Local resolving address read.
DM_PRIV_SET_ADDR_RES_ENABLE_IND
Address resolving enable set.
DM_REM_CONN_PARAM_REQ_IND
Remote connection parameter requested.
DM_CONN_DATA_LEN_CHANGE_IND
Data length changed.
DM_CONN_WRITE_AUTH_TO_IND
Write authenticated payload complete.
DM_CONN_AUTH_TO_EXPIRED_IND
Authenticated payload timeout expired.
DM_PHY_READ_IND
Read PHY.
DM_PHY_SET_DEF_IND
Set default PHY.
DM_PHY_UPDATE_IND
PHY update.
DM_ADV_SET_START_IND
Advertising set(s) started.
DM_ADV_SET_STOP_IND
Advertising set(s) stopped.
DM_SCAN_REQ_RCVD_IND
Scan request received.
DM_EXT_SCAN_START_IND
Extended scanning started.
DM_EXT_SCAN_STOP_IND
Extended scanning stopped.
DM_EXT_SCAN_REPORT_IND
Extended scan data received from peer device.
DM_PER_ADV_SET_START_IND
Periodic advertising set started.
DM_PER_ADV_SET_STOP_IND
Periodic advertising set stopped.
DM_PER_ADV_SYNC_EST_IND
Periodic advertising sync established.
DM_PER_ADV_SYNC_EST_FAIL_IND
Periodic advertising sync establishment failed.
DM_PER_ADV_SYNC_LOST_IND
Periodic advertising sync lost.
DM_PER_ADV_SYNC_TRSF_EST_IND
Periodic advertising sync transfer established.
DM_PER_ADV_SYNC_TRSF_EST_FAIL_IND
Periodic advertising sync transfer establishment failed.
DM_PER_ADV_SYNC_TRSF_IND
Periodic advertising sync info transferred.
DM_PER_ADV_SET_INFO_TRSF_IND
Periodic advertising set sync info transferred.
DM_PER_ADV_REPORT_IND
Periodic advertising data received from peer device.
DM_REMOTE_FEATURES_IND
Remote features from peer device.
DM_READ_REMOTE_VER_INFO_IND
Remote LL version information read.
DM_CONN_IQ_REPORT_IND
IQ samples from CTE of received packet from peer device.
DM_CTE_REQ_FAIL_IND
CTE request failed.
DM_CONN_CTE_RX_SAMPLE_START_IND
Sampling received CTE started.
DM_CONN_CTE_RX_SAMPLE_STOP_IND
Sampling received CTE stopped.
DM_CONN_CTE_TX_CFG_IND
Connection CTE transmit parameters configured.
DM_CONN_CTE_REQ_START_IND
Initiating connection CTE request started.
DM_CONN_CTE_REQ_STOP_IND
Initiating connection CTE request stopped.
DM_CONN_CTE_RSP_START_IND
Responding to connection CTE request started.
DM_CONN_CTE_RSP_STOP_IND
Responding to connection CTE request stopped.
DM_READ_ANTENNA_INFO_IND
Antenna information read.
DM_CIS_CIG_CONFIG_IND
CIS CIG configure complete.
DM_CIS_CIG_REMOVE_IND
CIS CIG remove complete.
DM_CIS_REQ_IND
CIS request.
DM_CIS_OPEN_IND
CIS connection opened.
DM_CIS_CLOSE_IND
CIS connection closed.
DM_REQ_PEER_SCA_IND
Request peer SCA complete.
DM_ISO_DATA_PATH_SETUP_IND
ISO data path setup complete.
DM_ISO_DATA_PATH_REMOVE_IND
ISO data path remove complete.
DM_DATA_PATH_CONFIG_IND
Data path configure complete.
DM_READ_LOCAL_SUP_CODECS_IND
Local supported codecs read.
DM_READ_LOCAL_SUP_CODEC_CAP_IND
Local supported codec capabilities read.
DM_READ_LOCAL_SUP_CTR_DLY_IND
Local supported controller delay read.
DM_BIG_START_IND
BIG started.
DM_BIG_STOP_IND
BIG stopped.
DM_BIG_SYNC_EST_IND
BIG sync established.
DM_BIG_SYNC_EST_FAIL_IND
BIG sync establishment failed.
DM_BIG_SYNC_LOST_IND
BIG sync lost.
DM_BIG_SYNC_STOP_IND
BIG sync stopped.
DM_BIG_INFO_ADV_REPORT_IND
BIG Info advertising data received from peer device.
DM_L2C_CMD_REJ_IND
L2CAP Command Reject.
DM_ERROR_IND
General error.
DM_HW_ERROR_IND
Hardware error.
DM_VENDOR_SPEC_IND
Vendor specific event.
Function Documentation
DmAddDeviceToPerAdvList()
void DmAddDeviceToPerAdvList (uint8_t advAddrType, uint8_t * pAdvAddr, uint8_t advSid)
Add device to periodic advertiser list.
Parameters
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
advSid Advertising SID.
Returns
None.
References HciLeAddDeviceToPerAdvListCmd().
DmAdvClearAdvSets()
void DmAdvClearAdvSets (void)
Clear advertising sets.
Returns
None.
References wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmAdvConfig()
void DmAdvConfig (uint8_t advHandle, uint8_t advType, uint8_t peerAddrType, uint8_t * pPeerAddr)
Set the advertising parameters using the given advertising type, and peer address.
Parameters
advHandle Advertising handle.
advType Advertising type.
peerAddrType Peer address type.
pPeerAddr Peer address.
Returns
None.
References BdaCpy(), DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmAdvIncTxPwr()
void DmAdvIncTxPwr (uint8_t advHandle, bool_t incTxPwr, int8_t advTxPwr)
Set whether or not to include TxPower in extended header of advertising PDU.
Parameters
advHandle Advertising handle.
incTxPwr Whether to include TxPower in extended header of advertising PDU (default value is FALSE).
advTxPwr Advertising tx power (127 = no preference).
Returns
None.
DmAdvInit()
void DmAdvInit (void)
Initialize DM legacy advertising.
Returns
None.
References HciVsInit(), WsfTaskLock(), and WsfTaskUnlock().
DmAdvModeExt()
bool_t DmAdvModeExt (void)
Whether DM advertising is in extended mode.
Returns
TRUE if DM advertising is in extended mode. FALSE, otherwise.
DmAdvModeLeg()
bool_t DmAdvModeLeg (void)
Whether DM advertising is in legacy mode.
Returns
TRUE if DM advertising is in legacy mode. FALSE, otherwise.
DmAdvOmitAdvAddr()
void DmAdvOmitAdvAddr (uint8_t advHandle, bool_t omitAdvAddr)
Set whether or not to omit advertiser's address from all PDUs (anonymous advertising).
Parameters
advHandle Advertising handle.
omitAdvAddr Whether to omit advertiser's address from all PDUs (default value is FALSE).
Returns
None.
DmAdvRemoveAdvSet()
void DmAdvRemoveAdvSet (uint8_t advHandle)
Remove an advertising set.
Parameters
advHandle Advertising handle.
Returns
None.
References DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmAdvScanReqNotifEnable()
void DmAdvScanReqNotifEnable (uint8_t advHandle, bool_t scanReqNotifEna)
Set scan request notification enable.
Parameters
advHandle Advertising handle.
scanReqNotifEna Scan request notification enable.
Returns
None.
DmAdvSetAddrType()
void DmAdvSetAddrType (uint8_t addrType)
Set the local address type used while advertising. This function can be used to configure advertising to use a random address.
Parameters
addrType Address type.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmAdvSetAdValue()
bool_t DmAdvSetAdValue (uint8_t adType, uint8_t len, uint8_t * pValue, uint16_t * pAdvDataLen, uint8_t * pAdvData, uint16_t advDataBufLen)
Set the value of an advertising data element in the given advertising or scan response data. If the element already exists in the data then it is replaced with the new value. If the element does not exist in the data it is appended to it, space permitting.
Parameters
adType Advertising data element type.
len Length of the value. Maximum length is 29 bytes.
pValue Pointer to the value.
pAdvDataLen Advertising or scan response data length. The new length is returned in this parameter.
pAdvData Pointer to advertising or scan response data.
advDataBufLen Length of the advertising or scan response data buffer maintained by Application.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
DmAdvSetChannelMap()
void DmAdvSetChannelMap (uint8_t advHandle, uint8_t channelMap)
Include or exclude certain channels from the advertising channel map.
Parameters
advHandle Advertising handle.
channelMap Advertising channel map.
Returns
None.
References DM_NUM_ADV_SETS, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmAdvSetData()
void DmAdvSetData (uint8_t advHandle, uint8_t op, uint8_t location, uint8_t len, uint8_t * pData)
Set the advertising or scan response data to the given data.
Parameters
advHandle Advertising handle.
op Data operation.
location Data location.
len Length of the data. Maximum length is 236 bytes.
pData Pointer to the data.
Returns
None.
References DM_DATA_LOC_ADV, DM_DATA_LOC_SCAN, DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmAdvSetFragPref()
void DmAdvSetFragPref (uint8_t advHandle, uint8_t fragPref)
Set fragment preference for advertising data.
Parameters
advHandle Advertising handle.
fragPref Fragment preference.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmAdvSetInterval()
void DmAdvSetInterval (uint8_t advHandle, uint16_t intervalMin, uint16_t intervalMax)
Set the minimum and maximum advertising intervals.
Parameters
advHandle Advertising handle.
intervalMin Minimum advertising interval.
intervalMax Maximum advertising interval.
Returns
None.
References DM_NUM_ADV_SETS, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmAdvSetName()
bool_t DmAdvSetName (uint8_t len, uint8_t * pValue, uint16_t * pAdvDataLen, uint8_t * pAdvData, uint16_t advDataBufLen)
Set the device name in the given advertising or scan response data. If the name can only fit in the data if it is shortened, the name is shortened and the AD type is changed to DM_ADV_TYPE_SHORT_NAME.
Parameters
len Length of the name. Maximum length is 29 bytes.
pValue Pointer to the name in UTF-8 format.
pAdvDataLen Advertising or scan response data length. The new length is returned in this parameter.
pAdvData Pointer to advertising or scan response data.
advDataBufLen Length of the advertising or scan response data buffer maintained by Application.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
Set the device name in the given advertising or scan response data. If the name can only fit in the data if it is shortened, the name is shortened and the AD type is changed to DM_ADV_TYPE_SHORT_NAME.
Parameters
len Length of the name. Maximum length is 29 bytes.
pValue Pointer to the name in UTF-8 format.
pAdvDataLen Advertising or scan response data length. The new length is returned in this parameter.
pAdvData Pointer to advertising or scan response data.
advDataBufLen Length of the advertising or scan response data buffer maintained by Application.
Returns
TRUE if the element was successfully added to the data, FALSE otherwise.
DmAdvSetPhyParam()
void DmAdvSetPhyParam (uint8_t advHandle, uint8_t priAdvPhy, uint8_t secAdvMaxSkip, uint8_t secAdvPhy)
Set extended advertising PHY parameters.
Parameters
advHandle Advertising handle.
priAdvPhy Primary advertising Phy.
secAdvMaxSkip Maximum advertising events Controller can skip before sending AUX_ADV_IND on secondary advertising channel (0 = AUX_ADV_IND will be sent prior to next advertising event).
secAdvPhy Secondary advertising Phy.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmAdvSetRandAddr()
void DmAdvSetRandAddr (uint8_t advHandle, const uint8_t * pAddr)
Set the random device address for a given advertising set.
Parameters
advHandle Advertising handle.
pAddr Random device address.
Returns
None.
References BdaCpy(), DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmAdvSetSid()
void DmAdvSetSid (uint8_t advHandle, uint8_t advSid)
Set advertising SID for the given advertising handle.
Parameters
advHandle Advertising handle.
advSid Advertsing SID.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmAdvStart()
void DmAdvStart (uint8_t numSets, uint8_t * pAdvHandles, uint16_t * pDuration, uint8_t * pMaxEaEvents)
Start advertising using the given advertising set and duration.
Parameters
numSets Number of advertising sets to enable.
pAdvHandles Advertising handles array.
pDuration Advertising duration (in milliseconds) array.
pMaxEaEvents Maximum number of extended advertising events array.
Returns
None.
References DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmAdvStop()
void DmAdvStop (uint8_t numSets, uint8_t * pAdvHandles)
Stop advertising for the given advertising set. If the number of sets is set to 0 then all advertising sets are disabled.
Parameters
numSets Number of advertising sets to disable.
pAdvHandles Advertising handles array.
Returns
None.
References DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmAdvUseLegacyPdu()
void DmAdvUseLegacyPdu (uint8_t advHandle, bool_t useLegacyPdu)
Set whether or not to use legacy advertising PDUs with extended advertising.
Parameters
advHandle Advertising handle.
useLegacyPdu Whether to use legacy advertising PDUs (default value is TRUE).
Returns
None.
DmBigGetSecLevel()
uint8_t DmBigGetSecLevel (uint16_t handle)
Get the security level of the LE Security Mode 3 for the given Broadcast Isochronous Group (BIG) connection handle.
Parameters
handle BIS connection handle.
Returns
Security level.
References DM_SEC_LEVEL_BCAST_NONE.
DmBigSetBcastCode()
void DmBigSetBcastCode (uint8_t bigHandle, bool_t encrypt, bool_t authen, uint8_t * pBcastCode)
Set the Broadcast Code for the given Broadcast Isochronous Group (BIG).
Parameters
bigHandle BIG handle.
encrypt FALSE (Unencrypted) or TRUE (Encrypted).
authen FALSE (Unauthenticated) or TRUE (Authenticated).
pBcastCode Broadcast code.
Returns
None.
DmBigSetPackingFraming()
void DmBigSetPackingFraming (uint8_t bigHandle, uint8_t packing, uint32_t framing)
Set the packing scheme and framing format for the given Broadcast Isochronous Group (BIG).
Parameters
bigHandle BIG handle.
packing Packing scheme.
framing Indicates format of BIS Data PDUs.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmBigSetPhy()
void DmBigSetPhy (uint8_t bigHandle, uint8_t phyBits)
Set the PHYs used for transmission of PDUs of Broadcast Isochronous Streams (BISes) in Broadcast Isochronous Group (BIG).
Parameters
bigHandle BIG handle.
phyBits PHY bit field.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmBigSetSecLevel()
void DmBigSetSecLevel (uint8_t bigHandle, uint8_t secLevel)
Set the security level of the LE Security Mode 3 for the given Broadcast Isochronous Group (BIG).
Parameters
bigHandle BIG handle.
secLevel Security level.
Returns
None.
References DM_SEC_LEVEL_BCAST_AUTH, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmBigStart()
void DmBigStart (uint8_t bigHandle, uint8_t advHandle, uint8_t numBis, uint32_t sduInterval, uint16_t maxSdu, uint16_t mtlMs, uint8_t rtn)
Start a Broadcast Isochronous Group (BIG) with one or more Broadcast Isochronous Streams (BISes).
Parameters
bigHandle CIG identifier.
advHandle Used to identify the periodic advertising train.
numBis; Total number of BISes in the BIG.
sduInterUsec Interval, in microseconds, of BIG SDUs.
maxSdu Maximum size of SDU
mtlMs Maximum time, in milliseconds, for transmitting SDU.
rtn Retransmitted number.
Returns
None.
Parameters
bigHandle BIG identifier.
advHandle Used to identify the periodic advertising train.
numBis; Total number of BISes in the BIG.
sduInterval Interval, in microseconds, of BIG SDUs.
maxSdu Maximum size of SDU.
mtlMs Maximum time, in milliseconds, for transmitting SDU.
Returns
None.
References DM_BIS_MAX, DM_NUM_ADV_SETS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmBigStop()
void DmBigStop (uint8_t bigHandle, uint8_t reason)
Stop a Broadcast Isochronous Group (BIG) identified for the given handle.
Parameters
bigHandle BIG identifier.
reason Reason BIG is terminated.
Returns
None.
References WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmBigSyncGetSecLevel()
uint8_t DmBigSyncGetSecLevel (uint16_t handle)
Get the security level of the LE Security Mode 3 for the given Broadcast Isochronous Group (BIG) connection handle.
Parameters
handle BIS connection handle.
Returns
Security level.
References DM_SEC_LEVEL_BCAST_NONE.
DmBigSyncSetBcastCode()
void DmBigSyncSetBcastCode (uint8_t bigHandle, bool_t encrypt, bool_t authen, uint8_t * pBcastCode)
Set the Broadcast Code for the given Broadcast Isochronous Group (BIG).
Parameters
bigHandle BIG handle.
encrypt FALSE (Unencrypted) or TRUE (Encrypted).
authen FALSE (Unauthenticated) or TRUE (Authenticated).
pBcastCode Broadcast code.
Returns
None.
DmBigSyncSetSecLevel()
void DmBigSyncSetSecLevel (uint8_t bigHandle, uint8_t secLevel)
Set the security level of the LE Security Mode 3 for the given Broadcast Isochronous Group (BIG).
Parameters
bigHandle BIG handle.
secLevel Security level.
Returns
None.
References DM_SEC_LEVEL_BCAST_AUTH, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmBigSyncStart()
void DmBigSyncStart (uint8_t bigHandle, uint16_t syncHandle, uint8_t mse, uint16_t bigSyncTimeout, uint8_t numBis, uint8_t * pBis)
Synchronize to a Broadcast Isochronous Group (BIG) described in the periodic advertising train specified by the sync handle.
Parameters
bigHandle BIG handle.
syncHandle Periodic advertising train handle.
mse Maximum number of subevents.
bigSyncTimeout Synchronization timeout for the BIS, in the units of 10ms.
numBis Total number of BISes in the BIG.
pBis List of indices of BISes (in ascending order).
Returns
None.
References DM_BIS_MAX, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmBigSyncStop()
void DmBigSyncStop (uint8_t bigHandle)
Stop synchronizing or cancel the process of synchronizing to the Broadcast Isochronous Group (BIG) identified by the handle.
Note
The command also terminates the reception of BISes in the BIG specified in DmBigSyncStart, destroys the associated connection handles of the BISes in the BIG and removes the data paths for all BISes in the BIG.
Parameters
bigHandle BIG handle.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmBisInUse()
bool_t DmBisInUse (uint16_t handle)
For internal use only. Return TRUE if the BIS is in use.
Parameters
handle BIS connection handle.
Returns
TRUE if the BIS connection is in use, FALSE otherwise.
Parameters
handle BIS connection handle.
Returns
TRUE if the BIS is in use, FALSE otherwise.
DmBisMasterInit()
void DmBisMasterInit (void)
Initialize DM BIS manager for operation as master.
Returns
None.
References HCI_LE_SUP_FEAT_ISO_HOST_SUPPORT, HCI_LE_SUP_FEAT_ISO_SYNC_RECEIVER, HciSetLeSupFeat(), and WsfTaskLock().
DmBisSlaveInit()
void DmBisSlaveInit (void)
Initialize DM BIS manager for operation as slave.
Returns
None.
References HCI_LE_SUP_FEAT_ISO_BROADCASTER, HCI_LE_SUP_FEAT_ISO_HOST_SUPPORT, HciSetLeSupFeat(), and WsfTaskLock().
DmBisSyncInUse()
bool_t DmBisSyncInUse (uint16_t handle)
For internal use only. Return TRUE if the BIS sync is in use.
Parameters
handle BIS connection handle.
Returns
TRUE if the BIS sync is in use, FALSE otherwise.
DmCisAccept()
void DmCisAccept (uint16_t handle)
Inform the Controller to accept the request for the Connected Isochronous Stream (CIS) that is identified by the connection handle.
Parameters
handle Connection handle of the CIS.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmCisCigConfig()
void DmCisCigConfig (uint8_t cigId, dmConnId_t numCis, HciCisCisParams_t * pCisParam)
Set the parameters of one or more Connected Isochronous Streams (CISes) that are associated with the given Connected Isochronous Group (CIG).
Parameters
cigId CIG identifier.
numCis Number of CIS to be configured.
pCisParam CIS parameters.
Returns
None.
References DM_CIS_MAX, HCI_MAX_CIG_ID, WSF_ASSERT, WsfMsgAlloc(), WsfMsgSend(), WsfTaskLock(), and WsfTaskUnlock().
DmCisCigRemove()
void DmCisCigRemove (uint8_t cigId)
Remove all the Connected Isochronous Streams (CISes) associated with the given Connected Isochronous Group (CIG).
Parameters
cigId CIG identifier.
Returns
None.
References wsfMsgHdr_t::event, HCI_MAX_CIG_ID, wsfMsgHdr_t::param, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmCisCigSetPackingFraming()
void DmCisCigSetPackingFraming (uint8_t cigId, uint8_t packing, uint32_t framing)
Set the packing scheme and framing format for the given Connected Isochronous Group (CIG).
Parameters
cigId CIG identifier.
packing Packing scheme.
framing Indicates format of CIS Data PDUs.
Returns
None.
References dmCisCigCb_t::framing, HCI_MAX_CIG_ID, dmCisCigCb_t::packing, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmCisCigSetSca()
void DmCisCigSetSca (uint8_t cigId, uint8_t sca)
Set the slaves clock accuracy for the given Connected Isochronous Group (CIG).
Parameters
cigId CIG identifier.
sca Slaves clck accuracy (0 if unknown).
Returns
None.
Note
The slaves clock accuracy must which must be the worst-case sleep clock accuracy of the slaves that will participate in the CIG.
References HCI_MAX_CIG_ID, dmCisCigCb_t::sca, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmCisCigSetSduInterval()
void DmCisCigSetSduInterval (uint8_t cigId, uint32_t sduIntervalMToS, uint32_t sduIntervalSToM)
Set the interval, in microseconds, of periodic SDUs for the given Connected Isochronous Group (CIG).
Parameters
cigId CIG ID.
sduIntervalMToS Time interval between start of consecutive SDUs from master Host.
sduIntervalSToM Time interval between start of consecutive SDUs from slave Host.
Returns
None.
References HCI_MAX_CIG_ID, dmCisCigCb_t::sduIntervalMToS, dmCisCigCb_t::sduIntervalSToM, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmCisCigSetTransLatInterval()
void DmCisCigSetTransLatInterval (uint8_t cigId, uint16_t transLatMToS, uint16_t transLatSToM)
Set the maximum transport latency, in microseconds, for the given Connected Isochronous Group (CIG).
Parameters
cigId CIG identifier.
transLatMToS Maximum time for SDU to be transported from master Controller to slave Controller.
transLatSToM Maximum time for SDU to be transported from slave Controller to master Controller.
Returns
None.
References HCI_MAX_CIG_ID, dmCisCigCb_t::transLatMToS, dmCisCigCb_t::transLatSToM, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmCisClose()
void DmCisClose (uint16_t handle, uint8_t reason)
Close the Connected Isochronous Stream (CIS) connection with the given handle.
Parameters
handle CIS connection handle.
reason Reason connection is being closed.
Returns
None.
References dmCisCcb_t::cisId, DM_CIS_ID_NONE, wsfMsgHdr_t::event, dmCisApiClose_t::hdr, wsfMsgHdr_t::param, dmCisApiClose_t::reason, wsfMsgHdr_t::status, WsfMsgAlloc(), and WsfMsgSend().
DmCisConnInUse()
bool_t DmCisConnInUse (uint16_t handle)
For internal use only. Return TRUE if the Connected Isochronous Stream (CIS) connection is in use.
Parameters
handle CIS connection handle.
Returns
TRUE if the CIS connection is in use, FALSE otherwise.
DmCisInit()
void DmCisInit (void)
Initialize DM Connected Isochronous Stream (CIS) manager.
Returns
None.
References HCI_LE_SUP_FEAT_ISO_HOST_SUPPORT, HciSetLeSupFeat(), and WsfTaskLock().
DmCisMasterInit()
void DmCisMasterInit (void)
Initialize DM Connected Isochronous Stream (CIS) manager for operation as master.
Returns
None.
References HCI_LE_SUP_FEAT_CIS_MASTER, HciSetLeSupFeat(), and WsfTaskLock().
DmCisOpen()
void DmCisOpen (uint8_t numCis, uint16_t * pCisHandle, uint16_t * pAclHandle)
Create one or more Connected Isochronous Streams (CISes) using the connections identified by the ACL connection handles.
Parameters
numCis Total number of CISes to be created.
pCisHandle List of connection handles of CISes.
pAclHandle List of connection handles of ACLs.
Returns
None.
References DM_CIS_MAX, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmCisReject()
void DmCisReject (uint16_t handle, uint8_t reason)
Inform the Controller to reject the request for the Connected Isochronous Stream (CIS) that is identified by the connection handle.
Parameters
handle Connection handle of the CIS to be rejected.
reason Reason the CIS request was rejected.
Returns
None.
References wsfMsgHdr_t::event, dmCisApiReject_t::hdr, wsfMsgHdr_t::param, dmCisApiReject_t::reason, wsfMsgHdr_t::status, WsfMsgAlloc(), and WsfMsgSend().
DmCisSlaveInit()
void DmCisSlaveInit (void)
Initialize DM Connected Isochronous Stream (CIS) manager for operation as slave.
Returns
None.
References HCI_LE_SUP_FEAT_CIS_SLAVE, HciSetLeSupFeat(), and WsfTaskLock().
DmClearPerAdvList()
void DmClearPerAdvList (void)
DM clear periodic advertiser list.
Returns
None.
References HciLeClearPerAdvListCmd().
DmConnAccept()
dmConnId_t DmConnAccept (uint8_t clientId, uint8_t advHandle, uint8_t advType, uint16_t duration, uint8_t maxEaEvents, uint8_t addrType, uint8_t * pAddr)
Accept a connection from the given peer device by initiating directed advertising.
Parameters
clientId The client identifier.
advHandle Advertising handle.
advType Advertising type.
duration Advertising duration (in ms).
maxEaEvents Maximum number of extended advertising events.
addrType Address type.
pAddr Peer device address.
Returns
Connection identifier.
References DM_ROLE_SLAVE.
DmConnCheckIdle()
uint16_t DmConnCheckIdle (dmConnId_t connId)
Check if a connection is idle.
Parameters
connId Connection identifier.
Returns
Zero if connection is idle, nonzero if busy.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmConnClose()
void DmConnClose (uint8_t clientId, dmConnId_t connId, uint8_t reason)
Close the connection with the give connection identifier.
Parameters
clientId The client identifier.
connId Connection identifier.
reason Reason connection is being closed.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, wsfMsgHdr_t::status, WsfMsgAlloc(), and WsfMsgSend().
DmConnCteGetReqState()
uint8_t DmConnCteGetReqState (dmConnId_t connId)
Returns the device manager's CTE request state for a given connection.
Parameters
connId Connection identifier.
Returns
The CTE request state.
References DM_CONN_ID_NONE, DM_CONN_MAX, and WSF_ASSERT.
DmConnCteGetRspState()
uint8_t DmConnCteGetRspState (dmConnId_t connId)
Returns the device manager's CTE response state for a given connection.
Parameters
connId Connection identifier.
Returns
The CTE response state.
References DM_CONN_ID_NONE, DM_CONN_MAX, and WSF_ASSERT.
DmConnCteInit()
void DmConnCteInit (void)
Initialize DM Connection Constant Tone Extension (CTE) module.
Returns
None.
References HCI_LE_SUP_FEAT_CONN_CTE_REQ, HCI_LE_SUP_FEAT_CONN_CTE_RSP, HciSetLeSupFeat(), and WsfTaskLock().
DmConnCteReqStart()
void DmConnCteReqStart (dmConnId_t connId, uint16_t cteReqInt, uint8_t reqCteLen, uint8_t reqCteType)
Initiate the CTE Request procedure on the specified connection.
Parameters
connId Connection identifier.
cteReqInt CTE request interval.
reqCteLen Minimum length of CTE being requested in 8 us units.
reqCteType Requested CTE type.
Returns
None.
References WsfMsgAlloc(), and WsfMsgSend().
DmConnCteReqStop()
void DmConnCteReqStop (dmConnId_t connId)
Stop initiating the CTE Request procedure on the specified connection.
Parameters
connId Connection identifier.
Returns
None.
References WsfMsgAlloc(), and WsfMsgSend().
DmConnCteRspStart()
void DmConnCteRspStart (dmConnId_t connId)
Start responding to LL_CTE_REQ PDUs with LL_CTE_RSP PDUs on the specified connection.
Parameters
connId Connection identifier.
Returns
None.
References WsfMsgAlloc(), and WsfMsgSend().
DmConnCteRspStop()
void DmConnCteRspStop (dmConnId_t connId)
Stop responding to LL_CTE_REQ PDUs with LL_CTE_RSP PDUs on the specified connection.
Parameters
connId Connection identifier.
Returns
None.
References WsfMsgAlloc(), and WsfMsgSend().
DmConnCteRxSampleStart()
void DmConnCteRxSampleStart (dmConnId_t connId, uint8_t slotDurations, uint8_t switchPatternLen, uint8_t * pAntennaIDs)
Enable sampling received CTE fields on the specified connection, and configure the antenna switching pattern, and switching and sampling slot durations to be used.
Parameters
connId Connection identifier.
slotDurations Switching and sampling slot durations to be used while receiving CTE.
switchPatternLen Number of Antenna IDs in switching pattern.
pAntennaIDs List of Antenna IDs in switching pattern.
Returns
None.
References HCI_MAX_NUM_ANTENNA_IDS, HCI_MIN_NUM_ANTENNA_IDS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmConnCteRxSampleStop()
void DmConnCteRxSampleStop (dmConnId_t connId)
Disable sampling received CTE fields on the specified connection.
Parameters
connId Connection identifier.
Returns
None.
References WsfMsgAlloc(), and WsfMsgSend().
DmConnCteTxConfig()
void DmConnCteTxConfig (dmConnId_t connId, uint8_t cteTypeBits, uint8_t switchPatternLen, uint8_t * pAntennaIDs)
Configure the antenna switching pattern, and permitted CTE types used for transmitting CTEs requested by the peer device on the specified connection.
Parameters
connId Connection identifier.
cteTypeBits Permitted CTE type bits used for transmitting CTEs requested by peer.
switchPatternLen Number of Antenna IDs in switching pattern.
pAntennaIDs List of Antenna IDs in switching pattern.
Returns
None.
References HCI_MAX_NUM_ANTENNA_IDS, HCI_MIN_NUM_ANTENNA_IDS, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmConnIdByHandle()
dmConnId_t DmConnIdByHandle (uint16_t handle)
For internal use only. Find the connection ID with matching handle.
Parameters
handle Handle to find.
Returns
Connection ID or DM_CONN_ID_NONE if error.
References DM_CONN_ID_NONE.
DmConnInit()
void DmConnInit (void)
Initialize DM connection manager.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmConnInUse()
bool_t DmConnInUse (dmConnId_t connId)
For internal use only. Return TRUE if the connection is in use.
Parameters
connId Connection ID.
Returns
TRUE if the connection is in use, FALSE otherwise.
DmConnLocalAddr()
uint8_t* DmConnLocalAddr (dmConnId_t connId)
For internal use only. Return the local address.
Parameters
connId Connection ID.
Returns
Pointer to local address.
References WSF_ASSERT.
DmConnLocalAddrType()
uint8_t DmConnLocalAddrType (dmConnId_t connId)
For internal use only. Return the local address type.
Parameters
connId Connection ID.
Returns
Local address type.
References WSF_ASSERT.
DmConnLocalRpa()
uint8_t* DmConnLocalRpa (dmConnId_t connId)
For internal use only. Return the local resolvable private address (RPA).
Parameters
connId Connection ID.
Returns
Pointer to local RPA.
References WSF_ASSERT.
DmConnMasterInit()
void DmConnMasterInit (void)
Initialize DM connection manager for operation as legacy master.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmConnOpen()
dmConnId_t DmConnOpen (uint8_t clientId, uint8_t initPhys, uint8_t addrType, uint8_t * pAddr)
Open a connection to a peer device with the given address.
Parameters
clientId The client identifier.
initPhys Initiator PHYs.
addrType Address type.
pAddr Peer device address.
Returns
Connection identifier.
References DM_ROLE_MASTER.
DmConnPeerAddr()
uint8_t* DmConnPeerAddr (dmConnId_t connId)
For internal use only. Return the peer device address.
Parameters
connId Connection ID.
Returns
Pointer to peer device address.
References WSF_ASSERT.
DmConnPeerAddrType()
uint8_t DmConnPeerAddrType (dmConnId_t connId)
For internal use only. Return the peer address type.
Parameters
connId Connection ID.
Returns
Peer address type.
References WSF_ASSERT.
DmConnPeerRpa()
uint8_t* DmConnPeerRpa (dmConnId_t connId)
For internal use only. Return the peer resolvable private address (RPA).
Parameters
connId Connection ID.
Returns
Pointer to peer RPA.
References WSF_ASSERT.
DmConnReadRssi()
void DmConnReadRssi (dmConnId_t connId)
Read RSSI of a given connection.
Parameters
connId Connection identifier.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmConnRegister()
void DmConnRegister (uint8_t clientId, dmCback_t cback)
Register with the DM connection manager.
Parameters
clientId The client identifier.
cback Client callback function.
Returns
None.
Register with the DM connection manager.
Parameters
clientId The client identifier.
cback Client callback function.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmConnRequestPeerSca()
void DmConnRequestPeerSca (dmConnId_t connId)
Request the Sleep Clock Accuracy (SCA) of a peer device.
Parameters
connId Connection identifier.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmConnRole()
uint8_t DmConnRole (dmConnId_t connId)
Return the connection role indicating master or slave.
Parameters
connId Connection identifier.
Returns
Device role.
Parameters
connId Connection identifier.
Returns
Connection role.
References WSF_ASSERT.
DmConnSecLevel()
uint8_t DmConnSecLevel (dmConnId_t connId)
For internal use only. Return the security level of the connection.
Parameters
connId Connection ID.
Returns
Security level of the connection.
For internal use only. Return the security level of the connection.
Parameters
connId Connection ID.
Returns
Security level of the connection.
References WSF_ASSERT.
DmConnSetAddrType()
void DmConnSetAddrType (uint8_t addrType)
Set the local address type used for connections created with DmConnOpen().
Parameters
addrType Address type.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmConnSetConnSpec()
void DmConnSetConnSpec (hciConnSpec_t * pConnSpec)
Set the connection spec parameters for connections to be created with DmConnOpen().
Parameters
pConnSpec Connection spec parameters.
Returns
None.
References HCI_INIT_PHY_LE_1M_BIT.
DmConnSetDataLen()
void DmConnSetDataLen (dmConnId_t connId, uint16_t txOctets, uint16_t txTime)
Set data length for a given connection.
Parameters
connId Connection identifier.
txOctets Maximum number of payload octets for a Data PDU.
txTime Maximum number of microseconds for a Data PDU.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmConnSetIdle()
void DmConnSetIdle (dmConnId_t connId, uint16_t idleMask, uint8_t idle)
Configure a bit in the connection idle state mask as busy or idle.
Parameters
connId Connection identifier.
idleMask Bit in the idle state mask to configure.
idle DM_CONN_BUSY or DM_CONN_IDLE.
Returns
None.
References DM_CONN_IDLE, DmConnInUse(), WsfTaskLock(), and WsfTaskUnlock().
DmConnSetScanInterval()
void DmConnSetScanInterval (uint16_t scanInterval, uint16_t scanWindow)
Set the scan interval and window for connections to be created with DmConnOpen().
Parameters
scanInterval The scan interval.
scanWindow The scan window.
Returns
None.
References HCI_INIT_PHY_LE_1M_BIT.
DmConnSlaveInit()
void DmConnSlaveInit (void)
Initialize DM connection manager for operation as legacy slave.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmConnUpdate()
void DmConnUpdate (dmConnId_t connId, hciConnSpec_t * pConnSpec)
Update the connection parameters of an open connection.
Parameters
connId Connection identifier.
pConnSpec Connection specification.
Returns
None.
References DM_ROLE_MASTER, DmConnRole(), wsfMsgHdr_t::event, HCI_INIT_PHY_LE_1M_BIT, HCI_INIT_PHY_LE_2M_BIT, HCI_INIT_PHY_LE_CODED_BIT, wsfMsgHdr_t::param, WSF_ASSERT, WsfMsgAlloc(), WsfMsgSend(), WsfTaskLock(), and WsfTaskUnlock().
DmDataPathConfig()
void DmDataPathConfig (HciConfigDataPath_t * pDataPathParam)
Request the Controller to configure the data transport path in a given direction between the Controller and the Host.
Parameters
pDataPathParam Parameters for configuring data path.
Returns
None.
References HciConfigDataPathCmd().
DmDevPrivInit()
void DmDevPrivInit (void)
Initialize device privacy module.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmDevPrivStart()
void DmDevPrivStart (uint16_t changeInterval)
Start using a private resolvable address.
Parameters
changeInterval Interval between automatic address changes, in seconds.
Returns
None.
References wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmDevPrivStop()
void DmDevPrivStop (void)
Stop using a private resolvable address.
Returns
None.
References wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmDevReset()
void DmDevReset (void)
Reset the device.
Returns
None.
References wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmDevSetExtFilterPolicy()
bool_t DmDevSetExtFilterPolicy (uint8_t advHandle, uint8_t mode, uint8_t policy)
Set the Advertising filter policy for the given advertising, Scanning or Initiator filter policy.
Parameters
advHandle Advertising handle (only applicable to advertising).
mode Policy mode.
policy Filter policy.
Returns
TRUE if the filter policy was successfully set, FALSE otherwise.
DmDevSetFilterPolicy()
bool_t DmDevSetFilterPolicy (uint8_t mode, uint8_t policy)
Set the Advertising, Scanning or Initiator filter policy.
Parameters
mode Policy mode.
policy Filter policy.
Returns
TRUE if the filter policy was successfully set, FALSE otherwise.
DmDevSetRandAddr()
void DmDevSetRandAddr (uint8_t * pAddr)
Set the random address to be used by the local device.
Parameters
pAddr Random address.
Returns
None.
References BdaCpy(), and HciLeSetRandAddrCmd().
DmDevVsInit()
void DmDevVsInit (uint8_t param)
Vendor-specific controller initialization function.
Parameters
param Vendor-specific parameter.
Returns
None.
References HciVsInit().
DmDevWhiteListAdd()
void DmDevWhiteListAdd (uint8_t addrType, uint8_t * pAddr)
Add a peer device to the white list. Note that this function cannot be called while advertising, scanning, or connecting with white list filtering active.
Parameters
addrType Address type.
pAddr Peer device address.
Returns
None.
References HciLeAddDevWhiteListCmd().
DmDevWhiteListClear()
void DmDevWhiteListClear (void)
Clear the white list. Note that this function cannot be called while advertising, scanning, or connecting with white list filtering active.
Returns
None.
References HciLeClearWhiteListCmd().
DmDevWhiteListRemove()
void DmDevWhiteListRemove (uint8_t addrType, uint8_t * pAddr)
Remove a peer device from the white list. Note that this function cannot be called while advertising, scanning, or connecting with white list filtering active.
Parameters
addrType Address type.
pAddr Peer device address.
Returns
None.
References HciLeRemoveDevWhiteListCmd().
DmExtAdvInit()
void DmExtAdvInit (void)
Initialize DM extended advertising.
Returns
None.
References HCI_LE_SUP_FEAT_LE_EXT_ADV, HCI_LE_SUP_FEAT_LE_PER_ADV, HciLeSetAdvSetRandAddrCmd(), HciSetLeSupFeat(), HciVsAeInit(), and WsfTaskLock().
DmExtConnMasterInit()
void DmExtConnMasterInit (void)
Initialize DM connection manager for operation as extended master.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmExtConnSetConnSpec()
void DmExtConnSetConnSpec (uint8_t initPhys, hciConnSpec_t * pConnSpec)
Set the extended connection spec parameters for extended connections to be created with DmConnOpen().
Parameters
initPhys The initiator PHYs.
pConnSpec Connection spec parameters array.
Returns
None.
References DM_NUM_PHYS.
DmExtConnSetScanInterval()
void DmExtConnSetScanInterval (uint8_t initPhys, uint16_t * pScanInterval, uint16_t * pScanWindow)
Set the scan interval and window for extended connections to be created with DmConnOpen().
Parameters
initPhys Initiator PHYs.
pScanInterval Scan interval array.
pScanWindow Scan window array.
Returns
None.
Parameters
initPhy Initiator PHYs.
pScanInterval Scan interval array.
pScanWindow Scan window array.
Returns
None.
References DM_NUM_PHYS.
DmExtConnSlaveInit()
void DmExtConnSlaveInit (void)
Initialize DM connection manager for operation as extended slave.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmExtMaxAdvDataLen()
uint16_t DmExtMaxAdvDataLen (uint8_t advType, bool_t useLegacyPdu)
Get the maximum advertising data length supported by Controller for a given advertising type.
Parameters
advType Advertising type.
useLegacyPdu Whether to use legacy advertising PDUs with extended advertising.
Returns
Maximum advertising data length.
DmExtScanInit()
void DmExtScanInit (void)
Initialize DM extended scanning.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmFindAdType()
uint8_t* DmFindAdType (uint8_t adType, uint16_t dataLen, uint8_t * pData)
Find an advertising data element in the given advertising or scan response data.
Parameters
adType Advertising data element type to find.
dataLen Data length.
pData Pointer to advertising or scan response data.
Returns
Pointer to the advertising data element byte array or NULL if not found.
Parameters
adType Advertising data element type to find.
dataLen Data length.
pData Pointer to advertising or scan response data.
Returns
Pointer to advertising data element byte array or NULL if not found.
References DM_AD_LEN_IDX, and DM_AD_TYPE_IDX.
DmHostAddrType()
uint8_t DmHostAddrType (uint8_t addrType)
Map an address type to a type used by Host.
Parameters
addrType Address type used by LL.
Returns
Address type used by Host.
References DM_ADDR_PUBLIC, DM_ADDR_PUBLIC_IDENTITY, DM_ADDR_RANDOM, and DM_ADDR_RANDOM_IDENTITY.
DmIsoDataPathRemove()
void DmIsoDataPathRemove (uint16_t handle, uint8_t directionBits)
Remove the input and/or output data path(s) associated with a Connected Isochronous Stream (CIS) or Broadcast Isochronous Stream (BIS) identified by the connection handle parameter.
Parameters
handle Connection handle of CIS or BIS.
directionBits Data path direction bits.
Returns
None.
Remove the input and/or output data path(s) associated with a Connected Isochronous Stream (CIS) or Broadcast Isochronous Stream (BIS) identified by the connection handle parameter.
Parameters
handle Connection handle of CIS or BIS.
directionBits Data path direction bits.
Returns
None.
References HCI_ISO_DATA_PATH_OUTPUT_BIT, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmIsoDataPathSetup()
void DmIsoDataPathSetup (HciIsoSetupDataPath_t * pDataPathParam)
Setup the isochronous data path between the Host and the Controller for an established Connected Isochronous Stream (CIS) or Broadcast Isochronous Stream (BIS) identified by the connection handle parameter.
Parameters
pDataPathParam Parameters to setup ISO data path.
Returns
None.
Setup the isochronous data path between the Host and the Controller for an established Connected Isochronous Stream (CIS) or Broadcast Isochronous Stream (BIS) identified by the connection handle parameter.
Parameters
pDataPathParam Parameters to setup ISO data path.
Returns
None.
References HciIsoSetupDataPath_t::codecConfigLen, HciIsoSetupDataPath_t::dpDir, HciIsoSetupDataPath_t::handle, HciIsoSetupDataPath_t::pCodecConfig, WSF_ASSERT, WsfMsgAlloc(), WsfMsgSend(), WsfTaskLock(), and WsfTaskUnlock().
DmIsoInit()
void DmIsoInit (void)
Initialize DM ISO manager.
Returns
None.
References HciIsoRegister(), WsfTaskLock(), and WsfTaskUnlock().
DmL2cCmdRejInd()
void DmL2cCmdRejInd (uint16_t handle, uint16_t result)
For internal use only. L2C calls this function to send the result of an L2CAP Command Reject up to the application.
Parameters
handle Connection handle.
result Connection update result code.
Returns
None.
For internal use only. L2C calls this function to send the result of an L2CAP Command Reject up to the application.
Parameters
handle Connection handle.
result Connection update result code.
Returns
None.
References DM_CLIENT_ID_APP, DM_L2C_CMD_REJ_IND, wsfMsgHdr_t::event, dmL2cCmdRejEvt_t::handle, HCI_SUCCESS, dmL2cCmdRejEvt_t::hdr, dmL2cCmdRejEvt_t::reason, and wsfMsgHdr_t::status.
DmL2cConnUpdateCnf()
void DmL2cConnUpdateCnf (uint16_t handle, uint16_t result)
For internal use only. L2C calls this function to send the result of an L2CAP connection update response to DM.
Parameters
handle Connection handle.
reason Connection update response reason code.
Returns
None.
Parameters
handle Connection handle.
result Connection update result code.
Returns
None.
References wsfMsgHdr_t::event.
DmL2cConnUpdateInd()
void DmL2cConnUpdateInd (uint8_t identifier, uint16_t handle, hciConnSpec_t * pConnSpec)
For internal use only. L2C calls this function when it receives a connection update request from a peer device.
Parameters
identifier Identifier value.
handle Connection handle.
pConnSpec Connection spec parameters.
Returns
None.
References wsfMsgHdr_t::event.
DmLlAddrType()
uint8_t DmLlAddrType (uint8_t addrType)
Map an address type to a type used by LL.
Parameters
addrType Address type used by Host.
Returns
Address type used by LL.
References DM_ADDR_PUBLIC, DM_ADDR_PUBLIC_IDENTITY, DM_ADDR_RANDOM, and DM_ADDR_RANDOM_IDENTITY.
DmLlPrivEnabled()
bool_t DmLlPrivEnabled (void)
Whether LL Privacy is enabled.
Returns
TRUE if LL Privacy is enabled. FALSE, otherwise.
DmPastConfig()
void DmPastConfig (dmConnId_t connId, uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
Specify how the Controller should process periodic advertising synchronization information received from the device identified by the connnection handle.
Parameters
connId Connection identifier.
mode Action to be taken when periodic advertising info is received.
skip Number of consecutive periodic advertising packets that the receiver may skip after successfully receiving a periodic advertising packet.
syncTimeout Maximum permitted time between successful receives. If this time is exceeded, synchronization is lost.
cteType Whether to only synchronize to periodic advertising with certain types of Constant Tone Extension.
Returns
None.
Specify how the Controller should process periodic advertising synchronization information received from the device identified by the connnection handle.
Parameters
connId Connection identifier.
mode Action to be taken when periodic advertising info is received.
skip Number of consecutive periodic advertising packets that the receiver may skip after successfully receiving a periodic advertising packet.
syncTimeout Maximum permitted time between successful receives. If this time is exceeded, synchronization is lost.
cteType Whether to only synchronize to periodic advertising with certain types of Constant Tone Extension.
Returns
None.
References wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmPastDefaultConfig()
void DmPastDefaultConfig (uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
Specify the initial value for the mode, skip, timeout, and Constant Tone Extension type to be used for all subsequent connections over the LE transport.
Parameters
mode Action to be taken when periodic advertising info is received.
skip Number of consecutive periodic advertising packets that the receiver may skip after successfully receiving a periodic advertising packet.
syncTimeout Maximum permitted time between successful receives. If this time is exceeded, synchronization is lost.
cteType Whether to only synchronize to periodic advertising with certain types of Constant Tone Extension.
Returns
None.
References wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmPastInit()
void DmPastInit (void)
Initialize DM Periodic Advertising Sync Transfer (PAST) module.
Returns
None.
References HCI_LE_SUP_FEAT_PAST_RECIPIENT, HCI_LE_SUP_FEAT_PAST_SENDER, HCI_LE_SUP_FEAT_RECV_CTE, HciSetLeSupFeat(), and WsfTaskLock().
DmPastRptRcvEnable()
void DmPastRptRcvEnable (dmSyncId_t syncId, bool_t enable)
Enable or disable reports for the periodic advertising identified by the sync id.
Parameters
syncId Sync identifier.
enable TRUE to enable reporting, FALSE to disable reporting.
Returns
None.
DmPastSetInfoTrsf()
void DmPastSetInfoTrsf (dmConnId_t connId, uint16_t serviceData, uint8_t advHandle)
Send synchronization information about the periodic advertising in an advertising set to a connected device.
Parameters
connId Connection identifier.
serviceData Value provided by the Host.
advHandle Advertising handle.
Returns
None.
References wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmPastSyncTrsf()
void DmPastSyncTrsf (dmConnId_t connId, uint16_t serviceData, dmSyncId_t syncId)
Send synchronization information about the periodic advertising identified by the sync id to a connected device.
Parameters
connId Connection identifier.
serviceData Value provided by the Host.
syncId Sync identifier.
Returns
None.
References wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmPerAdvConfig()
void DmPerAdvConfig (uint8_t advHandle)
Set the advertising parameters for periodic advertising.
Parameters
advHandle Advertising handle.
Returns
None.
References WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmPerAdvEnabled()
bool_t DmPerAdvEnabled (uint8_t advHandle)
Get status of periodic advertising handle.
Parameters
advHandle Advertising handle.
Returns
TRUE if periodic advertising is running on that handle. FALSE, otherwise.
DmPerAdvIncTxPwr()
void DmPerAdvIncTxPwr (uint8_t advHandle, bool_t incTxPwr)
Set whether or not to include TxPower in extended header of advertising PDU for periodic advertising.
Parameters
advHandle Advertising handle.
incTxPwr Whether to include TxPower in extended header of advertising PDU (default value is FALSE).
Returns
None.
DmPerAdvSetData()
void DmPerAdvSetData (uint8_t advHandle, uint8_t op, uint8_t len, uint8_t * pData)
Set the advertising data to the given data for periodic advertising.
Parameters
advHandle Advertising handle.
op Data operation.
len Length of the data. Maximum length is 236 bytes.
pData Pointer to the data.
Returns
None.
References HCI_PER_ADV_DATA_LEN, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmPerAdvSetInterval()
void DmPerAdvSetInterval (uint8_t advHandle, uint16_t intervalMin, uint16_t intervalMax)
Set the minimum and maximum advertising intervals for periodic advertising.
Parameters
advHandle Advertising handle.
intervalMin Minimum advertising interval.
intervalMax Maximum advertising interval.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
DmPerAdvStart()
void DmPerAdvStart (uint8_t advHandle)
Start periodic advertising for the advertising set specified by the advertising handle.
Parameters
advHandle Advertising handle.
Returns
None.
References WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmPerAdvStop()
void DmPerAdvStop (uint8_t advHandle)
Stop periodic advertising for the advertising set specified by the advertising handle.
Parameters
advHandle Advertising handle.
Returns
None.
References WSF_ASSERT, WsfMsgAlloc(), and WsfMsgSend().
DmPhyInit()
void DmPhyInit (void)
Initialize DM PHY.
Returns
None.
References HCI_LE_SUP_FEAT_LE_2M_PHY, HCI_LE_SUP_FEAT_LE_CODED_PHY, HciSetLeSupFeat(), and WsfTaskLock().
DmPrivAddDevToResList()
void DmPrivAddDevToResList (uint8_t addrType, const uint8_t * pIdentityAddr, uint8_t * pPeerIrk, uint8_t * pLocalIrk, bool_t enableLlPriv, uint16_t param)
Add device to resolving list. When complete the client's callback function is called with a DM_PRIV_ADD_DEV_TO_RES_LIST_IND event. The client must wait to receive this event before executing this function again.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
pPeerIrk The peer's identity resolving key.
pLocalIrk The local identity resolving key.
enableLlPriv Set to TRUE to enable address resolution in LL.
param client-defined parameter returned with callback event.
Returns
None.
This command cannot be used when address resolution is enabled in the Controller and:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
If the local or peer IRK associated with the peer Identity Address is all zeros then the Controller will use or accept the local or peer Identity Address respectively.
Parameter 'enableLlPriv' should be set to TRUE when the last device is being added to resolving list to enable address resolution in the Controller.
DmPrivClearResList()
void DmPrivClearResList (void)
Clear resolving list. When complete the client's callback function is called with a DM_PRIV_CLEAR_RES_LIST_IND event. The client must wait to receive this event before executing this function again.
Returns
None.
This command cannot be used when address resolution is enabled in the Controller and:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
Address resolution in Controller will be disabled when resolving list's cleared successfully.
Returns
None.
This command cannot be used when address resolution is enabled in the Controller and:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
Address resolution in the Controller will be disabled when resolving list's cleared successfully.
References wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmPrivGenerateAddr()
void DmPrivGenerateAddr (uint8_t * pIrk, uint16_t param)
Generate a Resolvable Private Address (RPA).
Parameters
pIrk The identity resolving key.
param Client-defined parameter returned with callback event.
Returns
None.
References Calc128Cpy(), wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmPrivInit()
void DmPrivInit (void)
Initialize DM privacy module.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmPrivReadLocalResolvableAddr()
void DmPrivReadLocalResolvableAddr (uint8_t addrType, const uint8_t * pIdentityAddr)
Read local resolvable address command. When complete the client's callback function is called with a DM_PRIV_READ_LOCAL_RES_ADDR_IND event. The client must wait to receive this event before executing this function again.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
Returns
None.
References HciLeReadLocalResolvableAddr().
DmPrivReadPeerResolvableAddr()
void DmPrivReadPeerResolvableAddr (uint8_t addrType, const uint8_t * pIdentityAddr)
HCI read peer resolvable address command. When complete the client's callback function is called with a DM_PRIV_READ_PEER_RES_ADDR_IND event. The client must wait to receive this event before executing this function again.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
Returns
None.
References HciLeReadPeerResolvableAddr().
DmPrivRemDevFromResList()
void DmPrivRemDevFromResList (uint8_t addrType, const uint8_t * pIdentityAddr, uint16_t param)
Remove device from resolving list. When complete the client's callback function is called with a DM_PRIV_REM_DEV_FROM_RES_LIST_IND event. The client must wait to receive this event before executing this function again.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
param client-defined parameter returned with callback event.
Returns
None.
This command cannot be used when address resolution is enabled in the Controller and:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
References BdaCpy(), wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmPrivResolveAddr()
void DmPrivResolveAddr (uint8_t * pAddr, uint8_t * pIrk, uint16_t param)
Resolve a private resolvable address. When complete the client's callback function is called with a DM_PRIV_RESOLVED_ADDR_IND event. The client must wait to receive this event before executing this function again.
Parameters
pAddr Peer device address.
pIrk The peer's identity resolving key.
param Client-defined parameter returned with callback event.
Returns
None.
Parameters
pAddr Peer device address.
pIrk The peer's identity resolving key.
param client-defined parameter returned with callback event.
Returns
None.
References BdaCpy(), Calc128Cpy(), wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmPrivSetAddrResEnable()
void DmPrivSetAddrResEnable (bool_t enable)
Enable or disable address resolution in LL. When complete the client's callback function is called with a DM_PRIV_SET_ADDR_RES_ENABLE_IND event. The client must wait to receive this event before executing this function again.
Parameters
enable Set to TRUE to enable address resolution or FALSE to disable it.
Returns
None.
This command can be used at any time except when:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
DmPrivSetPrivacyMode()
void DmPrivSetPrivacyMode (uint8_t addrType, const uint8_t * pIdentityAddr, uint8_t mode)
Set privacy mode for a given entry in the resolving list.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
mode Privacy mode (by default, network privacy mode is used).
Returns
None.
This command can be used at any time except when:
Advertising (other than periodic advertising) is enabled,
Scanning is enabled, or
(Extended) Create connection or Create Sync command is outstanding.
References BdaCpy(), wsfMsgHdr_t::event, WsfMsgAlloc(), and WsfMsgSend().
DmPrivSetResolvablePrivateAddrTimeout()
void DmPrivSetResolvablePrivateAddrTimeout (uint16_t rpaTimeout)
Set resolvable private address timeout command.
Parameters
rpaTimeout Timeout measured in seconds.
Returns
None.
References HciLeSetResolvablePrivateAddrTimeout().
DmReadAntennaInfo()
void DmReadAntennaInfo (void)
Read the switching rates, the sampling rates, the number of antennae, and the maximum length of a transmitted Constant Tone Extension supported by the Controller.
Returns
None.
Note
The antenna info will be returned with DM indication DM_READ_ANTENNA_INFO_IND.
References HciLeReadAntennaInfoCmd().
DmReadLocalSupCodecCap()
void DmReadLocalSupCodecCap (HciReadLocalSupCodecCaps_t * pCodecParam)
Read a list of codec capabilities supported by the Controller for a given codec.
Parameters
pCodecParam Parameters for reading local supported codec capabilities.
Returns
None.
References HciReadLocalSupCodecCapCmd().
DmReadLocalSupCodecs()
void DmReadLocalSupCodecs (void)
Read a list of the codecs supported by the Controller, as well as vendor specific codecs, which are defined by an individual manufacturer.
Returns
None.
References HciReadLocalSupCodecsCmd().
DmReadLocalSupCtrDly()
void DmReadLocalSupCtrDly (HciReadLocalSupControllerDly_t * pDelayParam)
Read the range of supported Controller delays for the codec specified by Codec ID on a given transport type specified by Logical Transport Type, in the direction specified by Direction, and with the codec configuration specified by Codec Configuration.
Parameters
pDelayParam Parameters for reading local supported controller delay.
Returns
None.
References HciReadLocalSupControllerDlyCmd().
DmReadPhy()
void DmReadPhy (dmConnId_t connId)
Read the current transmitter PHY and receiver PHY for a given connection.
Parameters
connId Connection identifier.
Returns
None.
References HciLeReadPhyCmd(), WsfTaskLock(), and WsfTaskUnlock().
DmReadRemoteFeatures()
void DmReadRemoteFeatures (dmConnId_t connId)
For internal use only. Read the features of the remote device.
Parameters
connId Connection identifier.
Returns
None.
For internal use only. Read the features of the remote device.
Parameters
connId Connection identifier.
Returns
None.
References DM_CLIENT_ID_APP, DM_REMOTE_FEATURES_IND, wsfMsgHdr_t::event, hciLeReadRemoteFeatCmplEvt_t::features, hciLeReadRemoteFeatCmplEvt_t::handle, HCI_SUCCESS, HciLeReadRemoteFeatCmd(), hciLeReadRemoteFeatCmplEvt_t::hdr, wsfMsgHdr_t::param, wsfMsgHdr_t::status, hciLeReadRemoteFeatCmplEvt_t::status, and UINT32_TO_BSTREAM.
DmReadRemoteVerInfo()
void DmReadRemoteVerInfo (dmConnId_t connId)
Read the version info of the remote device.
Parameters
connId Connection identifier.
Returns
None.
References HciReadRemoteVerInfoCmd().
DmRegister()
void DmRegister (dmCback_t cback)
Register a callback with DM for scan and advertising events.
Parameters
cback Client callback function.
Returns
None.
References DM_ERR_SMP_RX_PDU_LEN_EXCEEDED, DM_ERROR_IND, wsfMsgHdr_t::event, HciGetMaxRxAclLen(), dmEvt_t::hdr, L2C_HDR_LEN, wsfMsgHdr_t::param, SMP_PUB_KEY_MSG_LEN, and wsfMsgHdr_t::status.
DmRemoteConnParamReqNegReply()
void DmRemoteConnParamReqNegReply (dmConnId_t connId, uint8_t reason)
Negative reply to the HCI remote connection parameter request event. This command is used to indicate that the Host has rejected the remote device's request to change connection parameters.
Parameters
connId Connection identifier.
reason Reason for rejection.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmRemoteConnParamReqReply()
void DmRemoteConnParamReqReply (dmConnId_t connId, hciConnSpec_t * pConnSpec)
Reply to the HCI remote connection parameter request event. This command is used to indicate that the Host has accepted the remote device's request to change connection parameters.
Parameters
connId Connection identifier.
pConnSpec Connection specification.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmRemoveDeviceFromPerAdvList()
void DmRemoveDeviceFromPerAdvList (uint8_t advAddrType, uint8_t * pAdvAddr, uint8_t advSid)
DM remove device from periodic advertiser list.
Parameters
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
advSid Advertising SID.
Returns
None.
References HciLeRemoveDeviceFromPerAdvListCmd().
DmScanInit()
void DmScanInit (void)
Initialize DM legacy scanning.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmScanModeExt()
bool_t DmScanModeExt (void)
Whether DM scanning is in extended mode.
Returns
TRUE if DM scanning is in extended mode. FALSE, otherwise.
DmScanModeLeg()
bool_t DmScanModeLeg (void)
Whether DM scanning is in legacy mode.
Returns
TRUE if DM scanning is in legacy mode. FALSE, otherwise.
DmScanSetAddrType()
void DmScanSetAddrType (uint8_t addrType)
Set the local address type used while scanning. This function can be used to configure scanning to use a random address.
Parameters
addrType Address type.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmScanSetInterval()
void DmScanSetInterval (uint8_t scanPhys, uint16_t * pScanInterval, uint16_t * pScanWindow)
Set the scan interval and window for the specified PHYs.
Parameters
scanPhys Scanning PHYs.
pScanInterval Scan interval array.
pScanWindow Scan window array.
Returns
None.
References DM_NUM_PHYS.
DmScanStart()
void DmScanStart (uint8_t scanPhys, uint8_t mode, const uint8_t * pScanType, bool_t filterDup, uint16_t duration, uint16_t period)
Start scanning on the given PHYs.
Parameters
scanPhys Scanner PHYs.
mode Discoverability mode.
pScanType Scan type array.
filterDup Filter duplicates. Set to TRUE to filter duplicate responses received from the same device. Set to FALSE to receive all responses.
duration The scan duration, in milliseconds. If set to zero or both duration and period set to non-zero, scanning will continue until DmScanStop() is called.
period The scan period, in 1.28 sec units (only applicable to AE). If set to zero, periodic scanning is disabled.
Returns
None.
DmScanStop()
void DmScanStop (void)
Stop scanning.
Returns
None.
References wsfMsgHdr_t::event, HCI_INIT_PHY_LE_1M_BIT, HCI_INIT_PHY_LE_CODED_BIT, WSF_ASSERT, WsfMsgAlloc(), WsfMsgSend(), WsfTaskLock(), and WsfTaskUnlock().
DmSecAuthRsp()
void DmSecAuthRsp (dmConnId_t connId, uint8_t authDataLen, uint8_t * pAuthData)
This function is called in response to a DM_SEC_AUTH_REQ_IND event to provide PIN or OOB data during pairing.
Parameters
connId DM connection ID.
authDataLen Length of PIN or OOB data.
pAuthData pointer to PIN or OOB data.
Returns
None.
References smpDmAuthRsp_t::authData, smpDmAuthRsp_t::authDataLen, wsfMsgHdr_t::event, smpDmAuthRsp_t::hdr, wsfMsgHdr_t::param, SMP_MSG_API_AUTH_RSP, SMP_OOB_LEN, SmpDmMsgSend(), WSF_ASSERT, and WsfMsgAlloc().
DmSecCalcOobReq()
void DmSecCalcOobReq (uint8_t * pRand, uint8_t * pPubKeyX)
This function calculates the local random and confirm values used in LESC OOB pairing. The operation's result is posted as a DM_SEC_CALC_OOB_IND event to the application's DM callback handler. The local rand and confirm values are exchanged with the peer via out-of-band (OOB) methods and passed into the DmSecSetOob after DM_CONN_OPEN_IND.
Parameters
pRand Random value used in calculation.
pPubKeyX X component of the local public key.
Returns
None.
This function calculates the local random and confirm values used in LESC OOB pairing. The operation's result is posted as a DM_SEC_CALC_OOB_IND event to the application's DM callback handler. The local rand and confirm values are exchanged with the peer via out-of-band (OOB) methods and passed into the DmSecSetOob after DM_CONN_OPEN_IND.
Parameters
pRand Random value used in calculation.
pPubKeyX X component of the local public key.
Returns
none.
References Calc128Cpy(), DM_SEC_CALC_OOB_IND, wsfMsgHdr_t::event, HCI_ERR_MEMORY_EXCEEDED, dmSecOobCalcIndEvt_t::hdr, SecCmac(), SMP_F4_TEXT_LEN, SMP_PUB_KEY_LEN, SMP_RAND_LEN, wsfMsgHdr_t::status, WsfBufAlloc(), and WsfBufFree().
DmSecCancelReq()
void DmSecCancelReq (dmConnId_t connId, uint8_t reason)
This function is called to cancel the pairing process.
Parameters
connId DM connection ID.
reason Failure reason.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, SMP_MSG_API_CANCEL_REQ, SmpDmMsgSend(), wsfMsgHdr_t::status, and WsfMsgAlloc().
DmSecCompareRsp()
void DmSecCompareRsp (dmConnId_t connId, bool_t valid)
This function is called by the application in response to a DM_SEC_COMPARE_IND event. The valid parameter indicates if the compare value of the DM_SEC_COMPARE_IND was valid.
Parameters
connId ID of the connection.
valid TRUE if compare value was valid
Returns
None.
Parameters
connId ID of the connection
valid TRUE if compare value was valid
Returns
None.
DmSecEncryptReq()
void DmSecEncryptReq (dmConnId_t connId, uint8_t secLevel, dmSecLtk_t * pLtk)
This function is called by a master device to initiate link encryption.
Parameters
connId DM connection ID.
secLevel Security level of pairing when LTK was exchanged.
pLtk Pointer to LTK parameter structure.
Returns
None.
Parameters
connId DM connection ID.
secLevel Security level of pairing when key was exchanged.
pLtk Pointer to LTK parameter structure.
Returns
None.
References WsfMsgAlloc(), and WsfMsgSend().
DmSecGenerateEccKeyReq()
void DmSecGenerateEccKeyReq (void)
This function generates an ECC key for use with LESC security.
Returns
None.
This function generates an ECC key for use with LESC security.
Returns
None.
References SecEccGenKey().
DmSecGetCompareValue()
uint32_t DmSecGetCompareValue (uint8_t * pConfirm)
This function returns the 6-digit compare value for the specified 128-bit confirm value.
Parameters
pConfirm Pointer to 128-bit comfirm value.
Returns
Six-digit compare value.
DmSecGetEccKey()
secEccKey_t* DmSecGetEccKey (void)
This function gets the local ECC key for use with LESC security.
Returns
Pointer to local ECC key.
DmSecGetLocalCsrk()
uint8_t* DmSecGetLocalCsrk (void)
For internal use only. This function gets the local CSRK used by the device.
Returns
Pointer to CSRK.
For internal use only. This function gets the local CSRK used by the device.
Returns
Pointer to CSRK.
DmSecGetLocalIrk()
uint8_t* DmSecGetLocalIrk (void)
For internal use only. This function gets the local IRK used by the device.
Returns
Pointer to IRK.
For internal use only. This function gets the local IRK used by the device.
Returns
Pointer to IRK.
References SmpDbInit().
DmSecInit()
void DmSecInit (void)
Initialize DM security.
Returns
None.
References calc128Zeros.
DmSecLescInit()
void DmSecLescInit (void)
Initialize DM LE Secure Connections security.
Returns
None.
DmSecLtkRsp()
void DmSecLtkRsp (dmConnId_t connId, bool_t keyFound, uint8_t secLevel, uint8_t * pKey)
This function is called by a slave in response to a DM_SEC_LTK_REQ_IND event to provide the long term key used for encryption.
Parameters
connId DM connection ID.
keyFound TRUE if key found.
secLevel Security level of pairing when key was exchanged.
pKey Pointer to the key, if found.
Returns
None.
This function is called by a slave in response to a DM_SEC_LTK_REQ_IND event to provide the long term key used for encryption.
Parameters
connId DM connection ID.
keyFound TRUE if key found.
secLevel Security level of pairing when key was exchanged.
*pKey Pointer to the key, if found.
Returns
None.
DmSecPairReq()
void DmSecPairReq (dmConnId_t connId, uint8_t oob, uint8_t auth, uint8_t iKeyDist, uint8_t rKeyDist)
This function is called by a master device to initiate pairing.
Parameters
connId DM connection ID.
oob Out-of-band pairing data present or not present.
auth Authentication and bonding flags.
iKeyDist Initiator key distribution flags.
rKeyDist Responder key distribution flags.
Returns
None.
References smpDmPair_t::auth, wsfMsgHdr_t::event, smpDmPair_t::hdr, smpDmPair_t::iKeyDist, smpDmPair_t::oob, wsfMsgHdr_t::param, smpDmPair_t::rKeyDist, SMP_KEY_DIST_MASK, SMP_MSG_API_PAIR_REQ, SmpDmMsgSend(), and WsfMsgAlloc().
DmSecPairRsp()
void DmSecPairRsp (dmConnId_t connId, uint8_t oob, uint8_t auth, uint8_t iKeyDist, uint8_t rKeyDist)
This function is called by a slave device to proceed with pairing after a DM_SEC_PAIR_IND event is received.
Parameters
connId DM connection ID.
oob Out-of-band pairing data present or not present.
auth Authentication and bonding flags.
iKeyDist Initiator key distribution flags.
rKeyDist Responder key distribution flags.
Returns
None.
References smpDmPair_t::auth, wsfMsgHdr_t::event, smpDmPair_t::hdr, smpDmPair_t::iKeyDist, smpDmPair_t::oob, wsfMsgHdr_t::param, smpDmPair_t::rKeyDist, SMP_KEY_DIST_MASK, SMP_MSG_API_PAIR_RSP, SmpDmMsgSend(), and WsfMsgAlloc().
DmSecSetDebugEccKey()
void DmSecSetDebugEccKey (void)
This function sets the ECC key for use with LESC security to standard debug keys values.
Returns
None.
References secEccKey_t::privKey, secEccKey_t::pubKey_x, secEccKey_t::pubKey_y, and SEC_ECC_KEY_LEN.
DmSecSetEccKey()
void DmSecSetEccKey (secEccKey_t * pKey)
This function sets the ECC key for use with LESC security.
Parameters
pKey Pointer to key.
Returns
None.
This function sets the ECC key for use with LESC security.
Parameters
pKey Pointer to local ECC key
Returns
None.
DmSecSetLocalCsrk()
void DmSecSetLocalCsrk (uint8_t * pCsrk)
This function sets the local CSRK used by the device.
Parameters
pCsrk Pointer to CSRK.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmSecSetLocalIrk()
void DmSecSetLocalIrk (uint8_t * pIrk)
This function sets the local IRK used by the device.
Parameters
pIrk Pointer to IRK.
Returns
None.
Parameters
pCsrk Pointer to IRK.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
DmSecSetOob()
void DmSecSetOob (dmConnId_t connId, dmSecLescOobCfg_t * pCfg)
This function configures the DM to use OOB pairing for the given connection. The pRand and pConfirm contain the Random and Confirm values exchanged via out of band methods.
Parameters
connId ID of the connection.
pConfig Pointer to OOB configuration.
Returns
Pointer to IRK.
This function configures the DM to use OOB pairing for the given connection. The pRand and pConfirm contain the Random and Confirm values exchanged via out of band methods.
Parameters
connId ID of the connection
pCfg OOB Configuration
Returns
Pointer to IRK.
DmSecSlaveReq()
void DmSecSlaveReq (dmConnId_t connId, uint8_t auth)
This function is called by a slave device to request that the master initiates pairing or link encryption.
Parameters
connId DM connection ID.
auth Authentication flags.
Returns
None.
References smpDmSecurityReq_t::auth, wsfMsgHdr_t::event, smpDmSecurityReq_t::hdr, wsfMsgHdr_t::param, SMP_MSG_API_SECURITY_REQ, SmpDmMsgSend(), and WsfMsgAlloc().
DmSetDefaultPhy()
void DmSetDefaultPhy (uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys)
Set the preferred values for the transmitter PHY and receiver PHY for all subsequent connections.
Parameters
allPhys All PHYs preferences.
txPhys Preferred transmitter PHYs.
rxPhys Preferred receiver PHYs.
Returns
None.
References HciLeSetDefaultPhyCmd().
DmSetPhy()
void DmSetPhy (dmConnId_t connId, uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys, uint16_t phyOptions)
Set the PHY preferences for a given connection.
Parameters
connId Connection identifier.
allPhys All PHYs preferences.
txPhys Preferred transmitter PHYs.
rxPhys Preferred receiver PHYs.
phyOptions PHY options.
Returns
None.
References HciLeSetPhyCmd(), WsfTaskLock(), and WsfTaskUnlock().
DmSizeOfEvt()
uint16_t DmSizeOfEvt (dmEvt_t * pDmEvt)
Return size of a DM callback event.
Parameters
pDmEvt DM callback event.
Returns
Size of DM callback event.
References DM_CBACK_END, DM_CBACK_START, DM_NUM_PHYS, wsfMsgHdr_t::event, HCI_INIT_PHY_LE_1M_BIT, HCI_INIT_PHY_LE_2M_BIT, HCI_SCAN_PHY_LE_1M_BIT, HCI_SCAN_PHY_LE_2M_BIT, and dmEvt_t::hdr.
DmSmpCbackExec()
void DmSmpCbackExec (dmEvt_t * pDmEvt)
For internal use only. Execute DM callback from SMP procedures.
Parameters
pDmEvt Pointer to callback event data.
Returns
None.
References DM_CLIENT_ID_ATT, DM_SEC_ENCRYPT_IND, DM_SEC_PAIR_CMPL_IND, wsfMsgHdr_t::event, and dmEvt_t::hdr.
DmSmpEncryptReq()
void DmSmpEncryptReq (dmConnId_t connId, uint8_t secLevel, uint8_t * pKey)
For internal use only. This function is called by SMP to request encryption.
Parameters
connId DM connection ID.
secLevel Security level of pairing when key was exchanged.
pKey Pointer to key.
Returns
None.
DmSyncEnabled()
bool_t DmSyncEnabled (uint16_t syncHandle)
Get status of sync identified by the handle.
Parameters
syncHandle Synch handle.
Returns
TRUE if sync is enabled for that handle. FALSE, otherwise.
DmSyncEncrypted()
bool_t DmSyncEncrypted (uint16_t syncHandle)
Get the encryption mode of the Broadcast Isochronous Group (BIG) corresponding to the periodic advertising train identified by the sync handle.
Parameters
syncHandle Synch handle.
Returns
TRUE if sync encrypted. FALSE, otherwise.
Get the encryption mode of the Broadcast Isochronous Group (BIG) corresponding to the periodic advertising train identified by the sync handle.
Parameters
syncHandle Synch handle.
Returns
TRUE if sync encrypted. FALSE, otherwise.
DmSyncInitialRptEnable()
void DmSyncInitialRptEnable (bool_t enable)
DM enable or disable initial periodic advertisement reporting.
Parameters
enable TRUE to enable initial reporting, FALSE to disable initial reporting.
Returns
None.
DM enable or disable initial periodic advertisement reporting.
Parameters
enable TRUE to enable initial reporting, FALSE to disable initial reporting.
Returns
None.
DmSyncSetEncrypt()
void DmSyncSetEncrypt (uint16_t syncHandle, bool_t encrypt)
Set the encryption mode of the Broadcast Isochronous Group (BIG) corresponding to the periodic advertising train identified by the sync handle.
Parameters
syncHandle Synch handle.
encrypt FALSE (Unencrypted) or FALSE (Encrypted).
Returns
None.
Set the encryption mode of the Broadcast Isochronous Group (BIG) corresponding to the periodic advertising train identified by the sync handle.
Parameters
syncHandle Synch handle.
encrypt FALSE (Unencrypted) or FALSE (Encrypted).
Returns
None.
DmSyncStart()
dmSyncId_t DmSyncStart (uint8_t advSid, uint8_t advAddrType, const uint8_t * pAdvAddr, uint16_t skip, uint16_t syncTimeout)
Synchronize with periodic advertising from the given advertiser, and start receiving periodic advertising packets.
Note: The synchronization filter policy is used to determine whether the periodic advertiser list is used. If the periodic advertiser list is not used, the advertising SID, advertiser address type, and advertiser address parameters specify the periodic advertising device to listen to; otherwise these parameters are ignored.
Parameters
advSid Advertising SID.
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
skip Number of periodic advertising packets that can be skipped after successful receive.
syncTimeout Synchronization timeout.
Returns
Sync indentifier.
Note: The synchronization filter policy is used to determine whether the periodic advertiser list is used. If the periodic advertiser list is not used, the advertising SID, advertiser address type, and advertiser address parameters specify the periodic advertising device to listen to; otherwise these parameters are ignored.
Parameters
advSid Advertising SID.
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
skip Number of periodic advertising packets that can be skipped after successful receive.
syncTimeout Synchronization timeout.
Returns
Sync identifier.
References BdaCpy(), DM_SYNC_ID_NONE, WsfMsgAlloc(), WsfMsgSend(), WsfTaskLock(), and WsfTaskUnlock().
DmSyncStop()
void DmSyncStop (dmSyncId_t syncId)
Stop reception of the periodic advertising identified by the given sync identifier.
Parameters
syncId Sync identifier.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
DmWriteAuthPayloadTimeout()
void DmWriteAuthPayloadTimeout (dmConnId_t connId, uint16_t timeout)
Set authenticated payload timeout for a given connection.
Parameters
connId Connection identifier.
timeout Timeout period in units of 10ms.
Returns
None.
Parameters
connId Connection identifier.
timeout Timeout period in units of 10ms
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().