Cordio: STACK_ATTS_API
STACK_ATTS_API
Data Structures
struct attsAttr_t
struct attsCsfRec_t
struct attsGroup_t
struct attsCccSet_t
struct attsCccEvt_t
ATT Server Attribute Settings
Settings that may be set on each attribute.
#define ATTS_SET_UUID_128 0x01
#define ATTS_SET_WRITE_CBACK 0x02
#define ATTS_SET_READ_CBACK 0x04
#define ATTS_SET_VARIABLE_LEN 0x08
#define ATTS_SET_ALLOW_OFFSET 0x10
#define ATTS_SET_CCC 0x20
#define ATTS_SET_ALLOW_SIGNED 0x40
#define ATTS_SET_REQ_SIGNED 0x80
ATT Server Attribute Permissions
Permissions used to describe a attribute's security setting. These values can be set in any combination.
#define ATTS_PERMIT_READ 0x01
#define ATTS_PERMIT_READ_AUTH 0x02
#define ATTS_PERMIT_READ_AUTHORIZ 0x04
#define ATTS_PERMIT_READ_ENC 0x08
#define ATTS_PERMIT_WRITE 0x10
#define ATTS_PERMIT_WRITE_AUTH 0x20
#define ATTS_PERMIT_WRITE_AUTHORIZ 0x40
#define ATTS_PERMIT_WRITE_ENC 0x80
ATT Server Callbacks
typedef uint8_t(* attsReadCback_t) (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, attsAttr_t *pAttr)
typedef uint8_t(* attsWriteCback_t) (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
typedef uint8_t(* attsAuthorCback_t) (dmConnId_t connId, uint8_t permit, uint16_t handle)
typedef void(* attsCsfWriteCback_t) (dmConnId_t connId, uint8_t changeAwareState, uint8_t *pCsf)
typedef void(* attsCccCback_t) (attsCccEvt_t *pEvt)
ATT Server Functions
void AttsInit (void)
void AttsIndInit (void)
void AttsSignInit (void)
void AttsAuthorRegister (attsAuthorCback_t cback)
void AttsAddGroup (attsGroup_t *pGroup)
void AttsRemoveGroup (uint16_t startHandle)
void AttsCalculateDbHash (void)
bool_t AttsHashDatabaseString (uint8_t *pKey, uint8_t *pMsg, uint16_t msgLen)
uint8_t AttsSetAttr (uint16_t handle, uint16_t valueLen, uint8_t *pValue)
uint8_t AttsGetAttr (uint16_t handle, uint16_t *pLen, uint8_t **pValue)
void AttsHandleValueInd (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void AttsHandleValueNtf (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void AttsHandleValueIndZeroCpy (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void AttsHandleValueNtfZeroCpy (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void AttsCccRegister (uint8_t setLen, attsCccSet_t *pSet, attsCccCback_t cback)
void AttsCccInitTable (dmConnId_t connId, uint16_t *pCccTbl)
void AttsCccClearTable (dmConnId_t connId)
uint16_t AttsCccGet (dmConnId_t connId, uint8_t idx)
void AttsCccSet (dmConnId_t connId, uint8_t idx, uint16_t value)
uint16_t AttsCccEnabled (dmConnId_t connId, uint8_t idx)
uint8_t AttsGetCccTableLen (void)
void AttsContinueWriteReq (dmConnId_t connId, uint16_t handle, uint8_t status)
void AttsSetCsrk (dmConnId_t connId, uint8_t *pCsrk)
void AttsSetSignCounter (dmConnId_t connId, uint32_t signCounter)
uint32_t AttsGetSignCounter (dmConnId_t connId)
void AttsCsfInit (void)
void AttsCsfConnOpen (dmConnId_t connId, uint8_t changeAwareState, uint8_t *pCsf)
uint8_t AttsCsfWriteFeatures (dmConnId_t connId, uint16_t offset, uint16_t valueLen, uint8_t *pValue)
void AttsCsfGetFeatures (dmConnId_t connId, uint8_t *pCsfOut, uint8_t pCsfOutLen)
uint8_t AttsCsfGetClientChangeAwareState (dmConnId_t connId)
void AttsCsfSetClientChangeAwareState (dmConnId_t connId, uint8_t state)
void AttsCsfRegister (attsCsfWriteCback_t writeCback)
ATT Server Dynamic Service Subsystem Functions
void AttsDynInit (void)
void * AttsDynCreateGroup (uint16_t startHandle, uint16_t endHandle)
void AttsDynDeleteGroup (void *pSvcHandle)
void AttsDynRegister (void *pSvcHandle, attsReadCback_t readCback, attsWriteCback_t writeCback)
void AttsDynAddAttr (void *pSvcHandle, const uint8_t *pUuid, const uint8_t *pValue, uint16_t len, const uint16_t maxLen, uint8_t settings, uint8_t permissions)
void AttsDynAddAttrConst (void *pSvcHandle, const uint8_t *pUuid, const uint8_t *pValue, const uint16_t len, uint8_t settings, uint8_t permissions)
ATT Server Testing
void AttsErrorTest (uint8_t status)
EATT Server Functions
void EattsMultiValueNtf (dmConnId_t connId, uint8_t priority, uint16_t numTuples, eattTuple_t *pTupleList)
void EattsHandleValueInd (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void EattsHandleValueNtf (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void EattsHandleValueIndZeroCpy (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void EattsHandleValueNtfZeroCpy (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void EattsInit ()
Detailed Description
Data Structure Documentation
attsAttr_t
struct attsAttr_t
Attribute structure.
Data Fields
uint8_t const * pUuid
uint8_t * pValue
uint16_t * pLen
uint16_t maxLen
uint8_t settings
uint8_t permissions
attsCsfRec_t
struct attsCsfRec_t
Client supported features record structure.
Data Fields
uint8_t csf
uint8_t changeAwareState
Field Documentation
changeAwareState
uint8_t changeAwareState
Client awareness of GATT database changes
csf
uint8_t csf
Client supported features characteristic value
attsGroup_t
struct attsGroup_t
Attribute group.
Data Fields
struct attsGroup_tag * pNext
attsAttr_t * pAttr
attsReadCback_t readCback
attsWriteCback_t writeCback
uint16_t startHandle
uint16_t endHandle
attsCccSet_t
struct attsCccSet_t
Client characteristc configuration settings.
Data Fields
uint16_t handle
uint16_t valueRange
uint8_t secLevel
attsCccEvt_t
struct attsCccEvt_t
ATTS client characteristic configuration callback structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t handle
uint16_t value
uint8_t idx
Typedef Documentation
attsAuthorCback_t
typedef uint8_t(* attsAuthorCback_t) (dmConnId_t connId, uint8_t permit, uint16_t handle)
ATTS authorization callback type.
This callback function is executed when a read or write operation occurs and the security field of an attribute structure is set to ATTS_PERMIT_READ_AUTHORIZ or ATTS_PERMIT_WRITE_AUTHORIZ respectively.
Parameters
connId DM Connection ID.
permit Set to ATTS_PERMIT_WRITE for a writre operation or ATTS_PERMIT_READ for a read operation.
handle Attribute handle.
Returns
status of the operation. ATT_SUCCESS if successful, else if failure the ATT_ERR_AUTH is typically returned.
attsCccCback_t
typedef void(* attsCccCback_t) (attsCccEvt_t *pEvt)
ATTS client characteristic configuration callback.
Client characteristic configuration callback. This function is executed when a CCCD value changes. This happens when a peer device writes a new value to the CCCD or when a CCCD table is initialized by calling AttsCccInitTable.
Parameters
pEvt Pointer to callback structure.
Returns
None.
attsCsfWriteCback_t
typedef void(* attsCsfWriteCback_t) (dmConnId_t connId, uint8_t changeAwareState, uint8_t *pCsf)
ATTS client supported features write callback type.
This callback function is executed when the client supported features record for this client has been updated.
Parameters
connId DM Connection ID.
changeAwareState The state of awareness to a change, see attClientAwareStates.
pCsf Pointer to the client supported features value.
Returns
None.
attsReadCback_t
typedef uint8_t(* attsReadCback_t) (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, attsAttr_t *pAttr)
Attribute group read callback.
This is the attribute server read callback. It is executed on an attribute read operation if bitmask ATTS_SET_READ_CBACK is set in the settings field of the attribute structure. For a read operation, if the operation is successful the function must set pAttr->pValue to the data to be read. In addition, if the attribute is variable length then pAttr->pLen must be set as well.
Parameters
connId DM connection ID.
handle Attribute handle.
operation Operation type.
offset Read data offset.
pAttr Pointer to attribute structure.
Returns
status of the operation. ATT_SUCCESS if successful.
attsWriteCback_t
typedef uint8_t(* attsWriteCback_t) (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
Attribute group write callback.
This is the attribute server write callback. It is executed on an attribute write operation if bitmask ATTS_SET_WRITE_CBACK is set in the settings field of the attribute structure.
Parameters
connId DM connection ID.
handle Attribute handle.
operation Operation type.
offset Write data offset.
len Length of data to write.
pValue Pointer to data to write.
pAttr Pointer to attribute structure.
Returns
status of operation. ATT_SUCCESS if successful.
Function Documentation
AttsAddGroup()
void AttsAddGroup (attsGroup_t * pGroup)
Add an attribute group to the attribute server.
Parameters
pGroup Pointer to an attribute group structure.
Returns
None.
References attsGroup_t::pNext, attsGroup_t::startHandle, WsfQueueInsert(), and WsfTaskLock().
AttsAuthorRegister()
void AttsAuthorRegister (attsAuthorCback_t cback)
Register an authorization callback with the attribute server.
Parameters
cback Client callback function.
Returns
None.
AttsCalculateDbHash()
void AttsCalculateDbHash (void)
Calculate database hash from the GATT database.
Returns
None.
References ATTS_SET_UUID_128, AttsHashDatabaseString(), BYTES_TO_UINT16, attsGroup_t::endHandle, attsGroup_t::pAttr, attsAttr_t::pLen, attsGroup_t::pNext, attsAttr_t::pUuid, attsAttr_t::pValue, attsAttr_t::settings, attsGroup_t::startHandle, UINT16_TO_BSTREAM, WSF_ASSERT, and WsfBufAlloc().
AttsCccClearTable()
void AttsCccClearTable (dmConnId_t connId)
Clear and deallocate the client characteristic configuration descriptor value table for a connection. This function must be called when a connection is closed.
Parameters
connId DM connection ID.
Returns
None.
AttsCccEnabled()
uint16_t AttsCccEnabled (dmConnId_t connId, uint8_t idx)
Check if a client characteristic configuration descriptor is enabled and if the characteristic's security level has been met.
Parameters
connId DM connection ID.
idx Index of descriptor in CCC descriptor handle table.
Returns
Value of the descriptor if security level is met, otherwise zero.
References AttsCccGet(), DmConnSecLevel(), and WSF_ASSERT.
AttsCccGet()
uint16_t AttsCccGet (dmConnId_t connId, uint8_t idx)
Get the value of a client characteristic configuration descriptor by its index. If not found, return zero.
Parameters
connId DM connection ID.
idx Index of descriptor in CCC descriptor handle table.
Returns
Value of the descriptor.
References WSF_ASSERT.
AttsCccInitTable()
void AttsCccInitTable (dmConnId_t connId, uint16_t * pCccTbl)
Initialize the client characteristic configuration descriptor value table for a connection. The table is initialized with the values from pCccTbl. If pCccTbl is NULL the table will be initialized to zero.
This function must be called when a connection is established or when a device is bonded.
Parameters
connId DM connection ID.
pCccTbl Pointer to the descriptor value array. The length of the array must equal the value of setLen passed to AttsCccRegister().
Returns
None.
Initialize the client characteristic configuration descriptor value table for a connection. The table is initialized with the values from pCccTbl. If pCccTbl is NULL the table will be initialized to zero.
Parameters
connId DM connection ID.
pCccTbl Pointer to the descriptor value array. The length of the array must equal the value of setLen passed to AttsCccRegister().
Returns
None.
References ATT_HANDLE_NONE.
AttsCccRegister()
void AttsCccRegister (uint8_t setLen, attsCccSet_t * pSet, attsCccCback_t cback)
Register the utility service for managing client characteristic configuration descriptors. This function is typically called once on system initialization.
Parameters
setLen Length of settings array.
pSet Array of CCC descriptor settings.
cback Client callback function.
Returns
None.
AttsCccSet()
void AttsCccSet (dmConnId_t connId, uint8_t idx, uint16_t value)
Set the value of a client characteristic configuration descriptor by its index.
Parameters
connId DM connection ID.
idx Index of descriptor in CCC descriptor handle table.
value Value of the descriptor.
Returns
None.
References WSF_ASSERT.
AttsContinueWriteReq()
void AttsContinueWriteReq (dmConnId_t connId, uint16_t handle, uint8_t status)
Send a response to a pending write request. For use with ATT_RSP_PENDING.
Parameters
connId Connection ID.
handle Attribute handle.
status Status of the write request.
Returns
None.
Note
When a higher layer returns ATT_RSP_PENDING to an ATT write callback indicating the response status is pending, the higher layer must subsequently call this function with the status of the write request.
References ATT_PDU_WRITE_REQ, ATT_PDU_WRITE_RSP, ATT_WRITE_RSP_LEN, L2C_PAYLOAD_START, and UINT8_TO_BSTREAM.
AttsCsfConnOpen()
void AttsCsfConnOpen (dmConnId_t connId, uint8_t changeAwareState, uint8_t * pCsf)
Initialize the client supported features for a connection.
Parameters
connId DM connection ID.
changeAwareState The state of awareness to a change in the database.
pCsf Pointer to the client supported features value to cache. NULL or buffer of length ATT_CSF_LEN.
Returns
None.
References ATT_CSF_LEN.
AttsCsfGetClientChangeAwareState()
uint8_t AttsCsfGetClientChangeAwareState (dmConnId_t connId)
Get client state of awareness to a change in the database.
Parameters
connId DM connection ID.
Returns
Client's change-aware state. See attClientAwareStates.
AttsCsfGetFeatures()
void AttsCsfGetFeatures (dmConnId_t connId, uint8_t * pCsfOut, uint8_t pCsfOutLen)
Get client supported feature record.
Parameters
connId DM connection ID.
pCsfOut Output parameter for client supported features buffer.
pCsfOutLen Length of output parameter buffer.
Returns
None.
References ATT_CSF_LEN.
AttsCsfInit()
void AttsCsfInit (void)
Initialize ATTS client supported features module.
Returns
None.
AttsCsfRegister()
void AttsCsfRegister (attsCsfWriteCback_t writeCback)
Register callback.
Parameters
writeCback Application callback for when client supported features record is updated.
Returns
None.
Parameters
writeCback Application callback for when features or status change.
Returns
None.
AttsCsfSetClientChangeAwareState()
void AttsCsfSetClientChangeAwareState (dmConnId_t connId, uint8_t state)
Update a client's state of awareness to a change in the database.
Parameters
connId DM connection ID. if DM_CONN_ID_NONE, sets the state for all connected clients.
state The state of awareness to a change, see attClientAwareStates.
Returns
None.
Note
A callback to application is not needed as it is expected the caller (i.e. the application) will have updated all persistent records prior to calling this function.
Parameters
connId DM connection ID. if DM_CONN_ID_NONE, sets the state for all connected clients.
state The state of awareness to a change, see attClientAwareStates.
Returns
None.
Note
A callback to application is not needed as it is expected the caller (i.e. the application) will have updated all persistent records prior to calling this function.
References ATTS_CLIENT_CHANGE_AWARE_DB_READ_PENDING, ATTS_CLIENT_CHANGE_PENDING_AWARE, DM_CONN_ID_NONE, and DM_CONN_MAX.
AttsCsfWriteFeatures()
uint8_t AttsCsfWriteFeatures (dmConnId_t connId, uint16_t offset, uint16_t valueLen, uint8_t * pValue)
GATT write of client supported feature characteristic value.
Parameters
connId DM connection ID.
offset offset into csf characteristic.
valueLen length of write in bytes.
pValue Pointer to client's supported features characteristic value.
Returns
ATT_SUCCESS is successful, ATT_ERR_VALUE_NOT_ALLOWED if any supported features are flipped from 1 to 0.
References ATT_CSF_LEN, ATT_ERR_LENGTH, ATT_ERR_VALUE_NOT_ALLOWED, ATT_SUCCESS, ATTS_CSF_ALL_FEATURES, attsCsfRec_t::changeAwareState, and attsCsfRec_t::csf.
AttsDynAddAttr()
void AttsDynAddAttr (void * pSvcHandle, const uint8_t * pUuid, const uint8_t * pValue, uint16_t len, const uint16_t maxLen, uint8_t settings, uint8_t permissions)
Dynamically add an attribute to a dynamic ATT Services at runtime.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
pUuid Constant UUID
pValue Initial value of attribute (copied into attribute memory)
len Length of pValue in bytes
maxLen Maximum length of the attribute in bytes
settings Attribute settings
permissions Attribute permissions
Returns
None.
Dynamically add an attribute to a dynamic ATT Services at runtime.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
pUuid Constant UUID
pValue Initial value of attribute (copied into attribute memory)
len Length of pValue in bytes
maxLen Maximum length of the attribute in bytes
settings Attribute settings
permissions Attribute permissions
Returns
None.
Note
It is recommended this function only be used when no connections are open and the device is not in a connectable mode.
References AttsAddGroup(), attsAttr_t::maxLen, attsAttr_t::permissions, attsAttr_t::pLen, attsAttr_t::pUuid, attsAttr_t::pValue, attsAttr_t::settings, and WSF_ASSERT.
AttsDynAddAttrConst()
void AttsDynAddAttrConst (void * pSvcHandle, const uint8_t * pUuid, const uint8_t * pValue, const uint16_t len, uint8_t settings, uint8_t permissions)
Dynamically add an attribute with a constant value to a dynamic ATT Services at runtime.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
pUuid Constant UUID
pValue Pointer to constant attribute memory
len Length of pValue in bytes
settings Attribute settings
permissions Attribute permissions
Returns
None.
Dynamically add an attribute with a constant value to a dynamic ATT Services at runtime.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
pUuid Constant UUID
pValue Pointer to constant attribute memory
len Length of pValue in bytes
settings Attribute settings
permissions Attribute permissions
Returns
None.
Note
It is recommended this function only be used when no connections are open and the device is not in a connectable mode.
References AttsAddGroup(), attsAttr_t::maxLen, attsAttr_t::permissions, attsAttr_t::pLen, attsAttr_t::pUuid, attsAttr_t::pValue, attsAttr_t::settings, and WSF_ASSERT.
AttsDynCreateGroup()
void* AttsDynCreateGroup (uint16_t startHandle, uint16_t endHandle)
Dynamically create an ATT Service at runtime.
Parameters
startHandle Starting attribute handle in the service
endHandle Last attribute handle in the service
Returns
Service Handle.
Parameters
startHandle Starting attribute handle in the service
endHandle Last attribute handle in the service
Returns
Service Handle.
Note
It is recommended this function only be used when no connections are open and the device is not in a connectable mode.
References WSF_ASSERT.
AttsDynDeleteGroup()
void AttsDynDeleteGroup (void * pSvcHandle)
Dynamically delete an ATT Service at runtime.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
Returns
None.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
Returns
None.
Note
It is recommended this function only be used when no connections are open and the device is not in a connectable mode.
References AttsDynInit(), AttsRemoveGroup(), and WSF_ASSERT.
AttsDynInit()
void AttsDynInit (void)
Initialize the Dynamic ATT Service subsystem.
Returns
None.
Parameters
None
Returns
None.
AttsDynRegister()
void AttsDynRegister (void * pSvcHandle, attsReadCback_t readCback, attsWriteCback_t writeCback)
Register callback functions for a dynamic ATT Service at runtime.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
readCback Read callback function
writeCback Write callback function
Returns
None.
Parameters
pSvcHandle Service handle returned by AttsDynCreateGroup
readCback Read callback function.
writeCback Write callback function.
Returns
None.
Note
It is recommended this function only be used when no connections are open and the device is not in a connectable mode.
References WSF_ASSERT.
AttsErrorTest()
void AttsErrorTest (uint8_t status)
For testing purposes only.
Parameters
status ATT status
Returns
None.
AttsGetAttr()
uint8_t AttsGetAttr (uint16_t handle, uint16_t * pLen, uint8_t ** pValue)
Get an attribute value in the attribute server.
Parameters
handle Attribute handle.
pLen Returned attribute length pointer.
pValue Returned attribute value pointer.
Returns
ATT_SUCCESS if successful otherwise error.
This function returns the attribute length in pLen and a pointer to the attribute value in pValue.
Get an attribute value in the attribute server.
Parameters
handle Attribute handle.
pLen Returned attribute length pointer.
pValue Returned attribute value pointer.
Returns
ATT_SUCCESS if successful or other error code if failure.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, attsAttr_t::pLen, and attsAttr_t::pValue.
AttsGetCccTableLen()
uint8_t AttsGetCccTableLen (void)
Get number of CCC entries in table.
Returns
Number of CCC entries in table.
Parameters
None
Returns
Number of CCC entries in table.
AttsGetSignCounter()
uint32_t AttsGetSignCounter (dmConnId_t connId)
Get the current value peer's sign counter on this connection. This function is typically called from the ATT connection callback when the connection is closed so the application can store the sign counter for use on future connections.
Parameters
connId DM connection ID.
Returns
Sign counter.
AttsHandleValueInd()
void AttsHandleValueInd (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Indication.
Parameters
connId DM connection ID.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_IND.
AttsHandleValueIndZeroCpy()
void AttsHandleValueIndZeroCpy (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Indication without copying the attribute value data.
Note: attribute value buffer 'pValue' must be allocated with AttMsgAlloc().
Parameters
connId DM connection ID.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_IND.
AttsHandleValueNtf()
void AttsHandleValueNtf (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Notification.
Parameters
connId DM connection ID.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_NTF.
AttsHandleValueNtfZeroCpy()
void AttsHandleValueNtfZeroCpy (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Notification without copying the attribute value data.
Note: attribute value buffer 'pValue' must be allocated with AttMsgAlloc().
Parameters
connId DM connection ID.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_NTF.
AttsHashDatabaseString()
bool_t AttsHashDatabaseString (uint8_t * pKey, uint8_t * pMsg, uint16_t msgLen)
Create hash from the database string.
Parameters
pKey Key for hashing.
pMsg Plaintext to hash.
msgLen Length of Plaintext data.
Returns
TRUE if successful, FALSE if not.
AttsIndInit()
void AttsIndInit (void)
Initialize ATT server for indications/notifications.
Returns
None.
References DM_CONN_MAX, and WSF_ASSERT.
AttsInit()
void AttsInit (void)
Initialize ATT server.
Returns
None.
References DM_CONN_MAX, and WSF_QUEUE_INIT.
AttsRemoveGroup()
void AttsRemoveGroup (uint16_t startHandle)
Remove an attribute group from the attribute server.
Parameters
startHandle Start handle of attribute group to be removed.
Returns
None.
References attsGroup_t::pNext, attsGroup_t::startHandle, WsfQueueRemove(), and WsfTaskLock().
AttsSetAttr()
uint8_t AttsSetAttr (uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Set an attribute value in the attribute server.
Parameters
handle Attribute handle.
valueLen Attribute length.
pValue Attribute value.
Returns
ATT_SUCCESS if successful otherwise error.
References ATT_ERR_LENGTH, ATT_ERR_NOT_FOUND, ATT_SUCCESS, ATTS_SET_VARIABLE_LEN, attsAttr_t::maxLen, attsAttr_t::pLen, attsAttr_t::pValue, attsAttr_t::settings, WsfTaskLock(), and WsfTaskUnlock().
AttsSetCsrk()
void AttsSetCsrk (dmConnId_t connId, uint8_t * pCsrk)
Set the peer's data signing key on this connection. This function is typically called from the ATT connection callback when the connection is established. The caller is responsible for maintaining the memory that contains the key.
Parameters
connId DM connection ID.
pCsrk Pointer to data signing key (CSRK).
Returns
None.
AttsSetSignCounter()
void AttsSetSignCounter (dmConnId_t connId, uint32_t signCounter)
Set the peer's sign counter on this connection. This function is typically called from the ATT connection callback when the connection is established. ATT maintains the value of the sign counter internally and sets the value when a signed packet is successfully received.
Parameters
connId DM connection ID.
signCounter Sign counter.
Returns
None.
AttsSignInit()
void AttsSignInit (void)
Initialize ATT server for data signing.
Returns
None.
References WSF_QUEUE_INIT.
EattsHandleValueInd()
void EattsHandleValueInd (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Indication.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_IND.
EattsHandleValueIndZeroCpy()
void EattsHandleValueIndZeroCpy (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Indication without copying the attribute value data.
Note: attribute value buffer 'pValue' must be allocated with AttMsgAlloc().
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_IND.
EattsHandleValueNtf()
void EattsHandleValueNtf (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Notification.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_NTF.
EattsHandleValueNtfZeroCpy()
void EattsHandleValueNtfZeroCpy (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Send an attribute protocol Handle Value Notification without copying the attribute value data.
Note: attribute value buffer 'pValue' must be allocated with AttMsgAlloc().
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_VALUE_NTF.
EattsInit()
void EattsInit ()
Initialize the Enhanced ATT Server.
Returns
None
EattsMultiValueNtf()
void EattsMultiValueNtf (dmConnId_t connId, uint8_t priority, uint16_t numTuples, eattTuple_t * pTupleList)
Send multiple attribute protocol Handle Value Notification.
Parameters
connId DM connection ID.
priority Operation priority.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
Parameters
connId DM connection ID.
priority Operation priority.
numTuples The number of tuples.
pTupleList Pointer to a list of tuples.
Returns
None.