Cordio: WSF_UTIL_API
WSF_UTIL_API
Data Structures
struct terminalCommand_t
Macros
#define BDA_ADDR_LEN 6
#define BDA_ADDR_STR_LEN (BDA_ADDR_LEN * 2)
#define BDA_ADDR_IS_RPA(bda) (((bda)[5] & 0xC0) == 0x40)
#define BDA_ADDR_IS_NRPA(bda) (((bda)[5] & 0xC0) == 0x00)
#define BDA_ADDR_IS_STATIC(bda) (((bda)[5] & 0xC0) == 0xC0)
#define BDA64_ADDR_IS_RPA(bda64) ((((bda64) >> 40) & 0xC0) == 0x40)
#define BDA64_ADDR_IS_NRPA(bda64) ((((bda64) >> 40) & 0xC0) == 0x00)
#define BDA64_ADDR_IS_STATIC(bda64) ((((bda64) >> 40) & 0xC0) == 0xC0)
#define CALC128_LEN 16
#define PRINT_ATTRIBUTE(a, b)
#define TERMINAL_MAX_ARGC 8u
#define TERMINAL_MAX_COMMAND_LEN 100u
#define TERMINAL_PRINTF_MAX_LEN 256u
#define TERMINAL_STRING_PROMPT "> "
#define TERMINAL_STRING_ERROR "ERROR: "
#define TERMINAL_STRING_USAGE "USAGE: "
#define TERMINAL_STRING_NEW_LINE "\r\n"
#define WSTR_IS_HEX_FORMAT(c)
#define WSTR_IS_BIN_FORMAT(c) (((char)(c)[0] == '0') && ((char)(c)[1] == 'b'))
Typedefs
typedef uint8_t bdAddr_t[BDA_ADDR_LEN]
typedef uint8_t(* terminalHandler_t) (uint32_t argc, char **argv)
typedef bool_t(* terminalUartTx_t) (const uint8_t *pBuf, uint32_t len)
Enumerations
enum
Functions
void BdaCpy (uint8_t *pDst, const uint8_t *pSrc)
bool_t BdaCmp (const uint8_t *pAddr1, const uint8_t *pAddr2)
uint8_t * BdaClr (uint8_t *pDst)
bool_t BdaIsZeros (const uint8_t *pAddr)
char * Bda2Str (const uint8_t *pAddr)
uint64_t BstreamToBda64 (const uint8_t *p)
uint64_t BstreamToUint64 (const uint8_t *p)
void Bda64ToBstream (uint8_t *p, uint64_t bda)
void Uint64ToBstream (uint8_t *p, uint64_t n)
void Calc128Cpy (uint8_t *pDst, uint8_t *pSrc)
void Calc128Cpy64 (uint8_t *pDst, uint8_t *pSrc)
void Calc128Xor (uint8_t *pDst, uint8_t *pSrc)
uint32_t CalcCrc32 (uint32_t crcInit, uint32_t len, const uint8_t *pBuf)
uint32_t PrintVsn (char *pStr, uint32_t size, const char *pFmt, va_list ap) PRINT_ATTRIBUTE(3
void TerminalInit (wsfHandlerId_t handlerId)
void TerminalRegisterUartTxFunc (terminalUartTx_t uartTxFunc)
void TerminalRegisterCommand (terminalCommand_t *pCommand)
void TerminalHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
void TerminalRx (uint8_t dataByte)
void TerminalTxStr (const char *pStr)
void TerminalTxChar (char c)
void TerminalTxPrint (const char *pStr,...)
void TerminalTx (const uint8_t *pData, uint16_t len)
void WstrnCpy (char *pBuf, const char *pData, uint8_t n)
void WStrReverseCpy (uint8_t *pBuf1, const uint8_t *pBuf2, uint16_t len)
void WStrReverse (uint8_t *pBuf, uint8_t len)
void WStrFormatHex (char *pBuf, uint32_t val, uint8_t len)
void WStrHexToArray (const char *pStr, uint8_t *pBuf, uint16_t len)
Variables
const uint8_t calc128Zeros [CALC128_LEN]
Macros for converting a little endian byte buffer to integers.
#define BYTES_TO_INT16(n, p) {n = ((int16_t)(p)[0] + ((int16_t)(p)[1] << 8));}
#define BYTES_TO_UINT16(n, p) {n = ((uint16_t)(p)[0] + ((uint16_t)(p)[1] << 8));}
#define BYTES_TO_UINT24(n, p)
#define BYTES_TO_UINT32(n, p)
#define BYTES_TO_UINT40(n, p)
#define BYTES_TO_UINT64(n, p)
Macros for converting a big endian byte buffer to integers.
#define BYTES_BE_TO_UINT16(n, p) {n = ((uint16_t)(p)[1] + ((uint16_t)(p)[0] << 8));}
#define BYTES_BE_TO_UINT24(n, p)
#define BYTES_BE_TO_UINT32(n, p)
Macros for converting little endian integers to array of bytes
#define UINT16_TO_BYTES(n) ((uint8_t) (n)), ((uint8_t)((n) >> 8))
#define UINT32_TO_BYTES(n) ((uint8_t) (n)), ((uint8_t)((n) >> 8)), ((uint8_t)((n) >> 16)), ((uint8_t)((n) >> 24))
Macros for converting big endian integers to array of bytes
#define UINT16_TO_BE_BYTES(n) ((uint8_t)((n) >> 8)), ((uint8_t) (n))
#define UINT24_TO_BE_BYTES(n) ((uint8_t)((n) >> 16)), ((uint8_t)((n) >> 8)), ((uint8_t) (n))
#define UINT32_TO_BE_BYTES(n) ((uint8_t)((n) >> 24)), ((uint8_t)((n) >> 16)), ((uint8_t)((n) >> 8)), ((uint8_t) (n))
Macros for converting little endian integers to single bytes
#define UINT16_TO_BYTE0(n) ((uint8_t) (n))
#define UINT16_TO_BYTE1(n) ((uint8_t) ((n) >> 8))
#define UINT32_TO_BYTE0(n) ((uint8_t) (n))
#define UINT32_TO_BYTE1(n) ((uint8_t) ((n) >> 8))
#define UINT32_TO_BYTE2(n) ((uint8_t) ((n) >> 16))
#define UINT32_TO_BYTE3(n) ((uint8_t) ((n) >> 24))
Macros for converting a little endian byte stream to integers, with increment.
#define BSTREAM_TO_INT8(n, p) {n = (int8_t)(*(p)++);}
#define BSTREAM_TO_UINT8(n, p) {n = (uint8_t)(*(p)++);}
#define BSTREAM_TO_INT16(n, p) {BYTES_TO_INT16(n, p); p += 2;}
#define BSTREAM_TO_UINT16(n, p) {BYTES_TO_UINT16(n, p); p += 2;}
#define BSTREAM_TO_UINT24(n, p) {BYTES_TO_UINT24(n, p); p += 3;}
#define BSTREAM_TO_UINT32(n, p) {BYTES_TO_UINT32(n, p); p += 4;}
#define BSTREAM_TO_UINT40(n, p) {BYTES_TO_UINT40(n, p); p += 5;}
#define BSTREAM_TO_UINT64(n, p) {n = BstreamToUint64(p); p += 8;}
#define BSTREAM_TO_BDA(bda, p) {BdaCpy(bda, p); p += BDA_ADDR_LEN;}
#define BSTREAM_TO_BDA64(bda, p) {bda = BstreamToBda64(p); p += BDA_ADDR_LEN;}
Macros for converting a big endian byte stream to integers, with increment.
#define BSTREAM_BE_TO_UINT16(n, p) {BYTES_BE_TO_UINT16(n, p); p += 2;}
#define BSTREAM_BE_TO_UINT24(n, p) {BYTES_BE_TO_UINT24(n, p); p += 3;}
Macros for converting integers to a little endian byte stream, with increment.
#define UINT8_TO_BSTREAM(p, n) {*(p)++ = (uint8_t)(n);}
#define UINT16_TO_BSTREAM(p, n) {*(p)++ = (uint8_t)(n); *(p)++ = (uint8_t)((n) >> 8);}
#define UINT24_TO_BSTREAM(p, n)
#define UINT32_TO_BSTREAM(p, n)
#define UINT40_TO_BSTREAM(p, n)
#define UINT64_TO_BSTREAM(p, n) {Uint64ToBstream(p, n); p += sizeof(uint64_t);}
#define BDA_TO_BSTREAM(p, bda) {BdaCpy(p, bda); p += BDA_ADDR_LEN;}
#define BDA64_TO_BSTREAM(p, bda) {Bda64ToBstream(p, bda); p += BDA_ADDR_LEN;}
Macros for converting integers to a big endian byte stream, with increment.
#define UINT16_TO_BE_BSTREAM(p, n) {*(p)++ = (uint8_t)((n) >> 8); *(p)++ = (uint8_t)(n);}
#define UINT32_TO_BE_BSTREAM(p, n)
Macros for converting integers to a little endian byte stream, without increment.
#define UINT16_TO_BUF(p, n) {(p)[0] = (uint8_t)(n); (p)[1] = (uint8_t)((n) >> 8);}
#define UINT24_TO_BUF(p, n)
#define UINT32_TO_BUF(p, n)
#define UINT40_TO_BUF(p, n)
Macros for converting integers to a big endian byte stream, without increment.
#define UINT16_TO_BE_BUF(p, n) {(p)[0] = (uint8_t)((n) >> 8); (p)[1] = (uint8_t)(n);}
#define UINT24_TO_BE_BUF(p, n)
#define UINT32_TO_BE_BUF(p, n)
Macros for comparing a little endian byte buffer to integers.
#define BYTES_UINT16_CMP(p, n) ((p)[1] == UINT16_TO_BYTE1(n) && (p)[0] == UINT16_TO_BYTE0(n))
Macros for IEEE FLOAT type: exponent = byte 3, mantissa = bytes 2-0
#define FLT_TO_UINT32(m, e) ((m) | ((int32_t)(e) * 16777216))
#define UINT32_TO_FLT(m, e, n) {m = UINT32_TO_FLT_M(n); e = UINT32_TO_FLT_E(n);}
#define UINT32_TO_FLT_M(n)
#define UINT32_TO_FLT_E(n) ((int8_t)(n >> 24))
Macros for IEEE SFLOAT type: exponent = bits 15-12, mantissa = bits 11-0
#define SFLT_TO_UINT16(m, e) ((m) | (0xF000 & ((int16_t)(e) * 4096)))
#define UINT16_TO_SFLT(m, e, n) {m = UINT16_TO_SFLT_M(n); e = UINT16_TO_SFLT_E(n);}
#define UINT16_TO_SFLT_M(n)
#define UINT16_TO_SFLT_E(n)
Detailed Description
Data Structure Documentation
terminalCommand_t
struct terminalCommand_t
Terminal command.
Data Fields
struct terminalCommand_tag * pNext
const char * pName
const char * pHelpStr
terminalHandler_t handler
Macro Definition Documentation
WSTR_IS_BIN_FORMAT
#define WSTR_IS_BIN_FORMAT (c) (((char)(c)[0] == '0') && ((char)(c)[1] == 'b'))
Binary format '0b' check
WSTR_IS_HEX_FORMAT
#define WSTR_IS_HEX_FORMAT (c)
Value:
(((char)(c)[0] == '0') && \
                               (((char)(c)[1] == 'x') || ((char)(c)[1] == 'X')))
HEX format '0x' or '0X' check
Typedef Documentation
terminalHandler_t
typedef uint8_t(* terminalHandler_t) (uint32_t argc, char **argv)
Handler for a terminal command.
Parameters
argc The number of arguments passed to the command.
argv The array of arguments; the 0th argument is the command.
Returns
Error code.
terminalUartTx_t
typedef bool_t(* terminalUartTx_t) (const uint8_t *pBuf, uint32_t len)
Handler for transmit.
Parameters
pBuf Buffer to transmit.
len Number of bytes to transmit.
Enumeration Type Documentation
anonymous enum
anonymous enum
Terminal command error codes.
Enumerator
TERMINAL_ERROR_OK
Command completed.
TERMINAL_ERROR_BAD_ARGUMENTS
ERROR: Invalid argument(s)
TERMINAL_ERROR_TOO_FEW_ARGUMENTS
ERROR: Too few arguments.
TERMINAL_ERROR_TOO_MANY_ARGUMENTS
ERROR: Too many arguments.
TERMINAL_ERROR_EXEC
Command completed with execution error.
Function Documentation
Bda2Str()
char* Bda2Str (const uint8_t * pAddr)
Convert a BD address to a string.
Parameters
pAddr Pointer to BD address.
Returns
Pointer to string.
References BDA_ADDR_LEN, and BDA_ADDR_STR_LEN.
Bda64ToBstream()
void Bda64ToBstream (uint8_t * p, uint64_t bda)
Convert BDA64 to bstream.
Parameters
p Bstream pointer.
bda uint64_t BDA.
BdaClr()
uint8_t* BdaClr (uint8_t * pDst)
Set a BD address to all zeros.
Parameters
pDst Pointer to destination.
Returns
pDst + BDA_ADDR_LEN
References BDA_ADDR_LEN.
BdaCmp()
bool_t BdaCmp (const uint8_t * pAddr1, const uint8_t * pAddr2)
Compare two BD addresses.
Parameters
pAddr1 First address.
pAddr2 Second address.
Returns
TRUE if addresses match, FALSE otherwise.
BdaCpy()
void BdaCpy (uint8_t * pDst, const uint8_t * pSrc)
Copy a BD address from source to destination.
Parameters
pDst Pointer to destination.
pSrc Pointer to source.
References BDA_ADDR_LEN.
BdaIsZeros()
bool_t BdaIsZeros (const uint8_t * pAddr)
Check if a BD address is all zeros.
Parameters
pAddr Pointer to address.
Returns
TRUE if address is all zeros, FALSE otherwise.
BstreamToBda64()
uint64_t BstreamToBda64 (const uint8_t * p)
Convert bstream to BDA64.
Parameters
p Bstream pointer.
Returns
Resulting BDA64 number.
BstreamToUint64()
uint64_t BstreamToUint64 (const uint8_t * p)
Convert bstream to uint64_t.
Parameters
p Bstream pointer.
Returns
Resulting uint64_t number.
Calc128Cpy()
void Calc128Cpy (uint8_t * pDst, uint8_t * pSrc)
Copy a 128-bit integer from source to destination.
Parameters
pDst Pointer to destination.
pSrc Pointer to source.
References CALC128_LEN.
Calc128Cpy64()
void Calc128Cpy64 (uint8_t * pDst, uint8_t * pSrc)
Copy a 64-bit integer from source to destination.
Parameters
pDst Pointer to destination.
pSrc Pointer to source.
References CALC128_LEN.
Calc128Xor()
void Calc128Xor (uint8_t * pDst, uint8_t * pSrc)
Exclusive-or two 128-bit integers and return the result in pDst.
Parameters
pDst Pointer to destination.
pSrc Pointer to source.
References CALC128_LEN.
CalcCrc32()
uint32_t CalcCrc32 (uint32_t crcInit, uint32_t len, const uint8_t * pBuf)
Calculate the CRC-32 of the given buffer.
Parameters
crcInit Initial value of the CRC.
len Length of the buffer.
pBuf Buffer to compute the CRC.
This routine was originally generated with crcmod.py using the following parameters:
polynomial 0x104C11DB7
bit reverse algorithm
PrintVsn()
uint32_t PrintVsn (char * pStr, uint32_t size, const char * pFmt, va_list ap)
Print a trace message.
Parameters
pStr Storage for formatted string.
size Maximum number of characters to store.
pFmt Format string.
ap Arguments.
Returns
Number of characters stored.
TerminalHandler()
void TerminalHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
Handler for terminal messages.
Parameters
event WSF event mask.
pMsg WSF message.
References TERMINAL_STRING_PROMPT, and TerminalTxStr().
TerminalInit()
void TerminalInit (wsfHandlerId_t handlerId)
Initialize terminal.
Parameters
handlerId Handler ID for TerminalHandler().
TerminalRegisterCommand()
void TerminalRegisterCommand (terminalCommand_t * pCommand)
Register command with terminal.
Parameters
pCommand Command.
References terminalCommand_t::handler, terminalCommand_t::pName, terminalCommand_t::pNext, TERMINAL_ERROR_BAD_ARGUMENTS, TERMINAL_ERROR_EXEC, TERMINAL_ERROR_OK, TERMINAL_ERROR_TOO_FEW_ARGUMENTS, TERMINAL_ERROR_TOO_MANY_ARGUMENTS, TERMINAL_MAX_ARGC, TERMINAL_STRING_ERROR, TERMINAL_STRING_NEW_LINE, and TerminalTxStr().
TerminalRegisterUartTxFunc()
void TerminalRegisterUartTxFunc (terminalUartTx_t uartTxFunc)
Register the UART Tx Function for the platform.
Parameters
uartTxFunc UART Tx callback function.
TerminalRx()
void TerminalRx (uint8_t dataByte)
Called by application when a data byte is received.
Parameters
dataByte received byte
dataByte Received byte.
References TERMINAL_STRING_NEW_LINE, TerminalTxStr(), and WsfSetEvent().
TerminalTx()
void TerminalTx (const uint8_t * pData, uint16_t len)
Application function to transmit data..
Parameters
pData Data.
len Length of data, in bytes.
Application function to transmit data..
Parameters
pBuf Buffer to transmit.
len Length of buffer in octets.
References TERMINAL_ERROR_TOO_FEW_ARGUMENTS.
TerminalTxChar()
void TerminalTxChar (char c)
Called by application to transmit character.
Parameters
c Character.
References TerminalTx().
TerminalTxPrint()
void TerminalTxPrint (const char * pStr, ...)
Called by application to print formatted data.
Parameters
pStr Message format string
... Additional arguments, printf-style
References terminalCommand_t::pHelpStr, terminalCommand_t::pNext, PrintVsn(), TERMINAL_ERROR_OK, TERMINAL_ERROR_TOO_MANY_ARGUMENTS, TERMINAL_PRINTF_MAX_LEN, TERMINAL_STRING_NEW_LINE, TerminalTx(), and TerminalTxStr().
TerminalTxStr()
void TerminalTxStr (const char * pStr)
Called by application to transmit string.
Parameters
pStr String.
References TerminalTx().
Uint64ToBstream()
void Uint64ToBstream (uint8_t * p, uint64_t n)
Convert uint64_t to bstream.
Parameters
p Bstream pointer.
n uint64_t number.
WStrFormatHex()
void WStrFormatHex (char * pBuf, uint32_t val, uint8_t len)
Format a hex value.
Parameters
pBuf Storage for string representation of value.
val Value.
len Length of value, in bits.
WStrHexToArray()
void WStrHexToArray (const char * pStr, uint8_t * pBuf, uint16_t len)
Convert a formatted string to int array, zero out space after the string length.
Parameters
pStr Pointer to the string to convert.
pBuf Pointer to destination buffer.
len Size of pBuf in bytes.
Returns
none.
WstrnCpy()
void WstrnCpy (char * pBuf, const char * pData, uint8_t n)
Copies a string up to a given length.
Parameters
pBuf Pointer to buffer to copy to.
pData Pointer to the string to copy.
n Size of pBuf in bytes.
Returns
none.
Copies a string up to a given length.
Returns
none.
WStrReverse()
void WStrReverse (uint8_t * pBuf, uint8_t len)
Byte by byte reverse a buffer.
Parameters
pBuf Buffer to reverse.
len size of pBuf in bytes.
WStrReverseCpy()
void WStrReverseCpy (uint8_t * pBuf1, const uint8_t * pBuf2, uint16_t len)
Byte by byte reverse and copy a buffer.
Parameters
pBuf1 Buffer to hold reversed copy.
pBuf2 Buffer to copy.
len Size of pBuf1 and pBuf2 in bytes.