Cordio: STACK_SMP_API
STACK_SMP_API
Data Structures
struct smpCfg_t
struct smpDmPair_t
struct smpDmAuthRsp_t
struct smpDmKeypress_t
struct smpDmSecurityReq_t
union smpDmMsg_t
Macros
#define SMP_HDR_LEN 1
#define SMP_TIMEOUT 30
#define SMP_OOB_LEN 16
#define SMP_PIN_LEN 3
SMP Events
Events recognized and handled by the SMP state machine.
enum
enum
SMP Initialization Functions
Legacy and Secure Connections initialization for Initiator and Responder roles.
void SmpiInit (void)
void SmprInit (void)
void SmpiScInit (void)
void SmprScInit (void)
void SmpNonInit (void)
SMP DM Interface Functions
Functions that allow the DM to send messages to SMP.
void SmpDmMsgSend (smpDmMsg_t *pMsg)
void SmpDmEncryptInd (wsfMsgHdr_t *pMsg)
bool_t SmpDmLescEnabled (dmConnId_t connId)
uint8_t * SmpDmGetStk (dmConnId_t connId, uint8_t *pSecLevel)
void SmpScGetCancelMsgWithReattempt (dmConnId_t connId, wsfMsgHdr_t *pHdr, uint8_t status)
void SmpDbInit (void)
void SmpScEnableZeroDhKey (bool_t enable)
SMP Encryption Key Size
#define SMP_KEY_SIZE_MAX 16
#define SMP_KEY_SIZE_MIN 7
SMP Error Codes
SMP PDU status codes
#define SMP_ERR_PASSKEY_ENTRY 0x01
#define SMP_ERR_OOB 0x02
#define SMP_ERR_AUTH_REQ 0x03
#define SMP_ERR_CONFIRM_VALUE 0x04
#define SMP_ERR_PAIRING_NOT_SUP 0x05
#define SMP_ERR_ENC_KEY_SIZE 0x06
#define SMP_ERR_COMMAND_NOT_SUP 0x07
#define SMP_ERR_UNSPECIFIED 0x08
#define SMP_ERR_ATTEMPTS 0x09
#define SMP_ERR_INVALID_PARAM 0x0A
#define SMP_ERR_DH_KEY_CHECK 0x0B
#define SMP_ERR_NUMERIC_COMPARISON 0x0C
#define SMP_ERR_BR_EDR_IN_PROGRESS 0x0D
#define SMP_ERR_CROSS_TRANSPORT 0x0E
Proprietary Error Codes
Internal error codes not sent in any SMP PDU.
#define SMP_ERR_MEMORY 0xE0
#define SMP_ERR_TIMEOUT 0xE1
SMP PDU Codes
SMP PDU Code describing command received or sent.
#define SMP_CMD_PAIR_REQ 0x01
#define SMP_CMD_PAIR_RSP 0x02
#define SMP_CMD_PAIR_CNF 0x03
#define SMP_CMD_PAIR_RAND 0x04
#define SMP_CMD_PAIR_FAIL 0x05
#define SMP_CMD_ENC_INFO 0x06
#define SMP_CMD_MASTER_ID 0x07
#define SMP_CMD_ID_INFO 0x08
#define SMP_CMD_ID_ADDR_INFO 0x09
#define SMP_CMD_SIGN_INFO 0x0A
#define SMP_CMD_SECURITY_REQ 0x0B
#define SMP_CMD_PUBLIC_KEY 0x0C
#define SMP_CMD_DHKEY_CHECK 0x0D
#define SMP_CMD_KEYPRESS 0x0E
#define SMP_CMD_MAX 0x0F
SMP PDU Packet Lengths
Fixed length of the PDU to be sent.
#define SMP_PAIR_REQ_LEN 7
#define SMP_PAIR_RSP_LEN 7
#define SMP_PAIR_CNF_LEN 17
#define SMP_PAIR_RAND_LEN 17
#define SMP_PAIR_FAIL_LEN 2
#define SMP_ENC_INFO_LEN 17
#define SMP_MASTER_ID_LEN 11
#define SMP_ID_INFO_LEN 17
#define SMP_ID_ADDR_INFO_LEN 8
#define SMP_SIGN_INFO_LEN 17
#define SMP_SECURITY_REQ_LEN 2
#define SMP_PUB_KEY_MSG_LEN (1 + 2*SMP_PUB_KEY_LEN)
#define SMP_DHKEY_CHECK_MSG_LEN (1 + SMP_DHKEY_CHECK_LEN)
#define SMP_KEYPRESS_MSG_LEN 2
SMP I/O Capabilities
I/O capabilities codes to be set for SMP_CMD_PAIR_REQ and SMP_CMD_PAIR_RSP
#define SMP_IO_DISP_ONLY 0x00
#define SMP_IO_DISP_YES_NO 0x01
#define SMP_IO_KEY_ONLY 0x02
#define SMP_IO_NO_IN_NO_OUT 0x03
#define SMP_IO_KEY_DISP 0x04
SMP OOB Data Flag
Out-of-Band codes to be set for SMP_CMD_PAIR_REQ and SMP_CMD_PAIR_RSP
#define SMP_OOB_DATA_NONE 0x00
#define SMP_OOB_DATA_PRESENT 0x01
SMP Authentication Requirements Flags
Authentication Requirements Flags to be set for SMP_CMD_PAIR_REQ and SMP_CMD_PAIR_RSP.
#define SMP_AUTH_BOND_MASK 0x03
#define SMP_AUTH_BOND_FLAG 0x01
#define SMP_AUTH_MITM_FLAG 0x04
#define SMP_AUTH_SC_FLAG 0x08
#define SMP_AUTH_KP_FLAG 0x10
SMP Key Distribution Flags
Flags of security keys this device is requesting to be distribution once pairing completes.
#define SMP_KEY_DIST_ENC 0x01
#define SMP_KEY_DIST_ID 0x02
#define SMP_KEY_DIST_SIGN 0x04
#define SMP_KEY_DIST_MASK (SMP_KEY_DIST_ENC | SMP_KEY_DIST_ID | SMP_KEY_DIST_SIGN)
SMP LE Secure Connection Keypress Codes
Keypress codes found in SMP_CMD_KEYPRESS PDU to be sent on the respective action when the SMP_AUTH_KP_FLAG is set in both the SMP_CMD_PAIR_REQ and SMP_CMD_PAIR_RSP.
#define SMP_PASSKEY_ENTRY_STARTED 0x00
#define SMP_PASSKEY_DIGIT_ENTERED 0x01
#define SMP_PASSKEY_DIGIT_ERASED 0x02
#define SMP_PASSKEY_CLEARED 0x03
#define SMP_PASSKEY_ENTRY_COMPLETED 0x04
SMP Value Length Constants
Lengths of various keys and values.
#define SMP_RAND_LEN 16
#define SMP_CONFIRM_LEN 16
#define SMP_KEY_LEN 16
#define SMP_RAND8_LEN 8
#define SMP_PRIVATE_KEY_LEN 32
#define SMP_PUB_KEY_LEN 32
#define SMP_DHKEY_LEN 32
#define SMP_DHKEY_CHECK_LEN 16
CMAC Input Lengths Constants
Input lengths of SMP cryptopgraphic toolbox functions.
#define SMP_F4_TEXT_LEN (SMP_PUB_KEY_LEN * 2 + 1)
#define SMP_G2_TEXT_LEN (SMP_PUB_KEY_LEN * 2 + SMP_RAND_LEN)
#define SMP_F5_TKEY_TEXT_LEN (SMP_DHKEY_LEN)
#define SMP_F5_TEXT_LEN (9 + 2*BDA_ADDR_LEN + 2*SMP_RAND_LEN)
#define SMP_F6_TEXT_LEN (2*BDA_ADDR_LEN + 3*SMP_RAND_LEN + 5)
Detailed Description
Data Structure Documentation
smpCfg_t
struct smpCfg_t
Configurable parameters.
Data Fields
uint32_t attemptTimeout
uint8_t ioCap
uint8_t minKeyLen
uint8_t maxKeyLen
uint8_t maxAttempts
uint8_t auth
uint32_t maxAttemptTimeout
uint32_t attemptDecTimeout
uint16_t attemptExp
smpDmPair_t
struct smpDmPair_t
Data type for SMP_MSG_API_PAIR_REQ and SMP_MSG_API_PAIR_RSP.
Data Fields
wsfMsgHdr_t hdr
uint8_t oob
uint8_t auth
uint8_t iKeyDist
uint8_t rKeyDist
smpDmAuthRsp_t
struct smpDmAuthRsp_t
Data type for SMP_MSG_API_AUTH_RSP.
Data Fields
wsfMsgHdr_t hdr
uint8_t authData [SMP_OOB_LEN]
uint8_t authDataLen
smpDmKeypress_t
struct smpDmKeypress_t
Data type for SMP_MSG_API_USER_KEYPRESS.
Data Fields
wsfMsgHdr_t hdr
uint8_t keypress
smpDmSecurityReq_t
struct smpDmSecurityReq_t
Data type for SMP_MSG_API_SECURITY_REQ.
Data Fields
wsfMsgHdr_t hdr
uint8_t auth
smpDmMsg_t
union smpDmMsg_t
Union SMP DM message data types.
Data Fields
wsfMsgHdr_t hdr
smpDmPair_t pair
smpDmAuthRsp_t authRsp
smpDmSecurityReq_t securityReq
smpDmKeypress_t keypress
Macro Definition Documentation
SMP_HDR_LEN
#define SMP_HDR_LEN 1
PDU format.
Attribute PDU header length.
SMP_TIMEOUT
#define SMP_TIMEOUT 30
Protocol timeout.
Protocol timeout in seconds.
Enumeration Type Documentation
anonymous enum
anonymous enum
Event handler messages for SMP state machines.
Enumerator
SMP_MSG_API_PAIR_REQ
API pairing request.
SMP_MSG_API_PAIR_RSP
API pairing response.
SMP_MSG_API_CANCEL_REQ
API cancel request.
SMP_MSG_API_AUTH_RSP
API pin response.
SMP_MSG_API_SECURITY_REQ
API security request.
SMP_MSG_CMD_PKT
SMP command packet received.
SMP_MSG_CMD_PAIRING_FAILED
SMP pairing failed packet received.
SMP_MSG_DM_ENCRYPT_CMPL
Link encrypted.
SMP_MSG_DM_ENCRYPT_FAILED
Link encryption failed.
SMP_MSG_DM_CONN_CLOSE
Connection closed.
SMP_MSG_WSF_AES_CMPL
AES calculation complete.
SMP_MSG_INT_SEND_NEXT_KEY
Send next key to be distributed.
SMP_MSG_INT_MAX_ATTEMPTS
Maximum pairing attempts reached.
SMP_MSG_INT_PAIRING_CMPL
Pairing complete.
SMP_MSG_INT_RSP_TIMEOUT
Pairing protocol response timeout.
SMP_MSG_INT_WI_TIMEOUT
Pairing protocol wait interval timeout.
SMP_MSG_INT_LESC
Pair with Secure Connections.
SMP_MSG_INT_LEGACY
Pair with Legacy Security.
SMP_MSG_INT_JW_NC
LESC Just-Works/Numeric Comparison pairing.
SMP_MSG_INT_PASSKEY
LESC Passkey pairing.
SMP_MSG_INT_OOB
LESC Out-of-Band Pairing.
SMP_MSG_API_USER_CONFIRM
User confirms valid numeric comparison.
SMP_MSG_API_USER_KEYPRESS
User keypress in passkey pairing.
SMP_MSG_API_KEYPRESS_CMPL
User keypress complete in passkey pairing.
SMP_MSG_WSF_ECC_CMPL
WSF ECC operation complete.
SMP_MSG_INT_PK_NEXT
Continue to next passkey bit.
SMP_MSG_INT_PK_CMPL
Passkey operation complete.
SMP_MSG_WSF_CMAC_CMPL
WSF CMAC operation complete.
SMP_MSG_DH_CHECK_FAILURE
DHKey check failure.
SMP_MSG_EARLY_CNF
An early Confirm from the initiator in passkey pairing.
SMP_MSG_INT_CLEANUP
Cleanup control information and return to IDLE state.
SMP_NUM_MSGS
Number of SMP message types.
anonymous enum
anonymous enum
Additional SMP messages.
Enumerator
SMP_DB_SERVICE_IND
SMP DB Service timer indication.
Function Documentation
SmpDbInit()
void SmpDbInit (void)
Initialize the SMP Database.
Returns
None.
SmpDmEncryptInd()
void SmpDmEncryptInd (wsfMsgHdr_t * pMsg)
This function is called by DM to notify SMP of encrypted link status.
Parameters
pMsg Pointer to HCI message structure.
Returns
None.
References DM_SEC_LEVEL_ENC, DM_SEC_LEVEL_ENC_AUTH, DM_SEC_LEVEL_ENC_LESC, wsfMsgHdr_t::event, HCI_SUCCESS, SMP_AUTH_MITM_FLAG, SMP_KEY_SIZE_MAX, SMP_MSG_DM_ENCRYPT_CMPL, SMP_MSG_DM_ENCRYPT_FAILED, SmpHandler(), wsfMsgHdr_t::status, and WSF_MIN.
SmpDmGetStk()
uint8_t* SmpDmGetStk (dmConnId_t connId, uint8_t * pSecLevel)
Return the STK for the given connection.
Parameters
connId Connection identifier.
pSecLevel Returns the security level of pairing when STK was created.
Returns
Pointer to STK or NULL if not available.
SmpDmLescEnabled()
bool_t SmpDmLescEnabled (dmConnId_t connId)
Check if LE Secure Connections is enabled on the connection.
Parameters
connId Connection identifier.
Returns
TRUE is Secure Connections is enabled, else FALSE
SmpDmMsgSend()
void SmpDmMsgSend (smpDmMsg_t * pMsg)
This function is called by DM to send a message to SMP.
Parameters
pMsg Pointer to message structure.
Returns
None.
References WsfMsgSend().
SmpiInit()
void SmpiInit (void)
Initialize SMP initiator role.
Returns
None.
SmpiScInit()
void SmpiScInit (void)
Initialize SMP initiator role utilizing BTLE Secure Connections.
Returns
None.
Initialize SMP initiator role utilizing BTLE Secure Connections.
Returns
None.
SmpNonInit()
void SmpNonInit (void)
Use this SMP init function when SMP is not supported.
Returns
None.
References L2C_CID_SMP, and L2cRegister().
SmprInit()
void SmprInit (void)
Initialize SMP responder role.
Returns
None.
SmprScInit()
void SmprScInit (void)
Initialize SMP responder role utilizing BTLE Secure Connections.
Returns
None.
Initialize SMP responder role utilizing BTLE Secure Connections.
Returns
None.
SmpScEnableZeroDhKey()
void SmpScEnableZeroDhKey (bool_t enable)
Called to force the DhKey to zero for qualification test purposes.
Parameters
enable TRUE - Force DhKey to zero. FALSE - Use calculated key
Returns
None.
SmpScGetCancelMsgWithReattempt()
void SmpScGetCancelMsgWithReattempt (dmConnId_t connId, wsfMsgHdr_t * pHdr, uint8_t status)
Format a cancel message with consideration for the attempts counter.
Parameters
connId Connection Id.
pHdr Pointer to header of message to fill.
status Status to include.
Returns
none.
References wsfMsgHdr_t::event, smpCfg_t::maxAttempts, wsfMsgHdr_t::param, pSmpCfg, SMP_ERR_CONFIRM_VALUE, SMP_MSG_API_AUTH_RSP, SMP_MSG_API_CANCEL_REQ, SMP_MSG_API_KEYPRESS_CMPL, SMP_MSG_API_PAIR_REQ, SMP_MSG_API_PAIR_RSP, SMP_MSG_API_SECURITY_REQ, SMP_MSG_API_USER_CONFIRM, SMP_MSG_API_USER_KEYPRESS, SMP_MSG_CMD_PAIRING_FAILED, SMP_MSG_CMD_PKT, SMP_MSG_DH_CHECK_FAILURE, SMP_MSG_DM_CONN_CLOSE, SMP_MSG_DM_ENCRYPT_CMPL, SMP_MSG_DM_ENCRYPT_FAILED, SMP_MSG_INT_CLEANUP, SMP_MSG_INT_JW_NC, SMP_MSG_INT_LEGACY, SMP_MSG_INT_LESC, SMP_MSG_INT_MAX_ATTEMPTS, SMP_MSG_INT_OOB, SMP_MSG_INT_PAIRING_CMPL, SMP_MSG_INT_PASSKEY, SMP_MSG_INT_PK_CMPL, SMP_MSG_INT_PK_NEXT, SMP_MSG_INT_RSP_TIMEOUT, SMP_MSG_INT_SEND_NEXT_KEY, SMP_MSG_INT_WI_TIMEOUT, SMP_MSG_WSF_AES_CMPL, SMP_MSG_WSF_CMAC_CMPL, SMP_MSG_WSF_ECC_CMPL, and wsfMsgHdr_t::status.