Cordio: PULSE_OXIMETER_PROFILE
PULSE_OXIMETER_PROFILE
Data Structures
struct plxpsCfg_t
struct plxpsRec_t
Macros
#define PLXPS_RACP_MIN_WRITE_LEN 2
#define PLXPS_RACP_RSP_LEN 4
#define PLXPS_RACP_NUM_REC_RSP_LEN 4
#define PLXPS_OPERAND_MAX ((CH_RACP_GLS_FILTER_TIME_LEN * 2) + 1)
Typedefs
typedef appPlxCm_t plxpCm_t
typedef appPlxScm_t plxpScm_t
Enumerations
enum
Functions
void PlxpcPlxsDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t PlxpcPlxsValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void PlxpcPlxsRacpSend (dmConnId_t connId, uint16_t handle, uint8_t opcode, uint8_t oper)
void PlxpsInit (wsfHandlerId_t handlerId, plxpsCfg_t *pCfg)
void PlxpsProcMsg (wsfMsgHdr_t *pMsg)
void PlxpsBtn (dmConnId_t connId, uint8_t btn)
uint8_t PlxpsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
void PlxpsSetFeature (uint16_t feature, uint16_t measStatus, uint32_t sensorStatus)
void PlxpsSetCccIdx (uint8_t plxscCccIdx, uint8_t plxcCccIdx, uint8_t racpCccIdx)
void PlxpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t plxmCccIdx)
void PlxpsMeasStop (void)
void plxpsSendSpotCheckMeas (dmConnId_t connId, plxpScm_t *pMeas)
void plxpsSendContinuousMeas (dmConnId_t connId, plxpCm_t *pMeas)
void plxpsDbInit (void)
uint8_t plxpsDbGetNextRecord (uint8_t oper, plxpsRec_t *pCurrRec, plxpsRec_t **pRec)
uint8_t plxpsDbDeleteRecords (uint8_t oper)
uint8_t plxpsDbGetNumRecords (uint8_t oper, uint8_t *pNumRec)
void plxpsDbGenerateRecord (void)
Detailed Description
Data Structure Documentation
plxpsCfg_t
struct plxpsCfg_t
Configurable parameters.
Data Fields
wsfTimerTicks_t period
plxpsRec_t
struct plxpsRec_t
Pulse Oximeter measurement record.
Data Fields
plxpScm_t spotCheck
Enumeration Type Documentation
anonymous enum
anonymous enum
Pulse Oximeter service enumeration of handle indexes of characteristics to be discovered.
Enumerator
PLXPC_PLXS_PLXSC_HDL_IDX
Pulse Oximeter Spot Check measurement.
PLXPC_PLXS_PLXSC_CCC_HDL_IDX
Pulse Oximeter Spot Check measurement CCC descriptor.
PLXPC_PLXS_PLXC_HDL_IDX
Pulse Oximeter Continuous measurement.
PLXPC_PLXS_PLXC_CCC_HDL_IDX
Pulse Oximeter Continuous measurement CCC descriptor.
PLXPC_PLXS_PLXF_HDL_IDX
Pulse Oximeter features.
PLXPC_PLXS_RACP_HDL_IDX
Record access control point.
PLXPC_PLXS_RACP_CCC_HDL_IDX
Record access control point CCC descriptor.
PLXPC_PLXS_HDL_LIST_LEN
Handle list length.
Function Documentation
PlxpcPlxsDiscover()
void PlxpcPlxsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Pulse Oximeter service. Parameter pHdlList must point to an array of length PLXPC_PLXS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Pulse Oximeter service. Parameter pHdlList must point to an array of length PLXPC_PLXS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attPlxsSvcUuid, and PLXPC_PLXS_HDL_LIST_LEN.
PlxpcPlxsRacpSend()
void PlxpcPlxsRacpSend (dmConnId_t connId, uint16_t handle, uint8_t opcode, uint8_t oper)
Send a command to the pulse oximeter service record access control point.
Parameters
connId Connection identifier.
handle Attribute handle.
opcode Command opcode.
oper Command operator or 0 if no operator required.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, AttcWriteReq(), and UINT8_TO_BSTREAM.
PlxpcPlxsValueUpdate()
uint8_t PlxpcPlxsValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length PLXPC_PLXS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length PLXPC_PLXS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, attEvt_t::handle, PLXPC_PLXS_PLXC_HDL_IDX, PLXPC_PLXS_PLXF_HDL_IDX, PLXPC_PLXS_PLXSC_HDL_IDX, PLXPC_PLXS_RACP_HDL_IDX, attEvt_t::pValue, and attEvt_t::valueLen.
PlxpsBtn()
void PlxpsBtn (dmConnId_t connId, uint8_t btn)
Handle a button press.
Parameters
connId Connection identifier.
btn Button press.
Returns
None.
References APP_UI_BTN_2_EX_LONG, APP_UI_BTN_2_LONG, CH_RACP_OPERATOR_ALL, DM_CONN_ID_NONE, plxpsDbDeleteRecords(), and plxpsDbGenerateRecord().
plxpsDbDeleteRecords()
uint8_t plxpsDbDeleteRecords (uint8_t oper)
Delete records that match the given filter parameters.
Parameters
oper Operator.
Returns
CH_RACP_RSP_SUCCESS if records deleted, otherwise an error status is returned.
Parameters
oper Operator.
Returns
CH_RACP_RSP_SUCCESS if records deleted, otherwise an error status is returned.
References CH_RACP_OPERATOR_ALL, CH_RACP_RSP_INV_OPERATOR, and CH_RACP_RSP_SUCCESS.
plxpsDbGenerateRecord()
void plxpsDbGenerateRecord (void)
Generate a new record.
Returns
None.
plxpsDbGetNextRecord()
uint8_t plxpsDbGetNextRecord (uint8_t oper, plxpsRec_t * pCurrRec, plxpsRec_t ** pRec)
Get the next record that matches the given filter parameters that follows the given current record.
Parameters
oper Operator.
pCurrRec Pointer to current record.
pRec Return pointer to next record, if found.
Returns
CH_RACP_RSP_SUCCESS if a record is found, otherwise an error status is returned.
Parameters
oper Operator.
pCurrRec Pointer to current record.
pRec Return pointer to next record, if found.
Returns
CH_RACP_RSP_SUCCESS if a record is found, otherwise an error status is returned.
References CH_RACP_OPERATOR_ALL, and CH_RACP_RSP_INV_OPERATOR.
plxpsDbGetNumRecords()
uint8_t plxpsDbGetNumRecords (uint8_t oper, uint8_t * pNumRec)
Get the number of records matching the filter parameters.
Parameters
oper Operator.
pNumRec Returns number of records which match filter parameters.
Returns
RACP status.
References CH_RACP_RSP_NO_RECORDS, CH_RACP_RSP_SUCCESS, and plxpsDbGetNextRecord().
plxpsDbInit()
void plxpsDbInit (void)
Initialize the pulse oximeter record database.
Returns
None.
PlxpsInit()
void PlxpsInit (wsfHandlerId_t handlerId, plxpsCfg_t * pCfg)
Initialize the Pulse Oximeter profile sensor.
Parameters
handlerId DM connection identifier.
pCfg Configuration parameters.
Returns
None.
None.
References AppHwPlxcmRead(), and plxpsDbInit().
PlxpsMeasStart()
void PlxpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t plxmCccIdx)
Start periodic pulse oximeter measurement. This function starts a timer to perform periodic measurements.
Parameters
connId DM connection identifier.
timerEvt WSF event designated by the application for the timer.
plxmCccIdx Index of pulse oximeter CCC descriptor in CCC descriptor handle table.
Returns
None.
References WsfTimerStartMs().
PlxpsMeasStop()
void PlxpsMeasStop (void)
Stop periodic pulse oximeter measurement.
Returns
None.
References WsfTimerStop().
PlxpsProcMsg()
void PlxpsProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when a message that requires processing by the pulse oximeter profile sensor is received.
Parameters
pMsg Event message.
Returns
None.
References ATTS_HANDLE_VALUE_CNF, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
plxpsSendContinuousMeas()
void plxpsSendContinuousMeas (dmConnId_t connId, plxpCm_t * pMeas)
Send a Continuous measurement notification.
Parameters
connId Connection ID.
pMeas Pointer to Pulse Oximiter continuous measurement.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, AttsHandleValueNtf(), and PLXS_CONTINUOUS_HDL.
plxpsSendSpotCheckMeas()
void plxpsSendSpotCheckMeas (dmConnId_t connId, plxpScm_t * pMeas)
Send a spot check measurement indication.
Parameters
connId Connection ID.
pMeas Pointer to pulse oximeter spot check measurement.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, AttsHandleValueInd(), and PLXS_SPOT_CHECK_HDL.
PlxpsSetCccIdx()
void PlxpsSetCccIdx (uint8_t plxscCccIdx, uint8_t plxcCccIdx, uint8_t racpCccIdx)
Set the CCCD index used by the application for pulse oximeter service characteristics.
Parameters
plxscCccIdx Pulse Oximeter spot check CCCD index.
plxcCccIdx Pulse Oximeter continuous CCCD index.
racpCccIdx Record access control point CCCD index.
Returns
None.
PlxpsSetFeature()
void PlxpsSetFeature (uint16_t feature, uint16_t measStatus, uint32_t sensorStatus)
Set the supported features of the pulse oximeter sensor.
Parameters
feature Feature bitmask.
measStatus Measurement status.
sensorStatus Sensor status.
Returns
None.
References AttsSetAttr(), CH_PLF_FLAG_MEAS_STATUS_SUP, CH_PLF_FLAG_SENSOR_STATUS_SUP, CH_PLXF_MAX_FEATURES_LEN, PLXS_FEATURES_HDL, UINT16_TO_BSTREAM, and UINT24_TO_BSTREAM.
PlxpsWriteCback()
uint8_t PlxpsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
ATTS write callback for pulse oximeter service.
Parameters
connId DM connection identifier.
handle ATT handle.
operation ATT operation.
offset Write offset.
len Write length.
pValue Value to write.
pAttr Attribute to write.
Returns
ATT status.
ATTS write callback for pulse oximeter service.
Returns
ATT status.
References ATT_ERR_CCCD, ATT_ERR_IN_PROGRESS, ATT_ERR_LENGTH, ATT_SUCCESS, AttsCccEnabled(), BSTREAM_TO_UINT8, CH_RACP_OPCODE_ABORT, CH_RACP_OPCODE_DELETE, CH_RACP_OPCODE_REPORT, CH_RACP_OPCODE_REPORT_NUM, CH_RACP_OPCODE_RSP, CH_RACP_OPERATOR_ALL, CH_RACP_OPERATOR_LAST, CH_RACP_OPERATOR_NULL, CH_RACP_RSP_INV_OPERAND, CH_RACP_RSP_INV_OPERATOR, CH_RACP_RSP_OPCODE_NOT_SUP, CH_RACP_RSP_OPERATOR_NOT_SUP, and PLXPS_RACP_MIN_WRITE_LEN.