Cordio: Mesh Proxy Profile API
Mesh Proxy Profile API
Enumerations
enum
enum
Functions
void MprxcMprxsDiscover (dmConnId_t connId, uint16_t *pHdlList)
void MprxcSetHandles (dmConnId_t connId, uint16_t dataInHandle, uint16_t dataOutHandle)
void MprxcSendDataIn (meshGattProxyPduSendEvt_t *pEvt)
void MprxcProcMsg (wsfMsgHdr_t *pMsg)
void MprxsProcMsg (wsfMsgHdr_t *pMsg)
uint8_t MprxsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
void MprxsSetCccIdx (uint8_t dataOutCccIdx)
void MprxsSendDataOut (meshGattProxyPduSendEvt_t *pEvt)
void SvcMprxsAddGroup (void)
void SvcMprxsRemoveGroup (void)
void SvcMprxsRegister (attsWriteCback_t writeCback)
Mesh Proxy Service handle range
#define MPRXS_START_HDL 0x0510
#define MPRXS_END_HDL (MPRXS_MAX_HDL - 1)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Mesh Proxy service enumeration of handle indexes of characteristics to be discovered
Enumerator
MPRXC_MPRXS_DIN_HDL_IDX
Data In
MPRXC_MPRXS_DOUT_HDL_IDX
Data Out
MPRXC_MPRXS_DOUT_CCC_HDL_IDX
Data Out CCC descriptor
MPRXC_MPRXS_HDL_LIST_LEN
Handle list length
anonymous enum
anonymous enum
Mesh Proxy Service handles
Enumerator
MPRXS_SVC_HDL
Mesh Proxy Server Service declaration
MPRXS_DIN_CH_HDL
Mesh Proxy Data In characteristic
MPRXS_DIN_HDL
Mesh Proxy Data In
MPRXS_DOUT_CH_HDL
Mesh Proxy Data Out characteristic
MPRXS_DOUT_HDL
Mesh Proxy Data Out
MPRXS_DOUT_CH_CCC_HDL
Mesh Proxy Data Out Client Characteristic Configuration Descriptor
MPRXS_MAX_HDL
Max handle
Function Documentation
MprxcMprxsDiscover()
void MprxcMprxsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Mesh Proxy service. Parameter pHdlList must point to an array of length MPRXC_MPRXS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attMprxSvcUuid, and MPRXC_MPRXS_HDL_LIST_LEN.
MprxcProcMsg()
void MprxcProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when a message that requires processing by the Mesh Proxy client is received.
Parameters
pMsg Event message.
Returns
None.
References ATTC_HANDLE_VALUE_NTF, ATTC_WRITE_CMD_RSP, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
MprxcSendDataIn()
void MprxcSendDataIn (meshGattProxyPduSendEvt_t * pEvt)
Send data to the Mesh Proxy Server.
Parameters
[in] pEvt GATT Proxy PDU send event.
Returns
None.
Send data to the Mesh Proxy Server.
Parameters
[in] pEvt GATT Proxy PDU send event.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, AttcWriteCmd(), meshGattProxyPduSendEvt_t::connId, meshGattProxyPduSendEvt_t::pProxyPdu, meshGattProxyPduSendEvt_t::proxyHdr, and meshGattProxyPduSendEvt_t::proxyPduLen.
MprxcSetHandles()
void MprxcSetHandles (dmConnId_t connId, uint16_t dataInHandle, uint16_t dataOutHandle)
Set the handle used by the application for interacting with the Mesh Proxy service Data In characteristic.
Parameters
connId Connection ID.
dataInHandle Data In handled on the server discovered by the client.
dataOutHandle Data Out handled on the server discovered by the client.
Returns
None.
References ATT_VALUE_NTF_LEN, AttGetMtu(), and MeshAddGattProxyConn().
MprxsProcMsg()
void MprxsProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when a message that requires processing by the Mesh Proxy server is received.
Parameters
pMsg Event message.
Returns
None.
References ATTS_CCC_STATE_IND, ATTS_HANDLE_VALUE_CNF, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
MprxsSendDataOut()
void MprxsSendDataOut (meshGattProxyPduSendEvt_t * pEvt)
Send data on the Mesh Proxy Server.
Parameters
[in] pEvt GATT Proxy PDU send event.
Returns
None.
References ATT_PDU_VALUE_NTF, AttMsgAlloc(), AttsCccEnabled(), AttsHandleValueNtfZeroCpy(), meshGattProxyPduSendEvt_t::connId, MPRXS_DOUT_HDL, meshGattProxyPduSendEvt_t::pProxyPdu, meshGattProxyPduSendEvt_t::proxyHdr, and meshGattProxyPduSendEvt_t::proxyPduLen.
MprxsSetCccIdx()
void MprxsSetCccIdx (uint8_t dataOutCccIdx)
Set the CCCD index used by the application for Mesh Proxy service characteristics.
Parameters
dataOutCccIdx Data Out CCCD index.
Returns
None.
MprxsWriteCback()
uint8_t MprxsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
ATTS write callback for Mesh Proxy service. Use this function as a parameter to SvcMprxsRegister().
Parameters
connId DM connection ID.
handle ATT handle.
operation ATT operation.
offset Write offset.
len Write value length.
pValue Data to write.
pAttr Attribute to write.
Returns
ATT status.
References ATT_ERR_INVALID_PDU, ATT_SUCCESS, MESH_GATT_PROXY_PDU_TYPE_PROVISIONING, and MeshProcessGattProxyPdu().
SvcMprxsAddGroup()
void SvcMprxsAddGroup (void)
Add the services to the attribute server.
Returns
None.
References AttsAddGroup().
SvcMprxsRegister()
void SvcMprxsRegister (attsWriteCback_t writeCback)
Register write callback for the service.
Parameters
writeCback Write callback function.
Returns
None.
SvcMprxsRemoveGroup()
void SvcMprxsRemoveGroup (void)
Remove the services from the attribute server.
Returns
None.
References AttsRemoveGroup(), and MPRXS_START_HDL.