Cordio: STACK_HCI_CMD_API
STACK_HCI_CMD_API
Data Structures
struct hciConnSpec_t
struct hciExtInitParam_t
struct hciExtInitScanParam_t
struct hciExtAdvParam_t
struct hciExtAdvEnableParam_t
struct hciExtScanParam_t
struct HciCisCisParams_t
struct HciCisCigParams_t
struct HciCisCreateCisParams_t
struct HciCreateBig_t
struct HciBigCreateSync_t
struct HciIsoSetupDataPath_t
struct HciConfigDataPath_t
struct HciReadLocalSupCodecCaps_t
struct HciReadLocalSupControllerDly_t
HCI Command Interface Functions
HCI commands
void HciDisconnectCmd (uint16_t handle, uint8_t reason)
void HciLeAddDevWhiteListCmd (uint8_t addrType, uint8_t *pAddr)
void HciLeClearWhiteListCmd (void)
void HciLeConnUpdateCmd (uint16_t handle, hciConnSpec_t *pConnSpec)
void HciLeCreateConnCmd (uint16_t scanInterval, uint16_t scanWindow, uint8_t filterPolicy, uint8_t peerAddrType, uint8_t *pPeerAddr, uint8_t ownAddrType, hciConnSpec_t *pConnSpec)
void HciLeCreateConnCancelCmd (void)
void HciLeEncryptCmd (uint8_t *pKey, uint8_t *pData)
void HciLeLtkReqNegReplCmd (uint16_t handle)
void HciLeLtkReqReplCmd (uint16_t handle, uint8_t *pKey)
void HciLeRandCmd (void)
void HciLeReadAdvTXPowerCmd (void)
void HciLeReadBufSizeCmd (void)
void HciLeReadBufSizeCmdV2 (void)
void HciLeReadChanMapCmd (uint16_t handle)
void HciLeReadLocalSupFeatCmd (void)
void HciLeReadRemoteFeatCmd (uint16_t handle)
void HciLeReadSupStatesCmd (void)
void HciLeReadWhiteListSizeCmd (void)
void HciLeRemoveDevWhiteListCmd (uint8_t addrType, uint8_t *pAddr)
void HciLeSetAdvEnableCmd (uint8_t enable)
void HciLeSetAdvDataCmd (uint8_t len, uint8_t *pData)
void HciLeSetAdvParamCmd (uint16_t advIntervalMin, uint16_t advIntervalMax, uint8_t advType, uint8_t ownAddrType, uint8_t peerAddrType, uint8_t *pPeerAddr, uint8_t advChanMap, uint8_t advFiltPolicy)
void HciLeSetEventMaskCmd (uint8_t *pLeEventMask)
void HciLeSetHostChanClassCmd (uint8_t *pChanMap)
void HciLeSetRandAddrCmd (uint8_t *pAddr)
void HciLeSetScanEnableCmd (uint8_t enable, uint8_t filterDup)
void HciLeSetScanParamCmd (uint8_t scanType, uint16_t scanInterval, uint16_t scanWindow, uint8_t ownAddrType, uint8_t scanFiltPolicy)
void HciLeSetScanRespDataCmd (uint8_t len, uint8_t *pData)
void HciLeStartEncryptionCmd (uint16_t handle, uint8_t *pRand, uint16_t diversifier, uint8_t *pKey)
void HciReadBdAddrCmd (void)
void HciReadBufSizeCmd (void)
void HciReadLocalSupFeatCmd (void)
void HciReadLocalVerInfoCmd (void)
void HciReadRemoteVerInfoCmd (uint16_t handle)
void HciReadRssiCmd (uint16_t handle)
void HciReadTxPwrLvlCmd (uint16_t handle, uint8_t type)
void HciResetCmd (void)
void HciSetEventMaskCmd (uint8_t *pEventMask)
void HciSetEventMaskPage2Cmd (uint8_t *pEventMask)
void HciReadAuthPayloadTimeout (uint16_t handle)
void HciWriteAuthPayloadTimeout (uint16_t handle, uint16_t timeout)
void HciLeAddDeviceToResolvingListCmd (uint8_t peerAddrType, const uint8_t *pPeerIdentityAddr, const uint8_t *pPeerIrk, const uint8_t *pLocalIrk)
void HciLeRemoveDeviceFromResolvingList (uint8_t peerAddrType, const uint8_t *pPeerIdentityAddr)
void HciLeClearResolvingList (void)
void HciLeReadResolvingListSize (void)
void HciLeReadPeerResolvableAddr (uint8_t addrType, const uint8_t *pIdentityAddr)
void HciLeReadLocalResolvableAddr (uint8_t addrType, const uint8_t *pIdentityAddr)
void HciLeSetAddrResolutionEnable (uint8_t enable)
void HciLeSetResolvablePrivateAddrTimeout (uint16_t rpaTimeout)
void HciLeSetPrivacyModeCmd (uint8_t addrType, uint8_t *pAddr, uint8_t mode)
void HciLeReadPhyCmd (uint16_t handle)
void HciLeSetDefaultPhyCmd (uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys)
void HciLeSetPhyCmd (uint16_t handle, uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys, uint16_t phyOptions)
void HciVendorSpecificCmd (uint16_t opcode, uint8_t len, uint8_t *pData)
void HciLeRemoteConnParamReqReply (uint16_t handle, uint16_t intervalMin, uint16_t intervalMax, uint16_t latency, uint16_t timeout, uint16_t minCeLen, uint16_t maxCeLen)
void HciLeRemoteConnParamReqNegReply (uint16_t handle, uint8_t reason)
void HciLeSetDataLen (uint16_t handle, uint16_t txOctets, uint16_t txTime)
void HciLeReadDefDataLen (void)
void HciLeWriteDefDataLen (uint16_t suggestedMaxTxOctets, uint16_t suggestedMaxTxTime)
void HciLeReadLocalP256PubKey (void)
void HciLeGenerateDHKey (uint8_t *pPubKeyX, uint8_t *pPubKeyY)
void HciLeGenerateDHKeyV2 (uint8_t *pPubKeyX, uint8_t *pPubKeyY, uint8_t keyType)
void HciLeReadMaxDataLen (void)
void HciLeReadTxPower (void)
void HciLeReadRfPathComp (void)
void HciLeWriteRfPathComp (int16_t txPathComp, int16_t rxPathComp)
HCI AE Advertiser Interface
HCI Advertising Extension functions used by the Advertiser role.
void HciLeSetAdvSetRandAddrCmd (uint8_t advHandle, const uint8_t *pAddr)
void HciLeSetExtAdvParamCmd (uint8_t advHandle, hciExtAdvParam_t *pExtAdvParam)
void HciLeSetExtAdvDataCmd (uint8_t advHandle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t *pData)
void HciLeSetExtScanRespDataCmd (uint8_t advHandle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t *pData)
void HciLeSetExtAdvEnableCmd (uint8_t enable, uint8_t numSets, hciExtAdvEnableParam_t *pEnableParam)
void HciLeReadMaxAdvDataLen (void)
void HciLeReadNumSupAdvSets (void)
void HciLeRemoveAdvSet (uint8_t advHandle)
void HciLeClearAdvSets (void)
void HciLeSetPerAdvParamCmd (uint8_t advHandle, uint16_t advIntervalMin, uint16_t advIntervalMax, uint16_t advProps)
void HciLeSetPerAdvDataCmd (uint8_t advHandle, uint8_t op, uint8_t len, const uint8_t *pData)
void HciLeSetPerAdvEnableCmd (uint8_t enable, uint8_t advHandle)
HCI AE Scanner Interface
HCI Advertising Extension functions used in the Scanner role.
void HciLeSetExtScanParamCmd (uint8_t ownAddrType, uint8_t scanFiltPolicy, uint8_t scanPhys, hciExtScanParam_t *pScanParam)
void HciLeExtScanEnableCmd (uint8_t enable, uint8_t filterDup, uint16_t duration, uint16_t period)
void HciLeExtCreateConnCmd (hciExtInitParam_t *pInitParam, hciExtInitScanParam_t *pScanParam, hciConnSpec_t *pConnSpec)
void HciLePerAdvCreateSyncCmd (uint8_t options, uint8_t advSid, uint8_t advAddrType, uint8_t *pAdvAddr, uint16_t skip, uint16_t syncTimeout, uint8_t unused)
void HciLePerAdvCreateSyncCancelCmd (void)
void HciLePerAdvTerminateSyncCmd (uint16_t syncHandle)
void HciLeAddDeviceToPerAdvListCmd (uint8_t advAddrType, uint8_t *pAdvAddr, uint8_t advSid)
void HciLeRemoveDeviceFromPerAdvListCmd (uint8_t advAddrType, uint8_t *pAdvAddr, uint8_t advSid)
void HciLeClearPerAdvListCmd (void)
void HciLeReadPerAdvListSizeCmd (void)
void HciLeSetPerAdvRcvEnableCmd (uint16_t syncHandle, uint8_t enable)
void HciLePerAdvSyncTrsfCmd (uint16_t connHandle, uint16_t serviceData, uint16_t syncHandle)
void HciLePerAdvSetInfoTrsfCmd (uint16_t connHandle, uint16_t serviceData, uint8_t advHandle)
void HciLeSetPerAdvSyncTrsfParamsCmd (uint16_t connHandle, uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
void HciLeSetDefaultPerAdvSyncTrsfParamsCmd (uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
void HciLeSetConnCteRxParamsCmd (uint16_t connHandle, uint8_t samplingEnable, uint8_t slotDurations, uint8_t switchPatternLen, uint8_t *pAntennaIDs)
void HciLeSetConnCteTxParamsCmd (uint16_t connHandle, uint8_t cteTypeBits, uint8_t switchPatternLen, uint8_t *pAntennaIDs)
void HciLeConnCteReqEnableCmd (uint16_t connHandle, uint8_t enable, uint16_t cteReqInt, uint8_t reqCteLen, uint8_t reqCteType)
void HciLeConnCteRspEnableCmd (uint16_t connHandle, uint8_t enable)
void HciLeReadAntennaInfoCmd (void)
void HciLeSetCigParamsCmd (HciCisCigParams_t *pCigParam)
void HciLeCreateCisCmd (uint8_t numCis, HciCisCreateCisParams_t *pCreateCisParam)
void HciLeAcceptCisReqCmd (uint16_t connHandle)
void HciLeRejectCisReqCmd (uint16_t connHandle, uint8_t reason)
void HciLeRemoveCigCmd (uint8_t cigId)
void HciLeRequestPeerScaCmd (uint16_t handle)
void HciLeCreateBigCmd (HciCreateBig_t *pCreateBig)
void HciTerminateBigCmd (uint8_t bigHandle, uint8_t reason)
void HciLeBigCreateSyncCmd (HciBigCreateSync_t *pCreateSync)
void HciLeBigTerminateSync (uint8_t bigHandle)
void HciLeIsoTxTest (uint16_t handle, uint8_t pldType)
void HciLeIsoRxTest (uint16_t handle, uint8_t pldType)
void HciLeIsoReadTestCounters (uint16_t handle)
void HciLeIsoTestEnd (uint16_t handle)
void HciLeSetupIsoDataPathCmd (HciIsoSetupDataPath_t *pDataPathParam)
void HciLeRemoveIsoDataPathCmd (uint16_t handle, uint8_t directionBits)
void HciConfigDataPathCmd (HciConfigDataPath_t *pDataPathParam)
void HciReadLocalSupCodecsCmd (void)
void HciReadLocalSupCodecCapCmd (HciReadLocalSupCodecCaps_t *pCodecParam)
void HciReadLocalSupControllerDlyCmd (HciReadLocalSupControllerDly_t *pDelayParam)
void HciLeSetHostFeatureCmd (uint8_t bitNum, bool_t bitVal)
Detailed Description
Data Structure Documentation
hciConnSpec_t
struct hciConnSpec_t
Connection specification type.
Data Fields
uint16_t connIntervalMin
uint16_t connIntervalMax
uint16_t connLatency
uint16_t supTimeout
uint16_t minCeLen
uint16_t maxCeLen
hciExtInitParam_t
struct hciExtInitParam_t
Initiating parameters.
Data Fields
uint8_t filterPolicy
uint8_t ownAddrType
uint8_t peerAddrType
const uint8_t * pPeerAddr
uint8_t initPhys
hciExtInitScanParam_t
struct hciExtInitScanParam_t
Initiating scan parameters.
Data Fields
uint16_t scanInterval
uint16_t scanWindow
hciExtAdvParam_t
struct hciExtAdvParam_t
Extended advertising parameters.
Data Fields
uint16_t advEventProp
uint32_t priAdvInterMin
uint32_t priAdvInterMax
uint8_t priAdvChanMap
uint8_t ownAddrType
uint8_t peerAddrType
uint8_t * pPeerAddr
uint8_t advFiltPolicy
int8_t advTxPwr
uint8_t priAdvPhy
uint8_t secAdvMaxSkip
uint8_t secAdvPhy
uint8_t advSID
uint8_t scanReqNotifEna
hciExtAdvEnableParam_t
struct hciExtAdvEnableParam_t
Extended advertising enable parameters.
Data Fields
uint8_t advHandle
uint16_t duration
uint8_t maxEaEvents
hciExtScanParam_t
struct hciExtScanParam_t
Extended scanning parameters.
Data Fields
uint16_t scanInterval
uint16_t scanWindow
uint8_t scanType
HciCisCisParams_t
struct HciCisCisParams_t
CIS parameters.
Data Fields
uint8_t cisId
uint16_t sduSizeMToS
uint16_t sduSizeSToM
uint8_t phyMToS
uint8_t phySToM
uint8_t rteMToS
uint8_t rteSToM
HciCisCigParams_t
struct HciCisCigParams_t
CIG parameters.
Data Fields
uint8_t cigId
uint32_t sduIntervalMToS
uint32_t sduIntervalSToM
uint8_t sca
uint8_t packing
uint8_t framing
uint16_t transLatMToS
uint16_t transLatSToM
uint8_t numCis
HciCisCisParams_t * pCisParam
HciCisCreateCisParams_t
struct HciCisCreateCisParams_t
CIS create CIS parameters.
Data Fields
uint16_t * pCisHandle
uint16_t * pAclHandle
HciCreateBig_t
struct HciCreateBig_t
BIG Create BIG parameters.
Data Fields
uint8_t bigHandle
uint8_t advHandle
uint8_t numBis
uint32_t sduInterUsec
uint16_t maxSdu
uint16_t mtlMs
uint8_t rtn
uint8_t phys
uint8_t packing
uint8_t framing
uint8_t encrypt
uint8_t bcstCode [HCI_BC_LEN]
HciBigCreateSync_t
struct HciBigCreateSync_t
BIG Create Sync parameters.
Data Fields
uint8_t bigHandle
uint16_t syncHandle
uint8_t encrypt
uint8_t bcstCode [HCI_BC_LEN]
uint8_t mse
uint16_t bigSyncTimeout
uint8_t numBis
uint8_t bis [HCI_MAX_BIS_COUNT]
HciIsoSetupDataPath_t
struct HciIsoSetupDataPath_t
Setup ISO data path parameters.
Data Fields
uint16_t handle
uint8_t dpDir
uint8_t dpId
uint8_t codingFmt
uint16_t compId
uint16_t vsCodecId
uint32_t ctrDly
uint8_t codecConfigLen
uint8_t * pCodecConfig
HciConfigDataPath_t
struct HciConfigDataPath_t
Configure data path parameters.
Data Fields
uint8_t dpDir
uint8_t dpId
uint8_t configLen
uint8_t * pConfig
HciReadLocalSupCodecCaps_t
struct HciReadLocalSupCodecCaps_t
Read local supported codec capabilities parameters.
Data Fields
uint8_t codingFmt
uint16_t compId
uint16_t vsCodecId
uint8_t transType
uint8_t direction
HciReadLocalSupControllerDly_t
struct HciReadLocalSupControllerDly_t
Read local supported controller delay parameters.
Data Fields
uint8_t codingFmt
uint16_t compId
uint16_t vsCodecId
uint8_t transType
uint8_t direction
uint8_t codecConfigLen
uint8_t * pCodecConfig
Function Documentation
HciConfigDataPathCmd()
void HciConfigDataPathCmd (HciConfigDataPath_t * pDataPathParam)
HCI configure data path command.
Parameters
pDataPathParam Parameters for configuring data path.
Returns
None.
References HciConfigDataPath_t::dpDir, HciConfigDataPath_t::dpId, wsfMsgHdr_t::event, HCI_CONFIG_DATA_PATH_CMD_CMPL_CBACK_EVT, HCI_ERR_INVALID_PARAM, HCI_SUCCESS, hciConfigDataPathCmdCmplEvt_t::hdr, PalCodecConfigureDataPath(), wsfMsgHdr_t::status, and hciConfigDataPathCmdCmplEvt_t::status.
HciDisconnectCmd()
void HciDisconnectCmd (uint16_t handle, uint8_t reason)
HCI disconnect command.
Parameters
handle Connection handle.
reason Reason for disconnect.
Returns
None.
References LlDisconnect().
HciLeAcceptCisReqCmd()
void HciLeAcceptCisReqCmd (uint16_t handle)
HCI LE accept CIS request command.
Parameters
connHandle Connection handle of the CIS to be accepted.
Returns
None.
Parameters
handle Connection handle of the CIS to be accepted.
Returns
None.
References LlAcceptCisReq(), and WSF_ASSERT.
HciLeAddDeviceToPerAdvListCmd()
void HciLeAddDeviceToPerAdvListCmd (uint8_t advAddrType, uint8_t * pAdvAddr, uint8_t advSid)
HCI LE add device to periodic advertiser list command.
Parameters
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
advSid Advertising SID.
Returns
None.
References LlDevicePerAdvList_t::advAddrType, LlDevicePerAdvList_t::advSID, LlAddDeviceToPeriodicAdvList(), LlDevicePerAdvList_t::pAdvAddr, and WSF_ASSERT.
HciLeAddDeviceToResolvingListCmd()
void HciLeAddDeviceToResolvingListCmd (uint8_t peerAddrType, const uint8_t * pPeerIdentityAddr, const uint8_t * pPeerIrk, const uint8_t * pLocalIrk)
HCI add device to resolving list command.
Parameters
peerAddrType Peer identity address type.
pPeerIdentityAddr Peer identity address.
pPeerIrk Peer IRK.
pLocalIrk Local IRK.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_ADD_DEV_TO_RES_LIST_CMD_CMPL_CBACK_EVT, hciLeAddDevToResListCmdCmplEvt_t::hdr, LlAddDeviceToResolvingList(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeAddDevToResListCmdCmplEvt_t::status.
HciLeAddDevWhiteListCmd()
void HciLeAddDevWhiteListCmd (uint8_t addrType, uint8_t * pAddr)
HCI LE add device white list command.
Parameters
addrType Address type.
pAddr Peer address.
Returns
None.
References LlAddDeviceToWhitelist().
HciLeBigCreateSyncCmd()
void HciLeBigCreateSyncCmd (HciBigCreateSync_t * pCreateSync)
HCI LE BIG create sync command.
Parameters
pCreateSync BIG Create Sync parameters.
Returns
None.
Parameters
pCreateSync BIG Create Sync parameters.
Returns
Status error code.
HCI LE BIG create sync command.
Parameters
pCreateSync BIG Create Sync parameters.
Returns
Status error code.
References HciLeBigSyncEstEvt_t::bigHandle, LlBigCreateSync_t::bigHandle, HciBigCreateSync_t::bis, wsfMsgHdr_t::event, HCI_LE_BIG_SYNC_EST_CBACK_EVT, HCI_SUCCESS, HciLeBigSyncEstEvt_t::hdr, LlBigCreateSync(), HciBigCreateSync_t::numBis, wsfMsgHdr_t::param, wsfMsgHdr_t::status, HciLeBigSyncEstEvt_t::status, and WSF_MIN.
HciLeBigTerminateSync()
void HciLeBigTerminateSync (uint8_t bigHandle)
HCI LE BIG terminate sync command.
Parameters
bigHandle Used to identify the BIG.
Returns
None.
HCI LE BIG terminate sync command.
Parameters
bigHandle Used to identify the BIG.
Returns
None.
References LlBigTerminateSync().
HciLeClearAdvSets()
void HciLeClearAdvSets (void)
HCI LE clear advertising sets command.
Returns
None.
References LlClearAdvSets().
HciLeClearPerAdvListCmd()
void HciLeClearPerAdvListCmd (void)
HCI LE clear periodic advertiser list command.
Returns
None.
References LlClearPeriodicAdvList().
HciLeClearResolvingList()
void HciLeClearResolvingList (void)
HCI clear resolving list command.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_CLEAR_RES_LIST_CMD_CMPL_CBACK_EVT, hciLeClearResListCmdCmplEvt_t::hdr, LlClearResolvingList(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeClearResListCmdCmplEvt_t::status.
HciLeClearWhiteListCmd()
void HciLeClearWhiteListCmd (void)
HCI LE clear white list command.
Returns
None.
References LlClearWhitelist().
HciLeConnCteReqEnableCmd()
void HciLeConnCteReqEnableCmd (uint16_t connHandle, uint8_t enable, uint16_t cteReqInt, uint8_t reqCteLen, uint8_t reqCteType)
HCI LE connection CTE request enable command.
Parameters
connHandle Connection handle.
enable TRUE to enable CTE request for connection, FALSE to disable it.
cteReqInt CTE request interval.
reqCteLen Minimum length of CTE being requested in 8 us units.
reqCteType Requested CTE type.
Returns
None.
HciLeConnCteRspEnableCmd()
void HciLeConnCteRspEnableCmd (uint16_t connHandle, uint8_t enable)
HCI LE connection CTE response enable command.
Parameters
connHandle Connection handle.
enable TRUE to enable CTE response for connection, FALSE to disable it.
Returns
None.
HciLeConnUpdateCmd()
void HciLeConnUpdateCmd (uint16_t handle, hciConnSpec_t * pConnSpec)
HCI connection update command.
Parameters
handle Connection handle.
pConnSpec Update connection parameters.
Returns
None.
None.
References LlConnUpdate().
HciLeCreateBigCmd()
void HciLeCreateBigCmd (HciCreateBig_t * pCreateBig)
HCI LE create BIG command.
Parameters
pCreateBis Create BIG parameters.
Returns
None.
HCI LE create BIG command.
Parameters
pCreateBis Create BIG parameters.
Returns
None.
References HciLeCreateBigCmplEvt_t::bigHandle, LlCreateBig_t::bigHandle, wsfMsgHdr_t::event, HCI_LE_CREATE_BIG_CMPL_CBACK_EVT, HCI_SUCCESS, HciLeCreateBigCmplEvt_t::hdr, LlCreateBig(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and HciLeCreateBigCmplEvt_t::status.
HciLeCreateCisCmd()
void HciLeCreateCisCmd (uint8_t numCis, HciCisCreateCisParams_t * pCreateCisParam)
HCI LE create CIS command.
Parameters
numCis Nunber of CISes.
pCreateCisParam Parameters for creating connected isochronous stream.
Returns
None.
References LlCreateCis(), and WSF_ASSERT.
HciLeCreateConnCancelCmd()
void HciLeCreateConnCancelCmd (void)
HCI LE create connection cancel command.
Returns
None.
References LlCreateConnCancel().
HciLeCreateConnCmd()
void HciLeCreateConnCmd (uint16_t scanInterval, uint16_t scanWindow, uint8_t filterPolicy, uint8_t peerAddrType, uint8_t * pPeerAddr, uint8_t ownAddrType, hciConnSpec_t * pConnSpec)
HCI LE create connection command.
Parameters
scanInterval Scan interval.
scanWindow Scan window.
filterPolicy Filter policy.
peerAddrType Peer address type.
pPeerAddr Peer address.
ownAddrType Own address type.
pConnSpec Connecdtion parameters.
Returns
None.
None.
References LlInitParam_t::filterPolicy, LlCreateConn(), LlInitParam_t::ownAddrType, LlInitParam_t::peerAddrType, LlInitParam_t::pPeerAddr, LlInitParam_t::scanInterval, and LlInitParam_t::scanWindow.
HciLeEncryptCmd()
void HciLeEncryptCmd (uint8_t * pKey, uint8_t * pData)
HCI LE encrypt command.
Parameters
pKey Encryption key.
pData Data to encrypt.
Returns
None.
None.
References Calc128Cpy(), hciLeEncryptCmdCmplEvt_t::data, wsfMsgHdr_t::event, HCI_LE_ENCRYPT_CMD_CMPL_CBACK_EVT, hciLeEncryptCmdCmplEvt_t::hdr, LlEncrypt(), wsfMsgHdr_t::status, hciLeEncryptCmdCmplEvt_t::status, and WSF_ASSERT.
HciLeExtCreateConnCmd()
void HciLeExtCreateConnCmd (hciExtInitParam_t * pInitParam, hciExtInitScanParam_t * pScanParam, hciConnSpec_t * pConnSpec)
HCI LE extended create connection command.
Parameters
pInitParam Initiating parameters.
pScanParam Initiating scan parameters.
pConnSpec Connection specification.
Returns
None.
References HCI_MAX_NUM_PHYS, hciExtInitParam_t::initPhys, LlExtCreateConn(), and WSF_ASSERT.
HciLeExtScanEnableCmd()
void HciLeExtScanEnableCmd (uint8_t enable, uint8_t filterDup, uint16_t duration, uint16_t period)
HCI LE extended scan enable command.
Parameters
enable Set to TRUE to enable scanning, FALSE to disable scanning.
filterDup Set to TRUE to filter duplicates.
duration Duration.
period Period.
Returns
None.
References LlExtScanEnable().
HciLeGenerateDHKey()
void HciLeGenerateDHKey (uint8_t * pPubKeyX, uint8_t * pPubKeyY)
HCI LE Generate DH Key.
Parameters
pPubKeyX Public key X-coordinate.
pPubKeyY Public key Y-coordinate.
Returns
None.
HCI LE Generate DH Key.
Returns
None.
None.
References wsfMsgHdr_t::event, HCI_LE_GENERATE_DHKEY_CMPL_CBACK_EVT, HCI_SUCCESS, hciLeGenDhKeyEvt_t::hdr, LlGenerateDhKey(), wsfMsgHdr_t::status, and hciLeGenDhKeyEvt_t::status.
HciLeGenerateDHKeyV2()
void HciLeGenerateDHKeyV2 (uint8_t * pPubKeyX, uint8_t * pPubKeyY, uint8_t keyType)
HCI LE Generate DH Key Version 2.
Parameters
pPubKeyX Public key X-coordinate.
pPubKeyY Public key Y-coordinate.
keyType Key type.
Returns
None.
HCI LE Generate DH Key Version 2.
Returns
None.
None.
References wsfMsgHdr_t::event, HCI_LE_GENERATE_DHKEY_CMPL_CBACK_EVT, HCI_SUCCESS, hciLeGenDhKeyEvt_t::hdr, LlGenerateDhKeyV2(), wsfMsgHdr_t::status, and hciLeGenDhKeyEvt_t::status.
HciLeIsoReadTestCounters()
void HciLeIsoReadTestCounters (uint16_t handle)
HCI LE read ISO test counter.
Parameters
handle CIS or BIS handle.
Returns
None.
HciLeIsoRxTest()
void HciLeIsoRxTest (uint16_t handle, uint8_t pldType)
HCI LE enable ISO Rx test.
Parameters
handle CIS or BIS handle.
pldType Payload type.
Returns
None.
References LlIsoRxTest(), and WSF_ASSERT.
HciLeIsoTestEnd()
void HciLeIsoTestEnd (uint16_t handle)
HCI LE ISO test end.
Parameters
handle CIS or BIS handle.
Returns
None.
HciLeIsoTxTest()
void HciLeIsoTxTest (uint16_t handle, uint8_t pldType)
HCI LE enable ISO Tx test.
Parameters
handle CIS or BIS handle.
pldType Payload type.
Returns
None.
References LlIsoTxTest(), and WSF_ASSERT.
HciLeLtkReqNegReplCmd()
void HciLeLtkReqNegReplCmd (uint16_t handle)
HCI LE long term key request negative reply command.
Parameters
handle Connection handle.
Returns
None.
None.
References LlLtkReqNegReply().
HciLeLtkReqReplCmd()
void HciLeLtkReqReplCmd (uint16_t handle, uint8_t * pKey)
HCI LE long term key request reply command.
Parameters
handle Connection handle.
pKey LTK.
Returns
None.
None.
References LlLtkReqReply().
HciLePerAdvCreateSyncCancelCmd()
void HciLePerAdvCreateSyncCancelCmd (void)
HCI LE periodic advertising create sync cancel command.
Returns
None.
References LlPeriodicAdvCreateSyncCancel(), and WSF_ASSERT.
HciLePerAdvCreateSyncCmd()
void HciLePerAdvCreateSyncCmd (uint8_t options, uint8_t advSid, uint8_t advAddrType, uint8_t * pAdvAddr, uint16_t skip, uint16_t syncTimeout, uint8_t unused)
HCI LE periodic advertising create sync command.
Parameters
options options.
advSid Advertising SID.
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
skip Number of periodic advertising packets that can be skipped after successful receive.
syncTimeout Synchronization timeout.
unused Reserved for future use (must be zero).
Returns
None.
Parameters
options Options.
advSid Advertising SID.
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
skip Number of periodic advertising packets that can be skipped after successful receive.
syncTimeout Synchronization timeout.
unused Reserved for future use (must be zero).
Returns
None.
References LlPerAdvCreateSyncCmd_t::advAddrType, LlPerAdvCreateSyncCmd_t::advSID, LlPeriodicAdvCreateSync(), LlPerAdvCreateSyncCmd_t::options, LlPerAdvCreateSyncCmd_t::pAdvAddr, LlPerAdvCreateSyncCmd_t::skip, LlPerAdvCreateSyncCmd_t::syncTimeOut, and WSF_ASSERT.
HciLePerAdvSetInfoTrsfCmd()
void HciLePerAdvSetInfoTrsfCmd (uint16_t connHandle, uint16_t serviceData, uint8_t advHandle)
HCI LE set periodic advertising set info transfer command.
Parameters
connHandle Connection handle.
serviceData Service data provided by the host.
advHandle Handle to identify an advertising set.
Returns
None.
References wsfMsgHdr_t::event, hciLePerAdvSetInfoTrsfCmdCmplEvt_t::handle, HCI_LE_PER_ADV_SET_INFO_TRSF_CMD_CMPL_CBACK_EVT, hciLePerAdvSetInfoTrsfCmdCmplEvt_t::hdr, LlPeriodicAdvSetInfoTransfer(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLePerAdvSetInfoTrsfCmdCmplEvt_t::status.
HciLePerAdvSyncTrsfCmd()
void HciLePerAdvSyncTrsfCmd (uint16_t connHandle, uint16_t serviceData, uint16_t syncHandle)
HCI LE periodic advertising sync transfer command.
Parameters
connHandle Connection handle.
serviceData Service data provided by the host.
syncHandle Periodic sync handle.
Returns
None.
References wsfMsgHdr_t::event, hciLePerAdvSyncTrsfCmdCmplEvt_t::handle, HCI_LE_PER_ADV_SYNC_TRSF_CMD_CMPL_CBACK_EVT, hciLePerAdvSyncTrsfCmdCmplEvt_t::hdr, LlPeriodicAdvSyncTransfer(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLePerAdvSyncTrsfCmdCmplEvt_t::status.
HciLePerAdvTerminateSyncCmd()
void HciLePerAdvTerminateSyncCmd (uint16_t syncHandle)
HCI LE periodic advertising terminate sync command.
Parameters
syncHandle Sync handle.
Returns
None.
References LlPeriodicAdvTerminateSync(), and WSF_ASSERT.
HciLeRandCmd()
void HciLeRandCmd (void)
HCI LE random command.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_RAND_CMD_CMPL_CBACK_EVT, HCI_SUCCESS, hciLeRandCmdCmplEvt_t::hdr, LlGetRandNum(), wsfMsgHdr_t::param, hciLeRandCmdCmplEvt_t::randNum, wsfMsgHdr_t::status, and hciLeRandCmdCmplEvt_t::status.
HciLeReadAdvTXPowerCmd()
void HciLeReadAdvTXPowerCmd (void)
HCI LE read advertising TX power command.
Returns
None.
HciLeReadAntennaInfoCmd()
void HciLeReadAntennaInfoCmd (void)
HCI LE read antenna information command.
Returns
None.
HciLeReadBufSizeCmd()
void HciLeReadBufSizeCmd (void)
HCI LE read buffer size command.
Returns
None.
HciLeReadBufSizeCmdV2()
void HciLeReadBufSizeCmdV2 (void)
HCI LE read buffer size version 2 command.
Returns
None.
HciLeReadChanMapCmd()
void HciLeReadChanMapCmd (uint16_t handle)
HCI LE read channel map command.
Parameters
handle Connection handle.
Returns
None.
None.
References hciReadChanMapCmdCmplEvt_t::chanMap, wsfMsgHdr_t::event, hciReadChanMapCmdCmplEvt_t::handle, HCI_LE_READ_CHAN_MAP_CMD_CMPL_CBACK_EVT, hciReadChanMapCmdCmplEvt_t::hdr, LlGetChannelMap(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciReadChanMapCmdCmplEvt_t::status.
HciLeReadDefDataLen()
void HciLeReadDefDataLen (void)
HCI LE Read Default Data Length.
Returns
None.
HCI LE Read Default Data Length.
Returns
None.
HciLeReadLocalP256PubKey()
void HciLeReadLocalP256PubKey (void)
HCI LE Read Local P-256 Public Key.
Returns
None.
HCI LE Read Local P-256 Public Key.
Returns
None.
References LlGenerateP256KeyPair().
HciLeReadLocalResolvableAddr()
void HciLeReadLocalResolvableAddr (uint8_t addrType, const uint8_t * pIdentityAddr)
HCI read local resolvable address command.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_READ_LOCAL_RES_ADDR_CMD_CMPL_CBACK_EVT, hciLeReadLocalResAddrCmdCmplEvt_t::hdr, LlReadLocalResolvableAddr(), hciLeReadLocalResAddrCmdCmplEvt_t::localRpa, wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeReadLocalResAddrCmdCmplEvt_t::status.
HciLeReadLocalSupFeatCmd()
void HciLeReadLocalSupFeatCmd (void)
HCI LE read local supported feautre command.
Returns
None.
HciLeReadMaxAdvDataLen()
void HciLeReadMaxAdvDataLen (void)
HCI LE read maximum advertising data length command.
Returns
None.
HciLeReadMaxDataLen()
void HciLeReadMaxDataLen (void)
HCI LE Read Maximum Data Length.
Returns
None.
HCI LE Read Maximum Data Length.
Returns
None.
HciLeReadNumSupAdvSets()
void HciLeReadNumSupAdvSets (void)
HCI LE read number of supported advertising sets command.
Returns
None.
HciLeReadPeerResolvableAddr()
void HciLeReadPeerResolvableAddr (uint8_t addrType, const uint8_t * pIdentityAddr)
HCI read peer resolvable address command.
Parameters
addrType Peer identity address type.
pIdentityAddr Peer identity address.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_READ_PEER_RES_ADDR_CMD_CMPL_CBACK_EVT, hciLeReadPeerResAddrCmdCmplEvt_t::hdr, LlReadPeerResolvableAddr(), wsfMsgHdr_t::param, hciLeReadPeerResAddrCmdCmplEvt_t::peerRpa, wsfMsgHdr_t::status, and hciLeReadPeerResAddrCmdCmplEvt_t::status.
HciLeReadPerAdvListSizeCmd()
void HciLeReadPerAdvListSizeCmd (void)
HCI LE read periodic advertiser size command.
Returns
None.
HciLeReadPhyCmd()
void HciLeReadPhyCmd (uint16_t handle)
HCI read PHY command.
Parameters
handle Connection handle.
Returns
None.
None.
References wsfMsgHdr_t::event, hciLeReadPhyCmdCmplEvt_t::handle, HCI_LE_READ_PHY_CMD_CMPL_CBACK_EVT, hciLeReadPhyCmdCmplEvt_t::hdr, LlReadPhy(), wsfMsgHdr_t::param, hciLeReadPhyCmdCmplEvt_t::rxPhy, wsfMsgHdr_t::status, hciLeReadPhyCmdCmplEvt_t::status, and hciLeReadPhyCmdCmplEvt_t::txPhy.
HciLeReadRemoteFeatCmd()
void HciLeReadRemoteFeatCmd (uint16_t handle)
HCI LE read remote feature command.
Parameters
handle Connection handle.
Returns
None.
None.
References LlReadRemoteFeat().
HciLeReadResolvingListSize()
void HciLeReadResolvingListSize (void)
HCI read resolving list command.
Returns
None.
HciLeReadRfPathComp()
void HciLeReadRfPathComp (void)
HCI LE read RF path compensation command.
Returns
None.
HciLeReadSupStatesCmd()
void HciLeReadSupStatesCmd (void)
HCI LE read supported states command.
Returns
None.
HciLeReadTxPower()
void HciLeReadTxPower (void)
HCI LE read transmit power command.
Returns
None.
HciLeReadWhiteListSizeCmd()
void HciLeReadWhiteListSizeCmd (void)
HCI LE read white list size command.
Returns
None.
HciLeRejectCisReqCmd()
void HciLeRejectCisReqCmd (uint16_t handle, uint8_t reason)
HCI LE reject CIS request command.
Parameters
connHandle Connection handle of the CIS to be rejected.
reason Reason the CIS request was rejected.
Returns
None.
Parameters
handle Connection handle of the CIS to be rejected.
reason Reason the CIS request was rejected.
Returns
None.
References LlRejectCisReq(), and WSF_ASSERT.
HciLeRemoteConnParamReqNegReply()
void HciLeRemoteConnParamReqNegReply (uint16_t handle, uint8_t reason)
HCI Remote Connection Parameter Request Negative Reply.
Parameters
handle Connection handle.
reason Negative reply reason.
Returns
None.
HCI Remote Connection Parameter Request Negative Reply.
Returns
None.
None.
References LlRemoteConnParamReqNegReply().
HciLeRemoteConnParamReqReply()
void HciLeRemoteConnParamReqReply (uint16_t handle, uint16_t intervalMin, uint16_t intervalMax, uint16_t latency, uint16_t timeout, uint16_t minCeLen, uint16_t maxCeLen)
HCI Remote Connection Parameter Request Reply.
Parameters
handle Connection handle.
intervalMin Interval minimum.
intervalMax Interval maximum.
latency Connection latency.
timeout Connection timeout.
minCeLen Minimum connection event length.
maxCeLen Maximum connection event length.
Returns
None.
HCI Remote Connection Parameter Request Reply.
Returns
None.
None.
References LlConnSpec_t::connIntervalMax, LlConnSpec_t::connIntervalMin, LlConnSpec_t::connLatency, LlRemoteConnParamReqReply(), LlConnSpec_t::maxCeLen, LlConnSpec_t::minCeLen, and LlConnSpec_t::supTimeout.
HciLeRemoveAdvSet()
void HciLeRemoveAdvSet (uint8_t advHandle)
HCI LE remove advertising set command.
Parameters
advHandle Advertising handle.
Returns
Status error code.
References LlRemoveAdvSet().
HciLeRemoveCigCmd()
void HciLeRemoveCigCmd (uint8_t cigId)
HCI LE remove CIG command.
Parameters
cigId Identifer of a CIG.
Returns
None.
References hciLeRemoveCigCmdCmplEvt_t::cigId, wsfMsgHdr_t::event, HCI_LE_REMOVE_CIG_CMD_CMPL_CBACK_EVT, hciLeRemoveCigCmdCmplEvt_t::hdr, LlRemoveCig(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeRemoveCigCmdCmplEvt_t::status.
HciLeRemoveDeviceFromPerAdvListCmd()
void HciLeRemoveDeviceFromPerAdvListCmd (uint8_t advAddrType, uint8_t * pAdvAddr, uint8_t advSid)
HCI LE remove device from periodic advertiser list command.
Parameters
advAddrType Advertiser address type.
pAdvAddr Advertiser address.
advSid Advertising SID.
Returns
None.
References LlDevicePerAdvList_t::advAddrType, LlDevicePerAdvList_t::advSID, LlRemoveDeviceFromPeriodicAdvList(), LlDevicePerAdvList_t::pAdvAddr, and WSF_ASSERT.
HciLeRemoveDeviceFromResolvingList()
void HciLeRemoveDeviceFromResolvingList (uint8_t peerAddrType, const uint8_t * pPeerIdentityAddr)
HCI remove device from resolving list command.
Parameters
peerAddrType Peer identity address type.
pPeerIdentityAddr Peer identity address.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_REM_DEV_FROM_RES_LIST_CMD_CMPL_CBACK_EVT, hciLeRemDevFromResListCmdCmplEvt_t::hdr, LlRemoveDeviceFromResolvingList(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeRemDevFromResListCmdCmplEvt_t::status.
HciLeRemoveDevWhiteListCmd()
void HciLeRemoveDevWhiteListCmd (uint8_t addrType, uint8_t * pAddr)
HCI LE remove device white list command.
Parameters
addrType Address type.
pAddr Peer address.
Returns
None.
None.
References LlRemoveDeviceFromWhitelist().
HciLeRemoveIsoDataPathCmd()
void HciLeRemoveIsoDataPathCmd (uint16_t handle, uint8_t directionBits)
HCI LE remove ISO data path command.
Parameters
handle Connection handle of the CIS or BIS.
directionBits Data path direction bits.
Returns
None.
References wsfMsgHdr_t::event, hciLeRemoveIsoDataPathCmdCmplEvt_t::handle, HCI_LE_REMOVE_ISO_DATA_PATH_CMD_CMPL_CBACK_EVT, hciLeRemoveIsoDataPathCmdCmplEvt_t::hdr, LlRemoveIsoDataPath(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeRemoveIsoDataPathCmdCmplEvt_t::status.
HciLeRequestPeerScaCmd()
void HciLeRequestPeerScaCmd (uint16_t handle)
HCI LE request peer SCA command.
Parameters
handle Connection handle.
Returns
None.
References LlRequestPeerSca(), and WSF_ASSERT.
HciLeSetAddrResolutionEnable()
void HciLeSetAddrResolutionEnable (uint8_t enable)
HCI enable or disable address resolution command.
Parameters
enable Set to TRUE to enable address resolution or FALSE to disable address resolution.
Returns
None.
References wsfMsgHdr_t::event, HCI_LE_SET_ADDR_RES_ENABLE_CMD_CMPL_CBACK_EVT, hciLeSetAddrResEnableCmdCmplEvt_t::hdr, LlSetAddrResolutionEnable(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeSetAddrResEnableCmdCmplEvt_t::status.
HciLeSetAdvDataCmd()
void HciLeSetAdvDataCmd (uint8_t len, uint8_t * pData)
HCI LE set advertising data command.
Parameters
len Length of advertising data.
pData Advertising data.
Returns
None.
None.
References LlSetAdvData().
HciLeSetAdvEnableCmd()
void HciLeSetAdvEnableCmd (uint8_t enable)
HCI LE set advanced enable command.
Parameters
enable Enable.
Returns
None.
None.
References LlAdvEnable().
HciLeSetAdvParamCmd()
void HciLeSetAdvParamCmd (uint16_t advIntervalMin, uint16_t advIntervalMax, uint8_t advType, uint8_t ownAddrType, uint8_t peerAddrType, uint8_t * pPeerAddr, uint8_t advChanMap, uint8_t advFiltPolicy)
HCI LE set advertising parameters command.
Parameters
advIntervalMin Adveritsing minimum interval.
advIntervalMax Advertising maximum interval.
advType Advertising type.
ownAddrType Own address type.
peerAddrType Peer address type.
pPeerAddr Peer address.
advChanMap Advertising channel map.
advFiltPolicy Advertising filter policy.
Returns
None.
None.
References LlSetAdvParam().
HciLeSetAdvSetRandAddrCmd()
void HciLeSetAdvSetRandAddrCmd (uint8_t advHandle, const uint8_t * pAddr)
HCI LE set advertising set random device address command.
Parameters
advHandle Advertising handle.
pAddr Random device address.
Returns
None.
References LlSetAdvSetRandAddr().
HciLeSetCigParamsCmd()
void HciLeSetCigParamsCmd (HciCisCigParams_t * pCigParam)
HCI LE set CIG parameters command.
Parameters
pCigParam CIG parameters.
Returns
None.
References LlCisCigParams_t::cigId, hciLeSetCigParamsCmdCmplEvt_t::cigId, HciCisCigParams_t::cigId, hciLeSetCigParamsCmdCmplEvt_t::cisHandle, wsfMsgHdr_t::event, HCI_LE_SET_CIG_PARAMS_CMD_CMPL_CBACK_EVT, hciLeSetCigParamsCmdCmplEvt_t::hdr, LlSetCigParams(), LlCisCigParams_t::numCis, hciLeSetCigParamsCmdCmplEvt_t::numCis, wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeSetCigParamsCmdCmplEvt_t::status.
HciLeSetConnCteRxParamsCmd()
void HciLeSetConnCteRxParamsCmd (uint16_t connHandle, uint8_t samplingEnable, uint8_t slotDurations, uint8_t switchPatternLen, uint8_t * pAntennaIDs)
HCI LE set connection CTE receive parameters command.
Parameters
connHandle Connection handle.
samplingEnable TRUE to enable Connection IQ sampling, FALSE to disable it.
slotDurations Switching and sampling slot durations to be used while receiving CTE.
switchPatternLen Number of Antenna IDs in switching pattern.
pAntennaIDs List of Antenna IDs in switching pattern.
Returns
None.
HciLeSetConnCteTxParamsCmd()
void HciLeSetConnCteTxParamsCmd (uint16_t connHandle, uint8_t cteTypeBits, uint8_t switchPatternLen, uint8_t * pAntennaIDs)
HCI LE set connection CTE transmit parameters command.
Parameters
connHandle Connection handle.
cteTypeBits Permitted CTE type bits used for transmitting CTEs requested by peer.
switchPatternLen Number of Antenna IDs in switching pattern.
pAntennaIDs List of Antenna IDs in switching pattern.
Returns
None.
HciLeSetDataLen()
void HciLeSetDataLen (uint16_t handle, uint16_t txOctets, uint16_t txTime)
HCI LE Set Data Length.
Parameters
handle Connection handle.
txOctets Tx octets.
txTime Tx time.
Returns
None.
HCI LE Set Data Length.
Returns
None.
None.
References LlSetDataLen().
HciLeSetDefaultPerAdvSyncTrsfParamsCmd()
void HciLeSetDefaultPerAdvSyncTrsfParamsCmd (uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
HCI LE set default periodic advertising sync transfer parameters command.
Parameters
mode Periodic sync advertising sync transfer mode.
skip The number of periodic advertising packets that can be skipped after a successful receive.
syncTimeout Synchronization timeout for the periodic advertising.
cteType Constant tone extension type(Used in AoD/AoA).
Returns
None.
References LlSetDefaultPeriodicAdvSyncTransParams().
HciLeSetDefaultPhyCmd()
void HciLeSetDefaultPhyCmd (uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys)
HCI set default PHY command.
Parameters
allPhys All PHYs.
txPhys Tx PHYs.
rxPhys Rx PHYs.
Returns
None.
None.
References wsfMsgHdr_t::event, HCI_LE_SET_DEF_PHY_CMD_CMPL_CBACK_EVT, hciLeSetDefPhyCmdCmplEvt_t::hdr, LlSetDefaultPhy(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeSetDefPhyCmdCmplEvt_t::status.
HciLeSetEventMaskCmd()
void HciLeSetEventMaskCmd (uint8_t * pLeEventMask)
HCI LE set event mask command.
Parameters
pLeEventMask LE Event mask.
Returns
None.
None.
HciLeSetExtAdvDataCmd()
void HciLeSetExtAdvDataCmd (uint8_t advHandle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t * pData)
HCI LE set extended advertising data command.
Parameters
advHandle Advertising handle.
op Operation.
fragPref Fragment preference.
len Data buffer length.
pData Advertising data buffer.
Returns
None.
References HCI_EXT_ADV_DATA_LEN, and LlSetExtAdvData().
HciLeSetExtAdvEnableCmd()
void HciLeSetExtAdvEnableCmd (uint8_t enable, uint8_t numSets, hciExtAdvEnableParam_t * pEnableParam)
HCI LE set extended advertising enable command.
Parameters
enable Set to TRUE to enable advertising, FALSE to disable advertising.
numSets Number of advertising sets.
pEnableParam Advertising enable parameter array.
Returns
None.
Parameters
enable Set to TRUE to enable advertising, FALSE to disable advertising.
numSets Number of advertising sets.
pScanParam Advertising enable parameter array.
Returns
None.
References LlExtAdvEnable(), and WSF_ASSERT.
HciLeSetExtAdvParamCmd()
void HciLeSetExtAdvParamCmd (uint8_t advHandle, hciExtAdvParam_t * pExtAdvParam)
HCI LE set extended advertising parameters command.
Parameters
advHandle Advertising handle.
pExtAdvParam Extended advertising parameters.
Returns
None.
References LlSetExtAdvParam().
HciLeSetExtScanParamCmd()
void HciLeSetExtScanParamCmd (uint8_t ownAddrType, uint8_t scanFiltPolicy, uint8_t scanPhys, hciExtScanParam_t * pScanParam)
HCI LE set extended scanning parameters command.
Parameters
ownAddrType Address type used by this device.
scanFiltPolicy Scan filter policy.
scanPhys Scanning PHYs.
pScanParam Scanning parameter array.
Returns
None.
References HCI_MAX_NUM_PHYS, LlSetExtScanParam(), and WSF_ASSERT.
HciLeSetExtScanRespDataCmd()
void HciLeSetExtScanRespDataCmd (uint8_t advHandle, uint8_t op, uint8_t fragPref, uint8_t len, const uint8_t * pData)
HCI LE set extended scan response data command.
Parameters
advHandle Advertising handle.
op Operation.
fragPref Fragment preference.
len Data buffer length.
pData Scan response data buffer.
Returns
None.
References HCI_EXT_ADV_DATA_LEN, and LlSetExtScanRespData().
HciLeSetHostChanClassCmd()
void HciLeSetHostChanClassCmd (uint8_t * pChanMap)
HCI set host channel class command.
Parameters
pChanMap Channel map.
Returns
None.
None.
HciLeSetHostFeatureCmd()
void HciLeSetHostFeatureCmd (uint8_t bitNum, bool_t bitVal)
HCI LE set host feature command.
Parameters
bitNum Bit position in the FeatureSet.
bitVal Enable or disable feature.
Returns
None.
Note
Set or clear a bit in the feature controlled by the Host in the Link Layer FeatureSet stored in the Controller.
HciLeSetPerAdvDataCmd()
void HciLeSetPerAdvDataCmd (uint8_t advHandle, uint8_t op, uint8_t len, const uint8_t * pData)
HCI LE set periodic advertising data command.
Parameters
advHandle Advertising handle.
op Operation.
len Data buffer length.
pData Advertising data buffer.
Returns
None.
References HCI_PER_ADV_DATA_LEN, LlSetPeriodicAdvData(), and WSF_ASSERT.
HciLeSetPerAdvEnableCmd()
void HciLeSetPerAdvEnableCmd (uint8_t enable, uint8_t advHandle)
HCI LE set periodic advertising enable command.
Parameters
enable Set to TRUE to enable advertising, FALSE to disable advertising.
advHandle Advertising handle.
Returns
None.
References LlSetPeriodicAdvEnable().
HciLeSetPerAdvParamCmd()
void HciLeSetPerAdvParamCmd (uint8_t advHandle, uint16_t advIntervalMin, uint16_t advIntervalMax, uint16_t advProps)
HCI LE set periodic advertising parameters command.
Parameters
advHandle Advertising handle.
advIntervalMin Periodic advertising interval minimum.
advIntervalMax Periodic advertising interval maximum.
advProps Periodic advertising properties.
Returns
None.
References LlSetPeriodicAdvParam(), LlPerAdvParam_t::perAdvInterMax, LlPerAdvParam_t::perAdvInterMin, LlPerAdvParam_t::perAdvProp, and WSF_ASSERT.
HciLeSetPerAdvRcvEnableCmd()
void HciLeSetPerAdvRcvEnableCmd (uint16_t syncHandle, uint8_t enable)
HCI LE set periodic advertising receive enable command.
Parameters
syncHandle Periodic sync handle.
enable TRUE to enable reports, FALSE to disable reports.
Returns
None.
References LlSetPeriodicAdvRcvEnable().
HciLeSetPerAdvSyncTrsfParamsCmd()
void HciLeSetPerAdvSyncTrsfParamsCmd (uint16_t connHandle, uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
HCI LE set periodic advertising sync transfer parameters command.
Parameters
connHandle Connection handle.
mode Periodic sync advertising sync transfer mode.
skip The number of periodic advertising packets that can be skipped after a successful receive.
syncTimeout Synchronization timeout for the periodic advertising.
cteType Constant tone extension type(Used in AoD/AoA).
Returns
None.
References LlSetPeriodicAdvSyncTransParams().
HciLeSetPhyCmd()
void HciLeSetPhyCmd (uint16_t handle, uint8_t allPhys, uint8_t txPhys, uint8_t rxPhys, uint16_t phyOptions)
HCI set PHY command.
Parameters
handle Connection handle.
allPhys All PHYs.
txPhys Tx PHYs.
rxPhys Rx PHYs.
phyOptions PHY options.
Returns
None.
None.
References LlSetPhy().
HciLeSetPrivacyModeCmd()
void HciLeSetPrivacyModeCmd (uint8_t addrType, uint8_t * pAddr, uint8_t mode)
HCI LE set privacy mode command.
Parameters
addrType Peer identity address type.
pAddr Peer identity address.
mode Privacy mode.
Returns
None.
Parameters
peerAddrType Peer identity address type.
pPeerAddr Peer identity address.
mode Privacy mode.
Returns
None.
References LlSetPrivacyMode().
HciLeSetRandAddrCmd()
void HciLeSetRandAddrCmd (uint8_t * pAddr)
HCI LE set random address command.
Parameters
pAddr Randon address.
Returns
None.
None.
References wsfMsgHdr_t::event, HCI_LE_SET_RAND_ADDR_CMD_CMPL_CBACK_EVT, LlSetRandAddr(), wsfMsgHdr_t::param, and wsfMsgHdr_t::status.
HciLeSetResolvablePrivateAddrTimeout()
void HciLeSetResolvablePrivateAddrTimeout (uint16_t rpaTimeout)
HCI set resolvable private address timeout command.
Parameters
rpaTimeout Timeout measured in seconds.
Returns
None.
References LlSetResolvablePrivateAddrTimeout().
HciLeSetScanEnableCmd()
void HciLeSetScanEnableCmd (uint8_t enable, uint8_t filterDup)
HCI LE set scan enable command.
Parameters
enable Enable.
filterDup Filter duplicates.
Returns
None.
None.
References LlScanEnable().
HciLeSetScanParamCmd()
void HciLeSetScanParamCmd (uint8_t scanType, uint16_t scanInterval, uint16_t scanWindow, uint8_t ownAddrType, uint8_t scanFiltPolicy)
HCI set scan parameters command.
Parameters
scanType Scan type.
scanInterval Scan interval.
scanWindow Scan window.
ownAddrType Own address type.
scanFiltPolicy Scanning filter policy.
Returns
None.
None.
References LlSetScanParam(), LlScanParam_t::ownAddrType, LlScanParam_t::scanFiltPolicy, LlScanParam_t::scanInterval, LlScanParam_t::scanType, LlScanParam_t::scanWindow, and WSF_ASSERT.
HciLeSetScanRespDataCmd()
void HciLeSetScanRespDataCmd (uint8_t len, uint8_t * pData)
HCI LE set scan response data.
Parameters
len Scan response data length.
pData Scan response data.
Returns
None.
None.
References LlSetScanRespData().
HciLeSetupIsoDataPathCmd()
void HciLeSetupIsoDataPathCmd (HciIsoSetupDataPath_t * pDataPathParam)
HCI LE setup ISO data path command.
Parameters
pDataPathParam Parameters for setup ISO data path.
Returns
None.
Parameters
pDataPathParam Parameters for setting up ISO data path.
Returns
None.
References wsfMsgHdr_t::event, LlIsoSetupDataPath_t::handle, hciLeSetupIsoDataPathCmdCmplEvt_t::handle, HciIsoSetupDataPath_t::handle, HCI_LE_SETUP_ISO_DATA_PATH_CMD_CMPL_CBACK_EVT, hciLeSetupIsoDataPathCmdCmplEvt_t::hdr, LlSetupIsoDataPath(), wsfMsgHdr_t::param, wsfMsgHdr_t::status, and hciLeSetupIsoDataPathCmdCmplEvt_t::status.
HciLeStartEncryptionCmd()
void HciLeStartEncryptionCmd (uint16_t handle, uint8_t * pRand, uint16_t diversifier, uint8_t * pKey)
HCI LE start encryption command.
Parameters
handle Connection handle.
pRand Random number.
diversifier Diversifier.
pKey Encryption key.
Returns
None.
None.
References LlStartEncryption().
HciLeWriteDefDataLen()
void HciLeWriteDefDataLen (uint16_t suggestedMaxTxOctets, uint16_t suggestedMaxTxTime)
HCI LE Write Default Data Length.
Parameters
suggestedMaxTxOctets Suggested maximum Tx octets.
suggestedMaxTxTime Suggested maximum Tx time.
Returns
None.
HCI LE Write Default Data Length.
Returns
None.
None.
References LlWriteDefaultDataLen().
HciLeWriteRfPathComp()
void HciLeWriteRfPathComp (int16_t txPathComp, int16_t rxPathComp)
HCI LE write RF path compensation command.
Parameters
txPathComp RF transmit path compensation value.
rxPathComp RF receive path compensation value.
Returns
None.
References LlWriteRfPathComp().
HciReadAuthPayloadTimeout()
void HciReadAuthPayloadTimeout (uint16_t handle)
HCI read authenticated payload timeout command.
Parameters
handle Connection handle.
Returns
None.
HciReadBdAddrCmd()
void HciReadBdAddrCmd (void)
HCI read BD address command.
Returns
None.
HciReadBufSizeCmd()
void HciReadBufSizeCmd (void)
HCI read buffer size command.
Returns
None.
HciReadLocalSupCodecCapCmd()
void HciReadLocalSupCodecCapCmd (HciReadLocalSupCodecCaps_t * pCodecParam)
HCI read local supported codec capabilities command.
Parameters
pCodecParam Parameters to read codec capablilties.
Returns
None.
References HciReadLocalSupCodecCaps_t::codingFmt, HciReadLocalSupCodecCaps_t::compId, HciReadLocalSupCodecCaps_t::direction, wsfMsgHdr_t::event, HCI_CODEC_TRANS_BIS_BIT, HCI_CODEC_TRANS_CIS_BIT, HCI_ERR_INVALID_PARAM, HCI_READ_LOCAL_SUP_CODEC_CAP_CMD_CMPL_CBACK_EVT, HCI_SUCCESS, hciReadLocalSupCodecCapCmdCmplEvt_t::hdr, PalCodecReadLocalSupportedCodecCapabilities(), wsfMsgHdr_t::status, hciReadLocalSupCodecCapCmdCmplEvt_t::status, HciReadLocalSupCodecCaps_t::transType, and HciReadLocalSupCodecCaps_t::vsCodecId.
HciReadLocalSupCodecsCmd()
void HciReadLocalSupCodecsCmd (void)
HCI read local supported codecs command.
Returns
None.
References wsfMsgHdr_t::event, HCI_CODEC_TRANS_BIS_BIT, HCI_CODEC_TRANS_CIS_BIT, HCI_MAX_CODEC, HCI_READ_LOCAL_SUP_CODECS_CMD_CMPL_CBACK_EVT, HCI_SUCCESS, hciReadLocalSupCodecsCmdCmplEvt_t::hdr, hciReadLocalSupCodecsCmdCmplEvt_t::numStdCodecs, hciReadLocalSupCodecsCmdCmplEvt_t::numVsCodecs, PalCodecReadLocalSupportedCodecs(), wsfMsgHdr_t::status, hciReadLocalSupCodecsCmdCmplEvt_t::status, hciReadLocalSupCodecsCmdCmplEvt_t::stdCodecs, hciReadLocalSupCodecsCmdCmplEvt_t::stdCodecTrans, hciReadLocalSupCodecsCmdCmplEvt_t::vsCodecs, and hciReadLocalSupCodecsCmdCmplEvt_t::vsCodecTrans.
HciReadLocalSupControllerDlyCmd()
void HciReadLocalSupControllerDlyCmd (HciReadLocalSupControllerDly_t * pDelayParam)
HCI read local supported controller delay command.
Parameters
pDelayParam Parameters to read controller delay.
Returns
None.
References HciReadLocalSupControllerDly_t::codingFmt, HciReadLocalSupControllerDly_t::compId, HciReadLocalSupControllerDly_t::direction, HCI_CODEC_TRANS_BIS_BIT, HCI_CODEC_TRANS_CIS_BIT, HCI_ERR_INVALID_PARAM, HCI_READ_LOCAL_SUP_CTR_DLY_CMD_CMPL_CBACK_EVT, HCI_SUCCESS, PalCodecReadLocalSupportedControllerDelay(), HciReadLocalSupControllerDly_t::transType, and HciReadLocalSupControllerDly_t::vsCodecId.
HciReadLocalSupFeatCmd()
void HciReadLocalSupFeatCmd (void)
HCI read local supported feature command.
Returns
None.
HciReadLocalVerInfoCmd()
void HciReadLocalVerInfoCmd (void)
HCI read local version info command.
Returns
None.
HciReadRemoteVerInfoCmd()
void HciReadRemoteVerInfoCmd (uint16_t handle)
HCI read remote version info command.
Parameters
handle Connection handle.
Returns
None.
None.
References LlReadRemoteVerInfo().
HciReadRssiCmd()
void HciReadRssiCmd (uint16_t handle)
HCI read RSSI command.
Parameters
handle Connection handle.
Returns
None.
None.
References wsfMsgHdr_t::event, hciReadRssiCmdCmplEvt_t::handle, HCI_READ_RSSI_CMD_CMPL_CBACK_EVT, hciReadRssiCmdCmplEvt_t::hdr, LlGetRssi(), wsfMsgHdr_t::param, hciReadRssiCmdCmplEvt_t::rssi, wsfMsgHdr_t::status, and hciReadRssiCmdCmplEvt_t::status.
HciReadTxPwrLvlCmd()
void HciReadTxPwrLvlCmd (uint16_t handle, uint8_t type)
HCI read Tx power level command.
Parameters
handle Connection handle.
type Type.
Returns
None.
None.
References wsfMsgHdr_t::event, hciReadTxPwrLvlCmdCmplEvt_t::handle, HCI_READ_TX_PWR_LVL_CMD_CMPL_CBACK_EVT, hciReadTxPwrLvlCmdCmplEvt_t::hdr, LlGetTxPowerLevel(), wsfMsgHdr_t::param, hciReadTxPwrLvlCmdCmplEvt_t::pwrLvl, wsfMsgHdr_t::status, and hciReadTxPwrLvlCmdCmplEvt_t::status.
HciResetCmd()
void HciResetCmd (void)
HCI reset command.
Returns
None.
References LlReset().
HciSetEventMaskCmd()
void HciSetEventMaskCmd (uint8_t * pEventMask)
HCI set event mask command.
Parameters
pEventMask Page 1 of the event mask.
Returns
None.
None.
HciSetEventMaskPage2Cmd()
void HciSetEventMaskPage2Cmd (uint8_t * pEventMask)
HCI set event page 2 mask command.
Parameters
pEventMask Page 2 of the event mask.
Returns
None.
HCI set event page 2 mask command.
Returns
None.
None.
HciTerminateBigCmd()
void HciTerminateBigCmd (uint8_t bigHandle, uint8_t reason)
HCI LE terminate BIG command.
Parameters
bigHandle Used to identify the BIG.
reason Termination reason.
Returns
None.
References HciLeTerminateBigCmplEvt_t::bigHandle, wsfMsgHdr_t::event, HCI_LE_TERM_BIG_CMPL_CBACK_EVT, HCI_SUCCESS, HciLeTerminateBigCmplEvt_t::hdr, LlTerminateBig(), wsfMsgHdr_t::param, HciLeTerminateBigCmplEvt_t::reason, and wsfMsgHdr_t::status.
HciVendorSpecificCmd()
void HciVendorSpecificCmd (uint16_t opcode, uint8_t len, uint8_t * pData)
HCI vencor specific command.
Parameters
opcode Opcode.
len Length of pData.
pData Command data.
Returns
None.
None.
References HCI_CMD_HDR_LEN.
HciWriteAuthPayloadTimeout()
void HciWriteAuthPayloadTimeout (uint16_t handle, uint16_t timeout)
HCI write authenticated payload timeout command.
Parameters
handle Connection handle.
timeout Timeout value.
Returns
None.
References wsfMsgHdr_t::event, hciWriteAuthPayloadToCmdCmplEvt_t::handle, HCI_WRITE_AUTH_PAYLOAD_TO_CMD_CMPL_CBACK_EVT, hciWriteAuthPayloadToCmdCmplEvt_t::hdr, LlWriteAuthPayloadTimeout(), wsfMsgHdr_t::status, and hciWriteAuthPayloadToCmdCmplEvt_t::status.