Cordio: BATTERY_SERVICE
BATTERY_SERVICE
Functions
void SvcBattAddGroup (void)
void SvcBattRemoveGroup (void)
void SvcBattCbackRegister (attsReadCback_t readCback, attsWriteCback_t writeCback)
void * SvcBattAddGroupDyn (void)
Battery Service Handles
enum
#define BATT_START_HDL 0x60
#define BATT_END_HDL (BATT_MAX_HDL - 1)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Battery Service Handles.
Enumerator
BATT_SVC_HDL
Battery service declaration.
BATT_LVL_CH_HDL
Battery level characteristic.
BATT_LVL_HDL
Battery level.
BATT_LVL_CH_CCC_HDL
Battery level CCCD.
BATT_MAX_HDL
Maximum handle.
Function Documentation
SvcBattAddGroup()
void SvcBattAddGroup (void)
Add the services to the attribute server.
Returns
None.
References AttsAddGroup().
SvcBattAddGroupDyn()
void* SvcBattAddGroupDyn (void)
Add the battery service using the dynamic attribute subsystem.
Returns
None.
References attBlChUuid, attChUuid, attCliChCfgUuid, attPrimSvcUuid, ATTS_PERMIT_READ, ATTS_PERMIT_WRITE, ATTS_SET_CCC, ATTS_SET_READ_CBACK, AttsDynAddAttr(), AttsDynAddAttrConst(), AttsDynCreateGroup(), BATT_END_HDL, BATT_START_HDL, and UINT16_TO_BYTES.
SvcBattCbackRegister()
void SvcBattCbackRegister (attsReadCback_t readCback, attsWriteCback_t writeCback)
Register callbacks for the service.
Parameters
readCback Read callback function.
writeCback Write callback function.
Returns
None.
SvcBattRemoveGroup()
void SvcBattRemoveGroup (void)
Remove the services from the attribute server.
Returns
None.
References AttsRemoveGroup(), and BATT_START_HDL.