Cordio: HUMAN_INTERFACE_DEVICE_PROFILE
HUMAN_INTERFACE_DEVICE_PROFILE
Data Structures
struct hidReportIdMap_t
struct hidConfig_t
Typedefs
typedef void(* hidOutputReportCback_t) (dmConnId_t connId, uint8_t id, uint16_t len, uint8_t *pReport)
typedef void(* hidFeatureReportCback_t) (dmConnId_t connId, uint8_t id, uint16_t len, uint8_t *pReport)
typedef void(* hidInfoCback_t) (dmConnId_t connId, uint8_t type, uint8_t value)
Functions
void HidSendInputReport (dmConnId_t connId, uint8_t reportId, uint16_t len, uint8_t *pValue)
void HidSetProtocolMode (uint8_t protocolMode)
uint8_t HidGetProtocolMode (void)
uint8_t HidGetControlPoint (void)
void HidInit (const hidConfig_t *pConfig)
uint8_t HidAttsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
Type of HID Information
#define HID_INFO_CONTROL_POINT 0
#define HID_INFO_PROTOCOL_MODE 1
HID Boot Report ID
#define HID_KEYBOARD_BOOT_ID 0xFF
#define HID_MOUSE_BOOT_ID 0xFE
Detailed Description
Data Structure Documentation
hidReportIdMap_t
struct hidReportIdMap_t
HID Report Type/ID to Attribute handle map item.
Data Fields
uint8_t type
uint8_t id
uint16_t handle
hidConfig_t
struct hidConfig_t
HID Profile Configuration.
Data Fields
hidReportIdMap_t * pReportIdMap
uint8_t reportIdMapSize
hidOutputReportCback_t outputCback
hidFeatureReportCback_t featureCback
hidInfoCback_t infoCback
Typedef Documentation
hidFeatureReportCback_t
typedef void(* hidFeatureReportCback_t) (dmConnId_t connId, uint8_t id, uint16_t len, uint8_t *pReport)
This callback function sends a received Feature Report to the application.
Parameters
connId The connection identifier.
id The ID of the report.
len The length of the report data in pReport.
pReport A buffer containing the report.
Returns
None.
hidInfoCback_t
typedef void(* hidInfoCback_t) (dmConnId_t connId, uint8_t type, uint8_t value)
This callback function notifies the application of a change in the protocol mode or control point from the host.
Parameters
connId The connection identifier.
mode The type of information (HID_INFO_CONTROL_POINT or HID_INFO_PROTOCOL_MODE)
value The value of the information
Returns
None.
hidOutputReportCback_t
typedef void(* hidOutputReportCback_t) (dmConnId_t connId, uint8_t id, uint16_t len, uint8_t *pReport)
This callback function sends a received Output Report to the application.
Parameters
connId The connection identifier.
id The ID of the report.
len The length of the report data in pReport.
pReport A buffer containing the report.
Returns
None.
Function Documentation
HidAttsWriteCback()
uint8_t HidAttsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
Called on an ATTS Write to the HID Service.
Parameters
connId DM connection identifier.
handle ATT handle.
operation ATT operation.
offset Write offset.
len Write length.
pValue Value to write.
pAttr Attribute to write.
Returns
ATT status.
ATT status.
References AttsSetAttr(), HID_CONTROL_POINT_HDL, HID_INFO_CONTROL_POINT, HID_INFO_PROTOCOL_MODE, HID_KEYBOARD_BOOT_OUT_HDL, HID_PROTOCOL_MODE_HDL, HID_REPORT_TYPE_FEATURE, HID_REPORT_TYPE_OUTPUT, HidSetProtocolMode(), hidReportIdMap_t::id, hidReportIdMap_t::type, and WSF_ASSERT.
HidGetControlPoint()
uint8_t HidGetControlPoint (void)
Gets the HID control point value.
Returns
The control point value (HID_CONTROL_POINT_SUSPEND or HID_CONTROL_POINT_RESUME).
The control point value (HID_CONTROL_POINT_SUSPEND or HID_CONTROL_POINT_RESUME).
References AttsGetAttr(), and HID_CONTROL_POINT_HDL.
HidGetProtocolMode()
uint8_t HidGetProtocolMode (void)
Gets the HID protocol mode value.
Returns
The protocol mode value (HID_PROTOCOL_MODE_REPORT or HID_PROTOCOL_MODE_BOOT).
The protocol mode value (HID_PROTOCOL_MODE_REPORT or HID_PROTOCOL_MODE_BOOT).
References AttsGetAttr(), and HID_PROTOCOL_MODE_HDL.
HidInit()
void HidInit (const hidConfig_t * pConfig)
Initialize the HID profile.
Parameters
pConfig HID Configuration structure
Returns
None.
References WSF_ASSERT.
HidSendInputReport()
void HidSendInputReport (dmConnId_t connId, uint8_t reportId, uint16_t len, uint8_t * pValue)
Sends an input report to the host.
Parameters
connId The connection ID
reportId The Report ID
len The length of the report in bytes
pValue A buffer containing the report
Returns
none.
References ATT_HANDLE_NONE, AttsHandleValueNtf(), AttsSetAttr(), and HID_REPORT_TYPE_INPUT.
HidSetProtocolMode()
void HidSetProtocolMode (uint8_t protocolMode)
Sets the HID protocol mode for keyboard and mouse devices that support Boot Mode.
Parameters
protocolMode The protocol mode (HID_PROTOCOL_MODE_REPORT or HID_PROTOCOL_MODE_BOOT)
Returns
None.
Parameters
protocolMode The protocol mode (HID_PROTOCOL_MODE_REPORT or HID_PROTOCOL_MODE_BOOT)
Returns
None.
References AttsSetAttr(), and HID_PROTOCOL_MODE_HDL.