Cordio: Time Client Model API
Time Client Model API
Data Structures
struct mmdlTimeSetParam_t
struct mmdlTimeZoneSetParam_t
struct mmdlTimeDeltaSetParam_t
struct mmdlTimeRoleSetParam_t
struct mmdlTimeClStatusEvent_t
struct mmdlTimeClZoneStatusEvent_t
struct mmdlTimeClDeltaStatusEvent_t
struct mmdlTimeClRoleStatusEvent_t
union mmdlTimeClEvent_t
Functions
void MmdlTimeClHandlerInit (wsfHandlerId_t handlerId)
void MmdlTimeClHandler (wsfMsgHdr_t *pMsg)
void MmdlTimeClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlTimeClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlTimeClZoneGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlTimeClZoneSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeZoneSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlTimeClDeltaGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlTimeClDeltaSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeDeltaSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlTimeClRoleGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlTimeClRoleSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeRoleSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlTimeClRegister (mmdlEventCback_t recvCback)
Variables
wsfHandlerId_t mmdlTimeClHandlerId
const meshMsgOpcode_t mmdlTimeClRcvdOpcodes []
Detailed Description
Data Structure Documentation
mmdlTimeSetParam_t
struct mmdlTimeSetParam_t
Model Time Client Set parameters structure.
Data Fields
mmdlTimeState_t state
Field Documentation
state
mmdlTimeState_t state
New Time State
mmdlTimeZoneSetParam_t
struct mmdlTimeZoneSetParam_t
Model Time Client Zone Set parameters structure.
Data Fields
mmdlTimeZoneState_t state
Field Documentation
state
mmdlTimeZoneState_t state
New Time Zone State
mmdlTimeDeltaSetParam_t
struct mmdlTimeDeltaSetParam_t
Model Time Client Delta Set parameters structure.
Data Fields
mmdlTimeDeltaState_t state
Field Documentation
state
mmdlTimeDeltaState_t state
New Time Delta State
mmdlTimeRoleSetParam_t
struct mmdlTimeRoleSetParam_t
Model Time Client Role Set parameters structure.
Data Fields
mmdlTimeRoleState_t state
Field Documentation
state
mmdlTimeRoleState_t state
New Time Role State
mmdlTimeClStatusEvent_t
struct mmdlTimeClStatusEvent_t
Time Client Model Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
mmdlTimeState_t state
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
serverAddr
meshAddress_t serverAddr
Server Address
state
mmdlTimeState_t state
Received state
mmdlTimeClZoneStatusEvent_t
struct mmdlTimeClZoneStatusEvent_t
Time Client Model Zone Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
uint8_t offsetCurrent
uint8_t offsetNew
uint64_t taiZoneChange
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
offsetCurrent
uint8_t offsetCurrent
Current local time zone offset
offsetNew
uint8_t offsetNew
Upcoming local time zone offset
serverAddr
meshAddress_t serverAddr
Server Address
taiZoneChange
uint64_t taiZoneChange
TAI Seconds time of the upcoming Time Zone Offset change
mmdlTimeClDeltaStatusEvent_t
struct mmdlTimeClDeltaStatusEvent_t
Time Client Model Delta Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
uint16_t deltaCurrent
uint16_t deltaNew
uint64_t deltaChange
Field Documentation
deltaChange
uint64_t deltaChange
TAI Seconds time of the upcoming TAI-UTC Delat change
deltaCurrent
uint16_t deltaCurrent
Current local time zone offset
deltaNew
uint16_t deltaNew
Upcoming diff between TAI and UTC in seconds
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
serverAddr
meshAddress_t serverAddr
Server Address
mmdlTimeClRoleStatusEvent_t
struct mmdlTimeClRoleStatusEvent_t
Time Client Model Role Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
uint8_t timeRole
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
serverAddr
meshAddress_t serverAddr
Server Address
timeRole
uint8_t timeRole
Time Role for element
mmdlTimeClEvent_t
union mmdlTimeClEvent_t
Time Client Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlTimeClStatusEvent_t statusEvent
mmdlTimeClZoneStatusEvent_t zoneStatusEvent
mmdlTimeClDeltaStatusEvent_t deltaStatusEvent
mmdlTimeClRoleStatusEvent_t roleStatusEvent
Field Documentation
deltaStatusEvent
mmdlTimeClDeltaStatusEvent_t deltaStatusEvent
State updated event. Used for MMDL_TIMEDELTA_CL_STATUS_EVENT.
hdr
wsfMsgHdr_t hdr
WSF message header
roleStatusEvent
mmdlTimeClRoleStatusEvent_t roleStatusEvent
State updated event. Used for MMDL_TIMEROLE_CL_STATUS_EVENT.
statusEvent
mmdlTimeClStatusEvent_t statusEvent
State updated event. Used for MMDL_TIME_CL_STATUS_EVENT.
zoneStatusEvent
mmdlTimeClZoneStatusEvent_t zoneStatusEvent
State updated event. Used for MMDL_TIMEZONE_CL_STATUS_EVENT.
Function Documentation
MmdlTimeClDeltaGet()
void MmdlTimeClDeltaGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Time Delta Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlTimeClDeltaSet()
void MmdlTimeClDeltaSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeDeltaSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Time Delta Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
MmdlTimeClGet()
void MmdlTimeClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Time Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlTimeClHandler()
void MmdlTimeClHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Time Client Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlTimeClHandlerInit()
void MmdlTimeClHandlerInit (wsfHandlerId_t handlerId)
Initializes the Mesh WSF handler.
Parameters
[in] handlerId WSF handler ID for Time Client Model.
Returns
None.
Parameters
[in] handlerId WSF handler ID for Level Client Model.
Returns
None.
References mmdlTimeClHandlerId.
MmdlTimeClRegister()
void MmdlTimeClRegister (mmdlEventCback_t recvCback)
Install the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlTimeClRoleGet()
void MmdlTimeClRoleGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Time Role Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlTimeClRoleSet()
void MmdlTimeClRoleSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeRoleSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Time Role Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
MmdlTimeClSet()
void MmdlTimeClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Time Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
MmdlTimeClZoneGet()
void MmdlTimeClZoneGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Time Zone Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlTimeClZoneSet()
void MmdlTimeClZoneSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlTimeZoneSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Time Zone Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
Variable Documentation
mmdlTimeClHandlerId
wsfHandlerId_t mmdlTimeClHandlerId
WSF handler id.
WSF handler id
mmdlTimeClRcvdOpcodes
const meshMsgOpcode_t mmdlTimeClRcvdOpcodes[]
Supported opcodes.
Supported opcodes