Cordio: Mesh Bearer API
Mesh Bearer API
Data Structures
struct meshBrConfig_t
struct meshBrPduStatus_t
union meshBrEventParams_t
Macros
#define MESH_BR_MAX_INTERFACES (MESH_ADV_MAX_INTERFACES + MESH_GATT_MAX_CONNECTIONS)
#define MESH_BR_INVALID_INTERFACE_ID 0xFF
#define MESH_BR_INTERFACE_ID_TYPE_MASK 0xF0
#define MESH_BR_INTERFACE_ID_INTERFACE_MASK 0x0F
#define MESH_BR_INTERFACE_ID_TYPE_OFFSET 5
#define MESH_BR_GET_BR_TYPE(brInterfaceId)
#define MESH_BR_ADV_IF_TO_BR_IF(interfaceId)
#define MESH_BR_IF_TO_ADV_IF(brInterfaceId)
#define MESH_BR_CONN_ID_TO_BR_IF(connId)
#define MESH_BR_IF_TO_CONN_ID(brInterfaceId)
Typedefs
typedef uint8_t meshBrInterfaceId_t
typedef uint8_t meshBrType_t
typedef uint8_t meshBrEvent_t
typedef void(* meshBrNwkPduRecvCback_t) (meshBrInterfaceId_t brInterfaceId, const uint8_t *pNwkPdu, uint8_t pduLen)
typedef void(* meshBrBeaconRecvCback_t) (meshBrInterfaceId_t brInterfaceId, const uint8_t *pBeaconData, uint8_t dataLen)
typedef void(* meshBrPbPduRecvCback_t) (meshBrInterfaceId_t brInterfaceId, const uint8_t *pPbPdu, uint8_t pduLen)
typedef void(* meshBrEventNotifyCback_t) (meshBrInterfaceId_t brInterfaceId, meshBrEvent_t event, const meshBrEventParams_t *pEventParams)
Enumerations
enum meshBrEventTypes
enum meshBrType
Functions
void MeshBrInit (void)
void MeshBrRegisterNwk (meshBrEventNotifyCback_t eventCback, meshBrNwkPduRecvCback_t nwkPduRecvCback)
void MeshBrRegisterNwkBeacon (meshBrEventNotifyCback_t eventCback, meshBrBeaconRecvCback_t beaconRecvCback)
void MeshBrRegisterPb (meshBrEventNotifyCback_t eventCback, meshBrPbPduRecvCback_t pbPduRecvCback)
void MeshBrRegisterPbBeacon (meshBrEventNotifyCback_t eventCback, meshBrBeaconRecvCback_t pbBcPduRecvCback)
bool_t MeshBrSendNwkPdu (meshBrInterfaceId_t brIfId, const uint8_t *pNwkPdu, uint8_t pduLen)
bool_t MeshBrSendBeaconPdu (meshBrInterfaceId_t brIfId, uint8_t *pBeaconData, uint8_t dataLen)
bool_t MeshBrSendPrvPdu (meshBrInterfaceId_t brIfId, const uint8_t *pPrvPdu, uint8_t pduLen)
bool_t MeshBrSendCfgPdu (meshBrInterfaceId_t brIfId, const uint8_t *pCfgPdu, uint8_t pduLen)
void MeshBrCloseIf (meshBrInterfaceId_t brIfId)
void MeshBrEnableGatt (void)
void MeshBrRegisterProxy (meshBrEventNotifyCback_t eventCback, meshBrNwkPduRecvCback_t pduRecvCback)
Detailed Description
Data Structure Documentation
meshBrConfig_t
struct meshBrConfig_t
Mesh Bearer configuration structure
Data Fields
meshBrType_t bearerType
Field Documentation
bearerType
meshBrType_t bearerType
Mesh Bearer interface type
meshBrPduStatus_t
struct meshBrPduStatus_t
Mesh Bearer PDU status structure
Data Fields
meshBrType_t bearerType
uint8_t * pPdu
Field Documentation
bearerType
meshBrType_t bearerType
Mesh Bearer interface type
pPdu
uint8_t* pPdu
Pointer to the delivered PDU
meshBrEventParams_t
union meshBrEventParams_t
Mesh Bearer Event notification union
Data Fields
meshBrConfig_t brConfig
meshBrPduStatus_t brPduStatus
Field Documentation
brConfig
meshBrConfig_t brConfig
MESH_BR_INTERFACE_OPENED_EVT MESH_BR_INTERFACE_CLOSED_EVT
brPduStatus
meshBrPduStatus_t brPduStatus
MESH_BR_INTERFACE_PACKET_SENT_EVT
Macro Definition Documentation
MESH_BR_ADV_IF_TO_BR_IF
#define MESH_BR_ADV_IF_TO_BR_IF (interfaceId)
Value:
(MESH_UTILS_BITMASK_SET(interfaceId, \
                                              (MESH_ADV_BEARER << MESH_BR_INTERFACE_ID_TYPE_OFFSET)))
Create bearer interface identifier from ADV interface identifier. See meshBrInterfaceId_t
MESH_BR_CONN_ID_TO_BR_IF
#define MESH_BR_CONN_ID_TO_BR_IF (connId)
Value:
(MESH_UTILS_BITMASK_SET(connId, \
                                          (MESH_GATT_BEARER << MESH_BR_INTERFACE_ID_TYPE_OFFSET)))
Create bearer interface identifier from GATT connection identifier. See meshBrInterfaceId_t
MESH_BR_GET_BR_TYPE
#define MESH_BR_GET_BR_TYPE (brInterfaceId)
Value:
(MESH_UTILS_BF_GET(brInterfaceId, \
                                              MESH_BR_INTERFACE_ID_TYPE_OFFSET, \
                                              MESH_BR_INTERFACE_ID_TYPE_OFFSET))
Extract bearer type from a bearer interface identifier. See meshBrInterfaceId_t
MESH_BR_IF_TO_ADV_IF
#define MESH_BR_IF_TO_ADV_IF (brInterfaceId)
Value:
(MESH_UTILS_BITMASK_CLR(brInterfaceId, \
                                              MESH_BR_INTERFACE_ID_TYPE_MASK))
Create ADV interface interface identifier from bearer identifier. See meshBrInterfaceId_t
MESH_BR_IF_TO_CONN_ID
#define MESH_BR_IF_TO_CONN_ID (brInterfaceId)
Value:
(MESH_UTILS_BITMASK_CLR(brInterfaceId, \
                                               MESH_BR_INTERFACE_ID_TYPE_MASK))
Create GATT connection identifier from bearer identifier. See meshBrInterfaceId_t
MESH_BR_INTERFACE_ID_INTERFACE_MASK
#define MESH_BR_INTERFACE_ID_INTERFACE_MASK 0x0F
Defines the bit mask for interface identifier inside the bearer interface identifier
MESH_BR_INTERFACE_ID_TYPE_MASK
#define MESH_BR_INTERFACE_ID_TYPE_MASK 0xF0
Defines the bit mask for bearer type inside the bearer interface identifier
MESH_BR_INTERFACE_ID_TYPE_OFFSET
#define MESH_BR_INTERFACE_ID_TYPE_OFFSET 5
Defines offset of the bearer type inside the bearer interface identifier
MESH_BR_INVALID_INTERFACE_ID
#define MESH_BR_INVALID_INTERFACE_ID 0xFF
Invalid Mesh Bearer interface ID value
MESH_BR_MAX_INTERFACES
#define MESH_BR_MAX_INTERFACES (MESH_ADV_MAX_INTERFACES + MESH_GATT_MAX_CONNECTIONS)
Maximum number of Mesh Bearer interfaces supported
Typedef Documentation
meshBrBeaconRecvCback_t
typedef void(* meshBrBeaconRecvCback_t) (meshBrInterfaceId_t brInterfaceId, const uint8_t *pBeaconData, uint8_t dataLen)
Mesh Beacon PDU received callback function pointer type.
Parameters
[in] brInterfaceId Unique Mesh Bearer interface ID.
[in] pBeaconData Pointer to the Beacon Data payload.
[in] dataLen Size of the Beacon Data payload.
Returns
None.
meshBrEvent_t
typedef uint8_t meshBrEvent_t
Mesh Bearer notification event type. See meshBrEventTypes
meshBrEventNotifyCback_t
typedef void(* meshBrEventNotifyCback_t) (meshBrInterfaceId_t brInterfaceId, meshBrEvent_t event, const meshBrEventParams_t *pEventParams)
Mesh Bearer event notification callback function pointer type.
Parameters
[in] brInterfaceId Unique Mesh Bearer interface ID.
[in] event Reason the callback is being invoked. See meshBrEvent_t
[in] pEventParams Pointer to the event parameters structure passed to the function. See meshBrEventParams_t
Returns
None.
Note
For the Mesh Bearer PDU transmission, the pEventParams contains the bearer PDU status structure. See meshBrPduStatus_t For interface specific events, the pEventParams contains the bearer configuration structure. See meshBrConfig_t For filtering specific events, the pEventParams contains the interface filter structure. See ::meshBrInterfaceFilter_t
meshBrInterfaceId_t
typedef uint8_t meshBrInterfaceId_t
Unique Mesh Bearer interface ID. The identifier is described as follows:
Bits 3-0 : The unique interface identifier for a specific bearer
Bits 7-4 : The bearer type. See meshBrType
meshBrNwkPduRecvCback_t
typedef void(* meshBrNwkPduRecvCback_t) (meshBrInterfaceId_t brInterfaceId, const uint8_t *pNwkPdu, uint8_t pduLen)
Mesh NWK PDU received on Bearer callback function pointer type.
Parameters
[in] brInterfaceId Unique Mesh Bearer interface ID.
[in] pNwkPdu Pointer to the Network PDU received.
[in] pduLen Size of the Network PDU received.
Returns
None.
meshBrPbPduRecvCback_t
typedef void(* meshBrPbPduRecvCback_t) (meshBrInterfaceId_t brInterfaceId, const uint8_t *pPbPdu, uint8_t pduLen)
Mesh Provisioning PDU received on Bearer callback function pointer type.
Parameters
[in] brInterfaceId Unique Mesh Bearer interface ID.
[in] pPbPdu Pointer to the Provisioning Bearer PDU received.
[in] pduLen Size of the Provisioning Bearer PDU received.
Returns
None.
meshBrType_t
typedef uint8_t meshBrType_t
Mesh Bearer interface type. See meshBrType
Enumeration Type Documentation
meshBrEventTypes
enum meshBrEventTypes
Mesh Bearer notification event types enumeration
Enumerator
MESH_BR_INTERFACE_OPENED_EVT
Bearer interface opened
MESH_BR_INTERFACE_CLOSED_EVT
Bearer interface closed
MESH_BR_INTERFACE_PACKET_SENT_EVT
Reference of sent packet
meshBrType
enum meshBrType
Mesh Bearer interface types enumeration
Enumerator
MESH_ADV_BEARER
Mesh Advertising Bearer
MESH_GATT_BEARER
Mesh GATT Bearer
MESH_INVALID_BEARER
Mesh Invalid Bearer type
Function Documentation
MeshBrCloseIf()
void MeshBrCloseIf (meshBrInterfaceId_t brIfId)
Closes the specified bearer interface. Works only for GATT interfaces.
Parameters
[in] brIfId Unique Mesh Bearer interface ID.
Returns
None.
Closes the specified bearer interface. Works only for GATT interfaces.
Parameters
[in] brIfId Unique Mesh Bearer interface ID.
Returns
None.
References MESH_BR_GET_BR_TYPE, MESH_BR_IF_TO_CONN_ID, MESH_BR_INVALID_INTERFACE_ID, MESH_GATT_BEARER, MeshGattCloseProxyConn(), and WSF_ASSERT.
MeshBrEnableGatt()
void MeshBrEnableGatt (void)
Initializes the GATT bearer functionality.
Returns
None.
References MeshGattInit(), and MeshGattRegister().
MeshBrInit()
void MeshBrInit (void)
Initializes the Mesh Bearer layer.
Returns
None.
References MeshAdvRegister().
MeshBrRegisterNwk()
void MeshBrRegisterNwk (meshBrEventNotifyCback_t eventCback, meshBrNwkPduRecvCback_t nwkPduRecvCback)
Registers the callback functions for event notification and received Network PDUs on the bearer interface.
Parameters
[in] eventCback Event notification callback for the upper layer.
[in] nwkPduRecvCback Callback to be invoked when a Mesh Bearer PDU is received on a specific bearer interface.
Returns
None.
MeshBrRegisterNwkBeacon()
void MeshBrRegisterNwkBeacon (meshBrEventNotifyCback_t eventCback, meshBrBeaconRecvCback_t beaconRecvCback)
Registers the callback functions for event notification and received Secure Network Beacon PDUs on the bearer interface.
Parameters
[in] eventCback Event notification callback for the upper layer.
[in] beaconRecvCback Callback to be invoked when a Mesh Beacon PDU is received on the bearer interface.
Returns
None.
MeshBrRegisterPb()
void MeshBrRegisterPb (meshBrEventNotifyCback_t eventCback, meshBrPbPduRecvCback_t pbPduRecvCback)
Registers the callback functions for event notification and received Provisioning PDUs on the bearer interface.
Parameters
[in] eventCback Event notification callback for the upper layer.
[in] pbPduRecvCback Callback to be invoked when a Mesh Bearer PDU is received on a specific bearer interface.
Returns
None.
MeshBrRegisterPbBeacon()
void MeshBrRegisterPbBeacon (meshBrEventNotifyCback_t eventCback, meshBrBeaconRecvCback_t pbBeaconPduRecvCback)
Registers the callback functions for event notification and received Unprovisioned Device Beacon PDUs on the bearer interface.
Parameters
[in] eventCback Event notification callback for the upper layer.
[in] pbBcPduRecvCback Callback to be invoked when a Mesh Bearer PDU is received on a specific bearer interface.
Returns
None.
Parameters
[in] eventCback Event notification callback for the upper layer.
[in] pbBeaconPduRecvCback Callback to be invoked when a Mesh Bearer PDU is received on a specific bearer interface.
Returns
None.
MeshBrRegisterProxy()
void MeshBrRegisterProxy (meshBrEventNotifyCback_t eventCback, meshBrNwkPduRecvCback_t pduRecvCback)
Registers the callback functions for event notification and received Proxy Configuration message on the bearer interface.
Parameters
[in] eventCback Event notification callback for the upper layer.
[in] pduRecvCback Callback to be invoked when a Mesh Bearer PDU is received on a specific bearer interface.
Returns
None.
MeshBrSendBeaconPdu()
bool_t MeshBrSendBeaconPdu (meshBrInterfaceId_t brIfId, uint8_t * pBeaconData, uint8_t dataLen)
Asynchronously sends a Mesh Beacon PDU on a bearer interface.
Parameters
[in] brIfId Unique Mesh Bearer interface ID.
[in] pBeaconData Pointer to the Beacon Data payload.
[in] dataLen Size of the Beacon Data payload.
Returns
True if message is sent to the interface, False otherwise.
MeshBrSendCfgPdu()
bool_t MeshBrSendCfgPdu (meshBrInterfaceId_t brIfId, const uint8_t * pCfgPdu, uint8_t pduLen)
Asynchronously sends a Proxy Configuration on a bearer interface.
Parameters
[in] brIfId Unique Mesh Bearer interface ID.
[in] pCfgPdu Pointer to the Proxy Configuration Data payload.
[in] pduLen Size of the Proxy Configuration Data payload.
Returns
True if message is sent to the interface, False otherwise.
MeshBrSendNwkPdu()
bool_t MeshBrSendNwkPdu (meshBrInterfaceId_t brIfId, const uint8_t * pNwkPdu, uint8_t pduLen)
Asynchronously sends a Mesh Network PDU on a bearer interface.
Parameters
[in] brIfId Unique Mesh Bearer interface ID.
[in] pNwkPdu Pointer to a buffer containing a Mesh Network PDU.
[in] pduLen Size of the Mesh Network PDU.
Returns
True if message is sent to the interface, False otherwise.
Note
A notification event will be sent with the transmission status when completed. See meshBrEvent_t and meshBrPduStatus_t
MeshBrSendPrvPdu()
bool_t MeshBrSendPrvPdu (meshBrInterfaceId_t brIfId, const uint8_t * pPrvPdu, uint8_t pduLen)
Asynchronously sends a Mesh Provisioning Bearer PDU on a bearer interface.
Parameters
[in] brIfId Unique Mesh Bearer interface ID.
[in] pPrvPdu Pointer to the Beacon Data payload.
[in] pduLen Size of the Beacon Data payload.
Returns
True if message is sent to the interface, False otherwise.