Cordio: HUMAN_INTERFACE_DEVICE_SERVICE
HUMAN_INTERFACE_DEVICE_SERVICE
Macros
#define HID_SVC_UUID ATT_UUID_HID_SERVICE
#define HID_MAX_REPORT_MAP_LEN 512
#define HID_MAX_REPORT_LEN 32
#define HID_INIT_REPORT_MAP_LEN 1
Functions
void SvcHidAddGroup (void)
void SvcHidRemoveGroup (void)
void SvcHidRegister (attsWriteCback_t writeCb, attsReadCback_t readCb)
void * SvcHidAddGroupDyn (void)
HID Spec Version
#define HID_VERSION 0x0111
HID Report Types
#define HID_REPORT_TYPE_INPUT 0x01
#define HID_REPORT_TYPE_OUTPUT 0x02
#define HID_REPORT_TYPE_FEATURE 0x03
HID Protocol Mode Types
#define HID_PROTOCOL_MODE_BOOT 0x00
#define HID_PROTOCOL_MODE_REPORT 0x01
HID Control Point Values
#define HID_CONTROL_POINT_SUSPEND 0x00
#define HID_CONTROL_POINT_RESUME 0x01
HID Service Handles
enum
#define HID_START_HDL 0x80
#define HID_END_HDL (HID_MAX_HDL - 1)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Proprietary Service Handles Common to HID Devices.
Enumerator
HID_SVC_HDL
Proprietary Service Declaration.
HID_INFO_CH_HDL
HID Information Characteristic Declaration.
HID_INFO_HDL
HID Information Value.
HID_REPORT_MAP_CH_HDL
HID Report Map Characteristic Declaration.
HID_REPORT_MAP_HDL
HID Report Map Value.
HID_EXTERNAL_REPORT_HDL
HID External Report Descriptor.
HID_CONTROL_POINT_CH_HDL
HID Control Point Characteristic Declaration.
HID_CONTROL_POINT_HDL
HID Control Point Value.
HID_KEYBOARD_BOOT_IN_CH_HDL
HID Keyboard Boot Input Characteristic Declaration.
HID_KEYBOARD_BOOT_IN_HDL
HID Keyboard Boot Input Value.
HID_KEYBOARD_BOOT_IN_CH_CCC_HDL
HID Keyboard Boot Input CCC Descriptor.
HID_KEYBOARD_BOOT_OUT_CH_HDL
HID Keyboard Boot Output Characteristic Declaration.
HID_KEYBOARD_BOOT_OUT_HDL
HID Keyboard Boot Output Value.
HID_MOUSE_BOOT_IN_CH_HDL
HID Mouse Boot Input Characteristic Declaration.
HID_MOUSE_BOOT_IN_HDL
HID Mouse Boot Input Value.
HID_MOUSE_BOOT_IN_CH_CCC_HDL
HID Mouse Boot Input CCC Descriptor.
HID_INPUT_REPORT_1_CH_HDL
HID Input Report Characteristic Declaration.
HID_INPUT_REPORT_1_HDL
HID Input Report Value.
HID_INPUT_REPORT_1_CH_CCC_HDL
HID Input Report CCC Descriptor.
HID_INPUT_REPORT_1_REFERENCE_HDL
HID Input Report Reference Descriptor.
HID_INPUT_REPORT_2_CH_HDL
HID Input Report Characteristic Declaration.
HID_INPUT_REPORT_2_HDL
HID Input Report Value.
HID_INPUT_REPORT_2_CH_CCC_HDL
HID Input Report CCC Descriptor.
HID_INPUT_REPORT_2_REFERENCE_HDL
HID Input Report Reference Descriptor.
HID_INPUT_REPORT_3_CH_HDL
HID Input Report Characteristic Declaration.
HID_INPUT_REPORT_3_HDL
HID Input Report Value.
HID_INPUT_REPORT_3_CH_CCC_HDL
HID Input Report CCC Descriptor.
HID_INPUT_REPORT_3_REFERENCE_HDL
HID Input Report Reference Descriptor.
HID_OUTPUT_REPORT_CH_HDL
HID Output Report Characteristic Declaration.
HID_OUTPUT_REPORT_HDL
HID Output Report Value.
HID_OUTPUT_REPORT_REFERENCE_HDL
HID Output Report Reference Descriptor.
HID_FEATURE_REPORT_CH_HDL
HID Feature Report Characteristic Declaration.
HID_FEATURE_REPORT_HDL
HID Feature Report Value.
HID_FEATURE_REPORT_REFERENCE_HDL
HID Feature Report Reference Descriptor.
HID_PROTOCOL_MODE_CH_HDL
HID Protocol Mode Characteristic Declaration.
HID_PROTOCOL_MODE_HDL
HID Protocol Mode Value.
HID_MAX_HDL
Maximum handle.
Function Documentation
SvcHidAddGroup()
void SvcHidAddGroup (void)
Add the services to the attribute server.
Returns
None.
Add the services to the attribute server.
Returns
None.
References AttsAddGroup().
SvcHidAddGroupDyn()
void* SvcHidAddGroupDyn (void)
Add the Hid Service using the dynamic attribute subsystem.
Returns
None.
References attChUuid, attCliChCfgUuid, attHidBkiChUuid, attHidBkoChUuid, attHidBmiChUuid, attHidErmUuid, attHidiChUuid, attHidRepChUuid, attHidRimUuid, attHidRmChUuid, attPrimSvcUuid, ATTS_PERMIT_READ, ATTS_SET_CCC, ATTS_SET_VARIABLE_LEN, ATTS_SET_WRITE_CBACK, AttsDynAddAttr(), AttsDynAddAttrConst(), AttsDynCreateGroup(), HID_END_HDL, HID_MAX_REPORT_LEN, HID_START_HDL, and UINT16_TO_BYTES.
SvcHidRegister()
void SvcHidRegister (attsWriteCback_t writeCb, attsReadCback_t readCb)
Register a read and write callback functions for the ATT Group.
Parameters
writeCb Write callback function
readCb Read callback function
Returns
None.
References attsGroup_t::readCback, and attsGroup_t::writeCback.
SvcHidRemoveGroup()
void SvcHidRemoveGroup (void)
Remove the services from the attribute server.
Returns
None.
References AttsRemoveGroup(), and HID_START_HDL.