Cordio: WSF_OS_API
WSF_OS_API
Data Structures
struct wsfMsgHdr_t
Macros
#define WSF_OS_DIAG FALSE
#define WSF_OS_MAX_SERVICE_FUNCTIONS 3
#define WSF_TASK_FROM_ID(handlerID) (((handlerID) >> 4) & 0x0F)
#define WSF_HANDLER_FROM_ID(handlerID) ((handlerID) & 0x0F)
#define WSF_INVALID_TASK_ID 0xFF
#define WSF_OS_GET_ACTIVE_HANDLER_ID() WSF_INVALID_TASK_ID
Typedefs
typedef uint8_t wsfHandlerId_t
typedef uint16_t wsfEventMask_t
typedef wsfHandlerId_t wsfTaskId_t
typedef uint8_t wsfTaskEvent_t
typedef bool_t(* WsfOsIdleCheckFunc_t) (void)
typedef void(* wsfEventHandler_t) (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
Functions
bool_t WsfOsActive (void)
void WsfSetEvent (wsfHandlerId_t handlerId, wsfEventMask_t event)
void WsfTaskLock (void)
void WsfTaskUnlock (void)
void WsfTaskSetReady (wsfHandlerId_t handlerId, wsfTaskEvent_t event)
wsfQueue_t * WsfTaskMsgQueue (wsfHandlerId_t handlerId)
wsfHandlerId_t WsfOsSetNextHandler (wsfEventHandler_t handler)
bool_t wsfOsReadyToSleep (void)
void wsfOsDispatcher (void)
void WsfOsInit (void)
void WsfOsEnterMainLoop (void)
void WsfOsRegisterSleepCheckFunc (WsfOsIdleCheckFunc_t func)
Variables
wsfHandlerId_t WsfActiveHandler
WSF Task Events
#define WSF_MSG_QUEUE_EVENT 0x01
#define WSF_TIMER_EVENT 0x02
#define WSF_HANDLER_EVENT 0x04
Detailed Description
Data Structure Documentation
wsfMsgHdr_t
struct wsfMsgHdr_t
Common message structure passed to event handler.
Data Fields
uint16_t param
uint8_t event
uint8_t status
Typedef Documentation
wsfEventHandler_t
typedef void(* wsfEventHandler_t) (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
Event handler callback function.
Parameters
event Mask of events set for the event handler.
pMsg Pointer to message for the event handler.
Function Documentation
WsfOsActive()
bool_t WsfOsActive (void)
Check if the WSF OS is active.
Returns
TRUE if active, FALSE if inactive.
wsfOsDispatcher()
void wsfOsDispatcher (void)
Event dispatched. Designed to be called repeatedly from infinite loop.
Returns
None.
References WSF_ASSERT, WSF_CS_ENTER, WSF_CS_EXIT, WSF_CS_INIT, WSF_MSG_QUEUE_EVENT, and WsfMsgDeq().
WsfOsInit()
void WsfOsInit (void)
Initialize OS control structure.
Returns
None.
References WSF_ASSERT, WSF_MSG_QUEUE_EVENT, and WsfMsgDeq().
wsfOsReadyToSleep()
bool_t wsfOsReadyToSleep (void)
Check if WSF is ready to sleep.
Returns
Return TRUE if there are no pending WSF task events set, FALSE otherwise.
Check if WSF is ready to sleep.
Returns
Return TRUE if there are no pending WSF task events set, FALSE otherwise.
WsfOsRegisterSleepCheckFunc()
void WsfOsRegisterSleepCheckFunc (WsfOsIdleCheckFunc_t func)
Register service check functions.
Parameters
func Service function.
WsfOsSetNextHandler()
wsfHandlerId_t WsfOsSetNextHandler (wsfEventHandler_t handler)
Set the next WSF handler function in the WSF OS handler array. This function should only be called as part of the OS initialization procedure.
Parameters
handler WSF handler function.
Returns
WSF handler ID for this handler.
Set the next WSF handler function in the WSF OS handler array. This function should only be called as part of the OS initialization procedure.
Parameters
handler WSF handler function.
Returns
WSF handler ID for this handler.
References WSF_ASSERT.
WsfSetEvent()
void WsfSetEvent (wsfHandlerId_t handlerId, wsfEventMask_t event)
Set an event for an event handler.
Parameters
handlerId Handler ID.
event Event or events to set.
References WSF_ASSERT, WSF_CS_INIT, and WSF_HANDLER_FROM_ID.
WsfTaskMsgQueue()
wsfQueue_t* WsfTaskMsgQueue (wsfHandlerId_t handlerId)
Return the task message queue used by the given handler.
Parameters
handlerId Event handler ID.
Returns
Task message queue.
Return the task message queue used by the given handler.
Parameters
handlerId Event handler ID.
Returns
Task message queue.
References WSF_ASSERT.
WsfTaskSetReady()
void WsfTaskSetReady (wsfHandlerId_t handlerId, wsfTaskEvent_t event)
Set the task used by the given handler as ready to run.
Parameters
handlerId Event handler ID.
event Task event mask.
References WSF_ASSERT, WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
WsfTaskUnlock()
void WsfTaskUnlock (void)
Unlock task scheduling.
Unlock task scheduling.
References WsfCsExit().
Variable Documentation
WsfActiveHandler
wsfHandlerId_t WsfActiveHandler
Diagnostic Task Identifier.
Active task handler ID.