Cordio: CYCLING_POWER_PROFILE
CYCLING_POWER_PROFILE
Functions
void CppsConnOpen (dmConnId_t connId)
void CppsSendPowerMeasurement (dmConnId_t connId)
void CppsSetParameter (uint8_t type, uint32_t value)
void CppsSetSensorLocation (uint8_t location)
void CppsSetFeatures (uint32_t features)
Cycle Power Measurement Types
#define CPP_PM_PARAM_INSTANTANEOUS_POWER 0 /* Instantaneous Power Measurement */
#define CPP_PM_PARAM_PEDAL_POWER 1 /* Pedal Power Balance */
#define CPP_PM_PARAM_ACCUMULATED_TORQUE 2 /* Accumulated Torque */
#define CPP_PM_PARAM_WHEEL_REVOLUTIONS 3 /* Wheel Revolution */
#define CPP_PM_PARAM_LAST_WHEEL_REV_TIME 4 /* Last Wheel Revolution Event Time */
#define CPP_PM_PARAM_CRANK_REVOLUTIONS 5 /* Crank Revolution */
#define CPP_PM_PARAM_LAST_CRANK_TIME 6 /* Last Crank Revolution Event Time */
#define CPP_PM_PARAM_MAX_FORCE_MAGNITUDE 7 /* Max Extreme Force Magnitudes */
#define CPP_PM_PARAM_MIN_FORCE_MAGNITUDE 8 /* Min Extreme Force Magnitudes */
#define CPP_PM_PARAM_MAX_TORQUE_MAGNITUDE 9 /* Max Extreme Torque Magnitudes */
#define CPP_PM_PARAM_MIN_TORQUE_MAGNITUDE 10 /* Min Extreme Torque Magnitudes */
#define CPP_PM_PARAM_MAX_EXTREME_ANGLE 11 /* Max Extreme Angles */
#define CPP_PM_PARAM_MIN_EXTREME_ANGLE 12 /* Min Extreme Angles */
#define CPP_PM_PARAM_TOP_DEAD_SPOT 13 /* Top Dead Spot Angle */
#define CPP_PM_PARAM_BOTTOM_DEAD_SPOT 14 /* Bottom Dead Spot Angle */
#define CPP_PM_PARAM_ACCUMULATED_ENERGY 15 /* Accumulated Energy */
Detailed Description
Function Documentation
CppsConnOpen()
void CppsConnOpen (dmConnId_t connId)
Setup connection specific variables.
Parameters
connId Connection ID
Returns
none
CppsSendPowerMeasurement()
void CppsSendPowerMeasurement (dmConnId_t connId)
Notifies the collector of a Cycle Power Measurement.
Parameters
connId Connection ID
Returns
none
References ATT_VALUE_NTF_LEN, AttGetMtu(), AttsHandleValueNtf(), CPS_CPM_HDL, UINT16_TO_BSTREAM, UINT16_TO_BUF, UINT24_TO_BSTREAM, UINT32_TO_BSTREAM, and UINT8_TO_BSTREAM.
CppsSetFeatures()
void CppsSetFeatures (uint32_t features)
Set the features attribute.
Parameters
features Features bitmask.
Returns
none
References AttsSetAttr(), CPS_CPF_HDL, and UINT32_TO_BYTES.
CppsSetParameter()
void CppsSetParameter (uint8_t type, uint32_t value)
Set a cycle measurement parameter.
Parameters
type Parameter identifier
value Measurement value.
Returns
none
Set a cycle measurement parameter.
Parameters
type Parameter identifier
value Measurement value.
Returns
none
CppsSetSensorLocation()
void CppsSetSensorLocation (uint8_t location)
Set the sensor location attribute.
Parameters
location Sensor Location.
Returns
none
References AttsSetAttr(), and CPS_CPSL_HDL.