Cordio: ASSET_TRACKING_PROFILE_SERVER
ASSET_TRACKING_PROFILE_SERVER
Functions
void AtpsInit (void)
void AtpsSetAntennaIds (dmConnId_t connId, uint8_t numAntenna, uint8_t *pAntennaIds)
void AtpsProcDmMsg (dmEvt_t *pEvt)
Detailed Description
Function Documentation
AtpsInit()
void AtpsInit (void)
Asset Tracking Profile server initialization.
Returns
None.
References SvcCteAddGroup(), and SvcCteCbackRegister().
AtpsProcDmMsg()
void AtpsProcDmMsg (dmEvt_t * pEvt)
Called by application to notify the Asset Tracking Profile server of DM Events.
Parameters
pEvt Pointer to the DM Event.
Returns
None.
References ATT_ERR_WRITE_REJ, ATT_SUCCESS, AttsContinueWriteReq(), CTE_ENABLE_ACL_BIT, CTE_ENABLE_HDL, hciLeReadAntennaInfoCmdCmplEvt_t::cteMaxLen, DM_CONN_CTE_RSP_START_IND, DM_CONN_CTE_RSP_STOP_IND, DM_CONN_CTE_TX_CFG_IND, DM_CTE_REQ_FAIL_IND, DM_READ_ANTENNA_INFO_IND, DM_RESET_CMPL_IND, DmConnCteRspStart(), DmReadAntennaInfo(), wsfMsgHdr_t::event, HCI_SUCCESS, dmEvt_t::hdr, hciLeReadAntennaInfoCmdCmplEvt_t::numAntennae, wsfMsgHdr_t::param, dmEvt_t::readAntennaInfo, wsfMsgHdr_t::status, hciLeReadAntennaInfoCmdCmplEvt_t::switchPatternMaxLen, and hciLeReadAntennaInfoCmdCmplEvt_t::switchSampleRates.
AtpsSetAntennaIds()
void AtpsSetAntennaIds (dmConnId_t connId, uint8_t numAntenna, uint8_t * pAntennaIds)
Set the antenna identifiers for a connection ID.
Parameters
connId Connection identifier.
numAntenna Number of antenna and len of pAntennaIds in bytes.
pAntennaIds Array containing identifiers of antenna for this connection.
Returns
None.
References DM_CONN_ID_NONE, DM_CONN_MAX, and WSF_ASSERT.