Cordio: LL_INIT_API
LL_INIT_API
Data Structures
struct LlInitRtCfg_t
Macros
#define INIT_BROADCASTER
#define BT_VER LL_VER_BT_CORE_SPEC_5_2
Functions
uint32_t LlInit (LlInitRtCfg_t *pCfg)
uint32_t LlInitControllerInit (LlInitRtCfg_t *pCfg)
uint32_t LlInitSetBbRtCfg (const BbRtCfg_t *pBbRtCfg, const uint8_t wlSizeCfg, const uint8_t rlSizeCfg, const uint8_t plSizeCfg, uint8_t *pFreeMem, uint32_t freeMemAvail)
uint32_t LlInitSetLlRtCfg (const LlRtCfg_t *pLlRtCfg, uint8_t *pFreeMem, uint32_t freeMemAvail)
void LlInitBbInit (void)
void LlInitSchInit (void)
void LlInitLlInit (void)
void LlInitChciTrInit (uint16_t maxAclLen, uint16_t maxIsoLen)
void LlInitLhciInit (void)
void LlMathSetSeed (const uint32_t *pSeed)
void LlInitLhciHandler (void)
Detailed Description
Data Structure Documentation
LlInitRtCfg_t
struct LlInitRtCfg_t
Runtime configuration parameters.
Data Fields
const BbRtCfg_t * pBbRtCfg
const uint8_t wlSizeCfg
const uint8_t rlSizeCfg
const uint8_t plSizeCfg
const LlRtCfg_t * pLlRtCfg
uint8_t * pFreeMem
uint32_t freeMemAvail
Field Documentation
freeMemAvail
uint32_t freeMemAvail
Amount of free memory available, returns adjusted amount of free memory.
pBbRtCfg
const BbRtCfg_t* pBbRtCfg
BB runtime configuration.
pFreeMem
uint8_t* pFreeMem
Pointer to free memory, returns adjusted location of free memory.
pLlRtCfg
const LlRtCfg_t* pLlRtCfg
LL runtime configuration.
plSizeCfg
const uint8_t plSizeCfg
Periodic list size configuration.
rlSizeCfg
const uint8_t rlSizeCfg
Resolving list size configuration.
wlSizeCfg
const uint8_t wlSizeCfg
Whitelist size configuration.
Function Documentation
LlInit()
uint32_t LlInit (LlInitRtCfg_t * pCfg)
Initialize configuration.
Parameters
pCfg Runtime configuration.
Returns
Memory used.
References LlInitRtCfg_t::freeMemAvail, LlInitBbInit(), LlInitLlInit(), LlInitSchInit(), LlInitSetBbRtCfg(), LlInitSetLlRtCfg(), LlInitRtCfg_t::pBbRtCfg, LlInitRtCfg_t::pFreeMem, LlInitRtCfg_t::pLlRtCfg, LlInitRtCfg_t::plSizeCfg, LlInitRtCfg_t::rlSizeCfg, and LlInitRtCfg_t::wlSizeCfg.
LlInitChciTrInit()
void LlInitChciTrInit (uint16_t maxAclLen, uint16_t maxIsoSduLen)
Initialize controller HCI transport.
Parameters
maxAclLen Maximum ACL data length.
maxIsoSduLen Maximum ISO SDU data length.
References WsfOsSetNextHandler().
LlInitControllerInit()
uint32_t LlInitControllerInit (LlInitRtCfg_t * pCfg)
Initialize controller configuration.
Parameters
pCfg Runtime configuration.
Returns
Memory used.
References LlInit(), LlInitChciTrInit(), LlInitLhciHandler(), LlInitLhciInit(), LlRtCfg_t::maxAclLen, LlRtCfg_t::maxIsoSduLen, and LlInitRtCfg_t::pLlRtCfg.
LlInitLhciHandler()
void LlInitLhciHandler (void)
LL initialization for controller configuration.
Copyright (c) 2013-2019 Arm Ltd. All Rights Reserved.
Copyright (c) 2019-2020 Packetcraft, Inc.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Initialize controller LHCI handler.
References WsfOsSetNextHandler().
LlInitSetBbRtCfg()
uint32_t LlInitSetBbRtCfg (const BbRtCfg_t * pBbRtCfg, const uint8_t wlSizeCfg, const uint8_t rlSizeCfg, const uint8_t plSizeCfg, uint8_t * pFreeMem, uint32_t freeMemAvail)
Set BB runtime configuration.
Parameters
pBbRtCfg BB runtime configuration (must be static).
wlSizeCfg Whitelist size.
rlSizeCfg Resolving list size.
plSizeCfg Periodic list size.
pFreeMem Free memory.
freeMemAvail Amount of free memory in bytes.
Returns
Amount of free memory consumed.
References BbBleInitPeriodicList(), BbBleInitResolvingList(), BbBleInitWhiteList(), and BbInitRunTimeCfg().
LlInitSetLlRtCfg()
uint32_t LlInitSetLlRtCfg (const LlRtCfg_t * pLlRtCfg, uint8_t * pFreeMem, uint32_t freeMemAvail)
Set LL runtime configuration.
Parameters
pLlRtCfg LL runtime configuration (must be static).
pFreeMem Free memory.
freeMemAvail Amount of free memory in bytes.
Returns
Amount of free memory consumed.
References LlInitBisMem(), LlInitCisMem(), LlInitConnMem(), LlInitExtAdvMem(), LlInitExtScanMem(), LlInitIsoMem(), and LlInitRunTimeCfg().
LlMathSetSeed()
void LlMathSetSeed (const uint32_t * pSeed)
Initialize random number seeds.
Parameters
pSeed Pointer to initial seed for random numbers.