Cordio: URIBEACON_CONFIGURATION_PROFILE
URIBEACON_CONFIGURATION_PROFILE
Macros
#define URICFG_UUID_BYTES(id)
#define URICFG_SERVICE_UUID 0xFED8
Typedefs
typedef void(* uriCfgAttWriteCback_t) (uint16_t handle, uint16_t valueLen, const uint8_t *pValue)
typedef void(* uriCfgLockChangeCback_t) (uint8_t lockState, const uint8_t *pLock)
Enumerations
enum
enum
Functions
void UriCfgStart (const uint8_t *pUriData, uint8_t uriDataLen, uint8_t uriFlags, int8_t *pAdvTxPwrLevels, uint8_t txPwrMode, uint16_t beaconPeriod)
void UriCfgStop (void)
void UriCfgAttWriteCbackRegister (uriCfgAttWriteCback_t cback)
void UriCfgMakeLockable (uint8_t lockState, uint8_t *pLock, uriCfgLockChangeCback_t cback)
void UriCfgSetUriDataResetValue (const uint8_t *pUriData)
URI Config Attributes Sizes
#define URICFG_MAXSIZE_URIDATA_ATT 18
#define URICFG_SIZE_TXPWRLEVELS_ATT 4
#define URICFG_SIZE_LOCK_ATT 16
Beacon period Attribute Values
#define URICFG_ATT_BEACONPERIOD_MIN 20
#define URICFG_ATT_BEACONPERIOD_MAX 10240
#define URICFG_ATT_BEACONPERIOD_DISABLE 0
Default (Reset) Values of Attributes
#define URICFG_ATT_URIFLAGS_DEFAULT 0x00
#define URICFG_ATT_TXPWRMODE_DEFAULT URICFG_ATT_TXPWRMODE_LOW
#define URICFG_ATT_BEACONPERIOD_DEFAULT 1000
#define URICFG_ATT_LOCK_DEFAULT_BYTES
Detailed Description
Typedef Documentation
uriCfgAttWriteCback_t
typedef void(* uriCfgAttWriteCback_t) (uint16_t handle, uint16_t valueLen, const uint8_t *pValue)
Attribute write callback.
Parameters
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
uriCfgLockChangeCback_t
typedef void(* uriCfgLockChangeCback_t) (uint8_t lockState, const uint8_t *pLock)
Lock change callback.
Parameters
lockState New lock state.
lock Lock value.
Returns
None.
Function Documentation
UriCfgAttWriteCbackRegister()
void UriCfgAttWriteCbackRegister (uriCfgAttWriteCback_t cback)
Register callback for written UriBeacon attributes.
Parameters
cback Callback to invoke when an attribute changes.
Returns
None.
UriCfgMakeLockable()
void UriCfgMakeLockable (uint8_t lockState, uint8_t * pLock, uriCfgLockChangeCback_t cback)
Make UriBeacon lockable.
Parameters
lockState Initial lock state value.
pLock Initial lock value.
cback Callback to invoke when lock changes.
Returns
None.
Parameters
lockState Initial lock state value.
lock Initial lock value.
cback Callback to invoke when lock changes.
Returns
None.
References AttsSetAttr(), URICFG_HANDLE_LOCK, URICFG_HANDLE_LOCKSTATE, and URICFG_SIZE_LOCK_ATT.
UriCfgSetUriDataResetValue()
void UriCfgSetUriDataResetValue (const uint8_t * pUriData)
Set reset value of URI data.
Parameters
pUriData Reset value of URI data.
Returns
None.
References URICFG_MAXSIZE_URIDATA_ATT.
UriCfgStart()
void UriCfgStart (const uint8_t * pUriData, uint8_t uriDataLen, uint8_t uriFlags, int8_t * pAdvTxPwrLevels, uint8_t txPwrMode, uint16_t beaconPeriod)
Start UriBeacon configuration service.
Parameters
pUriData Initial URI data value
uriDataLen Length of URI data value
uriFlags Initial URI flags value
pAdvTxPwrLevels Initial advertised tx power levels value
txPwrMode Initial tx power mode value
beaconPeriod Initial beacon period value
Returns
None.
Parameters
pUriData Initial URI data value
uriDataLen Length of URI data value
uriFlags Initial URI flags value
advTxPwrLevels Initial advertised tx power levels value
txPwrMode Initial tx power mode value
beaconPeriod Initial beacon period value
Returns
None.
References AttsSetAttr(), SvcUriCfgAddGroup(), SvcUriCfgCbackRegister(), UINT16_TO_BYTES, URICFG_HANDLE_BEACONPERIOD, URICFG_HANDLE_LOCKSTATE, URICFG_HANDLE_TXPWRLEVELS, URICFG_HANDLE_TXPWRMODE, URICFG_HANDLE_URIDATA, URICFG_HANDLE_URIFLAGS, URICFG_MAXSIZE_URIDATA_ATT, and URICFG_SIZE_TXPWRLEVELS_ATT.
UriCfgStop()
void UriCfgStop (void)
Stop UriBeacon configuration service.
Returns
None.
Stop UriBeacon configuration service.
Returns
None.
References SvcUriCfgRemoveGroup().