Cordio: STACK_SECURITY_API
STACK_SECURITY_API
Data Structures
struct secAes_t
struct secCmacMsg_t
struct secCcmEncMsg_t
struct secCcmDecMsg_t
union secMsg_t
struct secEccKey_t
struct secEccSharedSec_t
struct secEccMsg_t
Macros
#define SEC_CMAC_KEY_LEN 16
#define SEC_AES_BLK_LEN 16
#define SEC_CMAC_HASH_LEN 16
#define SEC_ECC_KEY_LEN 32
#define SEC_TOKEN_INVALID 0xFF
Typedefs
typedef void(* SecBlkEncFunc_t) (uint8_t *pKey, uint8_t *pMessage, void *pParam)
CCM-Mode algorithm lengths
#define SEC_CCM_KEY_LEN 16
#define SEC_CCM_MAX_ADDITIONAL_LEN ((1<<16) - (1<<8))
#define SEC_CCM_L 2
#define SEC_CCM_NONCE_LEN (15-SEC_CCM_L)
Security Initialization Functions
void SecInit (void)
void SecRandInit (void)
void SecAesInit (void)
void SecAesRevInit (void)
void SecCmacInit (void)
void SecCcmInit (void)
void SecEccInit (void)
Security AES, CMAC and CCM Functions
uint8_t SecAes (uint8_t *pKey, uint8_t *pPlaintext, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
uint8_t SecAesRev (uint8_t *pKey, uint8_t *pPlaintext, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
bool_t SecCmac (const uint8_t *pKey, uint8_t *pPlaintext, uint16_t textLen, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
bool_t SecCcmEnc (const uint8_t *pKey, uint8_t *pNonce, uint8_t *pPlainText, uint16_t textLen, uint8_t *pClear, uint16_t clearLen, uint8_t micLen, uint8_t *pResult, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
bool_t SecCcmDec (const uint8_t *pKey, uint8_t *pNonce, uint8_t *pCypherText, uint16_t textLen, uint8_t *pClear, uint16_t clearLen, uint8_t *pMic, uint8_t micLen, uint8_t *pResult, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Security ECC Functions
bool_t SecEccGenKey (wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
bool_t SecEccGenSharedSecret (secEccKey_t *pKey, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Security Random Number Generator Functions
void SecRand (uint8_t *pRand, uint8_t randLen)
Detailed Description
Data Structure Documentation
secAes_t
struct secAes_t
AES Security callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
uint8_t * pCiphertext
Field Documentation
hdr
wsfMsgHdr_t hdr
Header.
pCiphertext
uint8_t* pCiphertext
Pointer to 16 bytes of ciphertext data.
secCmacMsg_t
struct secCmacMsg_t
CMAC Security callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
uint8_t * pCiphertext
uint8_t * pPlainText
Field Documentation
hdr
wsfMsgHdr_t hdr
Header.
pCiphertext
uint8_t* pCiphertext
Pointer to 16 bytes of ciphertext data.
pPlainText
uint8_t* pPlainText
Pointer to pPlaintext parameter passed to SecCmac.
secCcmEncMsg_t
struct secCcmEncMsg_t
CCM-Mode encrypt callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
uint8_t * pCiphertext
uint16_t textLen
Field Documentation
hdr
wsfMsgHdr_t hdr
Header.
pCiphertext
uint8_t* pCiphertext
Pointer to ciphertext data.
textLen
uint16_t textLen
Length of pCiphertext in bytes.
secCcmDecMsg_t
struct secCcmDecMsg_t
CCM-Mode decrypt and authenticate callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
uint8_t * pText
uint8_t * pResult
uint16_t textLen
bool_t success
Field Documentation
hdr
wsfMsgHdr_t hdr
Header.
pResult
uint8_t* pResult
Pointer to result buffer (passed into SecCcmDec).
pText
uint8_t* pText
Pointer to decrypted text within result buffer.
success
bool_t success
TRUE if message is authenticated.
textLen
uint16_t textLen
Length of pText in bytes.
secMsg_t
union secMsg_t
Generic security callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
secAes_t aes
secCmacMsg_t cmac
secCcmEncMsg_t ccmEnc
secCcmDecMsg_t ccmDec
Field Documentation
aes
secAes_t aes
AES complete message.
ccmDec
secCcmDecMsg_t ccmDec
CCM-Mode Decrypt complete message.
ccmEnc
secCcmEncMsg_t ccmEnc
CCM-Mode Encrypt complete message.
cmac
secCmacMsg_t cmac
CMAC complete message.
hdr
wsfMsgHdr_t hdr
Header.
secEccKey_t
struct secEccKey_t
ECC Security public/private key pair.
Data Fields
uint8_t pubKey_x [SEC_ECC_KEY_LEN]
uint8_t pubKey_y [SEC_ECC_KEY_LEN]
uint8_t privKey [SEC_ECC_KEY_LEN]
Field Documentation
privKey
uint8_t privKey[SEC_ECC_KEY_LEN]
ECC private key.
pubKey_x
uint8_t pubKey_x[SEC_ECC_KEY_LEN]
x component of ECC public key.
pubKey_y
uint8_t pubKey_y[SEC_ECC_KEY_LEN]
y component of ECC public key.
secEccSharedSec_t
struct secEccSharedSec_t
ECC security DH Key shared secret.
Data Fields
uint8_t secret [SEC_ECC_KEY_LEN]
Field Documentation
secret
uint8_t secret[SEC_ECC_KEY_LEN]
DH Key Shared secret.
secEccMsg_t
struct secEccMsg_t
ECC Security callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
union {
secEccSharedSec_t sharedSecret
secEccKey_t key
bool_t keyValid
} data
Field Documentation
data
union { ... } data
ECC message data union.
hdr
wsfMsgHdr_t hdr
Header.
key
secEccKey_t key
ECC public/private key pair.
keyValid
bool_t keyValid
TRUE if ECC public/private key pair is valid.
sharedSecret
secEccSharedSec_t sharedSecret
Shared secret.
Function Documentation
SecAes()
uint8_t SecAes (uint8_t * pKey, uint8_t * pPlaintext, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Execute an AES calculation. When the calculation completes, a WSF message will be sent to the specified handler. This function returns a token value that the client can use to match calls to this function with messages.
Parameters
pKey Pointer to 16 byte key.
pPlaintext Pointer to 16 byte plaintext.
handlerId WSF handler ID.
param Client-defined parameter returned in message.
event Event for client's WSF handler.
Returns
Token value.
References Calc128Cpy(), hciLeEncryptCmdCmplEvt_t::data, wsfMsgHdr_t::event, HciLeEncryptCmd(), secMsg_t::hdr, hciEvt_t::leEncryptCmdCmpl, wsfMsgHdr_t::param, secAes_t::pCiphertext, SEC_TOKEN_INVALID, wsfMsgHdr_t::status, WsfMsgAlloc(), WsfMsgEnq(), and WsfMsgSend().
SecAesInit()
void SecAesInit (void)
Initialize the AES service. This function should only be called once upon system initialization.
Returns
None.
Initialize the AES service. This function should only be called once upon system initialization.
Parameters
none.
Returns
none.
SecAesRev()
uint8_t SecAesRev (uint8_t * pKey, uint8_t * pPlaintext, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Execute an AES calculation. When the calculation completes, a WSF message will be sent to the specified handler. This function returns a token value that the client can use to match calls to this function with messages. Note this version reverses the key and plaintext bytes.
Parameters
pKey Pointer to 16 byte key.
pPlaintext Pointer to 16 byte plaintext.
handlerId WSF handler ID.
param Client-defined parameter returned in message.
event Event for client's WSF handler.
Returns
Token value.
References Calc128Cpy(), hciLeEncryptCmdCmplEvt_t::data, wsfMsgHdr_t::event, secMsg_t::hdr, hciEvt_t::leEncryptCmdCmpl, wsfMsgHdr_t::param, secAes_t::pCiphertext, SEC_TOKEN_INVALID, wsfMsgHdr_t::status, WsfMsgAlloc(), and WsfMsgSend().
SecAesRevInit()
void SecAesRevInit (void)
Initialize the AES (reverse) service. This function should only be called once upon system initialization.
Returns
None.
Initialize the AES (reverse) service. This function should only be called once upon system initialization.
Parameters
none.
Returns
none.
SecCcmDec()
bool_t SecCcmDec (const uint8_t * pKey, uint8_t * pNonce, uint8_t * pCypherText, uint16_t textLen, uint8_t * pClear, uint16_t clearLen, uint8_t * pMic, uint8_t micLen, uint8_t * pResult, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Execute the CCM-Mode verify and decrypt algorithm.
Parameters
pKey Pointer to encryption key (SEC_CCM_KEY_LEN bytes).
pNonce Pointer to nonce (SEC_CCM_NONCE_LEN bytes).
pCypherText Pointer to text to decrypt.
textLen Length of pCypherText in bytes.
pClear Pointer to additional, unencrypted authentication text.
clearLen Length of pClear in bytes.
pMic Pointer to authentication digest.
micLen Size of MIC in bytes (4, 8 or 16).
pResult Buffer to hold result (returned in complete event).
handlerId Task handler ID to receive complete event.
param Optional parameter passed in complete event.
event Event ID of complete event.
Returns
TRUE if successful, else FALSE.
SecCcmEnc()
bool_t SecCcmEnc (const uint8_t * pKey, uint8_t * pNonce, uint8_t * pPlainText, uint16_t textLen, uint8_t * pClear, uint16_t clearLen, uint8_t micLen, uint8_t * pResult, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Execute the CCM-Mode encryption algorithm.
Parameters
pKey Pointer to encryption key (SEC_CCM_KEY_LEN bytes).
pNonce Pointer to nonce (SEC_CCM_NONCE_LEN bytes).
pPlainText Pointer to text to encrypt.
textLen Length of pPlainText in bytes.
pClear Pointer to additional, unencrypted authentication text.
clearLen Length of pClear in bytes.
micLen Size of MIC in bytes (4, 8 or 16).
pResult Buffer to hold result (returned in complete event).
handlerId Task handler ID to receive complete event.
param Optional parameter passed in complete event.
event Event ID of complete event.
Returns
TRUE if successful, else FALSE.
SecCcmInit()
SecCcmInit (void)
Called to initialize CCM security.
Called to initialize CCM-Mode security.
Returns
None.
Parameters
None.
Returns
None.
SecCmac()
bool_t SecCmac (const uint8_t * pKey, uint8_t * pPlainText, uint16_t textLen, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Execute the CMAC algorithm.
Parameters
pKey Key used in CMAC operation.
pPlaintext Plain text buffer - buffer must persist until secCmacMsg_t callback.
textLen Size of pPlaintext in bytes.
handlerId WSF handler ID for client.
param Optional parameter sent to client's WSF handler.
event Event for client's WSF handler.
Returns
TRUE if successful, else FALSE.
Parameters
pKey Key used in CMAC operation.
pPlainText Data to perform CMAC operation over
len Size of pPlaintext in bytes.
handlerId WSF handler ID for client.
param Optional parameter sent to client's WSF handler.
event Event for client's WSF handler.
Returns
TRUE if successful, else FALSE.
SecCmacInit()
void SecCmacInit (void)
Called to initialize CMAC security. This function should only be called once upon system initialization.
Returns
None.
Called to initialize CMAC security. This function should only be called once upon system initialization.
Parameters
None.
Returns
None.
SecEccGenKey()
bool_t SecEccGenKey (wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Generate an ECC key.
Parameters
handlerId WSF handler ID for client.
param Optional parameter sent to client's WSF handler.
event Event for client's WSF handler.
Returns
TRUE if successful, else FALSE.
SecEccGenSharedSecret()
bool_t SecEccGenSharedSecret (secEccKey_t * pKey, wsfHandlerId_t handlerId, uint16_t param, uint8_t event)
Generate an ECC key.
Parameters
pKey ECC Key structure.
handlerId WSF handler ID for client.
param Optional parameter sent to client's WSF handler.
event Event for client's WSF handler.
Returns
TRUE if successful, else FALSE.
SecEccInit()
void SecEccInit (void)
Called to initialize ECC security. This function should only be called once upon system initialization.
Returns
None.
Called to initialize ECC security. This function should only be called once upon system initialization.
Parameters
None.
Returns
None.
SecInit()
void SecInit (void)
Initialize the security service. This function should only be called once upon system initialization.
Returns
None.
References HciSecRegister(), and WSF_QUEUE_INIT.
SecRand()
void SecRand (uint8_t * pRand, uint8_t randLen)
This function returns up to 16 bytes of random data to a buffer provided by the client.
Parameters
pRand Pointer to returned random data.
randLen Length of random data.
Returns
None.
This function returns up to 16 bytes of random data to a buffer provided by the client.
Parameters
pRand Pointer to returned random data.
randLen Length of random data.
Returns
None.
References HCI_ENCRYPT_DATA_LEN, HCI_KEY_LEN, HCI_RAND_LEN, HciLeEncryptCmd(), HciLeRandCmd(), WSF_ASSERT, WsfMsgEnq(), and WStrReverseCpy().
SecRandInit()
void SecRandInit (void)
Initialize the random number service. This function should only be called once upon system initialization.
Returns
None.
References HciLeRandCmd().