Cordio: LL_API_TEST
LL_API_TEST
Data Structures
struct LlTestReport_t
struct LlIsoTestCtrs_t
struct LlIsoLinkQual_t
Enumerations
enum
enum
enum
enum LlIsoPldType_t
Functions
uint32_t llCalcPacketTime (uint8_t len, uint8_t phy, uint8_t phyOptions)
uint32_t llCalcPacketInterval (uint8_t len, uint8_t phy, uint8_t phyOptions)
uint8_t LlTxTest (uint8_t rfChan, uint8_t len, uint8_t pktType, uint16_t numPkt)
uint8_t LlRxTest (uint8_t rfChan, uint16_t numPkt)
uint8_t LlEnhancedTxTest (uint8_t rfChan, uint8_t len, uint8_t pktType, uint8_t phy, uint16_t numPkt)
uint8_t LlEnhancedRxTest (uint8_t rfChan, uint8_t phy, uint8_t modIdx, uint16_t numPkt)
uint8_t LlRxTestV3 (uint8_t rfChan, uint8_t phy, uint8_t modIdx, uint8_t cteLen, uint8_t cteType, uint8_t slotDur, uint8_t swPatLen, uint8_t *antIds, uint16_t numPkt)
uint8_t LlTxTestV3 (uint8_t rfChan, uint8_t len, uint8_t pktType, uint8_t phy, uint8_t cteLen, uint8_t cteType, uint8_t swPatLen, uint8_t *antIds, uint16_t numPkt)
uint8_t LlEndTest (LlTestReport_t *pRpt)
uint8_t LlSetTxTestErrorPattern (uint32_t pattern)
uint8_t LlModifySleepClockAccuracy (uint8_t action)
uint8_t LlIsoTxTest (uint16_t handle, uint8_t pldType)
uint8_t LlIsoRxTest (uint16_t handle, uint8_t pldType)
uint8_t LlIsoReadTestCounter (uint16_t handle, LlIsoTestCtrs_t *pCtr)
uint8_t LlIsoTestEnd (uint16_t handle, LlIsoTestCtrs_t *pCtr)
uint8_t LlSetTxPowerReporting (uint16_t handle, uint8_t enableLocal, uint8_t enableRemote)
uint8_t LlSetPowerMonitorEnable (uint16_t handle, bool_t enable)
uint8_t LlSetPathLossReportingParams (uint16_t handle, uint8_t highThresh, uint8_t highHyst, uint8_t lowThresh, uint8_t lowHyst, uint16_t minTime)
uint8_t LlSetPathLossReportingEnable (uint16_t handle, uint8_t enable)
uint8_t LlPowerCtrlReq (uint16_t handle, int8_t delta, uint8_t phy)
void LlIsoEventCompleteEnable (uint8_t enable)
Detailed Description
Data Structure Documentation
LlTestReport_t
struct LlTestReport_t
Test report data.
Data Fields
uint16_t numTx
uint16_t numRxSuccess
uint16_t numRxCrcError
uint16_t numRxTimeout
Field Documentation
numRxCrcError
uint16_t numRxCrcError
CRC failed packet count.
numRxSuccess
uint16_t numRxSuccess
Successfully received packet count.
numRxTimeout
uint16_t numRxTimeout
Receive timeout count.
numTx
uint16_t numTx
Total transmit packet count.
LlIsoTestCtrs_t
struct LlIsoTestCtrs_t
ISO test counter data.
Data Fields
uint32_t numSuccess
uint32_t numMissed
uint32_t numFailed
Field Documentation
numFailed
uint32_t numFailed
Received failed packet count.
numMissed
uint32_t numMissed
Received missed packet count.
numSuccess
uint32_t numSuccess
Received good packet count.
LlIsoLinkQual_t
struct LlIsoLinkQual_t
ISO link quality statistics.
Data Fields
uint32_t txUnAckPkt
uint32_t txFlushedPkt
uint32_t txLastSubEventPkt
uint32_t retransmitPkt
uint32_t crcErrPkt
uint32_t rxUnreceivedPkt
uint32_t duplicatePkt
Field Documentation
crcErrPkt
uint32_t crcErrPkt
CRC error packets.
duplicatePkt
uint32_t duplicatePkt
Retransmitted CIS data PDUs.
retransmitPkt
uint32_t retransmitPkt
Retransmitted packets.
rxUnreceivedPkt
uint32_t rxUnreceivedPkt
Packets unreceived by flush point.
txFlushedPkt
uint32_t txFlushedPkt
Flushed packets.
txLastSubEventPkt
uint32_t txLastSubEventPkt
The CIS slave transmit CIS Data PDU on it's last subevent.
txUnAckPkt
uint32_t txUnAckPkt
Unacked packets.
Enumeration Type Documentation
anonymous enum
anonymous enum
Test packet payload type.
Enumerator
LL_TEST_PKT_TYPE_PRBS9
Pseudo-Random bit sequence 9.
LL_TEST_PKT_TYPE_0F
00001111'b packet payload type.
LL_TEST_PKT_TYPE_55
01010101'b packet payload type.
LL_TEST_PKT_TYPE_PRBS15
Pseudo-Random bit sequence 15.
LL_TEST_PKT_TYPE_FF
11111111'b packet payload type.
LL_TEST_PKT_TYPE_00
00000000'b packet payload type.
LL_TEST_PKT_TYPE_F0
11110000'b packet payload type.
LL_TEST_PKT_TYPE_AA
10101010'b packet payload type.
anonymous enum
anonymous enum
Test PHY type.
Enumerator
LL_TEST_PHY_LE_1M
LE 1M PHY.
LL_TEST_PHY_LE_2M
LE 2M PHY.
LL_TEST_PHY_LE_CODED
LE Coded PHY (data coding unspecified).
LL_TEST_PHY_LE_CODED_S8
LE Coded PHY with S=8 data coding.
LL_TEST_PHY_LE_CODED_S2
LE Coded PHY with S=2 data coding.
anonymous enum
anonymous enum
Test modulation index.
Enumerator
LL_TEST_MOD_IDX_STANDARD
Standard modulation index.
LL_TEST_MOD_IDX_STABLE
Stable modulation index.
LlIsoPldType_t
enum LlIsoPldType_t
ISO test packet payload type.
Enumerator
LL_ISO_PLD_TYPE_ZERO_LEN
Zero length payload.
LL_ISO_PLD_TYPE_VAR_LEN
Variable length payload.
LL_ISO_PLD_TYPE_MAX_LEN
Maximum length payload.
Function Documentation
llCalcPacketInterval()
uint32_t llCalcPacketInterval (uint8_t len, uint8_t phy, uint8_t phyOptions)
Calculate packet interval.
Parameters
len Packet length.
phy PHY.
phyOptions PHY options.
Returns
Interval between packets in microseconds.
References BB_PROT_BLE_DTM, BbStop(), BbBleData_t::chan, PalBbBleChan_t::chanIdx, lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrPersistCtrlBlk_t::handlerId, PalBbBleChan_t::initTxPhyOptions, LCTR_DISP_TEST, LL_TEST_PKT_TYPE_00, LL_TEST_PKT_TYPE_0F, LL_TEST_PKT_TYPE_55, LL_TEST_PKT_TYPE_AA, LL_TEST_PKT_TYPE_F0, LL_TEST_PKT_TYPE_FF, LL_TEST_PKT_TYPE_PRBS15, LL_TEST_PKT_TYPE_PRBS9, llCalcPacketTime(), LlEndTest(), lmgrCb, lmgrPersistCb, BbBleData_t::op, BbOpDesc_t::pBle, BbBleTestTx_t::pktInterUsec, BbOpDesc_t::prot, BbBleTestTx_t::pTxBuf, PalBbBleChan_t::rxPhy, lmgrCtrlBlk_t::testEnabled, BbBleData_t::testTx, PalBbBleChan_t::tifsTxPhyOptions, BbBleTestTx_t::txLen, PalBbBleChan_t::txPhy, WsfBufFree(), WsfMsgAlloc(), and WsfMsgSend().
llCalcPacketTime()
uint32_t llCalcPacketTime (uint8_t len, uint8_t phy, uint8_t phyOptions)
Calculate packet interval.
Parameters
len Packet length.
phy PHY.
phyOptions PHY options.
Returns
Packet length in microseconds.
References BB_PHY_BLE_1M, BB_PHY_BLE_2M, BB_PHY_BLE_CODED, BB_PHY_OPTIONS_BLE_S2, and BB_PHY_OPTIONS_BLE_S8.
LlEndTest()
uint8_t LlEndTest (LlTestReport_t * pRpt)
End test mode.
Parameters
pRpt Report return buffer.
Returns
Status error code.
End test mode and return the report.
Parameters
pRpt Report return buffer.
Returns
Status error code.
End test mode and return the report.
Note
Receive tests must wait for the duration of the synchronization timeout before another test can be issued.
References BB_PROT_PRBS15, BbStop(), LL_TEST_PKT_TYPE_PRBS15, lmgrCb, and lmgrCtrlBlk_t::testEnabled.
LlEnhancedRxTest()
uint8_t LlEnhancedRxTest (uint8_t rfChan, uint8_t phy, uint8_t modIdx, uint16_t numPkt)
Enter enhanced receive test mode.
Parameters
rfChan RF channel number, i.e. "rfChan = (F - 2402) / 2)".
phy Receiver PHY.
modIdx Modulation index.
numPkt Auto terminate after number of successful packets, 0 for infinite.
Returns
Status error code.
Start the receive test mode on the given channel.
References BbOpDesc_t::abortCback, PalBbBleChan_t::accAddr, lmgrCtrlBlk_t::advEnabled, BB_BLE_OP_TEST_RX, BB_PHY_BLE_1M, BB_PHY_BLE_2M, BB_PHY_BLE_CODED, BB_PROT_BLE_DTM, BbBleData_t::chan, PalBbBleChan_t::chanIdx, PalBbBleChan_t::crcInit, LlRtCfg_t::dtmRxSyncMs, BbOpDesc_t::endCback, lmgrCtrlBlk_t::features, LL_FEAT_LE_2M_PHY, LL_FEAT_LE_CODED_PHY, LL_TEST_MOD_IDX_STABLE, LL_TEST_PHY_LE_1M, LL_TEST_PHY_LE_2M, LL_TEST_PHY_LE_CODED, lmgrCb, lmgrCtrlBlk_t::numConnEnabled, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, lmgrCtrlBlk_t::numScanEnabled, BbBleData_t::op, PalBbBleChan_t::opType, BbOpDesc_t::pBle, pLctrRtCfg, BbOpDesc_t::prot, BbOpDesc_t::protId, BbBleTestRx_t::pRxBuf, BbBleTestRx_t::rxLen, PalBbBleChan_t::rxPhy, BbBleTestRx_t::rxSyncDelayUsec, BbBleTestRx_t::testCback, BbBleData_t::testRx, PalBbBleChan_t::txPhy, WSF_MAX, WsfBufAlloc(), and WsfBufFree().
LlEnhancedTxTest()
uint8_t LlEnhancedTxTest (uint8_t rfChan, uint8_t len, uint8_t pktType, uint8_t phy, uint16_t numPkt)
Enter enhanced transmit test mode.
Parameters
rfChan RF channel number, i.e. "rfChan = (F - 2402) / 2)".
len Length of test data.
pktType Test packet payload type.
phy Transmitter PHY.
numPkt Auto terminate after number of packets, 0 for infinite.
Returns
Status error code.
Start the transmit test mode on the given channel.
References lmgrCtrlBlk_t::advEnabled, lmgrCtrlBlk_t::advTxPwr, BB_PHY_BLE_1M, BB_PHY_BLE_2M, BB_PHY_BLE_CODED, BB_PHY_OPTIONS_BLE_S2, BB_PHY_OPTIONS_BLE_S8, BB_PHY_OPTIONS_DEFAULT, BB_PROT_PRBS15, BbStart(), PalBbBleChan_t::chanIdx, lmgrCtrlBlk_t::features, PalBbBleChan_t::initTxPhyOptions, LL_FEAT_LE_2M_PHY, LL_FEAT_LE_CODED_PHY, LL_TEST_PHY_LE_1M, LL_TEST_PHY_LE_2M, LL_TEST_PHY_LE_CODED_S2, LL_TEST_PHY_LE_CODED_S8, LL_TEST_PKT_TYPE_AA, LL_TEST_PKT_TYPE_PRBS15, lmgrCb, lmgrCtrlBlk_t::numConnEnabled, lmgrCtrlBlk_t::numExtAdvEnabled, lmgrCtrlBlk_t::numInitEnabled, lmgrCtrlBlk_t::numScanEnabled, PalBbBleSetChannelParam(), lmgrCtrlBlk_t::testEnabled, PalBbBleChan_t::txPhy, PalBbBleChan_t::txPower, and WSF_CS_INIT.
LlIsoEventCompleteEnable()
void LlIsoEventCompleteEnable (uint8_t enable)
ISO event complete enable.
Parameters
enable Set to TRUE to enable, FALSE to disable.
Enable or disable reports about the scanners from which an advertiser receives scan requests.
References wsfMsgHdr_t::event, LlIsoEventCmplInd_t::evtCtr, lctrIsoHdr_t::handle, LlIsoEventCmplInd_t::handle, HCI_ISO_HDR_LEN, LlIsoEventCmplInd_t::hdr, lctrCodecHandlers_t::in, LL_ISO_EVT_CMPL_IND, lmgrCb, LmgrSendEvent(), LlRtCfg_t::maxIsoSduLen, wsfMsgHdr_t::param, lctrBisCtx_t::pBigCtx, pLctrRtCfg, lmgrCtrlBlk_t::sendIsoCmplEvt, wsfMsgHdr_t::status, WSF_ASSERT, WsfMsgAlloc(), and WsfMsgFree().
LlIsoReadTestCounter()
uint8_t LlIsoReadTestCounter (uint16_t handle, LlIsoTestCtrs_t * pCtr)
ISO read test counters.
Parameters
handle CIS or BIS handle.
pCtr Test Counter.
Returns
Status error code.
ISO read test counters.
Parameters
handle CIS or BIS handle.
pCtr Test Counter.
Returns
Status error code.
LlIsoRxTest()
uint8_t LlIsoRxTest (uint16_t handle, uint8_t pldType)
Enable ISO Rx test.
Parameters
handle CIS or BIS handle.
pldType Payload type.
Returns
Status error code.
LlIsoTestEnd()
uint8_t LlIsoTestEnd (uint16_t handle, LlIsoTestCtrs_t * pCtr)
Terminate ISO Tx or Rx test.
Parameters
handle CIS or BIS handle.
pCtr Test counters.
Returns
Status error code.
LlIsoTxTest()
uint8_t LlIsoTxTest (uint16_t handle, uint8_t pldType)
Enable ISO Tx test.
Parameters
handle CIS or BIS handle.
pldType Payload type.
Returns
Status error code.
LlModifySleepClockAccuracy()
uint8_t LlModifySleepClockAccuracy (uint8_t action)
Modify the sleep clock accuracy.
Parameters
action Increase or decrease the sleep clock accuracy.
Returns
Status error code.
Parameters
action Increase or decrease the sleep clock accuracy
Returns
Status error code.
References lctrScaReq_t::action, lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, lctrScaReq_t::hdr, LCTR_CONN_MSG_API_REQ_PEER_SCA, LCTR_DISP_CONN, LctrGetUsedFeatures(), LctrIsConnHandleEnabled(), LctrValidateModifyScaParam(), LL_FEAT_SCA_UPDATE, lmgrCb, lmgrPersistCb, LlRtCfg_t::maxConn, pLctrRtCfg, lmgrCtrlBlk_t::scaMod, WsfMsgAlloc(), and WsfMsgSend().
LlPowerCtrlReq()
uint8_t LlPowerCtrlReq (uint16_t handle, int8_t delta, uint8_t phy)
Request change to or read peer txPower.
Parameters
handle Connection handle.
delta Requested change.
phy Phy this change requests the change on.
Returns
Status error code.
References LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlRxTest()
uint8_t LlRxTest (uint8_t rfChan, uint16_t numPkt)
Enter receive test mode.
Parameters
rfChan RF channel number, i.e. "rfChan = (F - 2402) / 2)".
numPkt Auto terminate after number of successful packets, 0 for infinite.
Returns
Status error code.
Start the receive test mode on the given channel.
References LL_TEST_MOD_IDX_STANDARD, LL_TEST_PHY_LE_1M, and LlEnhancedRxTest().
LlRxTestV3()
uint8_t LlRxTestV3 (uint8_t rfChan, uint8_t phy, uint8_t modIdx, uint8_t cteLen, uint8_t cteType, uint8_t slotDur, uint8_t swPatLen, uint8_t * antIds, uint16_t numPkt)
Enter enhanced receive test mode.
Parameters
rfChan RF channel number, i.e. "rfChan = (F - 2402) / 2)".
phy Receiver PHY.
modIdx Modulation index.
cteLen CTE length.
cteType CTE type.
slotDur Slot Durations.
swPatLen Swithcing pattern length.
antIds Antenna IDs.
numPkt Auto terminate after number of successful packets, 0 for infinite.
Returns
Status error code.
Start the receive test mode on the given channel.
References LlEnhancedRxTest().
LlSetPathLossReportingEnable()
uint8_t LlSetPathLossReportingEnable (uint16_t handle, uint8_t enable)
Set path loss enable.
Parameters
handle Connection handle.
enable Enable flag.
Returns
Status error code.
References LctrIsConnHandleEnabled(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlSetPathLossReportingParams()
uint8_t LlSetPathLossReportingParams (uint16_t handle, uint8_t highThresh, uint8_t highHyst, uint8_t lowThresh, uint8_t lowHyst, uint16_t minTime)
Set path loss monitoring parameters.
Parameters
handle Handle identifier for connection.
highThresh High extreme threshold.
highHyst High extreme hysteresis.
lowThresh Low extreme threshold.
lowHyst Low extreme hysteresis.
minTime Minimum time spent to trigger event generation.
Returns
Status error code.
References LctrIsConnHandleEnabled(), LL_PC_PATH_LOSS_UNUSED_HIGH_THRESHOLD, LlRtCfg_t::maxConn, and pLctrRtCfg.
LlSetPowerMonitorEnable()
uint8_t LlSetPowerMonitorEnable (uint16_t handle, bool_t enable)
Set enable state for power monitoring.
Parameters
handle Handle identifier for connection.
enable Enable status for power monitor.
Returns
Status error code.
Note
Path loss must be disabled.
LlSetTxPowerReporting()
uint8_t LlSetTxPowerReporting (uint16_t handle, uint8_t enableLocal, uint8_t enableRemote)
Set transmit power change reporting enable.
Parameters
handle Connection handle.
enableLocal Enable local reporting.
enableRemote Enable remote reporting.
Returns
Status error code.
References LctrIsConnHandleEnabled(), lctrSetTxPowerReporting(), LlRtCfg_t::maxConn, and pLctrRtCfg.
LlSetTxTestErrorPattern()
uint8_t LlSetTxTestErrorPattern (uint32_t pattern)
Set pattern of errors for Tx test mode.
Parameters
pattern Error pattern (1s = no error; 0s = CRC failure).
Returns
Status error code.
Set pattern of errors for Tx test mode.
Note
The error pattern must be set after the Tx test is started.
LlTxTest()
uint8_t LlTxTest (uint8_t rfChan, uint8_t len, uint8_t pktType, uint16_t numPkt)
Enter transmit test mode.
Parameters
rfChan RF channel number, i.e. "rfChan = (F - 2402) / 2)".
len Length of test data.
pktType Test packet payload type.
numPkt Auto terminate after number of packets, 0 for infinite.
Returns
Status error code.
Start the transmit test mode on the given channel.
References LL_TEST_PHY_LE_1M, LlEnhancedTxTest(), BbBleData_t::op, BbOpDesc_t::pBle, BbOpDesc_t::prot, BbBleTestRx_t::pRxBuf, BbBleData_t::testRx, and WsfBufFree().
LlTxTestV3()
uint8_t LlTxTestV3 (uint8_t rfChan, uint8_t len, uint8_t pktType, uint8_t phy, uint8_t cteLen, uint8_t cteType, uint8_t swPatLen, uint8_t * antIds, uint16_t numPkt)
Enter enhanced transmit test mode.
Parameters
rfChan RF channel number, i.e. "rfChan = (F - 2402) / 2)".
len Length of test data.
pktType Test packet payload type.
phy Transmitter PHY.
cteLen CTE length.
cteType CTE type.
swPatLen Swithcing pattern length.
antIds Antenna IDs.
numPkt Auto terminate after number of successful packets, 0 for infinite.
Returns
Status error code.
Start the transmit test mode on the given channel.
References LlEnhancedTxTest().