Cordio: LL_API_OBSERVER
LL_API_OBSERVER
Data Structures
struct LlScanParam_t
struct LlExtScanParam_t
struct LlPerAdvCreateSyncCmd_t
struct LlDevicePerAdvList_t
Macros
#define LL_PER_ADV_CREATE_SYNC_OPTIONS_BITS 0x03
Enumerations
enum
enum
enum
enum
enum
enum
Functions
uint8_t LlSetSetScanChanMap (uint8_t chanMap)
uint8_t LlSetScanParam (const LlScanParam_t *pParam)
void LlScanEnable (uint8_t enable, uint8_t filterDup)
uint8_t LlSetExtScanParam (uint8_t ownAddrType, uint8_t scanFiltPolicy, uint8_t scanPhys, const LlExtScanParam_t param[])
void LlExtScanEnable (uint8_t enable, uint8_t filterDup, uint16_t duration, uint16_t period)
uint8_t LlPeriodicAdvCreateSync (const LlPerAdvCreateSyncCmd_t *pParam)
uint8_t LlPeriodicAdvCreateSyncCancel (void)
uint8_t LlPeriodicAdvTerminateSync (uint16_t syncHandle)
uint8_t LlAddDeviceToPeriodicAdvList (const LlDevicePerAdvList_t *pParam)
uint8_t LlRemoveDeviceFromPeriodicAdvList (const LlDevicePerAdvList_t *pParam)
uint8_t LlClearPeriodicAdvList (void)
uint8_t LlReadPeriodicAdvListSize (uint8_t *pListSize)
uint8_t LlSetPeriodicAdvRcvEnable (uint16_t syncHandle, uint8_t enable)
void LlPastInit (void)
uint8_t LlPeriodicAdvSyncTransfer (uint16_t connHandle, uint16_t serviceData, uint16_t syncHandle)
uint8_t LlPeriodicAdvSetInfoTransfer (uint16_t connHandle, uint16_t serviceData, uint8_t advHandle)
uint8_t LlSetPeriodicAdvSyncTransParams (uint16_t connHandle, uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
uint8_t LlSetDefaultPeriodicAdvSyncTransParams (uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
Detailed Description
Data Structure Documentation
LlScanParam_t
struct LlScanParam_t
Scan parameters.
Data Fields
uint16_t scanInterval
uint16_t scanWindow
uint8_t scanType
uint8_t ownAddrType
uint8_t scanFiltPolicy
Field Documentation
ownAddrType
uint8_t ownAddrType
Address type used by this device.
scanFiltPolicy
uint8_t scanFiltPolicy
Scan filter policy.
scanInterval
uint16_t scanInterval
Scan interval.
scanType
uint8_t scanType
Scan type.
scanWindow
uint16_t scanWindow
Scan window.
LlExtScanParam_t
struct LlExtScanParam_t
Extended scan parameters.
Data Fields
uint16_t scanInterval
uint16_t scanWindow
uint8_t scanType
Field Documentation
scanInterval
uint16_t scanInterval
Scan interval.
scanType
uint8_t scanType
Scan type.
scanWindow
uint16_t scanWindow
Scan window.
LlPerAdvCreateSyncCmd_t
struct LlPerAdvCreateSyncCmd_t
Periodic advertising create sync command.
Data Fields
uint8_t options
uint8_t advSID
uint8_t advAddrType
uint8_t * pAdvAddr
uint16_t skip
uint16_t syncTimeOut
Field Documentation
advAddrType
uint8_t advAddrType
Advertiser Address Type.
advSID
uint8_t advSID
Advertising SID.
options
uint8_t options
Options.
pAdvAddr
uint8_t* pAdvAddr
Advertiser Address.
skip
uint16_t skip
Skip.
syncTimeOut
uint16_t syncTimeOut
Synchronization Timeout.
LlDevicePerAdvList_t
struct LlDevicePerAdvList_t
Device in periodic advertiser list.
Data Fields
uint8_t advAddrType
uint8_t * pAdvAddr
uint8_t advSID
Field Documentation
advAddrType
uint8_t advAddrType
Advertiser Address Type.
advSID
uint8_t advSID
Advertising SID.
pAdvAddr
uint8_t* pAdvAddr
Advertiser Address.
Enumeration Type Documentation
anonymous enum
anonymous enum
Type of scan.
Enumerator
LL_SCAN_PASSIVE
Passive scanning.
LL_SCAN_ACTIVE
Active scanning.
anonymous enum
anonymous enum
Init filter policy.
Enumerator
LL_INIT_FILTER_PEER
Filter to only Peer addr and addr type.
LL_INIT_FILTER_WL
Filter to only whitelist.
LL_INIT_FILTER_TOTAL
Total number of filter policies.
anonymous enum
anonymous enum
Scan filter policy.
Enumerator
LL_SCAN_FILTER_NONE
Accept all advertising packets.
LL_SCAN_FILTER_WL_BIT
Accept from While List only.
LL_SCAN_FILTER_RES_INIT_BIT
Accept directed advertisements with RPAs.
LL_SCAN_FILTER_WL_OR_RES_INIT
Accept from White List or directed advertisements with RPAs.
anonymous enum
anonymous enum
Periodic scan filter policy.
Enumerator
LL_PER_SCAN_FILTER_NONE
Use advSID, advAddrType and advAddr to filter.
LL_PER_SCAN_FILTER_PL_BIT
Use the periodic advertiser list.
anonymous enum
anonymous enum
Scan filter modes for duplicate report.
Enumerator
LL_SCAN_FILTER_DUP_DISABLE
Duplicate filtering disabled.
LL_SCAN_FILTER_DUP_ENABLE_ONCE
Duplicate filtering enabled.
LL_SCAN_FILTER_DUP_ENABLE_PERIODIC
Duplicate filtering enabled, reset for each scan period.
anonymous enum
anonymous enum
Advertising report event types.
Enumerator
LL_RPT_TYPE_ADV_IND
Connectable undirected advertising (ADV_IND).
LL_RPT_TYPE_ADV_DIRECT_IND
Connectable directed advertising (ADV_DIRECT_IND).
LL_RPT_TYPE_ADV_SCAN_IND
Scannable undirected advertising (ADV_SCAN_IND).
LL_RPT_TYPE_ADV_NONCONN_IND
Non connectable undirected advertising (ADV_NONCONN_IND).
LL_RPT_TYPE_SCAN_RSP
Scan Response (SCAN_RSP).
Function Documentation
LlAddDeviceToPeriodicAdvList()
uint8_t LlAddDeviceToPeriodicAdvList (const LlDevicePerAdvList_t * pParam)
Add device to periodic advertiser list.
Parameters
pParam Add to periodic list parameters.
Returns
Status error code.
Add device to periodic advertiser list.
Parameters
pParam Add to periodic advertiser list parameters.
Returns
Status error code.
References LlDevicePerAdvList_t::advAddrType, LlDevicePerAdvList_t::advSID, BbBlePeriodicListAdd(), BbBlePeriodicListCheckAddr(), BstreamToBda64(), LL_ADDR_RANDOM, lmgrCb, LmgrIsExtCommandAllowed(), lmgrCtrlBlk_t::numPlFilterEnabled, and LlDevicePerAdvList_t::pAdvAddr.
LlClearPeriodicAdvList()
uint8_t LlClearPeriodicAdvList (void)
Clear all devices in periodic advertiser list command.
Returns
Status error code.
Clear all devices in periodic advertiser list command.
Clear all devices in periodic advertiser list command.
Returns
Status error code.
References BbBlePeriodicListClear(), lmgrCb, LmgrIsExtCommandAllowed(), and lmgrCtrlBlk_t::numPlFilterEnabled.
LlExtScanEnable()
void LlExtScanEnable (uint8_t enable, uint8_t filterDup, uint16_t duration, uint16_t period)
Extended scan enable.
Parameters
enable Set to TRUE to enable scanning, FALSE to disable scanning.
filterDup Set to TRUE to filter duplicates.
duration Duration.
period Period.
Enable or disable extended scanning.
Parameters
enable Set to TRUE to enable scanning, FALSE to disable scanning.
filterDup Filter duplicate report mode.
duration Duration.
period Period.
Enable or disable extended scanning.
References lmgrCtrlBlk_t::extScanEnaDelayCnt, lmgrCtrlBlk_t::extScanEnaStatus, LL_SCAN_FILTER_DUP_DISABLE, LL_SCAN_FILTER_DUP_ENABLE_PERIODIC, lmgrCb, LmgrIsExtCommandAllowed(), lmgrCtrlBlk_t::numExtScanPhys, and WSF_ASSERT.
LlPastInit()
void LlPastInit (void)
Initialize LL subsystem for PAST(Periodic advertising sync transfer).
This function initializes the LL subsystem for PAST(Periodic advertising sync transfer).
LlPeriodicAdvCreateSync()
uint8_t LlPeriodicAdvCreateSync (const LlPerAdvCreateSyncCmd_t * pParam)
Create synchronization of periodic advertising.
Parameters
pParam Create sync parameters.
Returns
Status error code.
Create synchronization of periodic advertising.
Parameters
pParam Create sync parameters.
Returns
Status error code.
References LlPerAdvCreateSyncCmd_t::advAddrType, LlPerAdvCreateSyncCmd_t::advSID, LL_ADDR_RANDOM, LL_PER_ADV_CREATE_SYNC_OPTIONS_BITS, LmgrIsExtCommandAllowed(), LlPerAdvCreateSyncCmd_t::options, LlPerAdvCreateSyncCmd_t::skip, and LlPerAdvCreateSyncCmd_t::syncTimeOut.
LlPeriodicAdvCreateSyncCancel()
uint8_t LlPeriodicAdvCreateSyncCancel (void)
Cancel pending synchronization of periodic advertising.
Returns
Status error code.
Cancel pending synchronization of periodic advertising.
Returns
Status error code.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrPersistCtrlBlk_t::handlerId, LctrPerScanMsg_t::hdr, LCTR_DISP_PER_CREATE_SYNC, LmgrIsExtCommandAllowed(), lmgrPersistCb, WsfMsgAlloc(), and WsfMsgSend().
LlPeriodicAdvSetInfoTransfer()
uint8_t LlPeriodicAdvSetInfoTransfer (uint16_t connHandle, uint16_t serviceData, uint8_t advHandle)
Send sync info about periodic adv in an advertising set to a connected device.
Parameters
connHandle Connection handle.
serviceData Service data provided by the host.
advHandle Handle to identify an advertising set.
Returns
Status error code.
Send sync info about periodic adv in an advertising set to a connected device.
References LmgrIsExtCommandAllowed().
LlPeriodicAdvSyncTransfer()
uint8_t LlPeriodicAdvSyncTransfer (uint16_t connHandle, uint16_t serviceData, uint16_t syncHandle)
Send sync info about periodic advertising to a connected device.
Parameters
connHandle Connection handle.
serviceData Service data provided by the host.
syncHandle Periodic sync handle.
Returns
Status error code.
Send sync info about periodic advertising to a connected device.
Parameters
connHandle Connection handle.
serviceData Service data provided by the host.
syncHandle Periodic sync handle.
Returns
Status error code.
Send sync info about about periodic advertising to a connected device.
References LmgrIsExtCommandAllowed().
LlPeriodicAdvTerminateSync()
uint8_t LlPeriodicAdvTerminateSync (uint16_t syncHandle)
Stop synchronization of periodic advertising.
Parameters
syncHandle Sync handle.
Returns
Status error code.
Stop synchronization of periodic advertising.
Parameters
syncHandle Sync handle.
Returns
Status error code.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lctrMsgHdr_t::handle, lmgrPersistCtrlBlk_t::handlerId, LctrPerScanMsg_t::hdr, LCTR_DISP_PER_SCAN, LmgrIsExtCommandAllowed(), lmgrPersistCb, WsfMsgAlloc(), and WsfMsgSend().
LlReadPeriodicAdvListSize()
uint8_t LlReadPeriodicAdvListSize (uint8_t * pListSize)
Read total number of devices in periodic advertiser list command.
Parameters
pListSize Return size value of periodic advertiser list
Returns
Status error code.
Read total number of devices in periodic advertiser list command.
Read total number of devices in periodic advertiser list command.
Parameters
pListSize Return size value of periodic advertiser list
Returns
Status error code.
References BbBlePeriodicListGetSize(), and LmgrIsExtCommandAllowed().
LlRemoveDeviceFromPeriodicAdvList()
uint8_t LlRemoveDeviceFromPeriodicAdvList (const LlDevicePerAdvList_t * pParam)
Remove device from periodic advertiser list command.
Parameters
pParam Remove from periodic list parameters.
Returns
Status error code.
Parameters
pParam Remove from periodic advertiser list parameters..
Returns
Status error code.
References LlDevicePerAdvList_t::advAddrType, LlDevicePerAdvList_t::advSID, BbBlePeriodicListRemove(), BstreamToBda64(), LL_ADDR_RANDOM, lmgrCb, LmgrIsExtCommandAllowed(), lmgrCtrlBlk_t::numPlFilterEnabled, and LlDevicePerAdvList_t::pAdvAddr.
LlScanEnable()
void LlScanEnable (uint8_t enable, uint8_t filterDup)
Scan enable.
Parameters
enable Set to TRUE to enable scanning, FALSE to disable scanning.
filterDup Set to TRUE to filter duplicates.
Enable or disable scanning. This function is only used when operating in master role.
References LmgrIsLegacyCommandAllowed(), and LmgrSendScanEnableCnf().
LlSetDefaultPeriodicAdvSyncTransParams()
uint8_t LlSetDefaultPeriodicAdvSyncTransParams (uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
Set default periodic advertising sync transfer parameters.
Parameters
mode Periodic sync advertising sync transfer mode.
skip The number of periodic advertising packets that can be skipped after a successful receive.
syncTimeout Synchronization timeout for the periodic advertising.
cteType Constant tone extension type(Used in AoD/AoA).
Returns
Status error code.
Set default periodic advertising sync transfer parameters.
References lmgrConnCb, LmgrIsExtCommandAllowed(), lmgrConnCtrlBlk_t::syncMode, lmgrConnCtrlBlk_t::syncSkip, and lmgrConnCtrlBlk_t::syncTimeout.
LlSetExtScanParam()
uint8_t LlSetExtScanParam (uint8_t ownAddrType, uint8_t scanFiltPolicy, uint8_t scanPhys, const LlExtScanParam_t param[])
Set extended scanning parameters.
Parameters
ownAddrType Address type used by this device.
scanFiltPolicy Scan filter policy.
scanPhys Scanning PHYs bitmask.
param Scanning parameter table indexed by PHY.
Returns
Status error code.
Set the extended scan parameters to be used on the primary advertising channel.
References lmgrCtrlBlk_t::features, LL_ADDR_RANDOM, LL_ADDR_RANDOM_IDENTITY, LL_FEAT_EXT_SCAN_FILT_POLICY, LL_FEAT_LE_CODED_PHY, LL_FEAT_PRIVACY, LL_PHYS_LE_1M_BIT, LL_PHYS_LE_CODED_BIT, LL_SCAN_FILTER_WL_BIT, LL_SCAN_FILTER_WL_OR_RES_INIT, lmgrCb, LmgrIsExtCommandAllowed(), lmgrCtrlBlk_t::numExtScanPhys, lmgrCtrlBlk_t::numInitEnabled, and lmgrCtrlBlk_t::numScanEnabled.
LlSetPeriodicAdvRcvEnable()
uint8_t LlSetPeriodicAdvRcvEnable (uint16_t syncHandle, uint8_t enable)
Enable or disable reports for the periodic advertising sync.
Parameters
syncHandle Periodic sync handle.
enable 1 to enable reports, 0 to disable reports.
Returns
Status error code.
Enable or disable reports for the periodic advertising sync.
References LmgrIsExtCommandAllowed().
LlSetPeriodicAdvSyncTransParams()
uint8_t LlSetPeriodicAdvSyncTransParams (uint16_t connHandle, uint8_t mode, uint16_t skip, uint16_t syncTimeout, uint8_t cteType)
Set periodic advertising sync transfer parameters.
Parameters
connHandle Connection handle.
mode Periodic sync advertising sync transfer mode.
skip The number of periodic advertising packets that can be skipped after a successful receive.
syncTimeout Synchronization timeout for the periodic advertising.
cteType Constant tone extension type(Used in AoD/AoA).
Returns
Status error code.
Set periodic advertising sync transfer parameters.
References LmgrIsExtCommandAllowed().
LlSetScanParam()
uint8_t LlSetScanParam (const LlScanParam_t * pParam)
Set scan parameters.
Parameters
pParam Scan parameters.
Returns
Status error code.
Set scan parameters.
Note
This function must only be called when scanning is disabled.
References lctrMsgHdr_t::dispId, lctrMsgHdr_t::event, lmgrCtrlBlk_t::features, lmgrPersistCtrlBlk_t::handlerId, lctrScanParamMsg_t::hdr, LCTR_DISP_SCAN, LCTR_SCAN_MSG_PARAM_UPD, LL_ADDR_RANDOM, LL_ADDR_RANDOM_IDENTITY, LL_FEAT_EXT_SCAN_FILT_POLICY, LL_FEAT_PRIVACY, LL_SCAN_ACTIVE, LL_SCAN_FILTER_WL_BIT, LL_SCAN_FILTER_WL_OR_RES_INIT, lmgrCb, LmgrIsLegacyCommandAllowed(), lmgrPersistCb, lmgrCtrlBlk_t::numInitEnabled, lmgrCtrlBlk_t::numScanEnabled, lmgrScanParam_t::ownAddrType, LlScanParam_t::ownAddrType, lctrScanParamMsg_t::param, lmgrScanParam_t::scanFiltPolicy, LlScanParam_t::scanFiltPolicy, lmgrScanParam_t::scanInterval, LlScanParam_t::scanInterval, lmgrScanParam_t::scanType, LlScanParam_t::scanType, lmgrScanParam_t::scanWindow, LlScanParam_t::scanWindow, WsfMsgAlloc(), and WsfMsgSend().
LlSetSetScanChanMap()
uint8_t LlSetSetScanChanMap (uint8_t chanMap)
Set scan channel map.
Parameters
chanMap Scan channel map.
Returns
Status error code.
Set scan channel map.
Note
This function must only be called when scanning is disabled.
References LL_ADV_CHAN_ALL, lmgrCb, lmgrMstScanCb, lmgrCtrlBlk_t::numInitEnabled, lmgrCtrlBlk_t::numScanEnabled, and lmgrMstScanCtrlBlk_t::scanChanMap.