Cordio: STACK_EVENT
STACK_EVENT
ATT Event Handling
Message passing interface to ATT from other tasks through WSF.
void AttHandlerInit (wsfHandlerId_t handlerId)
void AttHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
DM Event Handling
Message passing interface to DM from other tasks through WSF.
void DmHandlerInit (wsfHandlerId_t handlerId)
void DmHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
HCI Event Handling
Message passing interface to HCI from application and other stack layers through WSF.
void HciHandlerInit (wsfHandlerId_t handlerId)
void HciHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
L2CAP Event Handling
Message passing interface to L2CAP from other tasks through WSF.
void L2cSlaveHandlerInit (wsfHandlerId_t handlerId)
void L2cSlaveHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
void L2cCocHandlerInit (wsfHandlerId_t handlerId)
void L2cCocHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
SMP Event Handling
Message passing interface to SMP from other tasks through WSF.
void SmpHandlerInit (wsfHandlerId_t handlerId)
void SmpHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
App Event Handling
Message passing interface to App Framework from other tasks through WSF.
void AppHandlerInit (wsfHandlerId_t handlerId)
void AppHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
void AppGetBdAddr (uint8_t *pBdAddr)
Detailed Description
Function Documentation
AppGetBdAddr()
void AppGetBdAddr (uint8_t * pBdAddr)
Get Bluetooth device address currently used by LL or all zeros if address is not set.
Parameters
pBdAddr Pointer where address will be stored.
Returns
None.
References LlGetBdAddr().
AppHandler()
void AppHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for app framework.
Parameters
event WSF event mask.
pMsg WSF message.
Returns
None.
References AppUiBtnPressed(), wsfMsgHdr_t::event, and appCb_t::masterCback.
AppHandlerInit()
void AppHandlerInit (wsfHandlerId_t handlerId)
App framework handler init function called during system initialization.
Parameters
handlerId WSF handler ID for App.
Returns
None.
Parameters
handlerID WSF handler ID for App.
Returns
None.
References AppDbInit().
AttHandler()
void AttHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for ATT.
Parameters
event WSF event mask.
pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event.
AttHandlerInit()
void AttHandlerInit (wsfHandlerId_t handlerId)
ATT handler init function called during system initialization.
Parameters
handlerId WSF handler ID for ATT.
Returns
None.
Parameters
handlerID WSF handler ID for ATT.
Returns
None.
References DM_CLIENT_ID_ATT, DmConnRegister(), L2C_CID_ATT, and L2cRegister().
DmHandler()
void DmHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for DM.
Parameters
event WSF event mask.
pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, and WSF_ASSERT.
DmHandlerInit()
void DmHandlerInit (wsfHandlerId_t handlerId)
DM handler init function called during system initialization.
Parameters
handlerId WSF handler ID for DM.
Returns
None.
Parameters
handlerID WSF handler ID for DM.
Returns
None.
HciHandler()
void HciHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for HCI.
Parameters
event WSF event mask.
pMsg WSF message.
Returns
None.
References HciCoreHandler().
HciHandlerInit()
void HciHandlerInit (wsfHandlerId_t handlerId)
HCI handler init function called during system initialization.
Parameters
handlerId WSF handler ID for HCI.
Returns
None.
Parameters
handlerID WSF handler ID for HCI.
Returns
None.
References HciCoreInit(), and WSF_QUEUE_INIT.
L2cCocHandler()
void L2cCocHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
The WSF event handler for L2C with connection oriented channels.
Parameters
event Event mask.
pMsg Pointer to message.
Returns
None.
References wsfMsgHdr_t::event.
L2cCocHandlerInit()
void L2cCocHandlerInit (wsfHandlerId_t handlerId)
Event handler initialization function for L2C with connection oriented channels.
Parameters
handlerId ID for this event handler.
Returns
None.
L2cSlaveHandler()
void L2cSlaveHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
The WSF event handler for L2C when operating as a slave.
Parameters
event Event mask.
pMsg Pointer to message.
Returns
None.
References wsfMsgHdr_t::event, and WSF_ASSERT.
L2cSlaveHandlerInit()
void L2cSlaveHandlerInit (wsfHandlerId_t handlerId)
Event handler initialization function for L2C when operating as a slave.
Parameters
handlerId ID for this event handler.
Returns
None.
SmpHandler()
void SmpHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for SMP.
Parameters
event WSF event mask.
pMsg WSF message.
Returns
None.
References DM_CONN_ID_NONE, wsfMsgHdr_t::event, wsfMsgHdr_t::param, secCmacMsg_t::pPlainText, SMP_DB_SERVICE_IND, SMP_MSG_WSF_AES_CMPL, SMP_MSG_WSF_CMAC_CMPL, wsfMsgHdr_t::status, and WsfBufFree().
SmpHandlerInit()
void SmpHandlerInit (wsfHandlerId_t handlerId)
SMP handler init function called during system initialization.
Parameters
handlerId WSF handler ID for SMP.
Returns
None.
Parameters
handlerID WSF handler ID for SMP.
Returns
None.
References DM_CLIENT_ID_SMP, DM_CONN_MAX, DmConnRegister(), L2C_CID_SMP, L2cRegister(), and SmpDbInit().