Cordio: Mesh Core API
Mesh Core API
Data Structures
struct meshModelMsgRecvEvt_t
struct meshModelPeriodicPubEvt_t
union meshModelEvt_t
struct meshModelLink_t
struct meshSigModel_t
struct meshVendorModel_t
struct meshElement_t
struct meshMemoryConfig_t
struct meshNvmConfig_t
struct meshConfig_t
struct meshMsgInfo_t
struct meshPubMsgInfo_t
struct meshGattConnEvt_t
struct meshAdvIfEvt_t
struct meshAttentionEvt_t
struct meshNodeStartedEvt_t
struct meshProxyServiceDataEvt_t
struct meshProxyFilterStatusEvt_t
struct meshIvUpdtEvt_t
struct meshHbInfoEvt_t
union meshEvt_t
struct meshGattProxyPduSendEvt_t
struct meshAdvPduSendEvt_t
struct meshPrvData_t
union modelId_t
struct meshMsgOpcode_t
struct meshProdInfo_t
struct meshNwkTransState_t
struct meshRelayRetransState_t
struct meshModelPublicationParams_t
struct meshNetKeyList_t
struct meshAppNetKeyBind_t
struct meshAppKeyList_t
struct meshModelAppList_t
struct meshCompData_t
struct meshHbPub_t
struct meshHbSub_t
struct meshFriendshipCriteria_t
Macros
#define MESH_ADV_IF_ID_IS_VALID(advIfId) ((advIfId) <= 0x1F)
#define MESH_GATT_PROXY_CONN_ID_IS_VALID(connId) ((connId) <= 0x1F)
#define MESH_USE_DEFAULT_TTL 0xFF
#define MESH_MEM_REQ_INVALID_CFG 0xFFFFFFFF
#define MESH_CBACK_START 0xA0 /*! Mesh callback event starting value */
#define MMDL_SUBSCR_LIST_SHARED 0xFF
#define MESH_CORE_MAX_EVENT MESH_CORE_HB_INFO_EVENT /*! Mesh callback event ending value */
#define MESH_MSG_INFO(modelId, opcode)
#define MESH_PUB_MSG_INFO(modelId, opcode)
#define MESH_AD_TYPE_PB 0x29
#define MESH_AD_TYPE_PACKET 0x2A
#define MESH_AD_TYPE_BEACON 0x2B
#define MESH_BEACON_TYPE_UNPROV 0x00
#define MESH_BEACON_TYPE_SEC_NWK 0x01
#define MESH_AID_MASK 0x3F
#define MESH_AID_SHIFT 0
#define MESH_AID_SIZE 6
#define MESH_AKF_MASK 0x40
#define MESH_AKF_SHIFT 6
#define MESH_AKF_SIZE 1
#define MESH_SEG_MASK 0x80
#define MESH_SEG_SHIFT 7
#define MESH_SEG_SIZE 1
#define MESH_KEY_INDEX_SIZE 12
#define MESH_APP_KEY_INDEX_MAX_VAL 0x0FFF
#define MESH_NET_KEY_INDEX_MAX_VAL 0x0FFF
#define MESH_SZMIC_MASK 0x80
#define MESH_SZMIC_SHIFT 7
#define MESH_SZMIC_SIZE 1
#define MESH_IVI_MASK 0x80
#define MESH_IVI_MASK 0x80
#define MESH_IVI_SHIFT 7
#define MESH_IVI_SHIFT 7
#define MESH_IVI_SIZE 1
#define MESH_IVI_SIZE 1
#define MESH_TTL_MASK 0x7F
#define MESH_TTL_SHIFT 0
#define MESH_TTL_SIZE 7
#define MESH_CTL_MASK 0x80
#define MESH_CTL_SHIFT 7
#define MESH_CTL_SIZE 1
#define MESH_NID_MASK 0x7F
#define MESH_NID_SHIFT 0
#define MESH_NID_SIZE 7
#define MESH_CTL_OPCODE_MASK 0x7F
#define MESH_CTL_OPCODE_SHIFT 0
#define MESH_CTL_OPCODE_SIZE 7
#define MESH_OBO_MASK 0x80
#define MESH_OBO_SHIFT 7
#define MESH_OBO_SIZE 1
#define MESH_SEQ_ZERO_H_MASK 0x7F
#define MESH_SEQ_ZERO_H_SHIFT 0
#define MESH_SEQ_ZERO_H_SIZE 7
#define MESH_SEQ_ZERO_H_PDU_OFFSET 1
#define MESH_SEQ_ZERO_L_MASK 0xFC
#define MESH_SEQ_ZERO_L_SHIFT 2
#define MESH_SEQ_ZERO_L_SIZE 6
#define MESH_SEQ_ZERO_L_PDU_OFFSET 2
#define MESH_SEG_ZERO_H_MASK 0x03
#define MESH_SEG_ZERO_H_SHIFT 3
#define MESH_SEG_ZERO_H_PDU_OFFSET 2
#define MESH_SEG_ZERO_L_MASK 0xE0
#define MESH_SEG_ZERO_L_SHIFT 5
#define MESH_SEG_ZERO_L_PDU_OFFSET 3
#define MESH_SEQ_ZERO_MASK 0x001FFF
#define MESH_SEG_N_MASK 0x1F
#define MESH_SEG_N_PDU_OFFSET 3
#define MESH_SEG_ACK_OPCODE 0x00
#define MESH_SEG_OPCODE_PDU_OFFSET 0
#define MESH_SEG_ACK_LENGTH 7
#define MESH_SEG_ACK_PDU_LENGTH 6
#define MESH_ACC_MAX_PDU_SIZE 380
#define MESH_ACC_SEG_MAX_LENGTH 12
#define MESH_CTL_SEG_MAX_LENGTH 8
#define MESH_SEG_HEADER_LENGTH 4
#define MESH_SEG_DATA_PDU_OFFSET 4
#define MESH_SEQ_MASK 0x00FFFFFF
#define MESH_SEQ_SHIFT 0x00
#define MESH_SEQ_MAX_VAL 0x00FFFFFF
#define MESH_IV_NUM_BYTES 4
#define MESH_SEQ_NUM_BYTES 3
#define MESH_ADDR_NUM_BYTES 2
#define MESH_NWK_ID_NUM_BYTES 8
#define MESH_NETMIC_SIZE_CTL_PDU 8
#define MESH_NETMIC_SIZE_PROXY_PDU 8
#define MESH_NETMIC_SIZE_ACC_PDU 4
#define MESH_LABEL_UUID_SIZE 16
#define MESH_KEY_SIZE_128 16
#define MESH_NWK_CACHE_MIN_SIZE 2
#define MESH_RP_MIN_LIST_SIZE 1
#define MESH_ADV_PDU_POS 2
#define MESH_ADV_TYPE_POS 1
#define MESH_IVI_NID_POS 0
#define MESH_CTL_TTL_POS 1
#define MESH_SEQ_POS 2
#define MESH_SRC_ADDR_POS 5
#define MESH_DST_ADDR_POS 7
#define MESH_ADDR_TYPE_UNASSIGNED 0x0000
#define MESH_ADDR_TYPE_UNICAST_MASK 0x8000
#define MESH_ADDR_TYPE_GROUP_VIRTUAL_MASK 0xC000
#define MESH_ADDR_TYPE_GROUP_MSBITS_VALUE 0x03
#define MESH_ADDR_TYPE_VIRTUAL_MSBITS_VALUE 0x02
#define MESH_ADDR_TYPE_SHIFT 14
#define MESH_ADDR_GROUP_PROXY 0xFFFC
#define MESH_ADDR_GROUP_FRIEND 0xFFFD
#define MESH_ADDR_GROUP_RELAY 0xFFFE
#define MESH_ADDR_GROUP_ALL 0xFFFF
#define MESH_GATT_PROXY_PDU_MIN_VALUE 20
#define MESH_ADV_IF_PDU_MIN_VALUE 0x02
#define MESH_ADV_IF_PDU_MAX_VALUE 0x1F
#define MESH_PUBLISH_PERIOD_NUM_STEPS_MAX 64
#define MESH_PUBLISH_PERIOD_DISABLED_NUM_STEPS 0
#define MESH_PUBLISH_RETRANS_COUNT_MAX 7
#define MESH_PUBLISH_RETRANS_INTVL_STEPS_MAX 31
#define MESH_COMP_DATA_PAGE_MAX 255
#define MESH_CFG_MDL_SR_MODEL_ID 0x0000
#define MESH_CFG_MDL_CL_MODEL_ID 0x0001
#define MESH_PROXY_NWKID_SERVICE_DATA_SIZE 9
#define MESH_PROXY_NODE_ID_SERVICE_DATA_SIZE 17
#define MESH_PRV_MAX_PDU_LEN 66
#define MESH_NWK_MAX_PDU_LEN 29
#define MESH_NWK_MIN_PDU_LEN 14
#define MESH_NWK_HEADER_LEN 9
#define MESH_NWK_BEACON_NUM_BYTES 22
#define MESH_TX_TTL_FILTER_VALUE 1
#define MESH_PRV_PUB_KEY_SIZE 32
#define MESH_ACC_RSP_MIN_SEND_DELAY_MS 20
#define MESH_ACC_RSP_MAX_SEND_DELAY_MS(unicast) ((unicast) ? 50 : 500)
#define MESH_ERR_CODE_TO_MODULE(errCode) ((uint8_t)((errCode) >> 8))
#define MESH_ERR_CODE_TO_BASE_ERR(errCode) ((uint8_t)((errCode) & 0xFF))
#define MESH_IS_ADDR_UNASSIGNED(addr) ((addr) == MESH_ADDR_TYPE_UNASSIGNED)
#define MESH_IS_ADDR_UNICAST(addr)
#define MESH_IS_ADDR_FIXED_GROUP(addr) ((addr) > 0xFFFB)
#define MESH_IS_ADDR_DYN_GROUP(addr) (((addr) >= 0xC000) && ((addr) < 0xFF00))
#define MESH_IS_ADDR_GROUP(addr)
#define MESH_IS_ADDR_RFU(addr) (((addr) >= 0xFF00) && ((addr) < 0xFFFC))
#define MESH_ADDR_EXTRACT_TWO_MSBITS(addr)
#define MESH_IS_ADDR_VIRTUAL(addr)
#define MESH_OPCODE_IS_SIZE_ONE(opcode) (((opcode).opcodeBytes[0] & 0x80) == 0)
#define MESH_OPCODE_MSBITS_TO_SIZE(opcode) (((opcode).opcodeBytes[0] & 0xC0) >> 6)
#define MESH_OPCODE_SIZE(opcode)
#define MESH_OPCODE_IS_VALID(opcode) (!((opcode).opcodeBytes[0] == 0x7F))
#define MESH_OPCODE_IS_VENDOR(opcode) (MESH_OPCODE_SIZE(opcode) == 3)
#define MESH_BEACON_STATE_IS_VALID(beacon) ((beacon == 0) || (beacon == 1))
#define MESH_TTL_IS_VALID(ttl) (!(((ttl) >= 0x80) && ((ttl) < 0xFF)))
#define MESH_SEQ_IS_VALID(seqNo) ((seqNo) <= MESH_SEQ_MAX_VAL)
#define MESH_VENDOR_MODEL_ID_TO_COMPANY_ID(modelId) ((uint16_t)((modelId) >> 16))
#define MESH_VENDOR_MODEL_ID_TO_MODEL_ID(modelId) ((uint16_t)((modelId) & 0xFFFF))
#define MESH_VENDOR_MODEL_MK(compId, modelId)
#define MESH_VENDOR_OPCODE_MK(opcode, compId)
Typedefs
typedef uint8_t meshMemConfigOptFeat_t
typedef uint8_t meshGattProxyConnId_t
typedef uint8_t meshProxyFilterType_t
typedef uint8_t meshProxyIdType_t
typedef uint8_t meshAdvIfId_t
typedef void(* meshCback_t) (meshEvt_t *pEvt)
typedef uint8_t meshPrvFlags_t
typedef void(* meshGattProxyPduSendCback_t) (meshGattProxyPduSendEvt_t *pEvt)
typedef void(* meshAdvPduSendCback_t) (meshAdvPduSendEvt_t *pEvt)
typedef uint16_t meshAddress_t
typedef uint16_t meshSigModelId_t
typedef uint32_t meshVendorModelId_t
typedef uint8_t meshElementId_t
typedef uint32_t meshSeqNumber_t
typedef uint16_t meshFeatures_t
typedef uint8_t meshPublishPeriodNumSteps_t
typedef uint8_t meshPublishPeriodStepRes_t
typedef uint8_t meshPublishFriendshipCred_t
typedef uint8_t meshPublishRetransCount_t
typedef uint8_t meshPublishRetransIntvlSteps_t
typedef uint8_t meshRelayStates_t
typedef uint8_t meshBeaconStates_t
typedef uint8_t meshGattProxyStates_t
typedef uint8_t meshNodeIdentityStates_t
typedef uint8_t meshFriendStates_t
typedef uint8_t meshLowPowerStates_t
typedef uint8_t meshKeyRefreshStates_t
typedef uint8_t meshKeyRefreshTrans_t
typedef uint8_t meshFriendshipRssiFactor_t
typedef uint8_t meshFriendshipRecvWinFactor_t
typedef uint8_t meshFriendshipMinQueueSizeLog_t
typedef uint8_t meshGattProxyPduType_t
Enumerations
enum meshEvents
enum meshEventValues
enum meshModelEventValues
enum MeshGattProxyPduSendEvent
enum meshAdvIfPduSendEvent
enum meshFeaturesBitMaskValues
enum meshPublishPeriodStepResValues
enum meshPublishCredValues
enum meshRelayStatesValues
enum meshBeaconStatesValues
enum meshGattProxyStatesValues
enum meshNodeIdentityStatesValues
enum meshFriendStatesValues
enum meshLowPowerStatesValues
enum meshKeyRefreshStatesValues
enum meshKeyRefreshTransValues
enum meshHtModelFaultValues
enum meshHtModelTestIdValues
enum meshProxyFilterType
enum meshProxyIdType
enum meshGattProxyPduTypes
enum meshFriendshipRssiFactorValues
enum meshFriendshipRecvWinFactorValues
enum meshFriendshipMinQueueSizeLogValues
enum meshFriendshipRecvDelayValues
enum meshFriendshipRecvWinValues
enum meshReturnValues
Functions
uint32_t MeshGetRequiredMemory (void)
uint32_t MeshInit (uint8_t *pFreeMem, uint32_t freeMemSize)
void MeshRegister (meshCback_t meshCback)
void MeshFactoryReset (void)
bool_t MeshIsProvisioned (void)
void MeshStartNode (void)
void MeshSendMessage (const meshMsgInfo_t *pMsgInfo, const uint8_t *pMsgParam, uint16_t msgParamLen, uint32_t rndDelayMsMin, uint32_t rndDelayMsMax)
void MeshPublishMessage (meshPubMsgInfo_t *pPubMsgInfo, const uint8_t *pMsgParam, uint16_t msgParamLen)
void MeshGattProxyInit (void)
void MeshRegisterGattProxyPduSendCback (meshGattProxyPduSendCback_t cback)
void MeshAddGattProxyConn (meshGattProxyConnId_t connId, uint16_t maxProxyPdu)
void MeshRemoveGattProxyConn (meshGattProxyConnId_t connId)
bool_t MeshIsGattProxyEnabled (void)
void MeshProcessGattProxyPdu (meshGattProxyConnId_t connId, const uint8_t *pProxyPdu, uint16_t proxyPduLen)
void MeshSignalGattProxyIfRdy (meshGattProxyConnId_t connId)
void MeshProxyClSetFilterType (meshGattProxyConnId_t connId, uint16_t netKeyIndex, meshProxyFilterType_t filterType)
void MeshProxyClAddToFilter (meshGattProxyConnId_t connId, uint16_t netKeyIndex, meshAddress_t *pAddrArray, uint16_t listSize)
void MeshProxyClRemoveFromFilter (meshGattProxyConnId_t connId, uint16_t netKeyIndex, meshAddress_t *pAddrArray, uint16_t listSize)
void MeshRegisterAdvIfPduSendCback (meshAdvPduSendCback_t cback)
void MeshAddAdvIf (meshAdvIfId_t advIfId)
void MeshRemoveAdvIf (meshAdvIfId_t advIfId)
void MeshProcessAdvPdu (meshAdvIfId_t advIfId, const uint8_t *pAdvPdu, uint8_t advPduLen)
void MeshSignalAdvIfRdy (meshAdvIfId_t advIfId)
void MeshLoadPrvData (const meshPrvData_t *pPrvData)
void MeshProxySrInit (void)
void MeshProxySrGetServiceData (uint16_t netKeyIndex, meshProxyIdType_t idType)
void MeshProxySrGetNextServiceData (meshProxyIdType_t idType)
void MeshProxyClInit (void)
void MeshAttentionSet (meshElementId_t elemId, uint8_t attTimeSec)
uint8_t MeshAttentionGet (meshElementId_t elemId)
uint16_t MeshSizeOfEvt (meshEvt_t *pMeshEvt)
void MeshHandlerInit (wsfHandlerId_t handlerId)
void MeshHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
void MeshSecurityHandlerInit (wsfHandlerId_t handlerId)
void MeshSecurityHandler (wsfEventMask_t event, wsfMsgHdr_t *pMsg)
Variables
meshConfig_t * pMeshConfig
Detailed Description
Data Structure Documentation
meshModelMsgRecvEvt_t
struct meshModelMsgRecvEvt_t
Mesh Model event for MESH_MODEL_EVT_MSG_RECV.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t srcAddr
uint8_t ttl
bool_t recvOnUnicast
meshMsgOpcode_t opCode
uint8_t * pMessageParams
uint16_t messageParamsLen
uint16_t appKeyIndex
modelId_t modelId
Field Documentation
appKeyIndex
uint16_t appKeyIndex
Global Application Key identifier.
elementId
meshElementId_t elementId
Identifier of the element which received the message
hdr
wsfMsgHdr_t hdr
Header structure
messageParamsLen
uint16_t messageParamsLen
Message parameters data length
modelId
modelId_t modelId
Model identifier.
opCode
meshMsgOpcode_t opCode
Opcode of the message
pMessageParams
uint8_t* pMessageParams
Pointer to the message parameters
recvOnUnicast
bool_t recvOnUnicast
Indicates if message was received on unicast
srcAddr
meshAddress_t srcAddr
Address off the element that sent the message
ttl
uint8_t ttl
TTL of the received message.
meshModelPeriodicPubEvt_t
struct meshModelPeriodicPubEvt_t
Mesh Model event for MESH_MODEL_EVT_PERIODIC_PUB.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
uint32_t nextPubTimeMs
modelId_t modelId
bool_t isVendorModel
Field Documentation
elementId
meshElementId_t elementId
Identifier of the element which received the message
hdr
wsfMsgHdr_t hdr
Header structure
isVendorModel
bool_t isVendorModel
Vendor Model identifier
modelId
modelId_t modelId
Model identifier.
nextPubTimeMs
uint32_t nextPubTimeMs
Next publication time in ms
meshModelEvt_t
union meshModelEvt_t
Mesh Model event union.
Data Fields
meshModelMsgRecvEvt_t msgRecvEvt
meshModelPeriodicPubEvt_t periodicPubEvt
Field Documentation
msgRecvEvt
meshModelMsgRecvEvt_t msgRecvEvt
Mesh Model message received event
periodicPubEvt
meshModelPeriodicPubEvt_t periodicPubEvt
Mesh Model periodic publish timer expired event
meshModelLink_t
struct meshModelLink_t
Mesh model subscription list link.
Data Fields
modelId_t rootModelId
meshElementId_t rootElementId
bool_t isSig
Field Documentation
isSig
bool_t isSig
TRUE if model identifier is SIG, FALSE for vendor
rootElementId
meshElementId_t rootElementId
Identifier of the element which shares the subscription list
rootModelId
modelId_t rootModelId
Identifier of the model which shares the subscription list
meshSigModel_t
struct meshSigModel_t
Mesh SIG model definition.
Data Fields
void * pModelDescriptor
wsfHandlerId_t * pHandlerId
const meshMsgOpcode_t * pRcvdOpcodeArray
const meshModelLink_t * pModelLink
meshSigModelId_t modelId
uint8_t opcodeCount
uint8_t subscrListSize
uint8_t appKeyBindListSize
Field Documentation
appKeyBindListSize
uint8_t appKeyBindListSize
AppKey to Model bind list size
modelId
meshSigModelId_t modelId
Model ID, as assigned by the SIG
opcodeCount
uint8_t opcodeCount
Number of SIG defined opcodes supported
pHandlerId
wsfHandlerId_t* pHandlerId
Pointer to Model WSF handler ID
pModelDescriptor
void* pModelDescriptor
Pointer to the model descriptor
pModelLink
const meshModelLink_t* pModelLink
Pointer to the model link descriptor
pRcvdOpcodeArray
const meshMsgOpcode_t* pRcvdOpcodeArray
Pointer to array of supported received SIG opcodes
subscrListSize
uint8_t subscrListSize
Subscription list size
meshVendorModel_t
struct meshVendorModel_t
Mesh Vendor model definition.
Data Fields
void * pModelDescriptor
wsfHandlerId_t * pHandlerId
const meshMsgOpcode_t * pRcvdOpcodeArray
meshModelLink_t * pModelLink
meshVendorModelId_t modelId
uint8_t opcodeCount
uint8_t subscrListSize
uint8_t appKeyBindListSize
Field Documentation
appKeyBindListSize
uint8_t appKeyBindListSize
AppKey to Model bind list size
modelId
meshVendorModelId_t modelId
Model ID, as assigned by vendor
opcodeCount
uint8_t opcodeCount
Number of SIG defined opcodes supported
pHandlerId
wsfHandlerId_t* pHandlerId
Pointer to Model WSF handler ID
pModelDescriptor
void* pModelDescriptor
Pointer to the model descriptor
pModelLink
meshModelLink_t* pModelLink
Pointer to the model link descriptor
pRcvdOpcodeArray
const meshMsgOpcode_t* pRcvdOpcodeArray
Pointer to array of supported received SIG opcodes
subscrListSize
uint8_t subscrListSize
Subscription list size
meshElement_t
struct meshElement_t
Mesh element definition
Usage:
const meshSigModel_t elem0SigModels[2] = {{.modelId = 0xaaaa}, {.modelId = 0xbbbb}};
meshElement_t firstElement =
{
  .numSigModels         = 2,
  .numVendorModels      = 0,
  .pSigModelArray       = elem0SigModels,
  .pVendorModedArray    = NULL
};
Data Fields
uint16_t locationDescriptor
uint8_t numSigModels
uint8_t numVendorModels
const meshSigModel_t * pSigModelArray
const meshVendorModel_t * pVendorModelArray
Field Documentation
locationDescriptor
uint16_t locationDescriptor
Location descriptor as defined in the GATT Bluetooth Namespace
numSigModels
uint8_t numSigModels
Number of SIG models in this element
numVendorModels
uint8_t numVendorModels
Number of Vendor models in this element
pSigModelArray
const meshSigModel_t* pSigModelArray
Pointer to array containing numSigModels number of SIG models in this element
pVendorModelArray
const meshVendorModel_t* pVendorModelArray
Pointer to array containing numVendorModels number of vendor models for this element
meshMemoryConfig_t
struct meshMemoryConfig_t
Mesh configuration memory descriptor.
Data Fields
uint16_t addrListMaxSize
uint16_t virtualAddrListMaxSize
uint16_t appKeyListSize
uint16_t netKeyListSize
uint8_t nwkCacheL1Size
uint16_t rpListSize
uint8_t nwkCacheL2Size
uint8_t nwkOutputFilterSize
uint8_t sarRxTranHistorySize
uint8_t sarRxTranInfoSize
uint8_t sarTxMaxTransactions
uint16_t cfgMdlClMaxSrSupported
uint8_t maxNumFriendships
uint8_t maxNumFriendQueueEntries
uint8_t maxFriendSubscrListSize
Field Documentation
addrListMaxSize
uint16_t addrListMaxSize
Maximum number of non-virtual addresses stored
appKeyListSize
uint16_t appKeyListSize
Maximum number of AppKeys stored
cfgMdlClMaxSrSupported
uint16_t cfgMdlClMaxSrSupported
Maximum number of Configuration Servers supported simultaneously by the Configuration Client
maxFriendSubscrListSize
uint8_t maxFriendSubscrListSize
Maximum number of subscription addresses for a friendship
maxNumFriendQueueEntries
uint8_t maxNumFriendQueueEntries
Maximum number of entries for a friend queue
maxNumFriendships
uint8_t maxNumFriendships
Maximum number of friendships this node can establish
netKeyListSize
uint16_t netKeyListSize
Maximum number of NetKeys stored
nwkCacheL1Size
uint8_t nwkCacheL1Size
Maximum number of elements in Level 1 Network Cache
nwkCacheL2Size
uint8_t nwkCacheL2Size
Maximum number of elements in Level 2 Network
nwkOutputFilterSize
uint8_t nwkOutputFilterSize
Maximum number of element addresses in the output filter of a network interface
rpListSize
uint16_t rpListSize
Maximum number of elements in Replay Protection List
sarRxTranHistorySize
uint8_t sarRxTranHistorySize
Maximum number of elements in SAR Rx Transaction History
sarRxTranInfoSize
uint8_t sarRxTranInfoSize
Maximum number of elements in SAR Rx Transaction Info Table
sarTxMaxTransactions
uint8_t sarTxMaxTransactions
Maximum number of SAR TX transactions
virtualAddrListMaxSize
uint16_t virtualAddrListMaxSize
Maximum number of virtual addresses stored
meshNvmConfig_t
struct meshNvmConfig_t
Mesh NVM configuration descriptor.
Data Fields
uint8_t instanceId
uint32_t startAddress
uint32_t endAddress
Field Documentation
endAddress
uint32_t endAddress
End address in persistent memory
instanceId
uint8_t instanceId
Mesh NVM instance ID
startAddress
uint32_t startAddress
Start address in persistent memory
meshConfig_t
struct meshConfig_t
Mesh Stack initial configuration structure.
Data Fields
const meshElement_t * pElementArray
uint8_t elementArrayLen
meshMemoryConfig_t * pMemoryConfig
Field Documentation
elementArrayLen
uint8_t elementArrayLen
Length of the element array
pElementArray
const meshElement_t* pElementArray
Pointer to array describing elements present in the node
pMemoryConfig
meshMemoryConfig_t* pMemoryConfig
Memory configuration for internal storage
meshMsgInfo_t
struct meshMsgInfo_t
Contains information that identifies a Mesh message.
Message identifier structure
Data Fields
modelId_t modelId
meshMsgOpcode_t opcode
meshElementId_t elementId
uint8_t * pDstLabelUuid
meshAddress_t dstAddr
uint16_t appKeyIndex
uint8_t ttl
Field Documentation
appKeyIndex
uint16_t appKeyIndex
Global identifier of the Application Key.
dstAddr
meshAddress_t dstAddr
Message destination address
elementId
meshElementId_t elementId
Identifier of the originating element
modelId
modelId_t modelId
Model identifier.
opcode
meshMsgOpcode_t opcode
Message operation code
pDstLabelUuid
uint8_t* pDstLabelUuid
Label UUID pointer for destination virtual address
ttl
uint8_t ttl
Initial TTL of the message, or MESH_USE_DEFAULT_TTL
meshPubMsgInfo_t
struct meshPubMsgInfo_t
Contains information that identifies a published Mesh message.
Published message identifier structure
Data Fields
meshMsgOpcode_t opcode
meshElementId_t elementId
modelId_t modelId
Field Documentation
elementId
meshElementId_t elementId
Identifier of the originating element
modelId
modelId_t modelId
Model identifier.
opcode
meshMsgOpcode_t opcode
Message operation code
meshGattConnEvt_t
struct meshGattConnEvt_t
GATT Proxy connection event type.
GATT Proxy connection event type for MESH_CORE_GATT_CONN_ADD_EVENT, MESH_CORE_GATT_CONN_REMOVE_EVENT, MESH_CORE_GATT_CONN_CLOSE_EVENT, MESH_CORE_GATT_PROCESS_PROXY_PDU_EVENT, MESH_CORE_GATT_SIGNAL_IF_RDY_EVENT
Data Fields
wsfMsgHdr_t hdr
meshGattProxyConnId_t connId
Field Documentation
connId
meshGattProxyConnId_t connId
Connection identifier
hdr
wsfMsgHdr_t hdr
Header structure
meshAdvIfEvt_t
struct meshAdvIfEvt_t
ADV interface event type.
ADV interface event type for MESH_CORE_ADV_IF_ADD_EVENT, MESH_CORE_ADV_IF_REMOVE_EVENT, MESH_CORE_ADV_IF_CLOSE_EVENT, MESH_CORE_ADV_PROCESS_PDU_EVENT, MESH_CORE_ADV_SIGNAL_IF_RDY_EVENT
Data Fields
wsfMsgHdr_t hdr
meshAdvIfId_t ifId
Field Documentation
hdr
wsfMsgHdr_t hdr
Header structure. Used with MESH_CORE_ADV_EVENT* events
ifId
meshAdvIfId_t ifId
ADV Interface identifier
meshAttentionEvt_t
struct meshAttentionEvt_t
Attention event type for MESH_CORE_ATTENTION_CHG_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
bool_t attentionOn
Field Documentation
attentionOn
bool_t attentionOn
New attention state
elementId
meshElementId_t elementId
Element identifier
hdr
wsfMsgHdr_t hdr
Header structure
meshNodeStartedEvt_t
struct meshNodeStartedEvt_t
Mesh event type for MESH_CORE_NODE_STARTED_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshAddress_t address
uint8_t elemCnt
Field Documentation
address
meshAddress_t address
Primary element address
elemCnt
uint8_t elemCnt
Number of elements
hdr
wsfMsgHdr_t hdr
Header structure
meshProxyServiceDataEvt_t
struct meshProxyServiceDataEvt_t
Proxy Service Data event type for MESH_CORE_PROXY_SERVICE_DATA_EVENT.
Data Fields
wsfMsgHdr_t hdr
uint8_t serviceData [MESH_PROXY_NODE_ID_SERVICE_DATA_SIZE]
uint8_t serviceDataLen
Field Documentation
hdr
wsfMsgHdr_t hdr
Header structure
serviceData
uint8_t serviceData[MESH_PROXY_NODE_ID_SERVICE_DATA_SIZE]
Service data
serviceDataLen
uint8_t serviceDataLen
Service data length
meshProxyFilterStatusEvt_t
struct meshProxyFilterStatusEvt_t
Proxy Filter Status event type for MESH_CORE_PROXY_FILTER_STATUS_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshGattProxyConnId_t connId
meshProxyFilterType_t filterType
uint16_t listSize
Field Documentation
connId
meshGattProxyConnId_t connId
Connection identifier
filterType
meshProxyFilterType_t filterType
Proxy filter type
hdr
wsfMsgHdr_t hdr
Header structure
listSize
uint16_t listSize
Proxy filter list size
meshIvUpdtEvt_t
struct meshIvUpdtEvt_t
Mesh IV updated event type for MESH_CORE_IV_UPDATED_EVENT.
Data Fields
wsfMsgHdr_t hdr
uint32_t ivIndex
Field Documentation
hdr
wsfMsgHdr_t hdr
Header structure
ivIndex
uint32_t ivIndex
IV index
meshHbInfoEvt_t
struct meshHbInfoEvt_t
Received Heartbeat info event type for MESH_CORE_HB_INFO_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshAddress_t src
meshFeatures_t features
uint8_t hops
uint8_t minHops
uint8_t maxHops
Field Documentation
features
meshFeatures_t features
Received features bitmask
hdr
wsfMsgHdr_t hdr
Header structure
hops
uint8_t hops
Hops taken by the Heartbeat message to reach the node
maxHops
uint8_t maxHops
Computed Maximum Hops value
minHops
uint8_t minHops
Computed Minimum Hops value
src
meshAddress_t src
SRC address
meshEvt_t
union meshEvt_t
Union of all Mesh Stack events.
Data Fields
wsfMsgHdr_t hdr
meshAdvIfEvt_t advIf
meshGattConnEvt_t gattConn
meshAttentionEvt_t attention
meshNodeStartedEvt_t nodeStarted
meshProxyServiceDataEvt_t serviceData
meshProxyFilterStatusEvt_t filterStatus
meshIvUpdtEvt_t ivUpdt
meshHbInfoEvt_t hbInfo
Field Documentation
advIf
meshAdvIfEvt_t advIf
Advertising interface API event data. See meshAdvIfEvt_t
attention
meshAttentionEvt_t attention
Attention event data. See meshAttentionEvt_t
filterStatus
meshProxyFilterStatusEvt_t filterStatus
Proxy filter status event. See meshProxyFilterStatusEvt_t
gattConn
meshGattConnEvt_t gattConn
GATT connection API event data. See meshGattConnEvt_t
hbInfo
meshHbInfoEvt_t hbInfo
Hearbeat information event. See::meshHbInfoEvt_t
hdr
wsfMsgHdr_t hdr
Generic WSF header. Used for the following events: MESH_CORE_RESET_EVENT MESH_CORE_ERROR_EVENT MESH_CORE_SEND_MSG_EVENT MESH_CORE_PUBLISH_MSG_EVENT
ivUpdt
meshIvUpdtEvt_t ivUpdt
IV updated event
nodeStarted
meshNodeStartedEvt_t nodeStarted
Node Started event data
serviceData
meshProxyServiceDataEvt_t serviceData
Proxy service data. See meshProxyServiceDataEvt_t
meshGattProxyPduSendEvt_t
struct meshGattProxyPduSendEvt_t
GATT Proxy PDU received event type.
Data Fields
wsfMsgHdr_t hdr
const uint8_t * pProxyPdu
uint16_t proxyPduLen
uint8_t proxyHdr
meshGattProxyConnId_t connId
Field Documentation
connId
meshGattProxyConnId_t connId
Connection identifier
hdr
wsfMsgHdr_t hdr
Header structure
pProxyPdu
const uint8_t* pProxyPdu
Pointer to a buffer containing a Proxy PDU
proxyHdr
uint8_t proxyHdr
Header value for a Proxy PDU
proxyPduLen
uint16_t proxyPduLen
Length of the Proxy PDU (incl. header) message
meshAdvPduSendEvt_t
struct meshAdvPduSendEvt_t
ADV interface PDU send event type.
Data Fields
wsfMsgHdr_t hdr
meshAdvIfId_t ifId
uint8_t adType
const uint8_t * pAdvPdu
uint8_t advPduLen
Field Documentation
adType
uint8_t adType
AD type.
advPduLen
uint8_t advPduLen
Length of the advertising PDU
hdr
wsfMsgHdr_t hdr
Header structure
ifId
meshAdvIfId_t ifId
ADV Interface identifier
pAdvPdu
const uint8_t* pAdvPdu
Pointer to a buffer containing an ADV PDU
meshPrvData_t
struct meshPrvData_t
Provisioning data type.
Data Fields
uint8_t * pDevKey
uint8_t * pNetKey
uint32_t ivIndex
uint16_t netKeyIndex
meshAddress_t primaryElementAddr
meshPrvFlags_t flags
Field Documentation
flags
meshPrvFlags_t flags
Provisioning flags bitmask
ivIndex
uint32_t ivIndex
Current value of the IV Index
netKeyIndex
uint16_t netKeyIndex
Global identifier of the Network Key
pDevKey
uint8_t* pDevKey
Pointer to DevKey array (not mandatory)
pNetKey
uint8_t* pNetKey
Pointer to NetKey array
primaryElementAddr
meshAddress_t primaryElementAddr
Unicast address of the primary element
modelId_t
union modelId_t
Union of SIG and vendor model identifiers.
Data Fields
meshSigModelId_t sigModelId
meshVendorModelId_t vendorModelId
Field Documentation
sigModelId
meshSigModelId_t sigModelId
SIG Model identifier
vendorModelId
meshVendorModelId_t vendorModelId
Vendor Model identifier
meshMsgOpcode_t
struct meshMsgOpcode_t
Message operation code structure.
Data Fields
uint8_t opcodeBytes [3]
Field Documentation
opcodeBytes
uint8_t opcodeBytes[3]
Opcode bytes
meshProdInfo_t
struct meshProdInfo_t
Data type for storing the product information values.
Data Fields
uint16_t companyId
uint16_t productId
uint16_t versionId
Field Documentation
companyId
uint16_t companyId
Company Identifier
productId
uint16_t productId
Product Identifier
versionId
uint16_t versionId
Version Identifier
meshNwkTransState_t
struct meshNwkTransState_t
Network Transmit state.
Data Fields
uint8_t transCount
uint8_t transIntervalSteps10Ms
Field Documentation
transCount
uint8_t transCount
Number of transmissions for each Network PDU
transIntervalSteps10Ms
uint8_t transIntervalSteps10Ms
Number of 10-millisecond steps between transmissions
meshRelayRetransState_t
struct meshRelayRetransState_t
Relay Retransmit state.
Data Fields
uint8_t retransCount
uint8_t retransIntervalSteps10Ms
Field Documentation
retransCount
uint8_t retransCount
Number of retransmission on advertising bearer for each Network PDU
retransIntervalSteps10Ms
uint8_t retransIntervalSteps10Ms
Number of 10-millisecond steps between retransmissions
meshModelPublicationParams_t
struct meshModelPublicationParams_t
Structure to store Model Publication state informations.
Data Fields
uint16_t publishAppKeyIndex
meshPublishPeriodNumSteps_t publishPeriodNumSteps
meshPublishPeriodStepRes_t publishPeriodStepRes
meshPublishFriendshipCred_t publishFriendshipCred
uint8_t publishTtl
meshPublishRetransCount_t publishRetransCount
meshPublishRetransIntvlSteps_t publishRetransSteps50Ms
Field Documentation
publishAppKeyIndex
uint16_t publishAppKeyIndex
Publish AppKey Index
publishFriendshipCred
meshPublishFriendshipCred_t publishFriendshipCred
Publish friendship security material
publishPeriodNumSteps
meshPublishPeriodNumSteps_t publishPeriodNumSteps
Publish period number of steps
publishPeriodStepRes
meshPublishPeriodStepRes_t publishPeriodStepRes
Publish period step resolution
publishRetransCount
meshPublishRetransCount_t publishRetransCount
Publish retransmit count
publishRetransSteps50Ms
meshPublishRetransIntvlSteps_t publishRetransSteps50Ms
Publish 50 ms retransmit steps
publishTtl
uint8_t publishTtl
Publish TTL
meshNetKeyList_t
struct meshNetKeyList_t
NetKey index list for a specific node.
Data Fields
uint8_t netKeyCount
uint16_t * pNetKeyIndexes
Field Documentation
netKeyCount
uint8_t netKeyCount
Size of the pNetKeyIndexes array
pNetKeyIndexes
uint16_t* pNetKeyIndexes
Array of NetKey indexes
meshAppNetKeyBind_t
struct meshAppNetKeyBind_t
Key indexes for a NetKey and a bound AppKey.
Data Fields
uint16_t netKeyIndex
uint16_t appKeyIndex
Field Documentation
appKeyIndex
uint16_t appKeyIndex
AppKey index
netKeyIndex
uint16_t netKeyIndex
Associated NetKey index
meshAppKeyList_t
struct meshAppKeyList_t
AppKey index list bound to a specific NetKey index.
Data Fields
uint16_t netKeyIndex
uint8_t appKeyCount
uint16_t * pAppKeyIndexes
Field Documentation
appKeyCount
uint8_t appKeyCount
Size of the pAppKeyIndexes array
netKeyIndex
uint16_t netKeyIndex
Associated NetKey index
pAppKeyIndexes
uint16_t* pAppKeyIndexes
Array of AppKey indexes
meshModelAppList_t
struct meshModelAppList_t
AppKey index list bound to a specific model.
Data Fields
meshAddress_t elemAddr
modelId_t modelId
bool_t isSig
uint8_t appKeyCount
uint16_t * pAppKeyIndexes
Field Documentation
appKeyCount
uint8_t appKeyCount
Size of the pAppKeyIndexes array
elemAddr
meshAddress_t elemAddr
Address of the element containing the model
isSig
bool_t isSig
TRUE if model identifier is SIG, FALSE for vendor
modelId
modelId_t modelId
Model identifier
pAppKeyIndexes
uint16_t* pAppKeyIndexes
Array of AppKey indexes
meshCompData_t
struct meshCompData_t
Composition Data.
Data Fields
uint8_t pageNumber
uint16_t pageSize
uint8_t * pPage
Field Documentation
pageNumber
uint8_t pageNumber
Page number
pageSize
uint16_t pageSize
Size of the pPage array
pPage
uint8_t* pPage
Page in raw octet format (as received over the air)
meshHbPub_t
struct meshHbPub_t
Heartbeat Publication state data.
Data Fields
meshAddress_t dstAddr
uint8_t countLog
uint8_t periodLog
uint8_t ttl
meshFeatures_t features
uint16_t netKeyIndex
Field Documentation
countLog
uint8_t countLog
Number of heartbeat messages to be sent
dstAddr
meshAddress_t dstAddr
Destination address for heartbeat message
features
meshFeatures_t features
Bit field for features that trigger heartbeat messages
netKeyIndex
uint16_t netKeyIndex
Associated NetKey index
periodLog
uint8_t periodLog
Period for sending heartbeat messages
ttl
uint8_t ttl
TTL used when sending heartbeat messages
meshHbSub_t
struct meshHbSub_t
Heartbeat Subscription state data.
Data Fields
meshAddress_t srcAddr
meshAddress_t dstAddr
uint8_t periodLog
uint8_t countLog
uint8_t minHops
uint8_t maxHops
Field Documentation
countLog
uint8_t countLog
Number of heartbeat messages to be sent
dstAddr
meshAddress_t dstAddr
Destination address for heartbeat message
maxHops
uint8_t maxHops
Max hops when receiving heartbeats
minHops
uint8_t minHops
Min hops when receiving heartbeats
periodLog
uint8_t periodLog
Period for sending heartbeat messages
srcAddr
meshAddress_t srcAddr
Source address for heartbeat message
meshFriendshipCriteria_t
struct meshFriendshipCriteria_t
Mesh Friendship Criteria structure.
Data Fields
meshFriendshipRssiFactor_t rssiFactor
meshFriendshipRecvWinFactor_t recvWinFactor
meshFriendshipMinQueueSizeLog_t minQueueSizeLog
Field Documentation
minQueueSizeLog
meshFriendshipMinQueueSizeLog_t minQueueSizeLog
Min Queue size log
recvWinFactor
meshFriendshipRecvWinFactor_t recvWinFactor
Receive Window factor
rssiFactor
meshFriendshipRssiFactor_t rssiFactor
RSSI factor
Macro Definition Documentation
MESH_ACC_RSP_MAX_SEND_DELAY_MS
#define MESH_ACC_RSP_MAX_SEND_DELAY_MS (unicast) ((unicast) ? 50 : 500)
Recommended maximum value for the random delay used in sending an Access message response
MESH_ACC_RSP_MIN_SEND_DELAY_MS
#define MESH_ACC_RSP_MIN_SEND_DELAY_MS 20
Recommended minimum value for the random delay used in sending an Access message response
MESH_IVI_MASK [1/2]
#define MESH_IVI_MASK 0x80
Mesh IVI field mask.
Mesh IV Index bit mask.
MESH_IVI_MASK [2/2]
#define MESH_IVI_MASK 0x80
Mesh IVI field mask.
Mesh IV Index bit mask.
MESH_IVI_SHIFT [1/2]
#define MESH_IVI_SHIFT 7
Mesh IVI field shift value.
Mesh IV Index bit shift value.
MESH_IVI_SHIFT [2/2]
#define MESH_IVI_SHIFT 7
Mesh IVI field shift value.
Mesh IV Index bit shift value.
MESH_IVI_SIZE [1/2]
#define MESH_IVI_SIZE 1
Mesh IVI field size.
Mesh IV Index field size bits.
MESH_IVI_SIZE [2/2]
#define MESH_IVI_SIZE 1
Mesh IVI field size.
Mesh IV Index field size bits.
MESH_NWK_CACHE_MIN_SIZE
#define MESH_NWK_CACHE_MIN_SIZE 2
Mesh Profile Spec 3.4.6.5: The Network Message Cache shall be able to store at least two Network PDUs
MESH_OPCODE_IS_SIZE_ONE
#define MESH_OPCODE_IS_SIZE_ONE (opcode) (((opcode).opcodeBytes[0] & 0x80) == 0)
Determines if a meshMsgOpcode_t message operation code has only one byte (opcode[0] == 0b0xxxxxxx)
Remarks
Do not use directly. Use MESH_OPCODE_SIZE instead
MESH_OPCODE_MSBITS_TO_SIZE
#define MESH_OPCODE_MSBITS_TO_SIZE (opcode) (((opcode).opcodeBytes[0] & 0xC0) >> 6)
opcode[0] is 0b10xxxxxx if opcode size is 2 or 0b11xxxxxx if opcode size is 3
Extract the two MSBits from a meshMsgOpcode_t message operation code that specify if its size is 2 or 3
Remarks
Do not use directly. Use MESH_OPCODE_SIZE instead
Typedef Documentation
meshPublishPeriodNumSteps_t
typedef uint8_t meshPublishPeriodNumSteps_t
Publish period number of steps. Publish period is number of steps * step resolution
See also
MESH_PUBLISH_PERIOD_NUM_STEPS_MAX
MESH_PUBLISH_PERIOD_DISABLED_NUM_STEPS
meshPublishRetransIntvlSteps_t
typedef uint8_t meshPublishRetransIntvlSteps_t
Number of 50 millisecond steps between retransmissions of published messages. See MESH_PUBLISH_RETRANS_INTVL_STEPS_MAX
Enumeration Type Documentation
meshAdvIfPduSendEvent
enum meshAdvIfPduSendEvent
Advertising interface PDU send callback event.
Enumerator
MESH_CORE_ADV_PDU_SEND_EVENT
ADV PDU send
meshBeaconStatesValues
enum meshBeaconStatesValues
Mesh Secure Network Beacon States values enumeration.
Enumerator
MESH_BEACON_NOT_BROADCASTING
The node is not broadcasting a Beacon
MESH_BEACON_BROADCASTING
The node is broadcasting a Beacon
MESH_BEACON_PROHIBITED_START
Start of the Prohibited values.
meshEvents
enum meshEvents
Mesh events.
Enumerator
MESH_CORE_EVENT
Mesh Core event
MESH_CFG_MDL_CL_EVENT
Mesh Configuration Client event
MESH_CFG_MDL_SR_EVENT
Mesh Configuration Server event
MESH_LPN_EVENT
Mesh LPN event
MESH_PRV_CL_EVENT
Mesh Provisioning Client event
MESH_PRV_SR_EVENT
Mesh Provisioning Server event
MESH_TEST_EVENT
Mesh Test event
meshEventValues
enum meshEventValues
Mesh callback events.
Enumerator
MESH_CORE_RESET_EVENT
Mesh reset event
MESH_CORE_ERROR_EVENT
Mesh internal error event
MESH_CORE_SEND_MSG_EVENT
Mesh send message event
MESH_CORE_PUBLISH_MSG_EVENT
Mesh publish message event
MESH_CORE_GATT_CONN_ADD_EVENT
Mesh add GATT proxy connection event
MESH_CORE_GATT_CONN_REMOVE_EVENT
Mesh remove GATT proxy connection event
MESH_CORE_GATT_CONN_CLOSE_EVENT
Mesh GATT proxy connection closed event
MESH_CORE_GATT_PROCESS_PROXY_PDU_EVENT
Mesh process GATT proxy PDU event
MESH_CORE_GATT_SIGNAL_IF_RDY_EVENT
Mesh signal GATT interface ready for TX event
MESH_CORE_ADV_IF_ADD_EVENT
Mesh add ADV interface event
MESH_CORE_ADV_IF_REMOVE_EVENT
Mesh remove ADV interface event
MESH_CORE_ADV_IF_CLOSE_EVENT
Mesh ADV interface closed event
MESH_CORE_ADV_PROCESS_PDU_EVENT
Mesh process ADV PDU event
MESH_CORE_ADV_SIGNAL_IF_RDY_EVENT
Mesh signal ADV interface ready event
MESH_CORE_ATTENTION_SET_EVENT
Mesh element attention set event
MESH_CORE_ATTENTION_CHG_EVENT
Mesh element attention state changed event
MESH_CORE_NODE_STARTED_EVENT
Mesh Node started
MESH_CORE_PROXY_SERVICE_DATA_EVENT
Proxy Service Data for connectable advertising data event
MESH_CORE_PROXY_FILTER_STATUS_EVENT
Mesh Proxy Configuration Filter Status event
MESH_CORE_IV_UPDATED_EVENT
Mesh IV updated
MESH_CORE_HB_INFO_EVENT
Mesh Heartbeat information received
meshFeaturesBitMaskValues
enum meshFeaturesBitMaskValues
Stack supported features bit masks. If bit is set, the feature is supported.
Enumerator
MESH_FEAT_RELAY
Relay feature support bit
MESH_FEAT_PROXY
Proxy feature support bit
MESH_FEAT_FRIEND
Friend feature support bit
MESH_FEAT_LOW_POWER
Low power feature support bit
MESH_FEAT_RFU_START
Start of the RFU bitmask. Other bits RFU
meshFriendStatesValues
enum meshFriendStatesValues
Mesh Friend States values enumeration.
Enumerator
MESH_FRIEND_FEATURE_DISABLED
Friend feature is supported but disabled
MESH_FRIEND_FEATURE_ENABLED
Friend feature is supported and enabled
MESH_FRIEND_FEATURE_NOT_SUPPORTED
Friend feature is not supported
MESH_FRIEND_FEATURE_PROHIBITED_START
Start of the Prohibited values
MeshGattProxyPduSendEvent
enum MeshGattProxyPduSendEvent
GATT proxy PDU send callback event.
Enumerator
MESH_GATT_PROXY_PDU_SEND
GATT Proxy PDU send
meshGattProxyPduTypes
enum meshGattProxyPduTypes
GATT Proxy PDU type values enumeration.
Enumerator
MESH_GATT_PROXY_PDU_TYPE_NETWORK_PDU
Proxy PDU contains a Network PDU
MESH_GATT_PROXY_PDU_TYPE_BEACON
Proxy PDU contains a Mesh Beacon
MESH_GATT_PROXY_PDU_TYPE_CONFIGURATION
Proxy PDU contains a Proxy Configuration
MESH_GATT_PROXY_PDU_TYPE_PROVISIONING
Proxy PDU contains a Provisioning PDU
meshGattProxyStatesValues
enum meshGattProxyStatesValues
Mesh GATT Proxy states values enumeration.
Enumerator
MESH_GATT_PROXY_FEATURE_DISABLED
GATT Proxy feature is supported but disabled
MESH_GATT_PROXY_FEATURE_ENABLED
GATT Proxy feature is supported and enabled
MESH_GATT_PROXY_FEATURE_NOT_SUPPORTED
GATT Proxy feature is not supported
MESH_GATT_PROXY_FEATURE_PROHIBITED_START
Start of the Prohibited values
meshHtModelFaultValues
enum meshHtModelFaultValues
Enumeration of the Health model standard fault values.
Enumerator
MESH_HT_MODEL_FAULT_NO_FAULT
No Fault
MESH_HT_MODEL_FAULT_LOW_BATTERY_WARN
Battery Low Warning
MESH_HT_MODEL_FAULT_LOW_BATTERY_ERR
Battery Low Error
MESH_HT_MODEL_FAULT_SUPPLY_VOLTAGE_LOW_WARN
Supply Voltage Too Low Warning
MESH_HT_MODEL_FAULT_SUPPLY_VOLTAGE_LOW_ERR
Supply Voltage Too Low Error
MESH_HT_MODEL_FAULT_SUPPLY_VOLTAGE_HIGH_WARN
Supply Voltage Too High Warning
MESH_HT_MODEL_FAULT_SUPPLY_VOLTAGE_HIGH_ERR
Supply Voltage Too High Error
MESH_HT_MODEL_FAULT_POWER_SUPPLY_INTERRUPTED_WARN
Power Supply Interrupt Warning
MESH_HT_MODEL_FAULT_POWER_SUPPLY_INTERRUPTED_ERR
Power Supply Interrupt Error
MESH_HT_MODEL_FAULT_NO_LOAD_WARN
No Load Warning
MESH_HT_MODEL_FAULT_NO_LOAD_ERR
No Load Error
MESH_HT_MODEL_FAULT_OVERLOAD_WARN
Overload Warning
MESH_HT_MODEL_FAULT_OVERLOAD_ERR
Overload Error
MESH_HT_MODEL_FAULT_OVERHEAT_WARN
Overheat Warning
MESH_HT_MODEL_FAULT_OVERHEAT_ERR
Overheat Error
MESH_HT_MODEL_FAULT_CONDENSATION_WARN
Condensation Warning
MESH_HT_MODEL_FAULT_CONDENSATION_ERR
Condensation Error
MESH_HT_MODEL_FAULT_VIBRATION_WARN
Vibration Warning
MESH_HT_MODEL_FAULT_VIBRATION_ERR
Vibration Error
MESH_HT_MODEL_FAULT_CONFIGURATION_WARN
Configuration Warning
MESH_HT_MODEL_FAULT_CONFIGURATION_ERR
Configuration Error
MESH_HT_MODEL_FAULT_NO_CALIBRATION_WARN
Element Not Calibrated Warning
MESH_HT_MODEL_FAULT_NO_CALIBRATION_ERR
Element Not Calibrated Error
MESH_HT_MODEL_FAULT_MEMORY_WARN
Memory Warning
MESH_HT_MODEL_FAULT_MEMORY_ERR
Memory Error
MESH_HT_MODEL_FAULT_SELFTEST_WARN
Self-Test Warning
MESH_HT_MODEL_FAULT_SELFTEST_ERR
Self-Test Error
MESH_HT_MODEL_FAULT_INPUT_LOW_WARN
Input Too Low Warning
MESH_HT_MODEL_FAULT_INPUT_LOW_ERR
Input Too Low Error
MESH_HT_MODEL_FAULT_INPUT_HIGH_WARN
Input Too High Warning
MESH_HT_MODEL_FAULT_INPUT_HIGH_ERR
Input Too High Error
MESH_HT_MODEL_FAULT_INPUT_NO_CHANGE_WARN
Input No Change Warning
MESH_HT_MODEL_FAULT_INPUT_NO_CHANGE_ERR
Input No Change Error
MESH_HT_MODEL_FAULT_ACTUATOR_BLOCKED_WARN
Actuator Blocked Warning
MESH_HT_MODEL_FAULT_ACTUATOR_BLOCKED_ERR
Actuator Blocked Error
MESH_HT_MODEL_FAULT_HOUSING_OPENED_WARN
Housing Opened Warning
MESH_HT_MODEL_FAULT_HOUSING_OPENED_ERR
Housing Opened Error
MESH_HT_MODEL_FAULT_TAMPER_WARN
Tamper Warning
MESH_HT_MODEL_FAULT_TAMPER_ERR
Tamper Error
MESH_HT_MODEL_FAULT_DEVICE_MOVED_WARN
Device Moved Warning
MESH_HT_MODEL_FAULT_DEVICE_MOVED_ERR
Device Moved Error
MESH_HT_MODEL_FAULT_DEVICE_DROPPED_WARN
Device Dropped Warning
MESH_HT_MODEL_FAULT_DEVICE_DROPPED_ERR
Device Dropped Error
MESH_HT_MODEL_FAULT_OVERFLOW_WARN
Overflow Warning
MESH_HT_MODEL_FAULT_OVERFLOW_ERR
Overflow Error
MESH_HT_MODEL_FAULT_EMPTY_WARN
Empty Warning
MESH_HT_MODEL_FAULT_EMPTY_ERR
Empty Error
MESH_HT_MODEL_FAULT_INTERNAL_BUS_WARN
Internal Bus Warning
MESH_HT_MODEL_FAULT_INTERNAL_BUS_ERR
Internal Bus Error
MESH_HT_MODEL_FAULT_MECHANISM_JAMMED_WARN
Mechanism Jammed Warning
MESH_HT_MODEL_FAULT_MECHANISM_JAMMED_ERR
Mechanism Jammed Error
MESH_HT_MODEL_FAULT_VENDOR_BASE
First vendor specific warning or error
meshHtModelTestIdValues
enum meshHtModelTestIdValues
Enumeration of the Health model test identifiers.
Enumerator
MESH_HT_MODEL_TEST_ID_STANDARD
Standard test
MESH_HT_MODEL_TEST_ID_VENDOR_FIRST
First vendor-specific test identifier
MESH_HT_MODEL_TEST_ID_VENDOR_LAST
Last vendor-specific test identifier
meshKeyRefreshStatesValues
enum meshKeyRefreshStatesValues
Mesh Key Refresh Phase States values enumeration.
Enumerator
MESH_KEY_REFRESH_NOT_ACTIVE
Normal operation. Key Refresh procedure is not active
MESH_KEY_REFRESH_FIRST_PHASE
First phase of Key Refresh procedure
MESH_KEY_REFRESH_SECOND_PHASE
Second phase of Key Refresh procedure
MESH_KEY_REFRESH_THIRD_PHASE
Third phase of Key Refresh procedure
MESH_KEY_REFRESH_PROHIBITED_START
Start of the Prohibited values
meshKeyRefreshTransValues
enum meshKeyRefreshTransValues
Mesh Key Refresh transition values enumeration (Table 4.18)
Note
: Allowed values (old, transition, new): (0,3,0); (1,2,2); (1,3,0); (2,2,2); (2,3,0)
Enumerator
MESH_KEY_REFRESH_TRANS02
Transition 2
MESH_KEY_REFRESH_TRANS03
Transition 3
meshLowPowerStatesValues
enum meshLowPowerStatesValues
Mesh Low Power Node states values enumeration.
Enumerator
MESH_LOW_POWER_FEATURE_DISABLED
Low Power feature is supported
MESH_LOW_POWER_FEATURE_ENABLED
Low Power feature is not supported
MESH_LOW_POWER_FEATURE_PROHIBITED_START
Start of the Prohibited values
meshModelEventValues
enum meshModelEventValues
Mesh Model event type enumeration.
Enumerator
MESH_MODEL_EVT_MSG_RECV
Mesh Model message received event
MESH_MODEL_EVT_PERIODIC_PUB
Mesh Model periodic publish time expired event
meshNodeIdentityStatesValues
enum meshNodeIdentityStatesValues
Mesh Node Identity states values enumeration.
Enumerator
MESH_NODE_IDENTITY_STOPPED
Node Identity for a subnet is stopped
MESH_NODE_IDENTITY_RUNNING
Node Identity for a subnet is running
MESH_NODE_IDENTITY_NOT_SUPPORTED
Node Identity is not supported
MESH_NODE_IDENTITY_PROHIBITED_START
Start of the Prohibited values
meshProxyFilterType
enum meshProxyFilterType
Proxy interface filter list types enumeration.
Enumerator
MESH_PROXY_WHITE_LIST
Filter type is white list
MESH_PROXY_BLACK_LIST
Filter type is black list
meshProxyIdType
enum meshProxyIdType
Proxy identification types enumeration.
Enumerator
MESH_PROXY_NWK_ID_TYPE
Network ID type
MESH_PROXY_NODE_IDENTITY_TYPE
Node Identity type
meshPublishCredValues
enum meshPublishCredValues
Credentials used to publish messages from a model.
Enumerator
MESH_PUBLISH_MASTER_SECURITY
Master security material is used for publishing
MESH_PUBLISH_FRIEND_SECURITY
Friendship security material is used for publishing
meshPublishPeriodStepResValues
enum meshPublishPeriodStepResValues
Mesh Publish Period Step Resolution values enumeration.
Enumerator
MESH_PUBLISH_PERIOD_STEP_RES_100MS
Publish Period step resolution is 100 milliseconds
MESH_PUBLISH_PERIOD_STEP_RES_1S
Publish Period step resolution is 1 second
MESH_PUBLISH_PERIOD_STEP_RES_10S
Publish Period step resolution is 10 seconds
MESH_PUBLISH_PERIOD_STEP_RES_10MIN
Publish Period step resolution is 10 minutes
meshRelayStatesValues
enum meshRelayStatesValues
Mesh Relay States values enumeration.
Enumerator
MESH_RELAY_FEATURE_DISABLED
Relay feature is supported but disabled
MESH_RELAY_FEATURE_ENABLED
Relay feature is supported and enabled
MESH_RELAY_FEATURE_NOT_SUPPORTED
Relay feature is not supported
MESH_RELAY_FEATURE_PROHIBITED_START
Start of the Prohibited values
meshReturnValues
enum meshReturnValues
Mesh stack return value (status) enumeration.
Enumerator
MESH_MODULE_BASE_MASK
Mask that can be used to determine the module that triggered the error
MESH_RETURN_VALUE_MASK
Mask that can be used to determine the error code
MESH_RETVAL_BASE
General return value base
MESH_PRV_RETVAL_BASE
Mesh Provisioning return value base
MESH_BR_RETVAL_BASE
Mesh Bearer return value base
MESH_ADV_BR_RETVAL_BASE
Mesh Advertising bearer return value base
MESH_GATT_BR_RETVAL_BASE
Mesh GATT bearer return value base
MESH_NWK_RETVAL_BASE
Mesh Network return value base
MESH_NWK_CACHE_RETVAL_BASE
Mesh Network cache return value base
MESH_LTR_RETVAL_BASE
Mesh Lower Transport return value base
MESH_SAR_RX_RETVAL_BASE
Mesh SAR RX return value base
MESH_SAR_TX_RETVAL_BASE
Mesh SAR TX return value base
MESH_UTR_RETVAL_BASE
Mesh Upper Transport return value base
MESH_ACC_RETVAL_BASE
Mesh Access return value base
MESH_SEQ_RETVAL_BASE
Mesh Sequence Manager return value base
MESH_LOCAL_CFG_RETVAL_BASE
Mesh Local Configuration return value base
MESH_SEC_TOOL_RETVAL_BASE
Mesh Security Toolbox return value base
MESH_SEC_RETVAL_BASE
Mesh Security return value base
MESH_TMR_RETVAL_BASE
Mesh Timer return value base
MESH_SUCCESS
Operation completed without errors
MESH_FAILURE
A general failure. A more specific reason may be defined within event.
MESH_OUT_OF_MEMORY
Memory allocation failed
MESH_INVALID_PARAM
Invalid parameter(s) in request
MESH_INVALID_CONFIG
Invalid configuration (params could be valid)
MESH_NO_RESOURCES
No resources available to complete request
MESH_OS_ERROR
An OS error has occurred
MESH_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_ALREADY_INITIALIZED
Init function already called
MESH_UNINITIALIZED
Init function not called
MESH_INSUFFICIENT_MEMORY
Insufficient memory allocation
MESH_ALREADY_EXISTS
Duplicate entry found.
MESH_INVALID_INTERFACE
Invalid interface.
MESH_LAST_COMMON_RETVAL
Last member of the common return values
MESH_INIT_OS_ERROR
An OS error occurred during init
MESH_INIT_INVALID_CONFIG
At least one of the configuration parameters is invalid
MESH_INIT_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_RESET_FAILED
Factory reset procedure encountered an error
MESH_MSG_TX_NO_INTERFACE
No interface available to send a message
MESH_PRV_OUT_OF_MEMORY
Unable to allocate more memory
MESH_PRV_INVALID_PARAM
The function parameter has invalid value
MESH_PRV_INVALID_STATIC_KEY
Invalid static key received
MESH_PRV_UNSUPPORTED_CAPABILITIES
Requested provisioning capabilities are not supported by the stack
MESH_PRV_ADV_ERROR
Error occurred during advertising
MESH_BR_OUT_OF_MEMORY
Memory allocation failed
MESH_BR_INVALID_PARAMS
At least one of the parameters is invalid
MESH_BR_INVALID_CONFIG
Invalid configuration (params could be valid)
MESH_BR_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_BR_ALREADY_INITIALIZED
Bearer is already initialized
MESH_BR_INVALID_INTERFACE
An invalid bearer interface was used
MESH_ADV_OUT_OF_MEMORY
Unable to allocate more memory
MESH_ADV_INVALID_PARAMS
At least one of the parameters is invalid
MESH_ADV_INVALID_CONFIG
Invalid configuration (params could be valid)
MESH_ADV_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_ADV_ALREADY_INITIALIZED
Advertising bearer is already initialized
MESH_ADV_NO_RESOURCES
No more interfaces available
MESH_ADV_ALREADY_EXISTS
Interface already exists
MESH_ADV_INVALID_INTERFACE
An invalid advertising interface was used
MESH_ADV_QUEUE_FULL
No more entries available in the TX queue
MESH_ADV_QUEUE_EMPTY
TX queue is empty
MESH_GATT_OUT_OF_MEMORY
Unable to allocate more memory
MESH_GATT_INVALID_PARAMS
At least one of the parameters is invalid
MESH_GATT_INVALID_CONFIG
Invalid configuration (params could be valid)
MESH_GATT_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_GATT_ALREADY_INITIALIZED
Advertising bearer is already initialized
MESH_GATT_NO_RESOURCES
No more interfaces available
MESH_GATT_ALREADY_EXISTS
Interface already exists
MESH_GATT_INVALID_INTERFACE
An invalid advertising interface was used
MESH_NWK_OUT_OF_MEMORY
Unable to allocate more memory
MESH_NWK_INVALID_PARAMS
The function parameter has invalid value
MESH_NWK_UNKNOWN_ERROR
An error not covered by other codes occured
MESH_NWK_ALREADY_INITIALIZED
Network is already initialized
MESH_NWK_TRANSPORT_ERROR
Error occured during transport PDU send
MESH_NWK_INIT_ERROR
Error occurred during network initialization
MESH_NWK_INVALID_INTERFACE_ID
Interface ID does not exist
MESH_NWK_INVALID_DST
DST address is unassigned address
MESH_NWK_INVALID_SRC
SRC address is not a unicast address
MESH_NWK_INVALID_TTL
Invalid TTL value
MESH_NWK_UNKNOWN_NID
NID cannot be matched to any known network keys
MESH_NWK_CACHE_INVALID_PARAM
The function parameter has invalid value
MESH_NWK_CACHE_INSUFFICIENT_MEMORY
Insufficient memory was provided
MESH_NWK_CACHE_ALREADY_EXISTS
Network PDU already exists in the Network Cache
MESH_LTR_INVALID_PARAMS
At least one of the parameters is invalid
MESH_LTR_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_LTR_ALREADY_INITIALIZED
Lower Transport is already initialized
MESH_LTR_UNINITIALIZED
Lower Transport not initialized
MESH_SAR_RX_OUT_OF_MEMORY
No memory to process the request
MESH_SAR_RX_INVALID_PARAMS
Invalid parameters in the request
MESH_SAR_TX_OUT_OF_MEMORY
Buffer allocation failed
MESH_SAR_TX_INVALID_PARAMS
At least one of the parameters is invalid
MESH_SAR_TX_NO_TRANSACTION
No SAR Tx transaction could be found
MESH_UTR_INVALID_PARAMS
At least one of the parameters is invalid
MESH_UTR_OUT_OF_MEMORY
Buffer allocation failed
MESH_UTR_UNKNOWN_ERROR
An error not covered by other codes occurred
MESH_UTR_ALREADY_INITIALIZED
Upper Transport is already initialized
MESH_UTR_UNINITIALIZED
Upper Transport not initialized
MESH_ACC_OUT_OF_MEMORY
Memory allocation failed
MESH_ACC_INVALID_PARAMS
At least one of the parameters is invalid
MESH_ACC_UNKNOWN_ERROR
An error occurred but the reason is none of the above
MESH_SEQ_INVALID_PARAMS
At least one of the parameters is invalid
MESH_SEQ_UNKNOWN_ERROR
An error not covered by other codes occured
MESH_SEQ_ALREADY_INITIALIZED
Sequence Manager is already initialized
MESH_SEQ_INIT_ERROR
Sequence Manager API called prior to initialization
MESH_SEQ_INVALID_ADDRESS
The address passed as parameter is an invalid address
MESH_SEQ_EXHAUSTED
The sequence number has reached maximum value
MESH_LOCAL_CFG_OUT_OF_MEMORY
No resources to service requests
MESH_LOCAL_CFG_INVALID_PARAMS
At least one of the parameters is invalid
MESH_LOCAL_CFG_UNKNOWN_ERROR
An error occurred but the reason is none of the above
MESH_LOCAL_CFG_ALREADY_EXIST
Requested element already exists
MESH_LOCAL_CFG_INVALID_OPERATION
Invalid operation was executed
MESH_LOCAL_CFG_NOT_FOUND
Requested element not found
MESH_SEC_TOOL_OUT_OF_MEMORY
No resources to service requests
MESH_SEC_TOOL_INVALID_PARAMS
Invalid parameters in request
MESH_SEC_TOOL_UNKNOWN_ERROR
An error occured but the reason is none of the above
MESH_SEC_OUT_OF_MEMORY
No resources available for the operation. Either the cryptographic framework is busy or the module is out of memory
MESH_SEC_INVALID_PARAMS
Invalid parameters
MESH_SEC_KEY_NOT_FOUND
The requested key is not stored in the module
MESH_SEC_KEY_MATERIAL_NOT_FOUND
The key derivation material is not available for the given key index
MESH_SEC_KEY_MATERIAL_EXISTS
The key derivation material already exists for the specified key index
MESH_TMR_INVALID_PARAMS
At least one of the parameters is invalid
MESH_TMR_UNKNOWN_ERROR
An error not covered by other codes occured
MESH_TMR_ALREADY_INITIALIZED
Timer is already initialized
MESH_TMR_UNINITIALIZED
Timer not initialized
Function Documentation
MeshAddAdvIf()
void MeshAddAdvIf (meshAdvIfId_t advIfId)
Adds a new advertising interface into the bearer.
Parameters
[in] advIfId Unique identifier for the interface. Valid range is 0x00 to 0x1F.
Returns
None.
References meshCb_t::initialized.
MeshAddGattProxyConn()
void MeshAddGattProxyConn (meshGattProxyConnId_t connId, uint16_t maxProxyPdu)
Adds a new GATT Proxy connection into the bearer.
Parameters
[in] connId Unique identifier for the connection. Valid range 0x00 to 0x0F.
[in] maxProxyPdu Maximum size of the Proxy PDU, derived from GATT MTU.
Returns
None.
Remarks
If GATT Proxy is supported and this the first connection, it also enables proxy.
Parameters
[in] connId Unique identifier for the connection. Valid range 0x00 to 0x0F.
[in] maxProxyPdu Maximum size of the Proxy PDU, derived from ATT MTU.
Returns
None.
Remarks
If GATT Proxy is supported and this the first connection, it also enables proxy.
References meshCb_t::initialized.
MeshAttentionGet()
uint8_t MeshAttentionGet (meshElementId_t elemId)
Gets attention timer remaining time in seconds for an element.
Parameters
[in] elemId Element identifier.
Returns
Current Attention Timer time in seconds.
References MeshLocalCfgGetAttentionTimer(), WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshAttentionSet()
void MeshAttentionSet (meshElementId_t elemId, uint8_t attTimeSec)
Sets attention timer for an element.
Parameters
[in] elemId Element identifier.
[in] attTimeSec Attention timer time in seconds. Set to 0 to disable.
Returns
None.
References meshCb_t::initialized.
MeshFactoryReset()
void MeshFactoryReset (void)
Resets the node to unprovisioned device state.
Returns
None.
References meshCb_t::initialized.
MeshGattProxyInit()
void MeshGattProxyInit (void)
Initializes the GATT proxy functionality.
Returns
None.
References MeshBrEnableGatt().
MeshGetRequiredMemory()
uint32_t MeshGetRequiredMemory (void)
Computes the required memory to be provided based on the given configuration.
Returns
Memory required value in bytes if success or MESH_MEM_REQ_INVALID_CFG in case fail.
References MESH_MEM_REQ_INVALID_CFG, MeshAccGetRequiredMemory(), MeshLocalCfgGetRequiredMemory(), MeshSarRxGetRequiredMemory(), and MeshSecGetRequiredMemory().
MeshHandler()
void MeshHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for Mesh API.
Parameters
[in] event WSF event mask.
[in] pMsg WSF message.
Returns
None.
MeshHandlerInit()
void MeshHandlerInit (wsfHandlerId_t handlerId)
Initializes the Mesh WSF handler.
Parameters
[in] handlerId WSF handler ID for Network.
Returns
None
References meshCb_t::handlerId, and meshCb_t::initialized.
MeshInit()
uint32_t MeshInit (uint8_t * pFreeMem, uint32_t freeMemSize)
Initializes the Mesh Core Stack.
Parameters
[in] pFreeMem Pointer to free memory.
[in] freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
References meshCb_t::initialized.
MeshIsGattProxyEnabled()
bool_t MeshIsGattProxyEnabled (void)
Checks if GATT Proxy Feature is enabled.
Returns
TRUE if GATT Proxy Feature is enabled. FALSE otherwise.
MeshIsProvisioned()
bool_t MeshIsProvisioned (void)
Checks if a device is provisioned.
Returns
TRUE if device is provisioned. FALSE otherwise.
MeshLoadPrvData()
void MeshLoadPrvData (const meshPrvData_t * pPrvData)
Sets the provisioning and configuration data, either as a result of a completed Provisioning Procedure, or after reading the data from NVM if already provisioned.
Parameters
[in] pPrvData Pointer to a structure containing provisioning and configuration data.
Returns
None.
References meshCb_t::initialized.
MeshProcessAdvPdu()
void MeshProcessAdvPdu (meshAdvIfId_t advIfId, const uint8_t * pAdvPdu, uint8_t advPduLen)
Sends an Advertising PDU to the Mesh Stack for processing.
Parameters
[in] advIfId Unique identifier for the interface on which the PDU was received. Valid range is 0x00 to 0x1F.
[in] pAdvPdu Pointer to a buffer containing the Advertising PDU.
[in] advPduLen Size of the advertising PDU.
Returns
None.
References meshCb_t::initialized.
MeshProcessGattProxyPdu()
void MeshProcessGattProxyPdu (meshGattProxyConnId_t connId, const uint8_t * pProxyPdu, uint16_t proxyPduLen)
Sends a GATT Proxy PDU to the Mesh Stack for processing.
Parameters
[in] connId Unique identifier for the connection on which the PDU was received. Valid range is 0x00 to 0x1F.
[in] pProxyPdu Pointer to a buffer containing the GATT Proxy PDU.
[in] proxyPduLen Size of the buffer referenced by pProxyPdu.
Returns
None.
References meshCb_t::initialized.
MeshProxyClAddToFilter()
void MeshProxyClAddToFilter (meshGattProxyConnId_t connId, uint16_t netKeyIndex, meshAddress_t * pAddrArray, uint16_t listSize)
Sends an Add Addresses to Filter configuration message to a Proxy Server.
Parameters
[in] connId Unique identifier for the connection on which the PDU was received. Valid range is 0x00 to 0x1F.
[in] netKeyIndex Global Network Key identifier.
[in] pAddrArray Pointer to a buffer containing the addresses.
[in] listSize Address list size.
Returns
None.
References meshCb_t::initialized.
MeshProxyClInit()
void MeshProxyClInit (void)
Initializes the Proxy Client functionality.
Returns
None.
References MESH_GATT_PROXY_FEATURE_DISABLED, MESH_GATT_PROXY_FEATURE_NOT_SUPPORTED, MeshLocalCfgGetGattProxyState(), MeshLocalCfgSetGattProxyState(), and meshProxyClCb_t::msgHandlerCback.
MeshProxyClRemoveFromFilter()
void MeshProxyClRemoveFromFilter (meshGattProxyConnId_t connId, uint16_t netKeyIndex, meshAddress_t * pAddrArray, uint16_t listSize)
Sends a Remove Addresses from Filter configuration message to a Proxy Server.
Parameters
[in] connId Unique identifier for the connection on which the PDU was received. Valid range is 0x00 to 0x1F.
[in] netKeyIndex Global Network Key identifier.
[in] pAddrArray Pointer to a buffer containing the addresses.
[in] listSize Address list size.
Returns
None.
References meshCb_t::initialized.
MeshProxyClSetFilterType()
void MeshProxyClSetFilterType (meshGattProxyConnId_t connId, uint16_t netKeyIndex, meshProxyFilterType_t filterType)
Sends a Set Filter Type configuration message to a Proxy Server.
Parameters
[in] connId Unique identifier for the connection on which the PDU was received. Valid range is 0x00 to 0x1F.
[in] netKeyIndex Global Network Key identifier.
[in] filterType Proxy filter type. See meshProxyFilterType.
Returns
None.
References meshCb_t::initialized.
MeshProxySrGetNextServiceData()
void MeshProxySrGetNextServiceData (meshProxyIdType_t idType)
Requests the next available Proxy service data from the Mesh stack while cycling through the netkey indexes.This is used by the application to send connectable advertising packets.
Parameters
[in] idType Identification type.
Returns
None.
References MESH_SUCCESS, MeshLocalCfgGetNextNetKeyIndex(), WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshProxySrGetServiceData()
void MeshProxySrGetServiceData (uint16_t netKeyIndex, meshProxyIdType_t idType)
Requests the Proxy service data from the Mesh stack. This is used by the application to send connectable advertising packets.
Parameters
[in] netKeyIndex Network key index.
[in] idType Identification type.
Returns
None.
References WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshProxySrInit()
void MeshProxySrInit (void)
Initializes the Proxy Server functionality.
Returns
None.
References MESH_BR_INVALID_INTERFACE_ID.
MeshPublishMessage()
void MeshPublishMessage (meshPubMsgInfo_t * pPubMsgInfo, const uint8_t * pMsgParam, uint16_t msgParamLen)
Publishes a Mesh Message based on internal Model Publication State configuration.
Parameters
[in] pPubMsgInfo Pointer to a Mesh publish message information structure.
[in] pMsgParam Pointer to a Mesh message parameter list.
[in] msgParamLen Length of the message parameter list.
Returns
None.
References meshCb_t::initialized.
MeshRegister()
void MeshRegister (meshCback_t meshCback)
Registers the Mesh Core Stack events callback.
Parameters
[in] meshCback Callback function for Mesh Stack events.
Returns
None.
References meshCb_t::evtCback.
MeshRegisterAdvIfPduSendCback()
void MeshRegisterAdvIfPduSendCback (meshAdvPduSendCback_t cback)
Registers advertising interface callback for PDU's sent by the stack to the bearer.
Parameters
[in] cback Callback used by the Mesh Stack to send an advertising PDU.
Returns
None.
References MeshAdvRegisterPduSendCback(), WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshRegisterGattProxyPduSendCback()
void MeshRegisterGattProxyPduSendCback (meshGattProxyPduSendCback_t cback)
Registers GATT proxy callback for PDU's sent by the stack to the bearer.
Parameters
[in] cback Callback used by the Mesh Stack to send a GATT Proxy PDU.
Returns
None.
Remarks
If GATT Proxy is supported and this the first connection, it also enables proxy.
Parameters
[in] cback Callback used by the Mesh Stack to send a GATT Proxy PDU.
Returns
None.
References MeshGattRegisterPduSendCback(), WSF_CS_ENTER, WSF_CS_EXIT, and WSF_CS_INIT.
MeshRemoveAdvIf()
void MeshRemoveAdvIf (meshAdvIfId_t advIfId)
Removes an advertising interface from the bearer.
Parameters
[in] advIfId Unique identifier for the interface. Valid range is 0x00 to 0x1F.
Returns
None.
References meshCb_t::initialized.
MeshRemoveGattProxyConn()
void MeshRemoveGattProxyConn (meshGattProxyConnId_t connId)
Removes a GATT Proxy connection from the bearer.
Parameters
[in] connId Unique identifier for a connection. Valid range is 0x00 to 0x1F.
Returns
None.
Remarks
A connection removed event is received after calling this.
References meshCb_t::initialized.
MeshSecurityHandler()
void MeshSecurityHandler (wsfEventMask_t event, wsfMsgHdr_t * pMsg)
WSF event handler for Mesh Security.
Parameters
[in] event WSF event mask.
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event.
MeshSecurityHandlerInit()
void MeshSecurityHandlerInit (wsfHandlerId_t handlerId)
Initializes the Mesh Security WSF handler.
Parameters
[in] handlerId WSF handler ID for Network.
Returns
None.
Parameters
[in] handlerId WSF handler ID for Security.
Returns
None.
MeshSendMessage()
void MeshSendMessage (const meshMsgInfo_t * pMsgInfo, const uint8_t * pMsgParam, uint16_t msgParamLen, uint32_t rndDelayMsMin, uint32_t rndDelayMsMax)
Sends a Mesh message to a destination address.
Parameters
[in] pMsgInfo Pointer to a Mesh message information structure.
[in] pMsgParam Pointer to a Mesh message parameter list.
[in] msgParamLen Length of the message parameter list.
[in] rndDelayMsMin Minimum value for random send delay in ms. 0 for instant send
[in] rndDelayMsMax Maximum value for random send delay in ms. 0 for instant send.
Returns
None.
Parameters
[in] pMsgInfo Pointer to a Mesh message information structure.
[in] pMsgParam Pointer to a Mesh message parameter list.
[in] msgParamLen Length of the message parameter list.
[in] rndDelayMsMin Minimum value for random send delay in ms. 0 for instant send.
[in] rndDelayMsMax Maximum value for random send delay in ms. 0 for instant send.
Returns
None.
References meshCb_t::initialized.
MeshSignalAdvIfRdy()
void MeshSignalAdvIfRdy (meshAdvIfId_t advIfId)
Signals the Mesh Stack that the advertising interface is ready to transmit packets.
Parameters
[in] advIfId Unique identifier for the connection.
Returns
None.
References meshCb_t::initialized.
MeshSignalGattProxyIfRdy()
void MeshSignalGattProxyIfRdy (meshGattProxyConnId_t connId)
Signals the Mesh Stack that the GATT Proxy interface is ready to transmit packets.
Parameters
[in] connId Unique identifier for the connection on which the PDU was received. Valid range is 0x00 to 0x1F.
Returns
None.
References meshCb_t::initialized.
MeshSizeOfEvt()
uint16_t MeshSizeOfEvt (meshEvt_t * pMeshEvt)
Return size of a Mesh callback event.
Parameters
[in] pMeshEvt Mesh callback event.
Returns
Size of Mesh callback event.
Parameters
[in] pDmEvt Mesh callback event.
Returns
Size of Mesh callback event.
References wsfMsgHdr_t::event, meshEvt_t::hdr, MESH_CORE_EVENT, MESH_CORE_MAX_EVENT, and wsfMsgHdr_t::param.
MeshStartNode()
void MeshStartNode (void)
Starts a device as node. The device needs to be already provisioned.
Returns
None.
References meshCb_t::initialized.
Variable Documentation
pMeshConfig
meshConfig_t* pMeshConfig
Mesh configuration structure.
Mesh Configuration