Cordio: STACK_ATTC_API
STACK_ATTC_API
Data Structures
struct attcDiscChar_t
struct attcDiscCfg_t
struct attcDiscCb_t
ATT Client Discovery and Configuration Settings
Settings used to configurate ATT Discovery procedure for ATT Clients.
#define ATTC_SET_UUID_128 0x01
#define ATTC_SET_REQUIRED 0x02
#define ATTC_SET_DESCRIPTOR 0x04
ATT Client Functions
void AttcInit (void)
void AttcSignInit (void)
void AttcFindInfoReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, bool_t continuing)
void AttcFindByTypeValueReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, uint16_t uuid16, uint16_t valueLen, uint8_t *pValue, bool_t continuing)
void AttcReadByTypeReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t *pUuid, bool_t continuing)
void AttcReadReq (dmConnId_t connId, uint16_t handle)
void AttcReadLongReq (dmConnId_t connId, uint16_t handle, uint16_t offset, bool_t continuing)
void AttcReadMultipleReq (dmConnId_t connId, uint8_t numHandles, uint16_t *pHandles)
void AttcReadByGroupTypeReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t *pUuid, bool_t continuing)
void AttcWriteReq (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void AttcWriteCmd (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void AttcSignedWriteCmd (dmConnId_t connId, uint16_t handle, uint32_t signCounter, uint16_t valueLen, uint8_t *pValue)
void AttcPrepareWriteReq (dmConnId_t connId, uint16_t handle, uint16_t offset, uint16_t valueLen, uint8_t *pValue, bool_t valueByRef, bool_t continuing)
void AttcExecuteWriteReq (dmConnId_t connId, bool_t writeAll)
void AttcCancelReq (dmConnId_t connId)
void AttcDiscService (dmConnId_t connId, attcDiscCb_t *pCb, uint8_t uuidLen, uint8_t *pUuid)
uint8_t AttcDiscServiceCmpl (attcDiscCb_t *pCb, attEvt_t *pMsg)
void AttcDiscCharStart (dmConnId_t connId, attcDiscCb_t *pCb)
uint8_t AttcDiscCharCmpl (attcDiscCb_t *pCb, attEvt_t *pMsg)
void AttcDiscIncSvcStart (dmConnId_t connId, attcDiscCb_t *pCb)
uint8_t AttcDiscIncSvcCmpl (attcDiscCb_t *pCb, attEvt_t *pMsg)
uint8_t AttcDiscConfigStart (dmConnId_t connId, attcDiscCb_t *pCb)
uint8_t AttcDiscConfigCmpl (dmConnId_t connId, attcDiscCb_t *pCb)
uint8_t AttcDiscConfigResume (dmConnId_t connId, attcDiscCb_t *pCb)
void AttcMtuReq (dmConnId_t connId, uint16_t mtu)
void AttcSetAutoConfirm (bool_t enable)
void AttcIndConfirm (dmConnId_t connId)
EATT Client Functions
void EattcFindInfoReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, bool_t continuing)
void EattcFindByTypeValueReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, uint16_t uuid16, uint16_t valueLen, uint8_t *pValue, bool_t continuing)
void EattcReadByTypeReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t *pUuid, bool_t continuing)
void EattcReadReq (dmConnId_t connId, uint8_t priority, uint16_t handle)
void EattcReadLongReq (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t offset, bool_t continuing)
void EattcReadMultipleReq (dmConnId_t connId, uint8_t priority, uint8_t numHandles, uint16_t *pHandles)
void EattcReadByGroupTypeReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t *pUuid, bool_t continuing)
void EattcWriteReq (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void EattcCancelReq (dmConnId_t connId, uint8_t priority)
void EattcIndConfirm (dmConnId_t connId, uint16_t cid)
void EattcWriteCmd (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t *pValue)
void EattcPrepareWriteReq (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t offset, uint16_t valueLen, uint8_t *pValue, bool_t valueByRef, bool_t continuing)
void EattcExecuteWriteReq (dmConnId_t connId, uint8_t priority, bool_t writeAll)
void EattcReadMultVarLenReq (dmConnId_t connId, uint8_t priority, uint8_t numHandles, uint16_t *pHandles)
void EattcInit ()
Detailed Description
Data Structure Documentation
attcDiscChar_t
struct attcDiscChar_t
ATT client structure for characteristic and descriptor discovery.
Data Fields
uint8_t const * pUuid
uint8_t settings
attcDiscCfg_t
struct attcDiscCfg_t
ATT client structure for characteristic and descriptor configuration.
Data Fields
uint8_t const * pValue
uint8_t valueLen
uint8_t hdlIdx
attcDiscCb_t
struct attcDiscCb_t
ATT client discovery control block.
Data Fields
attcDiscChar_t ** pCharList
uint16_t * pHdlList
attcDiscCfg_t * pCfgList
uint8_t charListLen
uint8_t cfgListLen
uint16_t svcStartHdl
uint16_t svcEndHdl
uint8_t charListIdx
uint8_t endHdlIdx
Function Documentation
AttcCancelReq()
void AttcCancelReq (dmConnId_t connId)
Cancel an attribute protocol request in progress.
Parameters
connId DM connection ID.
Returns
None.
AttcDiscCharCmpl()
uint8_t AttcDiscCharCmpl (attcDiscCb_t * pCb, attEvt_t * pMsg)
This utility function processes a characteristic discovery result. It should be called when an ATTC_READ_BY_TYPE_RSP or ATTC_FIND_INFO_RSP callback event is received after characteristic discovery is initiated by calling AttcDiscCharStart().
Parameters
pCb Pointer to discovery control block.
pMsg ATT callback event message.
Returns
ATT_CONTINUING if successful and the discovery procedure is continuing. ATT_SUCCESS if the discovery procedure completed successfully. Otherwise the discovery procedure failed.
This utility function processes a characteristic discovery result. It should be called when an ATTC_READ_BY_TYPE_RSP or ATTC_FIND_INFO_RSP callback event is received after characteristic discovery is initiated by calling AttcDiscCharStart().
Parameters
pCb Pointer to service discovery control block.
pMsg ATT callback event message.
Returns
ATT_CONTINUING if successful and discovery procedure is continuing. ATT_SUCCESS if discovery procedure completed successfully. Otherwise the discovery procedure failed.
References ATT_CONTINUING, ATT_ERR_UNDEFINED, ATT_SUCCESS, ATTC_FIND_INFO_RSP, ATTC_READ_BY_TYPE_RSP, attcDiscCb_t::charListLen, wsfMsgHdr_t::event, attEvt_t::hdr, and attcDiscCb_t::pHdlList.
AttcDiscCharStart()
void AttcDiscCharStart (dmConnId_t connId, attcDiscCb_t * pCb)
This utility function starts characteristic and characteristic descriptor discovery for a service on a peer device. The service must have been previously discovered by calling AttcDiscService() and AttcDiscServiceCmpl().
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
Returns
None.
Parameters
connId DM connection ID.
pCb Pointer to service discovery control block.
Returns
None.
References ATT_16_UUID_LEN, attChUuid, AttcReadByTypeReq(), attcDiscCb_t::charListIdx, attcDiscCb_t::endHdlIdx, attcDiscCb_t::svcEndHdl, and attcDiscCb_t::svcStartHdl.
AttcDiscConfigCmpl()
uint8_t AttcDiscConfigCmpl (dmConnId_t connId, attcDiscCb_t * pCb)
This utility function initiates the next characteristic configuration procedure. It should be called when an ATTC_READ_RSP or ATTC_WRITE_RSP callback event is received after characteristic configuration is initiated by calling AttcDiscConfigStart().
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
Returns
ATT_CONTINUING if successful and configuration procedure is continuing. ATT_SUCCESS if configuration procedure completed successfully.
This utility function initiates the next characteristic configuration procedure. It should be called when an ATTC_READ_RSP or ATTC_WRITE_RSP callback event is received after characteristic configuration is initiated by calling AttcDiscConfigStart().
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
Returns
ATT_CONTINUING if successful and configuration procedure is continuing. ATT_SUCCESS if configuration procedure completed successfully.
References attcDiscCb_t::charListIdx.
AttcDiscConfigResume()
uint8_t AttcDiscConfigResume (dmConnId_t connId, attcDiscCb_t * pCb)
This utility function resumes the characteristic configuration procedure. It can be called when an ATTC_READ_RSP or ATTC_WRITE_RSP callback event is received with failure status to attempt the read or write procedure again.
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
Returns
ATT_CONTINUING if successful and configuration procedure is continuing. ATT_SUCCESS if configuration procedure completed successfully.
This utility function resumes the characteristic configuration procedure. It can be called when an ATTC_READ_RSP or ATTC_WRITE_RSP callback event is received with failure status to attempt the read or write procedure again.
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
Returns
ATT_CONTINUING if successful and configuration procedure is continuing. ATT_SUCCESS if configuration procedure completed successfully.
AttcDiscConfigStart()
uint8_t AttcDiscConfigStart (dmConnId_t connId, attcDiscCb_t * pCb)
This utility function starts characteristic configuration for characteristics on a peer device. The characteristics must have been previously discovered by calling AttcDiscCharStart() and AttcDiscCharCmpl().
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
Returns
ATT_CONTINUING if successful and configuration procedure is continuing. ATT_SUCCESS if nothing to configure.
This utility function starts characteristic configuration for characteristics on a peer device. The characteristics must have been previously discovered by calling AttcDiscCharStart() and AttcDiscCharCmpl().
Parameters
connId DM connection ID.
pCb Pointer to service discovery control block.
Returns
ATT_CONTINUING if successful and configuration procedure is continuing. ATT_SUCCESS if nothing to configure.
References attcDiscCb_t::charListIdx.
AttcDiscIncSvcCmpl()
uint8_t AttcDiscIncSvcCmpl (attcDiscCb_t * pCb, attEvt_t * pMsg)
This utility function processes a service include discovery result. It should be called when an ATTC_READ_BY_TYPE_RSP allback event is received after service include discovery is initiated by calling AttcDiscIncSvcStart().
Parameters
pCb Pointer to service discovery control block.
pMsg ATT callback event message.
Returns
ATT_CONTINUING if successful and discovery procedure is continuing. ATT_SUCCESS if discovery procedure completed successfully. Otherwise the discovery procedure failed.
References ATT_ERR_INVALID_RSP, ATT_ERR_UNDEFINED, ATT_SUCCESS, ATTC_READ_BY_TYPE_RSP, ATTC_SET_UUID_128, BSTREAM_TO_UINT8, attEvt_t::continuing, wsfMsgHdr_t::event, attEvt_t::hdr, attEvt_t::pValue, wsfMsgHdr_t::status, and attEvt_t::valueLen.
AttcDiscIncSvcStart()
void AttcDiscIncSvcStart (dmConnId_t connId, attcDiscCb_t * pCb)
This utility function starts service include discovery for a service on a peer device. The service must have been previously discovered by calling AttcDiscService() and AttcDiscServiceCmpl().
Parameters
connId DM connection ID.
pCb Pointer to service discovery control block.
Returns
None.
This utility function starts service include discovery for a service on a peer device. The service must have been previously discovered by calling AttcDiscService() and AttcDiscServiceCmpl().
Parameters
connId DM connection ID.
pCb Pointer to service discovery control block.
Returns
None.
References ATT_16_UUID_LEN, AttcReadByTypeReq(), attIncUuid, attcDiscCb_t::charListIdx, attcDiscCb_t::endHdlIdx, attcDiscCb_t::svcEndHdl, and attcDiscCb_t::svcStartHdl.
AttcDiscService()
void AttcDiscService (dmConnId_t connId, attcDiscCb_t * pCb, uint8_t uuidLen, uint8_t * pUuid)
This utility function discovers the given service on a peer device. Function AttcFindByTypeValueReq() is called to initiate the discovery procedure.
Parameters
connId DM connection ID.
pCb Pointer to discovery control block.
uuidLen Length of service UUID (2 or 16).
pUuid Pointer to service UUID.
Returns
None.
Parameters
connId DM connection ID.
pCb Pointer to service discovery control block.
uuidLen Length of UUID (2 or 16).
pUuid Pointer to UUID data.
Returns
None.
References ATT_HANDLE_MAX, ATT_HANDLE_START, ATT_UUID_PRIMARY_SERVICE, and AttcFindByTypeValueReq().
AttcDiscServiceCmpl()
uint8_t AttcDiscServiceCmpl (attcDiscCb_t * pCb, attEvt_t * pMsg)
This utility function processes a service discovery result. It should be called when an ATTC_FIND_BY_TYPE_VALUE_RSP callback event is received after service discovery is initiated by calling AttcDiscService().
Parameters
pCb Pointer to discovery control block.
pMsg ATT callback event message.
Returns
ATT_SUCCESS if successful otherwise error.
This utility function processes a service discovery result. It should be called when an ATTC_FIND_BY_TYPE_VALUE_RSP callback event is received after service discovery is initiated by calling AttcDiscService().
Parameters
pCb Pointer to service discovery control block.
pMsg ATT callback event message.
Returns
ATT_SUCCESS if successful otherwise error.
References ATT_ERR_NOT_FOUND, ATT_ERR_UNDEFINED, ATT_SUCCESS, ATTC_FIND_BY_TYPE_VALUE_RSP, BSTREAM_TO_UINT16, wsfMsgHdr_t::event, attEvt_t::hdr, attEvt_t::pValue, wsfMsgHdr_t::status, attcDiscCb_t::svcEndHdl, attcDiscCb_t::svcStartHdl, and attEvt_t::valueLen.
AttcExecuteWriteReq()
void AttcExecuteWriteReq (dmConnId_t connId, bool_t writeAll)
Initiate an attribute protocol Execute Write Request.
Parameters
connId DM connection ID.
writeAll TRUE to write all queued writes, FALSE to cancel all queued writes.
Returns
None.
AttcFindByTypeValueReq()
void AttcFindByTypeValueReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, uint16_t uuid16, uint16_t valueLen, uint8_t * pValue, bool_t continuing)
Initiate an attribute protocol Find By Type Value Request.
Parameters
connId DM connection ID.
startHandle Attribute start handle.
endHandle Attribute end handle.
uuid16 16-bit UUID to find.
valueLen Length of value data.
pValue Pointer to value data.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
AttcFindInfoReq()
void AttcFindInfoReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, bool_t continuing)
Initiate an attribute protocol Find Information Request.
Parameters
connId DM connection ID.
startHandle Attribute start handle.
endHandle Attribute end handle.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
AttcIndConfirm()
void AttcIndConfirm (dmConnId_t connId)
Send an attribute protocol indication confirmation.
Parameters
connId DM connection ID.
Returns
None.
References ATT_PDU_VALUE_CNF, ATT_VALUE_CNF_LEN, L2C_CID_ATT, L2C_PAYLOAD_START, and L2cDataReq().
AttcInit()
void AttcInit (void)
Initialize ATT client.
Returns
None.
AttcMtuReq()
void AttcMtuReq (dmConnId_t connId, uint16_t mtu)
Initiate an attribute protocol Exchange MTU Request.
Parameters
connId DM connection ID.
mtu Attribute protocol MTU.
Returns
None.
Note
The Exchange MTU Request will be initiated automatically on a master connection.
This API can be used by the application to initiate an Exchange MTU Request on slave connections.
References ATT_MTU_REQ_LEN, ATT_PDU_MTU_REQ, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
AttcPrepareWriteReq()
void AttcPrepareWriteReq (dmConnId_t connId, uint16_t handle, uint16_t offset, uint16_t valueLen, uint8_t * pValue, bool_t valueByRef, bool_t continuing)
Initiate an attribute protocol Prepare Write Request.
Parameters
connId DM connection ID.
handle Attribute handle.
offset Write attribute data starting at this offset.
valueLen Length of value data.
pValue Pointer to value data.
valueByRef TRUE if pValue data is accessed by reference rather than copied.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
AttcReadByGroupTypeReq()
void AttcReadByGroupTypeReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t * pUuid, bool_t continuing)
Initiate an attribute protocol Read By Group Type Request.
Parameters
connId DM connection ID.
startHandle Attribute start handle.
endHandle Attribute end handle.
uuidLen Length of UUID (2 or 16).
pUuid Pointer to UUID data.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
AttcReadByTypeReq()
void AttcReadByTypeReq (dmConnId_t connId, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t * pUuid, bool_t continuing)
Initiate an attribute protocol Read By Type Request.
Parameters
connId DM connection ID.
startHandle Attribute start handle.
endHandle Attribute end handle.
uuidLen Length of UUID (2 or 16).
pUuid Pointer to UUID data.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
AttcReadLongReq()
void AttcReadLongReq (dmConnId_t connId, uint16_t handle, uint16_t offset, bool_t continuing)
Initiate an attribute protocol Read Long Request.
Parameters
connId DM connection ID.
handle Attribute handle.
offset Read attribute data starting at this offset.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
Initiate an attribute protocol Read Long Request.
Parameters
connId DM connection ID.
handle Attribute handle.
offset Read attribute data starting at this offset.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
AttcReadMultipleReq()
void AttcReadMultipleReq (dmConnId_t connId, uint8_t numHandles, uint16_t * pHandles)
Initiate an attribute protocol Read Multiple Request.
Parameters
connId DM connection ID.
numHandles Number of handles in attribute handle list.
pHandles List of attribute handles.
Returns
None.
References ATT_PDU_READ_MULT_REQ, ATT_READ_MULT_REQ_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
AttcReadReq()
void AttcReadReq (dmConnId_t connId, uint16_t handle)
Initiate an attribute protocol Read Request.
Parameters
connId DM connection ID.
handle Attribute handle.
Returns
None.
References ATT_PDU_READ_REQ, ATT_READ_REQ_LEN, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
AttcSetAutoConfirm()
void AttcSetAutoConfirm (bool_t enable)
Set automatic Indication Confirmations sent from this ATT Client.
Parameters
enable TRUE to enable automatic confirmations (default), FALSE to disable.
Returns
None.
AttcSignedWriteCmd()
void AttcSignedWriteCmd (dmConnId_t connId, uint16_t handle, uint32_t signCounter, uint16_t valueLen, uint8_t * pValue)
Initiate an attribute protocol signed Write Command.
Parameters
connId DM connection ID.
handle Attribute handle.
signCounter Value of the sign counter.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_SIGNED_WRITE_CMD, ATT_SIGNED_WRITE_CMD_LEN, AttcWriteCmd(), DM_SEC_LEVEL_NONE, DmConnSecLevel(), L2C_PAYLOAD_START, UINT16_TO_BSTREAM, UINT32_TO_BSTREAM, and UINT8_TO_BSTREAM.
AttcSignInit()
void AttcSignInit (void)
Initialize ATT client for data signing.
Returns
None.
AttcWriteCmd()
void AttcWriteCmd (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Initiate an attribute protocol Write Command.
Parameters
connId DM connection ID.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_WRITE_CMD, ATT_WRITE_CMD_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
AttcWriteReq()
void AttcWriteReq (dmConnId_t connId, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Initiate an attribute protocol Write Request.
Parameters
connId DM connection ID.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_WRITE_REQ, ATT_WRITE_REQ_LEN, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
EattcCancelReq()
void EattcCancelReq (dmConnId_t connId, uint8_t priority)
Cancel an attribute protocol request in progress.
Parameters
connId DM connection ID.
priority Operation priority.
Returns
None.
EattcExecuteWriteReq()
void EattcExecuteWriteReq (dmConnId_t connId, uint8_t priority, bool_t writeAll)
Initiate an attribute protocol Execute Write Request.
Parameters
connId DM connection ID.
priority Operation priority.
writeAll TRUE to write all queued writes, FALSE to cancel all queued writes.
Returns
None.
EattcFindByTypeValueReq()
void EattcFindByTypeValueReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, uint16_t uuid16, uint16_t valueLen, uint8_t * pValue, bool_t continuing)
Initiate an attribute protocol Find By Type Value Request.
Parameters
connId DM connection ID.
priority Operation priority.
startHandle Attribute start handle.
endHandle Attribute end handle.
uuid16 16-bit UUID to find.
valueLen Length of value data.
pValue Pointer to value data.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
EattcFindInfoReq()
void EattcFindInfoReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, bool_t continuing)
Initiate an attribute protocol Find Information Request.
Parameters
connId DM connection ID.
priority Operation priority.
startHandle Attribute start handle.
endHandle Attribute end handle.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
EattcIndConfirm()
void EattcIndConfirm (dmConnId_t connId, uint16_t cid)
Send an attribute protocol indication confirmation.
Parameters
connId DM connection ID.
cid L2Cap channel ID.
Returns
None.
References ATT_PDU_VALUE_CNF, ATT_VALUE_CNF_LEN, and L2cCocDataReq().
EattcInit()
void EattcInit ()
Initialize the Enhanced ATT Client.
Returns
None
EattcPrepareWriteReq()
void EattcPrepareWriteReq (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t offset, uint16_t valueLen, uint8_t * pValue, bool_t valueByRef, bool_t continuing)
Initiate an attribute protocol Prepare Write Request.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
offset Write attribute data starting at this offset.
valueLen Length of value data.
pValue Pointer to value data.
valueByRef TRUE if pValue data is accessed by reference rather than copied.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
EattcReadByGroupTypeReq()
void EattcReadByGroupTypeReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t * pUuid, bool_t continuing)
Initiate an attribute protocol Read By Group Type Request.
Parameters
connId DM connection ID.
priority Operation priority.
startHandle Attribute start handle.
endHandle Attribute end handle.
uuidLen Length of UUID (2 or 16).
pUuid Pointer to UUID data.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
EattcReadByTypeReq()
void EattcReadByTypeReq (dmConnId_t connId, uint8_t priority, uint16_t startHandle, uint16_t endHandle, uint8_t uuidLen, uint8_t * pUuid, bool_t continuing)
Initiate an attribute protocol Read By Type Request.
Parameters
connId DM connection ID.
priority Operation priority.
startHandle Attribute start handle.
endHandle Attribute end handle.
uuidLen Length of UUID (2 or 16).
pUuid Pointer to UUID data.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
EattcReadLongReq()
void EattcReadLongReq (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t offset, bool_t continuing)
Initiate an attribute protocol Read Request.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
offset Read attribute data starting at this offset.
continuing TRUE if ATTC continues sending requests until complete.
Returns
None.
EattcReadMultipleReq()
void EattcReadMultipleReq (dmConnId_t connId, uint8_t priority, uint8_t numHandles, uint16_t * pHandles)
Initiate an attribute protocol Read Multiple Request.
Parameters
connId DM connection ID.
priority Operation priority.
numHandles Number of handles in attribute handle list.
pHandles List of attribute handles.
Returns
None.
References ATT_PDU_READ_MULT_REQ, ATT_READ_MULT_REQ_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
EattcReadMultVarLenReq()
void EattcReadMultVarLenReq (dmConnId_t connId, uint8_t priority, uint8_t numHandles, uint16_t * pHandles)
Initiate an attribute protocol Read Multiple Variable Length Request.
Parameters
connId DM connection ID.
priority Operation priority.
numHandles The number of handles in pHandles.
pHandles List of attribute handles to read.
Returns
None.
References ATT_PDU_READ_MULT_VAR_REQ, ATT_READ_MULT_VAR_REQ_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, and WSF_ASSERT.
EattcReadReq()
void EattcReadReq (dmConnId_t connId, uint8_t priority, uint16_t handle)
Initiate an attribute protocol Read Request.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
Returns
None.
References ATT_PDU_READ_REQ, ATT_READ_REQ_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
EattcWriteCmd()
void EattcWriteCmd (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Initiate an attribute protocol Write Command.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_WRITE_CMD, ATT_WRITE_CMD_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
EattcWriteReq()
void EattcWriteReq (dmConnId_t connId, uint8_t priority, uint16_t handle, uint16_t valueLen, uint8_t * pValue)
Initiate an attribute protocol Write Request.
Parameters
connId DM connection ID.
priority Operation priority.
handle Attribute handle.
valueLen Length of value data.
pValue Pointer to value data.
Returns
None.
References ATT_PDU_WRITE_REQ, ATT_WRITE_REQ_LEN, L2C_PAYLOAD_START, UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.