Cordio: WEIGHT_SCALE_PROFILE
WEIGHT_SCALE_PROFILE
Enumerations
enum
Functions
void WspcWssDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t WspcWssValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void WspsMeasComplete (dmConnId_t connId, uint8_t wsmCccIdx)
void WspsSetWsmFlags (uint8_t flags)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Weight Scale service enumeration of handle indexes of characteristics to be discovered.
Enumerator
WSPC_WSS_WSM_HDL_IDX
Weight scale measurement.
WSPC_WSS_WSM_CCC_HDL_IDX
Weight scale measurement CCC descriptor.
WSPC_WSS_WSF_HDL_IDX
Weight scale feature.
WSPC_WSS_HDL_LIST_LEN
Handle list length.
Function Documentation
WspcWssDiscover()
void WspcWssDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Weight Scale service. Parameter pHdlList must point to an array of length WSPC_WSS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Weight Scale service. Parameter pHdlList must point to an array of length WSPC_WSS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attWssSvcUuid, and WSPC_WSS_HDL_LIST_LEN.
WspcWssValueUpdate()
uint8_t WspcWssValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length WSPC_WSS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length WSPC_WSS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, attEvt_t::handle, attEvt_t::pValue, attEvt_t::valueLen, and WSPC_WSS_WSM_HDL_IDX.
WspsMeasComplete()
void WspsMeasComplete (dmConnId_t connId, uint8_t wsmCccIdx)
Weight scale measurement complete.
Parameters
connId DM connection identifier.
wsmCccIdx Index of weight scale measurement CCC descriptor in CCC descriptor handle table.
Returns
None.
Weight scale measurement complete.
Parameters
connId DM connection identifier.
wsmCccIdx Index of weight scale measurement CCC descriptor in CCC descriptor handle table.
Returns
None.
References AppHwWsmRead(), ATT_DEFAULT_PAYLOAD_LEN, AttsCccEnabled(), AttsHandleValueInd(), and WSS_WM_HDL.
WspsSetWsmFlags()
void WspsSetWsmFlags (uint8_t flags)
Set the weight scale measurement flags.
Parameters
flags Weight scale measurement flags.
Returns
None.
Parameters
flags Weight measurement flags.
Returns
None.