Cordio: Light CTL Server Model API
Light CTL Server Model API
Data Structures
union mmdlLightCtlStates_t
struct mmdlLightCtlSrStateUpdate_t
union mmdlLightCtlSrEvent_t
struct mmdlLightCtlSrStoredState_t
struct mmdlLightCtlTransStep_t
struct mmdlLightCtlSrDesc_t
struct mmdlLightCtlTempSrState_t
struct mmdlLightCtlTempSrStateUpdate_t
union mmdlLightCtlTempSrEvent_t
struct mmdlLightCtlTempStoredState_t
struct mmdlLightCtlTempSrTransStep_t
struct mmdlLightCtlTempSrDesc_t
struct mmdlLightHslHueSrStateUpdate_t
union mmdlLightHslHueSrEvent_t
struct mmdlLightHslHueStoredState_t
struct mmdlLightHslHueSrDesc_t
struct mmdlLightHslSatSrStateUpdate_t
union mmdlLightHslSatSrEvent_t
struct mmdlLightHslSatStoredState_t
struct mmdlLightHslSatSrDesc_t
union mmdlLightHslStates_t
struct mmdlLightHslSrStateUpdate_t
union mmdlLightHslSrEvent_t
struct mmdlLightHslSrStoredState_t
struct mmdlLightHslTransStep_t
struct mmdlLightHslSrDesc_t
Functions
void MmdlLightCtlSrInit (void)
void MmdlLightCtlSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightCtlSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightCtlSetupSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightCtlSrPublish (meshElementId_t elementId)
void MmdlLightCtlSrRegister (mmdlEventCback_t recvCback)
void MmdlLightCtlSrLinkElements (meshElementId_t mainElementId, meshElementId_t tempElementId)
void MmdlLightCtlSrBind2OnPowerUp (meshElementId_t onPowerUpElemId, meshElementId_t ctlElemId)
void MmdlLightCtlSrBind2LtLtnessAct (meshElementId_t ltElemId, meshElementId_t ctlElemId)
void MmdlLightCtlSrGetState (meshElementId_t elementId)
void MmdlLightCtlSrSetState (meshElementId_t elementId, mmdlLightCtlState_t *pTargetState)
void MmdlLightCtlTemperatureSrInit (void)
void MmdlLightCtlTemperatureSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightCtlTemperatureSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightCtlTemperatureSrPublish (meshElementId_t elementId)
void MmdlLightCtlTemperatureSrRegister (mmdlEventCback_t recvCback)
void MmdlLightCtlTemperatureSrBind2GenLevel (meshElementId_t temperatureElemId, meshElementId_t glvElemId)
void MmdlLightHslHueSrInit (void)
void MmdlLightHslHueSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightHslHueSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightHslHueSrPublish (meshElementId_t elementId)
void MmdlLightHslHueSrRegister (mmdlEventCback_t recvCback)
void MmdlLightHslHueSrBind2GenLevel (meshElementId_t hueElemId, meshElementId_t glvElemId)
void MmdlLightHslSatSrInit (void)
void MmdlLightHslSatSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightHslSatSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightHslSatSrPublish (meshElementId_t elementId)
void MmdlLightHslSatSrRegister (mmdlEventCback_t recvCback)
void MmdlLightHslSatSrBind2GenLevel (meshElementId_t satElemId, meshElementId_t glvElemId)
void MmdlLightHslSrInit (void)
void MmdlLightHslSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightHslSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightHslSetupSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightHslSrPublish (meshElementId_t elementId)
void MmdlLightHslSrPublishTarget (meshElementId_t elementId)
void MmdlLightHslSrRegister (mmdlEventCback_t recvCback)
void MmdlLightHslSrLinkElements (meshElementId_t mainElementId, meshElementId_t hueElementId, meshElementId_t satElementId)
void MmdlLightHslSrBind2OnPowerUp (meshElementId_t onPowerUpElemId, meshElementId_t hslElemId)
void MmdlLightHslSrBind2LtLtnessAct (meshElementId_t ltElemId, meshElementId_t hslElemId)
void MmdlLightHslSrGetState (meshElementId_t elementId)
void MmdlLightHslSrSetState (meshElementId_t elementId, mmdlLightHslState_t *pTargetState)
Variables
wsfHandlerId_t mmdlLightCtlSrHandlerId
wsfHandlerId_t mmdlLightCtlTemperatureSrHandlerId
const meshMsgOpcode_t mmdlLightCtlTemperatureSrRcvdOpcodes []
wsfHandlerId_t mmdlLightHslHueSrHandlerId
const meshMsgOpcode_t mmdlLightHslHueSrRcvdOpcodes []
wsfHandlerId_t mmdlLightHslSatSrHandlerId
const meshMsgOpcode_t mmdlLightHslSatSrRcvdOpcodes []
wsfHandlerId_t mmdlLightHslSrHandlerId
Supported opcodes
const meshMsgOpcode_t mmdlLightCtlSrRcvdOpcodes []
const meshMsgOpcode_t mmdlLightCtlSetupSrRcvdOpcodes []
Supported opcodes
const meshMsgOpcode_t mmdlLightHslSrRcvdOpcodes []
const meshMsgOpcode_t mmdlLightHslSetupSrRcvdOpcodes []
Detailed Description
Data Structure Documentation
mmdlLightCtlStates_t
union mmdlLightCtlStates_t
Union of CTL states.
Data Fields
mmdlLightCtlState_t state
mmdlLightCtlRangeState_t rangeState
Field Documentation
rangeState
mmdlLightCtlRangeState_t rangeState
Range state
state
mmdlLightCtlState_t state
State
mmdlLightCtlSrStateUpdate_t
struct mmdlLightCtlSrStateUpdate_t
Light CTL Server Model State Update event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
mmdlLightCtlStates_t ctlStates
Field Documentation
ctlStates
mmdlLightCtlStates_t ctlStates
Updated states
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
mmdlLightCtlSrEvent_t
union mmdlLightCtlSrEvent_t
Light CTL Server Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlLightCtlSrStateUpdate_t statusEvent
Field Documentation
hdr
wsfMsgHdr_t hdr
WSF message header
statusEvent
mmdlLightCtlSrStateUpdate_t statusEvent
State updated event. Used for MMDL_LIGHT_CTL_SR_STATE_UPDATE_EVENT.
mmdlLightCtlSrStoredState_t
struct mmdlLightCtlSrStoredState_t
Light CTL stored state definition.
Data Fields
mmdlLightCtlState_t present
mmdlLightCtlState_t target
mmdlLightCtlState_t ctlScenes [MMDL_NUM_OF_SCENES]
uint16_t minTemperature
uint16_t maxTemperature
uint16_t defaultTemperature
uint16_t defaultDeltaUV
Field Documentation
ctlScenes
mmdlLightCtlState_t ctlScenes[MMDL_NUM_OF_SCENES]
Temperature Scenes
defaultDeltaUV
uint16_t defaultDeltaUV
Default Delta UV value
defaultTemperature
uint16_t defaultTemperature
Default Temperature value
maxTemperature
uint16_t maxTemperature
Maximum Temperature value
minTemperature
uint16_t minTemperature
Minimum Temperature value
present
mmdlLightCtlState_t present
Present state
target
mmdlLightCtlState_t target
Target state
mmdlLightCtlTransStep_t
struct mmdlLightCtlTransStep_t
Light CTL transition step definition.
Data Fields
int16_t ltness
int16_t temperature
int16_t deltaUV
Field Documentation
deltaUV
int16_t deltaUV
Delta UV step value
ltness
int16_t ltness
Lightness step value
temperature
int16_t temperature
Temperature step value
mmdlLightCtlSrDesc_t
struct mmdlLightCtlSrDesc_t
Model Light CTL Server descriptor definition.
Data Fields
mmdlLightCtlSrStoredState_t * pStoredState
mmdlNvmSaveHandler_t fNvmSaveStates
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
mmdlLightCtlTransStep_t transitionStep
uint16_t steps
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
uint16_t ackAppKeyIndex
mmdlStateUpdateSrc_t updateSource
meshElementId_t mainElementId
meshElementId_t tempElementId
meshElementId_t deltaUVElementId
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the delayed message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
deltaUVElementId
meshElementId_t deltaUVElementId
Element Id of the DeltaUVuration element
fNvmSaveStates
mmdlNvmSaveHandler_t fNvmSaveStates
Pointer to function that saves Model instance states in NVM
mainElementId
meshElementId_t mainElementId
Element Id of the Main element
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages
pStoredState
mmdlLightCtlSrStoredState_t* pStoredState
Pointer to the structure that stores the Light CTL state and scenes
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
steps
uint16_t steps
The number of transition steps
tempElementId
meshElementId_t tempElementId
Element Id of the Temperature element
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionStep
mmdlLightCtlTransStep_t transitionStep
Transition state update step
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
updateSource
mmdlStateUpdateSrc_t updateSource
State update source. Cached for transitions.
mmdlLightCtlTempSrState_t
struct mmdlLightCtlTempSrState_t
Light CTL Temperature Server Model State structure.
Data Fields
uint16_t temperature
uint16_t deltaUV
Field Documentation
deltaUV
uint16_t deltaUV
Delta UV state
temperature
uint16_t temperature
Temperature state
mmdlLightCtlTempSrStateUpdate_t
struct mmdlLightCtlTempSrStateUpdate_t
Light CTL Temperature Server Model State Update event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
uint16_t temperature
uint16_t deltaUV
Field Documentation
deltaUV
uint16_t deltaUV
Updated state
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
temperature
uint16_t temperature
Updated state
mmdlLightCtlTempSrEvent_t
union mmdlLightCtlTempSrEvent_t
Light CTL Temperature Server Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlLightCtlTempSrStateUpdate_t statusEvent
Field Documentation
hdr
wsfMsgHdr_t hdr
WSF message header
statusEvent
mmdlLightCtlTempSrStateUpdate_t statusEvent
State updated event. Used for MMDL_LIGHT_CTL_TEMP_SR_STATE_UPDATE_EVENT.
mmdlLightCtlTempStoredState_t
struct mmdlLightCtlTempStoredState_t
Light CTL Temperature stored state definition.
Data Fields
mmdlLightCtlTempSrState_t present
mmdlLightCtlTempSrState_t target
Field Documentation
present
mmdlLightCtlTempSrState_t present
Present state
target
mmdlLightCtlTempSrState_t target
Target state
mmdlLightCtlTempSrTransStep_t
struct mmdlLightCtlTempSrTransStep_t
Light CTL Temperature transition step structure.
Data Fields
int16_t temperature
int16_t deltaUV
Field Documentation
deltaUV
int16_t deltaUV
Delta UV step value
temperature
int16_t temperature
Temperature step value
mmdlLightCtlTempSrDesc_t
struct mmdlLightCtlTempSrDesc_t
Model Light CTL Temperature Server descriptor definition.
Data Fields
mmdlLightCtlTempStoredState_t * pStoredState
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
mmdlLightCtlTempSrTransStep_t transitionStep
uint16_t steps
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
uint16_t ackAppKeyIndex
meshElementId_t mainElementId
mmdlStateUpdateSrc_t updateSource
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the delayed message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
mainElementId
meshElementId_t mainElementId
Element Id of the Main element that uses this Temperature instance.
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages
pStoredState
mmdlLightCtlTempStoredState_t* pStoredState
Pointer to the structure that stores the Light CTL state and scenes
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
steps
uint16_t steps
The number of transition steps
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionStep
mmdlLightCtlTempSrTransStep_t transitionStep
Transition state update step
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
updateSource
mmdlStateUpdateSrc_t updateSource
State update source. Cached for transitions.
mmdlLightHslHueSrStateUpdate_t
struct mmdlLightHslHueSrStateUpdate_t
Light HSL Hue Server Model State Update event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
uint16_t state
Field Documentation
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
state
uint16_t state
Updated state
mmdlLightHslHueSrEvent_t
union mmdlLightHslHueSrEvent_t
Light HSL Hue Server Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlLightHslHueSrStateUpdate_t statusEvent
Field Documentation
hdr
wsfMsgHdr_t hdr
WSF message header
statusEvent
mmdlLightHslHueSrStateUpdate_t statusEvent
State updated event. Used for MMDL_LIGHT_HSL_HUE_SR_STATE_UPDATE_EVENT.
mmdlLightHslHueStoredState_t
struct mmdlLightHslHueStoredState_t
Light HSL Hue stored state definition.
Data Fields
uint16_t presentHue
uint16_t targetHue
Field Documentation
presentHue
uint16_t presentHue
Present state
targetHue
uint16_t targetHue
Target state
mmdlLightHslHueSrDesc_t
struct mmdlLightHslHueSrDesc_t
Model Light HSL Hue Server descriptor definition.
Data Fields
mmdlLightHslHueStoredState_t * pStoredState
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
int16_t transitionStep
uint16_t steps
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
uint16_t ackAppKeyIndex
meshElementId_t mainElementId
mmdlStateUpdateSrc_t updateSource
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the delayed message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
mainElementId
meshElementId_t mainElementId
Element Id of the Main element that uses this Hue instance.
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages
pStoredState
mmdlLightHslHueStoredState_t* pStoredState
Pointer to the structure that stores the Light HSL state and scenes
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
steps
uint16_t steps
The number of transition steps
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionStep
int16_t transitionStep
Transition state update step
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
updateSource
mmdlStateUpdateSrc_t updateSource
State update source. Cached for transitions.
mmdlLightHslSatSrStateUpdate_t
struct mmdlLightHslSatSrStateUpdate_t
Light HSL Saturation Server Model State Update event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
uint16_t state
Field Documentation
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
state
uint16_t state
Updated state
mmdlLightHslSatSrEvent_t
union mmdlLightHslSatSrEvent_t
Light HSL Saturation Server Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlLightHslSatSrStateUpdate_t statusEvent
Field Documentation
hdr
wsfMsgHdr_t hdr
WSF message header
statusEvent
mmdlLightHslSatSrStateUpdate_t statusEvent
State updated event. Used for MMDL_LIGHT_HSL_SAT_SR_STATE_UPDATE_EVENT.
mmdlLightHslSatStoredState_t
struct mmdlLightHslSatStoredState_t
Light HSL Sat stored state definition.
Data Fields
uint16_t presentSat
uint16_t targetSat
Field Documentation
presentSat
uint16_t presentSat
Present state
targetSat
uint16_t targetSat
Target state
mmdlLightHslSatSrDesc_t
struct mmdlLightHslSatSrDesc_t
Model Light HSL Saturation Server descriptor definition.
Data Fields
mmdlLightHslSatStoredState_t * pStoredState
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
int16_t transitionStep
uint16_t steps
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
uint16_t ackAppKeyIndex
meshElementId_t mainElementId
mmdlStateUpdateSrc_t updateSource
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the delayed message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
mainElementId
meshElementId_t mainElementId
Element Id of the Main element that uses this Sat instance.
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages
pStoredState
mmdlLightHslSatStoredState_t* pStoredState
Pointer to the structure that stores the Light HSL state and scenes
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
steps
uint16_t steps
The number of transition steps
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionStep
int16_t transitionStep
Transition state update step
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
updateSource
mmdlStateUpdateSrc_t updateSource
State update source. Cached for transitions.
mmdlLightHslStates_t
union mmdlLightHslStates_t
Union of HSL states.
Data Fields
mmdlLightHslState_t state
mmdlLightHslRangeState_t rangeState
Field Documentation
rangeState
mmdlLightHslRangeState_t rangeState
Range state
state
mmdlLightHslState_t state
State
mmdlLightHslSrStateUpdate_t
struct mmdlLightHslSrStateUpdate_t
Light HSL Server Model State Update event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
mmdlLightHslStates_t hslStates
Field Documentation
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
hslStates
mmdlLightHslStates_t hslStates
Updated states
mmdlLightHslSrEvent_t
union mmdlLightHslSrEvent_t
Light HSL Server Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlLightHslSrStateUpdate_t statusEvent
Field Documentation
hdr
wsfMsgHdr_t hdr
WSF message header
statusEvent
mmdlLightHslSrStateUpdate_t statusEvent
State updated event. Used for MMDL_LIGHT_HSL_SR_STATE_UPDATE_EVENT.
mmdlLightHslSrStoredState_t
struct mmdlLightHslSrStoredState_t
Light HSL stored state definition.
Data Fields
mmdlLightHslState_t present
mmdlLightHslState_t target
mmdlLightHslState_t hslScenes [MMDL_NUM_OF_SCENES]
uint16_t defaultHue
uint16_t minHue
uint16_t maxHue
uint16_t defaultSat
uint16_t minSat
uint16_t maxSat
Field Documentation
defaultHue
uint16_t defaultHue
Default Hue value
defaultSat
uint16_t defaultSat
Default Saturation value
hslScenes
mmdlLightHslState_t hslScenes[MMDL_NUM_OF_SCENES]
Hue Scenes
maxHue
uint16_t maxHue
Maximum Hue value
maxSat
uint16_t maxSat
Maximum Saturation value
minHue
uint16_t minHue
Minimum Hue value
minSat
uint16_t minSat
Minimum Saturation value
present
mmdlLightHslState_t present
Present state
target
mmdlLightHslState_t target
Target state
mmdlLightHslTransStep_t
struct mmdlLightHslTransStep_t
Light HSL transition step definition.
Data Fields
int16_t ltness
int16_t hue
int16_t saturation
Field Documentation
hue
int16_t hue
Hue step value
ltness
int16_t ltness
Lightness step value
saturation
int16_t saturation
Saturation step value
mmdlLightHslSrDesc_t
struct mmdlLightHslSrDesc_t
Model Light HSL Server descriptor definition.
Data Fields
mmdlLightHslSrStoredState_t * pStoredState
mmdlNvmSaveHandler_t fNvmSaveStates
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
mmdlLightHslTransStep_t transitionStep
uint16_t steps
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
uint16_t ackAppKeyIndex
mmdlStateUpdateSrc_t updateSource
meshElementId_t hueElementId
meshElementId_t satElementId
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the delayed message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
fNvmSaveStates
mmdlNvmSaveHandler_t fNvmSaveStates
Pointer to function that saves Model instance states in NVM
hueElementId
meshElementId_t hueElementId
Element Id of the Hue element
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages
pStoredState
mmdlLightHslSrStoredState_t* pStoredState
Pointer to the structure that stores the Light HSL state and scenes
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
satElementId
meshElementId_t satElementId
Element Id of the Saturation element
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
steps
uint16_t steps
The number of transition steps
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionStep
mmdlLightHslTransStep_t transitionStep
Transition state update step
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
updateSource
mmdlStateUpdateSrc_t updateSource
State update source. Cached for transitions.
Function Documentation
MmdlLightCtlSetupSrHandler()
void MmdlLightCtlSetupSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light CTL Setup Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
WSF message handler for Light CTL Setup Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlLightCtlSrBind2LtLtnessAct()
void MmdlLightCtlSrBind2LtLtnessAct (meshElementId_t ltElemId, meshElementId_t ctlElemId)
Creates a bind between a Light Lightness Actual State and a Light CTL state. A bind between the Generic OnOff and Light CTL and Generic Level and Light CTL is created to support the lightness extension.
Parameters
[in] ltElemId Element identifier where the Light Lightness Actual state resides.
[in] ctlElemId Element identifier where the Light CTL state resides.
Returns
None.
MmdlLightCtlSrBind2OnPowerUp()
void MmdlLightCtlSrBind2OnPowerUp (meshElementId_t onPowerUpElemId, meshElementId_t ctlElemId)
Creates a bind between a Light CTL State and a Generic OnPowerUp state.
Parameters
[in] onPowerUpElemId Element identifier where the OnPowerUp state resides.
[in] ctlElemId Element identifier where the Light CTL state resides.
Returns
None.
MmdlLightCtlSrGetState()
void MmdlLightCtlSrGetState (meshElementId_t elementId)
Get the local Light CTL state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References mmdlLightCtlState_t::deltaUV, mmdlLightCtlState_t::ltness, MMDL_LIGHT_CTL_SR_EVENT, MMDL_LIGHT_CTL_SR_STATE_UPDATE_EVENT, mmdlLightCtlSrStoredState_t::present, mmdlLightCtlSrDesc_t::pStoredState, and mmdlLightCtlState_t::temperature.
MmdlLightCtlSrHandler()
void MmdlLightCtlSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light CTL Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlLightCtlSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlLightCtlSrHandlerInit()
void MmdlLightCtlSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light CTL Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light CTL Server Model.
Returns
None.
References mmdlLightCtlSrHandlerId.
MmdlLightCtlSrInit()
void MmdlLightCtlSrInit (void)
Initializes the Light CTL Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlLightCtlSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlLightCtlSrDesc_t::pStoredState, mmdlLightCtlSrDesc_t::srcAddr, and mmdlLightCtlSrDesc_t::transitionTimer.
MmdlLightCtlSrLinkElements()
void MmdlLightCtlSrLinkElements (meshElementId_t mainElementId, meshElementId_t tempElementId)
Links the Main Element to the DeltaUV and Temperature elements.
Parameters
[in] mainElementId Identifier of the Main element
[in] tempElementId Identifier of the Temperature element
Returns
None.
Links the Main Element to the DeltaUV and Temperature elements.
Parameters
[in] mainElementId Identifier of the Main element
[in] tempElementId Identifier of the Temperature element
Returns
None.
References meshConfig_t::elementArrayLen, and pMeshConfig.
MmdlLightCtlSrPublish()
void MmdlLightCtlSrPublish (meshElementId_t elementId)
Publish a Light CTL Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightCtlSrRegister()
void MmdlLightCtlSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightCtlSrSetState()
void MmdlLightCtlSrSetState (meshElementId_t elementId, mmdlLightCtlState_t * pTargetState)
Set the local Light CTL state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] pTargetState Target State for this transaction. See mmdlLightCtlState_t
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
MmdlLightCtlTemperatureSrBind2GenLevel()
void MmdlLightCtlTemperatureSrBind2GenLevel (meshElementId_t temperatureElemId, meshElementId_t glvElemId)
Creates a bind between a Light CTL Temperature State and a Generic Level state.
Parameters
[in] temperatureElemId Element identifier where the Light CTL Temperature state resides.
[in] glvElemId Element identifier where the Generic Level state resides.
Returns
None.
MmdlLightCtlTemperatureSrHandler()
void MmdlLightCtlTemperatureSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light CTL Temperature Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlLightCtlTemperatureSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlLightCtlTemperatureSrHandlerInit()
void MmdlLightCtlTemperatureSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light CTL Temperature Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light CTL Temperature Server Model.
Returns
None.
References mmdlLightCtlTemperatureSrHandlerId.
MmdlLightCtlTemperatureSrInit()
void MmdlLightCtlTemperatureSrInit (void)
Initializes the Light CTL Temperature Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlLightCtlTemperatureSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlLightCtlTempSrDesc_t::pStoredState, mmdlLightCtlTempSrDesc_t::srcAddr, and mmdlLightCtlTempSrDesc_t::transitionTimer.
MmdlLightCtlTemperatureSrPublish()
void MmdlLightCtlTemperatureSrPublish (meshElementId_t elementId)
Publish a Light CTL Temperature Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightCtlTemperatureSrRegister()
void MmdlLightCtlTemperatureSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightHslHueSrBind2GenLevel()
void MmdlLightHslHueSrBind2GenLevel (meshElementId_t hueElemId, meshElementId_t glvElemId)
Creates a bind between a Light HSL Hue State and a Generic Level state.
Parameters
[in] hueElemId Element identifier where the Light HSL Hue state resides.
[in] glvElemId Element identifier where the Generic Level state resides.
Returns
None.
References MMDL_STATE_UPDATED_BY_BIND, mmdlLightHslHueSrDesc_t::pStoredState, and mmdlLightHslHueStoredState_t::targetHue.
MmdlLightHslHueSrHandler()
void MmdlLightHslHueSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light HSL Hue Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlLightHslHueSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlLightHslHueSrHandlerInit()
void MmdlLightHslHueSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light HSL Hue Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light HSL Hue Server Model.
Returns
None.
References mmdlLightHslHueSrHandlerId.
MmdlLightHslHueSrInit()
void MmdlLightHslHueSrInit (void)
Initializes the Light HSL Hue Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlLightHslHueSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlLightHslHueSrDesc_t::pStoredState, mmdlLightHslHueSrDesc_t::srcAddr, and mmdlLightHslHueSrDesc_t::transitionTimer.
MmdlLightHslHueSrPublish()
void MmdlLightHslHueSrPublish (meshElementId_t elementId)
Publish a Light HSL Hue Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightHslHueSrRegister()
void MmdlLightHslHueSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightHslSatSrBind2GenLevel()
void MmdlLightHslSatSrBind2GenLevel (meshElementId_t satElemId, meshElementId_t glvElemId)
Creates a bind between a Light HSL Saturation State and a Generic Level state.
Parameters
[in] satElemId Element identifier where the Light HSL Saturation state resides.
[in] glvElemId Element identifier where the Generic Level state resides.
Returns
None.
References MMDL_STATE_UPDATED_BY_BIND, mmdlLightHslSatSrDesc_t::pStoredState, and mmdlLightHslSatStoredState_t::targetSat.
MmdlLightHslSatSrHandler()
void MmdlLightHslSatSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light HSL Saturation Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlLightHslSatSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlLightHslSatSrHandlerInit()
void MmdlLightHslSatSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light HSL Saturation Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light HSL Saturation Server Model.
Returns
None.
References mmdlLightHslSatSrHandlerId.
MmdlLightHslSatSrInit()
void MmdlLightHslSatSrInit (void)
Initializes the Light HSL Saturation Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlLightHslSatSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlLightHslSatSrDesc_t::pStoredState, mmdlLightHslSatSrDesc_t::srcAddr, and mmdlLightHslSatSrDesc_t::transitionTimer.
MmdlLightHslSatSrPublish()
void MmdlLightHslSatSrPublish (meshElementId_t elementId)
Publish a Light HSL Sat Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightHslSatSrRegister()
void MmdlLightHslSatSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
MmdlLightHslSetupSrHandler()
void MmdlLightHslSetupSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light HSL Setup Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
WSF message handler for Light HSL Setup Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlLightHslSrBind2LtLtnessAct()
void MmdlLightHslSrBind2LtLtnessAct (meshElementId_t ltElemId, meshElementId_t hslElemId)
Creates a bind between a Light Lightness Actual State and a Light HSL state. A bind between the Generic OnOff and Light HSL and Generic Level and Light HSL is created to support the lightness extension.
Parameters
[in] ltElemId Element identifier where the Light Lightness Actual state resides.
[in] hslElemId Element identifier where the Light HSL state resides.
Returns
None.
MmdlLightHslSrBind2OnPowerUp()
void MmdlLightHslSrBind2OnPowerUp (meshElementId_t onPowerUpElemId, meshElementId_t hslElemId)
Creates a bind between a Light HSL State and a Generic OnPowerUp state.
Parameters
[in] onPowerUpElemId Element identifier where the OnPowerUp state resides.
[in] hslElemId Element identifier where the Light HSL state resides.
Returns
None.
MmdlLightHslSrGetState()
void MmdlLightHslSrGetState (meshElementId_t elementId)
Get the local Light HSL state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References mmdlLightHslState_t::hue, mmdlLightHslState_t::ltness, MMDL_LIGHT_HSL_SR_EVENT, MMDL_LIGHT_HSL_SR_STATE_UPDATE_EVENT, mmdlLightHslSrStoredState_t::present, mmdlLightHslSrDesc_t::pStoredState, and mmdlLightHslState_t::saturation.
MmdlLightHslSrHandler()
void MmdlLightHslSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light HSL Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlLightHslSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlLightHslSrHandlerInit()
void MmdlLightHslSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light HSL Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light HSL Server Model.
Returns
None.
References mmdlLightHslSrHandlerId.
MmdlLightHslSrInit()
void MmdlLightHslSrInit (void)
Initializes the Light HSL Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlLightHslSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlLightHslSrDesc_t::pStoredState, mmdlLightHslSrDesc_t::srcAddr, and mmdlLightHslSrDesc_t::transitionTimer.
MmdlLightHslSrLinkElements()
void MmdlLightHslSrLinkElements (meshElementId_t mainElementId, meshElementId_t hueElementId, meshElementId_t satElementId)
Links the Main Element to the Sat and Hue elements.
Parameters
[in] mainElementId Identifier of the Main element
[in] hueElementId Identifier of the Hue element
[in] satElementId Identifier of the Sat element
Returns
None.
References meshConfig_t::elementArrayLen, mmdlLightHslState_t::ltness, pMeshConfig, mmdlLightHslSrStoredState_t::present, mmdlLightHslSrDesc_t::pStoredState, and WSF_ASSERT.
MmdlLightHslSrPublish()
void MmdlLightHslSrPublish (meshElementId_t elementId)
Publish a Light HSL Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightHslSrPublishTarget()
void MmdlLightHslSrPublishTarget (meshElementId_t elementId)
Publish a Light HSL Target Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightHslSrRegister()
void MmdlLightHslSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightHslSrSetState()
void MmdlLightHslSrSetState (meshElementId_t elementId, mmdlLightHslState_t * pTargetState)
Set the local Light HSL state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] pTargetState Target State for this transaction. See mmdlLightHslState_t
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
Variable Documentation
mmdlLightCtlSetupSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightCtlSetupSrRcvdOpcodes[]
Supported opcodes
mmdlLightCtlSrHandlerId
wsfHandlerId_t mmdlLightCtlSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightCtlSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightCtlSrRcvdOpcodes[]
Supported opcodes
mmdlLightCtlTemperatureSrHandlerId
wsfHandlerId_t mmdlLightCtlTemperatureSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightCtlTemperatureSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightCtlTemperatureSrRcvdOpcodes[]
Supported opcodes.
Supported opcodes
mmdlLightHslHueSrHandlerId
wsfHandlerId_t mmdlLightHslHueSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightHslHueSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightHslHueSrRcvdOpcodes[]
Supported opcodes.
Supported opcodes
mmdlLightHslSatSrHandlerId
wsfHandlerId_t mmdlLightHslSatSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightHslSatSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightHslSatSrRcvdOpcodes[]
Supported opcodes.
Supported opcodes
mmdlLightHslSetupSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightHslSetupSrRcvdOpcodes[]
Supported opcodes
mmdlLightHslSrHandlerId
wsfHandlerId_t mmdlLightHslSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightHslSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightHslSrRcvdOpcodes[]
Supported opcodes