Cordio: Generic Power Level Client Model API
Generic Power Level Client Model API
Data Structures
struct mmdlGenPowerLevelSetParam_t
struct mmdlGenPowerDefaultSetParam_t
struct mmdlGenPowerRangeSetParam_t
struct mmdlGenPowerLevelClStatusEvent_t
struct mmdlGenPowerLastClStatusEvent_t
struct mmdlGenPowerDefaultClStatusEvent_t
struct mmdlGenPowerRangeClStatusEvent_t
union mmdlGenPowerLevelClEvent_t
Functions
void MmdlGenPowerLevelClHandlerInit (wsfHandlerId_t handlerId)
void MmdlGenPowerLevelClHandler (wsfMsgHdr_t *pMsg)
void MmdlGenPowerLevelClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlGenPowerLevelClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlGenPowerLevelSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlGenPowerLevelClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlGenPowerLevelSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlGenPowerLastClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlGenPowerDefaultClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlGenPowerDefaultClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, mmdlGenPowerLevelState_t powerLevel)
void MmdlGenPowerDefaultClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, mmdlGenPowerLevelState_t powerLevel)
void MmdlGenPowerRangeClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlGenPowerRangeClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, const mmdlGenPowerRangeSetParam_t *pSetParam)
void MmdlGenPowerRangeClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, const mmdlGenPowerRangeSetParam_t *pSetParam)
void MmdlGenPowerLevelClRegister (mmdlEventCback_t recvCback)
Variables
wsfHandlerId_t mmdlGenPowerLevelClHandlerId
const meshMsgOpcode_t mmdlGenPowerLevelClRcvdOpcodes []
Detailed Description
Data Structure Documentation
mmdlGenPowerLevelSetParam_t
struct mmdlGenPowerLevelSetParam_t
Model Power Level Client Set parameters structure.
Data Fields
mmdlGenPowerLevelState_t state
uint8_t tid
uint8_t transitionTime
uint8_t delay
Field Documentation
delay
uint8_t delay
Delay in steps of 5 ms
state
mmdlGenPowerLevelState_t state
New Power State
tid
uint8_t tid
Transaction Identifier
transitionTime
uint8_t transitionTime
Transition time
mmdlGenPowerDefaultSetParam_t
struct mmdlGenPowerDefaultSetParam_t
Model Power Range Client Set parameters structure.
Data Fields
mmdlGenPowerLevelState_t state
Field Documentation
state
mmdlGenPowerLevelState_t state
Default Power State
mmdlGenPowerRangeSetParam_t
struct mmdlGenPowerRangeSetParam_t
Model Power Level Client Set parameters structure.
Data Fields
mmdlGenPowerLevelState_t powerMin
mmdlGenPowerLevelState_t powerMax
Field Documentation
powerMax
mmdlGenPowerLevelState_t powerMax
Maximum Power Range State
powerMin
mmdlGenPowerLevelState_t powerMin
Minimum Power Range State
mmdlGenPowerLevelClStatusEvent_t
struct mmdlGenPowerLevelClStatusEvent_t
Generic Power Level Client Model Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
mmdlGenPowerLevelState_t state
mmdlGenPowerLevelState_t targetState
uint8_t remainingTime
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
remainingTime
uint8_t remainingTime
Remaining time until the transition completes
serverAddr
meshAddress_t serverAddr
Server Address
state
mmdlGenPowerLevelState_t state
Received published state
targetState
mmdlGenPowerLevelState_t targetState
Received published target state
mmdlGenPowerLastClStatusEvent_t
struct mmdlGenPowerLastClStatusEvent_t
Generic Power Last Client Model Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
mmdlGenPowerLevelState_t lastState
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
lastState
mmdlGenPowerLevelState_t lastState
Received published last state
serverAddr
meshAddress_t serverAddr
Server Address
mmdlGenPowerDefaultClStatusEvent_t
struct mmdlGenPowerDefaultClStatusEvent_t
Generic Power Default Client Model Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
mmdlGenPowerLevelState_t state
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
serverAddr
meshAddress_t serverAddr
Server Address
state
mmdlGenPowerLevelState_t state
Received published state
mmdlGenPowerRangeClStatusEvent_t
struct mmdlGenPowerRangeClStatusEvent_t
Generic Power Range Client Model Status event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elementId
meshAddress_t serverAddr
uint8_t statusCode
mmdlGenPowerLevelState_t powerMin
mmdlGenPowerLevelState_t powerMax
Field Documentation
elementId
meshElementId_t elementId
Element ID
hdr
wsfMsgHdr_t hdr
WSF message header
powerMax
mmdlGenPowerLevelState_t powerMax
Maximum Power Range state
powerMin
mmdlGenPowerLevelState_t powerMin
Minimum Power Range state
serverAddr
meshAddress_t serverAddr
Server Address
statusCode
uint8_t statusCode
Status Code
mmdlGenPowerLevelClEvent_t
union mmdlGenPowerLevelClEvent_t
Generic Power Level Client Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlGenPowerLevelClStatusEvent_t statusEvent
mmdlGenPowerLastClStatusEvent_t lastStatusEvent
mmdlGenPowerDefaultClStatusEvent_t defaultStatusEvent
mmdlGenPowerRangeClStatusEvent_t rangeStatusEvent
Field Documentation
defaultStatusEvent
mmdlGenPowerDefaultClStatusEvent_t defaultStatusEvent
State updated event. Used for MMDL_GEN_POWER_DEFAULT_CL_STATUS_EVENT.
hdr
wsfMsgHdr_t hdr
WSF message header
lastStatusEvent
mmdlGenPowerLastClStatusEvent_t lastStatusEvent
State updated event. Used for MMDL_GEN_POWER_LAST_CL_STATUS_EVENT.
rangeStatusEvent
mmdlGenPowerRangeClStatusEvent_t rangeStatusEvent
State updated event. Used for MMDL_GEN_POWER_RANGE_CL_STATUS_EVENT.
statusEvent
mmdlGenPowerLevelClStatusEvent_t statusEvent
State updated event. Used for MMDL_GEN_POWER_LEVEL_CL_STATUS_EVENT.
Function Documentation
MmdlGenPowerDefaultClGet()
void MmdlGenPowerDefaultClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a GenPowerDefaultGet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlGenPowerDefaultClSet()
void MmdlGenPowerDefaultClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, mmdlGenPowerLevelState_t powerLevel)
Send a GenPowerDefaultSet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
[in] powerLevel Default power level.
Returns
None.
References MESH_MSG_INFO.
MmdlGenPowerDefaultClSetNoAck()
void MmdlGenPowerDefaultClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, mmdlGenPowerLevelState_t powerLevel)
Send a GenPowerDefaultSetUnacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] appKeyIndex Application Key Index.
[in] powerLevel Default power level.
Returns
None.
References MESH_MSG_INFO.
MmdlGenPowerLastClGet()
void MmdlGenPowerLastClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a GenPowerLastGet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlGenPowerLevelClGet()
void MmdlGenPowerLevelClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a GenPowerLevelGet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlGenPowerLevelClHandler()
void MmdlGenPowerLevelClHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Power Level Client Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlGenPowerLevelClHandlerInit()
void MmdlGenPowerLevelClHandlerInit (wsfHandlerId_t handlerId)
Initializes the Mesh WSF handler.
Parameters
[in] handlerId WSF handler ID for On Off Client Model.
Returns
None.
References mmdlGenPowerLevelClHandlerId.
MmdlGenPowerLevelClRegister()
void MmdlGenPowerLevelClRegister (mmdlEventCback_t recvCback)
Install the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlGenPowerLevelClSet()
void MmdlGenPowerLevelClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlGenPowerLevelSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a GenPowerLevelSet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MESH_MSG_INFO.
MmdlGenPowerLevelClSetNoAck()
void MmdlGenPowerLevelClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlGenPowerLevelSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a GenPowerLevelSetUnacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MESH_MSG_INFO.
MmdlGenPowerRangeClGet()
void MmdlGenPowerRangeClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a GenPowerRangeGet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, MESH_MSG_INFO, MeshSendMessage(), and meshMsgInfo_t::ttl.
MmdlGenPowerRangeClSet()
void MmdlGenPowerRangeClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, const mmdlGenPowerRangeSetParam_t * pSetParam)
Send a GenPowerRangeSet message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
[in] pSetParam Pointer to structure containing the set parameters.
Returns
None.
References MESH_MSG_INFO.
MmdlGenPowerRangeClSetNoAck()
void MmdlGenPowerRangeClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex, const mmdlGenPowerRangeSetParam_t * pSetParam)
Send a GenPowerRangeSetUnacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] appKeyIndex Application Key Index.
[in] pSetParam Pointer to structure containing the set parameters.
Returns
None.
References MESH_MSG_INFO.
Variable Documentation
mmdlGenPowerLevelClHandlerId
wsfHandlerId_t mmdlGenPowerLevelClHandlerId
WSF handler id.
WSF handler id
mmdlGenPowerLevelClRcvdOpcodes
const meshMsgOpcode_t mmdlGenPowerLevelClRcvdOpcodes[]
Supported opcodes.
Supported opcodes