Cordio: Light Lightness Client Model API
Light Lightness Client Model API
Functions
void MmdlLightLightnessClHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightLightnessClHandler (wsfMsgHdr_t *pMsg)
void MmdlLightLightnessClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlLightLightnessClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessLinearClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlLightLightnessLinearClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessLinearSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessLinearClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessLinearSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessLastClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlLightLightnessDefaultClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlLightLightnessDefaultClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessDefaultSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessDefaultClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessDefaultSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessRangeClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
void MmdlLightLightnessRangeClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessRangeSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessRangeClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessRangeSetParam_t *pSetParam, uint16_t appKeyIndex)
void MmdlLightLightnessClRegister (mmdlEventCback_t recvCback)
Variables
wsfHandlerId_t mmdlLightLightnessClHandlerId
const meshMsgOpcode_t mmdlLightLightnessClRcvdOpcodes []
Detailed Description
Function Documentation
MmdlLightLightnessClGet()
void MmdlLightLightnessClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Light Lightness Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, meshPubMsgInfo_t::elementId, MESH_MSG_INFO, MESH_PUB_MSG_INFO, MeshPublishMessage(), MeshSendMessage(), MMDL_USE_PUBLICATION_ADDR, and meshMsgInfo_t::ttl.
MmdlLightLightnessClHandler()
void MmdlLightLightnessClHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light Lightness Client Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlLightLightnessClHandlerInit()
void MmdlLightLightnessClHandlerInit (wsfHandlerId_t handlerId)
Initializes the Mesh WSF handler.
Parameters
[in] handlerId WSF handler ID for Light Lightness Client Model.
Returns
None.
References mmdlLightLightnessClHandlerId.
MmdlLightLightnessClRegister()
void MmdlLightLightnessClRegister (mmdlEventCback_t recvCback)
Install the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightLightnessClSet()
void MmdlLightLightnessClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessClSetNoAck()
void MmdlLightLightnessClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Set Unacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessDefaultClGet()
void MmdlLightLightnessDefaultClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Light Lightness Default Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, meshPubMsgInfo_t::elementId, MESH_MSG_INFO, MESH_PUB_MSG_INFO, MeshPublishMessage(), MeshSendMessage(), MMDL_USE_PUBLICATION_ADDR, and meshMsgInfo_t::ttl.
MmdlLightLightnessDefaultClSet()
void MmdlLightLightnessDefaultClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessDefaultSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Default Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessDefaultClSetNoAck()
void MmdlLightLightnessDefaultClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessDefaultSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Default Set Unacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessLastClGet()
void MmdlLightLightnessLastClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Light Lightness Last Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, meshPubMsgInfo_t::elementId, MESH_MSG_INFO, MESH_PUB_MSG_INFO, MeshPublishMessage(), MeshSendMessage(), MMDL_USE_PUBLICATION_ADDR, and meshMsgInfo_t::ttl.
MmdlLightLightnessLinearClGet()
void MmdlLightLightnessLinearClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Light Lightness Linear Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, meshPubMsgInfo_t::elementId, MESH_MSG_INFO, MESH_PUB_MSG_INFO, MeshPublishMessage(), MeshSendMessage(), MMDL_USE_PUBLICATION_ADDR, and meshMsgInfo_t::ttl.
MmdlLightLightnessLinearClSet()
void MmdlLightLightnessLinearClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessLinearSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Linear Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessLinearClSetNoAck()
void MmdlLightLightnessLinearClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessLinearSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Linear Set Unacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server or MMDL_USE_PUBLICATION_ADDR.
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessRangeClGet()
void MmdlLightLightnessRangeClGet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, uint16_t appKeyIndex)
Send a Light Lightness Ranger Get message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] appKeyIndex Application Key Index.
Returns
None.
References meshMsgInfo_t::appKeyIndex, meshMsgInfo_t::dstAddr, meshMsgInfo_t::elementId, meshPubMsgInfo_t::elementId, MESH_MSG_INFO, MESH_PUB_MSG_INFO, MeshPublishMessage(), MeshSendMessage(), MMDL_USE_PUBLICATION_ADDR, and meshMsgInfo_t::ttl.
MmdlLightLightnessRangeClSet()
void MmdlLightLightnessRangeClSet (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessRangeSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Range Set message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] serverAddr Element address of the server.
[in] ttl TTL value as defined by the specification.
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
MmdlLightLightnessRangeClSetNoAck()
void MmdlLightLightnessRangeClSetNoAck (meshElementId_t elementId, meshAddress_t serverAddr, uint8_t ttl, const mmdlLightLightnessRangeSetParam_t * pSetParam, uint16_t appKeyIndex)
Send a Light Lightness Range Set Unacknowledged message to the destination address.
Parameters
[in] elementId Identifier of the Element implementing the model
[in] serverAddr Element address of the server
[in] ttl TTL value as defined by the specification
[in] pSetParam Pointer to structure containing the set parameters.
[in] appKeyIndex Application Key Index.
Returns
None.
References MMDL_USE_PUBLICATION_ADDR.
Variable Documentation
mmdlLightLightnessClHandlerId
wsfHandlerId_t mmdlLightLightnessClHandlerId
WSF handler id.
WSF handler id
mmdlLightLightnessClRcvdOpcodes
const meshMsgOpcode_t mmdlLightLightnessClRcvdOpcodes[]
Supported opcodes.
Supported opcodes