Cordio: LL_API_CIS
LL_API_CIS
Functions
uint8_t LlSetCigParams (LlCisCigParams_t *pCigParam, uint16_t *pCisHandles)
uint8_t LlSetCigParamsTest (LlCisCigParamsTest_t *pSetCigParamTest, uint16_t *pCisHandles)
uint8_t LlCreateCis (uint8_t numCis, LlCisCreateCisParams_t *pCreateCisParam)
uint8_t LlRemoveCig (uint8_t cigId)
uint8_t LlAcceptCisReq (uint16_t cisHandle)
uint8_t LlRejectCisReq (uint16_t cisHandle, uint8_t reason)
uint8_t LlCreateBig (LlCreateBig_t *pCreateBig)
uint8_t LlCreateBigTest (LlCreateBigTest_t *pCreateBigTest)
uint8_t LlTerminateBig (uint8_t bigHandle, uint8_t reason)
uint8_t LlBigCreateSync (LlBigCreateSync_t *pCreateSync)
void LlBigTerminateSync (uint8_t bigHandle)
uint8_t LlReadIsoTxSync (uint16_t handle, uint16_t *pPktSn, uint32_t *pTs, uint32_t *pTimeOffs)
uint8_t LlSetupIsoDataPath (LlIsoSetupDataPath_t *pSetupDataPath)
uint8_t LlRemoveIsoDataPath (uint16_t handle, uint8_t dpDir)
void LlCisSlaveInit (void)
void LlCisMasterInit (void)
uint16_t LlInitCisMem (uint8_t *pFreeMem, uint32_t freeMemSize)
void LlBisSlaveInit (void)
void LlBisMasterInit (void)
uint16_t LlInitBisMem (uint8_t *pFreeMem, uint32_t freeMemSize)
uint16_t LlInitIsoMem (uint8_t *pFreeMem, uint32_t freeMemSize)
void LlInitCodec (void)
void LlSendIsoData (uint8_t *pData)
uint8_t * LlRecvIsoData (void)
void LlRecvIsoDataComplete (uint8_t numBufs)
Detailed Description
Function Documentation
LlAcceptCisReq()
uint8_t LlAcceptCisReq (uint16_t cisHandle)
Used by the slave host to inform the controller to accept the request for the connected isochronous stream.
Parameters
cisHandle Handle of the connected isochronous stream.
Returns
Status error code.
LlBigCreateSync()
uint8_t LlBigCreateSync (LlBigCreateSync_t * pCreateSync)
Used to synchronize and receive PDUs from one or more BISes within a BIG.
Parameters
pCreateSync BIG Create Sync parameters.
Returns
Status error code.
References LlBigCreateSync_t::bigHandle, and LlBigCreateSync_t::syncHandle.
LlBigTerminateSync()
void LlBigTerminateSync (uint8_t bigHandle)
Used to stop synchronization with the BIG or to cancel the process of synchronizing to BISes invoked by the HCI_LE_BIG_Create_Sync command.
Parameters
bigHandle Used to identify the BIG.
References LctrMstBigTerminateSync().
LlBisMasterInit()
void LlBisMasterInit (void)
Initialize LL subsystem for operation for master broadcast isochronous stream.
This function initializes the LL subsystem for use as a master broadcast isochronous stream.
Initialize LL subsystem for operation for master broadcast isochronous stream.
This function initializes the LL subsystem for use as a slave broadcast isochronous stream.
References LctrMstBisInit(), LmgrIsoInit(), pLctrRtCfg, and WSF_ASSERT.
LlBisSlaveInit()
void LlBisSlaveInit (void)
Initialize LL subsystem for operation for slave broadcast isochronous stream.
This function initializes the LL subsystem for use as a slave broadcast isochronous stream.
References LmgrIsoInit(), pLctrRtCfg, and WSF_ASSERT.
LlCisMasterInit()
void LlCisMasterInit (void)
Initialize LL subsystem for operation for master connected isochronous stream.
This function initializes the LL subsystem for use as a master connected isochronous stream.
References LmgrIsoInit(), LmgrMstCisInit(), pLctrRtCfg, and WSF_ASSERT.
LlCisSlaveInit()
void LlCisSlaveInit (void)
Initialize LL subsystem for operation for slave connected isochronous stream.
This function initializes the LL subsystem for use as a slave connected isochronous stream.
References LmgrIsoInit(), pLctrRtCfg, and WSF_ASSERT.
LlCreateBig()
uint8_t LlCreateBig (LlCreateBig_t * pCreateBig)
Used by a broadcaster host to command is used to create one or more BISes of a BIG in the controller.
Parameters
pCreateBig Create BIG parameters.
Returns
Status error code.
References LlCreateBig_t::advHandle, and LlCreateBig_t::bigHandle.
LlCreateBigTest()
uint8_t LlCreateBigTest (LlCreateBigTest_t * pCreateBigTest)
Used by a broadcaster host to command is used to create one or more BISes of a BIG in the ISO test mode.
Parameters
pCreateBigTest Create BIG Test parameters.
Returns
Status error code.
Parameters
pCreateBigTest Create BIG parameters.
Returns
Status error code.
References LlCreateBigTest_t::advHandle, and LlCreateBigTest_t::bigHandle.
LlCreateCis()
uint8_t LlCreateCis (uint8_t numCis, LlCisCreateCisParams_t * pCreateCisParam)
Used by the master host to establish one or more connected isochronous streams.
Parameters
numCis Number of connected isochronous streams.
pCreateCisParam Parameters for create connected isochronous stream.
Returns
Status error code.
References lmgrCtrlBlk_t::features, LctrGetRole(), LctrIsConnHandleEnabled(), LL_FEAT_ISO_HOST_SUPPORT, LL_ROLE_MASTER, lmgrCb, LlRtCfg_t::maxConn, LlCisCreateCisParams_t::pAclHandle, and pLctrRtCfg.
LlInitBisMem()
uint16_t LlInitBisMem (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize memory for BIS.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for BIS.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for BIS slave.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
References pLctrRtCfg, and WSF_ASSERT.
LlInitCisMem()
uint16_t LlInitCisMem (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize memory for CIS.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for CIS.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for CIS slave.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
References pLctrRtCfg, and WSF_ASSERT.
LlInitCodec()
void LlInitCodec (void)
Initialize LL for use with an audio codec.
Assign codec functions for direct LL audio streaming.
LlInitIsoMem()
uint16_t LlInitIsoMem (uint8_t * pFreeMem, uint32_t freeMemSize)
Initialize memory for ISO.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for CIS.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
Parameters
pFreeMem Pointer to free memory.
freeMemSize Size of pFreeMem.
Returns
Amount of free memory consumed.
This function allocates memory for CIS slave.
Note
This routine must be called after LlInitRunTimeCfg() but only once before any other initialization routines.
References pLctrRtCfg, and WSF_ASSERT.
LlReadIsoTxSync()
uint8_t LlReadIsoTxSync (uint16_t handle, uint16_t * pPktSn, uint32_t * pTs, uint32_t * pTimeOffs)
Read the Time_Stamp and Time_Offset of a transmitted ISO_SDU identified by the Packet_Sequence_Number on a CIS or BIS identified by the Connection_Handle.
Parameters
handle BIS or CIS handle.
pPktSn Packet sequence number.
pTs Timestamp.
pTimeOffs Time offset.
Returns
Status error code.
Read the Time_Stamp and Time_Offset of a transmitted ISO_SDU identified by the Packet_Sequence_Number on a CIS or BIS identified by the Connection_Handle.
Parameters
handle BIS or CIS handle.
pPktSn Packet sequence number.
pTs Timestamp.
pTimeOffs Time offset.
Returns
Status error code.
LlRecvIsoData()
uint8_t* LlRecvIsoData (void)
Receive an ISO data packet.
Returns
Data buffer.
Receive an ISO data packet. If no ISO buffers are available this function returns NULL.
Note
The host must deallocate the buffer by calling WsfMsgFree() and call LlRecvBufCmpl() to update LL accounting.
Returns
Data buffer.
Receive an ISO data packet. This function returns a pointer to an ISO buffer formatted according to [1]. The host must parse the header to determine the connection handle, flags, and length fields. If no ISO buffers are available this function returns NULL.
The host must deallocate the buffer by calling WsfMsgFree() and then calling LlRecvIsoDataComplete().
LlRecvIsoDataComplete()
void LlRecvIsoDataComplete (uint8_t numBufs)
Indicate that received ISO data buffer has been deallocated.
Parameters
numBufs Number of completed packets.
Indicate that received ISO data buffer has been deallocated.
LlRejectCisReq()
uint8_t LlRejectCisReq (uint16_t cisHandle, uint8_t reason)
Used by the slave host to inform the controller to reject the request for the connected isochronous stream.
Parameters
cisHandle Handle of the connected isochronous stream.
reason Indicate the reason for rejecting the request.
Returns
Status error code.
LlRemoveCig()
uint8_t LlRemoveCig (uint8_t cigId)
Removes all the connected isochronous streams which have previously been set up.
Parameters
cigId Identifier of the connected isochronous group.
Returns
Status error code.
Removes all the connected isochronous streams which have previously been set up.
Parameters
cigId Identifier of the connected isochronous group.
Returns
Status error code.
LlRemoveIsoDataPath()
uint8_t LlRemoveIsoDataPath (uint16_t handle, uint8_t dpDir)
Used to remove the isochronous data path associated with the connected isochronous or broadcast isochronous stream.
Parameters
handle Handle for CIS or BIS.
dpDir Direction of data path to remove.
Returns
Status error code.
Used to remove the isochronous data path associated with the connected isochronous or broadcast isochronous stream.
Parameters
handle CIS or BIS handle.
dpDir Direction of data path to remove.
LlSendIsoData()
void LlSendIsoData (uint8_t * pData)
Send an ISO data packet.
Parameters
pData Data buffer
Send an ISO data packet. pData points to an ISO buffer formatted according to [1]; the host must set the connection handle, flags, and length fields in the buffer.
Parameters
pData Data buffer
Send an ISO data packet. pData points to an ACL buffer formatted according to [1]; the host must set the connection handle, flags, and length fields in the buffer.
References lmgrIsoCtrlBlk_t::availTxBuf, lmgrIsoCb, and WsfMsgFree().
LlSetCigParams()
uint8_t LlSetCigParams (LlCisCigParams_t * pCigParam, uint16_t * pCisHandles)
Used by a master host to set the parameters of all connected isochronous streams associated with a connected isochronous group in the controller.
Parameters
pCigParam CIG parameters.
pCisHandles Return buffer for the connected isochronous handles.
Returns
Status error code.
Parameters
pCigParam CIG parameters.
pCisHandles Return buffer for the connected isochronous stream handles.
Returns
Status error code.
References LlCisCigParams_t::cigId, LlCisCisParams_t::cisId, LlCisCigParams_t::framing, LlCisCigParams_t::numCis, LlCisCigParams_t::packing, LlCisCigParams_t::pCisParam, LlCisCisParams_t::phyMToS, LlCisCisParams_t::phySToM, LlCisCisParams_t::rteMToS, LlCisCisParams_t::rteSToM, LlCisCigParams_t::sca, LlCisCigParams_t::sduIntervalMToS, LlCisCigParams_t::sduIntervalSToM, LlCisCisParams_t::sduSizeMToS, LlCisCisParams_t::sduSizeSToM, LlCisCigParams_t::transLatMToS, and LlCisCigParams_t::transLatSToM.
LlSetCigParamsTest()
uint8_t LlSetCigParamsTest (LlCisCigParamsTest_t * pSetCigParamTest, uint16_t * pCisHandles)
Used by a master Host to set the parameters of all connected isochronous streams associated with a connected isochronous group in the controller for testing purpose.
Parameters
pSetCigParamTest CIG test parameters.
pCisHandles Return buffer for the connected isochronous handles.
Returns
Status error code.
Parameters
pSetCigParamTest CIG test parameters.
pCisHandles Return buffer for the connected isochronous stream handles.
Returns
Status error code.
References LlCisCigParamsTest_t::numCis.
LlSetupIsoDataPath()
uint8_t LlSetupIsoDataPath (LlIsoSetupDataPath_t * pSetupDataPath)
Used to identify and enable the isochronous data path between the host and the controller for each connected isochronous or broadcast isochronous stream.
Parameters
pSetupDataPath Parameters for setup ISO data path.
Returns
Status error code.
Used to identify and enable the isochronous data path between the host and the controller for each connected isochronous or broadcast isochronous stream.
Parameters
pSetupDataPath Parameters for setup ISO data path.
References LlIsoSetupDataPath_t::dpDir, LlIsoSetupDataPath_t::dpId, and LlIsoSetupDataPath_t::handle.
LlTerminateBig()
uint8_t LlTerminateBig (uint8_t bigHandle, uint8_t reason)
Used to terminate the transmission of all BISes of a BIG, or to cancel the process of creating a BIG using the HCI_LE_Create_BIG command from the Isochronous Broadcaster.
Parameters
bigHandle Used to identify the BIG.
reason Termination reason.
Returns
Status error code.