Cordio: PAL_FLASH
PAL_FLASH
Typedefs
typedef void(* PalFlashCback_t) (bool_t status)
Enumerations
enum PalFlashState_t
Functions
void PalFlashInit (PalFlashCback_t actCback)
void PalFlashDeInit (void)
PalFlashState_t PalNvmGetState (void)
uint32_t PalNvmGetTotalSize (void)
uint32_t PalNvmGetSectorSize (void)
void PalFlashRead (void *pBuf, uint32_t size, uint32_t srcAddr)
void PalFlashWrite (void *pBuf, uint32_t size, uint32_t dstAddr)
void PalFlashEraseSector (uint32_t size, uint32_t startAddr)
void PalFlashEraseChip (void)
Detailed Description
Enumeration Type Documentation
PalFlashState_t
enum PalFlashState_t
Operational states.
Enumerator
PAL_FLASH_STATE_UNINIT
Uninitialized state.
PAL_FLASH_STATE_ERROR
Error state.
PAL_FLASH_STATE_READY
Ready state.
PAL_FLASH_STATE_BUSY
Busy state.
Function Documentation
PalFlashDeInit()
void PalFlashDeInit (void)
De-initialize the platform flash.
Returns
None.
PalFlashEraseChip()
void PalFlashEraseChip (void)
Erase all of the NVM.
Returns
None.
References WsfCsEnter(), and WsfCsExit().
PalFlashEraseSector()
void PalFlashEraseSector (uint32_t size, uint32_t startAddr)
Erase sector.
Parameters
[in] size Data size in sectors to be erased.
[in] startAddr Word aligned address.
Returns
None.
References PalSysAssertTrap(), WsfCsEnter(), and WsfCsExit().
PalFlashInit()
void PalFlashInit (PalFlashCback_t actCback)
Initialize the platform flash.
Parameters
[in] actCback Callback function.
Returns
None.
PalFlashRead()
void PalFlashRead (void * pBuf, uint32_t size, uint32_t srcAddr)
Reads data from NVM storage.
Parameters
[in] pBuf Pointer to memory buffer where data will be stored.
[in] size Data size in bytes to be read.
[in] srcAddr Word aligned address from where data is read.
Returns
None.
References PAL_FLASH_STATE_READY, and PalNvmGetState().
PalFlashWrite()
void PalFlashWrite (void * pBuf, uint32_t size, uint32_t dstAddr)
Writes data to NVM storage.
Parameters
[in] pBuf Pointer to memory buffer from where data will be written.
[in] size Data size in bytes to be written.
[in] dstAddr Word aligned address to write data.
Returns
None.
References PAL_FLASH_STATE_READY, PalEnterCs(), PalExitCs(), PalNvmGetState(), PalSysAssertTrap(), WSF_ASSERT, WsfCsEnter(), and WsfCsExit().
PalNvmGetSectorSize()
uint32_t PalNvmGetSectorSize (void)
Get NVM sector size.
Returns
NVM sector size in bytes.
PalNvmGetState()
PalFlashState_t PalNvmGetState (void)
Get NVM state.
Returns
NVM state.
References PAL_FLASH_STATE_READY, and PAL_FLASH_STATE_UNINIT.
PalNvmGetTotalSize()
uint32_t PalNvmGetTotalSize (void)
Get NVM size.
Returns
NVM size in bytes.