Cordio: Light Lightness Server Model API
Light Lightness Server Model API
Data Structures
union mmdlLightLightnessStates_t
struct mmdlLightLightnessSrStateUpdate_t
struct mmdlLightLightnessSrCurrentState_t
union mmdlLightLightnessSrEvent_t
struct mmdlLightLightnessSrDesc_t
Macros
#define MMDL_LIGHT_LIGHTNESS_STATE_CNT 7
Functions
void MmdlLightLightnessSrInit (void)
void MmdlLightLightnessSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightLightnessSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightLightnessSrPublish (meshElementId_t elementId)
void MmdlLightLightnessSrPublishLinear (meshElementId_t elementId)
void MmdlLightLightnessSrGetState (meshElementId_t elementId)
void MmdlLightLightnessSrSetState (meshElementId_t elementId, mmdlLightLightnessState_t targetState)
void MmdlLightLightnessLinearSrGetState (meshElementId_t elementId)
void MmdlLightLightnessLinearSrSetState (meshElementId_t elementId, mmdlLightLightnessState_t targetState)
void MmdlLightLightnessLastSrGetState (meshElementId_t elementId)
void MmdlLightLightnessDefaultSrGetState (meshElementId_t elementId)
void MmdlLightLightnessRangeSrGetState (meshElementId_t elementId)
void MmdlLightLightnessSrRegister (mmdlEventCback_t recvCback)
void MmdlLightLightnessSrBind2OnPowerUp (meshElementId_t onPowerUpElemId, meshElementId_t ltElemId)
void MmdlLightLightnessSrBind2GenLevel (meshElementId_t ltElemId, meshElementId_t glvElemId)
void MmdlLightLightnessSrBind2OnOff (meshElementId_t ltElemId, meshElementId_t onoffElemId)
void MmdlLightLightnessSetupSrInit (void)
void MmdlLightLightnessSetupSrHandlerInit (wsfHandlerId_t handlerId)
void MmdlLightLightnessSetupSrHandler (wsfMsgHdr_t *pMsg)
void MmdlLightLightnessDefaultSetupSrSetState (meshElementId_t elementId, mmdlLightLightnessState_t targetState)
void MmdlLightLightnessRangeSetupSrSetState (meshElementId_t elementId, const mmdlLightLightnessRangeState_t *pTargetState)
void MmdlLightLightnessSetupSrRegister (mmdlEventCback_t recvCback)
Variables
wsfHandlerId_t mmdlLightLightnessSrHandlerId
const meshMsgOpcode_t mmdlLightLightnessSrRcvdOpcodes []
wsfHandlerId_t mmdlLightLightnessSetupSrHandlerId
const meshMsgOpcode_t mmdlLightLightnessSetupSrRcvdOpcodes []
Detailed Description
Data Structure Documentation
mmdlLightLightnessStates_t
union mmdlLightLightnessStates_t
Union of Light Lightness states.
Data Fields
mmdlLightLightnessState_t state
mmdlLightLightnessRangeState_t rangeState
Field Documentation
rangeState
mmdlLightLightnessRangeState_t rangeState
Range state
state
mmdlLightLightnessState_t state
State
mmdlLightLightnessSrStateUpdate_t
struct mmdlLightLightnessSrStateUpdate_t
Light Lightness Server Model State Update event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
mmdlStateUpdateSrc_t stateUpdateSource
mmdlLightLightnessStates_t lightnessState
Field Documentation
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
lightnessState
mmdlLightLightnessStates_t lightnessState
Updated state union
stateUpdateSource
mmdlStateUpdateSrc_t stateUpdateSource
Updated state source
mmdlLightLightnessSrCurrentState_t
struct mmdlLightLightnessSrCurrentState_t
Light Lightness Server Model Current State event structure.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
mmdlLightLightnessStates_t lightnessState
Field Documentation
elemId
meshElementId_t elemId
Element identifier
hdr
wsfMsgHdr_t hdr
WSF message header
lightnessState
mmdlLightLightnessStates_t lightnessState
Current state union
mmdlLightLightnessSrEvent_t
union mmdlLightLightnessSrEvent_t
Light Lightness Server Model event callback parameters structure.
Data Fields
wsfMsgHdr_t hdr
mmdlLightLightnessSrStateUpdate_t statusEvent
mmdlLightLightnessSrCurrentState_t currentStateEvent
Field Documentation
currentStateEvent
mmdlLightLightnessSrCurrentState_t currentStateEvent
Current state event. Sent after a Get request from the upper layer. Used for MMDL_LIGHT_LIGHTNESS_SR_CURRENT_STATE_EVENT.
hdr
wsfMsgHdr_t hdr
WSF message header
statusEvent
mmdlLightLightnessSrStateUpdate_t statusEvent
State updated event. Used for MMDL_LIGHT_LIGHTNESS_SR_STATE_UPDATE_EVENT.
mmdlLightLightnessSrDesc_t
struct mmdlLightLightnessSrDesc_t
Light Lightness Server descriptor definition.
Data Fields
mmdlLightLightnessState_t * pStoredStates
mmdlNvmSaveHandler_t fNvmSaveStates
wsfTimer_t transitionTimer
wsfTimer_t msgRcvdTimer
uint32_t remainingTimeMs
int16_t transitionStep
uint16_t steps
uint8_t delay5Ms
uint8_t transactionId
meshAddress_t srcAddr
bool_t ackPending
bool_t ackForUnicast
uint16_t ackAppKeyIndex
uint8_t transitionType
mmdlStateUpdateSrc_t updateSource
Field Documentation
ackAppKeyIndex
uint16_t ackAppKeyIndex
AppKeyIndex used for the last received message.
ackForUnicast
bool_t ackForUnicast
TRUE if the last message was received as a unicast, FALSE otherwise.
ackPending
bool_t ackPending
TRUE if an ACK is pending for the last received message.
delay5Ms
uint8_t delay5Ms
Delay until the transition to the new state begins. Unit is 5 ms.
fNvmSaveStates
mmdlNvmSaveHandler_t fNvmSaveStates
Pointer to function that saves Model instance states in NVM
msgRcvdTimer
wsfTimer_t msgRcvdTimer
Timer to manage received logically group messages.
pStoredStates
mmdlLightLightnessState_t* pStoredStates
Pointer to the structure that stores current state and scene data. First value is always the current one. Second value is the target state. Sequential values represent scene values starting with scene index 0 and ending with index :MMDL_NUM_OF_SCENES - 1. Structure will store :MMDL_NUM_OF_SCENES + 2 states.
remainingTimeMs
uint32_t remainingTimeMs
Time remaining until the current state is replaced with the target state. If set to 0, the target state is ignored. Unit is 1 ms.
srcAddr
meshAddress_t srcAddr
Source address of the logically grouped series of messages.
steps
uint16_t steps
The number of transition steps
transactionId
uint8_t transactionId
Transaction Identifier used to logically group a series of messages.
transitionStep
int16_t transitionStep
Transition state update step
transitionTimer
wsfTimer_t transitionTimer
WSF Timer for delay and state transition
transitionType
uint8_t transitionType
Transition type - Actual or Linear
updateSource
mmdlStateUpdateSrc_t updateSource
State update source. Cached for transitions.
Function Documentation
MmdlLightLightnessDefaultSetupSrSetState()
void MmdlLightLightnessDefaultSetupSrSetState (meshElementId_t elementId, mmdlLightLightnessState_t targetState)
Set the local Light Lightness Default state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] targetState Target State for this transaction. See mmdlLightLightnessState_t
Returns
None.
Set the local Light Lightness Default state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] targetState Target State for this transaction. See mmdlLightLightnessState_t
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
MmdlLightLightnessDefaultSrGetState()
void MmdlLightLightnessDefaultSrGetState (meshElementId_t elementId)
Get the local Light Lightness Default state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_INVALID_ELEMENT, MMDL_LIGHT_LIGHTNESS_DEFAULT_SR_CURRENT_STATE_EVENT, MMDL_LIGHT_LIGHTNESS_SR_EVENT, MMDL_SUCCESS, and mmdlLightLightnessSrDesc_t::pStoredStates.
MmdlLightLightnessLastSrGetState()
void MmdlLightLightnessLastSrGetState (meshElementId_t elementId)
Get the Light Lightness Last state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
Get the Light Lightness Last state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_INVALID_ELEMENT, MMDL_LIGHT_LIGHTNESS_LAST_SR_CURRENT_STATE_EVENT, MMDL_LIGHT_LIGHTNESS_SR_EVENT, MMDL_SUCCESS, and mmdlLightLightnessSrDesc_t::pStoredStates.
MmdlLightLightnessLinearSrGetState()
void MmdlLightLightnessLinearSrGetState (meshElementId_t elementId)
Get the local Light Lightness Linear state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_INVALID_ELEMENT, MMDL_LIGHT_LIGHTNESS_LINEAR_SR_CURRENT_STATE_EVENT, MMDL_LIGHT_LIGHTNESS_SR_EVENT, MMDL_SUCCESS, and mmdlLightLightnessSrDesc_t::pStoredStates.
MmdlLightLightnessLinearSrSetState()
void MmdlLightLightnessLinearSrSetState (meshElementId_t elementId, mmdlLightLightnessState_t targetState)
Set the Light Lightness Linear state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] targetState Target State for this transaction. See mmdlLightLightnessState_t
Returns
None.
Set the Light Lightness Linear state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] targetState Target State for this transaction. See mmdlLightLightnessState_t
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
MmdlLightLightnessRangeSetupSrSetState()
void MmdlLightLightnessRangeSetupSrSetState (meshElementId_t elementId, const mmdlLightLightnessRangeState_t * pTargetState)
Set the local Light Lightness Range state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] pTargetState Target State for this transaction. See mmdlLightLightnessRangeState_t
Returns
None.
Set the local Light Lightness Range state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] targetState Target State for this transaction. See mmdlLightLightnessRangeState_t
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
MmdlLightLightnessRangeSrGetState()
void MmdlLightLightnessRangeSrGetState (meshElementId_t elementId)
Get the Light Lightness Range state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
Get the Light Lightness Range state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_INVALID_ELEMENT, MMDL_LIGHT_LIGHTNESS_RANGE_SR_CURRENT_STATE_EVENT, MMDL_LIGHT_LIGHTNESS_SR_EVENT, MMDL_STATE_UPDATED_BY_BIND, MMDL_SUCCESS, and mmdlLightLightnessSrDesc_t::pStoredStates.
MmdlLightLightnessSetupSrHandler()
void MmdlLightLightnessSetupSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light Lightness Setup Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, meshModelMsgRecvEvt_t::opCode, and meshMsgOpcode_t::opcodeBytes.
MmdlLightLightnessSetupSrHandlerInit()
void MmdlLightLightnessSetupSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light Lightness Setup Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light Lightness Server Model.
Returns
None.
Parameters
[in] handlerId WSF handler ID for Light Lightness Setup Server Model.
Returns
None.
References mmdlLightLightnessSetupSrHandlerId.
MmdlLightLightnessSetupSrInit()
void MmdlLightLightnessSetupSrInit (void)
Initializes the Light Lightness Setup Server module.
Returns
None.
MmdlLightLightnessSetupSrRegister()
void MmdlLightLightnessSetupSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightLightnessSrBind2GenLevel()
void MmdlLightLightnessSrBind2GenLevel (meshElementId_t ltElemId, meshElementId_t glvElemId)
Creates a bind between a Light Lightness Actual State and a Generic Level state.
Parameters
[in] ltElemId Element identifier where the Light Lightness Actual state resides.
[in] glvElemId Element identifier where the Generic Level state resides.
Returns
None.
MmdlLightLightnessSrBind2OnOff()
void MmdlLightLightnessSrBind2OnOff (meshElementId_t ltElemId, meshElementId_t onoffElemId)
Creates a bind between a Light Lightness Actual State and a Generic On Off state.
Parameters
[in] ltElemId Element identifier where the Light Lightness Actual state resides.
[in] onoffElemId Element identifier where the On Off state resides.
Returns
None.
MmdlLightLightnessSrBind2OnPowerUp()
void MmdlLightLightnessSrBind2OnPowerUp (meshElementId_t onPowerUpElemId, meshElementId_t ltElemId)
Creates a bind between a Light Lightness Actual State and a Generic OnPowerUp state.
Parameters
[in] ltElemId Element identifier where the Light Lightness Actual state resides.
[in] onPowerUpElemId Element identifier where the OnPowerUp state resides.
Returns
None.
MmdlLightLightnessSrGetState()
void MmdlLightLightnessSrGetState (meshElementId_t elementId)
Get the local Light Lightness Actual state.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References MMDL_INVALID_ELEMENT, MMDL_LIGHT_LIGHTNESS_SR_CURRENT_STATE_EVENT, MMDL_LIGHT_LIGHTNESS_SR_EVENT, MMDL_SUCCESS, and mmdlLightLightnessSrDesc_t::pStoredStates.
MmdlLightLightnessSrHandler()
void MmdlLightLightnessSrHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Light Lightness Server Model.
Parameters
[in] pMsg WSF message.
Returns
None.
References meshModelPeriodicPubEvt_t::elementId, wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_MODEL_EVT_PERIODIC_PUB, MESH_OPCODE_SIZE, MmdlLightLightnessSrPublish(), meshModelEvt_t::msgRecvEvt, meshModelPeriodicPubEvt_t::nextPubTimeMs, meshModelMsgRecvEvt_t::opCode, meshMsgOpcode_t::opcodeBytes, and meshModelEvt_t::periodicPubEvt.
MmdlLightLightnessSrHandlerInit()
void MmdlLightLightnessSrHandlerInit (wsfHandlerId_t handlerId)
Initializes the Light Lightness Server WSF handler.
Parameters
[in] handlerId WSF handler ID for Light Lightness Server Model.
Returns
None.
References mmdlLightLightnessSrHandlerId.
MmdlLightLightnessSrInit()
void MmdlLightLightnessSrInit (void)
Initializes the Light Lightness Server module.
Returns
None.
References meshConfig_t::elementArrayLen, wsfMsgHdr_t::event, wsfTimer_t::handlerId, MESH_ADDR_TYPE_UNASSIGNED, mmdlLightLightnessSrHandlerId, wsfTimer_t::msg, pMeshConfig, mmdlLightLightnessSrDesc_t::srcAddr, and mmdlLightLightnessSrDesc_t::transitionTimer.
MmdlLightLightnessSrPublish()
void MmdlLightLightnessSrPublish (meshElementId_t elementId)
Publish a Light Lightness Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References meshPubMsgInfo_t::elementId, MESH_PUB_MSG_INFO, MeshPublishMessage(), mmdlLightLightnessSrDesc_t::pStoredStates, mmdlLightLightnessSrDesc_t::remainingTimeMs, mmdlLightLightnessSrDesc_t::steps, wsfTimer_t::ticks, mmdlLightLightnessSrDesc_t::transitionTimer, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, and WSF_MS_PER_TICK.
MmdlLightLightnessSrPublishLinear()
void MmdlLightLightnessSrPublishLinear (meshElementId_t elementId)
Publish a Light Lightness Linear Status message to the subscription list.
Parameters
[in] elementId Identifier of the Element implementing the model.
Returns
None.
References mmdlLightLightnessSrDesc_t::delay5Ms, meshPubMsgInfo_t::elementId, MESH_PUB_MSG_INFO, MeshPublishMessage(), mmdlLightLightnessSrDesc_t::pStoredStates, mmdlLightLightnessSrDesc_t::remainingTimeMs, mmdlLightLightnessSrDesc_t::steps, wsfTimer_t::ticks, mmdlLightLightnessSrDesc_t::transitionTimer, mmdlLightLightnessSrDesc_t::transitionType, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, and WSF_MS_PER_TICK.
MmdlLightLightnessSrRegister()
void MmdlLightLightnessSrRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] recvCback Callback installed by the upper layer to receive messages from the model.
Returns
None.
MmdlLightLightnessSrSetState()
void MmdlLightLightnessSrSetState (meshElementId_t elementId, mmdlLightLightnessState_t targetState)
Set the local Light Lightness Actual state.
Parameters
[in] elementId Identifier of the Element implementing the model.
[in] targetState Target State for this transaction. See mmdlLightLightnessState_t
Returns
None.
References MMDL_STATE_UPDATED_BY_APP.
Variable Documentation
mmdlLightLightnessSetupSrHandlerId
wsfHandlerId_t mmdlLightLightnessSetupSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightLightnessSetupSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightLightnessSetupSrRcvdOpcodes[]
Supported opcodes.
Supported opcodes
mmdlLightLightnessSrHandlerId
wsfHandlerId_t mmdlLightLightnessSrHandlerId
WSF handler id.
WSF handler ID
mmdlLightLightnessSrRcvdOpcodes
const meshMsgOpcode_t mmdlLightLightnessSrRcvdOpcodes[]
Supported opcodes.
Supported opcodes