Cordio: Mesh Provisioning Profile API
Mesh Provisioning Profile API
Enumerations
enum
enum
Functions
void MprvcMprvsDiscover (dmConnId_t connId, uint16_t *pHdlList)
void MprvcSetHandles (dmConnId_t connId, uint16_t dataInHandle, uint16_t dataOutHandle)
void MprvcSendDataIn (meshGattProxyPduSendEvt_t *pEvt)
void MprvcProcMsg (wsfMsgHdr_t *pMsg)
void MprvsProcMsg (wsfMsgHdr_t *pMsg)
uint8_t MprvsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t *pValue, attsAttr_t *pAttr)
void MprvsSetCccIdx (uint8_t dataOutCccIdx)
void MprvsSendDataOut (meshGattProxyPduSendEvt_t *pEvt)
void SvcMprvsAddGroup (void)
void SvcMprvsRemoveGroup (void)
void SvcMprvsRegister (attsWriteCback_t writeCback)
Mesh Provisioning Service handle range
#define MPRVS_START_HDL 0x0500
#define MPRVS_END_HDL (MPRVS_MAX_HDL - 1)
Detailed Description
Enumeration Type Documentation
anonymous enum
anonymous enum
Mesh Provisioning service enumeration of handle indexes of characteristics to be discovered
Enumerator
MPRVC_MPRVS_DIN_HDL_IDX
Data In
MPRVC_MPRVS_DOUT_HDL_IDX
Data Out
MPRVC_MPRVS_DOUT_CCC_HDL_IDX
Data Out CCC descriptor
MPRVC_MPRVS_HDL_LIST_LEN
Handle list length
anonymous enum
anonymous enum
Mesh Provisioning Service handles
Enumerator
MPRVS_SVC_HDL
Mesh Provisioning Server Service declaration
MPRVS_DIN_CH_HDL
Mesh Provisioning Data In characteristic
MPRVS_DIN_HDL
Mesh Provisioning Data In
MPRVS_DOUT_CH_HDL
Mesh Provisioning Data Out characteristic
MPRVS_DOUT_HDL
Mesh Provisioning Data Out
MPRVS_DOUT_CH_CCC_HDL
Mesh Provisioning Data Out Client Characteristic Configuration Descriptor
MPRVS_MAX_HDL
Max handle
Function Documentation
MprvcMprvsDiscover()
void MprvcMprvsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Mesh Provisioning service. Parameter pHdlList must point to an array of length MPRVC_MPRVS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attMprvSvcUuid, and MPRVC_MPRVS_HDL_LIST_LEN.
MprvcProcMsg()
void MprvcProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when a message that requires processing by the Mesh Provisioning client is received.
Parameters
pMsg Event message.
Returns
None.
References ATTC_HANDLE_VALUE_NTF, ATTC_WRITE_CMD_RSP, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
MprvcSendDataIn()
void MprvcSendDataIn (meshGattProxyPduSendEvt_t * pEvt)
Send data to the Mesh Provisioning Server.
Parameters
[in] pEvt GATT Proxy PDU send event.
Returns
None.
Send data to the Mesh Provisioning Server.
Parameters
[in] pEvt GATT Proxy PDU send event.
Returns
None.
References ATT_DEFAULT_PAYLOAD_LEN, ATT_HANDLE_NONE, AttcWriteCmd(), meshGattProxyPduSendEvt_t::connId, meshGattProxyPduSendEvt_t::pProxyPdu, meshGattProxyPduSendEvt_t::proxyHdr, and meshGattProxyPduSendEvt_t::proxyPduLen.
MprvcSetHandles()
void MprvcSetHandles (dmConnId_t connId, uint16_t dataInHandle, uint16_t dataOutHandle)
Set the handle used by the application for interacting with the Mesh Provisioning service Data In characteristic.
Parameters
connId Connection ID.
dataInHandle Data In handled on the server discovered by the client.
dataOutHandle Data Out handled on the server discovered by the client.
Returns
None.
References ATT_VALUE_NTF_LEN, AttGetMtu(), and MeshAddGattProxyConn().
MprvsProcMsg()
void MprvsProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when a message that requires processing by the Mesh Provisioning server is received.
Parameters
pMsg Event message.
Returns
None.
References ATTS_CCC_STATE_IND, ATTS_HANDLE_VALUE_CNF, DM_CONN_CLOSE_IND, DM_CONN_OPEN_IND, and wsfMsgHdr_t::event.
MprvsSendDataOut()
void MprvsSendDataOut (meshGattProxyPduSendEvt_t * pEvt)
Send data on the Mesh Provisioning Server.
Parameters
[in] pEvt GATT Proxy PDU send event.
Returns
None.
References ATT_PDU_VALUE_NTF, AttMsgAlloc(), AttsCccEnabled(), AttsHandleValueNtfZeroCpy(), meshGattProxyPduSendEvt_t::connId, MPRVS_DOUT_HDL, meshGattProxyPduSendEvt_t::pProxyPdu, meshGattProxyPduSendEvt_t::proxyHdr, and meshGattProxyPduSendEvt_t::proxyPduLen.
MprvsSetCccIdx()
void MprvsSetCccIdx (uint8_t dataOutCccIdx)
Set the CCCD index used by the application for mesh provisioning service characteristics.
Parameters
dataOutCccIdx Data Out CCCD index.
Returns
None.
MprvsWriteCback()
uint8_t MprvsWriteCback (dmConnId_t connId, uint16_t handle, uint8_t operation, uint16_t offset, uint16_t len, uint8_t * pValue, attsAttr_t * pAttr)
ATTS write callback for mesh provisioning service. Use this function as a parameter to SvcMprvsRegister().
Parameters
connId DM connection ID.
handle ATT handle.
operation ATT operation.
offset Write offset.
len Write value length.
pValue Data to write.
pAttr Attribute to write.
Returns
ATT status.
ATT status.
References ATT_ERR_INVALID_PDU, ATT_SUCCESS, MESH_GATT_PROXY_PDU_TYPE_PROVISIONING, MESH_SUCCESS, MESH_TEST_EVENT, and MeshProcessGattProxyPdu().
SvcMprvsAddGroup()
void SvcMprvsAddGroup (void)
Add the services to the attribute server.
Returns
None.
References AttsAddGroup().
SvcMprvsRegister()
void SvcMprvsRegister (attsWriteCback_t writeCback)
Register write callback for the service.
Parameters
writeCback Write callback function.
Returns
None.
SvcMprvsRemoveGroup()
void SvcMprvsRemoveGroup (void)
Remove the services from the attribute server.
Returns
None.
References AttsRemoveGroup(), and MPRVS_START_HDL.