Cordio: STACK_L2CAP_API
STACK_L2CAP_API
Data Structures
struct l2cCocReg_t
struct l2cCocConnectInd_t
struct l2cCocDisconnectInd_t
struct l2cCocDataInd_t
struct l2cCocDataCnf_t
struct l2cCocEnConnectInd_t
struct l2cCocEnReconfigInd_t
union l2cCocEvt_t
struct l2cCfg_t
Macros
#define L2C_COC_REG_ID_NONE 0
#define L2C_COC_CID_NONE 0
#define L2C_SIGNAL_ID_INVALID 0
#define L2C_MAX_EN_CHAN 5
#define L2C_PAYLOAD_START (HCI_ACL_HDR_LEN + L2C_HDR_LEN)
#define L2C_SIG_PKT_BASE_LEN (HCI_ACL_HDR_LEN + L2C_HDR_LEN + L2C_SIG_HDR_LEN)
#define L2C_LE_SDU_PKT_BASE_LEN (HCI_ACL_HDR_LEN + L2C_HDR_LEN + L2C_LE_SDU_HDR_LEN)
#define L2C_SIG_RSP_FLAG 0x01
Typedefs
typedef uint16_t l2cCocRegId_t
typedef void(* l2cDataCback_t) (uint16_t handle, uint16_t len, uint8_t *pPacket)
typedef void(* l2cCtrlCback_t) (wsfMsgHdr_t *pMsg)
typedef void(* l2cCocCback_t) (l2cCocEvt_t *pMsg)
typedef uint8_t(* l2cCocAcceptCb_t) (dmConnId_t connId, uint8_t numChans)
typedef uint16_t(* l2cCocAuthorCback_t) (dmConnId_t connId, l2cCocRegId_t regId, uint16_t psm)
L2CAP Control Callback Events
Control callback message events
#define L2C_CTRL_FLOW_ENABLE_IND 0
#define L2C_CTRL_FLOW_DISABLE_IND 1
L2CAP COC Channel Roles
Connection oriented channel initiator/acceptor role
#define L2C_COC_ROLE_NONE 0x00
#define L2C_COC_ROLE_INITIATOR 0x01
#define L2C_COC_ROLE_ACCEPTOR 0x02
L2CAP COC Data Confirm Codes
Connection oriented channel data confirm status values
#define L2C_COC_DATA_SUCCESS 0
#define L2C_COC_DATA_ERR_MEMORY 1
#define L2C_COC_DATA_ERR_OVERFLOW 2
L2CAP COC Callback Events
Connection oriented channel callback events.
enum
#define L2C_COC_CBACK_START 0x70
#define L2C_COC_CBACK_CBACK_END L2C_COC_DATA_CNF
L2CAP Initialization
Initialization and registration functions
void L2cInit (void)
void L2cMasterInit (void)
void L2cSlaveInit (void)
L2CAP CID Functions
Register and send data over a CID
void L2cRegister (uint16_t cid, l2cDataCback_t dataCback, l2cCtrlCback_t ctrlCback)
void L2cDataReq (uint16_t cid, uint16_t handle, uint16_t len, uint8_t *pL2cPacket)
void L2cDmSigReq (uint16_t handle, uint8_t code, uint16_t len, uint8_t *pParam)
L2CAP COC Functions
Connection Oriented Channels Functions
void L2cCocInit (void)
l2cCocRegId_t L2cCocRegister (l2cCocCback_t cback, l2cCocReg_t *pReg)
void L2cCocDeregister (l2cCocRegId_t regId)
void L2cCocSetAcceptCback (l2cCocRegId_t regId, l2cCocAcceptCb_t cback)
uint16_t L2cCocConnectReq (dmConnId_t connId, l2cCocRegId_t regId, uint16_t psm)
void L2cCocDisconnectReq (uint16_t cid)
void L2cCocDataReq (uint16_t cid, uint16_t len, uint8_t *pPayload)
bool_t L2cCocEnhancedConnectReq (dmConnId_t connId, l2cCocRegId_t regId, uint16_t psm, uint16_t credits, uint8_t numChan)
bool_t L2cCocEnhancedReconfigReq (dmConnId_t connId, uint16_t mtu, uint16_t mps, uint8_t numChan, uint16_t *pChanList)
void L2cCocErrorTest (uint16_t result)
void L2cCocCreditSendTest (uint16_t cid, uint16_t credits)
L2CAP Connection Parameter Update Functions
void L2cDmConnUpdateReq (uint16_t handle, hciConnSpec_t *pConnSpec)
void L2cDmConnUpdateRsp (uint8_t identifier, uint16_t handle, uint16_t result)
L2CAP Packet Constants
#define L2C_HDR_LEN 4
#define L2C_MIN_MTU 23
#define L2C_SIG_HDR_LEN 4
#define L2C_LE_SDU_HDR_LEN 2
L2CAP Parameter Lengths
Signaling packet parameter lengths
#define L2C_SIG_CONN_UPDATE_REQ_LEN 8
#define L2C_SIG_CONN_UPDATE_RSP_LEN 2
#define L2C_SIG_CMD_REJ_LEN 2
#define L2C_SIG_DISCONN_REQ_LEN 4
#define L2C_SIG_DISCONN_RSP_LEN 4
#define L2C_SIG_LE_CONN_REQ_LEN 10
#define L2C_SIG_LE_CONN_RSP_LEN 10
#define L2C_SIG_FLOW_CTRL_CREDIT_LEN 4
#define L2C_SIG_EN_CONNECT_REQ_LEN 8
#define L2C_SIG_EN_CONNECT_RSP_LEN 8
#define L2C_SIG_EN_RECONFIG_REQ_LEN 4
#define L2C_SIG_EN_RECONFIG_RSP_LEN 2
L2CAP Connection Identifiers
BLE Defined Connection Identifiers (CID)
#define L2C_CID_ATT 0x0004
#define L2C_CID_LE_SIGNALING 0x0005
#define L2C_CID_SMP 0x0006
L2CAP Signaling Codes
#define L2C_SIG_CMD_REJ 0x01
#define L2C_SIG_DISCONNECT_REQ 0x06
#define L2C_SIG_DISCONNECT_RSP 0x07
#define L2C_SIG_CONN_UPDATE_REQ 0x12
#define L2C_SIG_CONN_UPDATE_RSP 0x13
#define L2C_SIG_LE_CONNECT_REQ 0x14
#define L2C_SIG_LE_CONNECT_RSP 0x15
#define L2C_SIG_FLOW_CTRL_CREDIT 0x16
#define L2C_SIG_EN_CONNECT_REQ 0x17
#define L2C_SIG_EN_CONNECT_RSP 0x18
#define L2C_SIG_EN_RECONFIG_REQ 0x19
#define L2C_SIG_EN_RECONFIG_RSP 0x1A
L2CAP Command Rejection Codes
BLE defined Command rejection reason codes
#define L2C_REJ_NOT_UNDERSTOOD 0x0000
#define L2C_REJ_MTU_EXCEEDED 0x0001
#define L2C_REJ_INVALID_CID 0x0002
L2CAP Connection Parameter Update Result Codes
BLE defined result codes
#define L2C_CONN_PARAM_ACCEPTED 0x0000
#define L2C_CONN_PARAM_REJECTED 0x0001
L2CAP Connection Result Codes
BLE defined result codes
#define L2C_CONN_SUCCESS 0x0000
#define L2C_CONN_NONE 0x0001
#define L2C_CONN_FAIL_PSM 0x0002
#define L2C_CONN_FAIL_RES 0x0004
#define L2C_CONN_FAIL_AUTH 0x0005
#define L2C_CONN_FAIL_AUTHORIZ 0x0006
#define L2C_CONN_FAIL_KEY_SIZE 0x0007
#define L2C_CONN_FAIL_ENC 0x0008
#define L2C_CONN_FAIL_INVALID_SCID 0x0009
#define L2C_CONN_FAIL_ALLOCATED_SCID 0x000A
#define L2C_CONN_FAIL_UNACCEPT_PARAM 0x000B
#define L2C_CONN_FAIL_INVALID_PARAM 0x000C
L2CAP Interal Connection Result Codes
Proprietary codes not sent in any L2CAP packet.
#define L2C_CONN_FAIL_TIMEOUT 0xF000
L2CAP Signaling Parameter Value Ranges
#define L2C_PSM_MIN 0x0001
#define L2C_PSM_MAX 0x00FF
#define L2C_CID_DYN_MIN 0x0040
#define L2C_CID_DYN_MAX 0x007F
#define L2C_MTU_MIN 0x0017
#define L2C_MPS_MIN 0x0017
#define L2C_MPS_MAX 0xFFFD
#define L2C_CREDITS_MAX 0xFFFF
L2CAP Enhanced Connection Reconfigure Result Codes
#define L2C_RECONFIG_FAIL_MTU 0x0001
#define L2C_RECONFIG_FAIL_MPS 0x0002
#define L2C_RECONFIG_FAIL_CID 0x0003
#define L2C_RECONFIG_FAIL_PARAM 0x0004
Detailed Description
Data Structure Documentation
l2cCocReg_t
struct l2cCocReg_t
Connection oriented channel registration structure.
Data Fields
uint16_t psm
uint16_t mps
uint16_t mtu
uint16_t credits
bool_t authoriz
uint8_t secLevel
uint8_t role
l2cCocConnectInd_t
struct l2cCocConnectInd_t
Connection oriented channel connect indication structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t cid
uint16_t peerMtu
uint16_t psm
l2cCocDisconnectInd_t
struct l2cCocDisconnectInd_t
Connection oriented channel disconnect indication structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t cid
uint16_t result
l2cCocDataInd_t
struct l2cCocDataInd_t
Connection oriented channel data indication structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t cid
uint8_t * pData
uint16_t dataLen
l2cCocDataCnf_t
struct l2cCocDataCnf_t
Connection oriented channel disconnect indication structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t cid
l2cCocEnConnectInd_t
struct l2cCocEnConnectInd_t
Enhanced connection oriented channel connect indication structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t mps
uint16_t mtu
bool_t req
uint8_t cidLen
uint16_t cidList [L2C_MAX_EN_CHAN]
l2cCocEnReconfigInd_t
struct l2cCocEnReconfigInd_t
Enhanced connection oriented channel reconfiguration indication structure.
Data Fields
wsfMsgHdr_t hdr
uint16_t mps
uint16_t mtu
bool_t req
uint8_t cidLen
uint16_t cidList [L2C_MAX_EN_CHAN]
l2cCocEvt_t
union l2cCocEvt_t
Connection oriented channel event structure.
Connection oriented channel callback header parameters:
Parameters
hdr.event Callback event
hdr.param DM connection ID
hdr.status Event status (L2C_COC_DATA_CNF only)
Data Fields
wsfMsgHdr_t hdr
l2cCocConnectInd_t connectInd
l2cCocDisconnectInd_t disconnectInd
l2cCocDataInd_t dataInd
l2cCocDataCnf_t dataCnf
l2cCocEnConnectInd_t enConnectInd
l2cCocEnReconfigInd_t enReconfigInd
l2cCfg_t
struct l2cCfg_t
Configurable parameters.
Data Fields
uint16_t reqTimeout
Typedef Documentation
l2cCocAcceptCb_t
typedef uint8_t(* l2cCocAcceptCb_t) (dmConnId_t connId, uint8_t numChans)
This callback function asks clients of connection oriented channels if a given number of channels can be created on the PSM.
Parameters
connId DM connection ID.
numChans number of channels requested.
Returns
number of channels permitted by client.
l2cCocAuthorCback_t
typedef uint16_t(* l2cCocAuthorCback_t) (dmConnId_t connId, l2cCocRegId_t regId, uint16_t psm)
This callback function is used for authoriztion of connection oriented channels.
Parameters
connId DM connection ID.
regId The registration instance requiring authorization.
psm The PSM of the registration instance.
Returns
L2C_CONN_SUCCESS if authorization is successful, any other value for failure.
l2cCocCback_t
typedef void(* l2cCocCback_t) (l2cCocEvt_t *pMsg)
This callback function sends data and other events to connection oriented channels clients.
Parameters
pMsg Pointer to message structure.
Returns
None.
l2cCtrlCback_t
typedef void(* l2cCtrlCback_t) (wsfMsgHdr_t *pMsg)
This callback function sends control messages to the client.
Parameters
pMsg Pointer to message structure.
Returns
None.
l2cDataCback_t
typedef void(* l2cDataCback_t) (uint16_t handle, uint16_t len, uint8_t *pPacket)
This callback function sends a received L2CAP packet to the client.
Parameters
handle The connection handle.
len The length of the L2CAP payload data in pPacket.
pPacket A buffer containing the packet.
Returns
None.
Enumeration Type Documentation
anonymous enum
anonymous enum
COC callback events.
Enumerator
L2C_COC_CONNECT_IND
Channel connect indication.
L2C_COC_DISCONNECT_IND
Channel disconnect indication.
L2C_COC_EN_CONNECT_IND
Received enhanced connection indication.
L2C_COC_EN_RECONFIG_IND
Received enhanced reconfiguration indication.
L2C_COC_DATA_IND
Received data indication.
L2C_COC_DATA_CNF
Transmit data confirm.
Function Documentation
L2cCocConnectReq()
uint16_t L2cCocConnectReq (dmConnId_t connId, l2cCocRegId_t regId, uint16_t psm)
Initiate a connection to the given peer PSM.
Parameters
connId DM connection ID.
regId The associated registration instance.
psm Peer PSM.
Returns
Local CID or L2C_COC_CID_NONE none if failure.
References DM_CONN_ID_NONE, L2C_COC_CID_NONE, L2C_COC_ROLE_INITIATOR, WsfMsgAlloc(), WsfMsgSend(), WsfTaskLock(), and WsfTaskUnlock().
L2cCocCreditSendTest()
void L2cCocCreditSendTest (uint16_t cid, uint16_t credits)
For testing purposes only.
Parameters
cid The local channel identifier.
credits Credits to send.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
L2cCocDataReq()
void L2cCocDataReq (uint16_t cid, uint16_t len, uint8_t * pPayload)
Send an L2CAP data packet on the given connection oriented CID.
Parameters
cid The local channel identifier.
len The length of the payload data in pPacket.
pPayload Packet payload data.
Returns
None.
Parameters
cid The local channel identifier.
len The length of the payload data in pPacket.
pPacket Packet payload data.
Returns
None.
References L2C_LE_SDU_PKT_BASE_LEN, UINT16_TO_BSTREAM, WsfMsgAlloc(), WsfMsgFree(), and WsfMsgSend().
L2cCocDeregister()
void L2cCocDeregister (l2cCocRegId_t regId)
Deregister and deallocate a connection oriented channel registration instance. This function should only be called if there are no active channels using this registration instance.
Parameters
regId Registration instance ID.
Returns
None.
References WsfTaskLock(), and WsfTaskUnlock().
L2cCocDisconnectReq()
void L2cCocDisconnectReq (uint16_t cid)
Disconnect the channel for the given CID.
Parameters
cid Channel ID.
Returns
None.
References wsfMsgHdr_t::event, wsfMsgHdr_t::param, WsfMsgAlloc(), and WsfMsgSend().
L2cCocEnhancedConnectReq()
bool_t L2cCocEnhancedConnectReq (dmConnId_t connId, l2cCocRegId_t regId, uint16_t psm, uint16_t credits, uint8_t numChan)
Send a request to open enhanced credit based channels.
Parameters
connId DM connection ID.
regId The associated registration instance.
psm The protocol slave multiplexer.
credits The initial number of credits for each CID channel.
numChan The number of channels to create - L2C_MAX_EN_CHAN max.
Returns
FALSE if unable make request, else TRUE.
L2cCocEnhancedReconfigReq()
bool_t L2cCocEnhancedReconfigReq (dmConnId_t connId, uint16_t mtu, uint16_t mps, uint8_t numChan, uint16_t * pChanList)
Send a request to reconfigure enhanced credit based channels.
Parameters
connId DM connection ID.
mtu The maximum transmission unit of each source CID channel.
mps The maximum payload size on each source CID channel.
numChan The number of channels to create (1 to L2C_MAX_EN_CHAN).
pChanList A list of local CID to reconfigure (L2C_MAX_EN_CHAN channels, set unused to 0).
Returns
FALSE if unable make request, else TRUE.
Parameters
connId DM connection ID.
mtu The maximum transmission unit of each source CID channel.
mps The maximum payload size on each source CID channel.
numChan The number of channels to create (1 to L2C_MAX_EN_CHAN).
pChanList A list of local CID to Reconfig (L2C_MAX_EN_CHAN channels, set unused to 0).
Returns
FALSE if unable make request, else TRUE.
L2cCocErrorTest()
void L2cCocErrorTest (uint16_t result)
For testing purposes only.
Parameters
result Result code
Returns
None.
L2cCocInit()
void L2cCocInit (void)
Initialize L2C connection oriented channel subsystem.
Returns
None.
References DM_CLIENT_ID_L2C, and DmConnRegister().
L2cCocRegister()
l2cCocRegId_t L2cCocRegister (l2cCocCback_t cback, l2cCocReg_t * pReg)
Register to use a connection oriented channel, as either a channel acceptor, initiator, or both. If registering as channel acceptor then the PSM is specified. After registering a connection can be established by the client using this registration instance.
Parameters
cback Client callback function.
pReg Registration parameter structure.
Returns
Registration instance ID or L2C_COC_REG_ID_NONE if registration failed.
Register to use a connection oriented channel, as either a channel acceptor, initiator, or both. If registering as channel acceptor then the PSM is specified. After registering a connection can be established by the client using this registration instance.
Parameters
cback Client callback function.
pReg Registration parameter structure.
Returns
Registration instance ID or L2C_COC_REG_ID_NONE if registration failed.
References L2C_COC_REG_ID_NONE, WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
L2cCocSetAcceptCback()
void L2cCocSetAcceptCback (l2cCocRegId_t regId, l2cCocAcceptCb_t cback)
Set the channel accept callback.
Parameters
regId Registration instance ID.
cback Client callback function.
Returns
None.
References WSF_ASSERT, WsfTaskLock(), and WsfTaskUnlock().
L2cDataReq()
void L2cDataReq (uint16_t cid, uint16_t handle, uint16_t len, uint8_t * pPacket)
Send an L2CAP data packet on the given CID.
Parameters
cid The channel identifier.
handle The connection handle. The client receives this handle from DM.
len The length of the payload data in pPacket.
pL2cPacket A buffer containing the packet.
Returns
None.
Parameters
cid The channel identifier.
handle The connection handle. The client receives this handle from DM.
len The length of the payload data in pPacket.
pPacket A buffer containing the packet.
Returns
None.
References HciSendAclData(), L2C_HDR_LEN, and UINT16_TO_BSTREAM.
L2cDmConnUpdateReq()
void L2cDmConnUpdateReq (uint16_t handle, hciConnSpec_t * pConnSpec)
For internal use only. This function is called by DM to send an L2CAP connection update request.
Parameters
handle The connection handle.
pConnSpec Pointer to the connection specification structure.
Returns
None.
For internal use only. This function is called by DM to send an L2CAP connection update request.
Parameters
handle The connection handle.
pConnSpec Pointer to the connection specification structure.
Returns
None.
References hciConnSpec_t::connIntervalMax, hciConnSpec_t::connIntervalMin, hciConnSpec_t::connLatency, DM_CONN_ID_NONE, DmConnIdByHandle(), L2C_CID_LE_SIGNALING, L2C_PAYLOAD_START, L2C_SIG_CONN_UPDATE_REQ, L2C_SIG_CONN_UPDATE_REQ_LEN, L2C_SIG_HDR_LEN, L2C_SIG_PKT_BASE_LEN, L2cDataReq(), hciConnSpec_t::supTimeout, UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, and WsfTimerStartSec().
L2cDmConnUpdateRsp()
void L2cDmConnUpdateRsp (uint8_t identifier, uint16_t handle, uint16_t result)
For internal use only. This function is called by DM to send an L2CAP connection update response.
Parameters
identifier Identifier value previously passed from L2C to DM.
handle The connection handle.
result Connection update response result.
Returns
None.
For internal use only. This function is called by DM to send an L2CAP connection update response.
Parameters
identifier Identifier value previously passed from L2C to DM.
handle The connection handle.
result Connection update response result.
Returns
None.
References L2C_CID_LE_SIGNALING, L2C_PAYLOAD_START, L2C_SIG_CONN_UPDATE_RSP, L2C_SIG_CONN_UPDATE_RSP_LEN, L2C_SIG_HDR_LEN, L2C_SIG_PKT_BASE_LEN, L2cDataReq(), UINT16_TO_BSTREAM, and UINT8_TO_BSTREAM.
L2cDmSigReq()
void L2cDmSigReq (uint16_t handle, uint8_t code, uint16_t len, uint8_t * pParam)
Build and send a signaling packet.
Parameters
handle The connection handle.
code Type of command.
len Length of the parameter.
pParam parameters of command to send.
Returns
None.
Parameters
handle The connection handle.
code Type of command.
len Length of pParam.
pParam parameters of command to send.
Returns
None.
References DM_CONN_ID_NONE, DmConnIdByHandle(), L2C_CID_LE_SIGNALING, L2C_PAYLOAD_START, L2C_SIG_HDR_LEN, L2C_SIG_PKT_BASE_LEN, L2cDataReq(), UINT16_TO_BSTREAM, UINT8_TO_BSTREAM, and WsfTimerStartSec().
L2cInit()
void L2cInit (void)
Initialize L2C subsystem.
Returns
None.
References HciAclRegister().
L2cMasterInit()
void L2cMasterInit (void)
Initialize L2C for operation as a Bluetooth LE master.
Returns
None.
L2cRegister()
void L2cRegister (uint16_t cid, l2cDataCback_t dataCback, l2cCtrlCback_t ctrlCback)
called by the L2C client, such as ATT or SMP, to register for the given CID.
Parameters
cid channel identifier.
dataCback Callback function for L2CAP data received for this CID.
ctrlCback Callback function for control events for this CID.
Returns
None.
References L2C_CID_ATT, L2C_CID_SMP, and WSF_ASSERT.
L2cSlaveInit()
void L2cSlaveInit (void)
Initialize L2C for operation as a Bluetooth LE slave.
Returns
None.
References DM_CONN_MAX, and L2C_SIGNAL_ID_INVALID.