Cordio: WSF_TIMER_API
WSF_TIMER_API
Data Structures
struct wsfTimer_t
Macros
#define WSF_MS_PER_TICK 10
Typedefs
typedef uint32_t wsfTimerTicks_t
Functions
void WsfTimerInit (void)
void WsfTimerStartSec (wsfTimer_t *pTimer, wsfTimerTicks_t sec)
void WsfTimerStartMs (wsfTimer_t *pTimer, wsfTimerTicks_t ms)
void WsfTimerStop (wsfTimer_t *pTimer)
void WsfTimerUpdate (wsfTimerTicks_t ticks)
wsfTimer_t * WsfTimerServiceExpired (wsfTaskId_t taskId)
void WsfTimerSleep (void)
void WsfTimerSleepUpdate (void)
Detailed Description
Data Structure Documentation
wsfTimer_t
struct wsfTimer_t
Timer structure.
Data Fields
struct wsfTimer_tag * pNext
wsfMsgHdr_t msg
wsfTimerTicks_t ticks
wsfHandlerId_t handlerId
bool_t isStarted
Function Documentation
WsfTimerServiceExpired()
wsfTimer_t* WsfTimerServiceExpired (wsfTaskId_t taskId)
Service expired timers for the given task. This function is typically called only WSF OS porting code.
Parameters
taskId OS Task ID of task servicing timers.
Returns
Pointer to next expired timer or NULL if there are no expired timers.
Service expired timers for the given task. This function is typically called only WSF OS porting code.
Parameters
taskId Task ID.
Returns
Pointer to timer or NULL.
References wsfTimer_t::isStarted, wsfQueue_t::pHead, wsfTimer_t::ticks, WsfQueueRemove(), and WsfTaskLock().
WsfTimerSleep()
void WsfTimerSleep (void)
Check if there is an active timer and if there is enough time to go to sleep.
Check if there is an active timer and if there is enough time to go to sleep.
References PAL_LED_ID_CPU_ACTIVE, PAL_MAX_RTC_COUNTER_VAL, PalEnterCs(), PalExitCs(), PalLedOff(), PalLedOn(), PalRtcCompareSet(), PalRtcCounterGet(), PalRtcDisableCompareIrq(), PalRtcEnableCompareIrq(), PalSysIsBusy(), PalSysSleep(), and wsfOsReadyToSleep().
WsfTimerSleepUpdate()
void WsfTimerSleepUpdate (void)
Update WSF timer based on elapsed RTC ticks.
Update WSF timer based on elapsed RTC ticks.
References PAL_RTC_TICKS_PER_SEC, PalRtcCounterGet(), and WsfTimerUpdate().
WsfTimerStartMs()
void WsfTimerStartMs (wsfTimer_t * pTimer, wsfTimerTicks_t ms)
Start a timer in units of milliseconds.
Parameters
pTimer Pointer to timer.
ms Milliseconds until expiration.
References wsfTimer_t::isStarted, wsfTimer_t::ticks, WsfBufAlloc(), WsfCsEnter(), and WsfCsExit().
WsfTimerStartSec()
void WsfTimerStartSec (wsfTimer_t * pTimer, wsfTimerTicks_t sec)
Start a timer in units of seconds. Before this function is called parameter pTimer->handlerId must be set to the event handler for this timer and parameter pTimer->msg must be set to any application-defined timer event parameters.
Parameters
pTimer Pointer to timer.
sec Seconds until expiration.
Start a timer in units of seconds. Before this function is called parameter pTimer->handlerId must be set to the event handler for this timer and parameter pTimer->msg must be set to any application-defined timer event parameters.
Parameters
pTimer Pointer to timer.
sec Seconds until expiration.
References WsfTimerStartMs().
WsfTimerStop()
void WsfTimerStop (wsfTimer_t * pTimer)
Stop a timer.
Parameters
pTimer Pointer to timer.
References wsfTimer_t::isStarted, WsfCsEnter(), WsfTaskLock(), and WsfTaskUnlock().
WsfTimerUpdate()
void WsfTimerUpdate (wsfTimerTicks_t ticks)
Update the timer service with the number of elapsed ticks. This function is typically called only from timer porting code.
Parameters
ticks Number of ticks since last update.
Update the timer service with the number of elapsed ticks. This function is typically called only from timer porting code.
Parameters
ticks Number of ticks since last update.
References wsfTimer_t::handlerId, wsfQueue_t::pHead, wsfTimer_t::pNext, wsfTimer_t::ticks, WSF_TIMER_EVENT, WsfTaskLock(), WsfTaskSetReady(), and WsfTaskUnlock().