Cordio: BLOOD_PRESSURE_PROFILE
BLOOD_PRESSURE_PROFILE
Data Structures
struct blpsCfg_t
Enumerations
enum
Functions
void BlpcBpsDiscover (dmConnId_t connId, uint16_t *pHdlList)
uint8_t BlpcBpsValueUpdate (uint16_t *pHdlList, attEvt_t *pMsg)
void BlpsInit (wsfHandlerId_t handlerId, blpsCfg_t *pCfg)
void BlpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t icpCccIdx)
void BlpsMeasStop (void)
void BlpsMeasComplete (dmConnId_t connId, uint8_t bpmCccIdx)
void BlpsProcMsg (wsfMsgHdr_t *pMsg)
void BlpsSetBpmFlags (uint8_t flags)
void BlpsSetIcpFlags (uint8_t flags)
Detailed Description
Data Structure Documentation
blpsCfg_t
struct blpsCfg_t
Configurable parameters.
Data Fields
wsfTimerTicks_t period
Enumeration Type Documentation
anonymous enum
anonymous enum
Blood Pressure service enumeration of handle indexes of characteristics to be discovered.
Enumerator
BLPC_BPS_BPM_HDL_IDX
Blood pressure measurement.
BLPC_BPS_BPM_CCC_HDL_IDX
Blood pressure measurement CCC descriptor.
BLPC_BPS_ICP_HDL_IDX
Intermediate cuff pressure.
BLPC_BPS_ICP_CCC_HDL_IDX
Intermediate cuff pressure CCC descriptor.
BLPC_BPS_BPF_HDL_IDX
Blood pressure feature.
BLPC_BPS_HDL_LIST_LEN
Handle list length.
Function Documentation
BlpcBpsDiscover()
void BlpcBpsDiscover (dmConnId_t connId, uint16_t * pHdlList)
Perform service and characteristic discovery for Blood Pressure service. Parameter pHdlList must point to an array of length BLPC_BPS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
Perform service and characteristic discovery for Blood Pressure service. Parameter pHdlList must point to an array of length BLPC_BPS_HDL_LIST_LEN. If discovery is successful the handles of discovered characteristics and descriptors will be set in pHdlList.
Parameters
connId Connection identifier.
pHdlList Characteristic handle list.
Returns
None.
References AppDiscFindService(), ATT_16_UUID_LEN, attBpsSvcUuid, and BLPC_BPS_HDL_LIST_LEN.
BlpcBpsValueUpdate()
uint8_t BlpcBpsValueUpdate (uint16_t * pHdlList, attEvt_t * pMsg)
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length BLPC_BPS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
Process a value received in an ATT read response, notification, or indication message. Parameter pHdlList must point to an array of length BLPC_BPS_HDL_LIST_LEN. If the ATT handle of the message matches a handle in the handle list the value is processed, otherwise it is ignored.
Parameters
pHdlList Characteristic handle list.
pMsg ATT callback message.
Returns
ATT_SUCCESS if handle is found, ATT_ERR_NOT_FOUND otherwise.
References ATT_ERR_NOT_FOUND, ATT_SUCCESS, BLPC_BPS_BPF_HDL_IDX, BLPC_BPS_BPM_HDL_IDX, BLPC_BPS_ICP_HDL_IDX, BSTREAM_TO_UINT16, attEvt_t::handle, attEvt_t::pValue, and attEvt_t::valueLen.
BlpsInit()
void BlpsInit (wsfHandlerId_t handlerId, blpsCfg_t * pCfg)
Initialize the Blood Pressure profile sensor.
Parameters
handlerId WSF handler ID of the application using this service.
pCfg Configurable parameters.
Returns
None.
Parameters
handerId WSF handler ID of the application using this service.
pCfg Configurable parameters.
Returns
None.
BlpsMeasComplete()
void BlpsMeasComplete (dmConnId_t connId, uint8_t bpmCccIdx)
Blood pressure measurement complete.
Parameters
connId DM connection identifier.
bpmCccIdx Index of blood pressure measurement CCC descriptor in CCC descriptor handle table.
Returns
None.
References AppHwBpmRead(), ATT_DEFAULT_PAYLOAD_LEN, AttsCccEnabled(), and BlpsMeasStop().
BlpsMeasStart()
void BlpsMeasStart (dmConnId_t connId, uint8_t timerEvt, uint8_t icpCccIdx)
Start periodic blood pressure measurement. This function starts a timer to perform periodic measurements.
Parameters
connId DM connection identifier.
timerEvt WSF event designated by the application for the timer.
icpCccIdx Index of intermediate cuff pressure CCC descriptor in CCC descriptor handle table.
Returns
None.
References WsfTimerStartMs().
BlpsMeasStop()
void BlpsMeasStop (void)
Stop periodic blood pressure measurement.
Returns
None.
References WsfTimerStop().
BlpsProcMsg()
void BlpsProcMsg (wsfMsgHdr_t * pMsg)
This function is called by the application when the periodic measurement timer expires.
Parameters
pMsg Event message.
Returns
None.
References AppHwBpmRead(), ATT_DEFAULT_PAYLOAD_LEN, AttsCccEnabled(), wsfMsgHdr_t::param, and wsfMsgHdr_t::status.
BlpsSetBpmFlags()
void BlpsSetBpmFlags (uint8_t flags)
Set the blood pressure measurement flags.
Parameters
flags Blood pressure measurement flags.
Returns
None.
BlpsSetIcpFlags()
void BlpsSetIcpFlags (uint8_t flags)
Set the intermediate cuff pressure flags.
Parameters
flags Intermediate cuff pressure flags.
Returns
None.