Cordio: Mesh Health Client Model API
Mesh Health Client Model API
Data Structures
struct meshHtClFaultStatus_t
struct meshHtClAttentionStatusEvt_t
struct meshHtClPeriodStatusEvt_t
struct meshHtClFaultStatusEvt_t
union meshHtClEvt_t
Macros
#define MESH_HT_CL_NUM_RECVD_OPCODES 4
Typedefs
typedef void(* meshHtClCback_t) (const meshHtClEvt_t *pEvt)
Enumerations
enum meshHtClStatusValues
Functions
void MeshHtClHandlerInit (wsfHandlerId_t handlerId)
void MeshHtClInit (void)
void MeshHtClHandler (wsfMsgHdr_t *pMsg)
void MeshHtClRegister (mmdlEventCback_t evtCback)
void MeshHtClFaultGet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, uint16_t companyId)
void MeshHtClFaultClear (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, uint16_t companyId, bool_t ackRequired)
void MeshHtClFaultTest (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, meshHtMdlTestId_t testId, uint16_t companyId, bool_t ackRequired)
void MeshHtClPeriodGet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl)
void MeshHtClPeriodSet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, meshHtPeriod_t periodState, bool_t ackRequired)
void MeshHtClAttentionGet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl)
void MeshHtClAttentionSet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, meshHtAttTimer_t attTimerState, bool_t ackRequired)
Variables
wsfHandlerId_t meshHtClHandlerId
const meshMsgOpcode_t meshHtClRcvdOpcodes []
Detailed Description
Data Structure Documentation
meshHtClFaultStatus_t
struct meshHtClFaultStatus_t
Mesh Health Client Health Fault Status event parameter.
Data Fields
meshHtMdlTestId_t testId
uint16_t companyId
meshHtFaultId_t * pFaultIdArray
uint8_t faultIdArrayLen
Field Documentation
companyId
uint16_t companyId
Company identifier 16-bit
faultIdArrayLen
uint8_t faultIdArrayLen
Length of the array referenced by pFaultIdArray
pFaultIdArray
meshHtFaultId_t* pFaultIdArray
Pointer to a fault identifier array
testId
meshHtMdlTestId_t testId
Test identifier (8 bit)
meshHtClAttentionStatusEvt_t
struct meshHtClAttentionStatusEvt_t
Data structure for MESH_HT_CL_ATTENTION_STATUS_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
meshAddress_t htSrElemAddr
meshHtAttTimer_t attTimerState
Field Documentation
attTimerState
meshHtAttTimer_t attTimerState
Attention Timer state.
elemId
meshElementId_t elemId
Current element Identifier
hdr
wsfMsgHdr_t hdr
Header
htSrElemAddr
meshAddress_t htSrElemAddr
Address of the remote element containing an instance of Health Server
meshHtClPeriodStatusEvt_t
struct meshHtClPeriodStatusEvt_t
Data structure for MESH_HT_CL_PERIOD_STATUS_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
meshAddress_t htSrElemAddr
meshHtPeriod_t periodDivisor
Field Documentation
elemId
meshElementId_t elemId
Current element Identifier
hdr
wsfMsgHdr_t hdr
Header
htSrElemAddr
meshAddress_t htSrElemAddr
Address of the remote element containing an instance of Health Server
periodDivisor
meshHtPeriod_t periodDivisor
Fast Period Divisor
meshHtClFaultStatusEvt_t
struct meshHtClFaultStatusEvt_t
Data structure for MESH_HT_CL_CURRENT_STATUS_EVENT and MESH_HT_CL_FAULT_STATUS_EVENT.
Data Fields
wsfMsgHdr_t hdr
meshElementId_t elemId
meshAddress_t htSrElemAddr
meshHtClFaultStatus_t healthStatus
Field Documentation
elemId
meshElementId_t elemId
Current element Identifier
hdr
wsfMsgHdr_t hdr
Header
healthStatus
meshHtClFaultStatus_t healthStatus
Current health Status
htSrElemAddr
meshAddress_t htSrElemAddr
Address of the remote element containing an instance of Health Server
meshHtClEvt_t
union meshHtClEvt_t
Union of all Health Client model events.
Data Fields
wsfMsgHdr_t hdr
meshHtClFaultStatusEvt_t currentStatusEvt
meshHtClFaultStatusEvt_t faultStatusEvt
meshHtClPeriodStatusEvt_t periodStatusEvt
meshHtClAttentionStatusEvt_t attentionStatusEvt
Field Documentation
attentionStatusEvt
meshHtClAttentionStatusEvt_t attentionStatusEvt
Attention status event. Used for MESH_HT_CL_ATTENTION_STATUS_EVENT.
currentStatusEvt
meshHtClFaultStatusEvt_t currentStatusEvt
Current status event. Used for MESH_HT_CL_CURRENT_STATUS_EVENT.
faultStatusEvt
meshHtClFaultStatusEvt_t faultStatusEvt
Fault status event. Used for MESH_HT_CL_FAULT_STATUS_EVENT.
hdr
wsfMsgHdr_t hdr
Common header
periodStatusEvt
meshHtClPeriodStatusEvt_t periodStatusEvt
Period status event. Used for MESH_HT_CL_PERIOD_STATUS_EVENT.
Typedef Documentation
meshHtClCback_t
typedef void(* meshHtClCback_t) (const meshHtClEvt_t *pEvt)
Procedure callback triggered after a Health Client model procedure is completed or an unrequested Health Current Status message is received by a Health Server model.
Parameters
[in] pEvt Pointer to structure containing the Health Client Model Event.
Returns
None.
See also
meshHtClEvent_t
Enumeration Type Documentation
meshHtClStatusValues
enum meshHtClStatusValues
Mesh Health Client Status values.
Enumerator
MESH_HT_CL_SUCCESS
Procedure returned with success
Function Documentation
MeshHtClAttentionGet()
void MeshHtClAttentionGet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl)
Gets the current Attention Timer state of an element.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
Returns
None.
References MESH_HT_ATTENTION_GET_OPCODE, MeshSendMessage(), meshMsgInfo_t::modelId, and modelId_t::sigModelId.
MeshHtClAttentionSet()
void MeshHtClAttentionSet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, meshHtAttTimer_t attTimerState, bool_t ackRequired)
Sets the current Attention Timer state of an element.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
[in] attTimerState Attention timer state.
[in] ackRequired TRUE if request type is acknowledged.
Returns
None.
MeshHtClFaultClear()
void MeshHtClFaultClear (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, uint16_t companyId, bool_t ackRequired)
Clears the current Registered Fault state identified by the company ID.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
[in] companyId 16-bit Bluetooth assigned Company Identifier.
[in] ackRequired TRUE if request type is acknowledged.
Returns
None.
MeshHtClFaultGet()
void MeshHtClFaultGet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, uint16_t companyId)
Gets the current Registered Fault state identified by the company ID.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
[in] companyId 16-bit Bluetooth assigned Company Identifier.
Returns
None.
References MESH_HT_FAULT_GET_OPCODE, MeshSendMessage(), meshMsgInfo_t::modelId, modelId_t::sigModelId, and UINT16_TO_BUF.
MeshHtClFaultTest()
void MeshHtClFaultTest (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, meshHtMdlTestId_t testId, uint16_t companyId, bool_t ackRequired)
Invokes a self-test procedure on an element implementing a Health Server.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
[in] testId Identifier of a specific test to be performed.
[in] companyId 16-bit Bluetooth assigned Company Identifier.
[in] ackRequired TRUE if request type is acknowledged.
Returns
None.
MeshHtClHandler()
void MeshHtClHandler (wsfMsgHdr_t * pMsg)
WSF message handler for Health Client model.
Parameters
[in] pMsg WSF message.
Returns
None.
References wsfMsgHdr_t::event, MESH_MODEL_EVT_MSG_RECV, MESH_OPCODE_SIZE, and meshModelMsgRecvEvt_t::opCode.
MeshHtClHandlerInit()
void MeshHtClHandlerInit (wsfHandlerId_t handlerId)
Initializes the Health Client Handler.
Parameters
[in] handlerId WSF handler ID of the model.
Returns
None.
References meshHtClHandlerId.
MeshHtClInit()
void MeshHtClInit (void)
Initializes the Health Client model.
Returns
None.
MeshHtClPeriodGet()
void MeshHtClPeriodGet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl)
Gets the current Health Period state of an element.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
Returns
None.
References MESH_HT_PERIOD_GET_OPCODE, MeshSendMessage(), meshMsgInfo_t::modelId, and modelId_t::sigModelId.
MeshHtClPeriodSet()
void MeshHtClPeriodSet (meshElementId_t elementId, meshAddress_t htSrElemAddr, uint16_t appKeyIndex, uint8_t ttl, meshHtPeriod_t periodState, bool_t ackRequired)
Sets the current Health Period state of an element.
Parameters
[in] elementId Local element identifier for a Health Client model instance.
[in] htSrElemAddr Address of the element containing an instance of Health Server model.
[in] appKeyIndex AppKey Index.
[in] ttl TTL or MESH_USE_DEFAULT_TTL.
[in] periodState Health period divisor state.
[in] ackRequired TRUE if request type is acknowledged.
Returns
None.
MeshHtClRegister()
void MeshHtClRegister (mmdlEventCback_t recvCback)
Registers the callback that is triggered when a message is received for this model.
Parameters
[in] evtCback Callback registered by the upper layer to receive messages from the model.
Returns
None.
Variable Documentation
meshHtClHandlerId
wsfHandlerId_t meshHtClHandlerId
WSF handler ID for Health Client.
WSF handler id
meshHtClRcvdOpcodes
const meshMsgOpcode_t meshHtClRcvdOpcodes[]
Supported opcodes.
Supported opcodes