Cordio: Advertising Bearer Adaptation Layer API
Advertising Bearer Adaptation Layer API
Data Structures
struct advBearerCfg_t
Macros
#define ADV_BEARER_INVALID_IF_ID 0xFF
Functions
void AdvBearerInit (advBearerCfg_t *pAdvBearerCfg)
void AdvBearerRegisterIf (meshAdvIfId_t advIfId)
void AdvBearerDeregisterIf (void)
void AdvBearerStart (void)
bool_t AdvBearerStop (void)
void AdvBearerSendPacket (meshAdvPduSendEvt_t *pEvt)
void AdvBearerProcDmMsg (dmEvt_t *pMsg)
Detailed Description
Data Structure Documentation
advBearerCfg_t
struct advBearerCfg_t
Configurable parameters for Mesh Advertising Bearer.
Data Fields
uint16_t scanInterval
uint16_t scanWindow
uint8_t discMode
uint8_t scanType
uint16_t advDuration
uint16_t intervalMin
uint16_t intervalMax
Field Documentation
advDuration
uint16_t advDuration
The advertising duration in ms
discMode
uint8_t discMode
The GAP discovery mode (general, limited, or none)
intervalMax
uint16_t intervalMax
Maximum advertising interval, in 0.625 ms units
intervalMin
uint16_t intervalMin
Minimum advertising interval, in 0.625 ms units
scanInterval
uint16_t scanInterval
The scan interval, in 0.625 ms units
scanType
uint8_t scanType
The scan type (active or passive)
scanWindow
uint16_t scanWindow
The scan window, in 0.625 ms units. Must be less than or equal to scan interval.
Function Documentation
AdvBearerDeregisterIf()
void AdvBearerDeregisterIf (void)
Deregister Advertising Bearer for the Mesh node.
Returns
None.
References ADV_BEARER_INVALID_IF_ID.
AdvBearerInit()
void AdvBearerInit (advBearerCfg_t * pAdvBearerCfg)
Initialize Advertising Bearer for the Mesh node.
Parameters
[in] pAdvBearerCfg Configuration pointer for Mesh Advertising Bearer.
Returns
None.
References ADV_BEARER_INVALID_IF_ID.
AdvBearerProcDmMsg()
void AdvBearerProcDmMsg (dmEvt_t * pMsg)
Process DM messages for a Mesh node. This function should be called from the application's event handler.
Parameters
[in] pMsg Pointer to DM callback event message.
Returns
None.
References ADV_BEARER_INVALID_IF_ID, DM_ADV_SET_START_IND, DM_ADV_SET_STOP_IND, DM_ADV_START_IND, DM_ADV_STOP_IND, DM_EXT_SCAN_REPORT_IND, DM_EXT_SCAN_START_IND, DM_EXT_SCAN_STOP_IND, DM_RESET_CMPL_IND, DM_SCAN_REPORT_IND, DM_SCAN_START_IND, DM_SCAN_STOP_IND, DmFindAdType(), wsfMsgHdr_t::event, hciLeAdvReportEvt_t::eventType, hciLeExtAdvReportEvt_t::eventType, dmEvt_t::extScanReport, HCI_ERR_ADV_TIMEOUT, HCI_ERR_LIMIT_REACHED, HCI_SUCCESS, dmEvt_t::hdr, hciLeAdvReportEvt_t::len, hciLeExtAdvReportEvt_t::len, MESH_AD_TYPE_BEACON, MESH_AD_TYPE_PACKET, MESH_AD_TYPE_PB, MeshProcessAdvPdu(), MeshSignalAdvIfRdy(), hciLeAdvReportEvt_t::pData, hciLeExtAdvReportEvt_t::pData, dmEvt_t::scanReport, wsfMsgHdr_t::status, and WSF_ASSERT.
AdvBearerRegisterIf()
void AdvBearerRegisterIf (meshAdvIfId_t advIfId)
Register Advertising Bearer for the Mesh node.
Parameters
advIfId Advertising interface ID.
Returns
None.
None.
References ADV_BEARER_INVALID_IF_ID, and WSF_ASSERT.
AdvBearerSendPacket()
void AdvBearerSendPacket (meshAdvPduSendEvt_t * pEvt)
Send Mesh message on the Advertising Bearer.
Parameters
pEvt Advertising interface PDU to send.
Returns
None.
None.
References meshAdvPduSendEvt_t::adType, meshAdvPduSendEvt_t::advPduLen, HCI_ADV_DATA_LEN, and meshAdvPduSendEvt_t::pAdvPdu.
AdvBearerStart()
void AdvBearerStart (void)
Starts advertising bearer.
Returns
None.
Starts advertising bearer.
Returns
None.
References BDA_ADDR_LEN, DM_ADV_HANDLE_DEFAULT, DM_ADV_NONCONN_UNDIRECT, DmAdvConfig(), DmAdvSetInterval(), and HCI_ADDR_TYPE_PUBLIC.
AdvBearerStop()
bool_t AdvBearerStop (void)
Stops current advertising bearer.
Returns
Always TRUE.
Stops current advertising bearer.
Returns
Always TRUE.