/**
 * This file is a header override for arm_math.h, we only need a couple things from it. Add more here if necessary.
 */

#ifndef ARM_MATH_HEADER_OVERRIDE_H__
#define ARM_MATH_HEADER_OVERRIDE_H__

#include <stdint.h>

#define __SIMD32(addr) (*(int32_t **)&(addr))

typedef int64_t q63_t;

typedef int32_t q31_t;

typedef int16_t q15_t;

/**
 * @brief Error status returned by some functions in the library.
 */
typedef enum
{
    ARM_MATH_SUCCESS = 0,         /**< No error */
    ARM_MATH_ARGUMENT_ERROR = -1, /**< One or more arguments are incorrect */
    ARM_MATH_LENGTH_ERROR = -2,   /**< Length of data buffer is incorrect */
    ARM_MATH_SIZE_MISMATCH = -3,  /**< Size of matrices is not compatible with the operation. */
    ARM_MATH_NANINF = -4,         /**< Not-a-number (NaN) or infinity is generated */
    ARM_MATH_SINGULAR = -5,       /**< Generated by matrix inversion if the input matrix is singular and cannot be inverted. */
    ARM_MATH_TEST_FAILURE = -6    /**< Test Failed  */
} arm_status;

#endif
